<!-- Panel para asignar los filtros para generar los informes -->
<!-- class="form form-control input-sm" -->
  <!-- style="opacity: 0;" -->
  <div id="mensaje"></div>
<!--   <div class="panel">
    <div class="panel-heading paneles text-center panel-default" style="font-weight: bold;">Filtros Trazabilidad de
      Procesos</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
          <a id="btn_crea" href="#" data-toggle="modal" class="cell-detail  hint--top btn btn-primary btn-xs"
            data-hint="" data-target="#crear_trazabilidad"><i class="fas fa-plus-square"></i> Nueva Trazabilidad</a>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <div class="form-group">
            <label for="fecha_inicial" style="font-weight: bold;">Fecha Inicial</label>
            <input type="date" name="fecha_inicial" id="fecha_inicial" class="form-control input-xs" value="<?php date("
              Y-m-d");?>">
          </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
          <label for="fecha_final" style="font-weight: bold;">Fecha Final</label>
          <input type="date" name="fecha_final" id="fecha_final" class="form-control input-xs">
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>
      </div>
    </div>
  </div> -->

  <div class="row">
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    <div class="form-group form-group-sm">
      <div class="input-group">
        <div class="input-group-addon" style="font-weight: bold;font-size: 13px;">Fecha Inicial</div>
        <input type="date" name="fecha_inicial" id="fecha_inicial" class="form-control input-xs">
      </div>
    </div>
  </div>
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    <div class="form-group form-group-sm">
      <div class="input-group">
        <div class="input-group-addon" style="font-weight: bold;font-size: 13px;">Fecha Final</div>
        <input type="date" name="fecha_final" id="fecha_final" class="form-control input-xs">
      </div>
    </div>
  </div>
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
    <div class="form-group form-group-sm">
      <div class="input-group">
        <div class="input-group-addon" style="font-weight: bold;font-size: 13px;">Buscar</div>
        <input type="text" name="buscar" id="buscar" class="form-control input-xs">
      </div>
    </div>
  </div>
</div>

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div id="esconder">
        <div class="row">
          <div class="col-sm-12">
            <div class="table-responsive noSwipe">
              <table id="table1" class="table table-striped table-hover table-fw-widget table-condensed">
                <thead style="background-color:#332D2D;color:#fff;text-align:center;">
                  <tr>
                    <th >#</th>
                    <th>N° Pedido</th>
                    <th>Cliente</th>
                    <th>Fecha</th>
                    <th>Compartido por</th>
                    <th>Estado</th>
                    <!-- <th>Acción</th> -->
                  </tr>
                </thead>
                <tbody id="body_pedidos_compartidos">
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
	  	 <script src=<?php echo BASE_URL; ?>views/pedidos/js/compartidos.js type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>
	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
	    </script>