<link href="https://cdn.datatables.net/v/dt/jq-3.7.0/jszip-3.10.1/dt-2.1.8/b-3.2.0/b-colvis-3.2.0/b-html5-3.2.0/b-print-3.2.0/datatables.min.css" rel="stylesheet">
<div class="nexos-content">
  <div class="row" style="margin:-25px -39px -20px -39px;">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div id="mensaje"></div>
      <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;font-weight: 300;">
        <tbody>
          <tr>
            <td class="celda_titulo2 text-left" style="margin:25px;font-weight: 300;">
              Modulo de Pedidos Trazabilidad
            </td>
            <td class="text-right">
              <input type="hidden" id="tipo_usuario_perfil" value="<?php echo $_SESSION["usuario"]["tipo_perfil"]; ?>">
              <a id="btn_crea" href="#" data-toggle="modal" class="cell-detail  hint--top btn btn-primary btn-xs" data-hint="" data-target="#crear_trazabilidad"><i class="fas fa-plus-square"></i> Nueva Trazabilidad</a>
            </td>
          </tr>
        </tbody>
      </table>

      <!-- <div class="row"> </div> -->
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div id="esconder">
          <div class="row">
            <!-- <div class="col-sm-12"></div> -->
            <div class="table-responsive noSwipe">
              <table cellpadding="0" cellspacing="0" id="table1" class="table table-condensed table-hover" style="font-size: 10pt;border-top: #FFFFFF 1px solid;">
                <thead style="background-color:#332D2D;color:#fff;">
                  <tr>
                    <th style="color: white;width: auto; white-space: nowrap;color:#FFFFFF;">#</th>
                    <th style="color: white;width: auto; white-space: nowrap;color:#FFFFFF;">N° Pedido</th>
                    <th style="color: white;width: auto; white-space: nowrap;color:#FFFFFF;">N° Solicitud Servicio</th>
                    <th style="color: white;width: auto; white-space: nowrap;color:#FFFFFF;">Cliente</th>
                    <th style="color: white;width: auto; white-space: nowrap;color:#FFFFFF;">Fecha</th>
                    <th style="color: white;width: auto; white-space: nowrap;color:#FFFFFF;">Estado</th>
                    <th style="color: white;width: auto; white-space: nowrap;color:#FFFFFF;">Acción</th>
                  </tr>
                </thead>
                <tbody id="body_pedidos"></tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="crear_trazabilidad" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:left;height: 50px;padding: 19px;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #ffffff;"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><i class="far fa-calendar-alt"></i> Crear Trazabilidad</h4>
      </div>
      <div class="modal-body" style="padding: 5px 5px 5px;">
        <div id="notificaciones"></div>
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <label class="custom-control custom-radio custom-control-inline" style="font-weight: bold;margin-left: 5px;text-align: center;">
              <input type="radio" id="radio_nuevo" value="Nueva" name="tipo_operacion" class="tipo_pedido" style="transform: scale(2);margin-right: 5px;"> <span class="custom-control-label custom-control-color">
                Nueva</span>
            </label>
            <label class="custom-control custom-radio custom-control-inline" style="align-items: center;font-weight: bold;margin-left: 10px;">
              <input type="radio" id="radio_plantilla" value="Plantilla" name="tipo_operacion" class="tipo_pedido" style="transform: scale(2);margin-right: 5px;"> <span class="custom-control-label custom-control-color">
                Plantilla</span>
            </label>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="form-group" style="display: none;" id="select_plantilla">
              <select class="form-control input-xs" id="plantillas" name="plantillas">
                <option value="" selected>Seleccionar Plantilla</option>
              </select>
            </div>
          </div>

          <div id="parametros" style="display: none;">
            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
              <div class="form-group">
                <label for="clientes" style="font-weight: bold;">Seleccionar Cliente <span style="color: #DC4C64;">*</span></label>
                <select class="form-control input-xs" id="clientes" name="clientes">
                  <option value="">Seleccionar Cliente</option>
                </select>
              </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
              <div class="form-group" id="ref">
                <label for="referencia" style="font-weight: bold;">Referencia / Pedido <span style="color: #DC4C64;">*</span></label>
                <input class="form-control input-xs" type="text" id="referencia" name="referencia" oninput="verificarCampo()">
                <span id="mensaje_referencia" class="text-warning"></span>
              </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div class="form-group">
                <label for="observacion" style="font-weight: bold;">Observación</label>
                <textarea name="observacion" id="observacion" cols="30" rows="1" class="form-control input-xs"></textarea>
              </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7" style="margin-top: 5px;">
              <!-- <div class="container"></div> -->
              <h4 class="text-center" style="font-weight: bold;background-color: #332D2D;color:#FFFFFF;padding: 12px;">
                Parametros de trazabilidad</h4>
              <div class="panel-group" id="accordion">
                <!-- Contenido JS -->
              </div>
              <div class="panel-group" id="accordion_plantilla">
                <!-- Contenido JS -->
              </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5" style="margin-top: 20px;" id="lista_previsualizacion">
              <div class="panel panel-primary" style="background-color: #332D2D;color:#FFFFFF;margin-bottom:5px;">
                <h4 class="text-center" style="font-weight:bold;">Previsualizar orden actividades</h4>
              </div>
              <div class="panel-body border" style="max-height: 500px;overflow-x: hidden;overflow-y: auto ;padding: 1px 1px 1px;">
                <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div id="secondaryList"></div>
                  </div>
                </div>
              </div>
              <div class="panel-footer" style="padding: 1px 1px 1px;font-weight: bold;">
                <h4 id="posicion"></h4>
              </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="check_save_plantilla">
              <div class="checkbox">
                <label style="margin-left: 15px;font-weight: bold;font-size: 14px;">
                  <input type="checkbox" value="guardar_como_plantilla" id="check_plantilla" value="gaurdar_plantilla" style="transform: scale(1.5);margin-right: 5px;">
                  Desea gaurdar como plantilla
                </label>
              </div>
              <div class="form-group" id="nom_plantilla" style="display: none;">
                <label for="nombre_plantilla" style="font-weight: bold;">Nombre de la plantilla <span style="color: #DC4C64;">*</span></label>
                <input class="form-control input-xs" type="text" id="nombre_plantilla" name="nombre_plantilla">
                <span id="mensaje_plantilla" class="text-warning"></span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- <div class="modal-footer" style=" padding: 1px 1px 1px"> -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger btn-xs" data-dismiss="modal"><i class="fas fa-times"></i>
          Cerrar</button>
        <button type="button" class="btn btn-primary btn-xs" id="guardar_trazabilidad"><i class="far fa-save"></i>
          Guardar Trazabilidad</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="cancelar_trazabilidad" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#DC4C64;color:#fff;text-align:left;height: 50px;padding: 19px;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #ffffff;"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><i class="fa-regular fa-calendar-xmark"></i> Cancelar Trazabilidad</h4>
      </div>
      <div class="modal-body" style="padding: 5px 5px 5px;">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            <div class="form-group">

              <label for="motivo_cancelacion" style="font-weight: bold;">Referencia de Pedido<span style="color: #DC4C64;">*</span></label>
              <!-- <textarea name="motivo_cancelacion" id="motivo_cancelacion" cols="30" rows="3" class="form-control input-xs"></textarea> -->
              <input type="hidden" name="estado_cancelacion" id="estado_cancelacion">
              <input type="text" class="form-control input-xs" disabled id="referencia_pedido" name="referencia_pedido">
            </div>
          </div>

          <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <div class="form-group">
              <label for="motivo_cancelacion" style="font-weight: bold;">Numero de Pedido<span style="color: #DC4C64;">*</span></label>
              <!-- <textarea name="motivo_cancelacion" id="motivo_cancelacion" cols="30" rows="3" class="form-control input-xs"></textarea> -->
              <input type="text" class="form-control input-xs" disabled id="numdoc_pedido" name="numdoc_pedido">
            </div>
          </div>

          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="form-group">
              <label for="motivo_cancelacion" style="font-weight: bold;">Motivo de cancelación <span style="color: #DC4C64;">*</span></label>
              <textarea name="motivo_cancelacion" id="motivo_cancelacion" cols="30" rows="1" class="form-control input-xs"></textarea>
            </div>
          </div>

          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="form-group">
              <label for="responsable" style="font-weight: bold;">Responsable de cancelación <span style="color: #DC4C64;">*</span></label>
              <!-- <input type="text" class="form-control input-xs" name="responsable" id="responsable"> -->
              <select name="responsable" id="responsable" class="form-control input-xs select2"></select>
            </div>
          </div>

        </div>
      </div>
      <!-- <div class="modal-footer" style=" padding: 1px 1px 1px"> -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger btn-xs" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
        <button type="button" class="btn btn-primary btn-xs" id="cancelacion_trazabilidad"><i class="far fa-save"></i> Guardar</button>
      </div>
    </div>
  </div>
</div>

<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/js/main.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
<script src="<?php echo BASE_URL; ?>views/pedidos/js/pedidos.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
<!-- <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script> -->
<!-- Datatable -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
<script src="https://cdn.datatables.net/v/dt/jq-3.7.0/jszip-3.10.1/dt-2.1.8/b-3.2.0/b-colvis-3.2.0/datatables.min.js"></script>
<!-- <script src="https://cdn.datatables.net/v/dt/jq-3.7.0/jszip-3.10.1/dt-2.1.8/b-3.2.0/b-colvis-3.2.0/b-html5-3.2.0/b-print-3.2.0/datatables.min.js"></script> -->
<script type="text/javascript">
  $(document).ready(function() {
    $.isXs = function() {
      return window.innerWidth < 768; // Detecta si el ancho de la pantalla es menor a 768px
    };
    //initialize the javascript    // Prueba de $.isXs
    if ($.isXs()) {
      console.log("Dispositivo pequeño detectado");
    }
    App.init();
  });
</script>