<div class="container-fluid py-3">
    <!-- Variables ocultas de sesión -->
    <input type="hidden" id="ssn_id_cliente" value="<?= $_SESSION['usuario']['id_cliente'] ?>">
    <input type="hidden" id="ssn_id_usuario" value="<?= $_SESSION['usuario']['id_usuario'] ?>">
    <input type="hidden" id="ssn_nombre" value="<?= $_SESSION['usuario']['nom_usuario'] ?>">
    <input type="hidden" id="ssn_id_perfil" value="<?= $_SESSION['usuario']['id_perfil'] ?>">
    <input type="hidden" id="fecha_dia_solicitud" value="<?= date('Y-m-d') ?>">
    <input type="hidden" id="hora_dia_solicitud" value="<?= date('H:i:s') ?>">

    <div class="row">
        <div class="col-3 col-sm-12 col-md-3 col-lg-3 col-xl-3 col-xxl-3">
            <!-- Contenedor gráfica -->
            <div id="GraficaGeneralManifiestos" class="echart-pie-label-align-chart-example" style="min-height:350px"></div>

            <!-- Tabla resultados -->
            <div class="table-responsive mt-4">
                <table class='table table-bordered table-striped table-sm text-center' style=" font-size:12px;" id="tabla-general-precintos">
                    <thead class="table-primary">
                        <tr>
                            <th style='width:auto; white-space: nowrap;'>Tipo</th>
                            <th style='width:auto; white-space: nowrap;'>Cantidad</th>
                        </tr>
                    </thead>
                    <tbody id="tablaResultados"></tbody>
                </table>
            </div>

            <!-- Tabla de totales -->
            <?php if ($_SESSION['usuario']['id_perfil'] == 1): ?>
                <div class="table-responsive mt-4">
                    <table class='table table-bordered table-striped table-sm text-center' style=" font-size:12px;" id="tabla-general-precintos">
                        <thead class="table-primary">
                            <tr>
                                <th style='width:auto; white-space: nowrap;'>Agencia</th>
                                <th style='width:auto; white-space: nowrap;'>Total Manifiestos</th>
                                <th style='width:auto; white-space: nowrap;'>Total Anticipos</th>
                            </tr>
                        </thead>
                        <tbody id="tablaTotalResultados"></tbody>
                    </table>
                </div>
            <?php endif; ?>

        </div>

        <div class="col-3 col-sm-12 col-md-9 col-lg-9 col-xl-9 col-xxl-9">
            <div class="container mt-4">
                <div class="row">
                    <div class="col-md-6">
                        <div id="grafCumplidos" style="height:300px;"></div>
                    </div>
                    <div class="col-md-6">
                        <div id="grafAgencias" style="height:300px;"></div>
                    </div>
                </div>
                <div class="row mt-3"></div>
            </div>

            <div class="d-flex justify-content-between align-items-center mb-2">
                <!-- <span class="badge badge-phoenix badge-phoenix-info" style="font-size: 13px;">
                    Número de órdenes de cargue: <span class="fw-bold badge-phoenix-info contador">0</span>
                </span> -->
                <a href="JavaScript:void(0);" id="exportar_excel" class="text-decoration-none d-flex align-items-center text-success fw-bold">
                    <img src="<?= BASE_URL ?>public/img/excel_2013.png" alt="Excel" width="18px" class="me-1">
                    Exportar a Excel
                </a>
            </div>
            <!-- <div id="tablaDetalle" class="mt-3"></div> -->
            <table class='table table-bordered table-striped table-sm text-center' style=" font-size:12px;" id="tablaManifiestos" width="100%">
                <thead class="table-primary">
                    <tr>
                        <th style='width:auto; white-space: nowrap;'>Manifiesto</th>
                        <!-- <th style='width:auto; white-space: nowrap;'>Remesa</th> -->
                        <!-- <th style='width:auto; white-space: nowrap;'>Orden Cargue</th> -->
                        <th style='width:auto; white-space: nowrap;'>Placa</th>
                        <th style='width:auto; white-space: nowrap;'>Conductor</th>
                        <th style='width:auto; white-space: nowrap;'>Origen</th>
                        <th style='width:auto; white-space: nowrap;'>Destino</th>
                        <th style='width:auto; white-space: nowrap;'>Tipo Vehiculo</th>
                        <?php if ($_SESSION['usuario']['id_perfil'] != 10 || $_SESSION['usuario']['id_perfil'] != 11 || $_SESSION['usuario']['id_perfil'] != 12): ?>
                            <th style='width:auto; white-space: nowrap;'>Total</th>
                            <th style='width:auto; white-space: nowrap;'>Anticipo</th>
                        <?php endif; ?>
                        <th style='width:auto; white-space: nowrap;'>Agencia</th>
                        <th style='width:auto; white-space: nowrap;'>Fecha</th>
                        <th style='width:auto; white-space: nowrap;'>Estado</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>

        </div>
    </div>
</div>