<div class="container-fluid py-3">
    <!-- Variables ocultas de sesión -->
    <input type="hidden" id="ssn_id_cliente" value="<?= $_SESSION['usuario']['id_cliente'] ?>">
    <input type="hidden" id="ssn_id_usuario" value="<?= $_SESSION['usuario']['id_usuario'] ?>">
    <input type="hidden" id="ssn_nombre" value="<?= $_SESSION['usuario']['nom_usuario'] ?>">
    <input type="hidden" id="ssn_id_perfil" value="<?= $_SESSION['usuario']['id_perfil'] ?>">
    <input type="hidden" id="fecha_dia_solicitud" value="<?= date('Y-m-d') ?>">
    <input type="hidden" id="hora_dia_solicitud" value="<?= date('H:i:s') ?>">
    <div class="row">
        <div class="col-4 col-sm-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4">
            <!-- Contenedor gráfica -->
            <div id="IndicadoresSolicitudes" class="echart-pie-label-align-chart-example" style="min-height:350px"></div>

            <!-- Tabla resultados -->
            <div class="table-responsive mt-5">
                <table class='table table-bordered table-striped table-sm text-center' style=" font-size:12px;" id="tabla-general-precintos">
                    <thead class="table-primary">
                        <tr>
                            <th>Estado</th>
                            <th>Cantidad</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                    <tfoot>
                        <tr>
                            <th>Total</th>
                            <th id="total-general"></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        
        <div class="col-4 col-sm-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4">
            <!-- Contenedor gráfica -->
            <div id="IndicadoresSolicitudesAgencia" class="echart-pie-label-align-chart-example" style="min-height:350px"></div>

            <!-- Tabla resultados -->
            <div class="table-responsive mt-5">
                <table class='table table-bordered table-striped table-sm text-center' style=" font-size:12px;" id="tabla-estados-solicitudes">
                    <thead class="table-primary">
                        <tr>
                            <th>Agencia</th>
                            <th>Cantidad</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                    <tfoot>
                        <tr>
                            <th>Total</th>
                            <th id="total-general-estado"></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
            <div class="d-flex justify-content-between align-items-center mb-2">
                <!-- <span class="badge badge-phoenix badge-phoenix-info" style="font-size: 13px;">
                    Número de órdenes de cargue: <span class="fw-bold badge-phoenix-info contador">0</span>
                </span> -->
                <a href="JavaScript:void(0);" id="exportar_excel" class="text-decoration-none d-flex align-items-center text-success fw-bold">
                    <img src="http://principal.nexosapp.com/public/img/excel_2013.png" alt="Excel" width="18px" class="me-1">
                    Exportar a Excel
                </a>
            </div>
            <div id="loader" style="display:none; text-align:center; padding:20px;">
                <div class="spinner-border text-primary" role="status">
                    <span class="visually-hidden">Cargando...</span>
                </div>
                <p>Cargando datos...</p>
            </div>
            <div class="table-responsive">
                <table class='table table-bordered table-striped table-sm text-center' style="font-size:12px;" id="tbl-detalle-solicitudes">
                    <thead class="table-primary text-center">
                        <tr>
                            <th>Responsable</th>
                            <th>Placa</th>
                            <th>Responsable</th>
                            <th>Manifiesto</th>
                            <th>Fecha Solicitud</th>
                            <th>Fecha Expedición</th>
                            <th>N° Solicitud</th>
                            <th>Agencia</th>
                            <th>Cliente</th>
                            <th>Tipo Mercancía</th>
                            <th>Empaque</th>
                            <th>Tipo Vehículo</th>
                            <th>Clase</th>
                            <th>Tiempo Transcurrido</th>
                        </tr>
                    </thead>
                    <tbody id="tabla-detalle-solicitudes"></tbody>
                </table>
            </div>
        </div>
    </div>
</div>