<div class="container-fluid mt-5">
  <div class="d-flex justify-content-center">
    <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
      <div class="row">
        <h2 class="mb-4">Crear ventana de trabajo</h2>
        <div class="col-xl-12">
          <form class="row g-3 mb-6">
            <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
              <div class="mb-4">
                <div class="d-flex flex-wrap mb-2">
                  <h5 class="mb-0 text-body-highlight me-2">Pantalla <span style="color:red;"><i>*</i></h5>
                </div>
                <select class="form-select form-select-sm select2" id="selectPantallas">
                </select>
              </div>
            </div>

            <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
              <div class="mb-4">
                <div class="d-flex flex-wrap mb-2">
                  <h5 class="mb-0 text-body-highlight me-2">Nombre <span style="color:red;"><i>*</i></h5>
                </div>
                <input class="form-control form-control-sm" id="nombre_ventana" type="text" placeholder="Nombre ventana"
                  oninput="this.value = this.value.toUpperCase();" />
              </div>
            </div>

            <div class="col-sm-6 col-md-6">
              <div class="form-floating">
                <select class="form-select form-select-sm" id="estadoVentana">
                  <option selected="selected">Seleccionar</option>
                  <option value="Activo">Activo</option>
                  <option value="Inactivo">Inactivo</option>
                  <option value="Cancelada">Cancelada</option>
                </select>
                <label for="estadoVentana">Estado <span style="color:red;"><i>*</i></label>
              </div>
            </div>

            <div class="col-sm-6 col-md-6">
              <div class="form-floating">
                <select class="form-select form-select-sm" id="ordenventana">
                  <option selected="selected">Seleccionar</option>
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                  <option value="7">7</option>
                  <option value="8">8</option>
                  <option value="9">9</option>
                  <option value="10">10</option>
                </select>
                <label for="ordenventana">Orden <span style="color:red;"><i>*</i></label>
              </div>
            </div>

            <div class="col-12 gy-6">
              <div class="form-floating">
                <textarea class="form-control" id="descripcion_ventana" placeholder="Leave a comment here"
                  oninput="this.value = this.value.toUpperCase();" style="height: 100px"></textarea>
                <label for="descripcion_pantalla">Descripcion</label>
              </div>
            </div>

            <div class="col-12 gy-6">
              <div class="row g-3 justify-content-end">
                <div class="col-auto">
                  <button class="btn btn-phoenix-primary btn-sm px-5" type="button" id="btn-cancelar">
                    <span class="text-danger" data-feather="x"></span> Cancelar</button>
                </div>
                <div class="col-auto">
                  <button class="btn btn-primary btn-sm px-5" id="btn-save-ventana" type="button">
                    <span data-feather="save"></span> Crear Ventana</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script src=<?php echo BASE_URL ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL ?>views/pantallas/js/ventanas.js type="text/javascript"></script>
<script>
$(document).ready(function() {
  $('.select2').select2({
    placeholder: "Seleccione",
    allowClear: true
  });
});
</script>