<?php
	$_dbTable = ""; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/*** CREACION DE TABLA DE CONTENIDO ***/
	if( isset($this->seguridad) ){
		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_content = '
			<div class="row">
				<div class="col-sm-12">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th>Manifiesto</th>
									<th>Solicitudes</th>
									<th>Vehículo</th>
									<th>Flete</th>
									<th>Anticipo</th>
									<th>Método Desembolso</th>
									<th style="min-width:5%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$informarAnticipo = $this->seguridad->getInformarAnticipo("Informar asignación anticipo al conductor");
		// print_r("<pre>");
		// print_r($informarAnticipo);
		// print_r("</pre>");

		if ($informarAnticipo["actividades"]['rowsData']) {
			foreach ($informarAnticipo["actividades"]['rowsData'] as $key => $value) {
				// Se toma la información del vehículo
				$info_vehiculo = "";
				$_placa_trailer = "";
				// Se pregunta si el vehículo tiene trailer
				if ( $value["placa_trailer"] ) {
					$_placa_trailer = '<span class="cell-detail-description">Trailer: ' . $value["placa_trailer"] . '</span>';
				}
				// Se pregunta si el vehículo tiene algún tipo de carrocería establecido
				$_tipo_carroceria = "";
				if ( $value["tipo_carroceria"] ) {
					$_tipo_carroceria = ' (' . $value["tipo_carroceria"] . ')';
				}

				// Se toma la información de las solicitudes asociadas al agrupamiento
				// print_r("<pre>");
				// print_r($informarAnticipo["solicitudes"][ $value[0] ]);
				// print_r("</pre>");
				$info_solicitudes = "";
				foreach ($informarAnticipo["solicitudes"][ $value[0] ]["rowsData"] as $key1 => $value1) {
					$info_solicitudes.= '
						<span>' . $value1["numero_solicitud"] . '</span>
						<span class="cell-detail-description">' . $value1["nombre"] . '</span>
						<span class="cell-detail-description">Peso - <strong>' . number_format($value1["peso_parcial"], 2, ",", ".") . ' Kg</strong></span>
					';
				}

				// Se maqueta contenido de la tabla 
				$_action_metodo_desembolso = "";
				$_content_metodo_desembolso = "Anticipo no desembolsado";
				if ( $value["estado"] == "Anticipo Asignado" ) {
					$_content_metodo_desembolso = $value["metodo_desembolso"];
					$_action_metodo_desembolso = '
						<a href="#" data-toggle="modal" data-target="#gestionar" onclick="gestionarActividad(' . $value["ID_AGRUPACION"] . ', \'' . $informarAnticipo["id_actividades"][ $value[0] ] . '\')" class="cell-detail md-trigger hint--top-left" data-hint="Gestionar Actividad"><span class="icon mdi mdi-assignment-check"></span></a>
						<a href="#" data-toggle="modal" data-target="#ver_detalle" onclick="mostrarDetalle(' . $value["ID_AGRUPACION"] . ')" class="cell-detail md-trigger hint--top-left" data-hint="Ver Detalles"><span class="icon mdi mdi-info"></span></a>
					';
				}

				$table_content.= '
					<tr>
						<td class="cell-detail">
							<span>' . $value["numero_manifiesto"] . '</span>
							<span class="cell-detail-description">' . $value["numero_agrupacion"] . '</span>
							<span class="cell-detail-description">Peso - <strong>' . number_format($value["peso_total"], 2, ",", ".") . ' Kg</strong></span>
						</td>
						<td class="cell-detail">
							' . $info_solicitudes . '
						</td>
						<td class="cell-detail">
							<span>' . $value["nombre"] . '</span>
							<span class="cell-detail-description">Contacto - ' . $value["contacto"] . '</span>
							<span class="cell-detail-description">' . $value["placa"] . '</span>
							' . $_placa_trailer . ' 
							<span class="cell-detail-description">' . $value["TIPO_VEHICULO"] . $_tipo_carroceria . '</span>
						</td>
						<td class="cell-detail">
							<span>$ ' . number_format($value["flete"], 2, ",", ".") . '</span>
						</td>
						<td class="cell-detail">
							<span>$ ' . number_format($value["anticipo"], 2, ",", ".") . '</span>
							<span class="cell-detail-description">' . $value["porcentaje_anticipo"] . '%</span>
						</td>
						<td class="cell-detail">
							<span>' . $_content_metodo_desembolso . '</span>
						</td>
						<td class="actions">
							' . $_action_metodo_desembolso . '
						</td>
					</tr>
				';
			}

			$table_content.= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
		}
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	// Se crea el select de tipo de seguimiento
	$_slct_tipo_seguimiento = $this->seguridad->getHtmlSelectTipoSeguimiento( "tipo_seguimiento_ruta" , 1, "ruta" );
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Informar Anticipo al Conductor 
				<div class="tools"></div>
					<span class="panel-subtitle">Listado de los conductores que iniciaron su ruta con el matrial para informar que ya tiene disponible el anticipo de acuerdo con el método de desembolso acordado.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>

		<!-- DIV QUE VISTA DE DETALLES DE INFORMAR ANTICIPO -->
		<div id="ver_detalle" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="ver_detalle_title"></h3>
					</div>
					<div class="modal-body" id="ver_detalle_content">
						<div class="row"></div>
					</div>
					<div class="modal-footer" id="foot_contenidoagrupamiento">
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
					</div>
				</div>
			</div>
		</div>

		<!-- DIV DE GESTIÓN DE INFORMAR ANTICIPO -->
		<div id="gestionar" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<form id="form_gestionar" enctype="multipart/form-data" method="POST">
						<div class="modal-header">
							<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
							<h3 class="modal-title" id="gestion_detalle_title"></h3>
						</div>
						<div class="modal-body">
							<div class="row"></div>
							<div class="col-sm-12">
								<input type="hidden" name="id" id="id">
								<input type="hidden" name="id_agrupamiento" id="id_agrupamiento">
							</div>
							<div class="col-sm-12" id="ver_gestion_content">
							</div>
							<div class="row"></div>
						</div>
						<div class="modal-footer" id="foot_contenidoagrupamiento">
							<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
							<button id="btn_gestiona_informar_anticipo"  type="button" data-dismiss="modal" class="btn btn-success md-close">Guardar</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	';

	$url_gestion_actividad = BASE_URL . 'libs/gestion_actividades.php?tabla=cmx_importacion_actividades&proyecto=importaciones';

	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
		</script>

		<script type="text/javascript">
			// Funcion que muestra detalles del seguimiento
			function mostrarDetalle( id_agrupamiento ){
				$("#ver_detalle_content").empty();
				$("#ver_detalle_title").empty();

				params={
					accion 	: "detalle_informar_anticipo",
					id 		: id_agrupamiento
				}
				// console.log(params);

				$.ajax({
					type		: "POST",
					cache		: false,
					url			: "' . BASE_URL . '/libs/seguridad_ajax.php",
					data		: params,
					dataType	: "json",
					error 		: function(data){
								console.log("Error en el ajax");
								console.log(data);
								},
					success		: function(data) {
								// console.log(data);
								$("#ver_detalle_title").append(data.content.title);
								$("#ver_detalle_content").append(data.content.body.general);
								$("#ver_detalle_content").append(data.content.body.vehiculo);
								$("#ver_detalle_content").append(data.content.body.cliente);
					}
				});
			}

			// Funcion para gestionar la actividad de seguimiento
			function gestionarActividad(id_agrupamiento, id_actividades, id_origen, id_destino){
				// Se limpian los campos del formularios
				if(id_agrupamiento != $("#id_agrupamiento").val() ){
					$("#gestionar .form-control").val("");
				}

				$("#id_agrupamiento").val(id_agrupamiento);
				$("#id").val(id_actividades);

				$("#gestion_detalle_title").html("");
				$("#ver_gestion_content").html("");

				params={
					accion 		: "gestion_informar_anticipo",
					id 			: id_agrupamiento
				}
				// console.log(params);

				$.ajax({
					type		: "POST",
					cache		: false,
					url			: "' . BASE_URL . '/libs/seguridad_ajax.php",
					data		: params,
					dataType	: "json",
					error 		: function(data){
								console.log(data);
								},
					success		: function(data) {
								// console.log(data);
								$("#gestion_detalle_title").append(data.content.title);
								$("#id").val(data.actividades);
								$("#ver_gestion_content").append(data.content.body.general);
								$("#ver_gestion_content").append(data.content.body.vehiculo);
								$("#ver_gestion_content").append(data.content.body.anticipo);
					}
				});
			}

			$("#btn_gestiona_informar_anticipo").click(function () {
				console.log("entro en funcion del botón de gestion de actividades");
				var msg_error = "";
				var flag_click = false;
				if(!flag_click){
					flag_click = true;


					// Se toman los datos a validar
					var id = $("#id").val();
					var id_agrupamiento = $("#id_agrupamiento").val();
					var id_mapa_ruta = $("#slct_plan_ruta").val();

					if(!msg_error){
						console.log("Todo OK");
						// console.log($("#form_gestionar").serialize());

						$.ajax({
							url			: "' . BASE_URL . 'libs/gestion_seguridad.php?action=informar_anticipo",
							type		: "POST",
							cache		: false,
							dataType	: "json",
							data		: $("#form_gestionar").serialize(),
							beforeSend	: function(jqXHR, settings){
								$(".nexos-messages").html(\'<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' . BASE_URL . 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>\');
							},
							error		: function(data) {
								// console.log(data);
								$(".nexos-messages").html(\'<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong> Error en la creacion del registro.</div></div>\');
							},
							success		: function(data) {
								// console.log(data);
								if(data.actividades.length > 0){
									var id = "";
									var id_material = "";
									for (var i = 0; i < data.actividades.length; i++) {
										id+= data.actividades[i]["id"]  + ",";
										id_material+= data.actividades[i]["id_material"]  + ",";
									}
									var params = {
										id 					: id,
										id_importacion		: data.actividades[0]["id_importacion"],
										id_material			: id_material,
										orden				: data.actividades[0]["orden"],
										tipo_actividad 		: data.actividades[0]["tipo_actividad"],
										fecha_hora_inicio	: data.actividades[0]["fecha_hora_inicio"],
										costo_real 			: data.actividades[0]["costo_real"],
										respuesta 			: data.actividades[0]["respuesta"]
									};
									// console.log(params);

									$.ajaxSetup({async: false});
									$.ajax({
										type		: "POST",
										cache		: false,
										url			: "' . $url_gestion_actividad . '",
										data		: params,
										beforeSend	: function(jqXHR, settings){
											$(".nexos-messages").html(\'<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' . BASE_URL . 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>\');
										},
										error 		: function (jqXHR, textStatus, errorThrown){
											console.log(jqXHR);
											console.log(textStatus);
											console.log(errorThrown);
										},
										success		: function(data) {
											// console.log(data);
										}
									});
									$.ajaxSetup({async: true});
								}else{
									msg_error+= "<p>No se gestionaron las actividades.</p>";
								}
							}
						});
					}
					if(!msg_error){
						$(".nexos-messages").html(\'<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong> Se ha creado el registro con éxito.</div></div>\');
						$("html, body").animate({ scrollTop: 0 }, 600);
						setTimeout(function() { location.reload(false); }, 800);
					}
					if(msg_error){
						flag_click = false;
						$(".nexos-messages").html(\'<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>\' + msg_error + \'</div></div>\');
						$("html, body").animate({ scrollTop: 0 }, 600);
					}
				}
			});
		</script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_content , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
