<?php
	$_dbTable = ""; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/

	$time = date('Y-m-d H:i:s', time());

	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->seguridad)){
		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_content = '
			<div class="row">
				<div class="col-sm-12">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th></th>
									<th>Manifiesto</th>
									<th>Solicitudes</th>
									<th>Vehículo</th>
									<th>Último Seguimiento</th>
									<th>Última Observación</th>
									<th style="min-width:5%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arraySeguimientosRuta = $this->seguridad->getSeguimientosRuta("seguimiento_ruta");
		// print_r("<pre>");
		// print_r($arraySeguimientosRuta);
		// print_r("</pre>");

		if ($arraySeguimientosRuta["actividades"]['rowsData']) {
			foreach ($arraySeguimientosRuta["actividades"]['rowsData'] as $key => $value) {
				// Se toma la información del vehículo
				$info_vehiculo = "";
				$_placa_trailer = "";
				// Se pregunta si el vehículo tiene trailer
				if ( $value["placa_trailer"] ) {
					$_placa_trailer = '<span class="cell-detail-description">Trailer: ' . $value["placa_trailer"] . '</span>';
				}
				// Se pregunta si el vehículo tiene algún tipo de carrocería establecido
				$_tipo_carroceria = "";
				if ( $value["tipo_carroceria"] ) {
					$_tipo_carroceria = ' (' . $value["tipo_carroceria"] . ')';
				}
				// Se pregunta si el vehículo tiene algún contacto telefónico
				$_contacto = "";
				if ( $value["contacto"] ) {
					$_contacto = '<span class="cell-detail-description">Contacto - ' . $value["contacto"] . '</span>';
				}
				// Se pregunta si el vehículo tiene algún contacto celular
				$_contacto = "";
				if ( $value["celular"] ) {
					$_celular = '<span class="cell-detail-description">Celular - ' . $value["celular"] . '</span>';
				}

				// Se toma la información de las solicitudes asociadas al agrupamiento
				// print_r("<pre>");
				// print_r($arraySeguimientosRuta["solicitudes"][ $value[0] ]);
				// print_r("</pre>");
				$info_solicitudes = "";
				foreach ($arraySeguimientosRuta["solicitudes"][ $value[0] ]["rowsData"] as $key1 => $value1) {
					$info_solicitudes.= '
						<span>' . $value1["numero_solicitud"] . '</span>
						<span class="cell-detail-description">' . $value1["nombre"] . '</span>
						<span class="cell-detail-description">Peso - <strong>' . number_format($value1["peso_parcial"], 2, ",", ".") . ' Kg</strong></span>
					';
				}

				// Se establece si no se ha registrado el seguimiento a tiempo
				$_lapso = $this->seguridad->getTimeDiff($value["ULTIMO_SEGUIMIENTO_FECHA"], $time);
				// print_r("<pre>");
				// print_r($_lapso);
				// print_r("</pre>");

				$cell_color = "success";
				$hint_content = "";
				if ( $value["DIFERENCIA"] >= STANDBY_SEGUIMIENTO_HOURS ) {
					$cell_color = "danger";
					$hint_content = 'data-hint="Seguimiento retrasado por: ' . $_lapso["diferencia_text"] . '"';
				}

				// Se maqueta contenido de la tabla 
				$table_content.= '<tr>';
				$table_content.= '
					<td class="nexos-txt-' . $cell_color . '">
						<a data-toggle="modal" class="cell-detail md-trigger hint--top-right" ' . $hint_content . '>
							<span class="icon mdi mdi-dot-circle"></span>
						</a>
					</td>
					<td class="cell-detail">
						<span>' . $value["numero_manifiesto"] . '</span>
						<span class="cell-detail-description">' . $value["numero_agrupacion"] . '</span>
						<span class="cell-detail-description">Peso - <strong>' . number_format($value["peso_total"], 2, ",", ".") . ' Kg</strong></span>
					</td>
					<td class="cell-detail">
						' . $info_solicitudes . '
					</td>
					<td class="cell-detail">
						<span>' . $value["nombre"] . '</span>
						' . $_contacto . '
						' . $_celular . '
						<span class="cell-detail-description">' . $value["placa"] . '</span>
						' . $_placa_trailer . ' 
						<span class="cell-detail-description">' . $value["TIPO_VEHICULO"] . $_tipo_carroceria . '</span>
					</td>
					<td class="cell-detail">
						<span>' . $value["ULTIMO_SEGUIMIENTO_FECHA"] . '</span>
						<span class="cell-detail-description">' . $value["ULTIMO_SEGUIMIENTO_UBICACION"] . '</span>
					</td>
					<td class="cell-detail">
						<span>' . $value["ULTIMO_SEGUIMIENTO_TIPO_SEGUIMIENTO"] . '</span>
						<span class="cell-detail-description">' . $value["ULTIMO_SEGUIMIENTO_OBSERVACION"] . '</span>
						<span class="cell-detail-description" style="color: #ea4335;">' . $value["ULTIMO_SEGUIMIENTO_OBSERVACION_INTERNA"] . '</span>
					</td>
				';

				$_btn_seguimiento_ruta = '';
				// se asigna la columna de acciones
				if ( $value["ULTIMO_SEGUIMIENTO_TIPO_SEGUIMIENTO"] != "Sin iniciar ruta") {
					$_btn_seguimiento_ruta = '
						<a href="' . BASE_URL . 'importacion/reporte_ruta/' . $value["ID_ACTIVIDAD"] . '/' . $value["numero_importacion"] . '/seguimiento" class="icon hint--top-left" data-hint="Ver Seguimiento"><span class="mdi mdi-map"></span></a>
					';
				}

				$flag_latitud = 0;
				$flag_longitud = 0;
				if ($value["LATITUD"] AND $value["LONGITUD"]) {
					$flag_latitud = $value["LATITUD"];
					$flag_longitud = $value["LONGITUD"];
				} 

				$table_content.= '
					<td class="actions">
						' . $_btn_seguimiento_ruta . ' 
						<a href="#" data-toggle="modal" data-target="#gestionar" onclick="gestionarActividad(' . $value[0] . ',' . $flag_latitud . ',' . $flag_longitud . ', \'' . $arraySeguimientosRuta["id_actividades"][ $value[0] ] . '\');" class="cell-detail md-trigger hint--top-left" data-hint="Gestionar Actividad"><span class="icon mdi mdi-assignment-check"></span></a>
						<a href="#" data-toggle="modal" data-target="#ver_detalle" onclick="mostrarDetalle(' . $value[0] . ')" class="cell-detail md-trigger hint--top-left" data-hint="Ver Detalles"><span class="icon mdi mdi-info"></span></a>
					</td>
				';
				
				$table_content.= '</tr>';
			}

			$table_content.= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
		}
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	// Se crea el select de tipo de seguimiento
	$_slct_tipo_seguimiento = $this->seguridad->getHtmlSelectTipoSeguimiento( "tipo_seguimiento_ruta" , 1, "ruta" );
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Seguimientos de Rutas 
				<div class="tools"></div>
				<span class="panel-subtitle">Listado de las rutas que se encuentran en tránsito mientras llevan material de clientes.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>

		<!-- DIV QUE VISTA DE DETALLES DEL SEGUIMIENTO -->
		<div id="ver_detalle" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="ver_detalle_title"></h3>
					</div>
					<div class="modal-body" id="ver_detalle_content">
						<div class="row"></div>
					</div>
					<div class="modal-footer" id="foot_contenidoagrupamiento">
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
					</div>
				</div>
			</div>
		</div>

		<!-- DIV DE GESTIÓN DEL SEGUIMIENTO -->
		<div id="gestionar" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<form id="form_gestionar" enctype="multipart/form-data" method="POST">
						<div class="modal-header">
							<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
							<h3 class="modal-title">Gestionar Seguimiento de Ruta</h3>
						</div>
						<div class="modal-body" id="contenidoagrupamiento">
							<div class="row"></div>
							<div class="panel panel-border panel-contrast">
								<div class="panel-heading panel-heading-contrast">
									<strong>Atención</strong>
									<div class="tools">
									</div>
									<span class="panel-subtitle">Para la finalización de esta actividad debe tener en cuenta que el campo <strong>Tipo de Seguimiento de Ruta</strong> se debe seleccionar la opción <strong>Llegada destino</strong>.</span>
								</div>
							</div>
							<div class="row"></div>
							<div class="form-group col-sm-6">
								<label>(*) Adjunto de Satelital:</label>
								<input type="file" name="url_seguimiento" id="url_seguimiento" class="inputfile form-control">
								<label for="url_seguimiento" class="btn-success"> <i class="mdi mdi-upload"></i><span>Busque Archivo...</span></label>
							</div>
							<div class="col-sm-6">
								<input type="hidden" name="id" id="id" value="">
								<input type="hidden" id="id_agrupamiento" value="">
							</div>
							<div class="row"></div>
							<div  class="form-group col-md-6 col-lg-6 col-sm-6 col-xs-12" >
								<div  id="mapa_ruta" class="img-responsive" style="height: 300px;"></div>
							</div>
							<div class="col-md-6 col-lg-6 col-sm-6 col-xs-12"> 
								<div class="form-group col-xs-12">
									<label>(*) Tipo de Seguimiento de Ruta:</label>
									' . $_slct_tipo_seguimiento . '
								</div>
								<div class="form-group col-xs-12" id="slct_destino"></div>
								<div class="form-group col-xs-6">
									<label>(*) Latitud:</label>
									<input type="text" name="latitud" id="latitud" class="form-control input-sm" placeholder="Latitud">
								</div>
								<div class="form-group col-xs-6">
									<label>(*) Longitud:</label>
									<input type="text" name="longitud" id="longitud" class="form-control input-sm" placeholder="Longitud">
								</div>
								<div class="form-group col-xs-12">
									<label>(*) Ubicación:</label>
									<input type="text" name="ubicacion" id="ubicacion" class="form-control input-sm" placeholder="Ubicación">
								</div>
								<div class="form-group col-xs-12">
									<label>(*) Velocidad:</label>
									<input type="text" name="velocidad" id="velocidad" class="form-control input-sm" placeholder="Velocidad">
								</div>
							</div>
							<div class="row"></div>
							<div class="form-group col-xs-12">
								<div class="col-xs-6">
									<br>
									<label class="control-label">Observación:</label>
									<textarea name="seguimiento" id="seguimiento" class="form-control input-sm"></textarea>
								</div>
								<div class="col-xs-6">
									<label class="control-label">Observación Interna: <strong>Esta información sólo será vista por usuarios Nexos.</strong></label>
									<textarea name="seguimiento_interno" id="seguimiento_interno" class="form-control input-sm"></textarea>
								</div>
							</div>
						</div>
						<div class="modal-footer" id="foot_contenidoagrupamiento">
							<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
							<button id="btn_gestiona_seguimiento"  type="button" data-dismiss="modal" class="btn btn-success md-close">Guardar</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	';

	$url_gestion_actividad = BASE_URL . 'libs/gestion_actividades.php?tabla=cmx_importacion_actividades&proyecto=importaciones';

	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>

	    <!-- CARGA DE API GOOGLE MAPS -->
		<script async defer
			src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6vpUhRVoEe5U6m7Wh5_LFMCr_g8OzU1E&callback=initMap">
		</script>

	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
		</script>

		<script type="text/javascript">
			// Funcion que muestra detalles del seguimiento
			function mostrarDetalle( id_agrupamiento ){
				$("#ver_detalle_content").empty();
				$("#ver_detalle_title").empty();

				params={
					accion 	: "detalle_seguimiento_ruta",
					id 		: id_agrupamiento
				}
				// console.log(params);

				$.ajax({
					type		: "POST",
					cache		: false,
					url			: "' . BASE_URL . '/libs/seguridad_ajax.php",
					data		: params,
					dataType	: "json",
					error 		: function(data){
								console.log("Error en el ajax");
								console.log(data);
								},
					success		: function(data) {
								// console.log(data);
								$("#ver_detalle_title").append(data.content.title);
								$("#ver_detalle_content").append(data.content.body.general);
								$("#ver_detalle_content").append(data.content.body.vehiculo);
								$("#ver_detalle_content").append(data.content.body.cliente);
					}
				});
			}

			// Funcion para gestionar la actividad de seguimiento
			function gestionarActividad(id_agrupamiento, latitud, longitud, id_actividades){
 				// Se limpian los campos del formularios
				if(id_agrupamiento != $("#id_agrupamiento").val() ){
					$("#gestionar .form-control").val("");
					$("#slct_destino").empty();
				}

				$("#id_agrupamiento").val(id_agrupamiento);
				$("#id").val(id_actividades);

				// Se busca la ruta que debe seguir el vehículo
				params={
					accion 	: "busca_ruta_agrupamiento",
					id 		: id_agrupamiento
				}
				// console.log(params);
				$.ajax({
					url			: "' . BASE_URL . 'libs/seguridad_ajax.php",
					type		: "POST",
					cache		: false,
					data		: params,
					dataType 	: "json",
					error		: function(data) {
								// console.log(data);
					},
					success		: function(data) {
								// console.log(data);

								// Se envian los parámetros para crear el mapa de seguimiento 
								var params = {
									latitud 	: latitud,
									longitud 	: longitud,
									ruta 		: data.ruta_control,
									origen 		: data.origen,
									destino		: data.destino
								}
								initMap(params);
								App.wizard();
					}
				});
			}

			// Función para buscar coordenadas de un remitente-destinatario
			function buscarCoordenadas(destino){
				let longitud = destino.parents(".modal-body").find("#longitud");
				let latitud = destino.parents(".modal-body").find("#latitud");
				let ubicacion = destino.parents(".modal-body").find("#ubicacion");
				let id_destino = destino.find("option:selected").data("id_destino");
				let nom_destino = destino.find("option:selected").text();

				let params={
					accion 	: "busca_coordenadas",
					id 		: id_destino
				}
				// console.log(params);

				$.ajax({
					type		: "POST",
					cache		: false,
					url			: "' . BASE_URL . '/libs/seguridad_ajax.php",
					data		: params,
					dataType	: "json",
					error 		: function(data){
						console.log("Error en el ajax");
						console.log(data);
					},
					success		: function(data) {
						// console.log(data);
						if(data.content.longitud && data.content.latitud){
							longitud.val(data.content.longitud);
							latitud.val(data.content.latitud);
							ubicacion.val(nom_destino);
						}
					}
				});
			}

			// Se crea el select de clientes de destino 
			$("#slct_tipo_seguimiento_1").change(function () {
				$("#slct_destino").empty();

				if( $("#slct_tipo_seguimiento_1").val() == "Llegada Destino" ){
					params={
						accion 	: "slct_clientes_destino",
						id 		: $("#id_agrupamiento").val()
					}
					// console.log(params);

					$.ajax({
						type		: "POST",
						cache		: false,
						url			: "' . BASE_URL . '/libs/seguridad_ajax.php",
						data		: params,
						dataType	: "json",
						error 		: function(data){
							console.log("Error en el ajax");
							console.log(data);
							},
						success		: function(data) {
							// console.log(data);
							$("#slct_destino").append( data.content );

							$(".slct_clientes_destino").change(function(){
								buscarCoordenadas($(this));
							});
						}
					});
				}
			});

			// Se gestiona los saguimientos
			$("#btn_gestiona_seguimiento").click(function () {
				var msg_error = "";
				var flag_click = false;
				if(!flag_click){
					flag_click = true;

					// Se toman los datos a validar
					var id = $("#id").val();
					var id_agrupamiento = $("#id_agrupamiento").val();
					var latitud = $("#latitud").val();
					var longitud = $("#longitud").val();
					var ubicacion = $("#ubicacion").val();
					var tipo_seguimiento_ruta = $("#slct_tipo_seguimiento_1").val();
					var slct_solicitud = "";
					var id_destino = "";
					var velocidad = $("#velocidad").val();

					// se verifica si hay imagenes adjuntos
					if($(\'input[name=url_seguimiento]\').val()){
						var url_seguimiento= document.getElementById(\'url_seguimiento\').files;
						for( var i=0; i < url_seguimiento.length; i++ ){
							var extension = url_seguimiento[i].name.split(".");
							// Se valida el tipo de archivo
							if( validaFormatoArchivo("jpg,jpeg,png,gif,bmp,JPG,JPEG,PNG,GIF,BMP", extension[ extension.length - 1 ]) == 0 ){
								msg_error+= "<p>Formato de una o varias imagenes adjuntas no es válido como entregable para esta actividad.</p>";
								break;
							}
							// Se valida el tamaño del archivo 
							if( $(\'input[name=url_seguimiento]\')[0].files[0].size > 2000000 ){
								msg_error+= "<p>El tamaño del archivo es demasiado grande para subirlo al servidor, por favor use un archivo de menos de 2Mb de tamaño.</p>";
								break;
							}
						}
					}else{
						msg_error+= "<p>Debe adjuntar imágenes para continuar esta Actividad.</p>";
					}
					if( !latitud || !longitud ){
						msg_error+= "<p>Para continuar debe establecer la ubicación del seguimiento en el mapa.</p>";
					}
					if( !ubicacion ){
						msg_error+= "<p>Para continuar debe diligenciar el campo <strong>Ubicación</strong>.</p>";
					}
					if( tipo_seguimiento_ruta == null ){
						msg_error+= "<p>Para continuar debe seleccionar un <strong>Tipo de Seguimiento de Ruta</strong>.</p>";
					}else if( tipo_seguimiento_ruta == "Llegada Destino" ){
						slct_solicitud = $("#slct_solicitud").val();
						if( !slct_solicitud ){
							msg_error+= "<p>Para continuar debe seleccionar un <strong>Cliente Destino</strong>.</p>";
						} else  {
							id_destino = $("#slct_solicitud").find("option:selected").data("id_tramo");
						}
					}
					if( !velocidad ){
						msg_error+= "<p>Para continuar debe diligenciar el campo <strong>Velocidad</strong>.</p>";
					}

					if(!msg_error){
						console.log("Todo OK");
						// se crean los parámteros a enviar 
						var formData = new FormData($("#form_gestionar")[0]);
						formData.append( "id", id );
						formData.append( "id_agrupamiento", id_agrupamiento );
						formData.append( "latitud", latitud );
						formData.append( "longitud", longitud );
						formData.append( "tipo_seguimiento_ruta", tipo_seguimiento_ruta );
						formData.append( "id_solicitud", slct_solicitud );
						formData.append( "id_destino", id_destino );
						formData.append( "velocidad", velocidad );
						formData.append( "url_seguimiento", url_seguimiento );
						// console.log(formData);

						$.ajax({
							url			: "' . BASE_URL . 'libs/gestion_seguridad.php?action=seguimiento_ruta&id_usuario=' . $ssn_id_usuario . '",
							type		: "POST",
							cache		: false,
							contentType : false,
							processData : false,
							data		: formData,
							dataType	: "json",
							beforeSend	: function(jqXHR, settings){
								$(".nexos-messages").html(\'<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' . BASE_URL . 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>\');
							},
							error		: function(data) {
								console.log(data);
								console.log(jqXHR);
								console.log(textStatus);
								console.log(errorThrown);
								$(".nexos-messages").html(\'<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong> <p>\' + jqXHR.responseText + \'</p>.</div></div>\');
							},
							success		: function(data) {
								// console.log(data);
								if(data.actividades.length > 0){
									var id = "";
									var id_material = "";
									for (var i = 0; i < data.actividades.length; i++) {
										id+= data.actividades[i]["id"]  + ",";
										id_material+= data.actividades[i]["id_material"]  + ",";
									}
									var params = {
										id 					: id,
										id_importacion		: data.actividades[0]["id_importacion"],
										id_material			: id_material,
										orden				: data.actividades[0]["orden"],
										tipo_actividad 		: data.actividades[0]["tipo_actividad"],
										fecha_hora_inicio	: data.actividades[0]["fecha_hora_inicio"],
										costo_real 			: data.actividades[0]["costo_real"],
										respuesta 			: data.actividades[0]["respuesta"]
									};
									// console.log(params);

									$.ajaxSetup({async: false});
									$.ajax({
										type		: "POST",
										cache		: false,
										url			: "' . $url_gestion_actividad . '",
										data		: params,
										beforeSend	: function(jqXHR, settings){
											$(".nexos-messages").html(\'<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' . BASE_URL . 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>\');
										},
										error 		: function (jqXHR, textStatus, errorThrown){
											console.log(jqXHR);
											console.log(textStatus);
											console.log(errorThrown);
										},
										success		: function(data) {
											// console.log(data);
										}
									});
									$.ajaxSetup({async: true});
								}else{
									msg_error+= "<p>No se gestionaron las actividades.</p>";
								}
							}
						});
					}
					if(!msg_error){
						$(".nexos-messages").html(\'<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong> Se ha creado el registro con éxito.</div></div>\');
						$("html, body").animate({ scrollTop: 0 }, 600);
						setTimeout(function() { location.reload(false); }, 800);
					}
					if(msg_error){
						flag_click = false;
						$(".nexos-messages").html(\'<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>\' + msg_error + \'</div></div>\');
						$("html, body").animate({ scrollTop: 0 }, 600);
					}
				}
			});


			/******* FUNCIONES DEL API DE GOOGLE MAPS *******/
			var markers = [];
			var status_ruta = false;
			function initMap(params) {

				var flag_plan_ruta = false;
				if(!params){
					var latitud_inicial = 4.7097100;
					var longitud_inicial = -74.0677500;
				}else{
					var latitud_inicial = params["latitud"];
					var longitud_inicial = params["longitud"];

					if(params["ruta"]){
						flag_plan_ruta = true;
					}
				}

				var code = {lat: latitud_inicial, lng: longitud_inicial};
				mapa = new google.maps.Map(document.getElementById(\'mapa_ruta\'), {
					zoom: 7,
					center: code
				});

				// Se crea el marcardor del punto del último seguimeinto   
				markers[0] = new google.maps.Marker({
					map: mapa,
					position: code
				});

				var trafficLayer = new google.maps.TrafficLayer();
				trafficLayer.setMap(mapa);
				var directionsService = new google.maps.DirectionsService;
				var directionsDisplay = new google.maps.DirectionsRenderer;

				//add map
				directionsDisplay.setMap(mapa);

				if( flag_plan_ruta ){
					// Se debe crear aqui la ruta del plan de ruta 
					var markers_plan_ruta = [];

					for (var i = 0; i < params["ruta"].length; i++) {
						var LatLng = params["ruta"][i]["latitud"] + "," + params["ruta"][i]["longitud"];
						markers_plan_ruta.push({
							location: LatLng,
							stopover: true
						});
					}

					if(params["origen"][0]["latitud"] && params["origen"][0]["longitud"]){
						var ubicacion_origen = params["origen"][0]["latitud"] + ","+ params["origen"][0]["longitud"];
						var ubicacion_destino = params["destino"][0]["latitud"] + ","+ params["destino"][0]["longitud"];

						directionsService.route({
							origin: ubicacion_origen,
							destination: ubicacion_destino,
							waypoints: markers_plan_ruta,
							optimizeWaypoints: true,
							travelMode: "DRIVING"
						}, function (response, status) {
							if (status === google.maps.DirectionsStatus.OK) {
								directionsDisplay.setDirections(response);
							} else {
								window.alert(\'Ha fallado la comunicación en el mapa a causa de: \' + status);
							}
						});
					}
				}

				mapa.addListener(\'click\', function (event) {
					$("#latitud").val("Cargando...");
					$("#longitud").val("Cargando...");
					$("#ubicacion").val("Cargando Ubicación...");

					deleteMarkers();
					var point = new google.maps.LatLng(
						event.latLng.lat(),
						event.latLng.lng()
					);

					markers[1] = new google.maps.Marker({
						map: mapa,
						position: point
					});

					var latitud = event.latLng.lat();
					var longitud = event.latLng.lng();

					// Se busca en nombre de la posición se leccionada
					var geocoder = new google.maps.Geocoder;
					var latlng = {
						lat: parseFloat(latitud),
						lng: parseFloat(longitud)
					};
					geocoder.geocode({
						\'location\': latlng
					}, function(results, status) {
						if (status === google.maps.GeocoderStatus.OK) {
							var ubicacion = results[1].formatted_address;
							$("#ubicacion").val(ubicacion);
						} else {
							latitud = "";
							longitud = "";
							$("#ubicacion").val("");
							window.alert(\'Error en la ubicación seleccionada: \' + status);
						}
						$("#latitud").val(latitud);
						$("#longitud").val(longitud);
					});
				});
			}

			getKilometros = function (lat1, lon1, lat2, lon2){
				rad = function (x) {
					return x * Math.PI / 180;
				}
				var R = 6378.137; //Radio de la tierra en km
				var dLat = rad(lat2 - lat1);
				var dLong = rad(lon2 - lon1);
				var a = Math.sin(dLat / 2) * Math.sin(dLat / 2) + Math.cos(rad(lat1)) * Math.cos(rad(lat2)) * Math.sin(dLong / 2) * Math.sin(dLong / 2);
				var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
				var d = (R * c) * 1.1;
				return d.toFixed(3); //Retorna tres decimales
			}

			// Adds a marker to the map and push to the array.
			function addMarkerruta(location, mapa) {
				if (status_ruta == false) {
					var marker = new google.maps.Marker({
						position: location,
						map: mapa
					});
					marker.setTitle("Control");
					markers.push(marker);
				}
			}

			function addMarkertramo(location) {
				var tramo = new google.maps.Marker({
					position: location,
					map: mapa_ruta
				});
				tramo.setTitle("Control");
				tramos.push(tramo);
			}

			// Sets the map on all markers in the array.
			function setMapOnAll(map) {
				for (var i = 1; i < markers.length; i++) {
					markers[i].setMap(map);
				}
			}

			function setMaprutaOnAll(map) {
				for (var i = 0; i < tramos.length; i++) {
					tramos[i].setMap(map);
				}
			}

			// Removes the markers from the map, but keeps them in the array.
			function clearMarkers() {
				setMapOnAll(null);
			}
			function clearTramos() {
				setMaprutaOnAll(null);
			}

			// Shows any markers currently in the array.
			function showMarkers() {
				setMapOnAll(map);
			}

			// Deletes all markers in the array by removing references to them.
			function deleteMarkers() {
				clearMarkers();
				markers = [];
			}
			function deleteTramos() {
				clearTramos();
				tramos = [];
			}
			/******* FIN - FUNCIONES DEL API DE GOOGLE MAPS *******/
		</script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_content , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
