<div class="panel panel-border panel-contrast">
	<div class="panel-heading panel-heading-contrast">
		<div class="tools">

			<a href="#" data-toggle="modal" id="btn_crea" class="cell-detail  hint--top"  data-hint="Agregar Prefiltro" id="btn_crea"><span class="icon mdi mdi-plus"></span></a>

		</div>
		<span class="panel-subtitle">Permite identificar la disponibilidad de vehículos y conductores y si están o no habilitados para prestar servicios en carretera.</span>
		<div class=" col-xs-12 col-sm-4 col-md-12">
			<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'" >
			<input type="hidden" id="elperfil" class="form-control input-sm" readonly="readonly" value="0">
		</div>
	</div>
	<div class="panel-body">
		<div class="nexos-messages"></div>
		<div class="nexos-content" id="contenedor_registro">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				 <div class="panel panel-border-color panel-border-color-warning">
            <div class="panel-heading">
            	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center"><strong>REGISTRAR PREFILTRO</strong></div>
            </div>
              <div class="panel-body">
              	<div class="row">
              		<div>
                		<hr></hr><strong>Datos  Básicos</strong><hr></hr>
                	</div>  
              	  <div class="col-xs-12 col-md-4 col-sm-4 col-lg-4">
                      <label>Placa Vehiculo&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="placag" class="form-control input-sm">
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-4 col-lg-4">
                      <label>Placa Trailer</label>
                      <input type="text" id="placat" class="form-control input-sm">
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-4 col-lg-4">
                    	<label>Capacidad carga (Kg)&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                    	 <input type="number" id="capa_carga_vh" class="form-control input-sm">
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-4 col-lg-4">
                      <label>Web Sátelital&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="web" class="form-control input-sm">
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-4 col-lg-4">
                      <label>Usuario&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="user_satelite" class="form-control input-sm">
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-4 col-lg-4">
                      <label>Clave&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="clave" class="form-control input-sm">
                    </div>
                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                      <label>Nombre Propietario&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="nompro" class="form-control input-sm">
                    </div>
                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                      <label>Documento&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="number" id="docupro" class="form-control input-sm">
                    </div>
                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                      <label>Nombre Poseedor&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="nomtene" class="form-control input-sm">
                    </div>
                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                      <label>Documento&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="number" id="docutene" class="form-control input-sm">
                    </div>
                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                      <label>Nombre Conductor&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="nomcondu" class="form-control input-sm">
                    </div>
                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                      <label>Documento&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="number" id="docucondu" class="form-control input-sm">
                    </div>
                </div>
                <div>
                	<hr></hr><strong>Referencias  Empresariales</strong><hr></hr>
                </div>  
               	<div class="row">
               		<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4" style="border-right:1px solid gray">
               			<span>Nombre Empresa</span>
               			<input type="text" class="form-control input-sm" id="referencias_empresariales1"
                          onblur="mayuscula(this);">
                    <span>Persona Contacto</span>
               			<input type="text" id="contacto_ref1" placeholder="Nombre Contacto"
                          class="form-control input-sm" onblur="mayuscula(this);">      
                    <span>Celular Empresa</span>
               			 <input type="int" id="celular_ref1" placeholder="Celular Empresa" maxlength="10"
                          class="form-control input-sm">   
                    <span>Cargo</span>
               			<input type="text" id="cargo_ref1" placeholder="Cargo" class="form-control input-sm"
                          onblur="mayuscula(this);">
                    <span>Fecha ingreso 1</span>
                    <input type="date" id="fingresoa1" class="form-control input-sm">
                    <span>Fecha ingreso 2</span>
                    <input type="date" id="fretiroa3" class="form-control input-sm">
                     <span>Antiguedad</span>
               			 <input type="number" id="anti_ref1" min="0"
                          class="form-control input-sm">     
               		</div>
               		<!-- Segunda referencia -->
               		<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4" style="border-right:1px solid gray">
               			<span>Nombre Empresa</span>
               			<input type="text" class="form-control input-sm" id="referencias_empresariales2"
                          onblur="mayuscula(this);">
                    <span>Persona Contacto</span>
               			<input type="text" id="contacto_ref2" placeholder="Nombre Contacto"
                          class="form-control input-sm" onblur="mayuscula(this);">      
                    <span>Celular Empresa</span>
               			 <input type="int" id="celular_ref2" placeholder="Celular Empresa" maxlength="10"
                          class="form-control input-sm">   
                    <span>Cargo</span>
               			<input type="text" id="cargo_ref2" placeholder="Cargo" class="form-control input-sm"
                          onblur="mayuscula(this);"> 
                    <span>Fecha ingreso 1</span>
                    <input type="date" id="fingresob1" class="form-control input-sm">
                    <span>Fecha ingreso 2</span>
                    <input type="date" id="fretirob3" class="form-control input-sm">      
                     <span>Antiguedad</span>
               			 <input type="number" id="anti_ref2" min="0"
                          class="form-control input-sm">     
               		</div>
               		<!-- tercera referencia  -->
               		<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
               			<span>Nombre Empresa</span>
               			<input type="text" class="form-control input-sm" id="referencias_empresariales3"
                          onblur="mayuscula(this);">
                    <span>Persona Contacto</span>
               			<input type="text" id="contacto_ref3" placeholder="Nombre Contacto"
                          class="form-control input-sm" onblur="mayuscula(this);">      
                    <span>Celular Empresa</span>
               			 <input type="int" id="celular_ref3" placeholder="Celular Empresa" maxlength="10"
                          class="form-control input-sm">   
                    <span>Cargo</span>
               			<input type="text" id="cargo_ref3" placeholder="Cargo" class="form-control input-sm"
                          onblur="mayuscula(this);"> 
                    <span>Fecha ingreso 1</span>
                    <input type="date" id="fingresoc1" class="form-control input-sm">
                    <span>Fecha ingreso 2</span>
                    <input type="date" id="fretiroc3" class="form-control input-sm">      
                     <span>Antiguedad</span>
               			 <input type="number" id="anti_ref3" min="0" 
                          class="form-control input-sm">     
               		</div>
               	</div>
               	<div>
                <hr></hr><strong>Documentos Prefiltro</strong><hr></hr>
                </div> 

                <div class="row">
                	<div class="col-xs-2 col-sm-1 col-md-1 col-lg-1">
                		<label>Agregar archivo</label>
                		<button class=" form-control btn btn-info mdi mdi-plus input-xs text-center"
                          data-toggle="tooltip" data-placement="top" title="Agregar Archivo" id="agregar_docu">
                   	</button>
                	</div>
                 <div class="col-xs-10 col-sm-11 col-md-11 col-lg-11">
                 		 <table class="table table-bordered">
                        <thead>
                          <th>#</th>
                          <th>Tipo Hoja Vida</th>
                          <th>Clase</th>
                          <th>Ruta</th>
                          <th>Subir</th>
                          <th>Nombre Archivo</th>
                          <th>Acción</th>
                        </thead>
                        <tbody id="tabla_papeles">
                        </tbody>
                      </table>
                      <input type="hidden" id="cont_papel">
                 </div> 
                </div>
                <div class="col-xs-12 text-right">
               			<br><button id="crear_preestudio" class="btn btn-success text-right" style="align-content:right;">Guardar</button>
               		</div>

            </div>
          </div>
			</div>
		</div>

		<div class="nexos-content" id="contenedor_tabla">	
			<div class="row">
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfiltro">
					<label>Filtrar</label>
					<select id="filtro" class="form-control input-xs">
						<option value="">Seleccionar</option>
						<option value="1">Fecha</option>
					</select>
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divcliente">
					<label>Cliente</label>
					<select id="clientefiltro" class="form-control input-xs">
						<option value="">Seleccionar</option>
					</select>
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfechas">
					<label>Fecha inicial</label>
					<input type="date" id="finicial" class="form-control input-xs" value="<?php echo date('Y-m-d'); ?>">
					<label>Fecha final</label>
					<input type="date" id="ffinal" class="form-control input-xs" value="<?php echo date('Y-m-d'); ?>">
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divbtnbusqueda">
					<br><button id="buscar_prefiltro" class="btn btn-primary btn-sm">Buscar</button>
				</div>
			</div><br>
			<div class="row" id="tabla_datos">
				<hr>
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div  class='table-responsive noSwipe'>
					<table id='table1' class='table table-striped table-hover' data-page-length='100'>
						<thead>
							<tr class='nexos-encabezado'>
								<th>Placa</th>
								<th>Propietario</th>
								<th>Poseedor</th>
								<th>Conductor</th>
								<th>Satélital</th>
								<th style='width:10%;min-width: 10%;'>Acciones</th>
							</tr>
						</thead>
						<tbody id="tabla_prefiltros">
						</tbody>
					</table>
					</div>
				</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12"></div>
		</div>
	</div>
</div>

			<script src=<?php echo BASE_URL;?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/js/main.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
	  	 <script src=<?php echo BASE_URL;?>/views/prefiltro_operacion/js/prefiltro_ajax.js type="text/javascript"></script>
	  	 
		<!-- js para creacion de formularios dinamicos -->
	    <script src=<?php echo BASE_URL;?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>



<script type="text/javascript">
$(document).ready(function(){
//initialize the javascript
  App.init();
  App.wizard();
});
</script>