<?php
// se definen las variables de session
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

$vista = '
		<link rel="stylesheet" type="text/css" href="%root_file%lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>
	';
$table_content = "";

if (isset($this->internacional)) {
	$arrayRegistraEgreso = $this->internacional->getPagosPendientes();

	$table_content = '
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-2"></div>
				<div class="col-xs-12 col-sm-12 col-md-8">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover table-fw-widget" data-page-length="100">
							<thead>
								<tr class="nexos-encabezado">
									<th># Pago</th>
									<th>Moneda Egreso</th>
									<th>Cant. Egresos</th>
									<th>Fecha Generado</th>
									<th>Valor en COP</th>
									<th></th>
								</tr>
							</thead>
								<tbody>
		';

	if ($arrayRegistraEgreso["general"]) {
		foreach ($arrayRegistraEgreso["general"] as $key => $value) {
			$_col_actions = '
					<td class="actions">
						<a href="' . BASE_URL . 'public/files/internacional/egresos/' . $value["url_egreso"] . '" target="_blank" class="cell-detail hint--top-left" data-hint="Ver Egreso"><span class="icon mdi mdi-download"></span></a>
						<a href="javascript:" onclick="verRegistroPago(' . $value['id'] . ',\'' . $arrayRegistraEgreso["egresos"][$value['id']] . '\')" class="cell-detail hint--top-left" data-hint="Registrar Egreso"><span class="icon mdi mdi-edit" data-toggle="modal" data-target="#registra_egreso"></span></a>
					</td>
				';

			$table_content .= '
					<tr>
						<td class="cell-detail">
							<span>' . $value["numero_egreso"] . '</span>
							<span class="cell-detail-description">' . $value["numero_pago"] . '</span>
						</td>
						<td class="cell-detail">
							<span>' . $value["MONEDA"] . '</span>
						</td>
						<td class="cell-detail">
							<span class="label label-default">' . $value["CUANTOS"] . '</span>
						</td>
						<td class="cell-detail text-center">
							<span>' . $value["fecha_egreso"] . '</span>
						</td>
						<td class="cell-detail text-right">
							<span>$' . number_format($value["valor_egreso"], 2, ',', '.') . '</span>
						</td>
						' . $_col_actions . '
					</tr>
				';
		}
	}

	$table_content .= '
							</tbody>
						</table>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-2"></div>
			</div>
		';
}

/**** CONTENIDO DEL MODULO EN PANTALLA ****/
$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Registro de Pagos a Proveedores
				<div class="tools" id="link_registra_egreso"></div>
				<span class="panel-subtitle"></span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>

		<div id="registra_egreso" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="registra_egreso_title"></h3>
					</div>
					<div class="modal-body">
						<div id="nexos_messages_popup_registra_egreso"></div>
						<div id="contenidoregistraegreso"></div>
						<div class="row"></div>
					</div>
					<div class="modal-footer">
						<button id="btn_registra_egreso" type="button" class="btn btn-success md-close">Guardar</button>
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
					</div>
				</div>
			</div>
		</div>
	';

/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
$vista .= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
		<script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.wizard();
			});
		</script>
	';

/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%content%", $table_content, $vista);

echo $vista;
?>

<script type="text/javascript">
	$(document).ready(function() {
		$("#btn_registra_egreso").click(function() {
			// console.log("Entro en función del btn_registra_egreso");
			$("#nexos_messages_popup_registra_egreso").empty();
			var msg_error = "";

			/***** Validación de campos del formulario de registro de pagos a proveedores *****/
			var fecha_pago = $("#fecha_pago").val();
			var valor_pago = $("#valor_pago").val();
			var file = $("#pago_file").val();

			if (!fecha_pago) {
				msg_error += "<p>Debe diligenciar el campo <strong>Fecha Desembolso</strong> para registrar el pago.</p>";
			}

			if (!valor_pago) {
				msg_error += "<p>Debe diligenciar el campo <strong>Valor Debitado</strong> para registrar el pago.</p>";
			}

			if (!file) {
				msg_error += "<p>Debe seleccionar un <strong>Adjunto Comprobante de Pago</strong> para registrar el pago.</p>";
			} else {
				var adjunto = $("#pago_file")[0].files[0];
				// Se valida el peso del archivo
				if (adjunto.size < $("#max_file_size").val()) {
					// Se valida el tipo de archivo
					var extension = adjunto.name.split(".");
					var formato_archivo = "pdf,PDF,zip,ZIP,rar,RAR,doc,DOC,docx,DOCX,jpg,jpeg,png,gif,bmp,tif,JPG,JPEG,PNG,GIF,BMP,TIF,xls,XLS,xlsx,XLSX,ppt,PPT,pptx,PPTX,pps,PPS,ppsx,PPSX,ods,ODS";
					if (validaFormatoArchivo(formato_archivo, extension[extension.length - 1]) == 0) {
						msg_error += "<p>Formato del archivo del campo <strong>Adjunto Comprobante de Pago</strong> no es válido para poder crear el sobrecosto.</p>";
						msg_error += "<p>Formatos válidos: <strong>" + formato_archivo + "</strong>.</p>";
					}
				} else {
					msg_error += "<p>El archivo del campo <strong>Adjunto Comprobante de Pago</strong> es muy pesado para subirlo al servidor. El peso máximo del archivo debe ser menor de <strong>" + ($("#max_file_size").val() / 1000000) + "MB</strong>.</p>";
				}
			}
			/***** Fin - Validación de campos del formulario de registro de pagos a proveedores *****/

			if (!msg_error) {
				var params = new FormData($("#form_registro_pago")[0]);

				$.ajax({
					url: $("#id_url_ajax").val() + "libs/internacional_ajax.php?action=registrar_pago",
					type: 'POST',
					contentType: false,
					data: params,
					cache: false,
					dataType: 'json',
					processData: false,
					beforeSend: function(jqXHR, settings) {
						$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
					},
					error: function(jqXHR, textStatus, errorThrown) {
						$(".nexos-messages").html('');
						msg_error += "<p>" + jqXHR.responseText + "</p>";
						console.log(jqXHR);
						console.log(textStatus);
						console.log(errorThrown);
					},
					success: function(data, textStatus, jqXHR) {
						$(".nexos-messages").html('');
						// console.log(data);

						let arrayRegistro = data.flag_gestion.pagos_pendientes;
						let arrayFlagGestion = data.flag_gestion.flag_gestiona_subir_facturas;

						for (var i = 0; i < arrayRegistro.length; i++) {
							let array = arrayRegistro[i];
							if (array["REGISTROS_PENDIENTES"] == 0 && array["PAGOS_PENDIENTES"] == 0 && array["EGRESOS_PENDIENTES"] == 0 && arrayFlagGestion[i]) {
								var params = {
									id: array["ID_ACTIVIDAD"] + ",",
									orden: array["orden"],
									fecha_hora_inicio: array["fecha_hora_inicio"],
									id_importacion: array["id_importacion"],
									bloque: array["bloque"],
									grupo: array["grupo"],
									simultaneo: array["EGRESOS_PENDIENTES"],
									tipo_actividad: array["tipo_actividad"],
									costo_real: array["costo_real"],
									respuesta: array["respuesta"],
								}
								// console.log(params);
								actualizaActividad(params);
							}
						}

						if (data.error) {
							msg_error += data.error;
						}
					}
				});

				if (!msg_error) {
					$("#nexos_messages_popup_registra_egreso").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado! </strong>Se ha creado el registro con éxito.</div></div>');
					$("#registra_egreso").animate({
						scrollTop: 0
					}, 600);
					setTimeout(function() {
						location.reload(false);
					}, 800);
				}
				if (msg_error) {
					$("#nexos_messages_popup_registra_egreso").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
					$("#registra_egreso").animate({
						scrollTop: 0
					}, 600);
				}
			}
			if (msg_error) {
				$("#nexos_messages_popup_registra_egreso").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
				$("#registra_egreso").animate({
					scrollTop: 0
				}, 600);
			}
		});
	});

	function verRegistroPago(id, egresos) {
		// console.log("Entro en función verRegistroPago");
		$("#nexos_messages_popup_registra_egreso").empty();
		$("#registra_egreso_title").empty();
		$("#contenidoregistraegreso").empty();
		var msg_error = "";

		var params = {
			id: id,
			egresos,
			egresos
		}
		// console.log(params);

		$.ajaxSetup({
			async: false
		});
		$.ajax({
			// url: $("#id_url_ajax").val() + "libs/internacional_ajax.php?action=form_registra_egreso",
			url: $("#id_url_ajax").val() + "libs/internacional_ajax.php?action=form_crea_pago",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend: function(jqXHR, settings) {
				$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
			},
			error: function(jqXHR, textStatus, errorThrown) {
				$(".nexos-messages").html('');
				msg_error += "<p>" + jqXHR.responseText + "</p>";
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function(data, textStatus, jqXHR) {
				// console.log(data);
				$(".nexos-messages").html('');
				$("#nexos_messages_popup_registra_egreso").html("");
				if (data.content) {
					$("#registra_egreso_title").html(data.content.title);
					$("#contenidoregistraegreso").html(data.content.content);
					App.formElements();
				}
			}
		});
		$.ajaxSetup({
			async: true
		});
		if (msg_error) {
			$("#nexos_messages_popup_registra_egreso").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("#registra_egreso").animate({
				scrollTop: 0
			}, 600);
		}
	}

	function calculaTRM(elemento, valor) {
		// console.log("Entro en funcion calculaTRM");
		var tasa_cambio = elemento.value.replace(/\./g, "").replace(/\,/g, ".");
		var float_valor = parseFloat(valor);
		var total_cambio = float_valor * tasa_cambio;
		var array_total_cambio = String(total_cambio).split(".");

		if (total_cambio.length > 1) {
			if (total_cambio[1].length == 1) {
				total_cambio = total_cambio * 10;
			}
		} else {
			total_cambio = parseInt(total_cambio * 100);
		}
		$("#valor_pago_pesos").val(getFormatoNumeroDecimal_value(total_cambio));
	}

	function actualizaActividad(params) {
		// console.log(params);
		var msg_error = "";

		// Se actualizan las actividades del proyecto
		$.ajax({
			type: "POST",
			cache: false,
			url: $("#id_url_ajax").val() + "libs/gestion_actividades.php?tabla=cmx_importacion_actividades&proyecto=importacion",
			data: params,
			beforeSend: function(jqXHR, settings) {
				$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
			},
			error: function(data) {
				console.log(data);
				$("#nexos_messages_popup_crea_pago").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong> Error en la creación del registro.</div></div>');
			},
			success: function(data) {
				console.log(data);
			}
		});
	}
</script>