<?php
// se definen las variables de session
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

$vista = ' <link rel="stylesheet" type="text/css" href="%root_file%lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>';
$year_cartera = "";

if (isset($this->internacional)) {
	// Se verifican los permisos del pefil de usuario
	$arrayPermisos = $this->internacional->permisosPerfil($ssn_id_perfil, 73);
	$_permisos = $arrayPermisos;
	$year_cartera = $this->internacional->getHtmlSelectYearCartera("year_cartera", date('Y', time()));
}

/**** CONTENIDO DEL MODULO EN PANTALLA ****/
$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Cartera Pagada Clientes Internacional
				<span class="panel-subtitle">Resumen de los pagos realizados por lo clientes desglosado por <strong>años</strong>.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				<div class="form-group col-xs-12 col-sm-2 col-md-4"></div>
				<div class="form-group col-xs-12 col-sm-8 col-md-4">
					<label for="slct_year">Año:</label>
					' . $year_cartera . '
				</div>
				<div class="form-group col-xs-12 col-sm-2 col-md-4"></div>
				<div class="table-responsive noSwipe col-xs-12 col-sm-12 col-md-12" id="table_content"></div>
			</div>
		</div>

		<div id="ver_cartera" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="ver_cartera_title"></h3>
					</div>
					<div class="modal-body">
						<div id="nexos_messages_popup_cartera"></div>
						<div id="contenidocartera"></div>
						<div class="row"></div>
					</div>
					<div class="modal-footer">
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
					</div>
				</div>
			</div>
		</div>
	';

/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
$vista .= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

		<script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
		</script>
	';

/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA ****/
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);

echo $vista;
?>

<script type="text/javascript">
	$(document).ready(function() {
		cargarTabla();
		$("#slct_year").change(function() {
			cargarTabla();
		});
	});

	function cargarTabla() {
		$("#table_content").empty();
		var msg_error = '';
		var year = $("#slct_year").val();
		var params = {
			year: year
		}
		$.ajaxSetup({
			async: false
		});
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/internacional_ajax.php?action=table_cartera_pagada",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend: function(jqXHR, settings) {
				funct_msg_loading(".nexos-messages");
			},
			error: function(jqXHR, textStatus, errorThrown) {
				$(".nexos-messages").html('');
				msg_error += "<p>" + jqXHR.responseText + "</p>";
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function(data, textStatus, jqXHR) {
				$(".nexos-messages").html('');
				// console.log(data);
				if (!msg_error) {
					if (data.content) {
						$("#table_content").html(data.content);
						App.dataTables();
					}
				}
			}
		});
		if (msg_error) {
			funct_msg_error(".nexos-messages", msg_error);
		}
		$.ajaxSetup({
			async: true
		});
	}

	function verPagosRegistrados(id) {
		$("#nexos_messages_popup_cartera").empty();
		$("#ver_cartera_title").empty();
		$("#contenidocartera").empty();
		var msg_error = "";
		var year = $("#slct_year").val();

		var params = {
			id: id,
			year: year
		}
		$.ajaxSetup({
			async: false
		});
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/internacional_ajax.php?action=form_cartera_pagada",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend: function(jqXHR, settings) {
				funct_msg_loading(".nexos-messages");
			},
			error: function(jqXHR, textStatus, errorThrown) {
				$(".nexos-messages").html('');
				msg_error += "<p>" + jqXHR.responseText + "</p>";
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function(data, textStatus, jqXHR) {
				$(".nexos-messages").html('');
				// console.log(data);
				if (!data.error) {
					$("#nexos_messages_popup_cartera").empty();
					if (data.content) {
						$("#ver_cartera_title").html(data.content.title);
						$("#contenidocartera").html(data.content.content);
					}
				} else {
					msg_error += data.error;
				}
			}
		});
		if (msg_error) {
			funct_msg_error("#nexos_messages_popup_cartera", msg_error);
			$("#ver_cartera").animate({
				scrollTop: 0
			}, 600);
		}
		$.ajaxSetup({
			async: true
		});
	}
</script>