<?php
// se definen las variables de session
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

$vista = '
		<link rel="stylesheet" type="text/css" href="' . BASE_URL . '/views/layout/assets/lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>';
$table_content = "";

if (isset($this->internacional)) {
	$arrayListaDocumentos = $this->internacional->getProyectosDocumentos();

	$table_content = '
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12">
					<input type="hidden" id="flag_popup">
					<table class="table table-striped table-hover" data-page-length="100" id="table1">
						<thead>
							<tr class="nexos-encabezado">
								<th>Proyecto</th>
								<th>Cliente</th>
								<th>Negociación</th>
								<th>Cant. Detinos</th>
								<th>Valor Declarado</th>
								<th></th>
							</tr>
						</thead>
							<tbody>
		';

	if ($arrayListaDocumentos) {
		// Se verifican los permisos del pefil de usuario
		$arrayPermisos = $this->internacional->permisosPerfil($ssn_id_perfil, 66);
		$_permisos = $arrayPermisos;

		foreach ($arrayListaDocumentos as $key => $value) {

			// Se verifica si la actividad puede ser gestiuonada
			$_btn_gestiona = '';
			if ($value["CANT_DOCUMENTOS"] > 0 and $value["do"] and $_permisos["editar"]) {
				$_btn_gestiona = '<a href="javascript:" onclick="gestionarActividad(' . $value['id'] . ')" class="cell-detail hint--top-left" data-hint="Cerrar Actividad"><span class="icon mdi mdi-check-circle" data-toggle="modal" data-target="#gestiona_actividad"></span></a>';
			}

			$_col_actions = '
					<td class="actions">
						' . $_btn_gestiona . '
						<a href="javascript:" onclick="registrar_documentos(' . $value['id'] . ')" class="cell-detail hint--top-left" data-hint="Registrar Documentos"><span class="icon mdi mdi-edit" data-toggle="modal" data-target="#registro_documentos"></span></a>
					</td>
				';

			$_valor_declarado = '<span class="text-danger"><strong>No declarado</strong></span>';
			if ($value["valor_declarado"]) {
				$_valor_declarado = '
						<span>$' . number_format($value["valor_declarado"], 2, ',', '.') . '</span>
						<span class="cell-detail-description">' . $value["MONEDA"] . '</span>
					';
			}

			$_do = '<span class="text-danger"><strong>Cotización aún no aprobada</strong></span>';
			if ($value["do"]) {
				$_do = '<span>' . $value["do"] . '</span>';
			}

			$table_content .= '
					<tr>
						<td class="cell-detail">
							' . $_do . '
							<span class="cell-detail-description">' . $value["numero_importacion"] . ' <strong>(' . $this->internacional->getTimestampToDate($value["numero_importacion"]) . ')</strong></span>
							<span class="cell-detail-description">' . $value["importacion"] . '</span>
						</td>
						<td class="cell-detail">
							<span>' . $value["sigla"] . '</span>
							<span class="cell-detail-description">' . $value["DOCUMENTO_CLIENTE"] . '</span>
							<span class="cell-detail-description">' . $value["cod_cliente"] . '</span>
						</td>
						<td class="cell-detail">
							<span>' . $value["tipo_operacion"] . '</span>
							<span class="cell-detail-description">' . $value["incoterm"] . '</span>
							<span class="cell-detail-description">' . $value["tipo_transporte"] . '</span>
						</td>
						<td class="cell-detail">
							<span class="label label-default">' . $value["CANT_DESTINOS"] . '</span>
						</td>
						<td class="cell-detail text-right">
							' . $_valor_declarado . '
						</td>
						' . $_col_actions . '
					</tr>
				';
		}
	}

	$table_content .= '
						</tbody>
					</table>
				</div>
			</div>
		';
}

/**** CONTENIDO DEL MODULO EN PANTALLA ****/
$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Subir Documentos de Envío
				<div class="tools"></div>
				<span class="panel-subtitle">Se sube los documentos necesarios para realizar el transporte de un material, también para determinar si algún material que se está transportando es peligroso o requiere de refrigeración.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>

		<div id="registro_documentos" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="registro_documentos_title"></h3>
					</div>
					<div class="modal-body">
						<div id="nexos_messages_popup_registro_documentos"></div>
						<div id="contenidoregistromaterial"></div>
						<div class="row"></div>
					</div>
					<div class="modal-footer">
						<button id="btn_registra_material" type="button" class="btn btn-success md-close">Guardar</button>
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
					</div>
				</div>
			</div>
		</div>

		<div id="gestiona_actividad" tabindex="-1" role="dialog" class="modal fade in">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close"><span class="mdi mdi-close"></span></button>
					</div>
					<div class="modal-body">
						<div id="gestiona_actividad_popup"></div>
						<div class="text-center" id="gestiona_actividad_content"></div>
					</div>
					<div class="modal-footer"></div>
				</div>
			</div>
		</div>
	';

/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
$vista .= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
		<script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.wizard();
			});
		</script>
	';

/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%content%", $table_content, $vista);

echo $vista;
?>

<script type="text/javascript">
	$(document).ready(function() {
		$("#btn_registra_material").click(function() {
			// console.log("Entro en función del btn_registra_material");
			$("#nexos_messages_popup_registro_documentos").empty();
			var msg_error = "";

			/***** Validación de campos del formulario de registro de documentos *****/

			/***** Validación del formulario de materiales *****/
			var flag_gestiona_peligrosos = false;
			var id_materiales = "";
			$(".check_peligroso").each(function() {
				if (!$(this).prop("disabled")) {
					if ($(this).prop("checked")) {
						flag_gestiona_peligrosos = true;
						var array = $(this).attr("id").split("_");
						var id = array[array.length - 1];
						id_materiales += id + ",";

						var un = $("#un_" + id).val();
						var id_riesgo = $("#slct_riesgo_" + id + "_").val();
						var hoja_seguridad = $("#hoja_seguridad_file_" + id).val();
						var guia = $("#guia_" + id).val();
						var material = $("#material_" + id).val();

						if (!un) {
							msg_error += '<p>Debe diligenciar el campo <strong>UN</strong> del <strong>' + material + '</strong> de la guía <strong>' + guia + '</strong> para registrar el material.</p>';
						}
						if (!id_riesgo) {
							msg_error += '<p>Debe seleccionar un <strong>Riesgo</strong> del <strong>' + material + '</strong> de la guía <strong>' + guia + '</strong> para registrar el material.</p>';
						}
						if (!hoja_seguridad) {
							msg_error += '<p>Debe seleccionar un <strong>Archivo</strong> del <strong>' + material + '</strong> de la guía <strong>' + guia + '</strong> para registrar el material.</p>';
						} else {
							var adjunto = $("#hoja_seguridad_file_" + id)[0].files[0];
							// Se valida el peso del archivo
							if (adjunto.size < $("#max_file_size").val()) {
								// Se valida el tipo de archivo
								var extension = adjunto.name.split(".");
								var formato_archivo = 'pdf,PDF,zip,ZIP,rar,RAR,doc,DOC,docx,DOCX,jpg,jpeg,png,gif,bmp,tif,JPG,JPEG,PNG,GIF,BMP,TIF,xls,XLS,xlsx,XLSX,ppt,PPT,pptx,PPTX,pps,PPS,ppsx,PPSX,ods,ODS';
								if (validaFormatoArchivo(formato_archivo, extension[extension.length - 1]) == 0) {
									msg_error += '<p>Formato del archivo del campo <strong>Hoja de Seguridad</strong> del <strong>' + material + '</strong> de la guía <strong>' + guia + '</strong> no es válido para registrar el material.</p>';
									msg_error += '<p>Formatos válidos: <strong>' + formato_archivo + '</strong>.</p>';
								}
							} else {
								msg_error += '<p>El archivo del campo <strong>Hoja de Seguridad</strong> del <strong>' + material + '</strong> de la guía <strong>' + guia + '</strong> es muy pesado para subirlo al servidor. El peso máximo del archivo debe ser menor de <strong>' + ($("#max_file_size").val() / 1000000) + 'MB</strong>.</p>';
							}
						}
					}

				}
			});
			$("#id_materiales").val(id_materiales);
			/***** Fin - Validación del formulario de materiales *****/

			/***** Validación del formulario de documentos *****/
			var flag_gestiona_documentos = false;
			var id_documentos = "";
			$(".file_documento").each(function() {
				var documento_envio = $(this).val();

				if (documento_envio) {
					flag_gestiona_documentos = true;
					var array = $(this).attr("id").split("_");
					var id = array[array.length - 1];
					id_documentos += id + ",";
					var documento = $("#documento_" + id).val();
					var adjunto = $(this)[0].files[0];

					// Si exite el campo fecha de valida el contenido
					if ($(this).parents(".form_content").find(".fecha_gestion").length > 0) {
						let campo_fecha = $(this).parents(".form_content").find(".fecha_gestion");
						if (!campo_fecha.val()) {
							msg_error += `<p>Debe diligenciar el campo <strong>Fecha Gestión</strong> del documento <strong>${documento}</strong>.</p>`;
						}
					}

					// Se valida el peso del archivo
					if (adjunto.size < $("#max_file_size").val()) {
						// Se valida el tipo de archivo
						var extension = adjunto.name.split(".");
						var formato_archivo = 'pdf,PDF,zip,ZIP,rar,RAR,doc,DOC,docx,DOCX,jpg,jpeg,png,gif,bmp,tif,JPG,JPEG,PNG,GIF,BMP,TIF,xls,XLS,xlsx,XLSX,ppt,PPT,pptx,PPTX,pps,PPS,ppsx,PPSX,ods,ODS';
						if (validaFormatoArchivo(formato_archivo, extension[extension.length - 1]) == 0) {
							msg_error += '<p>Formato del archivo del documento <strong>' + documento + '</strong> no es válido para ser registrado.</p>';
							msg_error += '<p>Formatos válidos: <strong>' + formato_archivo + '</strong>.</p>';
						}
					} else {
						msg_error += '<p>El archivo del documento <strong>' + documento + '</strong> es muy pesado para subirlo al servidor. El peso máximo del archivo debe ser menor de <strong>' + ($("#max_file_size").val() / 1000000) + 'MB</strong>.</p>';
					}
				}
			});
			$("#id_documentos").val(id_documentos);

			// Se verifica si se puede gestionar alguna acción del formulario
			if (!flag_gestiona_documentos) {
				if (!flag_gestiona_peligrosos) {
					msg_error += '<p>No se a realizado ningún movimiento en el formulario para realizar alguna acción.</p>';
				}
			}
			/***** Fin - Validación del formulario de documentos *****/

			/***** Fin - Validación de campos del formulario de registro de documentos *****/

			if (!msg_error) {
				// console.log("Se guarda la información de los materiales del proyecto");
				var params = new FormData($("#form_registro_documentos")[0]);
				$.ajaxSetup({
					async: false
				});
				$.ajax({
					url: $("#id_url_ajax").val() + "libs/internacional_ajax.php?action=registrar_documentos",
					type: 'POST',
					contentType: false,
					data: params,
					cache: false,
					dataType: 'json',
					processData: false,
					beforeSend: function(jqXHR, settings) {
						$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
					},
					error: function(jqXHR, textStatus, errorThrown) {
						$(".nexos-messages").html('');
						msg_error += "<p>" + jqXHR.responseText + "</p>";
						console.log(jqXHR);
						console.log(textStatus);
						console.log(errorThrown);
					},
					success: function(data, textStatus, jqXHR) {
						$(".nexos-messages").html('');
						// console.log(data);

						if (data.error) {
							msg_error += data.error;
						}
					}
				});
				$.ajaxSetup({
					async: true
				});

				if (!msg_error) {
					$("#nexos_messages_popup_registro_documentos").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado! </strong>Se ha creado el registro con éxito.</div></div>');
					$("#registro_documentos").animate({
						scrollTop: 0
					}, 600);
					setTimeout(function() {
						location.reload(false);
					}, 800);
				}
				if (msg_error) {
					$("#nexos_messages_popup_registro_documentos").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
					$("#registro_documentos").animate({
						scrollTop: 0
					}, 600);
				}
			}
			if (msg_error) {
				$("#nexos_messages_popup_registro_documentos").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
				$("#registro_documentos").animate({
					scrollTop: 0
				}, 600);
			}
		});
	});

	function registrar_documentos(id) {
		// console.log("Entro en función registrar_documentos");
		if ($("#flag_popup").val() != id) {
			$("#flag_popup").val(id);
			$("#nexos_messages_popup_registro_documentos").empty();
			$("#registro_documentos_title").empty();
			$("#contenidoregistromaterial").empty();
			var msg_error = "";

			var params = {
				id: id,
			}
			// console.log(params);

			$.ajaxSetup({
				async: false
			});
			$.ajax({
				url: $("#id_url_ajax").val() + "libs/internacional_ajax.php?action=form_registro_documentos",
				type: 'POST',
				data: params,
				cache: false,
				dataType: 'json',
				beforeSend: function(jqXHR, settings) {
					$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
				},
				error: function(jqXHR, textStatus, errorThrown) {
					$(".nexos-messages").html('');
					msg_error += "<p>" + jqXHR.responseText + "</p>";
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
				},
				success: function(data, textStatus, jqXHR) {
					// console.log(data);
					$(".nexos-messages").html('');
					$("#nexos_messages_popup_registro_documentos").html("");
					if (data.content) {
						$("#registro_documentos_title").html(data.content.title);
						$("#contenidoregistromaterial").html(data.content.content);

						if ($("#contenidoregistromaterial").find(".datetimepicker").length > 0) {
							App.formElements();
						}
					}
				}
			});
			$.ajaxSetup({
				async: true
			});

			if (msg_error) {
				$("#nexos_messages_popup_registro_documentos").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
				$("#registro_documentos").animate({
					scrollTop: 0
				}, 600);
			}
		}
	}

	function actualizaActividad(params) {
		// console.log(params);
		var msg_error = "";

		// Se actualizan las actividades del proyecto
		$.ajax({
			type: "POST",
			cache: false,
			url: $("#id_url_ajax").val() + "libs/gestion_actividades.php?tabla=cmx_importacion_actividades&proyecto=importacion",
			data: params,
			beforeSend: function(jqXHR, settings) {
				$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
			},
			error: function(data) {
				console.log(data);
				$("#nexos_messages_popup_registro_documentos").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong> Error en la creación del registro.</div></div>');
			},
			success: function(data) {
				console.log(data);
			}
		});
	}

	function gestionarActividad(id) {
		// console.log("Entro en función gestionarActividad");
		$("#gestiona_actividad_popup").empty();
		$("#gestiona_actividad_content").empty();

		var msg_error = "";

		var params = {
			id: id,
		}

		$.ajax({
			url: $("#id_url_ajax").val() + "libs/internacional_ajax.php?action=form_gestiona_actividad_documentos",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend: function(jqXHR, settings) {
				$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
			},
			error: function(jqXHR, textStatus, errorThrown) {
				$(".nexos-messages").html('');
				msg_error += "<p>" + jqXHR.responseText + "</p>";
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function(data, textStatus, jqXHR) {
				// console.log(data);
				$(".nexos-messages").html('');
				$("#gestiona_actividad_content").html(data.content);

				$("#btn_gestiona_actividad").click(function() {
					actualizaActividad(data.actividad);
					$("#gestiona_actividad_popup").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado! </strong>Se ha creado el registro con éxito.</div></div>');
					$("#edita_cotizacion").animate({
						scrollTop: 0
					}, 600);
					setTimeout(function() {
						location.reload(false);
					}, 800);
				});
			}
		});
		if (msg_error) {
			$("#gestiona_actividad_popup").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("#edita_cotizacion").animate({
				scrollTop: 0
			}, 600);
		}
	}
</script>