<div class="pb-6">
    <div class="row align-items-center justify-content-between g-3 mb-6">
        <div class="col-12 col-md-auto">
            <!-- <h2 class="mb-0">Analytics</h2> -->
        </div>
        <div class="col-12 col-md-auto">
            <!-- <div class="flatpickr-input-container">
                <input class="form-control ps-6 datetimepicker" id="datepicker" type="text"
                    data-options='{"dateFormat":"M j, Y","disableMobile":true,"defaultDate":"Mar 1, 2022"}' /><span
                    class="uil uil-calendar-alt flatpickr-icon text-body-tertiary"></span>
            </div> -->
        </div>
    </div>
    <div class="px-3 mb-6">
        <div class="row">
            <div class="col-12 col-md-12">
                <div class="card h-100">
                    <div class="row card-body" id="indicadores_graficos"></div>
                    <div class="col-12 col-md-12">
                        <table class="text-end" cellpadding="0" cellspacing="0" border="0" style="width:100%;font-size: 13px;">
                            <thead>
                                <tr>
                                    <td class="text-right" style="border: 0px solid #ddd;padding: 1px;width: auto; white-space: nowrap;" colspan="5">
                                        <a href="JavaScript:void(0);" id="exportar_excel" style="text-decoration: none;cursor: pointer;color: #332D2D;"><img src="<?php echo BASE_URL; ?>public/img/excel_2013.png" alt="Excel" width="15px"> <span style="font-size: 11px;"> Exportar a excel</span></a>
                                    </td>
                                </tr>
                            </thead>
                        </table>
                        <div class="table-responsive scrollbar">
                            <table id='table1' class='table table-bordered table-sm' data-page-length='100' style="font-size:11px;">
                                <thead>
                                    <tr>
                                        <th class='text-center' style='width: auto; white-space: nowrap;'>Modalidad</th>
                                        <th class='text-center' style='width: auto; white-space: nowrap;'>Pedido</th>
                                        <th class='text-center' style='width: auto; white-space: nowrap;'>Estado</th>
                                        <th class='text-center' style='width: auto; white-space: nowrap;'>Ciudad Origen</th>
                                        <th class='text-center' style='width: auto; white-space: nowrap;'>Ciudad Destino</th>
                                        <th class='text-center' style='width: auto; white-space: nowrap;'>Codigo Producto</th>
                                        <th class='text-center' style='width: auto; white-space: nowrap;'>Producto</th>
                                        <th class='text-center' style='width: auto; white-space: nowrap;'>Fecha Cargue</th>
                                        <th class='text-center' style='width: auto; white-space: nowrap;'>Fecha Entrega</th>
                                    </tr>
                                </thead>
                                <tbody id='tbl_graficos_pedidos' class='text-center'>
                                    <tr>
                                        <td colspan="9" class="text-center" style="font-size:15px;font-weight:bold;">
                                            <img src="<?= BASE_URL ?>public/img/nexos_loading.gif" height="25" width="25" id="load_info" style="display: none;"> Esperando Información
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>