<div class="container-fluid mt-5">
  <div class="d-flex justify-content-center">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
      <div class="row">
        <div class="col-xl-12 mt-5">
          <div class="card border border-body-secondary">
            <div class="card-header p-1 bg-body-secondary d-flex justify-content-between align-items-center">
              <h5 class="mb-1">Plantillas de pedidos</h5>
            </div>

            <div class="card-body p-1">
              <form class="row g-3 mb-6">
                <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
                  <div class="mb-4">
                    <div class="d-flex flex-wrap mb-2">
                      <h5 class="mb-0 text-body-highlight me-2">Proveedores <span style="color:red;"><i>*</i></h5>
                    </div>
                    <select class="form-select form-select-sm select2" id="slt_Proveedores" style="width:100%;"></select>
                  </div>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
                  <div class="mb-4">
                    <div class="d-flex flex-wrap mb-2">
                      <h5 class="mb-0 text-body-highlight me-2">Nombre Plantilla <span style="color:red;"><i>*</i></h5>
                    </div>
                    <input type="text" class="form-control form-control-sm" name="nombre_plantilla" id="nombre_plantilla">
                  </div>
                </div>

                <!-- <div class="container"></div> -->
                <div class="col-sm-12 col-md-7 col-lg-7 col-xl-7 col-xxl-7">
                  <h4 class="text-center" style="font-weight: bold;background-color: #332D2D;color:#FFFFFF;padding: 12px;">
                    Parametros de trazabilidad</h4>
                  <div id="accordionExample">
                    <!-- Contenido JS -->
                  </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5" id="lista_previsualizacion">
                  <div class="panel panel-primary" style="background-color: #332D2D;color:#FFFFFF;margin-bottom:5px;">
                    <h4 class="text-center" style="font-weight:bold; background-color: #332D2D;color:#FFFFFF;padding: 12px;">Previsualizar orden actividades</h4>
                  </div>
                  <div class="panel-body border" style="max-height: 500px;overflow-x: hidden;overflow-y: auto ;padding: 1px 1px 1px;">
                    <div class="row">
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div id="secondaryList"></div>
                      </div>
                    </div>
                  </div>
                  <div class="panel-footer" style="padding: 1px 1px 1px;font-weight: bold;">
                    <h4 id="posicion"></h4>
                  </div>
                </div>
              </form>

              <div class="col-12 gy-6">
                <div class="row g-3 justify-content-end">
                  <!-- <div class="col-auto">
                    <button class="btn btn-phoenix-primary btn-sm px-5" type="button" id="btn-cancelar">
                      <span class="text-danger" data-feather="x"></span> Cancelar</button>
                  </div> -->
                  <div class="col-auto">
                    <button class="btn btn-primary btn-sm px-5" id="btn-create-plantilla" type="button">
                      <span data-feather="save"></span> Crear Plantilla</button>
                  </div>
                </div>
              </div>


            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<script src=<?php echo BASE_URL ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL ?>views/torrecontrol/js/plantilla_pedidos.js type="text/javascript"></script>
<script>
  $(document).ready(function() {
    $('.select2').select2({
      placeholder: "Seleccione",
      allowClear: true
    });
  });
</script>