<div class="container-fluid py-3">
    <!-- Variables ocultas de sesión -->
    <input type="hidden" id="ssn_id_cliente" value="<?= $_SESSION['usuario']['id_cliente'] ?>">
    <input type="hidden" id="ssn_id_usuario" value="<?= $_SESSION['usuario']['id_usuario'] ?>">
    <input type="hidden" id="ssn_nombre" value="<?= $_SESSION['usuario']['nom_usuario'] ?>">
    <input type="hidden" id="ssn_id_perfil" value="<?= $_SESSION['usuario']['id_perfil'] ?>">
    <input type="hidden" id="fecha_dia_solicitud" value="<?= date('Y-m-d') ?>">
    <input type="hidden" id="hora_dia_solicitud" value="<?= date('H:i:s') ?>">

    <div class="d-flex justify-content-between align-items-center mb-1">
        <h5 class="mb-0 fw-bold"><!-- Órdenes de Cargue --></h5>
        <button class="btn btn-success btn-sm" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvaBodegas" aria-controls="offcanvaBodegas">
            <i class="fa-solid fa-plus me-1"></i> Nuevo Compromiso
        </button>
    </div>

    <div class="row">
        <div class="col-3 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
            <div class="table-responsive mt-5">
                <table class='table table-bordered table-striped table-sm text-center' style=" font-size:12px;" id="tabla-general-compromisos">
                    <thead class="table-primary">
                        <tr>
                            <th>#</th>
                            <th>Estudio</th>
                            <th>Responsable</th>
                            <th>Tiempo Transcurrido</th>
                            <th>Hoja de Vida</th>
                            <th>Compromiso</th>
                            <th>Estado</th>
                        </tr>
                    </thead>
                    <tbody id="tbody-compromisos-estudios"></tbody>
                </table>
            </div>
        </div>
    </div>
</div>