<?php

$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
//2. se definen variables para diseñar el contenido
$vista = '';
$table_content = '';
$table_content2 = '';
$formulario = '';
$table_cliente = '';
$table_solicitud = '';
$filtro = '';

if (isset($this->pedir_vehiculo)) {
  // $arrayPermisos = $this->pedir_vehiculo->permisosPerfil($ssn_id_perfil, 80);
  // $_permisos = $arrayPermisos;

  // $table_solicitud .= "
  // 	<div  class='table-responsive noSwipe'>
  // 		<table id='table2' class='table table-striped table-hover' data-page-length='100'>
  // 				<thead>
  // 					<tr class='nexos-encabezado'>
  // 					<th>Solicitud</th>
  // 					<th>Mercancía</th>
  // 					<th>Item</th>
  // 					<th>Origen</th>
  // 					<th>Destino</th>
  // 					<th>Peso(Kg) / Tipo vehiculo</th>
  // 					<th>Cliente</th>
  // 					<th>Tipo</th>
  // 					<th>Acciones</th>
  // 					</tr>
  // 				</thead>
  // 				<tbody>";

  // $arra = $this->pedir_vehiculo->getsolicitudes($ssn_id_perfil);

  // if ($arra) {
  //   $cont = 0;
  //   foreach ($arra as $key => $value) {
  //     $cont++;
  //     $btn_seleccion = '';

  //     if ($value['elesta'] != 'Realizada') {
  //       $table_solicitud .= "<tr>
  // 				<td>$value[nundoc_solicitud]</td>
  // 				<td>$value[idpareja_origen_destino]- $value[tipo_mercancia]</td>
  // 				<td>$value[item]</td>
  // 				<td>$value[ori]</td>
  // 				<td>$value[des]</td>
  // 				<td>$value[peso_kg]/$value[tipo_vehiculo]</td>
  // 				<td>$value[nombre_cliente]</td>
  // 				<td class='text-success' style='font-weight:800;'>$value[tipo_servicio_mer]</td>
  // 				<td><button id='btn_uno" . $cont . "'  class='btn btn-secondary mdi mdi-plus' onclick='atraparsolici(" . $cont . ",this);'
  // 						data-id='" . $value['nundoc_solicitud'] . "'
  // 					 data-id2='" . $value['nombre_cliente'] . "'
  // 					 data-id3='" . $value['n_cotizacion'] . "'
  // 					 data-id4='" . $value['item'] . "'
  // 					 data-id5='" . $value['tipo_mercancia'] . "'
  // 					 data-id6='" . $value['flete'] . "'
  // 					 data-id7='" . $value['peso_neto_tn'] . "'
  // 					 data-id8='" . $value['total_tarifa'] . "'
  // 					 >
  // 				</button></td>
  // 				</tr>";
  //     }
  //   }
  // }
  // $table_solicitud .= "</tbody>
  // </table>
  // </div>";


  /**************************************************************************************************************************************************************************************************************************************************************************************************/
  // $array = $this->pedir_vehiculo->getasignarvehiculo($ssn_id_usuario, $filtro = "todos", $fecha_inicial = date("Y-m-01"), $fecha_final = date("Y-m-t"));
  // $table_content .= '
  // 	 <div id="la_tabla">
  // 		<div class="row">
  // 			<div class="col-xs-12 col-sm-12 col-md-12">
  // 				<div class="table-responsive noSwipe">
  // 					<input type="hidden" id="flag_popup">
  // 					<table id="table1" class="table table-striped table-hover table-fw-widge" data-page-length="100" style="font-size: 11px;">
  // 						<thead style="background-color:#332D2D;color:#fff;text-align:center;">
  // 							<tr>
  // 								<th style="text-align: center;vertical-align: middle;">#</th>
  // 								<th style="text-align: center;vertical-align: middle;">Escenario</th>
  // 								<th style="text-align: center;vertical-align: middle;">Solicitud</th>
  //                                   <th style="text-align: center;vertical-align: middle;">Itr</th>
  // 								<!--<th style="text-align: center;vertical-align: middle;">Cantidad</th>-->
  // 								<th style="text-align: center;vertical-align: middle;">Cliente</th>
  // 								<th style="text-align: center;vertical-align: middle;width: 100px;">Mercancía</th>
  // 								<th style="text-align: center;vertical-align: middle;">Vehículo</th>
  // 								<th style="text-align: center;vertical-align: middle; width: 10px;" >P.Neto</th>
  // 								<th style="text-align: center;vertical-align: middle;width: 150px;">Ruta</th>
  // 								<th style="text-align: center;vertical-align: middle;">Fecha</th>
  // 								<th style="text-align: center;vertical-align: middle;">Estado</th>
  // 								<th style="text-align: center;vertical-align: middle;width: 100px;">Acciones</th>
  // 							</tr>
  // 						</thead>
  // 					<tbody id="tbl-solicitudes">';

  // $vista .= '
  //     <!-- Filtro de los estados de las solicitudes de servicio -->
  //       <div class="row" style="margin-bottom:10px;">
  //             <div class="panel panel-default">
  //             <div class="panel-body" style>
  //             <div class="col-xs-3 d-flex justify-content-start">
  //             <label for="formGroupInputSmall" style="vertical-align: center;"><b>Filtro</b></label>
  //             <div class="form-group form-group-sm">
  //                 <select class="form-control input-sm filtro_estado" name="filtro_estado" id="filtro_estado">
  //                   <option value="todos" selected title="Todas las solicitudes de servicio">Todos</option>
  //                   <option value="Pendiente" title="No se ha asignado ningún vehículo en la actualidad">Pendiente asignar</option>
  //                   <option value="asignada" title="Por lo menos tiene una placa asignada">Asignada solicitud preestudio</option>
  //                   <option value="en_tramite" title="Ha iniciado el estudio de seguridad de al menos una placa">En tramite solicitud prefiltro</option>
  //                   <option value="aprobado_prefiltro" title="Aprobado para registrar hojas de vida">Aprobado prefiltro</option>
  //                 </select>
  //             </div>
  //           </div>

  //           <div class="col-xs-3 d-flex justify-content-start">
  //             <label style="vertical-align: center;"><b>Fecha Inicial</b></label>
  //             <div class="form-group form-group-sm">
  //               <input class="form-control input-sm" type="date" id="fecha_inicial" name="fecha_inicial" value="' . date("Y-m-d") . '">
  //             </div>
  //           </div>

  //           <div class="col-xs-3 d-flex justify-content-start">
  //             <label style="vertical-align: center;"><b>Fecha Final</b></label>
  //             <div class="form-group form-group-sm">
  //               <input class="form-control input-sm" type="date" id="fecha_final" name="fecha_final" value="' . date("Y-m-d") . '">
  //             </div>
  //           </div>

  //           <div class="col-xs-3 text-center" style="margin-top:25px;">
  //             <div class="form-group form-group-sm">
  //               <button type="button" class="btn btn-primary" id="btn-filtrar"><span class="mdi mdi-search"></span> Consular solicitudes</button>
  //             </div>
  //           </div>
  //             </div>
  //           </div>
  //       </div>

  //       <input type="hidden" id="usuario" class="form-control input-sm" readonly="readonly" value="' . $ssn_nombre . '" >
  //       %content%
  //   ';
} ?>

<!-- Modal de mensaje de vencimiento de la solicitud de servicio -->
<!-- <div class="modal fade" id="md-footer-primary" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog" style="width: 600px;">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" type="button" data-dismiss="modal" aria-hidden="true"><span class="mdi mdi-close"></span></button>
      </div>
      <div class="modal-body">
        <div class="text-center">
          <div class="text-primary"><span class="modal-main-icon mdi mdi-info-outline"></span></div>
          <h2 style="font-weight: bold;">Información!</h2>
          <p id="mensaje_vigencia" style="font-weight: 500;"></p>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" type="button" data-dismiss="modal">Aceptar</button>
      </div>
    </div>
  </div>
</div> -->


<!-- <div id="ver_cotizacion" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
  <div class="modal-dialog custom-width">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
        <h2 class="modal-title text-center" id="ver_title">
          <label id="titulo" style="font-size:19pt; color:white; text-align:center;">ASIGNAR VEHÍCULO</label>
        </h2>
      </div>
      <div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
        <div id="msg_ver"></div>
        <div id="content_ver">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div clas="row">
              <div class="col-xs-12 col-md-6 col-sm-6 col-lg-6">
                <label style="font-weight:800; margin-top:20px; ">Origen</label>
                <p id="orisoli" class="text-primary"></p>
              </div>
              <div class="col-xs-12 col-md-6 col-sm-6 col-lg-6">
                <label style="font-weight:800; margin-top:20px; ">Destino</label>
                <p id="destisoli" class="text-primary"></p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3 col-sm-12 col-xs-12 ">
                <label style="font-weight:800; margin-top:20px; ">N° Cotización</label>
                <input type="text" id="num_cotizar" value="" readonly="readonly" class="form-control input-sm text-center" style="font-size:15px;">
              </div>
              <div class="col-md-3 col-sm-12 col-xs-12 ">
                <label style="font-weight:800; margin-top:20px; ">N° Solicitud</label>
                <input type="text" id="num_soli" value="" readonly="readonly" class="form-control input-sm text-center" style="font-size:15px;">
              </div>

              <div class="col-md-6 col-sm-12 col-xs-12 ">
                <label style="font-weight:800; margin-top:20px; ">Tipo Vehículo</label>
                <input type="text" id="veh" value="" readonly="readonly" class="form-control input-sm text-center" style="font-size:15px;">
              </div>
              <div class="col-md-12 col-sm-12 col-xs-12 ">
                <label style="font-weight:800; margin-top:20px; ">Observación</label>
                <textarea id="observe" class="form-control input-sm"></textarea>
              </div>

              <div class="col-md-3 col-sm-12 col-xs-12 ">
                <input type="hidden" id="origen" value="" readonly="readonly" class="form-control input-sm text-center" style="font-size:15px;">
              </div>
              <div class="col-md-3 col-sm-12 col-xs-12 ">
                <input type="hidden" id="destino" value="" readonly="readonly" class="form-control input-sm text-center" style="font-size:15px;">
              </div>
            </div>
            <div class="row" style="padding:20px;">
              <div class="col-md-6 col-sm-6 col-xs-6">
                <label style="font-weight:800; margin-top:20px; ">Vehículo Nuevo</label>
                <div class="col-xs-3">
                  <div class="be-radio-icon inline">
                    <input type="radio" checked="" name="rad1" id="rad1" onclick="nuevo();">
                    <label for="rad1"><span class="mdi mdi-circle-o"></span></label>
                  </div>
                </div>

              </div>
              <div class="col-md-6 col-sm-6 col-xs-6">
                <label style="font-weight:800; margin-top:20px; ">Vehículo Histórico</label>
                <div class="col-xs-3">
                  <div class="be-radio-icon inline">
                    <input type="radio" name="rad1" id="rad2" onclick="historico();">
                    <label for="rad2"><span class="mdi mdi-circle-o"></span></label>
                  </div>
                </div>
              </div>
              <div class="col-md-12 col-sm-12 col-xs-12 ocultar" style="padding:30px;">
                <div class="col-md-6 col-sm-12 col-xs-12">
                  <label style="font-weight:800; margin-top:20px; ">Buscar Vehículo</label>
                  <button id="buscar_placa" class="form-control btn btn-info mdi mdi-car input-sm" data-toggle="modal" data-target="#exampleModalLong">Buscar</button>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12 ">
                  <label style="font-weight:800; margin-top:20px; ">Placa Seleccionada</label>
                  <input type="text" id="placa_sele" class="form-control input-sm" readonly="">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row"></div>
      </div>
      <div class="modal-footer">
        <button type="button" id="asignar" class="btn btn-success btn-md">Asignar</button>
        <button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
      </div>
    </div>
  </div>
</div> -->


<!-- <div class="modal fade" id="modalservicio" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class=".modal-dialog-centered.modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#FFD700;">
        <h5 class="modal-title" id="exampleModalLongTitle">VEHÍCULO</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row" style="border:1px solid silver;">
          <div class="form-group col-xs-12 col-sm-12" style="padding:20px; ">
            <label style="font-weight:700; font-size:14pt;">Placa Vehículo:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
            <input type="text" placeholder="Placa" class="typeahead form-control input-sm" id="cargar_cliente">
          </div>
          <div class="form-group col-xs-12 col-sm-12">
            <?php echo $table_cliente; ?>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div> -->

<!-- <div class="modal fade" id="status" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:center;height: 50px;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color:#fff;">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="exampleModalLabel"><strong><span class="mdi mdi-dialpad text-left"></span>
            Trazabilidad</strong></h4>
      </div>
      <div class="modal-body" style="max-height: 800px; overflow-y: auto;">
        <div class="panel panel-default">
          <div clas s="panel-heading" style="background-color:#14A44D;color:#fff;text-align:left;height: 20px;margin: 1px 1px 1px;">
            <h6 style="margin-top: 0px; font-weight: 500;color: #fff;padding: 3px 2px 2px 10px;">Cotización</h6>
          </div>
          <div class="panel-body">
            <div class="row">
              <table id="table" class="table table-condensed table-bordered table-striped" style="text-align: center;">
                <thead>
                  <tr>
                    <th class="text-center">Cotización</th>
                    <th class="text-center">Item</th>
                    <th class="text-center">Mercancía</th>
                    <th class="text-center">Estado</th>
                    <th class="text-center">Fecha</th>
                    <th class="text-center">Hora</th>
                    <th class="text-center">Usuario</th>
                    <th class="text-center">Proceso</th>
                  </tr>
                </thead>
                <tbody id="movimientos_coti">
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div clas s="panel-heading" style="background-color:#14A44D;color:#fff;text-align:left;height: 20px;margin: 1px 1px 1px;">
            <h6 style="margin-top: 0px; font-weight: 500;color: #fff;padding: 3px 2px 2px 10px;">Solicitud servicios
            </h6>
          </div>
          <div class="panel-body">
            <div class="row">
              <table id="table" class="table table-condensed table-bordered table-striped" style="text-align: center;">
                <thead>
                  <tr>
                    <th class="text-center">Solicitud</th>
                    <th class="text-center">Cotización</th>
                    <th class="text-center">Item</th>
                    <th class="text-center">Mercancía</th>
                    <th class="text-center">Fecha</th>
                    <th class="text-center">Hora</th>
                    <th class="text-center">Usuario</th>
                    <th class="text-center">Estado</th>
                    <th class="text-center">Proceso</th>
                  </tr>
                </thead>
                <tbody id="movimientos_status">
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div clas s="panel-heading" style="background-color:#14A44D;color:#fff;text-align:left;height: 20px;margin: 1px 1px 1px;">
            <h6 style="margin-top: 0px; font-weight: 500;color: #fff;padding: 3px 2px 2px 10px;">Solicitud preestudio
            </h6>
          </div>
          <div class="panel-body">
            <div class="row" id="tbtres">
              <table id="table" class="table table-condensed table-bordered table-striped" style="text-align: center;">
                <thead>
                  <tr>
                    <th class="text-center">Preestudio</th>
                    <th class="text-center">solicitud preestudio</th>
                    <th class="text-center">s. servicio</th>
                    <th class="text-center">Fecha</th>
                    <th class="text-center">Hora</th>
                    <th class="text-center">Usuario</th>
                    <th class="text-center">Proceso</th>
                  </tr>
                </thead>
                <tbody id="movimientos_preestudio">
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row" id="tbtres">
              <table id="table" class="table table-condensed table-bordered table-striped" style="text-align: center;">
                <thead>
                  <tr>
                    <td class="text-center active" style="font-size:10px;color: #332D2D;">Placa</td>
                    <td class="text-center active" style="font-size:10px;color: #332D2D;">Fecha</td>
                    <td class="text-center active" style="font-size:10px;color: #332D2D;">Usuario</td>
                    <td class="text-center active" style="font-size:10px;color: #332D2D;">Operación</td>
                  </tr>
                </thead>
                <tbody id="estados_preestudio">
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div> -->

<!-- <div class="modal fade" id="historial_estados" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered" role="document" style="width: 400px;">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:center;height:40px;">
        <h5 class="modal-title" id="exampleModalLabel"><b>Detalle historial estados</b></h5>
      </div>
      <div class="modal-body">
        <div class="form-group col-md-12 col-sm-12 col-xs-12">
          <div class="e_titulogeneral col-md-12">
          </div>
        </div>
        <div class="row">
          <table class="table table-condensed table-bordered">
            <thead>
              <tr>
                <td class="text-center active" style="font-size:10px;color: #332D2D;">Solicitud</td>
                <td class="text-center active" style="font-size:10px;color: #332D2D;">Placa</td>
                <td class="text-center active" style="font-size:10px;color: #332D2D;">Estado</td>
                <td class="text-center active" style="font-size:10px;color: #332D2D;">Fecha</td>
              </tr>
            </thead>
            <tbody id="tbody_historia_estado">
            </tbody>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div> -->

<!-- <div class="modal fade" id="status_solo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"><strong>Trazabilidad</strong></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group col-md-12 col-sm-12 col-xs-12">
          <div class="e_titulogeneral col-md-12">
            <strong>Movimientos</strong>
            <hr / style="border: 0; height: 12px; box-shadow: inset 0 12px 12px -12px blue;">
          </div>
        </div>
        <div class="row">
          <table class="table">
            <thead>
              <tr>
                <th style="width:10%;">Área</th>
                <th style="width:50%;">Observación</th>
                <th style="width:10%;">Fecha</th>
                <th class="number">Hora</th>
                <th class="number">Usuario</th>
                <th class="number">Estado</th>
                <th class="actions"></th>
              </tr>
            </thead>
            <tbody id="movimientos_statussolo">
            </tbody>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div> -->

<!-- <div id="cambiar_flete" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
  <div class="modal-dialog custom-width">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
        <h3 class="modal-title" id="editar_title">
          <label id="titulo" style="font-size:20pt; color:white; text-align:center;">Proponer Flete</label>
        </h3>
      </div>
      <div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
        <div id="msg_posponerflete"></div>
        <div id="content_pospone">
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <h4>Datos Básicos</h4>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
              <label style="font-weight:800; margin-top:20px;">Cliente</label>
              <input type="text" id="s_cliente" class="form-control input-xs" readonly="readonly">
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
              <label style="font-weight:800; margin-top:20px;">N° solicitud servicio</label>
              <input type="text" id="s_nsolicitud" class="form-control input-xs" readonly="readonly">
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <label style="font-weight:800; margin-top:20px;">Vehículo</label>
              <input type="text" id="s_vehiculo" class="form-control input-xs" readonly="readonly">
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <label style="font-weight:800; margin-top:20px;">Tipo carga</label>
              <input type="text" id="s_tipocarga" class="form-control input-xs" readonly="readonly">
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <label style="font-weight:800; margin-top:20px;">Mercancía</label>
              <input type="text" id="s_mercancia" class="form-control input-xs" readonly="readonly">
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <label style="font-weight:800; margin-top:20px;">Peso Bruto</label>
              <input type="text" id="s_pesobruto" class="form-control input-xs" readonly="readonly">
              <label style="font-weight:800; margin-top:20px;">Peso Neto(kg)</label>
              <input type="text" id="s_pesnonetok" class="form-control input-xs" readonly="readonly">
              <label style="font-weight:800; margin-top:20px;">Peso Neto(Tn)</label>
              <input type="text" id="s_pesonetot" class="form-control input-xs" readonly="readonly">
            </div>
            <section class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <label style="font-weight:800; margin-top:20px;">Flete cotización</label>
              <input type="text" id="s_flete" class="form-control input-xs" readonly="readonly">
              <input type="hidden" id="s_rentactual" class="form-control input-xs" readonly="readonly">
              <input type="hidden" id="s_cotizacion" class="form-control input-xs" readonly="readonly">
              <input type="hidden" id="s_idservicio" class="form-control input-xs" readonly="readonly">
            </section>
            <section class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <label style="font-weight:800; margin-top:20px;">Flete sugerido</label>
              <input type="text" id="s_fletecap" class="form-control input-xs">
              <input type="hidden" id="s_tarifa" class="form-control input-xs" readonly="readonly">
              <input type="hidden" id="s_calculo" class="form-control input-xs" readonly="readonly">
              <input type="hidden" id="s_rentabilidad" class="form-control input-xs" readonly="readonly">
              <input type="hidden" id="s_total" class="form-control input-xs" readonly="readonly">
            </section>
          </div>

          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <h4>Fletes Registrados</h4>
            </div>
          </div>
          <div class="row">
            <table class="table table-condensed table-hover table-bordered table-striped">
              <thead>
                <tr>
                  <th>Estado</th>
                  <th>Flete propuesto</th>
                  <th>Fecha</th>
                  <th>Hora</th>
                  <th>Usuario</th>
                  <th>Acción</th>
                </tr>
              </thead>
              <tbody id="cuerpo_fletespropuestos">
              </tbody>
            </table>

          </div>

        </div>
        <div class="modal-footer">
          <button id="btn_guadarp" type="button" class="btn btn-success md-close" onclick="">Guardar</button>
          <button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
        </div>
      </div>
    </div>
  </div>
</div> -->

<!--COTIZACION Y SOLICTUD DE SERVICIO-->
<!-- <div id="consulta_coti" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
  <div class="modal-dialog custom-width">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
        <h2 class="modal-title text-center" id="ver_title">
          <label id="titulo" style="font-size:19pt; color:white; text-align:center;">Solicitud de servicio</label>
        </h2>
      </div>
      <div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
        <div id="msg_cotizacion"></div>
        <div id="content_ver">
          <div id="titlu"></div>
          <div class="titulogeneral col-md-12">
            <strong>Datos Cliente</strong>
            <hr style="border: 0; height: 12px; box-shadow: inset 0 12px 12px -12px #33B5E5;margin-top:2px">
          </div>
          <table class="table table-condensed table-hover table-bordered table-striped">
            <thead>
              <tr>
                <th>Nombre Cliente</th>
                <th>Nit</th>
                <th class="">Dirección</th>
                <th class="">Teléfono</th>
                <th class="">Procedencia</th>
              </tr>
            </thead>
            <tbody id="cuerpo_cliente">
            </tbody>
          </table>

          <div class="titulogeneral col-md-12">
            <strong>Datos de la Mercancía</strong>
            <hr style="border: 0; height: 12px; box-shadow: inset 0 12px 12px -12px #33B5E5;margin-top:2px">
          </div>
          <div class="col-md-9 col-xs-12 col-sm-12 col-lg-12">
            <table class="table table-condensed table-hover table-bordered table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Tipo Servicio</th>
                  <th>Tipo Vehículo</th>
                  <th>Tipo carga</th>
                  <th>Tipo transporte</th>
                  <th>Tipo Mercancía</th>
                  <th>Peso Bruto</th>
                  <th>Peso neto(Kg)</th>
                  <th>Peso Neto(Tn)</th>
                </tr>
              </thead>
              <tbody id="cuerpo_mer1">
              </tbody>
            </table>
          </div>

          <div class="col-md-2 col-xs-12 col-sm-6 col-lg-6">
            <table class="table table-condensed table-hover table-bordered table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Origen</th>
                </tr>
              </thead>
              <tbody id="muniorigen">
              </tbody>
            </table>
          </div>
          <div class="col-md-2 col-xs-12 col-sm-6 col-lg-6">
            <table class="table table-condensed table-hover table-bordered table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Destino</th>
                </tr>
              </thead>
              <tbody id="munidestino">
              </tbody>
            </table>
          </div>
          <table class="table table-condensed table-hover table-bordered table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>Alto</th>
                <th>Largo</th>
                <th>Ancho</th>
                <th>Volumen total</th>
                <th>Empaque</th>
                <th>Cantidad</th>
                <th>Costo Flete</th>
              </tr>
            </thead>
            <tbody id="cuerpo_mer2">
            </tbody>
          </table>

          <div class="titulogeneral col-md-12">
            <strong>Datos Servicios especiales</strong>
            <hr style="border: 0; height: 12px; box-shadow: inset 0 12px 12px -12px #33B5E5;margin-top:2px">
          </div>
          <table class="table table-condensed table-hover table-bordered table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>Tipo Servicio</th>
                <th>Cantidad</th>
                <th>Costo Unitario</th>
                <th>Total Servicio</th>
              </tr>
            </thead>
            <tbody id="cuerpo_especial">
            </tbody>
          </table>
          <div id="solicitud"></div>
          <div class="titulogeneral col-md-12">
            <strong>Solicitud de servicio</strong>
            <hr style="border: 0; height: 12px; box-shadow: inset 0 12px 12px -12px #33B5E5;margin-top:2px">
          </div>
          <table class="table table-condensed table-hover table-bordered table-striped">
            <thead>
              <tr>
                <th>N° solicitud</th>
                <th>Fecha/Hora</th>
                <th>Usuario</th>
                <th>Agencia</th>
                <th>Proceso</th>
                <th>Cant. solicitada</th>
                <th>Cant. Disponible</th>
              </tr>
            </thead>
            <tbody id="cuerpo_solicitud">
            </tbody>
          </table>

          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <strong>Contenerización</strong>
              <hr style="border: 0; height: 12px; box-shadow: inset 0 12px 12px -12px #33B5E5;margin-top:2px">
            </div>
            <table class="table table-condensed table-hover table-bordered table-striped">
              <thead>
                <tr>
                  <th>Tipo contenedor</th>
                  <th>Núm. contenedor</th>
                  <th>Fecha vencimiento</th>
                  <th>Mun devolución</th>
                  <th>Dirección devolución</th>
                  <th>Fecha comodato</th>
                </tr>
              </thead>
              <tbody id=" cuerpo_contenerizacion">
              </tbody>
            </table>
          </div>

          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <strong>Remitentes y Destinatarios</strong>
              <hr style="border: 0; height: 12px; box-shadow: inset 0 12px 12px -12px #33B5E5;margin-top:2px">
            </div>
            <table class="table table-condensed table-hover table-bordered table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Tipo</th>
                  <th>Municipio</th>
                  <th>Dirección</th>
                  <th>Observación</th>
                  <th>Fecha R/E</th>
                  <th>Hora R/E</th>
                  <th>Relación</th>
                </tr>
              </thead>
              <tbody id="cuerpo_punto_recoleccion">
              </tbody>
            </table>
            <hr>
            <table class="table table-condensed table-hover table-bordered table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Tipo</th>
                  <th>Municipio</th>
                  <th>Dirección</th>
                  <th>Observación</th>
                  <th>Fecha R/E</th>
                  <th>Hora R/E</th>
                  <th>Relación</th>
                </tr>
              </thead>
              <tbody id="cuerpo_punto_destino">
              </tbody>
            </table>
          </div>
        </div>
        <div class="row"></div>
      </div>
      <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
      </div>
    </div>
  </div>
</div> -->

<!-- SOLICITUD DE SERVICIO -->
<!-- <div id="consulta_solicitud" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary" style="overflow-y:scroll;">
  <div class="modal-dialog custom-width">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:center;height: 50px;padding: 19px;">
        <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close" style="color:#fff;"></span></button>
        <h4 class="modal-title" id="editar_title"> Solicitud Servicio
        </h4>
      </div>
      <div class="modal-body">
        <div id="msg_servicio"></div>
        <div id="content">

          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <span><strong>Solicitud servicio</strong></span>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div id="consultass_general"></div>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div id="contener_remitente"></div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" data-dismiss="modal" class="btn btn-default md-close">Cerrar</button>
        </div>
      </div>
    </div>
  </div>
</div> -->

<!-- <script type="text/javascript">
  $(document).on('click', '#btn_soli', function() {
    $('#solicitudservicio').modal('show');
  });
  $(document).on('click', '#cancel', function() {
    $('#solicitudservicio').modal('hide');
  });
  $(document).on('click', '#btn_soli2', function() {
    $('#solicitudservicionew').modal('show');
  });
  $(document).on('click', '#cancel2', function() {
    $('#solicitudservicionew').modal('hide');
  });
  $(document).on('click', '#btn_cerrar', function() {
    $('#crea_vehiculopreestudio').modal('hide');
    location.reload();
  });
</script> -->

<!-- Modal para mostrar si el documento que esta colocando no es un recurso nuevo en la plataforma -->
<!-- <div class="modal fade" id="mod-warning" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="text-center">
          <div class="text-warning"><span class="modal-main-icon mdi mdi-alert-triangle"></span></div>
          <h3 id="mensaje_notificacion">Warning!</h3>
          <p id="texto_notificacion">Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br>Fusce ultrices euismod lobortis.</p>
          <div class="mt-8">
            <button class="btn btn-space btn-danger btn-xs" type="button" id="btn_cerrar_notificaciones">Cerrar</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> -->

<!-- <div id="crea_vehiculopreestudio" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary" style="overflow-y: scroll;">
  <div class=".modal-dialog-modal-lg.modal-dialog ">
    <div class="modal-content ">
      <div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:left;height: 50px;padding: 19px;">
        <button type="button" id="btn_cerrar" data-dismiss="modal" aria-hidden="true" class="close md-close" style="color: #fff;"><span class="mdi mdi-close"></span></button>
        <h4 class="modal-title">
          <span class="mdi mdi-car"></span> <b>Consultar vehículo</b>
        </h4>
      </div>
      <div class="modal-body" style="padding: 1px 1px 1px;">
        <div id="nexos_messages_popup"></div>
        <h4 id="nexos_messages_b1"></h4>
        <h4 id="nexos_messages_b2"></h4>
        <div id="historicos"></div>
        <div id="mensaje_itr"></div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row">
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <label>N° solicitud</label>
                <input type="text" id="servicio_base" class="form-control input-sm text-center" readonly="readonly">
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <label class="text-center">Tipo servicio</label>
                <input type="text" id="tipo_base" class="form-control input-sm text-center" readonly="readonly">
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <label>Placa</label>
                <input type="text" id="placa" class="form-control input-sm text-center">
                <input type="hidden" id="proceso_itr" class="form-control input-sm text-center">
              </div>

              <div class="col-xs-3 col-md-3 col-sm-3 col-lg-3">
                <br><button class="btn btn-primary btn-lg" onclick="ValidacionReglaNegocio();" style="width: 100%;margin-top: 7px;"><span class="mdi mdi-search"></span> Buscar</button>
              </div>
              <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <input type="hidden" id="origen_base" class="form-control input-sm" readonly="readonly" name="origen_de_base">
              </div>
              <div class="col-xs-12 col-md-3 col-sm-3 col-lg-3">
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div id="historico"></div>
            <div id="historico_vencido"></div>
          </div>
        </div>

        <div class="row" id="controles_tipo"><br>
          <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12  thv" style="display:none;">

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
              <input type="hidden" id="estado_vehiculo">
              <label><b>Tipo de operación:</b>&nbsp;<span style="color:red;"><i>(*)</i></span></label>
            </div>

            <div id="divnuevo" class="col-xs-3 col-sm-3 col-md-3 col-lg-3" style="display:none;">
              <input type="radio" id="nuevo" class="tipo_hoja" name="gender" value="1" style="width: 20px; height: 20px;">
              <label for="nuevo" id="nuevo2">Nuevo</label>&nbsp;&nbsp;
            </div>
            <div id="divhabil" class="col-xs-3 col-sm-3 col-md-3 col-lg-3" style="display:none;">
              <input type="radio" id="habil" class="tipo_hoja" name="gender" value="2" style="width: 20px; height: 20px;">
              <label for="habil" id="habil2">Habilitar</label>&nbsp;&nbsp;
            </div>
            <div id="divactualiza" class="col-xs-3 col-sm-3 col-md-3 col-lg-3" style="display:none;">
              <input type="radio" id="update" class="tipo_hoja" name="gender" value="3" style="width: 20px; height: 20px;">
              <label for="update" id="update2">Actualizar</label>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
          <input type="hidden" id="tiporadio" class="form-control input-sm">
        </div>
        <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
          <label>Último estado (prefiltro):</label>
          <input type="text" id="estado_prefiltron" class="form-control text-danger input-sm" disabled="disabled" style="border:0px; background-color:white; font-weight:700; text-align:left;  ">
          <input type="hidden" id="solianterior" class="form-control input-sm">
        </div>

        <div class="col-xs-6 col-sm-12 col-md-12 col-lg-12" id="mensaje_vehiculo_bloquear"></div>
        <div class="col-xs-6 col-sm-12 col-md-12 col-lg-12" id="mensaje_inciado"></div>
        <div class="row" style="padding-right:1px; padding-left:1px; padding-bottom:1px;  padding-top:1px;" id="diveditardatos">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"></div>
        </div>
        <div class="row" style="padding-right:1px; padding-left:1px; padding-bottom:1px;  padding-top:1px;" id="divdatos">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div id="accordion1" class="panel-group accordion">
              <div class="panel panel-default hello" id="datos_proveedores" style="display:none;">
                <div class="panel-heading">
                  <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#collapseitr" class="collapsed"><i class="icon mdi mdi-chevron-down"></i>Datos ITR</a></h4>
                </div>
                <div id="collapseitr" class="panel-collapse collapse">
                  <div class="panel-body" style="padding: 1px 1px 1px;">
                    <div class="datos_proveedores">
                      <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
                        <tbody>
                          <tr>
                            <td class="celda_titulo2 text-center" style="margin:25px;">
                              <b>Datos del Vehículo</b>
                            </td>
                          </tr>
                          <tr>
                          </tr>
                        </tbody>
                      </table>
                      <table cellpadding="0" cellspacing="0" width="100%" id="tbl_datos_prefiltro">
                        <tbody>
                          <tr class="text-center active">
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Nombre Propietario</th>
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Documento</th>
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Celular</th>
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Acción</th>
                          </tr>
                          <tr>
                            <td id="vpropi" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                            <td id="vpdocumento" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                            <td id="cpropi" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                            <td id="accion_propietario" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                          </tr>
                          <tr>
                          </tr>
                          <tr class="text-center active">
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Nombre Poseedor</th>
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Documento</th>
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Celular</th>
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Acción</th>
                          </tr>
                          <tr>
                            <td id="vtene" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                            <td id="vtdocumento" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                            <td id="ctene" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                            <td id="accion_poseedor" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                          </tr>
                          <tr>
                          </tr>
                          <tr class="text-center active">
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Nombre Conductor</th>
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Documento</th>
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Celular</th>
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Acción</th>
                          </tr>
                          <tr>
                            <td id="vcondu" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                            <td id="vcdocumento" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                            <td id="ccondu" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                            <td id="accion_conductor" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                          </tr>
                          <tr>
                          </tr>
                          <tr class="text-center active">
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Nombre Propietario Trailer</th>
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Documento Propietarioi Trailer</th>
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Celular</th>
                            <th style="color: #332D2D;background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Acción</th>
                          </tr>
                          <tr>
                            <td id="ptcondu" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                            <td id="ptcdocumento" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                            <td id="cpropt" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"> </td>
                            <td id="accion_propietario_trailer" class="text-left" style="border: 1px solid rgb(221, 221, 221); padding: 1px; width: auto; white-space: nowrap; background-color: rgb(255, 255, 255);"></td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
              <div class="panel panel-default hello" id="hvpreestudio" style="display:none;">
                <div class="panel-heading">
                  <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#collapseThree" class="collapsed"><i class="icon mdi mdi-chevron-down"></i>Datos del vehículo</a></h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse">
                  <div class="panel-body">
                    <div class="sms"></div>
                    <div class="col-xs-12 col-md-6 col-sm-6 col-lg-6">
                      <label>Placa Vehiculo&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="placag" class="form-control input-xs" disabled="disabled">
                    </div>
                    <div class="col-xs-12 col-md-6 col-sm-6 col-lg-6">
                      <label>Web Sátelital&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="web" name="web" class="form-control input-xs">
                    </div>
                    <div class="col-xs-12 col-md-6 col-sm-6 col-lg-6">
                      <label>Usuario&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="user_satelite" name="user_satelite" class="form-control input-xs">
                    </div>
                    <div class="col-xs-12 col-md-6 col-sm-6 col-lg-6">
                      <label>Clave&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="clave" name="clave" class="form-control input-xs">
                    </div>
                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                      <label>Documento Propietario&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="number" id="docupro" name="docupro" class="form-control input-xs">
                    </div>
                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                      <label>Nombre Propietario&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="nompro" name="nompro" class="form-control input-xs">
                    </div>
                    <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
                      <div id="mensaje_propietario_existe"></div>
                    </div>
                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                      <label>Documento Poseedor&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="number" id="docutene" name="docutene" class="form-control input-xs">
                    </div>
                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                      <label>Nombre Poseedor&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="nomtene" name="nomtene" class="form-control input-xs">
                    </div>
                    <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
                      <div id="mensaje_poseedor_existe"></div>
                    </div>
                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                      <label>Documento Conductor&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="number" id="docucondu" name="docucondu" class="form-control input-xs" onChange="javascript:referencias_prefiltro();">
                    </div>
                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                      <label>Nombre Conductor&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" id="nomcondu" name="nomcondu" class="form-control input-xs">
                    </div>
                    <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
                      <div id="mensaje_conductor_existe"></div>
                    </div>
                    <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
                      <div class="border border-1">
                        <h5 style="font-weight: bold;">Datos Trailer&nbsp;&nbsp;&nbsp;&nbsp; <input type="checkbox" id="propietario_obligatorio" style="transform: scale(1.5);"></h5>
                      </div>
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-4 col-lg-4">
                      <label id="etiqueta_placa_trailer">Placa Trailer </label>
                      <input type="text" id="placat" name="placat" disabled class="form-control input-xs">
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-4 col-lg-4">
                      <label id="etiqueta_documento_trailer">Documento Propietario Trailer</label>
                      <input type="number" id="docproptrailer" name="docproptrailer" class="form-control input-xs" disabled>
                    </div>
                    <div class="col-xs-12 col-md-4 col-sm-4 col-lg-4">
                      <label id="estiqueta_propietario_trailer">Nombre Propietario Trailer</label>
                      <input type="text" id="nomproptrailer" name="nomproptrailer" class="form-control input-xs" disabled>
                    </div>
                    <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
                      <div id="mensaje_trailer_existe"></div>
                      <div id="mensaje_trailer_obligatorio" style="margin-top: 5px;"></div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                      <input type="hidden" id="cab" value="1">
                    </div>
                  </div>
                </div>
              </div>

              <div class="panel panel-default" id="panel_referenciaNEW" style="display:none;">
                <div class="panel-heading">
                  <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#collapsereferencianew" class="collapsed"><i class="icon mdi mdi-chevron-down"></i>Referencias laborales</a></h4>
                </div>
                <div id="collapsereferencianew" class="panel-collapse collapse">
                  <div class="panel-body">
                    <div class="col-xs-6 col-sm-2 col-md-2 col-lg-2" style="margin-top:10px; text-align:center; ">
                      <button class=" form-control btn btn-info mdi mdi-plus input-xs text-center" data-toggle="tooltip" data-placement="top" title="Agregar fila" id="agregar_fila">
                      </button>
                    </div>
                    <hr />
                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                      <h3>
                        <p class="text-center text-info">Referencias laborales</p>
                      </h3><br>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                      <table class="table table-info" id="table_mercancia">
                        <thead style="border-color:blue;">
                        </thead>
                        <tbody>

                        </tbody>
                      </table>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                      <input type="hidden" id="ref" value="2">
                    </div>
                  </div>
                </div>
              </div>

              <div class="panel panel-default" id="panel_referenciahv" style="display:none;">
                <div class="panel-heading">
                  <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#collapsereferencia" class="collapsed"><i class="icon mdi mdi-chevron-down"></i>Referencias Empresariales</a></h4>
                </div>
                <div id="collapsereferencia" class="panel-collapse collapse">
                  <div class="panel-body">
                    <input type="hidden" id="idconductor">
                    <div class="row">
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <span class="badge badge-pill badge-primary">1</span>
                      </div>

                      <div class="col-xs-12 col-sm-12 col-md-12  REmpresarial8">
                        <label>Empresa 1:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <input type="text" class="form-control input-sm" id="referencias_empresariales1" onblur="mayuscula(this);">
                        <label id="error_referencia_empresarial2"></label>
                      </div>

                      <div class="col-xs-6 col-sm-6 col-md-6">
                        <label>Fecha Ingreso:</label>
                        <input type="date" id="fingreso1" class="form-control input-sm">
                      </div>

                      <div class="form-group col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <label>Fecha Retiro:</label>
                        <input type="date" id="fretiro1" class="form-control input-sm">
                      </div>

                      <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label>Persona Contacto:</label>
                        <input type="text" id="contacto_ref1" placeholder="Nombre Contacto" class="form-control input-sm" onblur="mayuscula(this);">
                        <label id="error_contacto"></label>
                      </div>

                      <div class="form-group col-xs-12 col-sm-4 col-md-4 col-lg-4">
                        <label>Celular Empresa:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <input type="int" id="celular_ref1" placeholder="Celular Empresa" maxlength="10" class="form-control input-sm">
                        <label id="error_celularref1"></label>
                      </div>

                      <div class="form-group col-xs-12 col-sm-4 col-md-4  col-lg-4">
                        <label>Cargo:</label>
                        <input type="text" id="cargo_ref1" placeholder="Cargo" class="form-control input-sm" onblur="mayuscula(this);">
                        <label id="error_cargo"></label>
                      </div>
                      <div class="form-group col-xs-12 col-sm-4 col-md-4  col-lg-4">
                        <label>Antiguedad</label>
                        <input type="number" id="anti_ref1" min="0" placeholder="Antiguedad1" class="form-control input-sm">
                      </div>
                      <input type="hidden" id="idrl1">
                    </div>
                    <div class="row">
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <span class="badge badge-pill badge-primary">2</span>
                      </div>

                      <div class="col-xs-12 col-sm-12 col-md-12  REmpresarial8">
                        <label>Empresa 2:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <input type="text" class="form-control input-sm" id="referencias_empresariales2" onblur="mayuscula(this);">
                        <label id="error_referencia_empresarial2"></label>
                      </div>

                      <div class="col-xs-6 col-sm-6 col-md-6">
                        <label>Fecha Ingreso:</label>
                        <input type="date" id="fingreso2" class="form-control input-sm">
                      </div>

                      <div class="form-group col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <label>Fecha Retiro:</label>
                        <input type="date" id="fretiro2" class="form-control input-sm">
                      </div>

                      <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label>Persona Contacto:</label>
                        <input type="text" id="contacto_ref2" placeholder="Nombre Contacto" class="form-control input-sm" onblur="mayuscula(this);">
                        <label id="error_contacto"></label>
                      </div>

                      <div class="form-group col-xs-12 col-sm-4 col-md-4 col-lg-4">
                        <label>Celular Empresa:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <input type="int" id="celular_ref2" placeholder="Celular Empresa" maxlength="10" class="form-control input-sm">
                        <label id="error_celularref1"></label>
                      </div>

                      <div class="form-group col-xs-12 col-sm-4 col-md-4  col-lg-4">
                        <label>Cargo:</label>
                        <input type="text" id="cargo_ref2" placeholder="Cargo" class="form-control input-sm" onblur="mayuscula(this);">
                        <label id="error_cargo"></label>
                      </div>
                      <div class="form-group col-xs-12 col-sm-4 col-md-4  col-lg-4">
                        <label>Antiguedad</label>
                        <input type="number" id="anti_ref2" min="0" placeholder="Antiguedad2" class="form-control input-sm">
                      </div>
                      <input type="hidden" id="idrl2">
                    </div>
                    <div class="row">
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <span class="badge badge-pill badge-primary">3</span>
                      </div>

                      <div class="col-xs-12 col-sm-12 col-md-12  REmpresarial8">
                        <label>Empresa 3:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <input type="text" class="form-control input-sm" id="referencias_empresariales3" onblur="mayuscula(this);">
                        <label id="error_referencia_empresarial2"></label>
                      </div>

                      <div class="col-xs-6 col-sm-6 col-md-6">
                        <label>Fecha Ingreso:</label>
                        <input type="date" id="fingreso3" class="form-control input-sm">
                      </div>

                      <div class="form-group col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <label>Fecha Retiro:</label>
                        <input type="date" id="fretiro3" class="form-control input-sm">
                      </div>

                      <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label>Persona Contacto:</label>
                        <input type="text" id="contacto_ref3" placeholder="Nombre Contacto" class="form-control input-sm" onblur="mayuscula(this);">
                        <label id="error_contacto"></label>
                      </div>

                      <div class="form-group col-xs-12 col-sm-4 col-md-4 col-lg-4">
                        <label>Celular Empresa:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <input type="int" id="celular_ref3" placeholder="Celular Empresa" maxlength="10" class="form-control input-sm">
                        <label id="error_celularref1"></label>
                      </div>

                      <div class="form-group col-xs-12 col-sm-4 col-md-4  col-lg-4">
                        <label>Cargo:</label>
                        <input type="text" id="cargo_ref3" placeholder="Cargo" class="form-control input-sm" onblur="mayuscula(this);">
                        <label id="error_cargo"></label>
                      </div>
                      <div class="form-group col-xs-12 col-sm-4 col-md-4  col-lg-4">
                        <label>Antiguedad</label>
                        <input type="number" id="anti_ref3" min="0" placeholder="Antiguedad3" class="form-control input-sm">
                      </div>
                      <input type="hidden" id="idrl3">
                    </div>
                  </div>
                </div>
              </div>

              <div class="panel panel-default" id="panel_refepersonal" style="display:none;">
                <div class="panel-heading">
                  <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#collapsepersonal" class="collapsed"><i class="icon mdi mdi-chevron-down"></i>Persona Contacto y Referencia</a></h4>
                </div>
                <div id="collapsepersonal" class="panel-collapse collapse">
                  <div class="panel-body">
                    <div class="row">
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label><strong>Contacto en caso de emergencia</strong></label>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <span class="badge badge-pill badge-primary">1</span>
                      </div>
                      <div class="col-xs-12 col-sm-6 col-md-6 REmpresarial2">
                        <label>Nombre Persona 1:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <input class="form-control input-sm" id="referencias_personales1" onblur="mayuscula(this);">
                        <label id="error_referencias_personales"></label>
                      </div>
                      <div class="col-xs-12 col-sm-6 col-md-3 FPersonal1">
                        <label>Fecha 1:</label>
                        <input type="date" id="fecha_personal1" class="form-control input-sm">
                      </div>
                      <div class="col-xs-12 col-sm-6 col-md-3 REmpresarial2">
                        <label>Parentezco:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <select class="form-control input-sm" id="parenp1">
                          <option value="" readonly="readonly">Seleccione una opción</option>
                          <option value="1">Amigo/a</option>
                          <option value="2">Hermano/a</option>
                          <option value="3">Padre</option>
                          <option value="4">Madre</option>
                          <option value="5">Tio/a</option>
                          <option value="6">Sobrino/a</option>
                          <option value="7">Hijo/a</option>
                          <option value="8">Espaso/a</option>
                        </select>
                        <label id="error_referencias_personales"></label>
                      </div>
                      <div class="col-xs-12 col-sm-6 col-md-6 REmpresarial2">
                        <label>Teléfono:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <input type="number" id="telefonop1" min="0" class="form-control input-sm" maxlength="10">
                        <label id="error_referencias_personales"></label>
                      </div>
                      <div class="col-xs-12 col-sm-3 col-md-3 REmpresarial2">
                        <input type="hidden" id="idrper1">
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label><strong>Referencia personal</strong></label>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <span class="badge badge-pill badge-primary">2</span>
                      </div>
                      <div class="col-xs-12 col-sm-6 col-md-6 RPersonal2">
                        <label>Nombre Persona 2:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <input type="text" class="form-control input-sm" id="referencias_personales2" onblur="mayuscula(this);">
                        <label id="error_referencias_personales"></label>
                      </div>
                      <div class="col-xs-12 col-sm-6 col-md-3 FRpersonal2">
                        <label>Fecha Personal 2:</label>
                        <input type="date" id="fecha_personal2" class="form-control input-sm" value="">
                      </div>
                      <div class="col-xs-12 col-sm-6 col-md-3 REmpresarial2">
                        <label>Parentezco:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <select class="form-control input-sm" id="parenp2">
                          <option value="" readonly="readonly">Seleccione una opción</option>
                          <option value="1">Amigo/a</option>
                          <option value="2">Hermano/a</option>
                          <option value="3">Padre</option>
                          <option value="4">Madre</option>
                          <option value="5">Tio/a</option>
                          <option value="6">Sobrino/a</option>
                          <option value="7">Hijo/a</option>
                          <option value="8">Espaso/a</option>
                        </select>
                        <label id="error_referencias_personales"></label>
                      </div>
                      <div class="col-xs-12 col-sm-6 col-md-6 REmpresarial2">
                        <label>Teléfono:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <input type="number" id="telefonop2" min="0" class="form-control input-sm" maxlength="10">
                        <label id="error_referencias_personales"></label>
                      </div>
                      <div class="col-xs-12 col-sm-3 col-md-3 REmpresarial2">
                        <input type="hidden" id="idrper2">
                      </div>
                    </div>

                  </div>
                </div>
              </div>
              <div class="panel panel-default" id="panel_solicitudes" style="display:none;">
                <div class="panel-heading">
                  <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#collapseFour" class="collapsed"><i class="icon mdi mdi-chevron-down"></i> Datos de la solicitud</a></h4>
                </div>
                <div id="collapseFour" class="panel-collapse collapse">
                  <div class="panel-body">

                    <div id="solicitudservicio" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary" style="overflow-y:auto;">
                      <div class=".modal-dialog-modal-lg.modal-dialog ">
                        <div class="modal-content ">
                          <div class="modal-header">
                            <button type="button" id="cancel" class="close md-close"><span class="mdi mdi-close"></span></button>
                            <h3 class="modal-title">
                              <label style="font-weight:900; margin-top:20px;">
                                Solicitudes de servicio
                              </label>
                            </h3>
                          </div>
                          <div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
                            <div id="nexos_messages_popup"></div>
                            <div class="row">
                              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <label>Listas seleccionadas</label>
                                <ul id="listamodal"></ul>
                              </div>
                              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                                <?php echo $table_solicitud; ?>

                              </div>
                            </div>
                          </div>
                          <div class="modal-footer">
                            <button type="button" id="cancel" class="btn btn-default md-close">Cancelar</button>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                        <label style="font-weight:600; margin-top:20px;"> Solicitudes de servicio:
                        </label>&nbsp;&nbsp;
                        <button type="button" id="btn_soli" data-toggle="modal" class="btn btn-primary icon mdi mdi-shopping-cart">
                        </button>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <label style="font-weight:800; margin-top:20px;">Solicitudes de servicio seleccionadas</label>
                        <input type="hidden" id="maxservi" value="1">
                      </div>

                      <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <input type="hidden" value="3" id="soli_total">
                      </div>
                      <style type="text/css">
                        .seleccionada {
                          background-color: #0585C0;
                          color: white;
                        }
                      </style>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <table class="table table-bordered">
                          <thead>
                            <th>#</th>
                            <th>Servicio</th>
                            <th>cotización-Item-Mercancía</th>
                            <th>Cliente</th>
                            <th>Flete cot.</th>
                            <th style="display:none">Peso bruto(Tn)</th>
                            <th>Tarifa cot.</th>
                            <th>Acción</th>
                          </thead>
                          <tbody id="cuerpo_lista2">
                          </tbody>
                        </table>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <table class="table table-bordered">
                          <thead>
                            <th>Suma de Flete por solicitudes</th>
                            <th style="display:none;">Total peso Bruto(Tn)</th>
                          </thead>
                          <tbody id="totalizar"></tbody>
                        </table>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <table class="table table-bordered">
                          <thead>
                            <th>N° - Remitente</th>
                            <th>Fecha</th>
                            <th>Peso(Kg)</th>
                            <th>Punto de cargue</th>
                          </thead>
                          <tbody id="cuerpo_fechas">
                          </tbody>
                        </table>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <label>Total sumatoria Peso(Kg)</label>
                        <input type="text" id="total_pesos" class="form-control input-sm" readonly="readonly">
                      </div>
                      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <label>Capacidad carga vehículo(Kg)&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                        <input type="text" id="capa_carga_vh" class="form-control input-sm">
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label style="font-weight:800; margin-top:20px;">Solicitud de Preestudio</label>
                      </div>
                      <div class="col-xs-4 col-md-4 col-sm-4 col-lg-4">
                        <label>Fecha</label>
                        <input type="text" id="fpree" value="<?php echo date('Y-m-d'); ?>" class="form-control input-sm" readonly="readonly">
                      </div>
                      <div class="col-xs-4 col-md-4 col-sm-4 col-lg-4">
                        <label>Hora</label>
                        <input type="text" id="hpree" value="<?php echo date('H:i:s'); ?>" class="form-control input-sm" readonly="readonly">
                      </div>
                      <div class="col-xs-4 col-md-4 col-sm-4 col-lg-4">
                        <label>Usuario</label>
                        <input type="text" id="userpree" class="form-control input-sm" value="<?php echo $ssn_nombre; ?>" readonly="readonly">
                      </div>
                      <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
                        <label>Observaciones</label>
                        <textarea id="obserpree" class="form-control input-sm"></textarea>
                      </div>
                      <input type="hidden" id="id_consolidacion" class="form-control input-sm" readonly="readonly">
                    </div>
                  </div>
                </div>
              </div>
              <div class="panel panel-default" id="panel_seguridad" style="display:none;">
                <div class="panel-heading">
                  <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#collapse_update" class="collapsed"><i class="icon mdi mdi-chevron-down"></i>Actualiza Seguridad (hojas de vida)</a>
                  </h4>
                </div>
                <div id="collapse_update" class="panel-collapse collapse">
                  <div class="panel-body">
                    <div id="msg_alerta"></div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                      <hr />
                    </div>
                    <div class="row">
                      <div class="col-md-12 col-lg-12">
                        <div class="panel panel-border-color">
                          <div class="panel-body">

                            <div class="row">
                              <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                                <h4>Recursos actuales</h4>
                              </div>
                              <div class="col-sm-6 col-md-6 col-lg-6"></div>
                              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3"><label>Vehículo</label></div>
                                <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9"><input type="text" class="form-control input-xs" id="veh_vehiculo" readonly="readonly"></div>
                              </div>
                              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3"><label>Conductor</label></div>
                                <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9"><input type="text" class="form-control input-xs" id="veh_conduc" readonly="readonly"></div>
                              </div>
                              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3"><label>Propietario</label></div>
                                <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9"><input type="text" class="form-control input-xs" id="veh_propiet" readonly="readonly"></div>
                              </div>
                              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3"><label>Poseedor</label></div>
                                <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9"><input type="text" class="form-control input-xs" id="veh_poseed" readonly="readonly"></div>
                              </div>
                            </div>
                            <br>
                            <div class="row text-center">
                              <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                <label> <input type="checkbox" id="cbox1" class="recursos_checbox" value="nuevo_recurso" style="transform: scale(1.3);margin-right: 10px;"> Nuevo recurso </label>
                              </div>
                              <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                <label> <input type="checkbox" id="cbox2" class="recursos_checbox" value="datos_dinamicos" style="transform: scale(1.3);margin-right: 10px;"> Datos dinámicos</label>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div> <br>
                    <div class="row panel_tabs_recursos">
                      <div class="col-sm-12 col-md-12 col-lg-12">
                        <div class="panel panel-default">
                          <div class="tab-container">
                            <ul class="nav nav-tabs nav-tabs-warning">
                              <li class="active re_inexis"><a href="#home2" data-toggle="tab" style="display: none;" id="creacion_nuevo_recuro">Creación de recursos nuevos
                                </a>
                              </li>
                              <li class="re_dinamic"><a href="#profile2" data-toggle="tab" style="display: none;" id="datos_dinamicos">Datos dinámicos</a>
                              </li>
                            </ul>
                            <div class="tab-content">
                              <div id="home2" class="tab-pane active cont  re_inexis">
                                <div class="panel panel-border-color panel-border-color-dark" id="inexistente_actividades">
                                  <div class="panel-body text-center" style="padding: 1px 1px 1p;">
                                    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                      <label><input type="checkbox" id="cbpre1" class="chebox_recurso" value="Propietario"> Propietario</label>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                      <label><input type="checkbox" id="cbpre2" class="chebox_recurso" value="Poseedor"> Poseedor</label>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                      <label><input type="checkbox" id="cbpre3" class="chebox_recurso" value="Conductor"> Conductor</label>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                      <label><input type="checkbox" id="cbpre4" class="chebox_recurso" value="Trailer"> Tráiler</label>
                                    </div>
                                  </div>
                                </div>

                                <div class="panel panel-border-color panel-border-color-dark" id="inexistente_propietario">
                                  <div class="panel-body">
                                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                      <label>Número Documento</label>
                                      <input type="number" class="form-control input-xs" id="number_propietario">
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                      <label>Nombre completo propietario</label>
                                      <input type="text" class="form-control input-xs nombre_i" id="name_propietario">
                                    </div>
                                  </div>
                                </div>

                                <div class="panel panel-border-color panel-border-color-dark" id="inexistente_poseedor">
                                  <div class="panel-body">
                                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                      <label>Número Documento</label>
                                      <input type="number" class="form-control input-xs" id="number_poseedor">
                                    </div>
                                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                      <label>Nombre completo poseedor</label>
                                      <input type="text" class="form-control input-xs nombrei" id="name_poseedor">
                                    </div>
                                  </div>
                                </div>

                                <div class="panel panel-border-color panel-border-color-dark" id="inexistente_conductor">
                                  <div class="panel-body">
                                    <div class="row">
                                      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                        <label>Número Documento</label>
                                        <input type="number" class="form-control input-xs" id="number_conductor">
                                      </div>
                                      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                        <label>Nombre completo conductor</label>
                                        <input type="text" class="form-control input-xs nombre_i" id="name_conductor">
                                      </div>
                                    </div><br>
                                    <div class="row">

                                      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4" style="border-right:1px solid gray">
                                        <span>Nombre Empresa</span>
                                        <input type="text" class="form-control input-xs" id="referencias_empresariales1pre" onblur="mayuscula(this);">
                                        <span>Persona Contacto</span>
                                        <input type="text" id="contacto_ref1pre" placeholder="Nombre Contacto" class="form-control input-xs" onblur="mayuscula(this);">
                                        <span>Celular Empresa</span>
                                        <input type="number" id="celular_ref1pre" placeholder="Celular Empresa" maxlength="10" class="form-control input-xs">
                                        <span>Cargo</span>
                                        <input type="text" id="cargo_ref1pre" placeholder="Cargo" class="form-control input-sm" onblur="mayuscula(this);">
                                        <span>Fecha ingreso 1</span>
                                        <input type="date" id="fingresoa1pre" class="form-control input-xs">
                                        <span>Fecha ingreso 2</span>
                                        <input type="date" id="fretiroa3pre" class="form-control input-xs">
                                        <span>Antiguedad</span>
                                        <input type="number" id="anti_ref1pre" min="0" class="form-control input-xs">
                                      </div>

                                      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4" style="border-right:1px solid gray">
                                        <span>Nombre Empresa</span>
                                        <input type="text" class="form-control input-xs" id="referencias_empresariales2pre" onblur="mayuscula(this);">
                                        <span>Persona Contacto</span>
                                        <input type="text" id="contacto_ref2pre" placeholder="Nombre Contacto" class="form-control input-xs" onblur="mayuscula(this);">
                                        <span>Celular Empresa</span>
                                        <input type="number" id="celular_ref2pre" placeholder="Celular Empresa" maxlength="10" class="form-control input-xs">
                                        <span>Cargo</span>
                                        <input type="text" id="cargo_ref2pre" placeholder="Cargo" class="form-control input-xs" onblur="mayuscula(this);">
                                        <span>Fecha ingreso 1</span>
                                        <input type="date" id="fingresob1pre" class="form-control input-xs">
                                        <span>Fecha ingreso 2</span>
                                        <input type="date" id="fretirob3pre" class="form-control input-xs">
                                        <span>Antiguedad</span>
                                        <input type="number" id="anti_ref2pre" min="0" class="form-control input-xs">
                                      </div>

                                      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                                        <span>Nombre Empresa</span>
                                        <input type="text" class="form-control input-xs" id="referencias_empresariales3pre" onblur="mayuscula(this);">
                                        <span>Persona Contacto</span>
                                        <input type="text" id="contacto_ref3pre" placeholder="Nombre Contacto" class="form-control input-xs" onblur="mayuscula(this);">
                                        <span>Celular Empresa</span>
                                        <input type="number" id="celular_ref3pre" placeholder="Celular Empresa" maxlength="10" class="form-control input-xs">
                                        <span>Cargo</span>
                                        <input type="text" id="cargo_ref3pre" placeholder="Cargo" class="form-control input-xs" onblur="mayuscula(this);">
                                        <span>Fecha ingreso 1</span>
                                        <input type="date" id="fingresoc1pre" class="form-control input-xs">
                                        <span>Fecha ingreso 2</span>
                                        <input type="date" id="fretiroc3pre" class="form-control input-xs">
                                        <span>Antiguedad</span>
                                        <input type="number" id="anti_ref3pre" min="0" class="form-control input-xs">
                                      </div>
                                    </div>
                                  </div>
                                </div>

                                <div class="panel panel-border-color panel-border-color-dark" id="inexistente_vehiculo">
                                  <div class="panel-body">
                                    <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3">
                                      <label>Placa vehículo</label>
                                      <input type="text" class="form-control input-xs" id="placa_vehiculosat">
                                    </div>
                                    <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3">
                                      <label>URL satélital</label>
                                      <input type="text" class="form-control input-xs" id="url_sat">
                                    </div>
                                    <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3">
                                      <label>Usuario satélital</label>
                                      <input type="text" class="form-control input-xs" id="user_sat">
                                    </div>
                                    <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3">
                                      <label>Clave satélital</label>
                                      <input type="text" class="form-control input-xs" id="pass_sat">
                                    </div>
                                  </div>
                                </div>

                                <div class="panel panel-border-color panel-border-color-dark" id="inexistente_trailer">
                                  <div class="panel-body">
                                    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                                      <label>Placa tráiler</label>
                                      <input type="text" class="form-control input-xs" id="placa_trailerpre">
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                                      <label>Número documento propietario tráiler</label>
                                      <input type="text" class="form-control input-xs" id="propidocu_trailer">
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                                      <label>Nombre propietario tráiler</label>
                                      <input type="text" class="form-control input-xs" id="propi_trailer">
                                    </div>
                                  </div>
                                </div>

                              </div>
                              <div id="profile2" class="tab-pane cont  re_dinamic">

                                <div class="row">
                                  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                                    <h4>Tipo hoja de vida</h4>
                                  </div>
                                  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                    <select id="thv" class="form-control input-sm text-center">
                                      <option value="">Seleccione</option>
                                      <option value="propietario">Propietario</option>
                                      <option value="conductor">Conductor</option>
                                      <option value="tenedor">Tenedor</option>
                                      <option value="vehiculo">Vehículo</option>
                                      <option value="trailer">Trailer</option>
                                    </select>
                                  </div>
                                </div>

                                <div class="row uno">
                                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <input type="text" id="label" class="form-control input-xs" readonly="" style="font-size:12pt; text-align:center;">
                                  </div>
                                  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4" id="elbtn">
                                    <label>Campo actualizar: </label>
                                    <input type='text' class='form-control input-xs' id='dato'>
                                  </div>
                                  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4" id="elbtn">
                                    <label>Información actualizar: </label>
                                    <input type='text' class='form-control input-xs' id='detalle'>
                                  </div>
                                  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id="elbtn">
                                    <br><button id="agregue_tb" class="btn btn-success btn-sm  mdi mdi-plus text-center"></button>
                                  </div>
                                </div><br>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div><br>
                    <div class="row panel_total_recursos">
                      <div class="col-sm-12 col-md-12 col-lg-12">
                        <div class="panel panel-default">
                          <table class="table table-striped table-hover table-condensed table-bordered">
                            <thead style="background-color:#332D2D;color:#fff;text-align:center;">
                              <tr>
                                <th>Código</th>
                                <th>Tipo HV</th>
                                <th>Dato actualizar</th>
                                <th>Detalle</th>
                                <th>Archivo</th>
                                <th>X</th>
                              </tr>
                            </thead>
                            <tbody id="cuerpo_actu">
                            <tbody>
                          </table>
                          <input type="hidden" id="valortb" readonly="readonly">
                        </div>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
              <div class="panel panel-default" id="panel_papeles_actualiza" style="display:none;">
                <div class="panel-heading">
                  <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#doc_update" class="collapsed"><i class="icon mdi mdi-chevron-down"></i>Documentos Para Actualizar</a></h4>
                </div>
                <div id="doc_update" class="panel-collapse collapse">
                  <div class="panel-body">
                  </div>
                </div>
              </div>
              <div class="panel panel-default" id="panel_papeles_habilitar" style="display:none;">
                <div class="panel-heading">
                  <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#doc_habilitar" class="collapsed"><i class="icon mdi mdi-chevron-down"></i>Documentos Para Habilitar</a></h4>
                </div>
                <div id="doc_habilitar" class="panel-collapse collapse">
                  <div class="panel-body">
                    <div class="row">
                      <input type="hidden" id="deta_condu">
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <p class="text-center text-primary" style="font-size:14pt; margin-top:20px;"><strong>Documentos
                            obligatorios:</strong></p>
                        <hr>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label style="font-weight:800; margin-top:20px;">Fotos del Conductor</label>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label style="font-weight:800; margin-top:20px;">Fotos de Indumentaria</label>
                      </div>
                    </div>
                    <div class="row">
                      <p class="text-center text-primary" style="font-size:14pt; margin-top:20px;"><strong>Documentos
                          complementarios:</strong></p>
                      <hr>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label style="font-weight:800; margin-top:20px;">Referencia laboral</label>
                        <table class="table">
                          <thead style="text-align:left;
                       					 color:white; background-color:#FFA900;">
                            <tr>
                              <th style="width:3%;">#</th>
                              <th style="width:5%;">Documento/Img</th>
                              <th style="width:10%;">Nombre</th>
                              <th style="width:20%;">Actualice documento</th>
                            </tr>
                          </thead>
                          <tbody id="consulta_documentos">
                          </tbody>
                        </table>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label style="font-weight:800; margin-top:20px;">Referencia Personal</label>
                        <table class="table">
                          <thead style="text-align:left;
                       					 color:white; background-color:#FFA900;">
                            <tr>
                              <th style="width:3%;">#</th>
                              <th style="width:5%;">Documento/Img</th>
                              <th style="width:10%;">Nombre</th>
                              <th style="width:20%;">Actualice documento</th>
                            </tr>
                          </thead>
                          <tbody id="documentos_personal">
                          </tbody>
                        </table>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label style="font-weight:800; margin-top:20px;">Licencia</label>
                        <table class="table">
                          <thead style="text-align:left;
                       					 color:white; background-color:#FFA900;">
                            <tr>
                              <th style="width:3%;">#</th>
                              <th style="width:5%;">Documento/Img</th>
                              <th style="width:10%;">Nombre</th>
                              <th style="width:20%;">Actualice documento</th>
                            </tr>
                          </thead>
                          <tbody id="documentos_licencia">
                          </tbody>
                        </table>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label style="font-weight:800; margin-top:20px;">Rut</label>
                        <table class="table">
                          <thead style="text-align:left;
                       					 color:white; background-color:#FFA900;">
                            <tr>
                              <th style="width:3%;">#</th>
                              <th style="width:5%;">Documento/Img</th>
                              <th style="width:10%;">Nombre</th>
                              <th style="width:20%;">Actualice documento</th>
                            </tr>
                          </thead>
                          <tbody id="documentos_rut">
                          </tbody>
                        </table>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label style="font-weight:800; margin-top:20px;">Eps</label>
                        <table class="table">
                          <thead style="text-align:left;
                       					 color:white; background-color:#FFA900;">
                            <tr>
                              <th style="width:3%;">#</th>
                              <th style="width:5%;">Documento/Img</th>
                              <th style="width:10%;">Nombre</th>
                              <th style="width:20%;">Actualice documento</th>
                            </tr>
                          </thead>
                          <tbody id="documentos_eps">
                          </tbody>
                        </table>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label style="font-weight:800; margin-top:20px;">Arl</label>
                        <table class="table">
                          <thead style="text-align:left;
                       					 color:white; background-color:#FFA900;">
                            <tr>
                              <th style="width:3%;">#</th>
                              <th style="width:5%;">Documento/Img</th>
                              <th style="width:10%;">Nombre</th>
                              <th style="width:20%;">Actualice documento</th>
                            </tr>
                          </thead>
                          <tbody id="documentos_arl">
                          </tbody>
                        </table>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <label style="font-weight:800; margin-top:20px;">Curso Mercancías peligrosas</label>
                        <table class="table">
                          <thead style="text-align:left;
                       					 color:white; background-color:#FFA900;">
                            <tr>
                              <th style="width:3%;">#</th>
                              <th style="width:5%;">Documento/Img</th>
                              <th style="width:10%;">Nombre</th>
                              <th style="width:20%;">Actualice documento</th>
                            </tr>
                          </thead>
                          <tbody id="documentos_peligro">
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="panel panel-default" id="panel_papeles" style="display:none;">
                <div class="panel-heading">
                  <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#documentos" class="collapsed"><i class="icon mdi mdi-chevron-down"></i>Documentos prefiltro</a></h4>
                </div>
                <div id="documentos" class="panel-collapse collapse">
                  <div class="panel-body">
                    <div class="row">
                      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <label>¿Desea Agregar un documento?</label>
                      </div>
                      <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                        <button class=" form-control btn btn-info mdi mdi-plus input-sm text-center" data-toggle="tooltip" data-placement="top" title="Agregar" id="agregar_docu"> Agregar
                          Documentos</button>
                      </div>
                    </div><br>
                    <div class="row">
                      <table class="table table-bordered table-condensed">
                        <thead style="background-color:#332D2D;color:#fff;text-align:center;">
                          <th>#</th>
                          <th>Tipo Hoja Vida</th>
                          <th>Clase</th>
                          <th>Ruta</th>
                          <th>Subir</th>
                          <th>Nombre Archivo</th>
                          <th>Acción</th>
                        </thead>
                        <tbody id="tabla_papeles">
                        </tbody>
                      </table>
                    </div>
                    <input type="hidden" id="cont_papel">
                    <input type="hidden" id="valor_documento" class="form-control input-sm" readonly="readonly" value="6">
                  </div>
                </div>
              </div>

              <div class="panel panel-default" id="panel_fletepk" style="display:none;">
                <div class="panel-heading">
                  <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#collapseTwo" class="collapsed"><i class="icon mdi mdi-chevron-down"></i>Subasta</a></h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse">
                  <div class="panel-body">
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                      <label>Placa</label>
                      <input type="text" id="su_placa" class="form-control input-sm" readonly="readonly">
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                      <label>Num. servicio</label>
                      <input type="text" id="su_servicio" class="form-control input-sm" readonly="readonly">
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                      <label>Flete sugerido</label>
                      <input type="text" id="su_fletecot" class="form-control input-sm" readonly="readonly">
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                      <label>Total flete propuesto</label>
                      <input type="text" id="su_propuesto" class="form-control input-sm" min="0">
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                      <label>Total peso bruto(Tn)</label>
                      <input type="text" id="su_neto" class="form-control input-sm" readonly="readonly">
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                      <label title="sumatoria">Total peso Neto(Kg)</label>
                      <input type="text" id="su_sumatorianeto" class="form-control input-sm" readonly="readonly">
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                      <label>estado creación</label>
                      <input type="text" id="su_estado" value="pendiente" class="form-control input-sm" readonly="readonly">
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                      <label>usuario creación</label>
                      <input type="text" id="su_user" class="form-control input-sm" value="<?php echo $ssn_nombre; ?>" readonly="readonly">
                    </div>
                    <div class="col-xs-4 col-md-4 col-sm-4 col-lg-4">
                      <label>Fecha creación</label>
                      <input type="text" id="su_fecha" value="<?php echo date('Y-m-d'); ?>" class="form-control input-sm" readonly="readonly">
                    </div>
                    <div class="col-xs-4 col-md-4 col-sm-4 col-lg-4">
                      <label>Hora creación</label>
                      <input type="text" id="su_hora" value="<?php echo date('H:i:s'); ?>" class="form-control input-sm" readonly="readonly">
                    </div>
                    <div class="col-xs-4 col-md-4 col-sm-4 col-lg-4">
                      <label>Número subasta</label>
                      <input type="text" id="su_numsubasta" class="form-control input-sm" readonly="readonly">
                    </div>
                    <div class="col-xs-4 col-md-4 col-sm-4 col-lg-4">
                      <label>Responsable VehÍculo <span style="color:red;"><i>(*)</i></span></label>
                      <select name="responsable_vehiculo" id="responsable_vehiculo" class="form-control input-sm "></select>
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                      <input type="hidden" id="su_tarifacot" class="form-control input-sm" readonly="readonly">
                    </div>
                    <input type="hidden" id="su_valida" class="form-control input-sm" readonly="readonly" value="1">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" id="btn_cerrar" data-dismiss="modal" class="btn btn-danger btn-xs md-close" id="cierremodal"><i class="fas fa-times"></i> Cancelar</button>
        <button id="crear_preestudio" class="btn btn-success btn-xs"><i class="far fa-save"></i> Guardar Prefiltro</button>
      </div>
    </div>
  </div>
</div> -->

<div id="loading-overlay-nexosapp" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para NexosAPP...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
  </div>
</div>

<!-- <script src=<?php echo BASE_URL; ?>/views/prefiltro_nacional/js/prefiltro_nacional.js type="text/javascript"></script> -->
<?php
// $vista .= '
// 		<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
// 		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
// 		<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

// 		<script src="%root_file%js/main.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
// 		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

// 		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
// 		<link  rel="stylesheet" type="text/css" href="assets/lib/select2/css/select2.min.css"/>

// 		<link rel="stylesheet" type="text/css" src="%root_file%lib/assets/lib/select2/css/select2.min.css"/>

// 		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
// 		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

// 		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
// 		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
// 		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
// 		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

// 		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
// 		<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
// 		<!--<script type="text/javascript">
// 			$.fn.niftyModal(\'setDefaults\',{
// 				overlaySelector: \'.modal-overlay\',
// 				closeSelector: \'.modal-close\',
// 				classAddAfterOpen: \'modal-show\',
// 			});
// 			$(document).ready(function(){
// 				//initialize the javascript
// 				App.init();
// 			});
// 			$(document).ready(function(){
// 				//initialize the javascript
// 				App.init();
// 				App.dataTables();
// 			});
// 			$(document).ready(function(){
// 				//initialize the javascript
// 				App.init();
// 				App.wizard();
// 			});
// 		</script>-->
// 	';

// /**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/ //7.1   NO TOCARRRRRRRRR NUNCA
// $vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
// $vista = str_replace("%content%", $table_content, $vista); //variable $table_content sirve para crear adentro de esta todo lo que se va a mostrar en el cuerpo del conetenedor
// //$vista = str_replace("%content2%" , $table_content2 , $vista);
// echo $vista;
?>
<!-- <script type="text/javascript">
  $(".uno").hide();
  $(".dos").hide();
  $("#agregue_tb").hide();
  $("#label").hide();
  $(".panel_papeles").hide();
  //$("#panel_fletepk").hide();
  $("#thv").change(function() {
    var tipohv = $("#thv").val();
    $("#label").val(tipohv);
    if (tipohv == 'propietario' || tipohv == 'conductor' || tipohv == 'tenedor' || tipohv == 'vehiculo' || tipohv ==
      'trailer') {
      $(".uno").show();
      $(".dos").show();
      $("#agregue_tb").show();
      $("#label").show();
    } else {
      $(".uno").hide();
      $(".dos").hide();
      $("#agregue_tb").hide();
      $("#elbtn").hide();
      $("#label").hide();
    }
  });


  $("#su_propuesto").change(function() {
    $('#su_propuesto').val(parseFloat($('#su_propuesto').val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,")
      .toString());
  });


  //Sugerir flete para aprobacion

  function sugerir_flete(element) {
    var elemento = $(element);
    var idcotizacion = elemento.data("id");
    var idservicio = elemento.data("id2");
    var dato = {
      idcotizacion: idcotizacion,
      idservicio: idservicio,
      action: 'datos_sugerencia'
    };
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: dato,
      dataType: 'json',
      success: function(data) {
        $("#s_fletecap").val('');
        $("#s_tarifa").val('');
        $("#s_calculo").val('');
        $("#s_rentabilidad").val('');
        if (data) {
          var p;
          if (data.result[0].tipo_carga == 'G') {
            p = 'General';
          }
          if (data.result[0].tipo_carga == 'P') {
            p = 'Paqueteo';
          }
          if (data.result[0].tipo_carga == 'C') {
            p = 'Contenedor Cargado';
          }
          $("#s_cliente").val(data.result[0].nombre_cliente);
          $("#s_nsolicitud").val(idservicio);
          $("#s_vehiculo").val(data.result[0].tipovehiculo);
          $("#s_tipocarga").val(p);
          $("#s_mercancia").val(data.result[0].tipo_mercancia);
          $("#s_pesobruto").val(data.result[0].peso_bruto_kg);
          $("#s_pesnonetok").val(data.result[0].peso_neto_kg);
          $("#s_pesonetot").val(data.result[0].peso_neto_tn);
          $("#s_flete").val(data.result[0].flete);
          $("#s_rentactual").val(data.result[0].tmer_utili);
          $("#s_cotizacion").val(idcotizacion);
          $("#s_idservicio").val(idservicio);
          $("#s_tarifa").val(data.result[0].total_tarifa);
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        alert('error datos');
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });
    //consulta tabla
    var cons_table = {
      idcotizacion: idcotizacion,
      idservicio: idservicio,
      action: 'consulta_fletespropuesto'
    };
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: cons_table,
      dataType: 'json',
      success: function(data) {
        if (data) {
          var c = 0;
          $("#cuerpo_fletespropuestos").html('');
          data.result.forEach(function(element, index) {
            c++;
            var btn_anular = '';
            if (element.estado == 2 && element.estado_actual == 1) {
              btn_anular = '<button id="anular' + c +
                '" class="btn btn-xs btn-danger mdi mdi-close-circle-o" title="Anular" onclick="Anular_propuesta(' +
                element.id + ',' + c + ',' + element.idestado + ');"></button>';
            }
            var statu;
            var color;
            if (element.estado == 2) {
              statu = 'Pendiente';
              color = 'primary';
            }
            if (element.estado == 1) {
              statu = 'Aprobado';
              color = 'success';
            }
            if (element.estado == 3) {
              statu = 'Anulado';
              color = 'secondary';
            }
            if (element.estado == 4) {
              statu = 'Rechazado';
              color = 'danger';
            }

            $("#cuerpo_fletespropuestos").append('<tr>' +
              '<td class="text-' + color + '">' + statu + '</td>' +
              '<td>' + element.flete_nuevo + '</td>' +
              '<td>' + element.fecha + '</td>' +
              '<td>' + element.hora + '</td>' +
              '<td>' + element.usuario + '</td>' +
              '<td class="text-center">' + btn_anular + '</td>' +
              '</tr>');
          });
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });
  }

  $("#s_fletecap").change(function() {
    var fle = $("#s_fletecap").val();
    //tarifa
    var tarifa = $("#s_tarifa").val();
    //calcular utilidad
    resta = (parseFloat(tarifa) - parseFloat(fle));
    calculo = (parseFloat(resta) / parseFloat(tarifa));
    res = (parseFloat(calculo) * 100);
    res = res.toFixed(2);
    $("#s_calculo").val(res);
    //calcular rentabilidad
    var rent = (parseFloat(tarifa) - parseFloat(fle));
    $("#s_rentabilidad").val(rent);
  });

  $("#btn_guadarp").click(function() {
    var msg_error = '';
    if (!$("#s_cliente").val()) {
      msg_error += "<p>El campo <strong>Cliente</strong> para poder registrar.</p>";
    }
    if (!$("#s_nsolicitud").val()) {
      msg_error += "<p>El campo <strong>N° solicitud</strong> para poder registrar.</p>";
    }
    if (!$("#s_vehiculo").val()) {
      msg_error += "<p>El campo <strong>Vehículo</strong> para poder registrar.</p>";
    }
    if (!$("#s_tipocarga").val()) {
      msg_error += "<p>El campo <strong>Tipo carga</strong> para poder registrar.</p>";
    }
    if (!$("#s_mercancia").val()) {
      msg_error += "<p>El campo <strong>Mercancía</strong> para poder registrar.</p>";
    }
    if (!$("#s_pesobruto").val()) {
      msg_error += "<p>El campo <strong>Peso Bruto</strong> para poder registrar.</p>";
    }
    if (!$("#s_pesnonetok").val()) {
      msg_error += "<p>El campo <strong>Peso Neto(kg)</strong> para poder registrar.</p>";
    }
    if (!$("#s_pesonetot").val()) {
      msg_error += "<p>El campo <strong>Peso Neto(Tn)</strong> para poder registrar.</p>";
    }
    if (!$("#s_flete").val()) {
      msg_error += "<p>El campo <strong>Flete cotización</strong> para poder registrar.</p>";
    }
    if (!$("#s_rentactual").val()) {
      msg_error += "<p>El campo <strong>Rentabilidad actual</strong> para poder registrar.</p>";
    }
    if (!$("#s_idservicio").val()) {
      msg_error += "<p>Debe diligenciar el campo <strong>N° solicitud</strong> para poder registrar.</p>";
    }
    if (!$("#s_fletecap").val()) {
      msg_error += "<p>Debe diligenciar el campo <strong>Flete sugerido</strong> para poder registrar.</p>";
    }
    if (!msg_error) {
      Crear_Sugerencia();
    } else {
      $("#msg_posponerflete").html(
        '<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' +
        msg_error + '</div></div>');
      $("#cambiar_flete").animate({
        scrollTop: 0
      }, 600);
    }
  });

  function Anular_propuesta(idtb, id, idestado) {
    var anular = {
      idtbpropuesta: idtb,
      idtbestado: idestado,
      action: 'Anular_Propuesta'
    };
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: anular,
      dataType: 'json',
      success: function(data) {
        alert('Datos Actualizados Exitosamente!!');
        $("html, body").animate({
          scrollTop: 0
        }, 600);
        setTimeout(function() {
          location.reload(false);
        }, 800);
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });
  }

  //insertar
  function Crear_Sugerencia() {
    var s_cliente = $("#s_cliente").val();
    var s_nsolicitud = $("#s_nsolicitud").val();
    var s_vehiculo = $("#s_vehiculo").val();
    var s_tipocarga = $("#s_tipocarga").val();
    var s_mercancia = $("#s_mercancia").val();
    var s_pesobruto = $("#s_pesobruto").val();
    var s_pesnonetok = $("#s_pesnonetok").val();
    var s_pesonetot = $("#s_pesonetot").val();
    var s_flete = $("#s_flete").val();
    var s_renta = $("#s_rentactual").val(); //rentabilidad anterior
    var s_cotizacion = $("#s_cotizacion").val();
    var s_idservicio = $("#s_idservicio").val();
    var s_fletecep = $("#s_fletecap").val();
    var s_tarifa = $("#s_tarifa").val();
    var s_calculo = $("#s_calculo").val(); //UTILIDAD nueva
    var s_rentab = $("#s_rentabilidad").val(); //rentabilidad nueva
    var s_total = $("#s_total").val();
    var consultar = {
      s_cotizacion: s_cotizacion,
      s_idservicio: s_idservicio,
      action: 'Consultar_estado'
    };

    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: consultar,
      dataType: 'json',
      success: function(data) {
        if (data.result != null) {
          alert('Existe una propuesta de Flete en estado Pendiente');
        }
        if (data.result == null) {
          Insertar_Sugerencia();
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });
  }

  function Insertar_Sugerencia() {
    var s_cliente = $("#s_cliente").val();
    var s_nsolicitud = $("#s_nsolicitud").val();
    var s_vehiculo = $("#s_vehiculo").val();
    var s_tipocarga = $("#s_tipocarga").val();
    var s_mercancia = $("#s_mercancia").val();
    var s_pesobruto = $("#s_pesobruto").val();
    var s_pesnonetok = $("#s_pesnonetok").val();
    var s_pesonetot = $("#s_pesonetot").val();
    var s_flete = $("#s_flete").val();
    var s_renta = $("#s_rentactual").val(); //rentabilidad anterior
    var s_cotizacion = $("#s_cotizacion").val();
    var s_idservicio = $("#s_idservicio").val();
    var s_fletecep = $("#s_fletecap").val();
    var s_tarifa = $("#s_tarifa").val();
    var s_calculo = $("#s_calculo").val(); //UTILIDAD nueva
    var s_rentab = $("#s_rentabilidad").val(); //rentabilidad nueva
    var s_total = $("#s_total").val();
    var parametro = {
      s_cotizacion: s_cotizacion,
      s_idservicio: s_idservicio,
      s_fletecep: s_fletecep,
      s_tarifa: s_tarifa,
      s_calculo: s_calculo,
      s_renta: s_renta,
      s_rentab: s_rentab,
      s_total: s_total,
      s_cliente: s_cliente,
      action: 'Crear_Sugerencia'
    };
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: parametro,
      dataType: 'json',
      success: function(data) {
        if (data) {
          alert('Datos Registrados Exitosamente!!');
          $("html, body").animate({
            scrollTop: 0
          }, 600);
          setTimeout(function() {
            location.reload(false);
          }, 800);
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });
  }

  //validar los radiobutton de los tipos de hoja de vida
  $(".panel_seguridad").hide();
  $("#papeles").hide();
  $("#nuevo").change(function() {
    if ($(this).is(":checked")) {
      if ($("#estado_vehiculo").val() == 'Nuevo') {
        $(".panel_seguridad").hide();
        $("#papeles").show();
        $("#placag").prop('disabled', true);
        // $("#placat").prop('disabled', true);
        $("#web").prop('disabled', true);
        $("#user_satelite").prop('disabled', true);
        $("#clave").prop('disabled', true);
        $("#nompro").prop('disabled', true);
        $("#docupro").prop('disabled', true);
        $("#nomtene").prop('disabled', true);
        $("#docutene").prop('disabled', true);
        $("#nomcondu").prop('disabled', true);
        $("#docucondu").prop('disabled', true);
        $("#obserpree").prop('disabled', true);
        $("#capa_carga_vh").prop('disabled', true);
        //$("#btn_soli").prop('disabled', false);
        var i;
        for (i = 1; i <= 3; i++) {
          $("#idrl" + i).prop('disabled', true);
          $("#referencias_empresariales" + i).prop('disabled', true);
          $("#fingreso" + i).prop('disabled', true);
          $("#fretiro" + i).prop('disabled', true);
          $("#contacto_ref" + i).prop('disabled', true);
          $("#celular_ref" + i).prop('disabled', true);
          $("#cargo_ref" + i).prop('disabled', true);
          $("#anti_ref" + i).prop('disabled', true);
          $("#docuupdate" + i).prop('disabled', true);
        }
      } else {
        $(".panel_seguridad").hide();
        $("#papeles").show();
        $("#placag").prop('disabled', true);
        // $("#placat").prop('disabled', false);
        $("#web").prop('disabled', false);
        $("#user_satelite").prop('disabled', false);
        $("#clave").prop('disabled', false);
        $("#nompro").prop('disabled', false);
        $("#docupro").prop('disabled', false);
        $("#nomtene").prop('disabled', false);
        $("#docutene").prop('disabled', false);
        $("#nomcondu").prop('disabled', false);
        $("#docucondu").prop('disabled', false);
        $("#obserpree").prop('disabled', false);
        $("#capa_carga_vh").prop('disabled', false);
        //$("#btn_soli").prop('disabled', false);
        var i;
        for (i = 1; i <= 3; i++) {
          $("#idrl" + i).prop('disabled', false);
          $("#referencias_empresariales" + i).prop('disabled', false);
          $("#fingreso" + i).prop('disabled', false);
          $("#fretiro" + i).prop('disabled', false);
          $("#contacto_ref" + i).prop('disabled', false);
          $("#celular_ref" + i).prop('disabled', false);
          $("#cargo_ref" + i).prop('disabled', false);
          $("#anti_ref" + i).prop('disabled', false);
          $("#docuupdate" + i).prop('disabled', false);
        }
        // flete_desbloquear(); Echo por mi
      }
    }
  });

  $("#agregue_tb").click(function() {
    var msg_error = "";
    if (!$("#dato").val()) {
      msg_error +=
        "<p>Debe diligenciar el <strong>Campo actualizar</strong> para poder agregar las actualizaciones a seguridad.</p>";
    }
    if (!$("#detalle").val()) {
      msg_error +=
        "<p>Debe diligenciar el<strong>Información actualizar</strong> para poder agregar las actualizaciones a seguridad.</p>";
    }
    if (!msg_error) {
      tabla_seguridad();

    } else {
      $("#msg_alerta").html(
        '<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' +
        msg_error + '</div></div>');
      $("#crea_vehiculopreestudio").animate({
        scrollTop: 0
      }, 600);
    }
  });

  var conteo = 0;
  var a = 0;

  function tabla_seguridad() {
    conteo++
    a++
    //alert('tabla_seguridad');
    var tipo = $("#label").val();
    var dato = $("#dato").val();
    var detalle = $("#detalle").val();
    var archivo = '<input type="file" id="arc' + conteo + '" name="arcs[]" onchange="name_fontal(this.value,' + conteo + ')" class="form-control input-sm" accept="image/*,.pdf">';
    var nom = '<input type="text" id="nam' + conteo + '" class="form-control input-sm" name="man[]" disabled="disabled">';

    var ch = '<input type="button" id="p' + a + '" class="btn-primary borrar3" value="Eliminar">';

    $("#cuerpo_actu").append('<tr id="fila' + conteo + '">' +
      '<td><p><strong>' + conteo + '</strong></p><input type="hidden" id="sa' + a + '" value="1">  </td>' +
      '<td>' + tipo + '</td><td>' + dato + '</td><td>' + detalle + '</td>' + '<td>' + archivo + nom + '</td>' + '<td>' +
      ch + '</td></tr>');
    $("#dato").val('');
    $("#detalle").val('');
    $("#valortb").val(conteo);
  }

  $(document).on('click', '.borrar3', function(event) {
    event.preventDefault();
    $(this).closest('tr').remove();
    var v = this.id;
    var x = v.substr(1, 1);
    x = parseInt(x);
    var m = $("#sa" + x).val();
  });

  //funcion para eliminar filas de la tabla
  function eliminar_fila(id) {
    $("#fila" + id + "").remove();
  }

  //funcion para poner el nombre de los archivos Actualiza seguridad (hojas de vida)
  function name_fontal(fic, id) {
    var input = document.getElementById('arc' + id + ''); // Reemplaza 'tuInputFile' con el ID de tu input file
    var archivo = input.files[0];

    if (archivo) {
      var nombreArchivo = archivo.name;
      var extension = nombreArchivo.split(".").pop().toLowerCase();

      var extensionesPermitidas = ["pdf", "jpg", "png", "webp"]; // Lista de extensiones permitidas

      if (extensionesPermitidas.indexOf(extension) === -1) {
        let mensaje = `
            <div class="alert alert-primary alert-icon alert-icon-border alert-dismissible" role="alert">
                <div class="icon"><i class="fas fa-info"></i></div>
                <div class="message">
                  <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                  <strong>Mensaje!</strong> Extensión de archivo no permitida. Por favor, selecciona un archivo con una de las siguientes extensiones: ${extensionesPermitidas.join(", ")}
                </div>
            </div>`;
        $("#crea_vehiculopreestudio").animate({
          scrollTop: 0
        }, 600);
        d.getElementById("historicos").innerHTML = mensaje;
        input.value = ""; // Limpia el campo de entrada
      } else {
        fic = fic.split('\\');
        if (fic == '' || fic == null) {
          $("#nam" + id).val('');
        } else {
          $("#nam" + id).val(fic[fic.length - 1]);
        }
      }
    }

  }

  //Eliminar documentos
  $(document).on('click', '.borrar2', function(event) {
    event.preventDefault();

    $(this).closest('tr').remove();
    var v = this.id;
    //alert('v'+v);
    var x = v.substr(1, 1);
    x = parseInt(x);
    //$("#sk"+x).val();
    var d = $("#sk" + x).val();
  });
  //agregar documentos campos
  var a = 0;
  var b = 0;
  $("#agregar_docu").click(function() {
    a++; //contador
    b++;
    var m, sw;

    //if(sw==1){
    var ch = '<input type="button" id="p' + a + '" class="btn-primary borrar2" value="Eliminar">';
    var hv = '<select id="tipohoja' + a + '" name="tipohoja[]" class="form-control input-sm" onchange="tipodehoja(' +
      a + ', this.value);" >' +
      '<option value="">Seleccione</option>' +
      '<option value="Propietario">Propietario</option>' +
      '<option value="Tenedor">Tenedor</option>' +
      '<option value="Conductor">Conductor</option>' +
      '<option value="Vehiculo">Vehículo</option>' +
      '<option value="Trailer">Trailer</option>' +
      '<option value="Referencia_laboral1">Referencia laboral 1</option>' +
      '<option value="Referencia_laboral2">Referencia laboral 2</option>' +
      '<option value="Referencia_laboral3">Referencia laboral 3</option>' +
      +'</select>';
    var clase = '<select id="clase' + a + '" name="clase[]" class="form-control input-sm"><option value="">Seleccione</option>' +
      '<option value="cedula">Cédula</option>' +
      '<option value="cedula_extranjeria">Cédula de extranjería</option>' +
      '<option value="tarjeta_propiedad">Tarjeta de propiedad</option>' +
      '<option value="pasaporte">Pasaporte</option>' +
      '<option value="referencia_laboral">Referencia laboral</option>' +
      '<option value="referencia_personal">Referencia personal</option>' +
      '<option value="licencia">Licencia </option>' +
      '<option value="fotografia_vehiculo">Fotografias vehículo</option>' +
      '<option value="fotografia_conductor_frontal">Fotografia del conductor frontal</option>' +
      '<option value="fotografia_conductor_derecha">Fotografia del conductor derecha</option>' +
      '<option value="fotografia_conductor_izquierda">Fotografia del conductor izquierda</option>' +
      '<option value="fotografia_indumentaria">Fotografia de Indumentaria</option>' +
      '<option value="fotografia_trailer">Fotografia de trailer</option>' +
      '<option value="rut">Rut</option>' +
      '<option value="Antecedentes_policivos">Antecedentes policivos</option>' +
      '<option value="otros">Otros</option>' +
      +' </select>';
    //rutas
    var papel = '<tr>' +
      '<td><p><strong>' + a + '</strong></p><input type="hidden" id="sk' + a + '" value="1">   </td>' +
      '<td>' + hv + '</td>' +
      '<td>' + clase + '</td>' +
      '<td><input type="text" class="form-control input-sm" id="ruta' + a + '" name="ruta[]" disabled="disabled"></td>' +
      '<td><input type="file" class="form-control input-sm" name="documento[]" id="documento' + a + '" onchange="namedocumento(' + a + ', this.value);" accept="image/*,.pdf"> </td>' +
      '<td> <input type="text" class="form-control input-sm" name="namearchivo[]" id="namearchivo' + a + '" readonly="readonly"></td>' +
      '<td>' + ch + '</td>' +
      +'</tr>';

    $("#tabla_papeles").append(papel);
    $("#cont_papel").val(b);
  });

  function tipodehoja(id, valor) {
    if (valor == '') {
      alert('Por favor seleccione un tipo de hoja de vida');
      $("#ruta" + id + "").val("");
    }

    if (valor == 'Propietario') {
      //ruta
      var r = 'public/files/datostransporte/Propietario//';
      $("#ruta" + id + "").val(r);
      //tipo de documentos
    }

    if (valor == 'Tenedor') {
      var r = 'public/files/datostransporte/Tenedor//';
      $("#ruta" + id + "").val(r);
    }

    if (valor == 'Conductor') {
      var r = 'public/files/datostransporte/Conductor//';
      $("#ruta" + id + "").val(r);
    }

    if (valor == 'Vehiculo') {
      var r = 'public/files/datostransporte/Vehiculo//';
      $("#ruta" + id + "").val(r);
    }

    if (valor == 'Trailer') {
      var r = 'public/files/datostransporte/Trailer//';
      $("#ruta" + id + "").val(r);
    }

    if (valor == 'Referencia_laboral1') {
      var r = 'public/files/datostransporte/lab1//';
      $("#ruta" + id + "").val(r);
    }
    if (valor == 'Referencia_laboral2') {
      var r = 'public/files/datostransporte/lab2//';
      $("#ruta" + id + "").val(r);
    }
    if (valor == 'Referencia_laboral3') {
      var r = 'public/files/datostransporte/lab3//';
      $("#ruta" + id + "").val(r);
    }

  }
  //funcion para extraer el nombre de los documentos
  function namedocumento(id, valor) {
    var input = document.getElementById('documento' + id + ''); // Reemplaza 'tuInputFile' con el ID de tu input file
    var archivo = input.files[0];
    if (archivo) {
      var nombreArchivo = archivo.name;
      var extension = nombreArchivo.split(".").pop().toLowerCase();
      var extensionesPermitidas = ["pdf", "jpg", "png", "webp"]; // Lista de extensiones permitidas
      if (extensionesPermitidas.indexOf(extension) === -1) {
        let mensaje = `
            <div class="alert alert-primary alert-icon alert-icon-border alert-dismissible" role="alert">
                <div class="icon"><i class="fas fa-info"></i></div>
                <div class="message">
                  <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                  <strong>Mensaje!</strong> Extensión de archivo no permitida. Por favor, selecciona un archivo con una de las siguientes extensiones: ${extensionesPermitidas.join(", ")}
                </div>
            </div>`;
        $("#crea_vehiculopreestudio").animate({
          scrollTop: 0
        }, 600);
        d.getElementById("historicos").innerHTML = mensaje;
        input.value = ""; // Limpia el campo de entrada
      } else {
        var docu = document.getElementById('documento' + id + '').files[0].name;
        $("#namearchivo" + id + "").val(docu);
      }
    }
  }

  $(".ocultar").hide();
  //consultar cotizacion y solicitud de servicio
  function consulta_coti(element) {
    $("#consultass_general").html('');
    $("#contener_remitente").html('');
    $(".destinatari").html('');
    var elemento = $(element);
    var num_cotizacion = elemento.data("id");
    var solicitud_servicio = elemento.data("id2");
    var id_bloque = elemento.data("id3");
    var c_pedida = elemento.data("id4");
    var c_disponible = elemento.data("id5");
    var consulta_solicitud = {
      cotizar: num_cotizacion,
      solicitud: solicitud_servicio,
      action: 'consulta_serviciob'
    };
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: consulta_solicitud,
      dataType: 'json',
      success: function(data) {
        if (data) {

          $("#consultass_general").html(`
          <table class="table table-bordered table-striped">
              <colgroup>
              <col class="col-xs-2">
              <col class="col-xs-7">
              </colgroup>
              <thead>
                  <tr>
                      <th>Items</th>
                      <th>Descripsión</th>
                  </tr>
              </thead>
              <tbody>
                    <tr>
                      <th scope="row"><b>Solicitud</b></th>
                      <td>${solicitud_servicio}- Cot:${num_cotizacion}</td>
                    </tr>
                    <tr>
                      <th scope="row"> <b>Cliente:</b> </th>
                      <td>${data.result[0].nombre_cliente}</td>
                    </tr>
                    <tr>
                      <th scope="row"> <b>Ruta</b> </th>
                      <td>${ data.result[0].origen } - ${data.result[0].destino}</td>
                    </tr>
                    <tr>
                      <th scope="row"><b>Vehículo</b> </th>
                      <td>${data.result[0].nombre} - Cant. Solicitada: ${data.result[0].cant_vehiculo} - Cant. Disponible: ${data.result[0].cant_disponible} </td>
                    </tr>
                    <tr>
                      <th scope="row"><b>Peso</b></th>
                      <td>${data.result[0].peso_kg } KG</td>
                    </tr>
                    <tr>
                      <th scope="row"><b>Materias Primas</b></th>
                      <td>${data.result[0].tipo_mercancia } - ${data.result[0].cantidad_empaque} - ${data.result[0].volumen_total}</td>
                    </tr>
                    <tr>
                      <th scope="row"><b>Agencia</b></th>
                      <td>${data.result[0].agencia }</td>
                    </tr>
                    <tr>
                      <th scope="row"><b>Observacion:</b></th>
                      <td>${data.result[0].observacion }</td>
                    </tr>
              </tbody>
            </table>
          `);
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });

    var consulta_solciitud2 = {
      cotizar: num_cotizacion,
      solicitud: solicitud_servicio,
      // action: 'consulta_remitente'
    };
    $.ajax({
      // url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      url: $("#id_url_ajax").val() + "prefiltro_nacional/consulta_remitente",
      type: 'POST',
      data: consulta_solciitud2,
      dataType: 'json',
      success: function(data) {
        if (data) {
          data.result.forEach(function(element, index) {
            var observa = '';
            if (element.observacion != '') {
              observa = element.observacion;
            } else {
              observa = 'No hay observación';
            }
            $("#contener_remitente").append(
              '<div class="panel-body panel panel-default panel-contrast">' +
              '<span><strong>Remitentes</strong></span>' +
              '<div class="panel-heading">' +
              '<span><u>' + element.nombre + '</u></span>' +
              '<span class="panel-subtitle">' +
              '<p><strong>' + element.fecha_estimada_entrega + ' ' + element.hora_estimada + '</strong>  ' +
              element.direccion_entrega +
              '(' + element.municipio + ')' + '   ' + element.telefono + '  ' + observa + '</p>' +
              '</span>' +
              '</div>' +
              '<div class="panel-body panel-body-contrast">' +
              '<span><strong>Destinatarios</strong></span>' +
              '<div id="destinatario' + element.id +
              '" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 destinatari"></div>' +
              '</div></div>');
          });
        }
        if (data.result2 != '') {
          data.result2.forEach(function(element, index) {
            $("#destinatario" + element.remitente).append('<hr/><div>' +
              '<strong>Destinatario:</strong> ' + element.nombre + '  ' + '<strong>Dirección:</strong> ' +
              element.direccion_entrega + '  ' + '<strong>Municipio:</strong> ' + element.municipio + ' ' +
              '<strong>Fecha Hora:</strong> ' + element.fecha_estimada_entrega + ' ' + element.hora_estimada +
              '  ' + '<strong>Peso descargar:</strong> ' + element.peso + '  ' +
              '<strong>Teléfono:</strong> ' + element.telefono + '</div>');
          });
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });

  }
  //vinculos
  function ir_modulopreestudio() {
    var url = $("#id_url_ajax").val() + 'preestudiov/nacional_preestudio/?idmenu=1';
    window.location = (url);
  }

  function Status_Solo(element) {
    var elemento = $(element);
    var placa = elemento.data("id");
    // alert('status solo ');
    // alert(placa);
    //traer los movimientos de operaciones y seguridad
    //pertenecientes a esta placa
    var status_solo = {
      placa: placa,
      action: 'consultecarroindividual'
    };
    $("#movimientos_statussolo").html('');
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: status_solo,
      dataType: 'json',
      success: function(data) {
        // alert('si hay movimiento');
        if (data) {
          data.result.forEach(function(element, index) {
            $("#movimientos_statussolo").append('<tr><td>Operaciones</td>' +
              '<td>' + element.observacion + '</td>' +
              '<td>' + element.fecha_asignacion + '</td>' +
              '<td>' + element.hora_asignacion + '</td>' +
              '<td>' + element.user_log + '</td>' +
              '<td>' + element.estado + '</td>' +
              '</tr>');
          });
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        alert('No hay movimiento');
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });
  }

  function status(element) {
    // alert('hola estatus operaciones');
    $("#tbtres").hide();
    var elemento = $(element);
    var id = elemento.data("id");
    var solicitud = elemento.data("id2");
    //cotizacion
    var coti = {
      idcotizar: id,
      action: 'consulte_cotizar'
    };
    $("#movimientos_coti").html('');
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: coti,
      dataType: 'json',
      success: function(data) {
        // alert('hay datico');
        // console.log(data);
        if (data) {
          var statu = '';
          data.result.forEach(function(element, index) {
            if (element.estado == 'F3') {
              statu = 'F3-Ganada';
            }
            if (element.estado == 'F2') {
              statu = 'F2-Entregada';
            }
            if (element.estado == 'F1') {
              statu = 'F1.Realizada';
            }
            if (element.estado == 'F4') {
              statu = 'F4-Perdida';
            }
            if (element.estado == 'F5') {
              statu = 'F5-Cancelada';
            }


            $("#movimientos_coti").append('<tr><td>' + element.n_cotizacion + '</td>' +
              '<td>' + element.item + '</td>' +
              '<td>' + element.pareja + '</td>' +
              '<td>' + statu + '</td>' +
              '<td>' + element.fecha_creacion + '</td>' +
              '<td>' + element.hora_creacion + '</td>' +
              '<td>' + element.elaborado_por + '</td>' +
              '<td>' + element.proceso + '</td>' +
              '</tr>');

          });

        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });

    //solicitud de servicio + operaciones
    var status = {
      idcotizar: id,
      solicitud: solicitud,
      action: 'consulte_movimientos'
    };
    $("#movimientos_status").html('');
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: status,
      dataType: 'json',
      success: function(data) {
        // alert('hay datico');
        // console.log(data);
        //solicitud de servicio
        if (data) {
          data.result.forEach(function(element, index) {
            $("#movimientos_status").append('<tr><td>' + element.nundoc_solicitud + '</td>' +
              '<td>' + element.n_cotizacion + '</td>' +
              '<td>' + element.item + '</td>' +
              '<td>' + element.pareja + '</td>' +
              '<td>' + element.fecha + '</td>' +
              '<td>' + element.hora + '</td>' +
              '<td>' + element.usuario_auditor + '</td>' +
              '<td>' + element.estado + '</td>' +
              '<td>' + element.proceso + '</td>' +
              '</tr>');

          });
          //operaciones
          /*data.result2.forEach(function(element,index){
          	$("#movimientos_status").append('<tr><td>Operaciones</td>'+
          	'<td>'+element.fecha_asignacion+'</td>'+
          	'<td>'+element.hora_asignacion+'</td>'+
          	'<td>'+element.user_log+'</td>'+
          	'<td>'+element.estado+'</td>'+
          	'</tr>');
          });	*/
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });

    //preestudio
    var pre = {
      //solicitud de servicio
      solicitud: solicitud,
      action: 'consulte_preestudio'
    };
    $("#movimientos_preestudio").html('');
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: pre,
      dataType: 'json',
      success: function(data) {
        console.log('si llego preestudio');
        $("#tbtres").show();
        if (data) {

          $("#movimientos_preestudio").append('<tr>' +
            '<td>' + data.result[0].id_preestudio + '</td>' +
            '<td>' + data.result[0].id + '</td>' +
            '<td>' + data.result[0].id_servicio_cliente + '</td>' +
            '<td>' + data.result[0].fecha + '</td>' +
            '<td>' + data.result[0].hora + '</td>' +
            '<td>' + data.result[0].usuario + '</td>' +
            '<td>' + data.result[0].proceso + '</td>' +
            '</tr>');
        } else {
          $("#tbtres").hide();
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log('no llego preestudio');
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });



    //estados de prefiltro
    var est = {
      idcotizar: solicitud,
      action: 'consulte_preestudio_estados'
    }
    $("#estados_preestudio").html('');
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: est,
      dataType: 'json',
      success: function(data) {
        if (data) {
          data.result.forEach(function(element, index) {
            // var btn = '<button id="btn_' + element.id_preestudio +
            //   '" class="btn btn-xs btn-secondary" onClick="Historial_estado(this)"  data-id="' + element
            //   .id_preestudio + '">Historial</button>';
            $("#estados_preestudio").append('<tr><td>' + element.placa + '</td>' +
              '<td>' + element.fecha_solicitud + '</td>' +
              '<td>' + element.usuario + '</td>' +
              '<td>' + element.operacion + '</td>' +
              // '<td>' + btn + '</td>' +
              '</tr>');
          });
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log('no llego preestudio');
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });

    // //estados de prefiltro

    // var est = {
    //   idcotizar: id,
    //   action: 'consulte_preestudio_estados'
    // }
    // $("#estados_preestudio").html('');
    // $.ajax({
    //   url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
    //   type: 'POST',
    //   data: est,
    //   dataType: 'json',
    //   success: function(data) {
    //     if (data) {
    //       data.result.forEach(function(element, index) {
    //         var btn = '<button id="btn_' + element.id_preestudio +
    //           '" class="btn btn-xs btn-secondary" onClick="Historial_estado(this)"  data-id="' + element
    //           .id_preestudio + '">Historial</button>';
    //         $("#estados_preestudio").append('<tr><td>' + element.id_servicio_cliente + '</td>' +
    //           '<td>' + element.id_preestudio + '</td>' +
    //           '<td>' + element.placa + '</td>' +
    //           '<td>' + element.ultimoestado + '</td>' +
    //           '<td>' + btn + '</td>' +
    //           '</tr>');
    //       });
    //     }
    //   },
    //   error: function(jqXHR, textStatus, errorThrown) {
    //     console.log('no llego preestudio');
    //     console.log(jqXHR);
    //     console.log(textStatus);
    //     console.log(errorThrown);
    //   }
    // });
  }

  function Historial_estado(element) {
    var elemento = $(element);
    var id = elemento.data("id");
    $(document).on('click', '#btn_' + id, function() {
      $('#historial_estados').modal('show');
      $('#historial_estados').modal('handleUpdate');
      // $("#div_header").css('background','yellow');
    });
    var dato = {
      id: id,
      action: 'Consulta_Historial_Estudios'
    }
    $("#tbody_historia_estado").html('');
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: dato,
      dataType: 'json',
      success: function(data) {
        if (data) {
          data.result.forEach(function(element, index) {
            let estadoh;
            if (element.estado == 'pendiente_iniciar') {
              estadoh = 'Pendiente de iniciar';
            } else if (element.estado == 'iniciado') {
              estadoh = 'Iniciado';
            } else if (element.estado == 'aprobado') {
              estadoh = 'Aprobado';
            } else if (element.estado == 'rechazado para modificar') {
              estadoh = 'Rechazado para modificar';
            } else if (element.estado == 'rechazado') {
              estadoh = 'Rechazado';
            } else if (element.estado == 'cancelado') {
              estadoh = 'Cancelado';
            } else if (element.estado == 'vencida') {
              estadoh = 'Vencida';
            } else if (element.estado == 'pendiente') {
              estadoh = 'Pendiente';
            }
            var cuerpo_tabla = `<tr>
          <td class="text-center" style="font-size:10px;">${element.id}</td>
          <td class="text-center"style="font-size:10px;width:40px;">${element.placa}</td>
          <td class="text-center" style="font-size:10px;width:120px;">${estadoh}</td>
          <td class="text-center" style="font-size:10px;">${element.traza}</td>
        </tr>`;
            $("#tbody_historia_estado").append(cuerpo_tabla);
          });
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log('no consulta');
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });
  }

  function Visualizar(element) {
    // console.log('visualizar');
    // alert('hjdhjshd');
    var elemento = $(element);
    var id = elemento.data("id");
    var num = elemento.data("id2");
    var origen = elemento.data("id3");
    var destino = elemento.data("id4");
    var tipo_vehiculo = elemento.data("id5");
    // console.log(id);
    $("#num_cotizar").val(id);
    $("#num_soli").val(num);
    $("#origen").val(origen);
    $("#destino").val(destino);
    $("#veh").val(tipo_vehiculo);
    //traer origenes y destinos
    var ciudad = {
      origen: origen,
      destino: destino,
      action: 'ciudades_solicitudtodos'
    };
    $.ajax({
      url: $("#id_url_ajax").val() + 'libs/solicitudes_nacional_ajax.php',
      type: 'POST',
      data: ciudad,
      dataType: 'json',
      success: function(data) {
        data.result.forEach(function(element, index) {
          $("#orisoli").html(element.origi);
        });

        data.result1.forEach(function(element, index) {
          $("#destisoli").html(element.desti);
        });
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });
  }

  /*function nuevo(){
  	alert('Debe Dirigirse Al Módulo De Parámetros Para Registrar La Hoja De Vida Del Vehículo¡¡¡');
  } */
  function historico() {
    $(".ocultar").show();
  }
  $(document).on('click', '.borrar', function(event) {
    event.preventDefault();
    //eliminar de tabla

    $(this).closest('tr').remove();
    var v = this.id;
    var x = v.substr(1, 1);
    x = parseInt(x);
    $("#servicio" + x).val(0);
    x2 = $("#servicio" + x).val();
    //sumatoria();//funcion recalcular tabla totalizar
    //eliminar de tabla cuerpo_fechas
    var y = $(this).data('formid'); //traer data del boton eliminar
    $("." + y).remove();
    sumatoria(); //funcion recalcular tabla totalizar
    //eliminar de tabla cuerpo_fechas
  });

  $("#listamodal").html('');
  var con = 1;
  var cone = 1;

  function atraparsolici(cont, element) {

    var id_fila_selected;
    var elemento = $(element);
    var idsol = elemento.data("id");
    var cliente = elemento.data("id2");
    var ncotiza = elemento.data("id3");
    var item = elemento.data("id4");
    var merc = elemento.data("id5");
    var flete = elemento.data("id6");
    var pesoneto = elemento.data("id7"); //peso bruto tonelada
    //alert('idsolicitud'+idsol);
    var tarifa = elemento.data("id8");

    var valida_numsubasta = {
      numservicio: idsol,
      action: 'valida_numero_subasta'
    };
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
      type: 'POST',
      data: valida_numsubasta,
      dataType: 'json',
      success: function(data) {

        console.log(data);
        if (data.result != null) {
          //ya tiene una subasta, comparar si el número de subasta consultado es igual al número de subasta base
          var nsubasta = data.result[0]["id_subasta"];
          var num_base = $("#su_numsubasta").val();
          //sino no se puede agregar
          alert(
            'Señor usuario no puede agregar esta solicitud de servicio porque pertenece a otra subasta activa ' +
            data.result[0]["id_subasta"]);
        }
        if (data.result == null) {
          //no pertenece
          //si es condolidado pero no tiene subasta sin embargo la solicitud de base ya pertenece a una subasta no dejar elegir mas
          if ($("#su_numsubasta").val()) {
            $("#btn_soli").prop("disabled", true);
            alert(
              'Señor usuario no puede agregar solicitudes de servicio porque esta subasta ya tiene condiciones');
          } else {

            var a, sw;
            for (a = 1; a <= cone; a++) {
              var id = $("#servicio" + a).val();
              //alert('id'+id);
              if (idsol == id) {
                sw = 0;
                a = cone + 1;
                alert('Esta solicitud ya fue agregada');
              } else {
                sw = 1;
              }
            }

            if (sw == 1) {
              //agregar a el modal
              con++;
              cone = cone + 1;
              var ch = '<input type="button" id="b' + con + '" class="btn-primary borrar" data-formid="' + idsol +
                '" value="Eliminar">';
              var fila = "<tr id=" + con + " onclick='seleccionar(this.id)' class='prin" + con + "'>" +
                '<td>' + cone + '</td>' +
                '<td><input type="hidden" id="servicio' + con + '" value="' + idsol +
                '" class="fserva" name="fserva[]">' + idsol +
                '</td><td>' + ncotiza + ' (' + item + ') ' + item + ' ' + merc + '</td><td>' + cliente + '</td>' +
                '<td><input type="text" id="fl' + idsol + '" class="form-control input-xs tflete" value="' + flete +
                '" readonly="readonly"></td>' +
                '<td  style="display:none"><input type="text" class="form-control input-xs tneto2" value="' +
                pesoneto + '" readonly="readonly"></td>' +
                '<td><input type="hidden" id="tari' + con + '" class="form-control input-xs ttarifa" value="' +
                tarifa + '" readonly="readonly"></td>' +
                '<td>' + ch + '</td>' + "</tr>";
              $("#cuerpo_lista2").append(fila);
              //formatear numeros
              if ($('#fl' + idsol).val() > 0) {
                $('#fl' + idsol).val(parseFloat($('#fl' + idsol).val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,").toString());
              }
              $('.tneto2').val(parseFloat($('.tneto2').val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,")
                .toString());
              $("#tari" + con).val(parseFloat($('#tari' + con).val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g,
                "$1,").toString());

              $("#maxservi").val(cone);
              $("#maxservi2").val(cone);
              var fchas = {
                id_sol_servicio: idsol,

                action: 'consultar_fechacargue'
              };
              $.ajax({
                url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
                type: 'POST',
                data: fchas,
                dataType: 'json',
                success: function(data) {
                  if (data) {
                    var mor = 1;
                    //$("#cuerpo_fechas").html('');
                    data.result.forEach(function(element, index) {
                      mor++;
                      var datec = (element.fecha_estimada_entrega + ' ' + element.hora_estimada);
                      var actuali = moment().format('YYYY-MM-DD h:mm:ss');
                      var cant = moment(datec).diff(actuali, 'hours');
                      $("#cuerpo_fechas").append('<tr id="fil' + mor + '" class="' + element
                        .cod_ini_ruta + '">' +
                        '<td>' +
                        '<input type="hidden" id="oculto' + mor + '" value="' + cant +
                        '" class="fo" readonly="readonly">' +
                        '<input type="text" id="serv' + mor +
                        '" class="form-control input-xs fserv" value="' + element.cod_ini_ruta +
                        '" readonly="readonly"></td>' +
                        '<td><input type="text" id="fecha' + mor +
                        '" class="form-control input-xs cp" value="' +
                        element.fecha_estimada_entrega + ' ' + element.hora_estimada +
                        '" readonly="readonly"></td>' +
                        '<td><input type="text" id="peso' + mor +
                        '" class="form-control input-xs fp" value="' + element.peso +
                        '" readonly="readonly"></td>' +
                        '<td><input type="text" class="form-control input-xs" value="' + element.lugar +
                        ' (' + element.direccion_entrega + ')' + '" readonly="readonly" title="' +
                        element.direccion_entrega +
                        '" ><input type="text" class="form-control input-xs" value="' + element.muni +
                        '" readonly="readonly"></td>' +
                        '</tr>');
                      //formatear números

                      /*$("#peso"+mor+"").val(parseFloat($("#peso"+mor+"").val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,").toString());*/
                      sumatoria();
                      /*$(".fp").val(parseFloat($(".fp").val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,").toString());*/
                    });
                  }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                  console.log(jqXHR);
                  console.log(textStatus);
                  console.log(errorThrown);
                }
              });
              sumatoria();
              alert('Solicitud agregada');
            }
          }
        }
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      }
    });
  }

  function sumatoria() { //Fletes y pesos netos
    var suma = 0; //acumulador
    var suman = 0;
    var sumapes = 0;
    var sumntarifa = 0;
    $(".tflete").each(function() {
      var valor = ($(this).val()).replace(/,/g, "");
      suma += parseFloat(valor);
    });
    var canserv = $("#cuerpo_lista2").find('tr').length;
    var div = parseFloat(suma) / parseFloat(canserv);
    // $("#totalfle").val(suma);
    $(".tneto2").each(function() {
      var peso = ($(this).val()).replace(/,/g, "");
      suman += parseFloat(peso);
    });
    //sumar pesos netos , vienen del remitente
    $(".fp").each(function() {
      var valpeso = ($(this).val()).replace(/,/g, "");
      sumapes += parseFloat(valpeso);
    });
    //sumas tarifas
    $(".ttarifa").each(function() {
      var valtarifa = ($(this).val()).replace(/,/g, "");
      sumntarifa += parseFloat(valtarifa);
    });
    //var totari=parseFloat(sumntarifa)/parseFloat(canserv);
    $('#totalfle').val(suma);
    $("#tottarifa").val(sumntarifa);
    $("#totalneto").val(suman);
    $("#su_fletecot").val(suma);
    $("#su_neto").val(suman);
    $("#total_pesos").val(sumapes);
    $("#su_sumatorianeto").val(sumapes);
    $("#su_tarifacot").val(sumntarifa);
    //formatear numeros
    $('#totalfle').val(parseFloat($('#totalfle').val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,").toString());
    $('#totalneto').val(parseFloat($('#totalneto').val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,")
      .toString());
    $('#su_fletecot').val(parseFloat($('#su_fletecot').val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,")
      .toString());
    $('#su_neto').val(parseFloat($('#su_neto').val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,").toString());
    $('#total_pesos').val(parseFloat($('#total_pesos').val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,")
      .toString());
    $('#su_sumatorianeto').val(parseFloat($('#su_sumatorianeto').val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g,
      "$1,").toString());
    $("#tottarifa").val(parseFloat($('#tottarifa').val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,")
      .toString());
    $("#su_tarifacot").val(parseFloat($('#su_tarifacot').val(), 100).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, "$1,")
      .toString());
  }

  conteo = 0;

  function seleccionar(idfila) {
    if ($("#" + idfila).hasClass('seleccionada')) {
      $("#" + idfila).removeClass('seleccionada');
    } else {
      $("#" + idfila).addClass('seleccionada');
    }
    id_fila_selected = idfila;
  }
    
  $("#remover").click(function() {
    eliminar(id_fila_selected);
  });

  $("#remover2").click(function() {
    eliminar_new(id_fila_selected);
  });

  function eliminar(idfila) {
    if (idfila.length > 0) {
      $("#" + idfila).remove();
      $("#s" + idfila).remove();
      var inpu = $("#maxservi").val();
      //alert(inpu);
      var r = 0;
      r = (parseFloat(inpu) - 1);
      //alert('descontar'+r);
      $("#maxservi").val(r);
      //alert($("#maxservi").val());

    }
  }

  function eliminar_new(idfila) {
    if (idfila.length > 0) {
      $("#" + idfila).remove();
      $("#s" + idfila).remove();
      var inpu = $("#maxservi2").val();
      //alert(inpu);
      var r = 0;
      r = (parseFloat(inpu) - 1);
      //alert('descontar'+r);
      $("#maxservi2").val(r);
      //alert($("#maxservi").val());
    }
  }

  function atraparVehiculo(element) {
    // alert('atrapado');
    var elemento = $(element);
    var placa = elemento.data("id");
    $("#cargar_cliente").val(placa);
    $("#exampleModalLong").modal('hide');
    $("#placa_sele").val(placa);
  }

  $("#asignar").click(function() {
    alert('asignar vehiculo a esta solicitud de servicio');
    //UPDATE EN LA TABLA cmx_solicitud_vehiculo2 enviado la placa
    var placa = $("#placa_sele").val();
    var n_solicitud = $("#num_soli").val();
    var usuario = $("#usuario").val();
    var tipo_vehiculo = $("#veh").val();
    var observe = $("#observe").val();
    // alert(placa);
    // alert(n_solicitud);
    if (!placa) {
      alert('la placa esta vacia, por favor busque un vehículo para asignarlo a esta Solicitud');
    } else {

      var asigne = {
        placa: placa,
        n_solicitud: n_solicitud,
        user: usuario,
        vehiculo: tipo_vehiculo,
        observe: observe,
        action: 'asinar_vehiculo_solicitud'
      };
      $.ajax({
        url: $("#id_url_ajax").val() + "libs/solicitudes_nacional_ajax.php",
        type: 'POST',
        data: asigne,
        dataType: 'json',
        success: function(data) {
          alert('Datos registrados exitosamente!!!');
          $("html, body").animate({
            scrollTop: 0
          }, 600);
          setTimeout(function() {
            location.reload(false);
          }, 800);

        },
        error: function(jqXHR, textStatus, errorThrown) {
          console.log('error de asignacion');
          console.log(jqXHR);
          console.log(textStatus);
          console.log(errorThrown);
        }
      });
    }
  });

  $(document).ready(function() {
    $("#placag").prop('disabled', true);
    // $("#placat").prop('disabled', true);
    $("#web").prop('disabled', true);
    $("#user_satelite").prop('disabled', true);
    $("#clave").prop('disabled', true);
    $("#nompro").prop('disabled', true);
    $("#docupro").prop('disabled', true);
    $("#nomtene").prop('disabled', true);
    $("#docutene").prop('disabled', true);
    $("#nomcondu").prop('disabled', true);
    $("#docucondu").prop('disabled', true);


    var i;
    for (i = 1; i <= 3; i++) {
      $("#idrl" + i).prop('disabled', false);
      $("#referencias_empresariales" + i).prop('disabled', true);
      $("#fingreso" + i).prop('disabled', true);
      $("#fretiro" + i).prop('disabled', true);
      $("#contacto_ref" + i).prop('disabled', true);
      $("#celular_ref" + i).prop('disabled', true);
      $("#cargo_ref" + i).prop('disabled', true);
      $("#anti_ref" + i).prop('disabled', true);
      //deshabilitar los input file para actualizar documentos
      $("#docuupdate" + i).prop('disabled', true);
    }

    var m;
    for (m = 1; m <= 2; m++) {
      $("#referencias_personales" + m).prop('disabled', true);
      $("#fecha_personal" + m).prop('disabled', true);
      $("#parenp" + m).prop('disabled', true);
      $("#telefonop" + m).prop('disabled', true);
      $("#docuupdatep" + m).prop('disabled', true);
    }
    $("#obserpree").prop('disabled', true);
    //$("#btn_soli").prop('disabled', true);

    $("#docuupdatepli1").prop('disabled', true);
    $("#docuupdatepru1").prop('disabled', true);
    $("#docuupdateeps1").prop('disabled', true);
    $("#docuupdatearl1").prop('disabled', true);
    $("#docuupdatecurso1").prop('disabled', true);
  });

  function currencyMask(ele) {
    alert('ssjdh');
  }
</script> -->