<?php
$_dbTable = "fletes"; // SIN EL PREFIJO cmx_
$_jsScripts = "";

$vista = '';

/********* POPUPS *********/
/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
// POPUP DE MUESTRA DE INFORMACION
$info = new Popup();
// POPUP DE ALERTA DE CONFIRMACION
$alert = new Popup();
// POPUP DE FORMULARIO DE EDICION 
$form_edita = new Popup();
// POPUP DE FORMULARIO DE CREACION 
$form_crea = new Popup();

/********* FIN POPUPS *********/


/*** CREACION DE TABLA DE CONTENIDO ***/
if (isset($this->flete)) {

	/*** SE CREA TABLA DE CONTENIDO ***/
	$table_flete = '
			<div class="row">
				<div class="col-sm-12">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover" data-page-length="200">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width:10%;">#</th>
									<th>Origen</th>
									<th>Destino</th>
									<th style="width:10%;">Tipo de vehículo</th>
									<th style="width:10%;">Flete</th>
									<th style="min-width:5%;"></th>
								</tr>
							</thead>
							<tbody>
		';

	$flete = $this->flete->getTabla();

	foreach ($flete as $key => $value) {
		/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
		switch ($value["estado"]) {
			case '0':
				// se asigna contenido de la columna de estado
				$col_stasus = '<td class="nexos-txt-danger"><span class="mdi mdi-dot-circle icon"></span></td>';

				$_popupHabilita = $alert->_alert_modal_mod_success($value['id'], "Realmente desea habilitar este elemento?", $_dbTable);
				$vista .= $_popupHabilita[0];
				$_jsScripts .= $_popupHabilita[1];

				// se asigna contenudo de la columna de acciones
				$col_action = '
						<td class="actions">
							<span id="#habilita_' . $value['id'] . '" data-toggle="modal" data-target="#habilita_' . $value['id'] . '" class="icon mdi mdi-check-circle"></span>
						</td>
					';
				break;

			case '1':
				// se asigna contenido de la columna de estado
				$col_stasus = '<td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>';

				// se asigna contenido de la columna de acciones
				$col_action = '
						<td class="actions">
							<!--
							<span id="elimina_' . $value['id'] . '"data-toggle="modal" data-target="#elimina_' . $value['id'] . '" class="icon mdi mdi-close-circle"></span>
							-->
							<a href="javascript:" class="cell-detail  hint--top-left" data-hint="Editar" onclick="editaFlete(' . $value['id'] . ')">
								<span class="icon mdi mdi-edit" data-toggle="modal" data-target="#edita_flete"></span>
							</a>
						</td>
					';

				break;
		}
		/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

		// Se maqueta contenido de la tabla 
		$table_flete .= '<tr>';
		$table_flete .= $col_stasus;
		$table_flete .= '
				<td class="cell-detail">
					<span>' . $value["municipio_origen"] . '</span>
					<span class="cell-detail-description">' . $value["depto_origen"] . ' - ' . $value["pais_origen"] . '</span>
				</td>
				<td class="cell-detail">
					<span>' . $value["municipio_destino"] . '</span>
					<span class="cell-detail-description">' . $value["depto_destino"] . ' - ' . $value["pais_destino"] . '</span>
				</td>
				<td class="cell-detail">
					<span>' . $value["nombre"] . '</span>
				</td>
				<td class="cell-detail number">
					<span>$' . number_format($value["tarifa"], 0, ",", ".") . '</span>
					<span class="cell-detail-description">Vigencia - ' . $value["vigencia"] . '</span>
				</td>
			';

		// se asigna la columna de acciones
		$table_flete .= $col_action;

		$table_flete .= '</tr>';
	}

	$table_flete .= '
							</tbody>
						</table>
					</div>
				</div>
			</div>
		';
}
/*** FIN CREACION DE TABLA DE CONTENIDO ***/


/**** CONTENIDO DEL MODULO EN PANTALLA ****/
$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Fletes Carga
				<div class="tools">
					<a href="#" data-toggle="modal" data-target="#crea_' . $_dbTable . '" class="cell-detail  hint--top"  data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a> 
				</div>
				<span class="panel-subtitle">Se establece la base de pago a los transportadores que realizan traslados de materiales según el trayecto y tipo de vehículo.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
			</div>
		</div>

		<div id="crea_fletes" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<form id="form_crea_fletes">
						<div class="modal-header">
							<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
							<h3 class="modal-title">Crear Flete</h3>
						</div>
						<div class="modal-body">
							<div class="nexos_messages_popup"></div>
							<div class="text-right">
								<span>(*) Campos Obligatorios</span>
							</div>
							<div class="row"></div>
							<div class="form-group col-xs-6">
								<label>(*) Origen:</label>
								' . $this->municipios->getHtmlSelect("id_ciudad_origen", "") . '
							</div>
							<div class="form-group col-xs-6">
								<label>(*) Destino:</label>
								' . $this->municipios->getHtmlSelect("id_ciudad_destino", "") . '
							</div>
							<div class="row"></div>
							<div class="form-group col-xs-4">
								<label>(*) Tipo Vehículo:</label>
								' . $this->tipo_vehiculo->getHtmlSelect("id_tipo_vehiculo", "", "1") . '
							</div>
							<div class="form-group col-xs-4">
								<label>(*) Flete:</label>
								<input type="text" name="valor" id="valor" placeholder="Flete" class="form-control">
							</div>
							<div class="form-group col-xs-4">
								<label>(*) Vigencia:</label>
								<input type="text" name="vigencia" id="vigencia" placeholder="Vigencia" class="form-control">
							</div>
							<div class="row"></div>
						</div>
						<div class="modal-footer">
							<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
							<button id="btn_crea_flete" type="button" data-dismiss="modal" class="btn btn-success md-close">Guardar</button>
						</div>
					</form>
				</div>
			</div>
		</div>

		<div id="edita_flete" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<form id="form_edita_flete">
						<div class="modal-header">
							<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
							<h3 class="modal-title" id="edita_flete_title"></h3>
						</div>
						<div class="modal-body">
							<div class="nexos_messages_popup"></div>
							<div class="text-right">
								<span>(*) Campos Obligatorios</span>
							</div>
							<div id="edita_flete_content"></div>
							<div class="row"></div>
						</div>
						<div class="modal-footer">
							<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
							<button id="btn_edita_flete" type="button" data-dismiss="modal" class="btn btn-success md-close">Guardar</button>
						</div>
					</form>
				</div>
			</div>
		</div>

	';

/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
$vista .= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();


			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';

/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%content%", $table_flete, $vista);

// Se asiga codigo JS generado de la tabla de contenido
$vista .= $_jsScripts;

// SE PINTA CONTENIDO EN PANTALLA
echo $vista;

?>

<script type="text/javascript">
	// FUNCIONES PARA VERIFICACIÓN DE EXISTENCIA DE FLETE CON ORIGEN, DESTINO Y TIPO DE VEHÍCULO
	$("select[name=id_ciudad_origen]").change(function() {
		$(".nexos-messages").empty();
		$(".nexos_messages_popup").html('');

		if ($("select[name=id_ciudad_origen]").val() && $("select[name=id_ciudad_destino]").val() && $("#slct_tipo_vehiculo_").val()) {
			if (verificaFlete($("select[name=id_ciudad_origen]").val(), $("select[name=id_ciudad_destino]").val(), $("#slct_tipo_vehiculo_").val())) {
				$("#valor").val("");
				$("#valor").attr("disabled", true);
				$("#vigencia").val("");
				$("#vigencia").attr("disabled", true);
				$(".nexos_messages_popup").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong><p>La tarifa que esta intentando crear ya se encuentra creada, por favor búsquela de la lista de tarifas para editarla.</p></div></div>');
			}
		}
	});

	$("select[name=id_ciudad_destino]").change(function() {
		$(".nexos-messages").empty();
		$(".nexos_messages_popup").html('');

		if ($("select[name=id_ciudad_origen]").val() && $("select[name=id_ciudad_destino]").val() && $("#slct_tipo_vehiculo_").val()) {
			if (verificaFlete($("select[name=id_ciudad_origen]").val(), $("select[name=id_ciudad_destino]").val(), $("#slct_tipo_vehiculo_").val())) {
				$("#valor").val("");
				$("#valor").attr("disabled", true);
				$("#vigencia").val("");
				$("#vigencia").attr("disabled", true);
				$(".nexos_messages_popup").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong><p>La tarifa que esta intentando crear ya se encuentra creada, por favor búsquela de la lista de tarifas para editarla.</p></div></div>');
			}
		}
	});

	$("#slct_tipo_vehiculo_").change(function() {
		$(".nexos-messages").empty();
		$(".nexos_messages_popup").html('');

		if ($("select[name=id_ciudad_origen]").val() && $("select[name=id_ciudad_destino]").val() && $("#slct_tipo_vehiculo_").val()) {
			if (verificaFlete($("select[name=id_ciudad_origen]").val(), $("select[name=id_ciudad_destino]").val(), $("#slct_tipo_vehiculo_").val())) {
				$("#valor").val("");
				$("#valor").attr("disabled", true);
				$("#vigencia").val("");
				$("#vigencia").attr("disabled", true);
				$(".nexos_messages_popup").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong><p>La tarifa que esta intentando crear ya se encuentra creada, por favor búsquela de la lista de tarifas para editarla.</p></div></div>');
			}
		}
	});
	// FIN - FUNCIONES PARA VERIFICACIÓN DE EXISTENCIA DE FLETE CON ORIGEN, DESTINO Y TIPO DE VEHÍCULO

	// FUNCIONES PARA CREACIÓN DE FLETE
	$("#btn_crea_flete").click(function() {
		$(".nexos-messages").empty();
		var msg_error = "";

		// Validaciones del módulo 
		if (!$("select[name=id_ciudad_origen]").val()) {
			msg_error += "<p>Debe seleccionar un <strong>Origen</strong> para poder crear el Flete.</p>";
		}
		if (!$("select[name=id_ciudad_destino]").val()) {
			msg_error += "<p>Debe seleccionar un <strong>Destino</strong> para poder crear el Flete.</p>";
		}
		if (!$("#slct_tipo_vehiculo_").val()) {
			msg_error += "<p>Debe seleccionar un <strong>Tipo Vehículo</strong> para poder crear el Flete.</p>";
		}
		if (!$("#valor").val()) {
			msg_error += "<p>Debe diligenciar el campo <strong>Flete</strong> para poder crear el Flete.</p>";
		}
		if (!$("#vigencia").val()) {
			msg_error += "<p>Debe diligenciar el campo <strong>Vigencia</strong> para poder crear el Flete.</p>";
		}
		// Fin - Validaciones del módulo 

		if (!msg_error) {
			var params = {
				origen: $("select[name=id_ciudad_origen]").val(),
				destino: $("select[name=id_ciudad_destino]").val(),
				tipo_vehiculo: $("#slct_tipo_vehiculo_").val(),
				tarifa: $("#valor").val(),
				vigencia: $("#vigencia").val()
			}
			// console.log(params);

			$.ajaxSetup({
				async: false
			});
			$.ajax({
				url: $("#id_url_ajax").val() + "libs/fletes_ajax.php?action=guardaFlete",
				type: 'POST',
				data: params,
				cache: false,
				dataType: 'json',
				beforeSend: function(jqXHR, settings) {
					console.log("Entro en el proceso de creación del remitente/destinatario");
					$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
				},
				error: function(jqXHR, textStatus, errorThrown) {
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
					if (jqXHR.responseText) {
						msg_error += "<p>" + jqXHR.responseText + "</p>";
					}
				},
				success: function(data, textStatus, jqXHR) {
					// console.log(data);
					if (!data.error) {
						$(".nexos-messages").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong> Se ha creado el registro con éxito.</div></div>');
						setTimeout(function() {
							location.reload(false);
						}, 600);
					} else {
						msg_error += data.error;
					}
				}
			});
			$.ajaxSetup({
				async: true
			});
		}

		if (msg_error) {
			$(".nexos-messages").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("html, body").animate({
				scrollTop: 0
			}, 600);
		}
	});
	// FIN - FUNCIONES PARA CREACIÓN DE FLETE

	// FUNCIONES PARA EDICIÓN DE FLETE
	$("#btn_edita_flete").click(function() {
		console.log("Entro en evento click del btn_edita_flete");
		var msg_error = "";

		if (!$("#e_valor").val()) {
			msg_error += "<p>Debe diligenciar el campo <strong>Flete</strong> para poder editar el Flete.</p>";
		}
		if (!$("#e_vigencia").val()) {
			msg_error += "<p>Debe diligenciar el campo <strong>Vigencia</strong> para poder editar el Flete.</p>";
		}

		if (!msg_error) {
			var params = {
				id: $("#e_id").val(),
				tarifa: $("#e_valor").val(),
				vigencia: $("#e_vigencia").val()
			}
			// console.log(params);

			$.ajaxSetup({
				async: false
			});
			$.ajax({
				url: $("#id_url_ajax").val() + "libs/fletes_ajax.php?action=editaFlete",
				type: 'POST',
				data: params,
				cache: false,
				dataType: 'json',
				beforeSend: function(jqXHR, settings) {
					$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
				},
				error: function(jqXHR, textStatus, errorThrown) {
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
					if (jqXHR.responseText) {
						msg_error += "<p>" + jqXHR.responseText + "</p>";
					}
				},
				success: function(data, textStatus, jqXHR) {
					// console.log(data);
					if (!data.error) {
						$(".nexos-messages").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong> Se ha editado el registro con éxito.</div></div>');
						setTimeout(function() {
							location.reload(false);
						}, 600);
					} else {
						msg_error += data.error;
					}
				}
			});
			$.ajaxSetup({
				async: true
			});
		}

		if (msg_error) {
			$(".nexos-messages").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("html, body").animate({
				scrollTop: 0
			}, 600);
		}

	});
	// FIN - FUNCIONES PARA EDICIÓN DE FLETE

	function editaFlete(id) {
		// console.log("Entro en editaFlete");
		$(".nexos_messages_popup").html('');

		var params = {
			id: id
		}

		$.ajax({
			url: $("#id_url_ajax").val() + "libs/fletes_ajax.php?action=buscaFlete",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend: function(jqXHR, settings) {
				// console.log("Entro en el proceso de creación del remitente/destinatario");
				$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
			},
			error: function(jqXHR, textStatus, errorThrown) {
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function(data, textStatus, jqXHR) {
				// console.log(data);
				console.log(data.control);
				$(".nexos-messages").html('');
				if (!data.error) {
					$("#edita_flete_content").html(data.content);
				} else {
					$(".nexos_messages_popup").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + data.error + '</div></div>');
				}
			}
		});
	}

	function verificaFlete(origen, destino, tipo_vehiculo) {
		// console.log("Entro en función verificaFlete");
		$("#valor").attr("disabled", false);
		$("#vigencia").attr("disabled", false);

		var flag_verifica_flete = false;

		var params = {
			origen: origen,
			destino: destino,
			tipo_vehiculo: tipo_vehiculo
		}

		$.ajaxSetup({
			async: false
		});
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/fletes_ajax.php?action=verificaFlete",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend: function(jqXHR, settings) {
				$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
			},
			error: function(jqXHR, textStatus, errorThrown) {
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function(data, textStatus, jqXHR) {
				$(".nexos-messages").html('');
				// console.log(data);
				if (data.flag_flete) {
					flag_verifica_flete = true;
				}
			}
		});
		$.ajaxSetup({
			async: true
		});
		return flag_verifica_flete;
	}
</script>