<div class="panel panel-border panel-contrast">
	<div class="panel-heading panel-heading-contrast">
		Transmisión de Documentos a Avansat Operativo
		<div class="tools">	</div>
		<span class="panel-subtitle">Módulo dedicado a retransmisión de información a la plataforma Avansat (Grupo OET).</span>
		<div class=" col-xs-12 col-sm-4 col-md-12">
			<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'" >
			<input type="hidden" id="elperfil" class="form-control input-sm" readonly="readonly" value="0">
		</div>
	</div>
	<div class="panel-body">
		<div class="nexos-messages"></div>
		<div class="nexos-content">	
			<div class="row">

				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfiltro">
					<label>Documento</label>
					<select id="filtro" class="form-control input-sm">
						<option value="">Seleccionar</option>
						<option disabled>--- Parámetros ---</option>
							<option value="5">Cliente</option>
							<option value="6">Conductor - Propietario - Poseedor - Pro trailer</option>
							<option value="7">Trailer</option>
							<option value="8">Vehículos</option>
						<option disabled>--- Documentos Oficiales ---</option>
						<option value="1">Orden de cargue</option>
						<option value="2">Remesa Terrestre de Carga</option>
						<option value="3">Manifiesto de Carga</option>	
						<option value="4">Cumplido manifiesto de carga</option>		
					</select>
				</div>

				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfiltrob">
					<label>Opción filtro</label>
					<select id="filtrob" class="form-control input-sm">
						<option value="">Seleccione</option>
						<option value="f" id="opcion1">Fecha</option>
						<option value="n" id="opcion2">Número</option>
					</select>
				</div>

				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divnum">
					<label>Número Documento</label>
					<input type="text" id="numero_documento" class="form-control input-sm">
				</div>

				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfec">
					<label>Fecha</label>
					<input type="date" id="fecha_documento" class="form-control input-sm"  value="<?php echo date('Y-m-d')  ?>" >
				</div>


				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divbtnbusqueda">
					<br><button id="buscar_datos" class="btn btn-primary btn-sm">Buscar</button>
				</div>

			</div><br>
			<div class="row" id="tabla_datos">
				<hr>
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div  class='table-responsive noSwipe'>
					<table id='table1' class='table table-striped table-hover' data-page-length='100'>
						<thead id="cabecera_general">
						</thead>
						<tbody id="tabla_general">
						</tbody>
					</table>
					</div>
				</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12"></div>
		</div>
	</div>
</div>

     <script src=<?php echo BASE_URL;?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
      <script src=<?php echo BASE_URL;?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
      <script src=<?php echo BASE_URL;?>views/layout/assets/js/main.js type="text/javascript"></script>
      <script src=<?php echo BASE_URL;?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
   	 <script src=<?php echo BASE_URL;?>/views/integrar_oet/js/integracion_documentoet.js type="text/javascript"></script>
      <script src=<?php echo BASE_URL;?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
      <script src=<?php echo BASE_URL;?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
      <script src=<?php echo BASE_URL;?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>


<script type="text/javascript">
$(document).ready(function(){
//initialize the javascript
  App.init();
  App.wizard();
});
</script>