<?php
	$_dbTable = "actividades_plantilla"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";
	$_jsAjax = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

	$r = new Request();
	// print_r($r->getArgs());

	$vista = '';
	$_content = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();
	/********* FIN POPUPS *********/

	$arrayPuntoControl = $this->rutas->getBuscaPuntoControl( $r->getArgs()[0] );

	/*** CREACION DE TABLA DE CONTENIDO  ***/
	if(isset($this->rutas) /* && count($this->rutas) */){
		/*** SE CREA TABLA DE CONTENIDO ***/

		if ($arrayPuntoControl) {
			$id = $arrayPuntoControl["id"];
			$nombre = $arrayPuntoControl["nombre"];
			$contacto = $arrayPuntoControl["contacto"];
			$ubicacion = $arrayPuntoControl["ubicacion"];
			$telefono = $arrayPuntoControl["telefono"];
			$latitud = $arrayPuntoControl["latitud"];
			$longitud = $arrayPuntoControl["longitud"];
			$tipo_punto = $arrayPuntoControl["tipo_punto"];

			$_content.= '
				<div class="col-md-6">
					<span><strong>Información</strong></span>
					<table class="table">
						<tbody>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-md-6">
											<span>' . $nombre . '</span>
											<span class="cell-detail-description">' . $tipo_punto . '</span>
										</div>
										<div class="col-md-6">
											<span>' . $contacto . '</span>
											<span class="cell-detail-description">' . $telefono . '</span>
										</div>
									</div>
									<br>
									<div class="row">
										<div class="col-md-12">
											<span>Ubicación:</span>
											<span class="cell-detail-description">' . $ubicacion . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr><td></td></tr>
						</tbody>
					</table>
				</div>
				<div class="col-md-6">
					<div class="bs-grid-block">
						<div class="content">
							<div id="mapa" style="background-color: gray; width: 100%; height: 100%;"></div>
						</div>
					</div>
				</div>
			';

		}else{
			$_content.= '<h2>No hay información diponible...</h2>';
		}
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/

	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$return_page = "rutas/puntos_control";
	if ( isset($r->getArgs()[1]) ) {
		$return_page = "rutas/mapas_ruta_control/" . $r->getArgs()[1] ;
	}
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Información detallada Punto de Control - <strong>' . $nombre . '</strong>
				<div class="tools">
					<a href="' . BASE_URL . $return_page . '/" class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>
				</div>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
			</div>
		</div>
	';
	/**** FIN CONTENIDO DEL MODULO EN PANTALLA ****/

	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>



	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
		%js-ajax%
		<script async defer
			src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6vpUhRVoEe5U6m7Wh5_LFMCr_g8OzU1E&callback=initMap">
		</script>
		<script>
			var markers = [];
			var status_ruta = false;

			function initMap() {
				var latitud = parseFloat(' . $latitud . ') ;
				var longitud = parseFloat(' . $longitud . ');

				var code = {
					lat: latitud, 
					lng: longitud
				};

				var point = new google.maps.LatLng(
					latitud,
					longitud
				);

				var mapa = new google.maps.Map(document.getElementById("mapa"), {
					zoom: 8,
					center: code,
					streetViewControl: false,
					mapTypeControl: false,
				});

				var marker = new google.maps.Marker({
					map: mapa,
					position: point
				});
			}
		</script>
	';
	/**** FIN CARGA DE ARCHIVOS JS DE LA VISTA ****/

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%js-ajax%" , $_jsAjax , $vista);
	$vista = str_replace("%content%" , $_content , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;
?>
