<?php
	$_dbTable = "mapas_ruta"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->rutas) && count($this->rutas)){

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_content = '
			<div class="row">
				<div class="col-sm-1"></div>
				<div class="col-sm-10">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover" data-page-length="100">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width:5%;"></th>
									<th style="width:10%;">Cantidad Controles</th>
									<th>Nombre Ruta</th>
									<th>Origen</th>
									<th>Destino</th>
									<th style="width:10%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayRutas = $this->rutas->getRutas();
		// print_r("<pre>");
		// print_r($arrayRutas);
		// print_r("</pre>");

		if ($arrayRutas['rowsData']) {
			foreach ($arrayRutas['rowsData'] as $key => $value) {
				/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
				switch ($value["estado"]) {
					case '0':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-danger">
								<span style="display: none;">' . $value["estado"] . '</span>
								<span class="mdi mdi-dot-circle icon"></span>
							</td>
						';

						$_popupHabilita = $alert->_alert_modal_mod_success( $value[0] , "Realmente desea habilitar este elemento?" , $_dbTable );
						$vista.= $_popupHabilita[0];
						$_jsScripts.=$_popupHabilita[1];

						// se asigna contenido de la columna de acciones
						$col_action = '
							<td class="actions">
								<a href="#" class="icon hint--top-left" data-hint="Habilitar"><span id="#habilita_' . $value[0] . '" data-toggle="modal" data-target="#habilita_' . $value[0] . '" class="icon mdi mdi-check-circle"></span></a>
							</td>
						';
						break;
					
					case '1':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-success">
								<span style="display: none;">' . $value["estado"] . '</span>
								<span class="mdi mdi-dot-circle icon"></span>
							</td>
						';

						// se genera el formulario de edicion del registro
						$form_edit_table = '
							<input type="hidden" name="id" value="' . $value[0] . '" class="form-control">
							<div class="form-group col-xs-8">
								<label>Nombre:</label>
								<input type="text" name="nombre" value="' . $value["nombre"] . '" placeholder="Nombre de la Planilla" class="form-control">
							</div>
							<div class="form-group col-xs-4">
								<label>Tipo Proyecto:</label>
							</div>
							<div class="form-group col-xs-12">
								<label>Descripción:</label>
								<textarea name="descripcion" placeholder="Descripción" class="form-control">' . $value["descripcion"] . '</textarea>
							</div>
							<div class="row"></div>
						';

						$_popupEdita = $form_edita->_form_modal_update($value[0], "Editar Plantilla - " . $value[1] , $form_edit_table, $_dbTable);
						$vista.= $_popupEdita[0];
						$_jsScripts.=$_popupEdita[1];


						$_popupElimina = $alert->_alert_modal_mod_danger($value[0], "Realmente desea eliminar este elemento?",$_dbTable);
						$vista.= $_popupElimina[0];
						$_jsScripts.=$_popupElimina[1];

						// se asigna contenido de la columna de acciones
						$col_action = '
							<td class="actions">
								<a href="' . BASE_URL . 'rutas/mapas_ruta_control/' . $value[0] . '" class="icon hint--top-left" data-hint="Ver Puntos de Control">
									<span class="mdi mdi-eye"></span>
								</a>
								<a href="#" id="edita_' . $value[0] . '" data-toggle="modal" data-target="#edita_' . $value[0] . '" class="cell-detail md-trigger hint--top-left" data-hint="Editar Ruta">
									<span class="icon mdi mdi-edit"></span>
								</a>
								<a href="#" id="elimina_' . $value[0] . '"data-toggle="modal" data-target="#elimina_' . $value[0] . '" class="cell-detail md-trigger hint--top-left" data-hint="Inactivar Ruta">
									<span class="icon mdi mdi-close-circle"></span>
								</a>
							</td>
						';

						break;

					case '2':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-warning">
								<span style="display: none;">' . $value["estado"] . '</span>
								<span class="mdi mdi-dot-circle icon"></span>
							</td>

						';

						// se genera el formulario de edicion del registro
						$form_edit_table = '
							<input type="hidden" name="id" value="' . $value[0] . '" class="form-control">
							<div class="form-group col-xs-8">
								<label>Nombre:</label>
								<input type="text" name="nombre" value="' . $value["nombre"] . '" placeholder="Nombre de la Planilla" class="form-control">
							</div>
							<div class="form-group col-xs-4">
								<label>Tipo Proyecto:</label>
							</div>
							<div class="form-group col-xs-12">
								<label>Descripción:</label>
								<textarea name="descripcion" placeholder="Descripción" class="form-control">' . $value["descripcion"] . '</textarea>
							</div>
							<div class="row"></div>
						';

						$_popupEdita = $form_edita->_form_modal_update($value[0], "Editar Ruta - " . $value[1] , $form_edit_table, $_dbTable);
						$vista.= $_popupEdita[0];
						$_jsScripts.=$_popupEdita[1];


						$_popupElimina = $alert->_alert_modal_mod_danger($value[0], "Realmente desea eliminar este elemento?",$_dbTable);
						$vista.= $_popupElimina[0];
						$_jsScripts.=$_popupElimina[1];


						$_popupHabilita = $alert->_alert_modal_mod_success( $value[0] , "Realmente desea habilitar este elemento?" , $_dbTable );
						$vista.= $_popupHabilita[0];
						$_jsScripts.=$_popupHabilita[1];

						// se asigna contenido de la columna de acciones
						$_btn_habilita = '';
						if ($value['CUANTOS'] > 0) {
							$_btn_habilita = '
								<a href="#" id="#habilita_' . $value[0] . '" data-toggle="modal" data-target="#habilita_' . $value[0] . '" class="icon hint--top-left" data-hint="Habilitar Ruta"><span class="icon mdi mdi-check-circle"></span></a>
							';
						}
						$col_action = '
							<td class="actions">
								<a href="' . BASE_URL . 'rutas/mapas_ruta_control/' . $value[0] . '" class="icon hint--top-left" data-hint="Ver Puntos de Control"><span class="mdi mdi-eye"></span></a>
								<a href="#" id="#edita_' . $value[0] . '"  data-toggle="modal" data-target="#edita_' . $value[0] . '" class="icon hint--top-left" data-hint="Editar Ruta"><span class="mdi mdi-edit"></span></a>
								' . $_btn_habilita . '
								<a href="#" id="elimina_' . $value[0] . '"data-toggle="modal" data-target="#elimina_' . $value[0] . '" class="icon hint--top-left" data-hint="Inactivar Ruta"><span class="icon mdi mdi-close-circle"></span></a>
							</td>
						';

						break;
				}
				/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

				// Se maqueta contenido de la tabla 
				$table_content.= '<tr>';
				// Columna de estado
				$table_content.= $col_stasus;
				// Columna de cantidad de actividades
				$table_content.= '
					<td class="cell-detail">
						<span class="label label-default">' . $value['CUANTOS'] . '</span>
					</td>
				';
				// Columna de plantilla
				$table_content.= '
					<td class="cell-detail">
						<span>' . $value["nombre"] . '</span>
						<span class="cell-detail-description">' . $value["descripcion"] . '</span>
					</td>
				';
				// Columna de origen
				$table_content.= '
					<td class="cell-detail">
						<span>' . $value["ORIGEN"] . '</span>
					</td>
				';
				// Columna de destino
				$table_content.= '
					<td class="cell-detail">
						<span>' . $value["DESTINO"] . '</span>
					</td>
				';

				// se asigna la columna de acciones
				$table_content.=$col_action;
				
				$table_content.= '</tr>';
			}

			$table_content.= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
		}
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Mapas de Ruta 
				<div class="tools">
					<a href="#" data-toggle="modal" data-target="#crea_' . $_dbTable . '" class="cell-detail md-trigger hint--top" data-hint="Agregar"><span class="icon mdi mdi-plus"></span>
					</a> 
				</div>
				<span class="panel-subtitle">Administración de las rutas que deban ser usadas por los conductores en el transporte de materiales entre un origen y un destino.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';


	/****** CREACION CONTENIDO DE POPUPS ******/
	// CONTENIDO DEL POPUP DE FORMULARIO DE CREACION
	$_slct_origen = $this->rutas->getHtmlSelectMunicipios( "origen" , "" );
	$_slct_destino = $this->rutas->getHtmlSelectMunicipios( "destino" , "" );
	$forms = '
		<div class="form-group col-xs-8">
			<label>Nombre:</label>
			<input type="text" name="nombre" placeholder="Nombre de la Ruta" class="form-control">
		</div>
		<div class="form-group col-xs-6">
			<label>Origen:</label>
			' . $_slct_origen . '
		</div>
		<div class="form-group col-xs-6">
			<label>Destino:</label>
			' . $_slct_destino . '
		</div>
		<div class="form-group col-xs-12">
			<label>Descripción:</label>
			<textarea name="descripcion" placeholder="Descripción" class="form-control"></textarea>
		</div>
		<div class="row"></div>
	';

	$_popupCrea = $form_crea->_form_modal_simple_insert("crea_" . $_dbTable ,"Crear Ruta" , $forms , $_dbTable );
	$vista.= $_popupCrea[0];
	$_jsScripts.=$_popupCrea[1];


	/****** FIN CREACION CONTENIDO DE POPUPS ******/

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_content , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
