<?php
$_dbTable = "puntos_control"; // SIN EL PREFIJO cmx_
$_jsScripts = "";

// se definen las variables de session
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

$vista = '';

/********* POPUPS *********/
/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
// POPUP DE MUESTRA DE INFORMACION
$info = new Popup();
// POPUP DE ALERTA DE CONFIRMACION
$alert = new Popup();
// POPUP DE FORMULARIO DE EDICION 
$form_edita = new Popup();
// POPUP DE FORMULARIO DE CREACION 
$form_crea = new Popup();

/********* FIN POPUPS *********/


/*** CREACION DE TABLA DE CONTENIDO ***/
// if(isset($this->rutas) && count($this->rutas)){
if (isset($this->rutas)) {

	/*** SE CREA TABLA DE CONTENIDO ***/
	$table_content = '
			<div class="row">
				<div class="col-sm-12">
					<div class="table-responsive noSwipe">
						<input type="hidden" name="archivo" id="archivo" value="rutas/puntos_control" class="form-control" >
						<table id="table1" data-page-length="100" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th style="min-width:5%;">#</th>
									<th style="width:20%;">Punto de control</th>
									<th>Ubicación</th>
									<th style="width:15%;">Contacto</th>
									<th style="width:7%;"></th>
								</tr>
							</thead>
							<tbody>
		';

	$puntos_control = $this->rutas->getPuntosControl();
	// print_r($puntos_control);

	if ($puntos_control) {
		foreach ($puntos_control as $key => $value) {
			$col_status = '
					<td class="actions">
						<center>
							<span class="mdi mdi-pin icon"></span>
						</center>
					</td>
				';
			$_contacto = '<span>No aplica</span>';
			if ($value["tipo_punto"] == "PUESTO_CONTROL") {
				$col_status = '
						<td class="actions">
							<center>
								<span class="mdi mdi-account-box-phone icon"></span>
							</center>
						</td>

					';
				$_contacto = '
						<span>' . $value["contacto"] . '</span>
						<span class="cell-detail-description">' . $value["telefono"] . '</span>
					';
			}

			// Se maqueta contenido de la tabla 
			$table_content .= '<tr>';
			$table_content .= $col_status;
			$table_content .= '
					<td class="cell-detail md-trigger">
						<span>' . $value["nombre"] . '</span>
						<span class="cell-detail-description">' . $value["tipo_punto"] . '</span>
					</td>
				';
			$table_content .= '
					<td class="cell-detail md-trigger">
						<span>' . $value["ubicacion"] . '</span>
					</td>
				';
			$table_content .= '
					<td class="cell-detail md-trigger">
						' . $_contacto . '
					</td>
				';

			// se asigna la columna de acciones
			$table_content .= '
					<td class="actions">
						<a href="' . BASE_URL . 'rutas/detalle_punto_control/' . $value['id'] . '" class="icon hint--top-left" data-hint="Ver Detalle"><span class="mdi mdi-eye"></span></a>
					<a href="javascript:" class="cell-detail hint--top-left" data-hint="Editar" onclick="editaPunto(' . $value['id'] . ',\'' . $value["nombre"] . '\',\'' . $value["ubicacion"] . '\',\'' . $value["contacto"] . '\',\'' . $value["telefono"] . '\',\'' . $value["tipo_punto"] . '\')"><span class="icon mdi mdi-edit" data-toggle="modal" data-target="#edita_punto"></span></a>
					</td>
				';

			$table_content .= '</tr>';
		}

		$table_content .= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
	}
}
/*** FIN CREACION DE TABLA DE CONTENIDO ***/


/**** CONTENIDO DEL MODULO EN PANTALLA ****/
$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Puntos de Control
				<div class="tools">
					<a href="#" data-toggle="modal" data-target="#crea_' . $_dbTable . '" class="cell-detail  hint--top"  data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a> 
				</div>
				<span class="panel-subtitle">
					Establece los puntos de control dentro de una ruta para cuando se realice un seguimiento de ruta se pueda establecer si se encuentra a tiempo o si se encuentra dentro de la ruta propuesta. Se debe tener en cuenta lo siguiente:<br>
					<strong>Puntos de ubicación</strong>: Son puntos geográficos de referencia que sirven para establecer una ruta.<br>
					<strong>Puestos de control</strong>: Son puntos geográficos de referencia donde los conductores deben registrar su transito por ese sitio.
				</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>

	';

/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
$vista .= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});


			$(document).ready(function(){
				$("#slct_tipo_punto_").change(function () {
					var contenido = "";
					if( $("#slct_tipo_punto_").val() == "PUESTO_CONTROL" ){
						contenido = \' \n\
							<div class="form-group col-xs-8">\n\
								<label>(*) Contacto:</label>\n\
								<input type="text" name="contacto" value="" placeholder="Contacto" class="form-control">\n\
							</div>\n\
							<div class="form-group col-xs-4">\n\
								<label>(*) Teléfono:</label>\n\
								<input type="text" name="telefono" value="" placeholder="Teléfono" class="form-control">\n\
							</div>\n\
						\';
					}
					$("#div_contacto").html(contenido);
				});

				// Funciones para edición del punto de control
				$("#slct_tipo_punto_e").change(function () {
					var contenido = "";
					if( $("#slct_tipo_punto_e").val() == "PUESTO_CONTROL" ){
						contenido = \' \n\
							<div class="form-group col-xs-8">\n\
								<label>(*) Contacto:</label>\n\
								<input type="text" name="contacto" id="e_contacto" value="" placeholder="Contacto" class="form-control">\n\
							</div>\n\
							<div class="form-group col-xs-4">\n\
								<label>(*) Teléfono:</label>\n\
								<input type="text" name="telefono" id="e_telefono" value="" placeholder="Teléfono" class="form-control">\n\
							</div>\n\
						\';
					}
					$("#e_div_contacto").html(contenido);
					$("#e_contacto").val( $("#tmp_e_contacto").val() );
					$("#e_telefono").val( $("#tmp_e_telefono").val() );
				});
				// Fin - Funciones para edición del punto de control
			});

			// Funciones para edición del punto de control
			function editaPunto(id_punto, nombre, ubicacion, contacto, telefono, tipo_punto){
				$("#e_div_contacto").html("");
				$("#tmp_e_contacto").val("");
				$("#tmp_e_telefono").val("");
				$("#slct_tipo_punto_e option[value=\'PUNTO_UBICACION\']").attr("selected", false);
				$("#slct_tipo_punto_e option[value=\'PUESTO_CONTROL\']").attr("selected", false);

				$("#e_id").val(id_punto);
				$("#e_nombre").val(nombre);
				$("#slct_tipo_punto_e option[value=" + tipo_punto + "]").attr("selected", "selected");
				$("#e_ubicacion").val(ubicacion);

				var info_contacto = "";
				if( tipo_punto == "PUESTO_CONTROL"){
					$("#e_div_contacto").append(\'\n\
						<div class="form-group col-xs-8">\n\
							<label>(*) Contacto:</label>\n\
							<input type="text" name="contacto" id="e_contacto" value="" placeholder="Contacto" class="form-control">\n\
						</div>\n\
						<div class="form-group col-xs-4">\n\
							<label>(*) Teléfono:</label>\n\
							<input type="text" name="telefono" id="e_telefono" value="" placeholder="Teléfono" class="form-control">\n\
						</div>\n\
					\');
					$("#e_contacto").val(contacto);
					$("#e_telefono").val(telefono);
					$("#tmp_e_contacto").val(contacto);
					$("#tmp_e_telefono").val(telefono);
				}
			}
			// Fin - Funciones para edición del punto de control
		</script>
		<script async defer
			src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6vpUhRVoEe5U6m7Wh5_LFMCr_g8OzU1E&callback=initMap">
		</script>
	';


/****** CREACION CONTENIDO DE POPUPS ******/
// CONTENIDO DEL POPUP DE FORMULARIO DE CREACION
$forms = '
		<div class="form-group col-xs-8">
			<label>(*) Nombre:</label>
			<input type="text" name="nombre" value="" placeholder="Nombre" class="form-control">
		</div>
		<div class="form-group col-xs-4">
			<label>(*) Tipo de punto:</label>
			%slct_tipo_punto%
		</div>
		<div class="form-group col-xs-12" id="div_contacto"></div>
		<div class="form-group col-xs-12">
			<label>(*) Ubicación:</label>
			<textarea name="ubicacion" value="" placeholder="Ubicación" class="form-control"></textarea>
		</div>
		<div class="form-group col-xs-4">
			<div class="form-group col-xs-12">
				<label>(*) Latitud:</label>
				<input type="number" name="latitud" id="latitud" value="" placeholder="Latitud" class="form-control">
			</div>
			<div class="form-group col-xs-12">
				<label>(*) Longitud:</label>
				<input type="number" name="longitud" id="longitud" value="" placeholder="Longitud" class="form-control">
			</div>
		</div>
		<div class="form-group col-xs-8">
			<span>Ubicación:</span>
			<div  id="mapa_ubicacion" class="img-responsive" style="height: 300px;"></div>
		</div>
		<div class="row"></div>
	';
$forms = str_replace("%slct_tipo_punto%", $this->rutas->getEnumSlctTipoPunto("tipo_punto", "", ""), $forms);

// Posicion inicial por defecto en BOGOTA
$latitud_inicial = "4.7097100";
$longitud_inicial = "-74.0677500";

$_jsScripts .= '
		<script>
			var markers = [];
			var status_ruta = false;

			function initMap() {
				var latitud = parseFloat(' . $latitud_inicial . ') ;
				var longitud = parseFloat(' . $longitud_inicial . ');

				var code = {
					lat: latitud, 
					lng: longitud
				};
				var directionsService = new google.maps.DirectionsService;
				var directionsDisplay = new google.maps.DirectionsRenderer;

				var point = new google.maps.LatLng(
					latitud,
					longitud
				);

				var mapa_ubicacion = new google.maps.Map(document.getElementById("mapa_ubicacion"), {
					zoom: 5,
					center: code,
					streetViewControl: false,
					mapTypeControl: false,
				});

				mapa_ubicacion.addListener(\'click\', function (event) {
					$("#latitud").val("");
					$("#longitud").val("");

					deleteMarkers();
					addMarkerruta(event.latLng, mapa_ubicacion);

					var latitud = markers[0][\'position\'].lat();
					var longitud = markers[0][\'position\'].lng();

					$("#latitud").val(latitud);
					$("#longitud").val(longitud);
				});
			}

			// Deletes all markers in the array by removing references to them.
			function deleteMarkers() {
				clearMarkers();
				markers = [];
			}

			// Removes the markers from the map, but keeps them in the array.
			function clearMarkers() {
				setMapOnAll(null);
			}

			// Sets the map on all markers in the array.
			function setMapOnAll(map) {
				for (var i = 0; i < markers.length; i++) {
					markers[i].setMap(map);
				}
			}

			// Adds a marker to the map and push to the array.
			function addMarkerruta(location, mapa) {
				if (status_ruta == false) {
					var marker = new google.maps.Marker({
						position: location,
						map: mapa
					});
					marker.setTitle("Control");
					markers.push(marker);
				}
			}
		</script>
	';

$_popupCrea = $form_crea->_form_modal_simple_insert("crea_" . $_dbTable, "Crear - Punto de Control", $forms, $_dbTable);
$vista .= $_popupCrea[0];
$_jsScripts .= $_popupCrea[1];


// CONTENIDO DEL POPUP DE FORMULARIO DE EDICION
$forms = '
		<input type="hidden" name="id" id="e_id">
		<input type="hidden" id="tmp_e_contacto">
		<input type="hidden" id="tmp_e_telefono">
		<div class="form-group col-xs-8">
			<label>(*) Nombre:</label>
			<input type="text" name="nombre" id="e_nombre" value="" placeholder="Nombre" class="form-control">
		</div>
		<div class="form-group col-xs-4">
			<label>(*) Tipo de punto:</label>
			' . $this->rutas->getEnumSlctTipoPunto("tipo_punto", "e", "") . '
		</div>
		<div class="form-group col-xs-12" id="e_div_contacto"></div>
		<div class="form-group col-xs-12">
			<label>(*) Ubicación:</label>
			<textarea name="ubicacion" id="e_ubicacion" value="" placeholder="Ubicación" class="form-control"></textarea>
		</div>
		<div class="row"></div>
	';
$_popupEdita = $form_edita->_form_modal_update("punto", "Editar Punto de Control", $forms, $_dbTable);
$vista .= $_popupEdita[0];
$_jsScripts .= $_popupEdita[1];

/****** FIN CREACION CONTENIDO DE POPUPS ******/

/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
$vista = str_replace("%content%", $table_content, $vista);
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);

// Se asiga codigo JS generado de la tabla de contenido
$vista .= $_jsScripts;

// SE PINTA CONTENIDO EN PANTALLA
echo $vista;
