 <div class="d-flex flex-column h-100" style="overflow-y: auto;overflow-x:hidden;">
     <div class="card-header p-3 p-md-4 d-flex justify-content-between align-items-center" style="padding:5px !important;">
         <h6 class="mb-0">
             <i class="fas fa-list-ul me-2"></i>Detalles del Prefiltro
         </h6>

         <div class="d-flex align-items-center">
             <!-- Responsable Vehículo -->
             <span class="me-3 d-flex align-items-center">
                 <b>Responsable Vehículo:&nbsp;</b> <i class="fa-solid fa-circle text-success fs-11 me-1"></i>
                 <span id="responsable_vehiculo_prefiltro" class="fs-8 fw-semibold"> Nombre Responsable</span>
             </span>

             <!-- Botón de opciones -->
             <div class="dropdown">
                 <button class="btn btn-icon btn-phoenix-primary" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                     <span class="fa-solid fa-ellipsis-vertical"></span>
                 </button>
                 <ul class="dropdown-menu dropdown-menu-end p-0">
                     <li>
                         <a class="dropdown-item fw-bold" href="#!"
                             id="btn_secury"
                             data-proceso_prefiltro_itr="${ProcesoPrefiltroItr}"
                             data-prefiltroid=""
                             data-placa="${Placa}"
                             data-propietario="${DocumentoPropietario}"
                             data-tenedor="${DocumentoTenedor}"
                             data-conductor="${DocumentoConductor}"
                             data-placa_trailer_nuevo="${PlacaTrailerNuevo}"
                             data-documento_propietario_trailer="${DocumentoPropietarioTrailer}"
                             data-observacion_prefiltro="${Observacion}"
                             data-responsable_vehiculo="${UsuarioResponsableVehiculo}">
                             Anular Prefiltro
                         </a>
                     </li>
                 </ul>
             </div>
         </div>
     </div>

     <div class="card-body p-3 p-sm-4 scrollbar chat-content-body-0" style='padding:5px 5px 5px 5px !important; overflow-y: auto;overflow-x:hidden;'>

         <table class='table table-bordered table-sm' style=" font-size:12px;">
             <tbody>
                 <tr>
                     <th colspan="4" class="text-center" style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Cliente</th>
                 </tr>
                 <tr>
                     <td colspan="4" id="vcliente" class="text-center" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                 </tr>
                 <tr>
                     <th scope="row" style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Solicitud</th>
                     <td id="vid" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                     <th scope="row" style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Fecha</th>
                     <td id="vfecha" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                 </tr>
                 <tr>
                     <th scope="row" style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Placa</th>
                     <td id="vplaca" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                     <th scope="row" style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Hora</th>
                     <td id="vhora" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                 </tr>
                 <tr>
                     <th scope="row" style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Consecutivo</th>
                     <td id="vconse" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                     <th scope="row" style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Usuario</th>
                     <td id="vuser" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                 </tr>
             </tbody>
         </table>

         <table class='table table-bordered table-sm text-center' style=" font-size:12px;">
             <tbody>
                 <tr>
                     <td class="text-center" colspan='3'>
                         <b>Datos del Vehículo</b>
                     </td>
                 </tr>
                 <tr class="text-center active">
                     <th style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Nombre Propietario</th>
                     <th style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Documento</th>
                     <th style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Estado</th>
                 </tr>
                 <tr>
                     <td id="vpropi" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                     <td id="vpdocumento" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                     <td id="estado_tercero_propietario" class="text-left" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                 </tr>
                 <tr>
                 </tr>
                 <tr class="text-center active">
                     <th style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Nombre Poseedor</th>
                     <th style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Documento</th>
                     <th style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Estado</th>
                 </tr>
                 <tr>
                     <td id="vtene" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                     <td id="vtdocumento" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                     <td id="estado_tercero_poseedor" class="text-left" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                 </tr>
                 <tr>
                 </tr>
                 <tr class="text-center active">
                     <th style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Nombre Conductor</th>
                     <th style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Documento</th>
                     <th style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Estado</th>
                 </tr>
                 <tr>
                     <td id="vcondu" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                     <td id="vcdocumento" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                     <td id="estado_tercero_conductor" class="text-left" style="padding: 1px; width: auto; white-space: nowrap;"> </td>
                 </tr>
                 <tr>
                 <tr class="text-center active">
                     <th style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Nombre Propietario Trailer</th>
                     <th style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Documento Propietarioi Trailer</th>
                     <th style="width: 150px; font-weight: bold; padding: 1px; width: auto; white-space: nowrap;">Estado</th>
                 </tr>
                 <td id="ptcondu" class="text-left" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                 <td id="ptcdocumento" class="text-left" style="padding: 1px; width: auto; white-space: nowrap;"> </td>
                 <td id="estado_tercero_pro_trailer" class="text-left" style="padding: 1px; width: auto; white-space: nowrap;"> </td>
                 </tr>
             </tbody>
         </table>

         <table class='table table-bordered table-sm' style=" font-size:12px;">
             <tbody>
                 <tr class="text-center active">
                     <th class="text-center" style="width: 150px; font-weight: bold;padding: 1px; width: auto; white-space: nowrap;">Web</th>
                     <th class="text-center" style="width: 150px; font-weight: bold;padding: 1px; width: auto; white-space: nowrap;">Usuario</th>
                     <th class="text-center" style="width: 150px; font-weight: bold;padding: 1px; width: auto; white-space: nowrap;">Clave</th>
                 </tr>
                 <tr>
                     <td id="vweb" class="text-center" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                     <td id="vwuser" class="text-center" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                     <td id="vwclave" class="text-center" style="padding: 1px; width: auto; white-space: nowrap;"></td>
                 </tr>
             </tbody>
         </table>

         <!-- REFERENCIAS-->
         <table class='table table-bordered table-striped table-sm text-center' style=" font-size:12px;">
             <thead>
                 <tr>
                     <td colspan='6'>
                         <b>Referencias</b>
                     </td>
                 </tr>
                 <tr>
                     <th style="width: auto; white-space: nowrap; ">Empresa</th>
                     <th style="width: auto; white-space: nowrap; ">Ingreso</th>
                     <th style="width: auto; white-space: nowrap; ">Retiro</th>
                     <th style="width: auto; white-space: nowrap; ">Contacto</th>
                     <th style="width: auto; white-space: nowrap; ">Celular</th>
                     <th style="width: auto; white-space: nowrap; ">Cargo</th>
                 </tr>
             </thead>
             <tbody id="consulta_referencia"></tbody>
         </table>

         <!--SOLICITUDES SERVICIO-->
         <table class='table table-bordered table-striped table-sm text-center' style="font-size:12px;">
             <thead>
                 <tr>
                     <td colspan='7'>
                         <b>Solicitudes de servicio al cliente</b>
                     </td>
                 </tr>
                 <tr>
                     <th style="width: auto; white-space: nowrap; ">SS</th>
                     <th style="width: auto; white-space: nowrap; ">Cliente</th>
                     <th style="width: auto; white-space: nowrap; ">Ruta</th>
                     <th style="width: auto; white-space: nowrap; ">Peso / Tipo Vehículo</th>
                     <th style="width: auto; white-space: nowrap; ">Usuario</th>
                     <th style="width: auto; white-space: nowrap; ">Fecha-Hora</th>
                 </tr>
             </thead>
             <tbody id="consulta_tbservicio"></tbody>
         </table>

         <!-- RESPUESTAS DE SEGURIDAD PARA CREAR LAS HOJAS DE VIDA DE LOS RECURSOS -->

         <div id="nexos_messages_popup"></div>

         <table class='table table-bordered table-striped table-sm text-center' style="font-size:12px;">
             <tbody>
                 <tr class="active">
                     <th style="width: auto; white-space: nowrap;">Placa</th>
                     <th style="width: auto; white-space: nowrap;">Token de aprobación Hoja de vida</th>
                     <th style="width: auto; white-space: nowrap;">Expriración</th>
                 </tr>
                 <tr>
                     <td id="rplaca">-</td>
                     <td id="token">Sin respuesta de seguridad</td>
                     <td id="fechaexpiracion">Sin respuesta de seguridad</td>
                 </tr>
             </tbody>
         </table>

         <table class="table table-bordered table-striped table-sm text-center" style="font-size:12px;">
             <thead>
                 <tr>
                     <th style="width: auto; white-space: nowrap;">Estado</th>
                     <th style="width: auto; white-space: nowrap;">Observación</th>
                     <th style="width: auto; white-space: nowrap;">Usuario</th>
                     <th style="width: auto; white-space: nowrap;">Fecha / Hora</th>
                 </tr>
             </thead>
             <tbody id="respuestas_seguridad"></tbody>
         </table>

         <!--DOCUMENTOS-->
         <table class='table table-bordered table-striped table-sm text-center' style=" font-size:12px;">
             <thead>
                 <tr>
                     <td colspan='5'>
                         <b>Documentos</b>
                     </td>
                 </tr>
                 <tr>
                     <th style="width: auto; white-space: nowrap; ">Tipo hoja</th>
                     <th style="width: auto; white-space: nowrap; ">Clase</th>
                     <th style="width: auto; white-space: nowrap; ">Documento/Img</th>
                     <th style="width: auto; white-space: nowrap; ">Usuario</th>
                     <th style="width: auto; white-space: nowrap; ">Fecha - Hora</th>
                 </tr>
             </thead>
             <tbody id="consulta_documentos"> </tbody>
         </table>

         <div id="datos_val" class="mt-3" style="display: none;">
             <div class="row g-2 align-items-center">
                 <!-- Campo de token -->
                 <div class="col-12 col-md-8">
                     <input
                         type="text"
                         class="form-control form-control-sm"
                         id="tokenval"
                         name="tokenval"
                         placeholder="Token de validación"
                         disabled>
                 </div>
                 <!-- Botón -->
                 <div class="col-12 col-md-4 text-md-start text-center">
                     <button type="button" class="btn btn-success w-100 btn-sm" id="validar_token">
                         Validar Código de Seguridad
                     </button>
                 </div>
             </div>
         </div>

         <button class="btn btn-success btn-sm me-1 px-1 py-1" title="solicitar estudio de seguridad" id="validar_solicitud">
             <span class="mdi mdi-shield-security"></span> Solicitar Estudio de seguridad
         </button>

         <div id="sol_estu" style="display: none;">
             <div class="row">
                 <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                     <input type="hidden" id="placa_es" class="form-control input-sm" readonly="readonly">
                 </div>
                 <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                     <input type="hidden" id="popietario_es" class="form-control input-sm" readonly="readonly">
                 </div>
                 <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                     <input type="hidden" id="tenedor_es" class="form-control input-sm" readonly="readonly">
                 </div>
                 <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                     <input type="hidden" id="conductor_es" class="form-control input-sm" readonly="readonly">
                 </div>
             </div>
             <div class="row">
                 <table class='table table-bordered table-striped table-sm text-center' style=" font-size:12px;">
                     <thead>
                         <tr>
                             <th style="width: auto; white-space: nowrap;" class="text-center">Objeto</th>
                             <th style="width: auto; white-space: nowrap;" class="text-center">Validado</th>
                             <th style="width: auto; white-space: nowrap;" class="text-center">Mensaje</th>
                             <th style="width: auto; white-space: nowrap;" class="text-center">Módulo</th>
                         </tr>
                     </thead>
                     <tbody id="cuerpo_valida"></tbody>
                 </table>
             </div>

             <div class="col.12 text-center" style="margin-top: 15px;" id="validar_hv">
                 <button class="btn btn-info btn-sm me-1 px-1 py-1" title="solicitar estudio de seguridad" id="validar_hojasv">
                     <span class="mdi mdi-collection-text"></span> Validar Hojas de vida
                 </button>
             </div>

             <div style="text-align: center;display:none;" id="loadings">
                 <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="30" width="30">
                 <h4 style="color:#000;">Solicitanto estudio por favor esperar un momento...</h4>
             </div>

             <div class="col.12 text-center" style="margin-top: 15px;display: none;" id="solicitar_hv">
                 <button class="btn btn-success btn-sm me-1 px-1 py-1" title="solicitar estudio de seguridad" id="validar_solicitud">
                     <span class="mdi mdi-shield-security"></span> Solicitar Estudio de seguridad
                 </button>
             </div>
         </div>
     </div>
 </div>