<div class="panel panel-border panel-contrast">
  <div id="msg_editar_gestion"></div>
  <div id="content_editar">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg12">

      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-12 com-md-12 col-lg-12">
        <label><strong>Estados del vehículo</strong></label>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-hover table-bordered table-condensed table-striped">
          <thead>
            <tr>
              <th class="text-center">Estado</th>
              <th class="text-center">Fecha - Hora</th>
              <th class="text-center">Reporte cliente</th>
              <th class="text-center">Usuario</th>
            </tr>
          </thead>
          <tbody id="novedad_estado">
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-12 com-md-12 col-lg-12">
        <label><strong>Seguimientos</strong></label>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-condensed table-hover table-bordered table-striped">
          <thead>
            <tr>
              <th class="text-center">Orden cargue</th>
              <th class="text-center">Tipo</th>
              <th class="text-center">Fecha</th>
              <th class="text-center">Hora</th>
            </tr>
          </thead>
          <tbody id="tiempo_cargue">
          </tbody>
        </table>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-condensed table-hover table-bordered table-striped" id="tabla_novedad_seguimiento">
          <thead>
            <tr>
              <th class="text-center">T. seguimiento</th>
              <th class="text-center">Obs</th>
              <th class="text-center">contacto</th>
              <th class="text-center">Reporte</th>
              <th class="text-center">Solicitud servicio</th>
              <th class="text-center">Usuario</th>
              <th class="text-center">Registro</th>
            </tr>
          </thead>
          <tbody id="novedad_seguimiento">
          </tbody>
        </table>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-condensed table-hover table-bordered table-striped">
          <thead>
            <tr>
              <th class="text-center">Remesa</th>
              <th class="text-center">Tipo</th>
              <th class="text-center">Fecha</th>
              <th class="text-center">HOra</th>
            </tr>
          </thead>
          <tbody id="tiempo_descargue">
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
