<?php
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
$vista = '';
$table_content='';



$table_content.="<div class='row' >
			<div class='col-sm-12'>
				<div  class='table-responsive noSwipe'>
					<table id='table1' class='table table-striped table-hover' data-page-length='100'>
						<thead>
							<tr class='nexos-encabezado'>
								<th>#</th>
								<th>Origen</th>
								<th>Destino</th>
								<th>Tipo Vehículo</th>
								<th>Flete</th>
								<th style='width:10%;min-width: 10%;'>acciones</th>
							</tr>
						</thead>
						<tbody>";
						$arrayPermisos = $this->flete->permisosPerfil( $ssn_id_perfil , 59);
						$_permisos = $arrayPermisos;
						$array = $this->flete->getFleteNacional();
						if ( $array) {
							foreach ($array as $key => $valor) {

								$_btn_editar = ''; $btn_elimina='';
							if($valor['estado']==1){
								if ($_permisos['editar']) {
									$_btn_editar = '
										<a id="pruebabtn" href="javascript:"
										onclick="editaFlete(' . $valor['id'] . ')" class="cell-detail hint--top-left" data-hint="Editar Flete" 
											>
											<span class="icon mdi mdi-edit" data-toggle="modal"
											data-target="#edita_fletenacional" >
											</span>
										</a>
									';
								}	

								if($_permisos['eliminar']){
									$btn_elimina='<a id="" href="javascript:"
										onclick="inactivaFlete(' . $valor['id'] . ', '.$valor['tarifa'].')" class="cell-detail hint--top-left" data-hint="Inactivar Flete" 
											>
											<span class="icon mdi mdi-block" data-toggle="modal"
											data-target="#Inactiva_fletenacional" >
											</span>
										</a>';
								}
							}	

							//estados
							$estado='';
							if($valor['estado']==1){
								$estado="<td class='nexos-txt-success'>
									<center><span class='mdi mdi-dot-circle icon'></span></center>
								</td>";
							}
							if($valor['estado']==0){
								$estado="<td class='nexos-txt-danger'>
									<center><span class='mdi mdi-dot-circle icon'></span></center>
								</td>";
							}

								$table_content.='
								<tr>
								'.$estado.'
								<td>'.$valor['municipio_origen'].'</td>
								<td>'.$valor['municipio_destino'].'</td>
								<td>'.$valor['nombre'].'</td>
								<td>'.
								number_format($valor["tarifa"], 2, ',', '.') .'</td>
								<td  class="actions" >
								 '.$_btn_editar.'
								 '.$btn_elimina.'
								</td>
								</tr>';
							}
						}	
						$table_content.="</tbody>
					</table>
				</div>
			</div>
		</div>";


	$vista.='
			<div class="panel panel-border panel-contrast">
				<div class="panel-heading panel-heading-contrast">
					Fletes
					<div class="tools">
						<a id="btn_crea" href="#"  data-toggle="modal"  class="cell-detail  hint--top "  data-hint="" ><span class="icon mdi mdi-plus" title="Agregar"></span></a> 
					</div>
					<span class="panel-subtitle">Lista de Fletes estandar de las diferentes rutas a nivel nacional con variedad de tipos de vehículos.
					</span>
					<div class=" col-xs-12 col-sm-4 col-md-12">
						<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'" >
						<input type="hidden" id="elperfil" class="form-control input-sm" readonly="readonly" value="'.$ssn_id_perfil.'">
					</div>
				</div>
				<div class="panel-body">
					<div class="nexos-messages"></div>
					<div class="nexos-content">
						%content%
					</div>
					<div class="row">
					<div class="col-sm-12"></div>
					</div>
				</div>
			</div>
		'; 


		?>
<script type="text/javascript">
		//abrir el primer modal
		$(document).on('click', '#btn_crea', function() {
			//abrir el modal principal
	        $('#crea_fletenacional').modal('show');
    	});
	</script>

<?php 
$vista.='
<div id="crea_fletenacional" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary" style="overflow-y: scroll;">
	<div class=".modal-dialog-modal-lg.modal-dialog ">
		<div class="modal-content ">
			<div class="modal-header">
				<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
				<h3 class="modal-title">
				<label style="font-size:19pt; color:white; text-align:center;">
				Crear Flete Nacional
				</label>
				</h3>
			</div>
			<div class="modal-body"  style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
			<div id="nexos_messages_popup"></div>
			<div class="row">
				<div class="text-right">
					<span>(*) Campos Obligatorios</span>
				</div>
							<div class="form-group col-xs-6">
								<label style="font-weight:800; margin-top:20px;">(*) Origen:</label>
								' . $this->municipios->getHtmlSelectnew( "id_ciudad_origen" , "" ) . '
							</div>
							<div class="form-group col-xs-6">
								<label style="font-weight:800; margin-top:20px;">(*) Destino:</label>
								' . $this->municipios->getHtmlSelectnew2( "id_ciudad_destino" , "" ) . '
							</div>
							<div class="row"></div>
							<div class="form-group col-xs-4">
								<label style="font-weight:800; margin-top:20px;">(*) Tipo Vehículo:</label>
								' . $this->tipo_vehiculo->getHtmlSelect2( "id_tipo_vehiculo" , "" , "1" ) . '
							</div>
							<div class="form-group col-xs-4">
								<label style="font-weight:800; margin-top:20px;">(*)Costo Flete:</label>
								<input type="text" name="valor" id="valor" placeholder="Flete" class="form-control">
							</div>
							<div class="form-group col-xs-4">
								<label style="font-weight:800; margin-top:20px;">(*)Año Vigencia:</label>
								<input type="text" name="vigencia" id="vigencia" placeholder="Vigencia" class="form-control">
							</div>
							<div class="form-group col-xs-4">
								<label style="font-weight:800; margin-top:20px;">(*)Mes Vigencia:</label>
								<select class="form-control input-sm" id="mes_flete">
								<option value="">Seleccione un elemento de la lista</option>
								<option value="1">Enero</option>
								<option value="2">Febrero</option>
								<option value="3">Marzo</option>
								<option value="4">Abril</option>
								<option value="5">Mayo</option>
								<option value="6">Junio</option>
								<option value="7">Julio</option>
								<option value="8">Agosto</option>
								<option value="9">Septiembre</option>
								<option value="10">Octubre</option>
								<option value="11">Noviembre</option>
								<option value="12">Diciembre</option>
								</select>
							</div>
							</div>
			<div class="row"></div>
		</div>
		<div class="modal-footer">
			<button type="button"  id="btn_agregar_flete" class="btn btn-success">Guardar</button>
			<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
		</div>
	</div>
	</div>
</div>	';


$vista.='
<div id="edita_fletenacional" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary" style="overflow-y: scroll;">
	<div class=".modal-dialog-modal-lg.modal-dialog ">
		<div class="modal-content ">
			<div class="modal-header">
				<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
				<h3 class="modal-title">
				<label style="font-size:19pt; color:white; text-align:center;">
				Editar Flete Nacional</label>
				</h3>
			</div>
			<div class="modal-body"  style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
			<div id="nexos_messages_popup"></div>
				<div class="row">
					<div class="nexos_messages_popup"></div>
							<div id="edita_flete_content"></div>
							<div class="row"></div>
				</div>
				<div class="row"></div>
		</div>
		<div class="modal-footer">
			<button type="button" data-dismiss="modal" id="btn_edita_flete" class="btn btn-success md-close">Guardar</button>
			<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
		</div>
	</div>
	</div>
</div>';

$vista.='<div id="Inactiva_fletenacional" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary" style="overflow-y: scroll;">
	<div class=".modal-dialog-modal-lg.modal-dialog ">
		<div class="modal-content ">
			<div class="modal-header">
				<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
				<h3 class="modal-title">
				<label style="font-size:19pt; color:white; text-align:center;">
				Inactivar Flete Nacional</label>
				</h3>
			</div>
			<div class="modal-body"  style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
			<div id="nexos_messages_popup"></div>	
				<div class="row">
					<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
						<label>Flete</label>
						<input type="text" id="iflete" class="form-control input-sm" readonly="readonly">
					</div>
					<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
						<label>Id</label>
						<input type="text" id="idflete" class="form-control input-sm" readonly="readonly">
					</div>
				</div>
		</div>
		<div class="modal-footer">
			<button type="button" data-dismiss="modal" id="btn_inactiva_flete" class="btn btn-success md-close">Inactivar</button>
			<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
		</div>
	</div>
	</div>
</div>';
	
	$vista.= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
		<link  rel="stylesheet" type="text/css" href="assets/lib/select2/css/select2.min.css"/>

		<link rel="stylesheet" type="text/css" src="%root_file%lib/assets/lib/select2/css/select2.min.css"/>


		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
		<script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.wizard();
			});
		</script>
	';
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_content , $vista); //variable $table_content sirve para crear adentro de esta todo lo que se va a mostrar en el cuerpo del conetenedor 
	echo $vista;	
?>

<script type="text/javascript">
$("select[name=slct_municipios]").change(function () {
	$(".nexos-messages").empty();
	$("#nexos_messages_popup").html('');
	if($("select[name=slct_municipios]").val() && $("select[name=slct_municipios2]").val() && $("#slct_tipo_vehiculo_").val()){
		if( verificaFlete( $("select[name=slct_municipios]").val(), $("select[name=slct_municipios2]").val(), $("#slct_tipo_vehiculo_").val() ) ){
			$("#valor").val("");
			$("#valor").attr("disabled",true);
			$("#vigencia").val("");
			$("#vigencia").attr("disabled",true);
			$("#nexos_messages_popup").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong><p>El Flete que esta intentando crear ya se encuentra creado, por favor búsquelo en la lista de fletes para editarlo.</p></div></div>');
		}
	}
});

$("select[name=slct_municipios2]").change(function () {
	$(".nexos-messages").empty();
	$("#nexos_messages_popup").html('');
	if($("select[name=slct_municipios]").val() && $("select[name=slct_municipios2]").val() && $("#slct_tipo_vehiculo_").val()){
		if( verificaFlete( $("select[name=slct_municipios]").val(), $("select[name=slct_municipios2]").val(), $("#slct_tipo_vehiculo_").val() ) ){
			$("#valor").val("");
			$("#valor").attr("disabled",true);
			$("#vigencia").val("");
			$("#vigencia").attr("disabled",true);
			$("#nexos_messages_popup").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong><p>El Flete que esta intentando crear ya se encuentra creado, por favor búsquelo en la lista de fletes para editarlo.</p></div></div>');
		}
	}
});	

$("#slct_tipo_vehiculo_").change(function () {
	$(".nexos-messages").empty();
	$("#nexos_messages_popup").html('');
	if($("select[name=slct_municipios]").val() && $("select[name=slct_municipios2]").val() && $("#slct_tipo_vehiculo_").val()){
		if( verificaFlete( $("select[name=slct_municipios]").val(), $("select[name=slct_municipios2]").val(), $("#slct_tipo_vehiculo_").val() ) ){
			$("#valor").val("");
			$("#valor").attr("disabled",true);
			$("#vigencia").val("");
			$("#vigencia").attr("disabled",true);
			$("#nexos_messages_popup").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong><p>El Flete que esta intentando crear ya se encuentra creado, por favor búsquelo en la lista de fletes para editarlo.</p></div></div>');
		}
	}
});

$("#btn_agregar_flete").click(function () {
	//alert('crear flete');
	$("#nexos_messages_popup").empty();
		var msg_error = "";

		// Validaciones del módulo 
		if ( !$("select[name=slct_municipios]").val() ) {
			msg_error+= "<p>Debe seleccionar un <strong>Origen</strong> para poder crear el Flete.</p>";
		}
		if ( !$("select[name=slct_municipios2]").val() ) {
			msg_error+= "<p>Debe seleccionar un <strong>Destino</strong> para poder crear el Flete.</p>";
		}
		if ( !$("#slct_tipo_vehiculo_").val() ) {
			msg_error+= "<p>Debe seleccionar un <strong>Tipo Vehículo</strong> para poder crear el Flete.</p>";
		}
		if ( !$("#valor").val() ) {
			msg_error+= "<p>Debe diligenciar el campo <strong>Costo Flete</strong> para poder crear el Flete.</p>";
		}
		if ( !$("#vigencia").val() ) {
			msg_error+= "<p>Debe diligenciar el campo <strong>Vigencia</strong> para poder crear el Flete.</p>";
		}
		if( !$("#mes_flete").val() ){
			msg_error+= "<p>Debe diligenciar el campo <strong>Mes Vigencia</strong> para poder crear el Flete.</p>";
		}
		// Fin - Validaciones del módulo 
		if (!msg_error) {
			var params = {
				vigencia 		: $("#vigencia").val(),
				mes             : $("#mes_flete").val(),
				origen 			: $("select[name=slct_municipios]").val(),
				destino 		: $("select[name=slct_municipios2]").val(),
				tipo_vehiculo 	: $("#slct_tipo_vehiculo_").val(),
				tarifa 			: $("#valor").val()
				
			}
			// console.log(params);
			$.ajaxSetup({async: false});
			$.ajax({
				url: $("#id_url_ajax").val() + "libs/fletes_ajax.php?action=guardaFleteNacional",
				type: 'POST',
				data: params,
				cache: false,
				dataType: 'json',
				beforeSend	: function(jqXHR, settings){
					console.log("Entro en el proceso de creación del remitente/destinatario");
					$("#nexos_messages_popup").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
				},
				error: function (jqXHR, textStatus, errorThrown)
				{
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
					if(jqXHR.responseText){
						msg_error+= "<p>" + jqXHR.responseText + "</p>";
					}
				},
				success: function (data, textStatus, jqXHR)
				{
					// console.log(data);
					if (!data.error) {
						$("#nexos_messages_popup").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong> Se ha creado el registro con éxito.</div></div>');
						setTimeout(function() { location.reload(false);  }, 600);
					} else {
						msg_error+= data.error;
					}
				}
			});
			$.ajaxSetup({async: true});
		}
		if(msg_error){
			$("#nexos_messages_popup").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("html, body").animate({ scrollTop: 0 }, 600);
		}
});

function editaFlete(id){
		// console.log("Entro en editaFlete");
		 //alert(id);
		$(".nexos_messages_popup").html('');

		var params = {
			id 		: id
		}

		$.ajax({
			url: $("#id_url_ajax").val() + "libs/fletes_ajax.php?action=buscaFlete2",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			error: function (jqXHR, textStatus, errorThrown)
			{
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function (data, textStatus, jqXHR)
			{
				// console.log(data);
				console.log(data.control);
				$(".nexos-messages").html('');
				if (!data.error) {
					$("#edita_flete_content").html(data.content);
				} else {
					$(".nexos_messages_popup").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + data.error + '</div></div>');
				}
			}
		});
	}

$("#btn_edita_flete").click(function(){
	// alert('editar flete');
	$(".nexos-messages").empty();
	var msg_error = "";
	if ( !$("#e_valor").val() ) {
			msg_error+= "<p>Debe diligenciar el campo <strong>Flete</strong> para poder editar el Flete.</p>";
		}
		if ( !$("#e_vigencia").val() ) {
			msg_error+= "<p>Debe diligenciar el campo <strong>Vigencia</strong> para poder editar el Flete.</p>";
		}

		if (!msg_error) {
			var params = {
				id 				: $("#e_id").val(),
				tarifa 			: $("#e_valor").val(),
				vigencia 		: $("#e_vigencia").val(),
				mes             : $("#e_mes").val()
			}
			// console.log(params);

			$.ajaxSetup({async: false});
			$.ajax({
				url: $("#id_url_ajax").val() + "libs/fletes_ajax.php?action=editaFlete2",
				type: 'POST',
				data: params,
				cache: false,
				dataType: 'json',
				beforeSend	: function(jqXHR, settings){
					$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
				},
				error: function (jqXHR, textStatus, errorThrown)
				{
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
					if(jqXHR.responseText){
						msg_error+= "<p>" + jqXHR.responseText + "</p>";
					}
				},
				success: function (data, textStatus, jqXHR)
				{
					// console.log(data);
					if (!data.error) {
						$(".nexos-messages").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong> Se ha editado el registro con éxito.</div></div>');
						setTimeout(function() { location.reload(false);  }, 600);
					} else {
						msg_error+= data.error;
					}
				}
			});
			$.ajaxSetup({async: true});
		}

		if(msg_error){
			$(".nexos-messages").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("html, body").animate({ scrollTop: 0 }, 600);
		}

});	


function inactivaFlete(id,valor){
	$("#idflete").val(id);	
	$("#iflete").val(valor);
}

$("#btn_inactiva_flete").click(function(){
	$(".nexos-messages").empty();
	var msg_error = "";
	var id=$("#idflete").val();
	var params = {
		id 		: id
	}
	$.ajaxSetup({async: false});
			$.ajax({
				url: $("#id_url_ajax").val() + "libs/fletes_ajax.php?action=inactivarFlete",
				type: 'POST',
				data: params,
				cache: false,
				dataType: 'json',
				beforeSend	: function(jqXHR, settings){
					$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
				},
				error: function (jqXHR, textStatus, errorThrown)
				{
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
					if(jqXHR.responseText){
						msg_error+= "<p>" + jqXHR.responseText + "</p>";
					}
				},
				success: function (data, textStatus, jqXHR)
				{
					// console.log(data);
					alert('Flete Inactivado Exitosamente!!');
					setTimeout(function() { location.reload(false);  }, 600);
				}
			});
			$.ajaxSetup({async: true});
	
});

function verificaFlete(origen, destino, tipo_vehiculo){
		// console.log("Entro en función verificaFlete");
		$("#valor").attr("disabled",false);
		$("#vigencia").attr("disabled",false);
		var flag_verifica_flete = false;
		var params = {
			origen 			: origen,
			destino 		: destino,
			tipo_vehiculo 	: tipo_vehiculo
		}
		$.ajaxSetup({async: false});
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/fletes_ajax.php?action=verificaFlete2",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend	: function(jqXHR, settings){
				$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
			},
			error: function (jqXHR, textStatus, errorThrown)
			{
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function (data, textStatus, jqXHR)
			{
				$(".nexos-messages").html('');
				// console.log(data);
				if ( data.flag_flete ) {
					flag_verifica_flete = true;
				}
			}
		});
		$.ajaxSetup({async: true});
		return flag_verifica_flete;
}
</script>