<?php
	$vista = '';
	$conexion= new Conexion();
	function reversarKey($key) {
		$key = html_entity_decode($key);
		$key = strrev($key);
		$key = base64_decode($key);
		return explode('|', $key);
	}
		
	$data = reversarKey($_REQUEST['k']);
	$verificar_url=$conexion->verificar_url($data[1]);


	// print_r("<pre> <p>data</p>");
	// print_r($data);
	// print_r("</pre>");

	// print_r("<pre> <p>_REQUEST</p>");
	// print_r($_REQUEST);
	// print_r("</pre>");

	// print_r("<pre> <p>_SESSION</p>");
	// print_r($_SESSION);
	// print_r("</pre>");

	if (!($verificar_url) || !(empty($_REQUEST['k']) || $data[0] != $_SESSION['confirm_reset']['reset_pass'] || $data[1] != $_SESSION['confirm_reset']['user_log'] || $data[2] != $_SESSION['confirm_reset']['email']  )) {

		// Se busca el id del usuario que está restableciendo la clave
		$result = $this->usuarios->getUserId($_SESSION['confirm_reset']['user_log']);
		$id_usuario = $result["rowsData"][0][0];

		$url = BASE_URL . 'libs/myajax.php';
		$vista .= '
			<input type="hidden" id="id_url_ajax" value="' . BASE_URL . '">
			<div class="panel-body xs-mt-15">
				<div class="col-xs-1 col-sm-2 col-md-3"></div>
				<div class="col-xs-12 col-sm-8 col-md-6">
					<div class="panel panel-default panel-border-color panel-border-color-warning">
						<div class="panel-heading text-center">
							<img src="' . BASE_URL . 'views\layout\assets\img\logo.png" alt="logo" width="242" height="85" class="logo-img">
							<span class="splash-description"><h4>Recuperación de contraseña NexossApp.</h4></span>
						</div>
						<div class="panel-body" id="panel_reset">

							<div role="alert" class="alert alert-contrast alert-primary alert-dismissible  mensajito">
                    			<div class="icon"><span class="mdi mdi-check"></span></div>
         						<div class="message">
                      				<p class="text-center">
                      					<strong>
                      						El botón para recuperar su contraseña aparecerá cuando el proceso este completo y no tenga ningún error
                     					</strong>
                      				</p>
                    			</div>
                			</div>

							<div class="form-group error_messages" id="mensajes"></div>
							<form id="form_reset" method="post">
								<div class="form-group col-xs-12 col-sm-12 col-md-4">
									<label>Número de Documento:</label>
									<input type="text" placeholder="Número de Documento" id="user_log" name="user_log" class="form-control input-sm">
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-8">
									<label>Correo Electrónico</label>
									<input type="email" placeholder="Correo Electrónico" id="correo" class="form-control input-sm">
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-12">
									<label>Ingresa el código enviado al correo electrónico</label>
									<input type="text" placeholder="Código de Verificación" id="code" class="form-control input-sm">
								</div>
								<div class="form-group col-xs-12 col-sm-6 col-md-6">
									<label>Nueva Contraseña:</label>
									<input type="password" placeholder="Nueva Contraseña" id="new_pass" name="new_pass" data-id_usuario="' . $id_usuario . '" class="form-control input-sm  nueva_clave">
								</div>
								<div class="form-group col-xs-12 col-sm-6 col-md-6">
									<label>Confirmar Nueva Contraseña:</label>
									<input type="password" placeholder="Confirmar Nueva Contraseña" id="confirm_pass" name="confirm_pass" class="form-control input-sm  nueva_clave">
								</div>
							</form>
							<div class="col-xs-12 col-sm-12 col-md-12">
								<p class="text-right">
									<button id="btn_recuperar" class="btn btn-space btn-primary btn_content" style="font-size:15px;">Recuperar contraseña</button>
								</p>
							</div>
						</div>
					</div>
					<div class="col-sm-3"></div>
				</div>
				<div class="col-xs-1 col-sm-2 col-md-3"></div>
			</div>
		';

		/***** CARGA DE ARCHIVOS JS DE LA VISTA *****/
		$vista .= '
			<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
			<script src="%root_file%js/main.js" type="text/javascript"></script>
			<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
			<script type="text/javascript">
				$(document).ready(function(){
					//initialize the javascript
					App.init();
				});
			</script>
		';

		/***** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  *****/
		$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
	} else {
		$vista = '
			<div class="be-wrapper be-error be-error-404">
				<div class="error-container">
					<div class="error-number">403</div>
					<div class="error-description">Acceso denegado.</div>
					<div class="error-goback-text">Usted no tiene permisos para ingresar a este modulo.</div>
				</div>
			</div>
		';
	}
	echo $vista;
?>
<script type="text/javascript">
	$(document).ready(function(){
		$(".btn_content").hide();
		//para realizar los insert en las tablas porque todo esta bien 
		$("#btn_recuperar").click(function(){
			$("#mensajes").empty();

				
			let msg_error = ""; 
			var form = $('#form_reset'); //cobija todo lo que este dentro del formulario 
			var campos = form.find('.form-control');//encontrar los campos del formulario que tengasn la clase form-control 
			//alert (campos.length);
			campos.each(function(){//usa el placeholder, valida que los campos no estén vacíos y usa el placeholder para mostrar que campo debe diligenciar el usuario
				if(!$(this).val() ){
					msg_error+= `<p>Debe diligenciar el campo <strong>${$(this).attr('placeholder')}</strong> para poder cambiar la clave.</p>`;
				}
			});

			/*if (user_log != true || email != true || new_pass != true || confirm_pass != true || code != true){
				funct_msg_error("#mensajes", "<p>Hay campos sin diligenciar en el formulario, por favor verifique toda la información para poder continuar.</p>");
				$("html, body").animate({ scrollTop: 0 }, 600);
			} */

			if(!msg_error){
				$.ajax({
					type:       "POST", //TIPO DE PETICION PUEDE SER GET
					dataType:   "json", //EL TIPO DE DATO QUE DEVUELVE PUEDE SER JSON/TEXT/HTML/XML
					url: $("#id_url_ajax").val() + 'libs/myajax.php', //DIRECCION DONDE SE ENCUENTRA LA OPERACION A REALIZAR
					data:   {
						user_log:$("#user_log").val(),
						email:$("#correo").val(),
						pass:$("#new_pass").val(),
						Op:"reset"
					}, //DATOS ENVIADOS PUEDE SER TEXT A TRAVEZ DE LA URL O PUEDE SER UN OBJETO
					beforeSend: function(){//ACCION QUE SUCEDE ANTES DE HACER EL SUBMIT
						$(".error_messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
					},
					success: function(response){//ACCION QUE SUCEDE DESPUES DE REALIZAR CORRECTAMENTE LA PETCION EL CUAL NOS TRAE UNA RESPUESTA
						$(".error_messages").empty();
						if (response.respuesta == "GOOD"){
							$("#mensajes").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong></strong> Se ha actualizado tu contraseña <br> A continuación la pagina se dirigira al inicio de sesion </div></div>');
							setTimeout(function(){ window.location.href = $("#id_url_ajax").val() + "index"; }, 2000);
						} else{
							$("#mensajes").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong></strong> Su contraseña no ha podido ser actualizada, por favor intente nuevamente</div></div>');
						}
					},
					error: function(){//SI OCURRE UN ERROR
						$(".error_messages").empty(); 
						$("#mensajes").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong></strong> Su contraseña no ha podido ser actualizada, por favor intente nuevamente</div></div>');

					}
				});
			}
			if(msg_error){
				funct_msg_error(".error_messages", msg_error);
				$("html, body").animate({ scrollTop: 0 }, 600);
			}
		});

		//valida que el número de documento coincida con la bd
		$("#user_log").focusout(function(){
			$(".error_messages").empty();
			if($(this).val()){
				sincrono("ValidarDatosReset", "user_log", "#user_log", $("#id_url_ajax").val() + 'libs/myajax.php', function(resp){
					if (resp == false){
						funct_msg_error(".error_messages", "El número de documento ingresado es incorrecto");
						$("html, body").animate({ scrollTop: 0 }, 600);
					}
				});
			}
		});

		//valida que el número de verificación ingresado sea el mismo registrado en la tabla cmx_usuarios_claves
		$("#code").focusout(function(){
			$(".error_messages").empty();
			if($(this).val()){
				sincrono("ValidarDatosReset", "code", "#code", "'.$url.'", function (resp){
					if (resp == false){
						funct_msg_error(".error_messages", "El código de verificación ingresado es incorrecto");
						$("html, body").animate({ scrollTop: 0 }, 600);
					}
				});
			}
		});

		//valida el protocolo de la clave y que no se repita en la bd
		$("#new_pass").blur(function(){
			$(".error_messages").empty();
			let msg_error = "";
			if($(this).val()){
				var clave = $(this).val();
				let flag_clave = valida_clave(clave,$(this).data("id_usuario"));
				if(flag_clave){ msg_error+= flag_clave; }
				if(msg_error){
					funct_msg_error(".error_messages", msg_error);
					$("html, body").animate({ scrollTop: 0 }, 600);
				}
			}
		});

		//se valida que las claves no sena iguales, se le pone la misma clase a los dos campos  
		$(".nueva_clave").blur(function(){
			$(".error_messages").empty();
			let msg_error = "";
			msg_error+= claves_iguales($("#new_pass").val(), $("#confirm_pass").val());
			if (!msg_error && $("#new_pass").val() && $("#confirm_pass").val()) {
				$(".btn_content").show(); 
			}
			if (msg_error) { //se crean los mensajes de error que se muestran en la parte superior del formulario cambio clave
				funct_msg_error(".error_messages", msg_error); 
				$("html,body").animate({ scrollTop: 0 }, 600);
				$(".btn_content").hide();
			}
		});






	});
</script>