<?php
	$_dbTable = "perfiles"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/***** CREACION DE TABLA DE CONTENIDO *****/
	if(isset($this->usuario)){
		$result = $this->usuario->permisosPerfil( $_SESSION["usuario"]["id_perfil"], 69);
		$permisos = $result["rowsData"][0];
		// print_r("<pre>");
		// print_r($permisos);
		// print_r("</pre>");

		/***** SE CREA TABLA DE CONTENIDO *****/
		$table_content = '
			<div class="table-responsive noSwipe col-xs-12 col-sm-12 col-md-12">
				<table id="table1" class="table table-striped table-hover" data-page-length="100">
					<thead>
						<tr class="nexos-encabezado">
							<th class="col-xs-2 col-sm-2 col-md-2">#</th>
							<th>Perfil</th>
							<th class="col-xs-2 col-sm-2 col-md-2"></th>
						</tr>
					</thead>
					<tbody>
		';

		$result = $this->usuario->getPerfiles();
		// print_r("<pre>");
		// print_r($result);
		// print_r("</pre>");
		 $cont=0;
		if ($result) {
			foreach ($result["rowsData"] as $key => $value) {
				$cont++;
				// Filtro de la visa de estado del usuario 
				$col_action = '
					<td class="actions"></td>
				';
				switch ($value["estado"]) {
					case 0:
						$col_stasus = '
							<td class="nexos-txt-danger">
								<center>
									<div style="display: none;">' . $value[0] . '</div>
									<span class="icon mdi mdi-dot-circle"></span>
								</center>
							</td>
						';
						if ($permisos["eliminar"]) {
							$col_action = '
								<td class="actions">
									<a href="#" data-toggle="modal" data-target="#activar" class="cell-detail activar md-trigger hint--top-left" data-hint="Activar Perfil" data-id="' . $value[0] . '">
										<span class="icon mdi mdi-check-circle"></span>
									</a> 
								</td>
							';
						}
						break;

					case 1:
						$col_stasus = '
							<td class="nexos-txt-success">
								<center>
									<div style="display: none;">' . $value[0] . '</div>
									<span class="icon mdi mdi-dot-circle"></span>
								</center>
							</td>
						';
						$_btn_inactivar = '';
						if ($permisos["eliminar"]) {
							$_btn_inactivar = '
								<a href="#" data-toggle="modal" data-target="#inactivar" class="cell-detail inactivar md-trigger hint--top-left" data-hint="Inactivar Perfil" data-id="' . $value[0] . '">
									<span class="icon mdi mdi-close-circle"></span>
								</a> 
							';
						}

						$_btn_editar = '';
						$_btn_submodulo='';
						if ($permisos["editar"]) {
							$_btn_editar = '
								<a href="#" data-toggle="modal" data-target="#permisos" class="cell-detail permisos md-trigger hint--top-left" data-hint="Adiministrar Permisos" data-id="' . $value[0] . '" data-nombre="' . $value["nombre_perfil"] . '">
									<span class="icon mdi mdi-menu"></span>
								</a> 
								<a href="#" data-toggle="modal" data-target="#modulos" class="cell-detail modulos md-trigger hint--top-left" data-hint="Adiministrar Líneas de Negocio" data-id="' . $value[0] . '" data-nombre="' . $value["nombre_perfil"] . '" data-autor="' . $_SESSION["usuario"]["id_usuario"] . '">
									<span class="icon mdi mdi-view-module"></span>
								</a> 
								<a href="#" data-toggle="modal" data-target="#editar" class="cell-detail editar md-trigger hint--top-left" data-hint="Editar Perfil" data-id="' . $value[0] . '" data-nombre="' . $value["nombre_perfil"] . '" data-tipo_perfil="' . $value["tipo_perfil"] . '">
									<span class="icon mdi mdi-edit"></span>
								</a> ';
								//ASOCIAR EL SUBMENU A UN MODULO
							/*	$_btn_submodulo ='<a href="#" data-toggle="modal" 
									id="botonmodulo"
									data-target="#submenu_modulo'.$cont.'" class="cell-detail editar md-trigger hint--top-left" data-hint="Asociar Submenú Al Módulo" data-id="' . $value[0] . '" data-nombre="' . $value["nombre_perfil"] . '" data-tipo_perfil="' . $value["tipo_perfil"] . '">
									<span class="icon mdi mdi-widgets"></span>
								</a>'; */


									$_btn_submodulo ='<a href="javascript:" onclick="sub_modulo(this)" class="cell-detail hint--top-left" data-hint="Editar Cotización" 
										data-id="' . $value[0] . '"  data-nombre="' . $value["nombre_perfil"] . '" data-tipo_perfil="' . $value["tipo_perfil"] . '"  >
										<span class="icon mdi mdi-widgets" data-toggle="modal" data-target="#submenu_modulo">
										</span>
									</a>
								';



							
						}

						$col_action = '
							<td class="actions">
								' . $_btn_editar . '
								'.$_btn_submodulo.'
								' . $_btn_inactivar . '
							</td>
						';
						break;
				}
				$table_content.= '
					<tr>
						' . $col_stasus . '
						<td class="cell-detail">
							<span>' . $value["nombre_perfil"] . '</span>
							<span class="cell-detail-description">' . $value["tipo_perfil"] . '</span>
						</td>
						' . $col_action . '
					</tr>
				';
			}
		}

		$table_content.= '
					</tbody>
				</table>
			</div>
		';
	}
	/***** FIN CREACION DE TABLA DE CONTENIDO *****/

	/***** CONTENIDO DEL MODULO EN PANTALLA *****/
	$slct_tipo_perfil = $this->usuario->getEnumSlctTipoPerfil( "tipo_perfil" , "" , "");
	$slct_e_tipo_perfil = $this->usuario->getEnumSlctTipoPerfil( "e_tipo_perfil" , "" , "");

	$_btn_crear = '';
	if ($permisos["adicionar"]) {
		$_btn_crear = '
			<a href="#" data-toggle="modal" data-target="#crear" class="cell-detail crear hint--top-left" data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a> 
		';
	}

	$vista.='
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
	';

	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Adimistrar Perfiles de Usuarios
				<div class="tools">
					' . $_btn_crear . '
				</div>
				<span class="panel-subtitle"></span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
			</div>
		</div>

		<div id="crear" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title">Crear Perfil de Usuario</h3>
					</div>
					<div class="modal-body">
						<div class="nexos_messages_popup"></div>
						<form id="form_crear">
							<div class="form-group col-md-2"></div>
							<div class="form-group col-xs-12 col-sm-6 col-md-4">
								<label>(*) Tipo Perfil:</label>
								' . $slct_tipo_perfil . '
							</div>
							<div class="form-group col-xs-12 col-sm-6 col-md-4">
								<label>(*) Nombre:</label>
								<input type="text" name="nombre" id="nombre" placeholder="Nombre Perfil" class="form-control input-sm">
							</div>
							<div class="form-group col-md-2"></div>
							<div class="row"></div>
						</form>
					</div>
					<div class="modal-footer">
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
						<button id="btn_crear" type="button" class="btn btn-success md-close">Guardar</button>
					</div>
				</div>
			</div>
		</div>

		<div id="editar" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="editar_title"></h3>
					</div>
					<div class="modal-body">
						<div class="nexos_messages_popup"></div>
						<form id="form_editar">
							<input type="hidden" name="id_edita" id="id_edita">
							<div class="form-group col-md-2"></div>
							<div class="form-group col-xs-12 col-sm-6 col-md-4">
								<label>(*) Tipo Perfil:</label>
								' . $slct_e_tipo_perfil . '
							</div>
							<div class="form-group col-xs-12 col-sm-6 col-md-4">
								<label>(*) Nombre:</label>
								<input type="text" name="e_nombre" id="e_nombre" placeholder="Nombre Perfil" class="form-control input-sm">
							</div>
							<div class="form-group col-md-2"></div>
							<div class="row"></div>
						</form>
					</div>
					<div class="modal-footer">
						<button id="btn_editar" type="button" class="btn btn-success md-close">Guardar</button>
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
					</div>
				</div>
			</div>
		</div>
		<!--submenu y modulo -->
		<div id="submenu_modulo" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="editar_title">Asignar Módulo al Submenú</h3>
					</div>
					<div class="modal-body">
						<div class="nexos_messages_popup"></div>
						<form id="form_editar">
						<div class="row">
							
							<div class="form-group col-xs-12 col-sm-4 col-md-4">
								<label>(*)Perfil:</label>
								<input type="text" id="perfil" readonly="" class="form-control input-sm">
							</div>
							<div class="form-group col-xs-12 col-sm-4 col-md-4">
								<label>(*)Nombre:</label>
								<input type="text" id="name_perfil" readonly="" class="form-control input-sm">
							</div>
							<div class="form-group col-xs-12 col-sm-4 col-md-4">
								<label>(*)Tipo Perfil:</label>
								<input type="text" id="tipo_perfil" readonly="" class="form-control input-sm">
							</div>
							<input type="hidden" name="id_auditor" id="id_auditor" value="'.$_SESSION["usuario"]["id_usuario"].'">
						</div>	
						<div class="row">
						<div class="form-group col-xs-12 col-sm-4 col-md-4">
							<label>Submenú</label>
							<select class="form-control select2" id="submenu">
								<option></option>
							</select>
						</div>
						<div class="form-group col-xs-12 col-sm-4 col-md-4">	
							<label>Módulo</label>
							<select class="form-control select2" id="elmodulo">
								<option></option>
							</select>
						</div>	

						</div>
							
							<div class="row"></div>
						</form>
					</div>
					<div class="modal-footer">
						<button id="btn_asignarmodulo" type="button" class="btn btn-success md-close">Guardar</button>
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
					</div>
				</div>
			</div>
		</div>

		<div id="inactivar" tabindex="-1" role="dialog" class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close"><span class="mdi mdi-close"></span></button>
					</div>
					<div class="modal-body">
						<div class="nexos_messages_popup"></div>
						<input type="hidden" name="id_inactiva" id="id_inactiva">
						<div class="form-group col-sm-12 text-center">
							<div class="text-danger"><span class="modal-main-icon mdi mdi-close-circle"></span></div>
							<h3 >¿Desea inactivar este perfil?</h3>
						</div>
					</div>
					<div class="modal-footer">
						<div class="col-sm-12 text-center">
							<button type="button" data-dismiss="modal" class="btn btn-default">Cancelar</button>
							<button id="btn_inactivar" type="button"  class="btn btn-danger">Aceptar</button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div id="activar" tabindex="-1" role="dialog" class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close"><span class="mdi mdi-close"></span></button>
					</div>
					<div class="modal-body">
						<div class="nexos_messages_popup"></div>
						<input type="hidden" name="id_activa" id="id_activa">
						<div class="form-group col-sm-12 text-center">
							<div class="text-success"><span class="modal-main-icon mdi mdi-check-circle"></span></div>
							<h3 >¿Desea activar este perfil?</h3>
						</div>
					</div>
					<div class="modal-footer">
						<div class="col-sm-12 text-center">
							<button type="button" data-dismiss="modal" class="btn btn-default">Cancelar</button>
							<button type="button" class="btn btn-success" id="btn_activar">Aceptar</button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div id="permisos" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="permisos_title"></h3>
					</div>
					<div class="modal-body">
						<div class="nexos_messages_popup"></div>
						<div id="permisos_content"></div>
					</div>
					<div class="modal-footer">
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
					</div>
				</div>
			</div>
		</div>

		<div id="modulos" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="modulos_title"></h3>
					</div>
					<div class="modal-body">
						<div class="nexos_messages_popup"></div>
						<div id="modulos_content"></div>
					</div>
					<div class="modal-footer">
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
					</div>
				</div>
			</div>
		</div>
	';

  	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_content , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;
?>

<script type="text/javascript">

	$(document).ready(function(){
		$("#btn_crear").click(function(){
			var msg_error = "";
			var nombre = $("#nombre").val();
			var tipo_perfil = $("#slct_tipo_perfil_").val();
			if (!tipo_perfil) { msg_error+= '<p>Debe seleccionar un <strong>Tipo Perfil</strong> para crear el perfil.</p>'; }
			if (!nombre) { msg_error+= '<p>Debe diligenciar el campo <strong>Nombre</strong> para crear el perfil.</p>'; }

			if (!msg_error) {
				var param = {
					action: "crea_perfil",
					id: $("#id_edita").val(),
					nombre_perfil: nombre,
					tipo_perfil: tipo_perfil
				}
				ejecutaJquery(param);
			}
			if (msg_error) { funct_msg_error(".nexos_messages_popup", msg_error); }
		});

		$("#btn_editar").click(function(){
			var msg_error = "";
			var nombre = $("#e_nombre").val();
			var tipo_perfil = $("#slct_e_tipo_perfil_").val();
			if (!tipo_perfil) { msg_error+= '<p>Debe seleccionar un <strong>Tipo Perfil</strong> para editar el perfil.</p>'; }
			if (!nombre) { msg_error+= '<p>Debe diligenciar el campo <strong>Nombre</strong> para editar el perfil.</p>'; }

			if (!msg_error) {
				var param = {
					action: "edita_perfil",
					id: $("#id_edita").val(),
					nombre_perfil: nombre,
					tipo_perfil: tipo_perfil
				}
				ejecutaJquery(param);
			}
			if (msg_error) { funct_msg_error(".nexos_messages_popup", msg_error); }
		});

		$("#btn_inactivar").click(function(){
			var param = {
				action: "inactiva_perfil",
				id: $("#id_inactiva").val()
			}
			ejecutaJquery(param);
		});

		$("#btn_activar").click(function(){
			var param = {
				action: "activa_perfil",
				id: $("#id_activa").val()
			}
			ejecutaJquery(param);
		});
	});

		function sub_modulo(element){
				// alert('hidhshd');
				var elemento = $(element);
				var perfil= elemento.data("id");
				var nombre= elemento.data("nombre");
				var tipo= elemento.data("tipo_perfil");
				// alert(perfil);
				// alert(nombre);
				// alert(tipo);
				$("#perfil").val(perfil);
				$("#name_perfil").val(nombre);
				$("#tipo_perfil").val(tipo);

				//cargar submenus y cargar modulos
				var dato1={
					action:'traer submenus'
				};
				
					$("#submenu").select2({
						  width:'100%'
					});

					$.ajax({
						url:"http://localhost/mvcLuisMiguel/libs/submenus_ajax.php",
			 			type:'POST',
			 			data:dato1,
			 			dataType:'json',
			 			success: function(data){
			 				// console.log(data);
			 				// alert('trajjo submenu');
			 				data.result.forEach(function(element,index){
			 					$("#submenu").append('<option value="'+element.id+'">'+element.nom_menu+'-'+ element.titulo+'</option>');
			 				});

			 			},
			 			error: function(jqXHR, textStatus, errorThrown){
			 				// alert('no trajo submenu');
			 				console.log(jqXHR);
							console.log(textStatus);
							console.log(errorThrown);
			 			}

 					});	

 				var dato2={
 					action:'traer_modulo'
 				};

 				$("#elmodulo").select2({
						  width:'100%'
					});
 				$.ajax({
						url:"http://localhost/mvcLuisMiguel/libs/submenus_ajax.php",
			 			type:'POST',
			 			data:dato2,
			 			dataType:'json',
			 			success: function(data){
			 				// console.log(data);
			 				// alert('trajjo modulo');
			 				data.result.forEach(function(element,index){
			 					$("#elmodulo").append('<option value="'+element.id+'">'+element.nombre+'</option>');
			 				});

			 			},
			 			error: function(jqXHR, textStatus, errorThrown){
			 				// alert('no trajo modulo');
			 				console.log(jqXHR);
							console.log(textStatus);
							console.log(errorThrown);
			 			}

 					});	
		}


		$("#btn_asignarmodulo").click(function(){
			alert('asignar modulo');
			var a=$("#submenu").val();
			var b=$("#elmodulo").val();
			var usuario=$("#id_auditor").val();
			if(a=='' || b==''){
				alert('Por favor Seleccione un submenu y un módulo');
			}else{
				alert('puede asignar');

				var crear={
					submemu:a,
					modulo:b,
					user:usuario,
					action:'crear_submenumodulo'
				};

				$.ajax({
						url:"http://localhost/mvcLuisMiguel/libs/submenus_ajax.php",
			 			type:'POST',
			 			data:crear,
			 			dataType:'json',
			 			success: function(data){
			 				// console.log(data);
			 				 alert('Datos Registrados Exitosamente!!');
			 				 $("html, body").animate({ scrollTop: 0 }, 600);
							setTimeout(function() { location.reload(false);  }, 800);
			 			},
			 			error: function(jqXHR, textStatus, errorThrown){
			 				 // alert('No inserto');
			 				console.log(jqXHR);
							console.log(textStatus);
							console.log(errorThrown);
			 			}
 					});	
			}
		});

	$(".modulos").click(function(e){
		$("#modulos_title").html(`Módulos del Perfil - ${$(this).data("nombre")}`);
		var id_perfil = $(this).data("id");
		var param = {
			action: "ver_modulos_perfil",
			id: id_perfil,
			nombre: $(this).data("nombre"),
			autor: $(this).data("autor")
		}
		var content = consultaJquery(param);
		if (content) {
			$("#modulos_content").html(content);
			//deben estar dentro para funcionar con la tabla 
			$(".check_todos_1").change(function(){
				var id_perfil = $(this).data("id");
				var id_modulo = new Array();

				$(".check_1_" + id_perfil).each(function(){
					let flag = true;
					if( $(this).is(":checked") ){ flag = false; }
					id_modulo.push({
						id: $(this).val(),
						autor: $(this).data("autor"),
						flag: flag
					});
				});

				if( $(this).is(":checked") ){
					var accion = "crear";
					$(".check_1_" + id_perfil).prop("checked",true);
				} else {
					var accion = "quitar";
					$(".check_1_" + id_perfil).removeAttr("checked");
				}

				var param = {
					action: "cambia_modulo",
					accion: accion,
					id_perfil: id_perfil,
					id_modulo: id_modulo
				}
				consultaJquery(param);
			});

			$(".check_solo_1").change(function(){
				$(".check_todos_1").removeAttr("checked");
				var id_perfil = $(this).data("id_perfil");
				if( $(this).is(":checked") ){ var accion = "crear"; }
				else { var accion = "quitar"; }
				var id_modulo = new Array();
				id_modulo.push({
					id: $(this).val(),
					autor: $(this).data("autor"),
					flag: true
				});

				var param = {
					action: "cambia_modulo",
					accion: accion,
					id_perfil: id_perfil,
					id_modulo: id_modulo
				}
				consultaJquery(param);
			});

		}
	});

	$(".permisos").click(function(e){
		$("#permisos_title").html(`Permisos Perfil - ${$(this).data("nombre")}`);
		var id_perfil = $(this).data("id");
		var param = {
			action: "ver_permisos_perfil",
			id: id_perfil
		}
		var content = consultaJquery(param);
		if (content) {
			$("#permisos_content").html(content);

			$(".check_todos").change(function(){
				var id_menu = $(this).data("id");
				var id_submenu = new Array();

				$(".check_" + id_menu).each(function(){
					let flag = true;
					if( $(this).is(":checked") ){ flag = false; }
					id_submenu.push({
						id: $(this).val(),
						flag: flag
					});
				});

				if( $(this).is(":checked") ){
					var accion = "crear";
					$(".check_" + id_menu).prop("checked",true);
				} else {
					var accion = "quitar";
					$(".check_" + id_menu).removeAttr("checked");
				}

				var param = {
					action: "cambia_acceso",
					accion: accion,
					id_perfil: id_perfil,
					id_submenu: id_submenu
				}
				consultaJquery(param);
				verificaPermisos(id_menu);
			});

			$(".check_solo").change(function(){
				$(".check_todos").removeAttr("checked");
				var id_menu = $(this).data("id_menu");
				if( $(this).is(":checked") ){ var accion = "crear"; }
				else { var accion = "quitar"; }
				var id_submenu = new Array();
				id_submenu.push({
					id: $(this).val(),
					flag: true
				});

				var param = {
					action: "cambia_acceso",
					accion: accion,
					id_perfil: id_perfil,
					id_submenu: id_submenu
				}
				consultaJquery(param);
				verificaPermisos(id_menu);
			});

			$(".check_adicionar").change(function(){
				$(".check_todos").removeAttr("checked");
				if( $(this).is(":checked") ){ var accion = "asignar"; }
				else { var accion = "quitar"; }
				var id_submenu = $(this).val() ;

				var param = {
					action: "cambia_permiso",
					accion: accion,
					campo: "adicionar",
					id_perfil: id_perfil,
					id_submenu: id_submenu
				}
				consultaJquery(param);
			});

			$(".check_editar").change(function(){
				$(".check_todos").removeAttr("checked");
				if( $(this).is(":checked") ){ var accion = "asignar"; } 
				else { var accion = "quitar"; }
				var id_submenu = $(this).val() ;

				var param = {
					action: "cambia_permiso",
					accion: accion,
					campo: "editar",
					id_perfil: id_perfil,
					id_submenu: id_submenu
				}
				consultaJquery(param);
			});

			$(".check_eliminar").change(function(){
				$(".check_todos").removeAttr("checked");
				if( $(this).is(":checked") ){ var accion = "asignar"; } 
				else { var accion = "quitar"; }
				var id_submenu = $(this).val() ;

				var param = {
					action: "cambia_permiso",
					accion: accion,
					campo: "eliminar",
					id_perfil: id_perfil,
					id_submenu: id_submenu
				}
				consultaJquery(param);
			});
		}
	});

	$(".editar").click(function(e){
		let element = $(this);
		$(".nexos_messages_popup").empty();
		$("#editar_title").html(`Editar Perfil - ${element.data("nombre")}`);
		$("#id_edita").val( element.data("id") );
		$("#e_nombre").val( element.data("nombre") );
		$("#slct_e_tipo_perfil_ option[value=" + element.data("tipo_perfil") + "]").attr('selected','selected');
	});

	$(".activar").click(function(e){
		$("#id_activa").val( $(this).data("id") );
	});

	$(".inactivar").click(function(e){
		$("#id_inactiva").val( $(this).data("id") );
	});

	function ejecutaJquery(params){
		var msg_error = "";
		try{
			// console.log(params);
			$.ajaxSetup({async: false});
			$.ajax({
				url: $("#id_url_ajax").val() + "libs/usuarios_ajax.php",
				type: 'POST',
				data: params,
				dataType: 'json',
				cache: false,
				beforeSend : function(jqXHR, settings){
					funct_msg_loading(".nexos-messages");
				},
				error: function (jqXHR, textStatus, errorThrown){
					msg_error+= "<p>" + jqXHR.responseText + "</p>";
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
				},
				success: function (data, textStatus, jqXHR){
					// console.log(data);
					if (data.error) { msg_error+= data.error; }
				}, 
			});
			$(".nexos-messages").html('');
			if (msg_error) { funct_msg_error(".nexos_messages_popup", msg_error); }
			if (!msg_error) {
				funct_msg_success(".nexos_messages_popup");
				setTimeout(function() { location.reload(false);  }, 800);
			}
			$.ajaxSetup({async: true});
		}catch(error){
			console.log(error);
		}
	}

	function consultaJquery(params){
		var msg_error = "";
		var msg_content = "";
		$(".nexos_messages_popup").html('');
		try{
			// console.log(params);
			$.ajaxSetup({async: false});
			$.ajax({
				url: $("#id_url_ajax").val() + "libs/usuarios_ajax.php",
				type: 'POST',
				data: params,
				dataType: 'json',
				cache: false,
				beforeSend : function(jqXHR, settings){
					funct_msg_loading(".nexos-messages");
				},
				error: function (jqXHR, textStatus, errorThrown){
					msg_error+= "<p>" + jqXHR.responseText + "</p>";
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
				},
				success: function (data, textStatus, jqXHR){
					// console.log(data);
					if (data.error) { msg_error+= data.error; } 
					if (data.content) { msg_content+= data.content; }
				}, 
			});
			$(".nexos-messages").html('');
			if (msg_error) { funct_msg_error(".nexos_messages_popup", msg_error); }
			else {
				if (msg_content) { return msg_content; }
			}
			$.ajaxSetup({async: true});
		}catch(error){
			console.log(error);
		}
	}

	function verificaPermisos(id_menu){
		var color = "default";
		$("#perfil_" + id_menu).find(".check_solo").each(function(){
			var id_submenu = $(this).val();
			if ( $(this).is(":checked") ) {
				color = "success";
				$("#check_adicionar_" + id_submenu).removeAttr("disabled");
				$("#check_editar_" + id_submenu).removeAttr("disabled");
				$("#check_eliminar_" + id_submenu).removeAttr("disabled");
			} else {
				$("#check_adicionar_" + id_submenu).prop("checked",false).attr("disabled","disabled");
				$("#check_editar_" + id_submenu).prop("checked",false).attr("disabled","disabled");
				$("#check_eliminar_" + id_submenu).prop("checked",false).attr("disabled","disabled");
			}
		});
		$("#perfil_" + id_menu).attr("class", "panel panel-default panel-border-color panel-border-color-" + color);
	}
</script>
