<input type="hidden" name="perfil_id" id="perfil_id" value="<?= $_SESSION["usuario"]["id_perfil"] ?>">
<input type="hidden" name="proveedor_id" id="proveedor_id" value="<?= $_SESSION['usuario']['proveedor_id'] ?>">
<input type="hidden" name="cliente_id" id="cliente_id" value="<?= $_SESSION['usuario']['id_cliente'] ?>">
<input type="hidden" name="ventana_id" class="ventana_id" value="<?= $_SESSION['usuario']['ventanas'] ?>">
<div class="container-fluid">
    <div class="row">

        <div class="col-12 col-sm-12 col-md-4 col-lg-5 col-xl-5 col-xxl-5">
            <div class="d-flex flex-wrap justify-content-start mt-2">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                    <h5 class="mb-0 text-body-highlight me-2">Añadir Precintos</h5>
                </div>
            </div>
            <hr class="my-1 text-dark">

            <div class="row mt-2">
                <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12 col-xl-4 col-xxl-4">
                    <div class="mb-3">
                        <label class="control-label">Código inicial:</label>
                        <input type="text" class="form-control form-control-sm" name="codigo_inicial" id="codigo_inicial" required placeholder="PREC-0001">
                    </div>
                </div>

                <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12 col-xl-4 col-xxl-4">
                    <div class="mb-3">
                        <label class="control-label">Código final:</label>
                        <input type="text" class="form-control form-control-sm" name="codigo_final" id="codigo_final" required placeholder="PREC-0100">
                    </div>
                </div>

                <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12 col-xl-4 col-xxl-4">
                    <div class="mb-3">
                        <label class="control-label">Tipo precinto:</label>
                        <select class="form-select form-select-sm" name="tipo_precinto" id="tipo_precinto" required>
                            <option value="" selected>Seleccione</option>
                            <option value="Botella">Botella</option>
                            <option value="Metalico" disabled>Metalico</option>
                            <option value="Plastico" disabled>Plastico</option>
                            <option value="Adhesivo">Adhesivo</option>
                            <option value="Correilla">Correilla</option>
                        </select>
                    </div>
                </div>

                <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                    <div class="border-top border-translucent border-dashed pt-2">
                        <div class="row justify-content-end">
                            <div class="col-auto">
                                <button class="btn btn-success btn-sm py-1" id="btn_guardar_lote" type="button">
                                    <span class="uil uil-save"></span> Registrar Lote
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 col-sm-12 col-md-7 col-lg-7 col-xl-7 col-xxl-7">
            <div class="d-flex flex-wrap justify-content-start mt-2">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                    <h5 class="mb-0 text-body-highlight me-2">Listado de Precintos</h5>
                </div>
            </div>
            <hr class="my-1 text-dark">

            <div id="tableExample3" data-list='{"valueNames":["codigo","tipo","estado","fecha_ingreso","agencia_asignada],"page":15,"pagination":true}'>
                <div class="row mb-3 align-items-center justify-content-center">
                    <div class="col-md-4 search-box mb-3 mx-auto">
                        <form class="position-relative mb-0">
                            <input class="form-control search-input search form-control-sm" type="search" placeholder="Buscar por código, tipo..." aria-label="Search" />
                            <span class="fas fa-search search-box-icon"></span>
                        </form>
                    </div>
                    <div class="col-md-3">
                        <select id="filtro_tipo_precinto" class="form-select form-select-sm">
                            <option value="">-- Filtrar por Tipo --</option>
                            <!-- Opciones insertadas por JS -->
                        </select>
                    </div>
                </div>


                <div class="table-responsive scrollbar">
                    <table class='table table-striped table-hover table-fw-widget table-sm w-100' data-page-length='100' style="font-size:12px;">
                        <thead>
                            <tr>
                                <th class='sort text-center' style='width: auto; white-space: nowrap;'>#</th>
                                <th class='sort text-center' style='width: auto; white-space: nowrap;' data-sort="codigo">Código</th>
                                <th class='sort text-center' style='width: auto; white-space: nowrap;' data-sort="tipo">Tipo</th>
                                <th class='sort text-center' style='width: auto; white-space: nowrap;' data-sort="agencia_asignada">Agencia Asignada</th>
                                <th class='sort text-center' style='width: auto; white-space: nowrap;' data-sort="fecha_ingreso">Fecha Ingreso</th>
                                <th class='sort text-center' style='width: auto; white-space: nowrap;' data-sort="estado">Estado</th>
                                <!-- <th class='text-center' style='width: auto; white-space: nowrap;'>Acciones</th> -->
                            </tr>
                        </thead>
                        <tbody class="list" id="tbody_precintos_listado">
                            <tr class="text-center img_load" id="img_load" style="display: none;">
                                <td colspan="8"><img src="<?= BASE_URL ?>public/img/nexos_loading.gif" height="25" width="25"> Esperando Información</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="d-flex justify-content-between mt-3"><span class="d-none d-sm-inline-block" data-list-info="data-list-info"></span>
                    <div class="d-flex">
                        <button class="page-link" data-list-pagination="prev"><span class="fas fa-chevron-left"></span></button>
                        <ul class="mb-0 pagination"></ul>
                        <button class="page-link pe-0" data-list-pagination="next"><span class="fas fa-chevron-right"></span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Mensajes para los usuarios de la plataforma -->
<div id="loading-overlay-nexosapp" class="loading-nexosapp">
    <div style="text-align: center;">
        <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
        <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para NexosAPP...</h2>
        <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
    </div>
</div>