<?php

$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

$vista = '';
$table_content='';
$table_content2='';

$arrayPermisos = $this->informecot ->permisosPerfil( $ssn_id_perfil , 59);
$_permisos = $arrayPermisos["rowsData"][0];

/*
$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Cotizaciones
				<div class="tools">
				</div>
				<span class="panel-subtitle">Módulo para aprobar cotizaciones de gerencia.</span>
			</div>
			<div class="panel-body">
				<div class="nexos-messages"></div>
				<div class="nexos-content">
					%content%
					%content2%
				</div>
				<div class="row">
				<div class="col-sm-12"></div>
				</div>
			</div>
		<div class="panel-body">
			<div class="nexos-content">
					%content%
					%content2%
				</div>
		</div>
		</div>'; */

	//FILTRO
	$vista.='<div class="row">
		<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
			<label>Fecha inicial</label>
			<input type="date" id="fecinicio" class="form-control input-xs" value="'.date('Y-m-d').'">
		</div>
		<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
			<label>Fecha final</label>
			<input type="date" id="fecfinal" class="form-control input-xs" value="'.date('Y-m-d').'">
		</div>
		<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
			<br>
			<button id="consultar_datos" class="btn btn-primary">Buscar</button>
		</div>
	</div><br>';	


	//PANELES
	$vista.='
	<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
		<div class="panel panel-border panel-contrast">
				<div class="panel-heading panel-heading-contrast">
					Cotizaciones
					<div class="tools">
					</div>
					<span class="panel-subtitle">Tabla para consulta de cotizaciones.</span>
				</div>
		</div>
		<div class="panel-body">
			<div class="nexos-content">
					%content%
				</div>
		</div>
	</div>


	<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
		<div class="panel panel-border panel-contrast">
				<div class="panel-heading panel-heading-contrast">
					Fletes Propuestos
					<div class="tools">
					</div>
					<span class="panel-subtitle">Tabla para consulta de fletes - histórico.</span>
				</div>
		</div>	
		<div class="panel-body">
			<div class="nexos-content">
					%content2%
				</div>
		</div>
	</div>'; 	


	$table_content.="
					<div class='row' >
						<div class='col-sm-12'>
							<div  class=''>
								<table class='table table-bordered'>
									<thead>
										<tr class='nexos-encabezado'>
											<th>#</th>
											<th>N° Cotización</th>
											<th>Cliente</th>
											<th>Estado</th>
											<th>Autorizo</th>
										</tr>
									</thead>
									<tbody id='cuerpo_cotiza'>";
				
	$table_content.="</tbody>
				</table>
			</div>
		</div>
	</div>";	


	$table_content2.="<div class='row' >
	<div class='col-sm-12'>
	<div  class='table-responsive noSwipe'>
		<table class='table table-bordered'>
			<thead>
			<tr class='nexos-encabezado'>
				<th>#</th>
				<th>N° Cotización</th>
				<th>Cliente</th>
				<th>valor propuesto</th>
				<th>Estado</th>
			</tr>
			</thead>
			<tbody id='cuerpo_flete'>";
	
	$table_content2.="</tbody>
				</table>
			</div>
		</div>
	</div>";



	$vista.= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>

		<script src="%root_file%lib/serv_clientecotizaciones_ajax.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
		<link  rel="stylesheet" type="text/css" href="assets/lib/select2/css/select2.min.css"/>

		<link rel="stylesheet" type="text/css" src="%root_file%lib/assets/lib/select2/css/select2.min.css"/>


		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
		<script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.wizard();
			});
		</script>
	';

	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_content , $vista); 
	$vista = str_replace("%content2%" , $table_content2 , $vista); 
	echo $vista;
?>
<script type="text/javascript">
	$("#consultar_datos").click(function(){
		var fi=$("#fecinicio").val();
		var ff=$("#fecfinal").val();

		var consulta={
			fi:fi,
			ff:ff,
			action:'consultar_tablas'
		};

		$.ajax({
			url:$("#id_url_ajax").val()+"libs/gerencia_ajax.php",
 			type:'POST',
 			data:consulta,
 			dataType:'json',
 			success: function(data){
 				$("#cuerpo_cotiza").html('');
 				$("#cuerpo_flete").html('');
 				var estadotb='';
 				if(data.result!=null){
 					data.result.forEach(function(element,index){
 						if(element.estado=='F1'){
 							estadotb='F1-Realizada';
 						}
 						if(element.estado=='F2'){
 							estadotb='F2-Entregada';
 						}
 						if(element.estado=='F3'){
 							estadotb='F3-Ganada';
 						}
 						if(element.estado=='F4'){
 							estadotb='F4-Perdida';
 						}
 						if(element.estado=='F5'){
 							estadotb='F5-Rechazada';
 						}

 						$("#cuerpo_cotiza").append('<tr>'+
 						'<td></td>'+
 						'<td>'+element.n_cotizacion+'</td>'+
 						'<td>'+element.nombre_cliente+'</td>'+
 						'<td>'+estadotb+'</td>'+
 						'<td>'+element.autorizado_por+'</td>'+
 						'</tr>');
 					});
 				}
 				if(data.result2!=null){
 					data.result2.forEach(function(element,index){
 						var s='';
 						if(element.estado==1){
 							s='Aprobado';
 							color='success';
 						}
 						if(element.estado==4){
 							s='Rechazado';
 							color='danger';
 						}

 						$("#cuerpo_flete").append('<tr>'+
 						'<td>'+element.usuario+'</td>'+
 						'<td>'+element.n_cotizacion+'/'+element.id_servicio+'</td>'+
 						'<td>'+element.cliente+'</td>'+
 						'<td>'+element.flete_nuevo+'</td>'+
 						'<td class="text-'+color+'">'+s+'</td>'+	
 						'</tr>');
 					});
 				}
 			},
 			error:function(jqXHR, textStatus, errorThrown){
 				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
 			}	
 		});

	});
</script>