<?php
	$_dbTable = "agrupacion_anticipo"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/

	/*** SE CREA TABLA DE CONTENIDO ***/
	$table_view = '';

	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->solicitudes) /* && count($this->solicitudes) */){
		$table_view = '
			<div class="row">
				<div class="col-sm-1"></div>
				<div class="col-sm-10">
					<table id="table1" class="table table-striped table-hover">
						<thead>
							<tr class="nexos-encabezado">
								<th>Agrupación</th>
								<th class="col-xs-2 col-sm-1 col-md-1">Peso Total</th>
								<th>Vehículo</th>
								<th>Beneficiario</th>
								<th>Solicitudes</th>
								<th class="col-xs-1 col-sm-1 col-md-1"></th>
							</tr>
						</thead>
						<tbody>
		';
		$anticipos = $this->solicitudes->getAnticipos();

		if ($anticipos) {
			foreach ($anticiposas as $key => $value) {
				// se buscan datos del anticipo 
				// $datos_anticipo = $this->solicitudes->getDatosAnticipo($value[0]);
				$datos_anticipo = $this->solicitudes->getDatosAnticipo($value['id']);

				$pin_tarjeta = "";
				$clave = "";
				$numero_manifiesto = "";
				$flete = $value["flete"];
				$anticipo = "";
				$banco = "";
				$tipo_cuenta = "";
				$num_cuenta = "";
				$doc_titular = "";
				$numero_cheque = "";
				$numero_cheque = "";

				if ($datos_anticipo) {
					$pin_tarjeta = $datos_anticipo["pin_tarjeta"];
					$clave = $datos_anticipo["clave"];
					$numero_manifiesto = $datos_anticipo["numero_manifiesto"];
					$flete = $datos_anticipo["flete"];
					$metodo_desembolso = $datos_anticipo["metodo_desembolso"];
					$anticipo = $datos_anticipo["anticipo"];
					$porcentaje_anticipo = $datos_anticipo["porcentaje_anticipo"];
					$banco = $datos_anticipo["banco"];
					$tipo_cuenta = $datos_anticipo["tipo_cuenta"];
					$num_cuenta = $datos_anticipo["num_cuenta"];
					$doc_titular = $datos_anticipo["documento_titular"];
					$nom_titular = $datos_anticipo["nombre_titular"];
					$num_cheque = $datos_anticipo["numero_cheque"];
					$agencia = $datos_anticipo["AGENCIA"];
				}

				switch ($metodo_desembolso) {
					case 'Tarjeta Débito':
						$form_content = '
							<div class="form-group col-xs-8">
								<label>(*) Número de Tarjeta:</label>
								<input type="text" name="pin_tarjeta" id="pin_tarjeta_' . $value['id'] . '" placeholder="Número de Tarjeta" class="form-control" >
							</div>
							<div class="form-group col-xs-4">
								<label>(*) Clave:</label>
								<input type="text" name="clave" id="clave_' . $value['id'] . '" placeholder="Clave" class="form-control" maxlength="4">
							</div>
						';
						break;

					case 'Cuenta Personal':
						$form_content = '
							<div class="row"></div>
							<div class="form-group col-xs-4">
								<label>(*) Entidad Bancaria:</label>
								<input type="text" name="banco" id="banco_' . $value['id'] . '" placeholder="Banco" class="form-control" >
							</div>
							<div class="form-group col-xs-4">
								<label>(*) Tipo de Cuenta:</label></ br>
								<select class="select2 form-control" name="tipo_cuenta" id="tipo_cuenta_' . $value['id'] . '">
									<option value="" disabled selected>Seleccione</option>
									<option value="Ahorros">Ahorros</option>
									<option value="Corriente">Corriente</option>
								</select>
							</div>
							<div class="form-group col-xs-4">
								<label>(*) Número de Cuenta:</label>
								<input type="number" min="0" name="num_cuenta" id="num_cuenta_' . $value['id'] . '" value="" placeholder="Número de Cuenta" class="form-control" >
							</div>
							<div class="form-group col-xs-4">
								<label>(*) Documento del Titular:</label>
								<input type="text" name="documento_titular" id="documento_titular_' . $value['id'] . '" placeholder="Documento del Titular" class="form-control" >
							</div>
							<div class="form-group col-xs-8">
								<label>(*) Nombre del Titular:</label>
								<input type="text" name="nombre_titular" id="nombre_titular_' . $value['id'] . '" placeholder="Nombre del Titular" class="form-control" >
							</div>
						';
						break;

					case 'Cheque':
						$form_content = '
							<div class="row"></div>
							<div class="form-group col-xs-4"></div>
							<div class="form-group col-xs-4">
								<label>(*) Número de Cheque:</label>
								<input type="text" name="numero_cheque" id="numero_cheque_' . $value['id'] . '" placeholder="Número de Cheque" class="form-control" >
							</div>
							<div class="form-group col-xs-4"></div>
						';
						break;

					default:
						$form_content = 'No hay nada';
						break;
				}

				// Se busca la información de las remesas de la agrupación 
				$material_plantilla = $this->solicitudes->getMaterialPlanilla($value['id']);

				$remesas = "";
				foreach ($material_plantilla as $key_01 => $value_01) {
					$_remesa = $value_01["numero_remesa"];
					$remesas.= '
						<input type="hidden" name="numero_remesa_' . $value_01['id'] . '" id="numero_remesa_' . $value_01['id'] . '" value="' . $_remesa . '">
					';
				}

				$form_content.= $remesas;

				$material_proyecto = $this->solicitudes->getMaterialProyecto($value["id"], "Generar Anticipo");
				$vista.= $material_proyecto;

				// se genera el formulario de edicion del registro
				$slct_bancos = $this->solicitudes->getSlctContabildadBancosToAnticipos("cuenta", $value["id"]);
				$form_edit_table = '
					<input type="hidden" name="id_agrupacion" id="id_agrupacion_' . $value["id"] . '" value="' . $value["id"] . '" class="form-control">
					<input type="hidden" name="modulo" value="anticipo" class="form-control">
					<input type="hidden" name="metodo_desembolso" id="metodo_desembolso_' . $value["id"] . '" value="' . $metodo_desembolso . '" class="form-control">
					<input type="hidden" name="numero_manifiesto" value="' . $numero_manifiesto . '" class="form-control">
					<input type="hidden" name="flete" value="' . $flete . '" class="form-control">
					<input type="hidden" name="porcentaje_anticipo" value="' . $porcentaje_anticipo . '" class="form-control">
					<strong>Información del Anticipo</strong>
					<table class="table">
						<tbody>
							<tr>
								<td class="cell-detail text-center" style="padding:5px 5px;">
									<span>Manifiesto</span>
									<span class="cell-detail-description">' . $numero_manifiesto . '</span>
									<span class="cell-detail-description">' . $agencia . '</span>
								</td>
								<td class="cell-detail" style="padding:5px 5px;">
									<span>Beneficiario</span>
									<span class="cell-detail-description">' . $value["NOMBRE_BENEFICIARIO"] . ' (' . $value["DOCUMENTO_BENEFICIARIO"] . ')</span>
									<span class="cell-detail-description">' . $value["BENEFICIARIO"] . '</span>
								</td>
								<td class="cell-detail text-center" style="padding:5px 5px;">
									<span>Flete</span>
									<span class="cell-detail-description">$' . number_format($flete, 0, ",", ".") . '</span>
								</td>
								<td class="cell-detail text-center" style="padding:5px 5px;">
									<span>Anticipo</span>
									<span class="cell-detail-description">$' . number_format($anticipo, 0, ",", ".") . '</span>
								</td>
								<td class="cell-detail text-center" style="padding:5px 5px;">
									<span>% Anticipo</span>
									<span class="cell-detail-description">' . $porcentaje_anticipo . '%</span>
								</td>
							</tr>
							<tr><td></td><td></td><td></td><td></td><td></td></tr>
						</tbody>
					</table>
					<div class="form-group col-xs-6">
						<label>(*) Comprobante de Egreso:</label>
						<input type="text" name="comprobante_egreso" id="comprobante_egreso_' . $value['id'] . '" placeholder="Comprobante de Egreso" class="form-control" >
					</div>
					<div class="form-group col-xs-6">
						<label>(*) Cuenta:</label>
						' . $slct_bancos . '
					</div>
					' . $form_content . ' 
					<div class="row"></div>
				';

				$_popupEdita = $form_edita->_form_modal_update_validate( $value['id'] , "Gestionar Anticipo - Agrupación # " . $value["numero_agrupacion"] , $form_edit_table , $_dbTable );
				$vista.= $_popupEdita[0];
				$_jsScripts.=$_popupEdita[1];

				// Se busca las solicitudes asociadas al agrupamiento del vehículo
				$solicitud_anticipos = $this->solicitudes->getSolicitudAnticipos($value["id"]);

				$info_solicitudes = "";
				foreach ($solicitud_anticipos as $key1 => $value1) {
					$info_solicitudes.= $value1["numero_solicitud"];
				}

				// Se busca el vehiculo y conductor del transporte
				$solicitud_vehiculo = $this->solicitudes->getVehiculoAnticipos($value["id"]);
				$info_vehiculo = "";
				foreach ($solicitud_vehiculoas as $key2 => $value2) {
					$_placa_trailer = "";
					// Se pregunta si el vehículo tiene trailer
					if ( $value2["placa_trailer"] ) {
						$_placa_trailer = '<span class="cell-detail-description">Trailer: ' . $value2["placa_trailer"] . '</span>';
					}
					// Se pregunta si el vehículo tiene algún tipo de carrocería establecido
					$_tipo_carroceria = "";
					if ( $value2["tipo_carroceria"] ) {
						$_tipo_carroceria = ' (' . $value2["tipo_carroceria"] . ')';
					}
					$info_vehiculo.= '
						<span>' . $value2["CONDUCTOR"] . '</span>
						<span class="cell-detail-description">' . $value2["placa"] . '</span>
						' . $_placa_trailer . ' 
						<span class="cell-detail-description">' . $value2["nombre"] . $_tipo_carroceria . '</span>
					';
				}

				// Se maqueta contenido de la tabla 
				$table_view.= '
					<tr>
						<td class="cell-detail">
							<span>' . $numero_manifiesto . '</span>
							<span class="cell-detail-description">' . $value["numero_agrupacion"] . '</span>
							<span class="cell-detail-description">' . $value["AGENCIA"] . '</span>
						</td>
						<td class="cell-detail">
							<span>' . number_format($value["peso_total"], 2, ",", ".") . ' Kg</span>
						</td>
						<td class="cell-detail">
							' . $info_vehiculo . '
						</td>
						<td class="cell-detail">
							<span>' . $value["NOMBRE_BENEFICIARIO"] . '</span>
							<span class="cell-detail-description">' . $value["DOCUMENTO_BENEFICIARIO"] . '</span>
							<span class="cell-detail-description">' . $value["BENEFICIARIO"] . '</span>
						</td>
						<td class="cell-detail">
							' . $info_solicitudes . '
						</td>
						<td class="actions">
							<a href="#" data-toggle="modal" data-target="#edita_' . $value[0] . '" class="cell-detail md-trigger hint--top-left" data-hint="Gestionar Anticipo"><span class="icon mdi mdi-edit"></span></a>
						</td>
					</tr>
				';
			}
		}

		$table_view.= '
						</tbody>
					</table>
				</div>
			</div>
		';
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Anticipos de Carga
				<div class="tools">
				</div>
				<span class="panel-subtitle">Módulo de documentación y asignación de clave de las tarjetas físicas que son entregadas al conductor.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
			</div>
		</div>
	';


  	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();


			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_view , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
