<?php
	//include "../models/Solicitudes.php";
	$_dbTable = "ar"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	$vista .= '		<link rel="stylesheet" type="text/css" href="%root_file%lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>
		<style>
			.twitter-typeahead{
				width: 100%;
			}
			.tt-menu {
				background: white;
				border-radius: 4px;
				border: 1px solid gray;
				width: 100%;
				max-height: 100px;
				overflow-y: auto;
				width: 100%;
				text-align: left;
			}
			.tt-suggestion{
				padding:5px 10px;
			}
			.tt-suggestion.tt-cursor{
				color: white;
				background: #0097cf;
			}
		</style>';
	/********* FIN POPUPS *********/

	/*** CREACION DE TABLA DE CONTENIDO ***/
	/*** SE CREA TABLA DE CONTENIDO ***/
	$tabla_asignaciones = "
		<div class='row'>
			<div class='col-sm-12'>
				<div class='table-responsive noSwipe'>
					<table id='table1' class='table table-striped table-hover'>
						<thead>
							<tr class='nexos-encabezado'>
								<th style='width:5%;'>#</th>
								<th>Número de agrupación</th>
								<th>Cliente</th>
								<th>Peso </th>
								<th>Tipo vehículo</th>
								<th>Fecha</th>
								<th>Solicitudes</th>
								<th style='width:10%;min-width: 10%;'>Vehículos</th>
							</tr>
						</thead>
						<tbody >
	";
	$model = new Aprobaciones();
	$model->listarAsignaciones();
	$respuesta = $model->respuesta;
	// print_r("<pre>");
	// print_r($model);
	// print_r("</pre>");

	$totalsolicitudes = 0;
	if ($respuesta == "BAD") {
		$totalsolicitudes = 0;
	}
	if ($respuesta == "GOOD") {
		$datos_asignaciones = $model->listado;
		$totalsolicitudes = count($datos_asignaciones);
		if (count($datos_asignaciones) > 0) {
			$tabla_asignaciones .= "";
			$x = 1;
			foreach ($datos_asignaciones as $asignacion) {
				$tabla_asignaciones .= "</span></td>    ";
				$tabla_vehiculos_asignaciones ="";
				$valor_aprobado= false;
				if(count($asignacion["vehiculos"])>0){
					$tabla_vehiculos_asignaciones .= "
						<td>
							<table class='table table-striped' style='margin-bottom: 0px;'>
								<thead>
									<tr>
										<th style='padding: 1px 10px;'>Placa</th>
										<th style='padding: 1px 10px;'>Trámite</th>
										<th style='padding: 1px 10px;'>Estado</th>
										<th style='width:10%;min-width: 10%; padding: 1px 10px;'</th>
									</tr>
								</thead>
								<tbody>
					";
					$placa_aprobada="";
					for ($x = 0; $x < count($asignacion["vehiculos"]); $x++) {
						$tabla_vehiculos_asignaciones .="
							<tr>
								<td class='cell-detail' style='padding-top: 1px; padding-bottom: 1px;'>
									<span>".$asignacion["vehiculos"][$x]["placa"]."</span>
								</td>
								<td class='cell-detail' style='padding-top: 1px; padding-bottom: 1px;'>
									<span>".$asignacion["vehiculos"][$x]["tipo_tramite"]."</span>
								</td>
								<td class='cell-detail' style='padding-top: 1px; padding-bottom: 1px;'>
									<span>".$asignacion["vehiculos"][$x]["estado"]."</span>
								</td>
								<td class='actions' style='padding-top: 1px; padding-bottom: 1px;'>
									<a href='javascript:' onclick='verVehiculo(".$asignacion["vehiculos"][$x]["id_vehiculo"].",".$asignacion["vehiculos"][$x]["id_agrupacion_solicitud"].")'  class='cell-detail  hint--top-left' data-hint='Ver vehículo'>
										<span class='icon mdi mdi-eye' data-toggle='modal' data-target='#ver_vehiculos'></span>
									</a>
									<a href='javascript:' class='cell-detail  hint--top-left' data-hint='Cambiar estado asignación'>
										<span class='icon mdi mdi-check-circle' onclick='enviaridasignacionestado(".$asignacion["vehiculos"][$x]["id_agrupacion_solicitud"].")' data-toggle='modal' data-target='#cambia_estado_asignaciones'></span>
									</a>
								</td>
							</tr>
						";
						if($asignacion["vehiculos"][$x]["estado"]== "Aprobado"){
							$valor_aprobado= true;
							$placa_aprobada=$asignacion["vehiculos"][$x]["placa"];
						}
					}

					$tabla_vehiculos_asignaciones .=   "</tbody></table>";
					if($valor_aprobado == true){
						$tabla_vehiculos_asignaciones= "
							<td>
								<span class='cell-detail'>".$placa_aprobada."</span>
							</td>
						";
					}
				}
				else{
					$tabla_vehiculos_asignaciones= "
						<td>
							<span class='cell-detail'>Aún no hay asignación de vehículos para este grupo</span>
						</td>
					";
				}
				if ($valor_aprobado == true){
					$tabla_asignaciones.="
						<tr>
							<td class='nexos-txt-success'>
								<span class='mdi mdi-dot-circle icon'></span>
							</td>
					";
				}
				else if ($asignacion["codigo_rojo"] == "1"){
					$tabla_asignaciones.="
						<tr>
							<td class='nexos-txt-danger'>
								<span class='mdi mdi-dot-circle icon'></span>
							</td>
					";
				}
				else if ($asignacion["codigo_rojo"] == "0"){
					$tabla_asignaciones.="
						<tr>
							<td class='nexos-txt-warning'>
								<span class='mdi mdi-dot-circle icon'></span>
							</td>
					";
				}

				$col_cliente = "<td class='cell-detail'>";
				for ($y = 0; $y < count($asignacion["solicitudes"]); $y++) {
					$col_cliente.= "<span>" . $asignacion["clientes"][$y] . "</span>";
				}
				$col_cliente.= "</td>";

				$tabla_asignaciones .= "
					<td class='cell-detail'><span >$asignacion[numero_agrupacion]</span></td>
					" . $col_cliente . "
					<td class='cell-detail'><span >" . number_format($asignacion["peso_total"], 2, ",", ".") . " Kg</span></td>
					<td class='cell-detail'><span >$asignacion[tipo_vehiculo]</span></td>
					<td class='cell-detail'><span >$asignacion[fecha_hora_operacion]</span></td>
					<td class='cell-detail'>
				";
				for ($x = 0; $x < count($asignacion["solicitudes"]); $x++) {
					$tabla_asignaciones .= $asignacion["solicitudes"][$x];
				}
				$tabla_asignaciones.=$tabla_vehiculos_asignaciones."</tr>";
				$x++;
			}
		}
	}

	$tabla_asignaciones .= '
						</tbody>
					</table>
					<input type="hidden" id="num_solicitudes" value= "' . $totalsolicitudes . '">
				</div>
			</div>
		</div>
	';
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Aprobación de vehículos
				<span class="panel-subtitle">Módulo para la aprobación de vehículos a propuestos por operaciones.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista .= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/typeahead.bundle.js" type="text/javascript"></script>
		<script src="%root_file%lib/aprobaciones_ajax.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>

		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/daterangepicker/js/daterangepicker.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script src="%root_file%lib/moment.js/min/moment.min.js" type="text/javascript"></script>

		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>

		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
				App.formElements();
			});
		</script>
	';
	/****** CREACION CONTENIDO DE POPUPS ******/

	// CONTENIDO DEL POPUP DE FORMULARIO DE CREACION
	?>

	<div id="cambia_estado_asignaciones" tabindex="-1" role="dialog" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" data-dismiss="modal" aria-hidden="true" class="close"><span class="mdi mdi-close"></span></button>
				</div>
				<div class="modal-body">
					<div id="cambia_estado_asignaciones_msg"></div>
					<div class="text-center">
						<div class="text-success"><span class="modal-main-icon mdi mdi-check-circle"></span></div>
						<h3 class="form-group">¿Desea cambiar el estado de esta asignación?</h3>
						<div class="form-group col-xs-12 col-sm-6 col-md-6">
							<label for="estado_asignaciones">Estado:</label>
							<select id="estado_asignaciones" class="form-control input-sm">
								<option value="">Seleccione el estado</option>
								<option value="Propuesto">Propuesto</option>
								<option value="Aprobado">Aprobado</option>
								<option value="Preaprobado">Preaprobado</option>
								<option value="Pendiente">Pendiente</option>
								<option value="No Aprobado">No Aprobado</option>
								<option value="Cancelado">Cancelado</option>
							</select>
						</div>
						<div class="form-group col-xs-12 col-sm-6 col-md-6">
							<label for="e_tipo_tramite">Tipo de trámite:</label>
							<select id="e_tipo_tramite" class="form-control input-sm" disabled>
								<option value="">Seleccione el tipo de trámite</option>
								<option value="Nuevo">Nuevo</option>
								<option value="Actualizacion">Actualización</option>
								<option value="Refrendacion">Refrendación</option>
								<option value="Validacion">Validación</option>
								<option value="Habilitacion">Habilitación</option>
								<option value="Legalizacion">Legalización</option>
							</select>
						</div>
						<div class="form-group col-xs-3"></div>
						<div class="form-group col-xs-12 col-sm-12 col-md-6">
							<label for="e_observaciones">Observaciones:</label>
							<textarea id="e_observaciones" class="form-control input-sm" placeholder="Observaciones"></textarea> 
						</div>
						<div class="form-group col-xs-3"></div>
						<div class="col-sm-12" id="e_table_content">algo</div>
					</div>
				</div>
				<div class="modal-footer">
					<div class="col-sm-12 text-center">
						<input type="hidden" id="e_flete">
						<input type="hidden" id="e_id_vehiculo">
						<input type="hidden" id="e_id_asignacion">
						<button type="button" data-dismiss="modal" class="btn btn-default">Cancelar</button>
						<button id="btn_cambia_estado_asignacion" type="button"  class="btn btn-success">Aceptar</button>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="ver_vehiculos" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
		<div class="modal-dialog custom-width">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
					<h3 class="modal-title" id="ver_vehiculos_title"></h3>
				</div>
				<div class="modal-body">
					<div class="nexos_messages_popup"></div>
					<div id="ver_vehiculos_content"></div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
				</div>
			</div>
		</div>
	</div>
	<?php
	/****** FIN CREACION CONTENIDO DE POPUPS ******/

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
	$vista = str_replace("%content%", $tabla_asignaciones, $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista .= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;
?>
