<?php
$_dbTable = "agrupaciones"; // SIN EL PREFIJO cmx_
$_jsScripts = "";

$vista = '';

/********* POPUPS *********/
/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
// POPUP DE MUESTRA DE INFORMACION
$info = new Popup();
// POPUP DE ALERTA DE CONFIRMACION
$alert = new Popup();
// POPUP DE FORMULARIO DE EDICION 
$form_edita = new Popup();
// POPUP DE FORMULARIO DE CREACION 
$form_crea = new Popup();

/********* FIN POPUPS *********/

/*** CREACION DE TABLA DE CONTENIDO ***/
if (isset($this->control_agrupaciones)) {

	/*** SE CREA TABLA DE CONTENIDO ***/
	$table_content = '
			<div class="row">
				<div class="col-sm-12">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover" data-page-length="25">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width:5%;">#</th>
									<th style="width:10%;">Código Rojo</th>
									<th>Agrupación</th>
									<th>Peso</th>
									<th>Vehículo Propuesto</th>
									<th>Tarifa</th>
									<th>Valor Flete</th>
									<th>Valor Venta</th>
									<th style="width:10%;">Solicitudes</th>
									<th style="width:10%;"></th>
								</tr>
							</thead>
							<tbody>
		';

	$control_agrupaciones = $this->control_agrupaciones->getControlAgrupamientos();

	if ($control_agrupaciones) {
		foreach ($control_agrupaciones as $key => $value) {

			/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
			switch ($value["estado"]) {
				case '2':
					// se asigna contenido de la columna de estado
					$col_stasus = '<td class="nexos-txt-warning"><span class="mdi mdi-dot-circle icon"></span></td>';

					// se asigna contenido de la columna de estado
					$col_codigo_rojo = '<td class="actions"><center><span class="mdi mdi-truck icon"></center></span></td>';
					if ($value["codigo_rojo"]) {
						$col_codigo_rojo = '<td class="nexos-txt-danger"><center><span class="mdi mdi-truck icon"></center></span></td>';
					}

					// se genera el formulario de edicion del registro
					$_popupHabilita = $alert->_alert_modal_mod_success_control($value['id'], "¿Realmente desea aprobar esta tarifa?", $_dbTable);
					$vista .= $_popupHabilita[0];
					$_jsScripts .= $_popupHabilita[1];

					$_popupElimina = $alert->_alert_modal_mod_danger_control($value['id'], "¿Realmente desea rechazar esta tarifa?", $_dbTable);
					$vista .= $_popupElimina[0];
					$_jsScripts .= $_popupElimina[1];

					// se asigna contenudo de la columna de acciones
					$col_action = '
							<td class="actions">
								<a href="javascript:" class="cell-detail  hint--top-left" data-hint="Ver detalles" onclick="verdatosagrupamiento(' . $value['id'] . ',\'' . $value["numero_agrupacion"] . '\')">
									<span class="icon mdi mdi-eye" data-toggle="modal" data-target="#ver_agrupamiento"></span>
								</a>
								<a href="#" data-toggle="modal" data-target="#habilita_' . $value['id'] . '" class="cell-detail md-trigger hint--top-left" data-hint="Aprobar">
									<span class="icon mdi mdi-check-circle"></span>
								</a>
								<a href="#" data-toggle="modal" data-target="#elimina_' . $value['id'] . '" class="cell-detail md-trigger hint--top-left" data-hint="Rechazar">
									<span class="icon mdi mdi-close-circle"></span>
								</a>
							</td>
						';

					break;
			}
			/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

			// Se maqueta contenido de la tabla 
			$table_content .= '<tr>';
			$table_content .= $col_stasus;
			$table_content .= $col_codigo_rojo;
			$table_content .= '
					<td class="cell-detail">
						<span>' . $value["numero_agrupacion"] . '</span>
						<span class="cell-detail-description">' . $value["fecha_hora_operacion"] . '</span>
					</td>
					<td class="cell-detail text-center">
						<span>' . number_format($value["peso_total"], 2, ",", ".") . ' Kg</span>
					</td>
					<td class="cell-detail">
						<span>' . $value["nombre"] . '</span>
						<span class="cell-detail-description">' . number_format($value["peso_maximo"], 2, ",", ".") . ' Kg</span>
					</td>
					<td class="cell-detail text-right">
						<span>$ ' . number_format($value["tarifa_transporte"], 0, ",", ".") . '</span>
					</td>
					<td class="cell-detail text-right">
						<span>$ ' . number_format($value["valor_compra"], 0, ",", ".") . '</span>
					</td>
					<td class="cell-detail text-right">
						<span>$ ' . number_format($value["valor_venta"], 0, ",", ".") . '</span>
					</td>
					<td class="cell-detail">
						<span class="label label-default">' . $value["CANT_SOLICITUDES"] . '</span>
					</td>
				';
			// se asigna la columna de acciones
			$table_content .= $col_action;
			$table_content .= '</tr>';
		}
	}

	$table_content .= '
							</tbody>
						</table>
					</div>
				</div>
				<div class="col-sm-2"></div>
			</div>
		';
}
/*** FIN CREACION DE TABLA DE CONTENIDO ***/

/**** CONTENIDO DEL MODULO EN PANTALLA ****/
$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Control de Tarifas - Módulo Agrupaciones
				<div class="tools">
				</div>
				<span class="panel-subtitle">Módulo que permite validar si una tarifa es aprobada para continuar con el proceso de transporte de un material.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
			</div>
		</div>
		<div id="ver_agrupamiento" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="title_agrupamiento"></h3>
					</div>
					<div class="modal-body" id="content_agrupamiento">

					</div>
					<div class="modal-footer">
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
					</div>
				</div>
			</div>
		</div>
	';


/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
$vista .= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';


/****** CREACION CONTENIDO DE POPUPS ******/

/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%content%", $table_content, $vista);

// Se asiga codigo JS generado de la tabla de contenido
$vista .= $_jsScripts;

// SE PINTA CONTENIDO EN PANTALLA
echo $vista;

?>
<script type="text/javascript">
	function verdatosagrupamiento(id, agrupamiento) {
		// console.log("Entro en funcion verdatosagrupamiento");

		var params = {
			accion: "verSolicitudesDeAgrupamiento",
			id: id,
			agrupamiento: agrupamiento,
		};
		// console.log(params);

		$.ajax({
			url: $("#id_url_ajax").val() + "libs/solicitudes_ajax.php",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend: function(jqXHR, settings) {
				// console.log("Entro en el proceso de búsqueda de datos de las solicitudes de la agrupación");
				$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
			},
			error: function(jqXHR, textStatus, errorThrown) {
				$(".nexos-messages").html('');
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function(data, textStatus, jqXHR) {
				$(".nexos-messages").html('');
				// console.log(data);
				$("#title_agrupamiento").html(data.title);
				$("#content_agrupamiento").html(data.content);
			}
		});
	}
</script>