<div class="nexos-content">
  <?php /*  if ($ssn_id_perfil == 23 || $ssn_id_perfil == 22 || $ssn_id_perfil == 27 || $ssn_id_perfil == 24 || $ssn_id_perfil == 1) : */ ?>
  <?php if ($ssn_id_perfil == 23 || $ssn_id_perfil == 22 || $ssn_id_perfil == 27 || $ssn_id_perfil == 24) : ?>
    <div class="row" style="margin:-25px -39px -25px -39px;">
      <div id="sin_datos" style="display: none;">
        ERROR
      </div>
      <div id="datos" style="display: none;">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div id="nexos_messages_popup"></div>
          <div class="row">
            <div id="nexos_messages_popup2"></div>
          </div>
          <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
            <tbody>
              <tr>
                <td class="celda_titulo2 text-center" style="margin:25px;">
                  <b>Información del tercero</b>
                </td>
              </tr>
              <tr>
              </tr>
            </tbody>
          </table>
          <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;">
            <tbody>
              <tr>
                <td class="celda_titulo2" style="margin:25px;">
                  <b>Seleccionar el tipo de actividad</b>
                </td>
              </tr>
              <tr>
              </tr>
            </tbody>
          </table>
          <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
            <thead>
              <tr>
                <td class="text-center" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  <input type="checkbox" id="Conductor" name="Conductor" class="tipo_actividad" style=" transform: scale(1.2);" disabled>
                </td>
                <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Conductor</th>
                <td class="text-center" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  <input type="checkbox" id="poseedor_vehiculo" name="poseedor_vehiculo" class="tipo_actividad" style=" transform: scale(1.2);" disabled>
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Poseedor Vehículo</th>
                <td class="text-center" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="checkbox" id="propietario_vehiculo" name="propietario_vehiculo" class="tipo_actividad" style=" transform: scale(1.2);" disabled>
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Propietario Vehículo</th>
                <td class="text-center" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="checkbox" id="propietario_trailer" name="propietario_trailer" class="tipo_actividad" style=" transform: scale(1.2);" disabled>
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Propietario Trailer</th>
                <td class="text-center" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="checkbox" id="Proveedor" name="Proveedor" class="tipo_actividad" style=" transform: scale(1.2);">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Proveedor</th>
              </tr>
            </thead>
          </table>
          <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;">
            <tbody>
              <tr>
                <td class="celda_titulo2" style="margin:25px;">
                  <b>Datos Generales</b>
                </td>
              </tr>
              <tr>
              </tr>
            </tbody>
          </table>
          <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #BDBDBD;color:#fff;border-top: 1px #fff solid;">
            <tbody>
              <tr>
                <td class="text-center" style="margin:25px;">
                  <b>Aplica solo para conductor <span class="text-primary">(*)</span></b>
                </td>
              </tr>
              <tr>
              </tr>
            </tbody>
          </table>
          <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
            <thead>
              <tr>
                <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Tipo de documento:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;margin: 0;">
                  <select id="tipo_documento" style="width: 100%;">
                    <option value="" disabled="disabled" selected="selected">Seleccione un tipo de documento</option>
                    <option value="NIT">NIT</option>
                    <option value="Cedula de Ciudadania">Cédula de Ciudadanía</option>
                    <option value="Cedula de Extranjeria">Cédula de Extranjería</option>
                    <option value="Identificacion Tributaria Internacional">Identificación Tributaria Internacional </option>
                  </select>
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Número de documento:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;margin: 0; ">
                  <input type="number" id="numero_documento" placeholder="Número de documento" style="width: 100%;">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Dígito verific.:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="number" id="digito_verificacion" placeholder="Dígito de verificación" readonly="readonly" style="width: 100%;background-color: #E0E0E0;">
                </td>
              </tr>
              <tr>
                <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Nombre o Razón social:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                  <input type="text" id="rndc_nombre" placeholder="Nombre o Razón social" onblur="mayuscula(this);" style="width: 100%;">
                  <input type="hidden" id="nombre" readonly="readonly">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Primer Apellido:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="text" id="primer_apellido" placeholder="Primer Apellido" onblur="mayuscula(this);" style="width: 100%;">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Segundo Apellido:</th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="text" id="segundo_apellido" placeholder="Segundo Apellido" onblur="mayuscula(this);" style="width: 100%;">
                </td>
              </tr>
              <tr>
                <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Abreviatura:</th>
                <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                  <input type="text" id="abreviatura" placeholder="Abreviatura" style="width: 100%;" onblur="mayuscula(this);">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Teléfono Fijo Contacto:</th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="text" id="contacto" placeholder="Teléfono Contacto" maxlength="7" style="width: 100%;">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Celular Contacto 1:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="text" id="celular" placeholder="Celular Contacto" maxlength="10" minlength="10" style="width: 100%;height: auto;">
                </td>
              </tr>
              <tr>
                <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Celular Contacto 2:&nbsp;<span style="color:blue;"><i><strong>(*)</strong></i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                  <input type="text" id="celular2" placeholder="Celular Contacto" maxlength="10" minlength="10" style="width: 100%;">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Correo electrónico:</th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="email" id="email" placeholder="Correo electrónico" style="width: 100%;">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Municipio:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  <div class="input-group">
                    <input type="text" id="municipio_tabla" placeholder="Municipio" style="width: 100%;" onblur="mayuscula(this);" readonly="readonly">
                    <span class="input-group-btn">
                      <button class="btn-success btn-xs" type="button" data-toggle="modal" data-target="#Modal_Municipios"><i class="fas fa-globe-europe"></i></button>
                    </span>
                    <input type="hidden" id="id_municipio">
                    <input type="hidden" id="rndc_id_municipio">
                    <label id="error_municipio"></label>
                  </div>
                </td>
              </tr>
              <tr>
                <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Dirección:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                  <div class="input-group">
                    <input type="text" id="direccion" placeholder="Dirección" style="width: 100%;" onblur="mayuscula(this);" readonly="readonly">
                    <span class="input-group-btn">
                      <button class="btn-success btn-xs" type="button" data-toggle="modal" data-target=".Modal_direcciones"><i class="fas fa-street-view"></i></button>
                    </span>
                  </div>
                </td>
                <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Tipo de identificación:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                  <select id="tipo_identificacion" disabled style="background-color: #BDBDBD;width: 100%;">
                    <option value="">Seleccione un tipo de identificación</option>
                    <option value="31">31</option>
                    <option value="13">13</option>
                    <option value="22">22</option>
                  </select>
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Estado:</th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <select id="estado" style="width: 100%;">
                    <option value="Activo">Activo</option>
                    <option value="Inactivo">Inactivo</option>
                  </select>
                  <label id="error_estado"></label>
                </td>
              </tr>
              <tr>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Sexo:</th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  <select id="sexo" style="width: 100%;">
                    <option value="">Seleccione</option>
                    <option value="Femenino">Femenino</option>
                    <option value="Masculino">Masculino</option>
                    <option value="Otro">Otro</option>
                  </select>
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Documento identificación:&nbsp;<span style="color:blue;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  <input type="file" name="file-2" id="documentos" onchange="docu_identificable(this.value)" data-multiple-caption="{count} archivos seleccionados" style="width: 100%;">
                </td>
                <input type="hidden" id="namedocu">
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Nombre Documento:</th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" id="documento">
                  <!-- <input type="text" id="docu_soporte" style="width: 100%;" readonly="readonly"> -->
                </td>
              </tr>
            </thead>
          </table>
          <div id="tbl_detalle_proveedor" style="display: none;">
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="celda_titulo2" style="margin:25px;">
                    <b>Detalle Proveedor</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #BDBDBD;color:#000000;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-center" style="margin:25px;">
                    <b>Tipo de proveedor</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
              <thead>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Nacional:</th>
                  <td class="text-center" style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input class="tipo_proveedor" id="nacional" type="radio" name="tipo_proveedor" value="1">
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Internacional:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" class="text-center">
                    <input class="tipo_proveedor" id="internacional" type="radio" name="tipo_proveedor" value="2">
                  </td>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Localización operacional:</th>
                  <td class="text-center" style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <select id="pv_localizacion" class="text-center" style="width: 100%;">
                    </select>
                  </td>
                </tr>
                <tr class="zona" style="display: none;">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Zona:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="8">
                    <input type="text" id="pv_zona" style="width: 100%;">
                  </td>
                </tr>
                <tr>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Tipo de servicio:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="8">
                    <select id="pv_tiposervice" style="width: 100%;">
                      <option value="">Seleccione</option>
                      <option value="Transporte">Transporte</option>
                      <option value="Porteadores">Porteadores</option>
                      <option value="Adecuaciones">Adecuaciones</option>
                      <option value="Aduana">Aduana</option>
                      <option value="Impuestos">Impuestos</option>
                      <option value="Agenciamiento de carga">Agenciamiento de carga</option>
                      <option value="Tramites operativos">Trámites operativos</option>
                      <option value="Tramites administrativos">Trámites administrativos</option>
                    </select>
                  </td>
                </tr>
                <tr>
                  <td class="celda_titulo2" style="margin:25px;background-color: #332D2D;color:#fff;border-top: 1px #fff solid;" colspan="8">
                    <b id="titulo_tservice"></b>
                  </td>
                </tr>
                <tr id="Transporte" style="display: none;">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px;width: auto; white-space: nowrap;">Vía:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="3">
                    <select id="pv_via" style="width: 100%;">
                      <option value="">Seleccione</option>
                      <option value="Aerea">Aerea</option>
                      <option value="Maritima">Maritima</option>
                      <option value="Terrestre">Terrestre</option>
                    </select>
                  </td>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px;width: auto; white-space: nowrap;">Tipificación:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="3">
                    <select id="pv_select" style="width: 100%;"></select>
                  </td>
                </tr>
                <tr id="porteadores" style="display: none;">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px;width: auto; white-space: nowrap;">Detalle:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="7">
                    <select id="detalle_porteador" style="width: 100%;">
                      <option value="">Seleccione</option>
                      <option value="Puertos">Puertos</option>
                      <option value="Aeropuertos">Aeropuertos</option>
                      <option value="Entes regulatorios">Entes regulatorios</option>
                      <option value="Trámites en frontera">Trámites en frontera</option>
                    </select>
                  </td>
                </tr>
                <tr id="agencia_carga" style="display: none;">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px;width: auto; white-space: nowrap;">Detalle:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="7">
                    <select id="detalle_acarga" style="width: 100%;">
                      <option value="">Seleccione</option>
                      <option value="Agente de carga">Agente de carga</option>
                      <option value="Consolidador neutral">Consolidador neutral</option>
                    </select>
                  </td>
                </tr>
                <tr id="tramite_admin" style="display: none;">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px;width: auto; white-space: nowrap;">Trámites Administrativos:</th>
                  <select id="detalle_acarga" style="width: 100%;">
                    <option value="">Seleccione</option>
                    <option value="Agente de carga">Agente de carga</option>
                    <option value="Consolidador neutral">Consolidador neutral</option>
                  </select>
                </tr>
              </thead>
            </table>
            <div id="tbl_contactos" style="display: none;">
              <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;">
                <tbody>
                  <tr>
                    <td class="celda_titulo2" style="margin:25px;">
                      <b>Contactos</b>
                    </td>
                  </tr>
                  <tr>
                  </tr>
                </tbody>
              </table>
              <table class="table table-bordered" id="etbcontact">
                <thead>

                </thead>
                <tbody>
                </tbody>
              </table>
              <input type="hidden" id="ecant_contacto" class="form-control">
              <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
                <thead>
                  <tr>
                    <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                      Agregar contactocional:</th>
                    <td class="text-right" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                      <button class="btn btn-info btn-xs text-center" id="agregar_fila"><i class="fas fa-plus-circle"></i></button>
                    </td>
                    <table class="table table-bordered">
                      <thead style="border-color:blue;">
                      </thead>
                      <tbody id="tabla_contacte">
                      </tbody>
                    </table>
                  </tr>
                </thead>
                <input type="hidden" id="cont_contactos">
              </table>
            </div>
          </div>
          <div class="text-center">
            <div class="btn-group" role="group" aria-label="..." style="margin-top: 15px;margin-bottom: 15px;">
              <button type="button" class="btn btn-success btn-xs" id="btn_agregar_proveedor" style="margin-right: 10px;"><i class="far fa-save"></i> Guardar Proveedor</button>
              <button type="button" class="btn btn-danger btn-xs" id="btn_cancelar_registro"><i class="fas fa-times-circle"></i> Cancelar</button>
              <!-- <button type="button" class="btn btn-default">Middle</button> -->
            </div>
          </div>
        </div>
      </div>
    </div>
  <?php else : ?>
    <div class="row" style="margin:-25px -39px -25px -39px;">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div id="sin_datos" style="display: none;">
          ERROR
        </div>
        <div id="datos" style="display: none;">
          <div id="nexos_messages_popup"></div>
          <!-- <div id="contenedor"></div> -->
          <div class="row">
            <div id="nexos_messages_popup2"></div>
          </div>
          <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
            <tbody>
              <tr>
                <td class="celda_titulo2 text-center" style="margin:25px;">
                  <b>Información del tercero</b>
                </td>
              </tr>
              <tr>
              </tr>
            </tbody>
          </table>
          <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;">
            <tbody>
              <tr>
                <td class="celda_titulo2" style="margin:25px;">
                  <b>Actividades de proveedor</b>
                </td>
              </tr>
              <tr>
              </tr>
            </tbody>
          </table>
          <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
            <thead>
              <tr>
                <td class="text-center" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  <input type="checkbox" id="Conductor" name="Conductor" class="tipo_actividad" style=" transform: scale(1.2);">
                </td>
                <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Conductor</th>
                <td class="text-center" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="checkbox" id="poseedor_vehiculo" name="poseedor_vehiculo" class="tipo_actividad" style=" transform: scale(1.2);">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Poseedor Vehículo</th>
                <td class="text-center" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="checkbox" id="propietario_vehiculo" name="propietario_vehiculo" class="tipo_actividad" style=" transform: scale(1.2);">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Propietario Vehículo</th>
                <td class="text-center" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="checkbox" id="propietario_trailer" name="propietario_trailer" class="tipo_actividad" style=" transform: scale(1.2);">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Propietario Trailer</th>
                <td class="text-center" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="checkbox" id="Proveedor" name="Proveedor" class="tipo_actividad" style=" transform: scale(1.2);">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Proveedor</th>
              </tr>
            </thead>
          </table>
          <div id="tbl_detalle_proveedor" style="display: none;">
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="celda_titulo2" style="margin:25px;">
                    <b>Detalle Proveedor</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #BDBDBD;color:#000000;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-center" style="margin:25px;">
                    <b>Tipo de proveedor</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
              <thead>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Nacional:</th>
                  <td class="text-center" style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input class="tipo_proveedor" id="nacional" type="radio" name="tipo_proveedor" value="1">
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Internacional:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" class="text-center">
                    <input class="tipo_proveedor" id="internacional" type="radio" name="tipo_proveedor" value="2">
                  </td>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Localización operacional:</th>
                  <td class="text-center" style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <select id="pv_localizacion" class="text-center" style="width: 100%;">
                    </select>
                  </td>
                </tr>
                <tr class="zona" style="display: none;">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Zona:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="8">
                    <input type="text" id="pv_zona" style="width: 100%;">
                  </td>
                </tr>
                <tr>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Tipo de servicio:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="8">
                    <select id="pv_tiposervice" style="width: 100%;">
                      <option value="">Seleccione</option>
                      <option value="Transporte">Transporte</option>
                      <option value="Porteadores">Porteadores</option>
                      <option value="Adecuaciones">Adecuaciones</option>
                      <option value="Aduana">Aduana</option>
                      <option value="Impuestos">Impuestos</option>
                      <option value="Agenciamiento de carga">Agenciamiento de carga</option>
                      <option value="Tramites operativos">Trámites operativos</option>
                      <option value="Tramites administrativos">Trámites administrativos</option>
                    </select>
                  </td>
                </tr>
                <tr>
                  <td class="celda_titulo2" style="margin:25px;background-color: #332D2D;color:#fff;border-top: 1px #fff solid;" colspan="8">
                    <b id="titulo_tservice"></b>
                  </td>
                </tr>
                <tr id="Transporte" style="display: none;">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px;width: auto; white-space: nowrap;">Vía:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="3">
                    <select id="pv_via" style="width: 100%;">
                      <option value="">Seleccione</option>
                      <option value="Aerea">Aerea</option>
                      <option value="Maritima">Maritima</option>
                      <option value="Terrestre">Terrestre</option>
                    </select>
                  </td>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px;width: auto; white-space: nowrap;">Tipificación:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="3">
                    <select id="pv_select" style="width: 100%;"></select>
                  </td>
                </tr>
                <tr id="porteadores" style="display: none;">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px;width: auto; white-space: nowrap;">Detalle:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="7">
                    <select id="detalle_porteador" style="width: 100%;">
                      <option value="">Seleccione</option>
                      <option value="Puertos">Puertos</option>
                      <option value="Aeropuertos">Aeropuertos</option>
                      <option value="Entes regulatorios">Entes regulatorios</option>
                      <option value="Trámites en frontera">Trámites en frontera</option>
                    </select>
                  </td>
                </tr>
                <tr id="agencia_carga" style="display: none;">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px;width: auto; white-space: nowrap;">Detalle:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="7">
                    <select id="detalle_acarga" style="width: 100%;">
                      <option value="">Seleccione</option>
                      <option value="Agente de carga">Agente de carga</option>
                      <option value="Consolidador neutral">Consolidador neutral</option>
                    </select>
                  </td>
                </tr>
                <tr id="tramite_admin" style="display: none;">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px;width: auto; white-space: nowrap;">Trámites Administrativos:</th>
                  <select id="detalle_acarga" style="width: 100%;">
                    <option value="">Seleccione</option>
                    <option value="Agente de carga">Agente de carga</option>
                    <option value="Consolidador neutral">Consolidador neutral</option>
                  </select>
                </tr>
              </thead>
            </table>
          </div>
          <!-- Datos generales -->
          <div id="tbl_datos_generales" style="display: none;">
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="celda_titulo2" style="margin:25px;">
                    <b>Datos Generales</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #BDBDBD;color:#fff;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-center" style="margin:25px;">
                    <b>Aplica solo para conductor <span class="text-primary">(*)</span></b>
                  </td>
                </tr>
              </tbody>
            </table>
            <div class="row">
              <div class="col-md-11" style="float: right;padding-left: 1px;">
                <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
                  <thead>
                    <!-- <tr id="tr_foto">
                    <td colspan="9" class="text-center"><img id="foto_proveedor" style="width: 120px;height: 120px;margin-top: 5px;margin-bottom: 5px;border-radius: 2px;"></td>
                  </tr> -->
                    <tr>
                      <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Tipo de documento:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                      <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;margin: 0;">
                        <select id="tipo_documento" style="width: 100%;">
                          <option value="" disabled="disabled" selected="selected">Seleccione un tipo de documento</option>
                          <option value="NIT">NIT</option>
                          <option value="Cedula de Ciudadania">Cédula de Ciudadanía</option>
                          <option value="Cedula de Extranjeria">Cédula de Extranjería</option>
                          <option value="Identificacion Tributaria Internacional">Identificación Tributaria Internacional </option>
                        </select>
                      </td>
                      <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Número de documento:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                      <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;margin: 0; ">
                        <input type="number" id="numero_documento" placeholder="Número de documento" style="width: 100%;">
                      </td>
                      <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Dígito verific.:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                      <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                        <input type="number" id="digito_verificacion" placeholder="Dígito de verificación" readonly="readonly" style="width: 100%;background-color: #E0E0E0;">
                      </td>
                    </tr>
                    <tr>
                      <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Nombre o Razón social:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                      <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                        <input type="text" id="rndc_nombre" placeholder="Nombre o Razón social" onblur="mayuscula(this);" style="width: 100%;">
                        <input type="hidden" id="nombre" readonly="readonly">
                      </td>
                      <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Primer Apellido:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                      <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                        <input type="text" id="primer_apellido" placeholder="Primer Apellido" onblur="mayuscula(this);" style="width: 100%;">
                      </td>
                      <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Segundo Apellido:</th>
                      <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                        <input type="text" id="segundo_apellido" placeholder="Segundo Apellido" onblur="mayuscula(this);" style="width: 100%;">
                      </td>
                    </tr>
                    <tr>
                      <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Abreviatura:</th>
                      <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                        <input type="text" id="abreviatura" placeholder="Abreviatura" style="width: 100%;" onblur="mayuscula(this);">
                      </td>
                      <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Teléfono Fijo Contacto:</th>
                      <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                        <input type="text" id="contacto" placeholder="Teléfono Contacto" maxlength="7" style="width: 100%;">
                      </td>
                      <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Celular Contacto 1:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                      <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                        <input type="text" id="celular" placeholder="Celular Contacto" maxlength="10" minlength="10" style="width: 100%;height: auto;">
                      </td>
                    </tr>
                    <tr>
                      <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Celular Contacto 2:&nbsp;<span style="color:blue;"><i><strong>(*)</strong></i></span></th>
                      <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                        <input type="text" id="celular2" placeholder="Celular Contacto" maxlength="10" minlength="10" style="width: 100%;">
                      </td>
                      <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Correo electrónico:</th>
                      <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                        <input type="email" id="email" placeholder="Correo electrónico" style="width: 100%;">
                        <!-- <label id="error_email"></label> -->
                      </td>
                      <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Municipio:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                      <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        <div class="input-group">
                          <input type="text" id="municipio_tabla" placeholder="Municipio" style="width: 100%;" onblur="mayuscula(this);" readonly="readonly">
                          <span class="input-group-btn">
                            <button class="btn-success btn-xs" type="button" data-toggle="modal" data-target="#Modal_Municipios"><i class="fas fa-globe-europe"></i></button>
                          </span>
                          <input type="hidden" id="id_municipio">
                          <input type="hidden" id="rndc_id_municipio">
                          <label id="error_municipio"></label>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Dirección:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                      <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                        <div class="input-group">
                          <input type="text" id="direccion" placeholder="Dirección" style="width: 100%;" onblur="mayuscula(this);" readonly="readonly">
                          <!-- <label id="error_direccion"></label> -->
                          <span class="input-group-btn">
                            <button class="btn-success btn-xs" type="button" data-toggle="modal" data-target=".Modal_direcciones"><i class="fas fa-street-view"></i></button>
                          </span>
                        </div>
                      </td>
                      <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Tipo de identificación:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                      <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                        <select id="tipo_identificacion" disabled style="background-color: #BDBDBD;width: 100%;">
                          <option value="">Seleccione un tipo de identificación</option>
                          <option value="31">31</option>
                          <option value="13">13</option>
                          <option value="22">22</option>
                        </select>
                      </td>
                      <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Estado:</th>
                      <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                        <select id="estado" style="width: 100%;">
                          <option value="Activo">Activo</option>
                          <option value="Inactivo">Inactivo</option>
                        </select>
                        <label id="error_estado"></label>
                      </td>
                    </tr>
                    <tr>
                      <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Sexo:</th>
                      <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        <select id="sexo" style="width: 100%;">
                          <option value="">Seleccione</option>
                          <option value="Femenino">Femenino</option>
                          <option value="Masculino">Masculino</option>
                          <option value="Otro">Otro</option>
                        </select>
                      </td>
                      <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Documento identificación:&nbsp;<span style="color:blue;"><i>(*)</i></span></th>
                      <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        <input type="file" name="file-2" id="documentos" onchange="docu_identificable(this.value)" data-multiple-caption="{count} archivos seleccionados" style="width: 100%;">
                      </td>
                      <input type="hidden" id="docu_soporte" style="width: 100%;" readonly="readonly">
                      <input type="hidden" id="namedocu">
                      <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                        Documento:</th>
                      <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" id="documento">
                        <!-- <button class="btn btn-primary btn-xs" style="width: 100%;height: 100%;" id="btn_documento"><i class="fas fa-file-pdf"></i> Cedula Conductor</button> -->
                      </td>
                    </tr>
                  </thead>
                </table>
              </div>
              <div class="col-md-1" style="padding: 1px 1px 1px 15px;" id="fotos_proveedor"></div>
            </div>

          </div>
          <table id="tbl_datos_conductor" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;display: none;">
            <tbody>
              <tr>
                <td class="text-left" style="margin:25px;">
                  <b>Datos del conductor</b>
                </td>
              </tr>
              <tr>
              </tr>
            </tbody>
          </table>
          <div id="datos_conductor"></div>
          <table id="tbl_datos_financieros" cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;display: none;">
            <tbody>
              <tr>
                <td class="text-left" style="margin:25px;">
                  <b>Datos Financieros</b>
                </td>
              </tr>
              <tr>
              </tr>
            </tbody>
          </table>
          <div id="datos_financieros"></div>
          <!-- Datos del conductor -->
          <div id="tbl_datos_especificos" style="display: none;">
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-left" style="margin:25px;">
                    <b>Datos Especificos</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #BDBDBD;color:#000000;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-center" style="margin:25px;">
                    <b>Referencias empresariales</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #E0E0E0;color:#fff;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-left" style="margin:25px;">
                    <b class="text-info">Empresa N° 1</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
              <thead>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Nombre Empresa:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input style="width: 100%;" id="referencias_empresariales1" onblur="mayuscula(this);">
                    <label id="error_referencias_empresariales"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Fecha Ingreso:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="date" id="fecha_referencia1" style="width: 100%;">
                    <label id="error_fecha_empresarial1"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Fecha Retiro:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="date" id="fecha_retiro1" style="width: 100%;">
                    <label id="error_fecha_empresarial1"></label>
                  </td>
                </tr>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Persona Contacto:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="text" id="contacto_ref1" placeholder="Nombre Contacto" style="width: 100%;" onblur="mayuscula(this);">
                    <label id="error_contacto"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Celular Empresa:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="int" id="celular_ref1" placeholder="Celular Empresa" maxlength="10" style="width: 100%;">
                    <label id="error_celularref1"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Cargo:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="text" id="cargo_ref1" placeholder="Cargo" style="width: 100%;" onblur="mayuscula(this);">
                    <label id="error_cargo"></label>
                  </td>
                </tr>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Antiguedad:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="number" id="anti_ref1" min="0" placeholder="Antiguedad" style="width: 100%;">
                    <label id="error_antig"></label>
                  </td>
                  <input type="hidden" id="idp1" class="form-control input-sm" disabled="">
                </tr>
              </thead>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #E0E0E0;color:#fff;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-left" style="margin:25px;">
                    <b class="text-info">Empresa N° 2</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
              <thead>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Nombre Empresa:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="text" style="width: 100%;" id="referencias_empresariales2" onblur="mayuscula(this);">
                    <label id="error_referencia_empresarial2"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Fecha Ingreso:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="date" id="fecha_referencia2" style="width: 100%;">
                    <label id="error_fecha_empresarial2"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Fecha Retiro:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="date" id="fecha_retiro2" style="width: 100%;">
                    <label id="error_fecha_empresarial1"></label>
                  </td>
                </tr>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Persona Contacto:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="text" id="contacto_ref2" placeholder="Nombre Contacto" style="width: 100%;" onblur="mayuscula(this);">
                    <label id="error_contacto"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Celular Empresa:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="int" id="celular_ref2" placeholder="Celular Empresa" maxlength="10" style="width: 100%;">
                    <label id="error_celularref1"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Cargo :</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="text" id="cargo_ref2" placeholder="Cargo" style="width: 100%;" onblur="mayuscula(this);">
                    <label id="error_cargo"></label>
                  </td>
                </tr>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Antiguedad:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="number" id="anti_ref2" min="0" placeholder="Antiguedad" style="width: 100%;">
                    <label id="error_antig"></label>
                  </td>
                  <input type="hidden" id="idp2" class="form-control input-sm" disabled="">
                </tr>
              </thead>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #E0E0E0;color:#fff;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-left" style="margin:25px;">
                    <b class="text-info">Empresa N° 3</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
              <thead>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Nombre Empresa:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="text" style="width: 100%;" id="referencias_empresariales3" onblur="mayuscula(this);">
                    <label id="error_referencia_empresarial3"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Fecha Ingreso:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="date" id="fecha_referencia3" style="width: 100%;" readonly=”readonly”>
                    <label id="error_fecha_empresarial3"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Fecha Retiro:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="date" id="fecha_retiro3" style="width: 100%;">
                    <label id="error_fecha_empresarial3"></label>
                  </td>
                </tr>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Persona Contacto:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="text" id="contacto_ref3" placeholder="Nombre Contacto" style="width: 100%;" onblur="mayuscula(this);">
                    <label id="error_contacto"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Celular Empresa:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="int" id="celular_ref3" placeholder="Celular Empresa" maxlength="10" style="width: 100%;">
                    <label id="error_celularref3"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Cargo:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="text" id="cargo_ref3" placeholder="Cargo" style="width: 100%;" onblur="mayuscula(this);">
                    <label id="error_cargo3"></label>
                  </td>
                </tr>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Antiguedad:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="number" id="anti_ref3" min="0" placeholder="Antiguedad" style="width: 100%;">
                    <label id="error_antig"></label>
                  </td>
                  <input type="hidden" id="idp3" class="form-control input-sm" disabled="">
                </tr>
              </thead>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #BDBDBD;color:#000;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-center" style="margin:25px;">
                    <b>Contacto en caso de emergencia</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #E0E0E0;color:#fff;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-left" style="margin:25px;">
                    <b class="text-info">Contacto 1</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
              <thead>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Nombre:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input style="width: 100%;" id="referencias_personales1" onblur="mayuscula(this);">
                    <label id="error_referencias_personales"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Fecha:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="date" id="fecha_personal1" style="width: 100%;" readonly=”readonly”>
                    <label id="error_referencias_personales1"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Parentesco:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <select style="width: 100%;" id="parenp1">
                      <option value="" readonly="readonly">Seleccione parentesco</option>
                      <option value="1">Amigo/a</option>
                      <option value="2">Hermano/a</option>
                      <option value="3">Padre</option>
                      <option value="4">Madre</option>
                      <option value="5">Tio/a</option>
                      <option value="6">Sobrino/a</option>
                      <option value="7">Hijo/a</option>
                      <option value="8">Esposo/a</option>
                    </select>
                    <label id="error_referencias_personales"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Teléfono:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="number" id="telefonop1" min="0" style="width: 100%;">
                    <label id="error_referencias_personales"></label>
                    <input type="hidden" name="ref_id" id="ref_id1">
                  </td>
                </tr>
              </thead>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #BDBDBD;color:#000;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-center" style="margin:25px;">
                    <b>Referencia Personal</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #E0E0E0;color:#fff;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-left" style="margin:25px;">
                    <b class="text-info">Contacto 2</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
              <thead>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Nombre:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="text" style="width: 100%;" id="referencias_personales2" onblur="mayuscula(this);">
                    <label id="error_referencias_personales"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Fecha:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="date" id="fecha_personal2" style="width: 100%;">
                    <label id="error_referencias_personales"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Parentesco:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <select style="width: 100%;" id="parenp2">
                      <option value="" readonly="readonly">Seleccione parentesco</option>
                      <option value="1">Amigo/a</option>
                      <option value="2">Hermano/a</option>
                      <option value="3">Padre</option>
                      <option value="4">Madre</option>
                      <option value="5">Tio/a</option>
                      <option value="6">Sobrino/a</option>
                      <option value="7">Hijo/a</option>
                      <option value="8">Esposo/a</option>
                    </select>
                    <label id="error_referencias_personales"></label>
                  </td>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Teléfono:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="number" id="telefonop2" min="0" style="width: 100%;">
                    <label id="error_referencias_personales"></label>
                    <input type="hidden" name="ref_id2" id="ref_id2">
                  </td>
                </tr>
              </thead>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #BDBDBD;color:#000;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-center" style="margin:25px;">
                    <b>Planilla de seguridad social</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
              <thead>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Certificado de planilla seguridad social:&nbsp;<span style="color:red;"><i>(*)</i></span> </th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="file" name="file-2" id="docu_eps" onchange="eps(this.value)" data-multiple-caption="{count} archivos seleccionados" multiple style="width: 100%;">
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Fecha vencimiento plan seguridad social:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="date" id="vence_eps" style="width: 100%;">
                    <label id="error_feps"></label>
                  </td>
                  <input type="hidden" id="namedocu_eps" style="width: 100%;" disabled="">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Documento:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" id="documento_seguridad_social"></td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Estado:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" id="estado_seguridad_social"></td>
                </tr>
              </thead>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #BDBDBD;color:#000;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-center" style="margin:25px;">
                    <b>Cursos Mercancias Peligrosas</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
              <thead>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Certificado del Curso:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="file" name="file-2" id="docu_curso" onchange="curso(this.value)" data-multiple-caption="{count} archivos seleccionados" multiple style="width: 100%;">
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Fecha Vencimiento:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                    <input type="date" id="vence_curso" style="width: 100%;">
                    <label id="error_nom_enti"></label>
                  </td>
                  <input type="hidden" id="namedocu_curso" style="width: 100%;" disabled="">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Documento:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" id="documento_mercancias_peligrosas"></td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Estado:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" id="estado_mercancias_peligrosas"></td>
                </tr>
              </thead>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #BDBDBD;color:#000;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-center" style="margin:25px;">
                    <b>Fotos del Conductor</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
              <thead>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Foto Frontal(1):&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="file" name="file-2" id="foto_conductor" onchange="name_fontal(this.value)" data-multiple-caption="{count} archivos seleccionados" style="width: 100%;" accept="image/*">
                  </td>
                  <input type="hidden" id="name_fontall" style="width: 100%;" readonly="readonly">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Documento Frontal:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" id="foto_frontal">
                    <!-- <input type="text" id="name_fontall" style="width: 100%;" readonly="readonly"> -->
                    <!-- <button class="btn btn-primary btn-xs" style="width: 100%;height: 100%;" id="btn_foto_conductor1"><i class="fa-regular fa-image"></i> Foto Frontal</button> -->
                  </td>
                </tr>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Foto lateral derecho(1):&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="file" name="file-2" id="foto_derecha" onchange="name_derecho(this.value)" data-multiple-caption="{count} archivos seleccionados" style="width: 100%;" accept="image/*">
                  </td>
                  <input type="hidden" id="name_derecha" style="width: 100%;" readonly="readonly">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Documento Derecha:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" id="foto_frontal_derecha">
                    <!-- <button class="btn btn-primary btn-xs" style="width: 100%;height: 100%;" id="btn_foto_conductor2"><i class="fa-regular fa-image"></i> Foto Derecha</button> -->
                  </td>
                </tr>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Foto lateral izquierdo(1):&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="file" name="file-2" id="foto_izquierda" onchange="name_izquierdo(this.value)" data-multiple-caption="{count} archivos seleccionados" style="width: 100%;" accept="image/*">
                  </td>
                  <input type="hidden" id="name_izquierda" style="width: 100%;" readonly="readonly">
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Documento Izquierda:</th>
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" id="foto_frontal_izquierda">
                    <!-- <button class="btn btn-primary btn-xs" style="width: 100%;height: 100%;" id="btn_foto_conductor3"><i class="fa-regular fa-image"></i> Foto Izquierda</button> -->
                  </td>
                </tr>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Foto:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="file" name="file-2" id="foto_indume" onchange="name_indu(this.value)" data-multiple-caption="{count} archivos seleccionados" style="width: 100%;" accept="image/*">
                    <!-- <label id="error_foto_indume"></label> -->
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Documento Indumentaria:</th>
                  <input type="hidden" id="name_indum" style="width: 100%;" readonly="readonly">
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" id="foto_indumentaria">
                    <!-- <button class="btn btn-primary btn-xs" style="width: 100%;height: 100%;" id="btn_foto_conductor4"><i class="fa-regular fa-image"></i> Foto Indumentaria</button> -->
                  </td>
                </tr>
              </thead>
            </table>
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #BDBDBD;color:#000;border-top: 1px #fff solid;">
              <tbody>
                <tr>
                  <td class="text-center" style="margin:25px;">
                    <b>Acuerdo de seguridad</b>
                  </td>
                </tr>
                <tr>
                </tr>
              </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
              <thead>
                <tr>
                  <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Documento 1&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                  <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                    <input type="file" name="file-2" id="acuerdo_uno" onchange="acuerdo_uno(this.value)" data-multiple-caption="{count} archivos seleccionados" style="width: 100%;">
                    <!-- <label id="error_foto_indume"></label> -->
                  </td>
                  <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                    Acuerdo de Mercancias:</th>
                  <input type="hidden" id="name_a1" style="width: 100%;" readonly="readonly">
                  <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" id="foto_acuerdo">
                    <!-- <button class="btn btn-primary btn-xs" style="width: 100%;height: 100%;" id="btn_curso_mercancia"><i class="fa-regular fa-image"></i> Foto Mercancias peligrosas</button> -->
                  </td>
                </tr>
              </thead>
            </table>
          </div>
          <div class="text-center">
            <div class="btn-group" role="group" aria-label="..." style="margin-top: 15px;margin-bottom: 15px;">
              <button type="button" class="btn btn-success btn-xs" id="btn_editar_proveedornew" style="margin-right: 10px;"><i class="far fa-save"></i> Actualizar Proveedor</button>
              <button type="button" class="btn btn-danger btn-xs" id="btn_cancelar_registro"><i class="fas fa-times-circle"></i> Cancelar</button>
            </div>
          </div>
        </div>

      </div>
    </div>
  <?php endif; ?>

</div>

<!-- Modal para agregar la direccion -->
<div class="modal fade Modal_direcciones" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel" data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:left;height: 50px;padding:19px;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #ffffff;"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="gridSystemModalLabel" style="font-weight: bold;"><i class="fas fa-map-signs"></i> Direccion Tercero</h4>
      </div>
      <div class="modal-body" style="padding: 1px 1px 1px;">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><!-- id="div_mascara" -->
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="border-bottom: 1px #E0E0E0 solid;border-top: 1px #E0E0E0 solid;">
              <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" style="margin-top: 10px;">
                <label><strong>Generador Dirección</strong></label>
              </div>
              <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <div class="be-checkbox inline">
                  <input type="checkbox" id="Complement" class="form-control input-sm comple_direc">
                  <label for="Complement">¿Complemento?</label>
                </div>
              </div>
              <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 text-right" style="margin-top: 10px;">
                <button id="limpiar" class="btn btn-xs btn-danger"><i class="far fa-trash-alt"></i> Limpiar</button>
              </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="border-bottom: 1px #E0E0E0 solid;">
              <div class="col-sm-3" style="margin-top: 10px;margin-bottom: 10px;">
                <label><strong>Tipo vía:(*)</strong></label>
                <select id="di_tipovia" class="form-control input-xs address">
                  <option value="">Seleccione</option>
                  <option value="AC">AC Avenida calle</option>
                  <option value="AD">AD Administración</option>
                  <option value="ADL">ADL Adelante</option>
                  <option value="AER">AER Aeropuerto</option>
                  <option value="AG">AG Agencia</option>
                  <option value="AGP">AGP Agrupación</option>
                  <option value="AK">AK Avenida carrera</option>
                  <option value="AL">AL Altillo</option>
                  <option value="ALD">ALD Al lado</option>
                  <option value="ALM">ALM Almacén</option>
                  <option value="AP">AP Apartamento</option>
                  <option value="APTDO">APTDO Apartado</option>
                  <option value="ATR">ATR Atrás</option>
                  <option value="AUT">AUT Autopista</option>
                  <option value="AV">AV Avenida</option>
                  <option value="AVIAL">AVIAL Anillo vial</option>
                  <option value="BG">BG Bodega</option>
                  <option value="BL">BL Bloque</option>
                  <option value="BLV">BLV Boulevard</option>
                  <option value="BR">BR Barrio</option>
                  <option value="C">C Corregimiento</option>
                  <option value="CA">CA Casa</option>
                  <option value="CAS">CAS Caserío</option>
                  <option value="CC">CC Centro comercial</option>
                  <option value="CD">CD Ciudadela</option>
                  <option value="CEL">CEL Célula</option>
                  <option value="CEN">CEN Centro</option>
                  <option value="CIR">CIR Circular</option>
                  <option value="CL">CL Calle</option>
                  <option value="CLJ">CLJ Callejón</option>
                  <option value="CN">CN Camino</option>
                  <option value="CON">CON Conjunto residencial</option>
                  <option value="CONJ">CONJ Conjunto</option>
                  <option value="CR">CR Carrera</option>
                  <option value="CRT">CRT Carretera</option>
                  <option value="CRV">CRV Circunvalar</option>
                  <option value="CS">CS Consultorio</option>
                  <option value="DG">DG Diagonal</option>DG Diagonal
                  <option value="DP">DP Depósito</option>
                  <option value="DPTO">DPTO Departamento</option>
                  <option value="DS">DS Depósito sótano</option>
                  <option value="ED">ED Edificio</option>
                  <option value="EN">EN Entrada</option>
                  <option value="ES">ES Escalera</option>
                  <option value="ESQ">ESQ Esquina</option>
                  <option value="ESTE">ESTE Este</option>
                  <option value="ET">ET Etapa</option>
                  <option value="EX">EX Exterior</option>
                  <option value="FCA">FCA Finca</option>
                  <option value="GJ">GJ Garaje</option>
                  <option value="GS">GS Garaje sótano</option>
                  <option value="GT">GT Glorieta</option>
                  <option value="HC">HC Hacienda</option>
                  <option value="HG">HG Hangar</option>
                  <option value="IN">IN Interior</option>
                  <option value="IP">IP Inspección de Policía</option>
                  <option value="IPD">IPD Inspección Departamental</option>
                  <option value="IPM">IPM Inspección Municipal</option>
                  <option value="KM">KM Kilómetro</option>
                  <option value="LC">LC Local</option>
                  <option value="LM">LM Local mezzanine</option>
                  <option value="LT">LT Lote</option>
                  <option value="MD">MD Módulo</option>
                  <option value="MJ">MJ Mojón</option>
                  <option value="MLL">MLL Muelle</option>
                  <option value="MN">MN Mezzanine</option>
                  <option value="MZ">MZ Manzana</option>
                  <option value="NOMBRE VIA">NOMBRE VIA Vías de nombre común</option>
                  <option value="NORTE">NORTE Norte</option>
                  <option value="O">O Oriente</option>
                  <option value="OCC">OCC Occidente</option>
                  <option value="OESTE">OESTE Oeste</option>
                  <option value="OF">OF Oficina</option>
                  <option value="P">P Piso</option>
                  <option value="PA">PA Parcela</option>
                  <option value="PAR">PAR Parque</option>
                  <option value="PD">PD Predio</option>
                  <option value="PH">PH Penthouse</option>
                  <option value="PJ">PJ Pasaje</option>
                  <option value="PL">PL Planta</option>
                  <option value="PN">PN Puente</option>
                  <option value="POR">POR Portería</option>
                  <option value="POS">POS Poste</option>
                  <option value="PQ">PQ Parqueadero</option>
                  <option value="PRJ">PRJ Paraje</option>
                  <option value="PS">PS Paseo</option>
                  <option value="PT">PT Puesto</option>
                  <option value="PW">PW Park Way</option>
                  <option value="RP">RP Round Point</option>
                  <option value="SA">SA Salón</option>
                  <option value="SC">SC Salón comunal</option>
                  <option value="SD">SD Salida</option>
                  <option value="SEC">SEC Sector</option>
                  <option value="SL">SL Solar</option>
                  <option value="SM">SM Súper manzana</option>
                  <option value="SS">SS Semisótano</option>
                  <option value="ST">ST Sótano</option>
                  <option value="SUITE">SUITE Suite</option>
                  <option value="SUR">SUR Sur</option>
                  <option value="TER">TER Terminal</option>
                  <option value="TERPLN">TERPLN Terraplén</option>
                  <option value="TO">TO Torre</option>
                  <option value="TV">TV Transversal</option>
                  <option value="TZ">TZ Terraza</option>
                  <option value="UN">UN Unidad</option>
                  <option value="UR">UR Unidad residencial</option>
                  <option value="URB">URB Urbanización</option>
                  <option value="VRD">VRD Vereda</option>
                  <option value="VTE">VTE Variante</option>
                  <option value="ZF">ZF Zona franca</option>
                  <option value="ZN">ZN Zona</option>
                </select>
              </div>
              <div class="col-sm-3" style="margin-top: 10px;margin-bottom: 10px;">
                <label><strong>Nombre/Núm de vía:(*)</strong></label>
                <input type="text" id="di_nomvia" class="form-control input-xs address">
              </div>
              <div class="col-sm-3" style="margin-top: 10px;margin-bottom: 10px;">
                <label><strong>Letra:</strong></label><br>
                <select id="di_letra1" class="form-control input-xs address">
                  <option value="">Seleccione</option>
                  <option value="A">A</option>
                  <option valu="B">B</option>
                  <option value="C">C</option>
                  <option value="D">D</option>
                  <option value="E">E</option>
                  <option value="F">F</option>
                  <option value="G">G</option>
                  <option value="H">H</option>
                  <option value="I">I</option>
                  <option value="J">J</option>
                  <option value="K">K</option>
                  <option value="L">L</option>
                  <option value="M">M</option>
                  <option value="N">N</option>
                  <option value="O">O</option>
                  <option value="P">P</option>
                  <option value="Q">Q</option>
                  <option value="R">R</option>
                  <option value="S">S</option>
                  <option value="T">T</option>
                  <option value="U">U</option>
                  <option value="V">V</option>
                  <option value="W">W</option>
                  <option value="X">X</option>
                  <option value="Y">Y</option>
                  <option value="Z">Z</option>
                </select>
              </div>
              <div class="col-sm-3" style="margin-top: 10px;margin-bottom: 10px;">
                <label><strong>Prefijo:</strong></label>
                <select id="di_prefijo1" class="form-control input-xs address">
                  <option value="">Seleccione</option>
                  <option value="BIS">BIS</option>
                </select>
              </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="border-bottom: 1px #E0E0E0 solid;">
              <div class="col-sm-4" style="margin-top: 10px;margin-bottom: 10px;">
                <label><strong>Letra:</strong></label>
                <select id="di_letra2" class="form-control input-xs address" style="margin-bottom: 10px;">
                  <option value="">Seleccione</option>
                  <option value="A">A</option>
                  <option valu="B">B</option>
                  <option value="C">C</option>
                  <option value="D">D</option>
                  <option value="E">E</option>
                  <option value="F">F</option>
                  <option value="G">G</option>
                  <option value="H">H</option>
                  <option value="I">I</option>
                  <option value="J">J</option>
                  <option value="K">K</option>
                  <option value="L">L</option>
                  <option value="M">M</option>
                  <option value="N">N</option>
                  <option value="O">O</option>
                  <option value="P">P</option>
                  <option value="Q">Q</option>
                  <option value="R">R</option>
                  <option value="S">S</option>
                  <option value="T">T</option>
                  <option value="U">U</option>
                  <option value="V">V</option>
                  <option value="W">W</option>
                  <option value="X">X</option>
                  <option value="Y">Y</option>
                  <option value="Z">Z</option>
                </select>
              </div>
              <div class="col-sm-4" style="margin-top: 10px;margin-bottom: 10px;">
                <label><strong>Cuadrante</strong></label>
                <select id="di_cuadrante" class="form-control input-xs address" style="margin-bottom: 10px;">
                  <option value="">Seleccione</option>
                  <option value="Norte">Norte</option>
                  <option value="Sur">Sur</option>
                  <option value="Este">Este</option>
                  <option value="Oeste">Oeste</option>
                </select>
              </div>
              <div class="col-xs-4 col-sm-4 col-md-4" style="margin-top: 10px;margin-bottom: 10px;">
                <label><strong>Número</strong></label>
                <input type="number" id="di_num1" class="form-control input-xs address" style="margin-bottom: 10px;">
              </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="border-bottom: 1px #E0E0E0 solid;">
              <div class="col-xs-4 col-sm-4 col-md-4" style="margin-top: 10px;margin-bottom: 10px;">
                <label><strong>Letra</strong></label>
                <select id="di_letra3" class="form-control input-xs address">
                  <option value="">Seleccione</option>
                  <option value="A">A</option>
                  <option valu="B">B</option>
                  <option value="C">C</option>
                  <option value="D">D</option>
                  <option value="E">E</option>
                  <option value="F">F</option>
                  <option value="G">G</option>
                  <option value="H">H</option>
                  <option value="I">I</option>
                  <option value="J">J</option>
                  <option value="K">K</option>
                  <option value="L">L</option>
                  <option value="M">M</option>
                  <option value="N">N</option>
                  <option value="O">O</option>
                  <option value="P">P</option>
                  <option value="Q">Q</option>
                  <option value="R">R</option>
                  <option value="S">S</option>
                  <option value="T">T</option>
                  <option value="U">U</option>
                  <option value="V">V</option>
                  <option value="W">W</option>
                  <option value="X">X</option>
                  <option value="Y">Y</option>
                  <option value="Z">Z</option>
                </select>
              </div>
              <div class="col-sm-4" style="margin-top: 10px;margin-bottom: 10px;">
                <label><strong>Número</strong></label>
                <input type="number" id="di_numero2" class="form-control input-xs address">
              </div>
              <div class="col-sm-4" style="margin-top: 10px;margin-bottom: 10px;">
                <label><strong>Cuadrante</strong></label>
                <select id="di_cuadrante2" class="form-control input-xs address">
                  <option value="">Seleccione</option>
                  <option value="Norte">Norte</option>
                  <option value="Sur">Sur</option>
                  <option value="Este">Este</option>
                  <option value="Oeste">Oeste</option>
                </select>
              </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="div_complemento" style="margin-top: 10px;">
              <div class="col-sm-3"><label>Complemento 1</label></div>
              <div class="col-sm-4">
                <label><strong>Tipo vía</strong></label>
                <select id="di_tipovia1" class="form-control input-xs address">
                  <option value="">Seleccione</option>
                  <option value="AC">AC Avenida calle</option>
                  <option value="AD">AD Administración</option>
                  <option value="ADL">ADL Adelante</option>
                  <option value="AER">AER Aeropuerto</option>
                  <option value="AG">AG Agencia</option>
                  <option value="AGP">AGP Agrupación</option>
                  <option value="AK">AK Avenida carrera</option>
                  <option value="AL">AL Altillo</option>
                  <option value="ALD">ALD Al lado</option>
                  <option value="ALM">ALM Almacén</option>
                  <option value="AP">AP Apartamento</option>
                  <option value="APTDO">APTDO Apartado</option>
                  <option value="ATR">ATR Atrás</option>
                  <option value="AUT">AUT Autopista</option>
                  <option value="AV">AV Avenida</option>
                  <option value="AVIAL">AVIAL Anillo vial</option>
                  <option value="BG">BG Bodega</option>
                  <option value="BL">BL Bloque</option>
                  <option value="BLV">BLV Boulevard</option>
                  <option value="BR">BR Barrio</option>
                  <option value="C">C Corregimiento</option>
                  <option value="CA">CA Casa</option>
                  <option value="CAS">CAS Caserío</option>
                  <option value="CC">CC Centro comercial</option>
                  <option value="CD">CD Ciudadela</option>
                  <option value="CEL">CEL Célula</option>
                  <option value="CEN">CEN Centro</option>
                  <option value="CIR">CIR Circular</option>
                  <option value="CL">CL Calle</option>
                  <option value="CLJ">CLJ Callejón</option>
                  <option value="CN">CN Camino</option>
                  <option value="CON">CON Conjunto residencial</option>
                  <option value="CONJ">CONJ Conjunto</option>
                  <option value="CR">CR Carrera</option>
                  <option value="CRT">CRT Carretera</option>
                  <option value="CRV">CRV Circunvalar</option>
                  <option value="CS">CS Consultorio</option>
                  <option value="DG">DG Diagonal</option>DG Diagonal
                  <option value="DP">DP Depósito</option>
                  <option value="DPTO">DPTO Departamento</option>
                  <option value="DS">DS Depósito sótano</option>
                  <option value="ED">ED Edificio</option>
                  <option value="EN">EN Entrada</option>
                  <option value="ES">ES Escalera</option>
                  <option value="ESQ">ESQ Esquina</option>
                  <option value="ESTE">ESTE Este</option>
                  <option value="ET">ET Etapa</option>
                  <option value="EX">EX Exterior</option>
                  <option value="FCA">FCA Finca</option>
                  <option value="GJ">GJ Garaje</option>
                  <option value="GS">GS Garaje sótano</option>
                  <option value="GT">GT Glorieta</option>
                  <option value="HC">HC Hacienda</option>
                  <option value="HG">HG Hangar</option>
                  <option value="IN">IN Interior</option>
                  <option value="IP">IP Inspección de Policía</option>
                  <option value="IPD">IPD Inspección Departamental</option>
                  <option value="IPM">IPM Inspección Municipal</option>
                  <option value="KM">KM Kilómetro</option>
                  <option value="LC">LC Local</option>
                  <option value="LM">LM Local mezzanine</option>
                  <option value="LT">LT Lote</option>
                  <option value="MD">MD Módulo</option>
                  <option value="MJ">MJ Mojón</option>
                  <option value="MLL">MLL Muelle</option>
                  <option value="MN">MN Mezzanine</option>
                  <option value="MZ">MZ Manzana</option>
                  <option value="NOMBRE VIA">NOMBRE VIA Vías de nombre común</option>
                  <option value="NORTE">NORTE Norte</option>
                  <option value="O">O Oriente</option>
                  <option value="OCC">OCC Occidente</option>
                  <option value="OESTE">OESTE Oeste</option>
                  <option value="OF">OF Oficina</option>
                  <option value="P">P Piso</option>
                  <option value="PA">PA Parcela</option>
                  <option value="PAR">PAR Parque</option>
                  <option value="PD">PD Predio</option>
                  <option value="PH">PH Penthouse</option>
                  <option value="PJ">PJ Pasaje</option>
                  <option value="PL">PL Planta</option>
                  <option value="PN">PN Puente</option>
                  <option value="POR">POR Portería</option>
                  <option value="POS">POS Poste</option>
                  <option value="PQ">PQ Parqueadero</option>
                  <option value="PRJ">PRJ Paraje</option>
                  <option value="PS">PS Paseo</option>
                  <option value="PT">PT Puesto</option>
                  <option value="PW">PW Park Way</option>
                  <option value="RP">RP Round Point</option>
                  <option value="SA">SA Salón</option>
                  <option value="SC">SC Salón comunal</option>
                  <option value="SD">SD Salida</option>
                  <option value="SEC">SEC Sector</option>
                  <option value="SL">SL Solar</option>
                  <option value="SM">SM Súper manzana</option>
                  <option value="SS">SS Semisótano</option>
                  <option value="ST">ST Sótano</option>
                  <option value="SUITE">SUITE Suite</option>
                  <option value="SUR">SUR Sur</option>
                  <option value="TER">TER Terminal</option>
                  <option value="TERPLN">TERPLN Terraplén</option>
                  <option value="TO">TO Torre</option>
                  <option value="TV">TV Transversal</option>
                  <option value="TZ">TZ Terraza</option>
                  <option value="UN">UN Unidad</option>
                  <option value="UR">UR Unidad residencial</option>
                  <option value="URB">URB Urbanización</option>
                  <option value="VRD">VRD Vereda</option>
                  <option value="VTE">VTE Variante</option>
                  <option value="ZF">ZF Zona franca</option>
                  <option value="ZN">ZN Zona</option>
                </select>
              </div>
              <div class="col-sm-4">
                <label>
                  <strong>Número/Nombre</strong></label>
                <input type="text" id="di_numero3" class="form-control input-xs address">
              </div>

            </div>
            <div class="col-sm-12 col-md-12 col-lg-12" style="margin-top: 10px;">
              <label><strong>Dirección final</strong></label>
              <input type="text" id="direccion_compuesta" class="form-control input-xs" readonly="readonly">
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger btn-xs" data-dismiss="modal"><i class="fas fa-times-circle"></i> Crerra</button>
        <!-- <button type="button" class="btn btn-primary btn-xs"><i class="fas fa-plus-circle"></i> Guardar Dirección</button> -->
      </div>
    </div>
  </div>
</div>

<!-- Modal para agregar el municipio -->
<div class="modal fade" id="Modal_Municipios" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static">
  <div class=" modal-dialog" role="document" style="width: 500px;">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:left;height: 50px;padding:19px;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #ffffff;"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Selecccioanr Municipio</h4>
      </div>
      <div class="modal-body" style="justify-content: center;padding: 5px 5px 5px;">
        <div class="mesanje_error"></div>
        <div id="caja_municipio">
          <input type="text" class="form-control input-xs typeahead text-center" placeholder="Municipio" id="municipio" style="width: 500px;">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger btn-xs" data-dismiss="modal"><i class="fas fa-times-circle"></i> Cerrar</button>
        <button type="button" class="btn btn-primary btn-xs" id="pasar_municipio"><i class="far fa-save"></i> Guardar Municipio</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="Modal_Mensajes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static">
  <div class=" modal-dialog" role="document" style="width: 700px;">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#3B71CA;color:#fff;text-align:left;height: 40px;padding:15px;">
        <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #ffffff;"><span aria-hidden="true">&times;</span></button> -->
        <h4 class="modal-title" id="myModalLabel">Respuesta de las operaciones</h4>
      </div>
      <div class="modal-body" style="justify-content: center;padding: 5px 5px 5px;">
        <div id="contenedor"></div>
      </div>
      <div class="modal-footer" style="justify-content: center;padding: 5px 5px 5px;">
        <button type="button" class="btn btn-danger btn-xs" data-dismiss="modal" id="btn-cerrar-mensajes"><i class="fas fa-times-circle"></i> Cerrar</button>
        <!-- <button type="button" class="btn btn-primary btn-xs" id="pasar_municipio"><i class="far fa-save"></i> Guardar Municipio</button> -->
      </div>
    </div>
  </div>
</div>

<!-- Ventana modal para confirmar o cancelar operacion -->
<div class="modal fade" id="md-footer-primary" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true" data-backdrop="static">
  <!-- <div class="modal-dialog modal-sm"> -->
  <div class="modal-dialog" style="width: 500px;">
    <div class="modal-content">
      <!-- <div class="modal-header">
        <button class="close" type="button" data-dismiss="modal" aria-hidden="true"><span class="mdi mdi-close"></span></button>
      </div> -->
      <div class="modal-body">
        <div class="text-center">
          <div class="text-primary"><span class="modal-main-icon mdi mdi-info-outline"></span></div>
          <h4 id="titulo_alerta" style="font-weight: bold;">Information!</h4>
          <!-- <p id="mensaje_alerta">Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br>Fusce ultrices euismod lobortis.</p> -->
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary btn-xs" type="button" data-dismiss="modal" id="btn_aceptar"><i class="fa-solid fa-check"></i> Aceptar</button>
        <button class="btn btn-danger btn-xs" type="button" data-dismiss="modal"><i class="fa-solid fa-xmark"></i> Cancelar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="md-actualizar" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true" data-backdrop="static">
  <!-- <div class="modal-dialog modal-sm"> -->
  <div class="modal-dialog" style="width: 500px;">
    <div class="modal-content">
      <!-- <div class="modal-header">
        <button class="close" type="button" data-dismiss="modal" aria-hidden="true"><span class="mdi mdi-close"></span></button>
      </div> -->
      <div class="modal-body">
        <div class="text-center">
          <div class="text-primary"><span class="modal-main-icon mdi mdi-info-outline"></span></div>
          <h4 class="titulo_alerta" style="font-weight: bold;">Information!</h4>
          <!-- <p id="mensaje_alerta">Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br>Fusce ultrices euismod lobortis.</p> -->
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary btn-xs" type="button" data-dismiss="modal" id="btn_aceptar_actualizacion"><i class="fa-solid fa-check"></i> Aceptar</button>
        <button class="btn btn-danger btn-xs" type="button" data-dismiss="modal"><i class="fa-solid fa-xmark"></i> Cancelar</button>
      </div>
    </div>
  </div>
</div>

<!-- Mensajes para los usuarios de la plataforma -->
<div id="loading-overlay-nexosapp" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para NexosAPP...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
  </div>
</div>

<div id="loading-overlay-oet" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para Oet...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
  </div>
</div>

<div id="loading-overlay-rndc" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para Rndc...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
  </div>
</div>

<div id="loading-overlay-mensaje_carga" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos para traer los datos.</h4>
  </div>
</div>

<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/select2/js/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/js/main.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/typeahead.bundle.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>public/helpers/helpers.js" type="text/javascript"></script>
<!-- <script src="<?php echo BASE_URL; ?>views/layout/assets/lib/proveedores_ajax.js" type="text/javascript"></script> -->
<script src="<?php echo BASE_URL; ?>views/solicitudes/js/proveedores.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>public/helpers/helpers.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script type="text/javascript">
  $(document).ready(function() {
    //initialize the javascript
    App.wizard();
    App.init();
    // App.formElements();
    $("#div_complemento").hide();

    // function mayuscula(elemento) {
    //   let texto = elemento.value;
    //   elemento.value = texto.toUpperCase();
    // }
    //CONCATENA MASCARA DE DIRECCIONES
    $(".address").change(function() {
      tipovia = $("#di_tipovia").val();
      di_nomvia = $("#di_nomvia").val();
      di_letra1 = $("#di_letra1").val();
      di_prefijo1 = $("#di_prefijo1").val();
      di_letra2 = $("#di_letra2").val();
      di_cuadrante = $("#di_cuadrante").val();
      di_num1 = $("#di_num1").val();
      di_letra3 = $("#di_letra3").val();
      di_numero2 = $("#di_numero2").val();
      di_cuadrante2 = $("#di_cuadrante2").val();
      di_tipovia1 = $("#di_tipovia1").val();
      di_numero3 = $("#di_numero3").val();
      var nomenclatura = (tipovia + ' ' + di_nomvia + ' ' + di_letra1 + ' ' + di_prefijo1 + ' ' + di_letra2 + ' ' +
        di_cuadrante + ' ' + di_num1 + ' ' + di_letra3 + ' ' + di_numero2 + ' ' + di_cuadrante2 + ' ' +
        di_tipovia1 +
        ' ' + di_numero3);
      $("#direccion_compuesta").val(nomenclatura);
      $("#direccion").val(nomenclatura);
    });
    $("#Complement").change(function() {
      if ($(this).is(":checked")) {
        $("#div_complemento").show();
      } else {
        $("#div_complemento").hide();
      }
    });
    $("#limpiar").click(function() {
      $("#di_tipovia").prop('selected', 'false');
      $("#di_nomvia").val('');
      $("#di_letra1").attr('selected', 'false');
      $("#di_prefijo1").attr('selected', 'false');
      $("#di_letra2").attr('selected', 'false');
      $("#di_cuadrante").attr('selected', 'false');
      $("#di_num1").val('');
      $("#di_letra3").attr('selected', 'false');
      $("#di_numero2").val('');
      $("#di_cuadrante2").attr('selected', 'false');
      $("#di_tipovia1").attr('selected', 'false');
      $("#di_numero3").val('');
      $("#direccion_compuesta").val('');
      $("#direccion").val('');
    });

    $(".addresse").change(function() {
      tipovia = $("#di_tipoviae").val();
      di_nomvia = $("#di_nomviae").val();
      di_letra1 = $("#di_letra1e").val();
      di_prefijo1 = $("#di_prefijo1e").val();
      di_letra2 = $("#di_letra2e").val();
      di_cuadrante = $("#di_cuadrantee").val();
      di_num1 = $("#di_num1e").val();
      di_letra3 = $("#di_letra3e").val();
      di_numero2 = $("#di_numero2e").val();
      di_cuadrante2 = $("#di_cuadrantee2").val();
      di_tipovia1 = $("#di_tipovia1e").val();
      di_numero3 = $("#di_numero3e").val();
      var nomenclatura = (tipovia + ' ' + di_nomvia + ' ' + di_letra1 + ' ' + di_prefijo1 + ' ' + di_letra2 + ' ' +
        di_cuadrante + ' ' + di_num1 + ' ' + di_letra3 + ' ' + di_numero2 + ' ' + di_cuadrante2 + ' ' +
        di_tipovia1 +
        ' ' + di_numero3);
      $("#direccion_compuestae").val(nomenclatura);
      $("#e_direccion").val(nomenclatura);
    });
    $("#Complemente").change(function() {
      if ($(this).is(":checked")) {
        $("#e_complemento").show();
      } else {
        $("#e_complemento").hide();
      }
    });
    $("#limpiare").click(function() {
      $("#di_tipoviae").prop('selected', 'false');
      $("#di_nomviae").val('');
      $("#di_letra1e").prop('selected', 'false');
      $("#di_prefijo1e").prop('selected', 'false');
      $("#di_letra2e").prop('selected', 'false');
      $("#di_cuadrantee").prop('selected', 'false');
      $("#di_num1e").val('');
      $("#di_letra3e").prop('selected', 'false');
      $("#di_numero2e").val('');
      $("#di_cuadrantee2").prop('selected', 'false');
      $("#di_tipovia1e").prop('selected', 'false');
      $("#di_numero3e").val('');
      $("#direccion_compuestae").val('');
      $("#e_direccion").val('');
    });
  });

  function mayuscula(elemento) {
    let texto = elemento.value;
    elemento.value = texto.toUpperCase();
  }

  function docu_identificable(fic) {
    var input = document.getElementById("documentos"); // Reemplaza 'tuInputFile' con el ID de tu input file
    var archivo = input.files[0];

    if (archivo) {
      var nombreArchivo = archivo.name;
      var extension = nombreArchivo.split(".").pop().toLowerCase();

      var extensionesPermitidas = ["pdf"]; // Lista de extensiones permitidas

      if (extensionesPermitidas.indexOf(extension) === -1) {
        // alert("Extensión de archivo no permitida. Por favor, selecciona un archivo con una de las siguientes extensiones: " +extensionesPermitidas.join(", "),);
        $("#documentos + p").remove();
        const ERROR = $("<p></p>")
          .text("Por favor, seleccione un archivo (PDF).")
          .addClass("bg-danger text-center")
          .css({
            color: "#FFF",
            "font-size": "12px",
            margin: 0
          });
        $("#documentos").after(ERROR);
        input.value = ""; // Limpia el campo de entrada
        $("#docu_soporte").val("");
      } else {
        fic = fic.split("\\");
        if (fic == "" || fic == null) {
          $("#docu_soporte").val("");
        } else {
          $("#docu_soporte").val(fic[fic.length - 1]);
        }
      }

      // Verifica el tamaño del archivo (en este caso, máximo 1MB)
      var maxSize = 1 * 1024 * 1024; // 1MB en bytes
      if (archivo.size > maxSize) {
        $("#documentos + p").remove();
        const ERROR = $("<p></p>")
          .text("El archivo no debe superar el tamaño de 1MB.")
          .addClass("bg-danger text-center")
          .css({
            color: "#FFF",
            "font-size": "12px",
            margin: 0
          });
        $("#documentos").after(ERROR);
        $("#docu_soporte").val("");
      } else {
        $("#documentos + p").remove();
      }
    }
  }

  //TRAER NOMBRE DE LOS FICHEROS
  function docu_identificable(fic) {
    var input = document.getElementById("documentos"); // Reemplaza 'tuInputFile' con el ID de tu input file
    var archivo = input.files[0];

    if (archivo) {
      var nombreArchivo = archivo.name;
      var extension = nombreArchivo.split(".").pop().toLowerCase();

      var extensionesPermitidas = ["pdf"]; // Lista de extensiones permitidas

      if (extensionesPermitidas.indexOf(extension) === -1) {
        // alert("Extensión de archivo no permitida. Por favor, selecciona un archivo con una de las siguientes extensiones: " +extensionesPermitidas.join(", "),);
        $("#documentos + p").remove();
        const ERROR = $("<p></p>")
          .text("Por favor, seleccione un archivo (PDF).")
          .addClass("bg-danger text-center")
          .css({
            color: "#FFF",
            "font-size": "12px",
            margin: 0
          });
        $("#documentos").after(ERROR);
        input.value = ""; // Limpia el campo de entrada
        $("#docu_soporte").val("");
      } else {
        fic = fic.split("\\");
        if (fic == "" || fic == null) {
          $("#docu_soporte").val("");
        } else {
          $("#docu_soporte").val(fic[fic.length - 1]);
        }
      }

      // Verifica el tamaño del archivo (en este caso, máximo 1MB)
      var maxSize = 1 * 1024 * 1024; // 1MB en bytes
      if (archivo.size > maxSize) {
        $("#documentos + p").remove();
        const ERROR = $("<p></p>")
          .text("El archivo no debe superar el tamaño de 1MB.")
          .addClass("bg-danger text-center")
          .css({
            color: "#FFF",
            "font-size": "12px",
            margin: 0
          });
        $("#documentos").after(ERROR);
        $("#docu_soporte").val("");
      } else {
        $("#documentos + p").remove();
      }
    }
  }
  //referencia laboral1
  function lab1(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#name_soporte").val('');
    } else {
      $("#name_soporte").val(fic[fic.length - 1]);
    }
  }
  //referencia laboral2
  function lab2(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#name_soporte2").val('');
    } else {
      $("#name_soporte2").val(fic[fic.length - 1]);
    }
  }
  //referencia laboral3
  function lab3(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#name_soporte3").val('');
    } else {
      $("#name_soporte3").val(fic[fic.length - 1]);
    }
  }
  //referencias personales 1
  function per1(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#docu_personal1").val('');
    } else {
      $("#docu_personal1").val(fic[fic.length - 1]);
    }
  }
  //referencias personales 2
  function per2(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#docu_personal2").val('');
    } else {
      $("#docu_personal2").val(fic[fic.length - 1]);
    }
  }
  //EPS
  function eps(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#namedocu_eps").val('');
    } else {
      $("#namedocu_eps").val(fic[fic.length - 1]);
    }
  }
  //ARL
  function Arl(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#namedocu_arl").val('');
    } else {
      $("#namedocu_arl").val(fic[fic.length - 1]);
    }
  }
  //CURSO MERCANCIAS PELIGROSAS
  function curso(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#namedocu_curso").val('');
    } else {
      $("#namedocu_curso").val(fic[fic.length - 1]);
    }
  }
  //nombre foto frontal
  function name_fontal(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#name_fontall").val('');
    } else {
      $("#name_fontall").val(fic[fic.length - 1]);
    }
  }
  //nombre foto derecha
  function name_derecho(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#name_derecha").val('');
    } else {
      $("#name_derecha").val(fic[fic.length - 1]);
    }
  }
  //nombre foto izquierda
  function name_izquierdo(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#name_izquierda").val('');
    } else {
      $("#name_izquierda").val(fic[fic.length - 1]);
    }
  }
  //nombre foto indumentaria
  function name_indu(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#name_indum").val('');
    } else {
      $("#name_indum").val(fic[fic.length - 1]);
    }
  }
  //acuerdo 1
  function acuerdo_uno(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#name_a1").val('');
    } else {
      $("#name_a1").val(fic[fic.length - 1]);
    }
  }
  //acuerdo 2
  function acuerdo_dos(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#name_a2").val('');
    } else {
      $("#name_a2").val(fic[fic.length - 1]);
    }
  }
  //acuerdo 3
  function acuerdo_tres(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#name_a3").val('');
    } else {
      $("#name_a3").val(fic[fic.length - 1]);
    }
  }
  //acuerdo 4
  function acuerdo_cuatro(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#name_a4").val('');
    } else {
      $("#name_a4").val(fic[fic.length - 1]);
    }
  }
</script>