<?php
	$_dbTable = "ar"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	$vista = '';

	/*** SE CREA TABLA DE CONTENIDO ***/
	$tabla_contenido = '
		<div class="row" >
			<div class="col-sm-2"></div>
			<div class="col-sm-8">
				<div  class="table-responsive noSwipe">
					<table id="table1" class="table table-striped table-hover" data-page-length="50">
						<thead>
							<tr class="nexos-encabezado">
								<th style="width:5%;">#</th>
								<th style="width: 10%;">Turno</th>
								<th>Conductor</th>
								<th>Contacto</th>
								<th style="width: 10%;"></th>
							</tr>
						</thead>
						<tbody >
	';

	$arrayTurnos = $this->solicitudes->getTurnos();
	// print_r("<pre>");
	// print_r($arrayTurnos);
	// print_r("</pre>");

	if ($arrayTurnos) {
		foreach ($arrayTurnos["rowsData"] as $key => $value) {
			/********** Se valida el contenido del semáforo **********/
			$col_status = '
				<td class="nexos-txt-warning sorting_1">
					<center><span class="mdi mdi-dot-circle icon"></span></center>
				</td>
			';
			if ( $value["TURNO"] != "N/A" ) {
				$col_status = '
					<td class="nexos-txt-success sorting_1">
						<center><span class="mdi mdi-dot-circle icon"></span></center>
					</td>
				';
			}
			if ( $value["estado"] == "No aprobado" || $value["estado"] == "Rechazado" || $value["estado"] == "Cancelado" ) {
				$col_status = '
					<td class="nexos-txt-danger sorting_1">
						<center><span class="mdi mdi-dot-circle icon"></span></center>
					</td>
				';
			}
			/********** Fin - Se valida el contenido del semáforo **********/

			/********** Se valida la vista de losbotones de acción **********/
			$col_action = '
				<a href="javascript:" class="cell-detail  hint--top-left" data-hint="Ver Detalle Conductor" onclick="verDetalleTurno(' . $value["ID_PROVEEDOR"] . ')"><span class="icon mdi mdi-eye" data-toggle="modal" data-target="#ver_turno"></span></a>
				<a href="javascript:" class="cell-detail  hint--top-left" data-hint="Descartar Conductor" onclick="descartarTurno(' . $value["ID_TURNO"] . ')"><span class="icon mdi mdi-close-circle" data-toggle="modal" data-target="#descartar_turno"></span></a>
			';
			if ( $value["estado"] == "No aprobado" || $value["estado"] == "Rechazado" || $value["estado"] == "Cancelado" ) {
				$col_action = '
					<a href="javascript:" class="cell-detail  hint--top-left" data-hint="Ver Detalle Conductor" onclick="verDetalleTurno(' . $value["ID_PROVEEDOR"] . ')"><span class="icon mdi mdi-eye" data-toggle="modal" data-target="#ver_turno"></span></a>
				';
			}
			/********** Fin - Se valida la vista de losbotones de acción **********/



			$tabla_contenido.= '
				<tr>
					' . $col_status . ' 
					<td class="cell-detail">
						<span class="label label-default">' . $value["TURNO"] . '</span>
					</td>
					<td class="cell-detail">
						<span>' . $value["nombre"] . '</span>
						<span class="cell-detail-description">' . $value["estado"] . '</span>
						<span class="cell-detail-description"><strong>' . $value["observacion"] . '</strong></span>
					</td>
					<td class="cell-detail">
						<span>' . $value["contacto"] . '</span>
						<span class="cell-detail-description">' . $value["direccion"] . '</span>
					</td>
					<td class="actions">
						' . $col_action . '
					</td>
				</tr>
			';
		}
	}

	$tabla_contenido .= '
						</tbody>
					</table>
				</div>
			</div>
			<div class="col-sm-2"></div>
		</div>
	';
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Enturnamiento de Conductores
				<span class="panel-subtitle">Módulo de listado de conductores que han solicitado su enturnamiento a través del App de Conductores.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista .= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/typeahead.bundle.js" type="text/javascript" ></script>
		<script src="%root_file%lib/aprobaciones_ajax.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
		</script>

		<script async defer
			src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6vpUhRVoEe5U6m7Wh5_LFMCr_g8OzU1E&callback=initMap">
		</script>
		<script>
			var markers = [];

			function initMap(ubicacion) {
				if( ubicacion ){
					var latitud = parseFloat( ubicacion["latitud"] ) ;
					var longitud = parseFloat( ubicacion["longitud"] );

					var code = {
						lat: latitud, 
						lng: longitud
					};

					var point = new google.maps.LatLng(
						latitud,
						longitud
					);

					var mapa = new google.maps.Map(document.getElementById("mapa"), {
						zoom: 8,
						center: code,
						streetViewControl: false,
						mapTypeControl: false,
					});

					var marker = new google.maps.Marker({
						map: mapa,
						position: point
					});
				}
			}
		</script>
	';


	/****** CREACION CONTENIDO DE POPUPS ******/

	// CONTENIDO DEL POPUP DE FORMULARIO DE CREACION
	?>

	<div id="ver_turno" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
	    <div class="modal-dialog custom-width">
	        <div class="modal-content">
	            <div class="modal-header">
	                <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
	                <h3 class="modal-title" id="ver_turno_title"></h3>
	            </div>
	            <div class="modal-body" id="ver_turno_content"></div>
	            <div class="modal-footer">
	                <button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
	            </div>
	        </div>
	    </div>
	</div>

	<div id="descartar_turno" tabindex="-1" role="dialog" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" data-dismiss="modal" aria-hidden="true" class="close"><span class="mdi mdi-close"></span></button>
				</div>
				<div class="modal-body">
					<div class="text-center">
						<form id="form_rechaza_turno">
							<div class="text-danger"><span class="modal-main-icon mdi mdi-close-circle"></span></div>
							<h3>Atención!</h3>
							<p>Realmente desea descartar el conductor de este turno?</p>
							<div class="form-group col-xs-3"></div>
							<div class="form-group col-xs-6">
								<label><strong>Motivo no aprobación</strong></label>
								<textarea class="form-control" name="observacion" id="observacion"></textarea>
							</div>
							<div class="form-group col-xs-3"></div>
							<div class="row"></div>
							<div class="col-xs-12">
								<input type="hidden" name="id" id="id_turno" value="">
								<input type="hidden" name="estado" id="estado" value="No aprobado">
								<button type="button" data-dismiss="modal" class="btn btn-space btn-default">Cancelar</button>
								<button id="btn_rechaza_turno" type="button" data-dismiss="modal" class="btn btn-space btn-danger">Eliminar</button>
							</div>
						</form>
					</div>
				</div>
				<div class="modal-footer"></div>
			</div>
		</div>
	</div>

<?php
	/****** FIN CREACION CONTENIDO DE POPUPS ******/

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
	$vista = str_replace("%content%", $tabla_contenido, $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista .= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;
?>

<script type="text/javascript">
	function verDetalleTurno( id_conductor ){
		$("#ver_turno_title").html("");
		$("#ver_turno_content").html("");

		var params = {
			action		: "ver_detalle_conductor",
			id 			: id_conductor,
		};
		// console.log(params);
		$.ajax({
			url 		: $("#id_url_ajax").val() + "/libs/enturnamiento_ajax.php",
			type 		: "POST",
			data 		: params,
			dataType 	: "json",
			error		: function(data) {
				console.log(data);
			},
			success		: function(data) {
				$("#ver_turno_title").append(data.content.title);
				$("#ver_turno_content").append(data.content.body.general);
				$("#ver_turno_content").append(data.content.body.content_turno);
				initMap(data.ubicacion);
			}
		});
	}

	function descartarTurno( id_turno ){
		if ( $("#id_turno").val() != id_turno) {
			$("#observacion").val("");
		}
		$("#id_turno").val(id_turno);
	}

	$("#btn_rechaza_turno").click(function(){
		var msg_error = "";
		if ( !$("#observacion").val() ) {
			msg_error+= "<p>Debe diligenciar el campo <strong>Observación</strong> poder continuar.</p>";
		}

		if ( !msg_error ) {
			var params = {
				action		: "rechaza_turno",
				id 			: $("#id_turno").val(),
				estado		: $("#estado").val(),
				observacion : $("#observacion").val()
			};
			// console.log(params);
			$.ajax({
				url 		: $("#id_url_ajax").val() + "/libs/enturnamiento_ajax.php",
				type 		: "POST",
				data 		: params,
				dataType 	: "json",
				beforeSend	: function(jqXHR, settings){
					$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
				},
				error		: function(data) {
					console.log(data);
				},
				success		: function(data) {
					// console.log(data);
					$(".nexos-messages").hide();
					$(".nexos-messages").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong>Se ha creado el registro con éxito.</div></div>');
					$("html, body").animate({ scrollTop: 0 }, 500);
					setTimeout(function() { location.reload(false);  }, 800);
				}
			});
		}
		if( msg_error ) {
			$(".nexos-messages").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("html, body").animate({ scrollTop: 0 }, 600);
 		}
	});
</script>
