<?php
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

$table_content = '';
$vista = '';

$_GET["sw"] = "";
$_GET["placa"] = "";
$_POST["tipo"] = "";

$table_content .= "<div class='row' >
			<div class='col-sm-12'>
				<!--<div  class='table-responsive noSwipe'>				</div>
					<table id='table1' class='table table-striped table-hover' data-page-length='100'>
						<thead>-->
					<table  cellpadding='0' cellspacing='0' width='100%' border='0' style='border-top: 1px solid #FFF;' class='text-center'>
						<thead style='background-color:#332D2D;color:#fff;'>
							<tr>
								<th  class='text-center'>Placa </th>
								<th  class='text-center'>Peso Vacío (Tn)</th>
								<th  class='text-center'>Configuración </th>
								<th  class='text-center'>Propietario</th>
								<th  class='text-center'>Estado</th>
								<th  class='text-center' style='width:10%;min-width: 10%;'>acciones</th>
							</tr>
						</thead>
						<tbody>";

$arrayPermisos = $this->trailer->permisosPerfil($ssn_id_perfil, 59);
$_permisos = $arrayPermisos;


if ($_GET["sw"]) {
	$sw1 = '';
	$sw1 = $_GET["sw"];
	if ($sw1 == '1') {
		//echo 'oki doki';
		$tipo = 'placa';
		$placa = $_GET["placa"];
		//echo "<script> alert ('".$placa."');</script>";
	}
} else {
	$sw1 = 0;
	$tipo = $_POST["tipo"];
	$placa = 0;
	if (empty($_POST['placat'])) {
		//El id no existe
		$placa = '';
	} else if ($_POST['placat'] == 0) {
		// Ingresa a un menu
		$placa = $_POST['placat'];
	} else {
		// El id ya fue utilizado
		$placa = $_POST['placat'];
	}
}



$array = $this->trailer->getPrueba($tipo, $placa);
if ($array) {
	foreach ($array["rowsData"] as $key => $value) {
		$estado = $value['estado'];
		// $asig = $value['estado_solicitud'];
		$asig = $value['Estado_Asignado'];

		if ($estado == 'Activo') {
			if ($asig == 1) {
				$_col_status = '
				<td style="font-size:12px;border: 1px solid #ddd;width: auto; white-space: nowrap;" >
					<center>
					<span class="label label-danger"> Asignado</span>
					</center>
				</td>';
			}

			if ($asig == 0) {
				$_col_status = '
					<td style="font-size:12px;border: 1px solid #ddd;width: auto; white-space: nowrap;">
						<center>
						<span class="label label-success"> Disponible</span>
						</center>
					</td>';
			}
		}

		if ($estado == 'Inactivo') {
			$_col_status = '
				<td style="font-size:12px;border: 1px solid #ddd;width: auto; white-space: nowrap;">
					<center>
					<span class="label label-danger">Inactivo</span>
					</center>
				</td>';
		}

		$btneditar = '';
		if ($ssn_id_perfil != 8 && $ssn_id_perfil != 9) {
			$url = 'http' . (isset($_SERVER['HTTPS']) ? 's' : '') . '://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
			// Obtener solo la parte de la consulta de la URL
			$queryString = parse_url($url, PHP_URL_QUERY);
			// Parsear la cadena de consulta y convertirla en un array asociativo
			parse_str($queryString, $queryParams);
			// Obtener el valor del parámetro 'idmenu'
			$idmenu = isset($queryParams['idmenu']) ? $queryParams['idmenu'] : null;

			$btneditar = "<a href='" . BASE_URL . "solicitudes/editar_trailer/?num_trailer=" . base64_encode($value['numdoc_trailer']) . "&idmenu=" . $idmenu . "' class='btn btn-warning btn-xs' data-toggle='tooltip' data-placement='bottom' title='Editar trailer'><span class='icon mdi mdi-edit'></span></a>";
		}

		$btnhistorico = '';
		$btnhistorico = "
							<button type='button' class='btn btn-secondary'
							<a href='javascript:' 
							onclick='historicotrailer($value[numdoc_trailer]);'
						 class='cell-detail  hint--top-left' 
						data-hint='' '><span class='icon mdi mdi-car'  data-toggle='modal' data-target='#historicovehiculos' title='Vehículos asociados al trailer'></span></a>
							";

		$btnver = '';
		$btnver = "
						<button type='button' class='btn btn-primary'
						<a href='javascript:' 
						onclick='vertrailer($value[numdoc_trailer]);'
						 class='cell-detail  hint--top-left' 
						data-hint='' '><span class='icon mdi mdi-eye'  data-toggle='modal' data-target='#vertrailer' title='Trailer del Vehículo' ></span></a>
						</button>";

		$table_content .= '
								<tr>
								<td style="font-size:12px;border: 1px solid #ddd;width: auto; white-space: nowrap;">' . $value['placa'] . '</td>
								<td style="font-size:12px;border: 1px solid #ddd;width: auto; white-space: nowrap;">' . $value['peso_vacio'] . '</td>
								<td style="font-size:12px;border: 1px solid #ddd;width: auto; white-space: nowrap;">' . $value['nameco'] . ' ' . $value['descripcion'] . '</td>
								<td style="font-size:12px;border: 1px solid #ddd;width: auto; white-space: nowrap;">' . $value['nombre'] . $value['doc_propietario'] . '</td>
								' . $_col_status . '
								<td class="actions cell-detail" style="font-size:12px;border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
										<div class="btn-group btn-group-xs" role="group" aria-label="Extra-small button group" style="width: 100%;"> 
										' . $btneditar . '
										' . $btnhistorico . '
										' . $btnver . '
										</div>
								</td>
								</tr>';
	}
}
$table_content .= "</tbody>
					</table>
			</div>
		</div>";



$vista .= '
		<!--<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Trailers \ Remolques
				<div class="tools">
					<a href="#" data-toggle="modal" id="btn_trailer" class="cell-detail  hint--top"  data-hint="" id="btn_trailer"><span class="icon mdi mdi-plus" title="Agregar Trailer"></span></a> 
				</div>
				<span class="panel-subtitle">
					Administración de la hoja de vida de los Trailer/Remolque donde se controla la información y se adjuntan los soportes.
				</span>
				<div class=" col-xs-12 col-sm-4 col-md-12">
					<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="' . $ssn_nombre . '" >
					<input type="hidden" id="elperfil" class="form-control input-sm" readonly="readonly" value="' . $ssn_id_perfil . '">
				</div>
			</div>
			<div class="panel-body">
			</div>
		</div>-->

		<div class="nexos-content">
			<div class="nexos-messages"></div>
				<div class="row" style="margin:-25px -25px -25px -25px;">
					<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
						<tbody>
							<tr>
								<td class="celda_titulo2 text-left" style="margin:25px;"><b>Trailers \ Remolques</b></td>
								<td class="celda_titulo2 text-right" style="margin:25px;">
									<button type="button" class="btn btn-info btn-xs" data-toggle="tooltip" data-placement="top" title="Agregar Trailer" id="btn_crear_trailer"><i class="fas fa-trailer"></i> Agregar Trailer</button>
								</td>
								<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="' . $ssn_nombre . '" >
								<input type="hidden" id="elperfil" class="form-control input-sm" readonly="readonly" value="' . $ssn_id_perfil . '">
							</tr>
						</tbody>
					</table>
					<form method="POST" action="">
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
              <thead>
                <tr>
                  <th style="background-color: #F5F5F5;font-weight: bold;font-size: 12px; border: 1px solid #ddd; width: auto; white-space: nowrap;" class="text-left">Tipo:</th>
                  <td style="border: 1px solid #ddd; width: auto; white-space: nowrap;">
                    <select id="tipo" name="tipo" style="width: 100%;height: 23px;" disabled>
                      <option value="placa" seleted>Placa</option>
                    </select>
                  </td>
                  <th style="background-color: #F5F5F5; font-weight: bold; font-size: 12px; border: 1px solid #ddd; width: auto; white-space: nowrap;" class="text-left"> Carácter Búsqueda:</th>
                  <td style="border: 1px solid #ddd; width: auto; white-space: nowrap;">
                    <input type="text" id="placat" name="placat" placeholder="Letras o números Placa" style="width: 100%;" oninput="this.value = this.value.toUpperCase();" value="' . $_GET['placa'] . '">
                  </td>
                  <th style="background-color: #F5F5F5; font-weight: bold; font-size: 12px; border: 1px solid #ddd; width: auto; white-space: nowrap;" class="text-left"> Acción:</th>
                  <td style="border: 1px solid #ddd; width: auto; white-space: nowrap;">
                    <button class="btn btn-success btn-xs" id="busqueda" name="busqueda" style="width: 100%;height: 23px;"><i class="fas fa-search"></i> Buscar</button>
                  </td>
                </tr>
              </thead>
            </table>
          </form>
					%content%
				</div>
		</div>
	';

$vista .= '
		<link rel="stylesheet" type="text/css" href="%root_file%lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>
		<style>
			.twitter-typeahead{ width: 100%; }
			.tt-menu {
				background: white;
				border-radius: 4px;
				border: 1px solid gray;
				width: 100%;
				max-height: 100px;
				overflow-y: auto;
				width: 100%;
				text-align: left;
			}
			.tt-suggestion{ padding:5px 10px; 
			.tt-suggestion.tt-cursor{
				color: white;
				background: #0097cf;
			}
		</style>
	';

$vista .= '
		<script src="%root_file%lib/trailer_ajax.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/daterangepicker/js/daterangepicker.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script src="%root_file%lib/moment.js/min/moment.min.js" type="text/javascript"></script>

		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>


		<link href="vendor/select2/dist/css/select2.min.css" rel="stylesheet" />
		<script src="vendor/select2/dist/js/select2.min.js"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
				App.formElements();
			});

			$(document).ready(function(){
			});
		</script>
	';


$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%content%", $table_content, $vista); //variable $table_content sirve para crear adentro de esta todo lo que se va a mostrar en el cuerpo del conetenedor 
echo $vista;
?>
<script>
	$(document).on('click', '#btn_trailer', function() {
		$('#exampleModalLong').modal('show');
	});
	//cierre de botones del segundo modal
	$(document).on('click', '#cierre', function() {
		$('#exampleModalLong').modal('hide');
	});
	//EDITAR TRAILER
	$(document).on('click', '#e_btn_trailer', function() {
		$('#editartrailer').modal('show');
	});
	$(document).on('click', '#e_cierre', function() {
		$('#editartrailer').modal('hide');
	});

	$(document).on('click', '#cierree', function() {
		$('#editartrailer').modal('hide');
	});

	$(document).on('click', '#h_cierre', function() {
		$('#historicovehiculos').modal('hide');
	});
</script>

<div id="editartrailer" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
	<div class=".modal-dialog-centered.modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="modal-title text-center" id="exampleModalLongTitle">
					<label style="font-size:19pt; color:white; text-align:center;">
						ACTUALIZAR DATOS DEL TRÁILER
					</label>
				</h3>
				<button type="button" class="close" id="cierree" aria-label="Close"><span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="row" style="border:1px solid silver;">
			</div>
			<div class="modal-body">
				<div class="enexos_messages_popup"></div>
				<!--cuerpo inicio -->
				<h5 class="text-center text-primary"><strong>
						<p>HOJA DE VIDA DEL TRAILER</p>
					</strong></h5>
				<div class="row">
					<div class="form-group col-xs-4">
						<label style="font-weight:800; margin-top:20px;">Placa trailer: Selecciona la letra</label>
						<select id="einiciar_trailer" class="form-control input-sm"></select>
					</div>
					<div class="form-group col-xs-4">
						<label style="font-weight:800; margin-top:20px;">Ingrese los números de la placa</label>
						<input type="number" id="econse_trailer" class="form-control input-sm">
					</div>
					<div class="form-group col-xs-4">
						<label style="font-weight:800; margin-top:20px;">Placa trailer:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<input type="text" id="e_placa_trailer" placeholder="Placa Trailer" class="form-control input-sm" onblur="mayuscula(this);" readonly="readonly">
					</div>
					<div class="form-group col-xs-6">
						<label style="font-weight:800; margin-top:20px;">Marca Trailer:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<select id="eT_marca" class="form-control input-sm" cargar_marca();>
						</select>
					</div>
					<div class="form-group col-xs-6">
						<label style="font-weight:800; margin-top:20px;">Peso Vacío(Tn) Trailer:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<input type="number" min="0" class="form-control input-sm" id="eT_peso">
					</div>

					<div class="form-group col-xs-6">
						<label style="font-weight:800; margin-top:20px;">Volumen Trailer (m3):&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<input type="number" min="0" class="form-control input-sm" id="eT_volumen">
					</div>
					<div class="form-group col-xs-6">
						<label style="font-weight:800; margin-top:20px;">Tipo trámite Trailer:</label>
						<select class="form-control input-sm" id="eT_tramite">
						</select>
					</div>
					<div class="form-group col-xs-6">
						<label style="font-weight:800; margin-top:20px;">Serie Chasis Trailer:</label>
						<input type="text" min="0" class="form-control input-sm" id="eT_chasis">
					</div>
					<div class="form-group col-xs-6">
						<label style="font-weight:800; margin-top:20px;">Configuración Trailer:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<select id="eT_configuracion" class="form-control input-sm">
						</select>
					</div>
					<div class="form-group col-xs-6">
						<label style="font-weight:800; margin-top:20px;">Modelo Trailer:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<input type="number" class="form-control input-sm" min="0" id="eT_modelo">
					</div>
					<div class="form-group col-xs-6">
						<label style="font-weight:800; margin-top:20px;">Alto(m) Trailer:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<input type="number" min="0" class="form-control input-sm" id="eT_alto">
					</div>
					<div class="form-group col-xs-6">
						<label style="font-weight:800; margin-top:20px;">Ancho Trailer:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<input type="number" class="form-control input-sm" min="0" id="eT_ancho">
					</div>
					<div class="form-group col-xs-4">
						<label style="font-weight:800; margin-top:20px;">Largo Trailer:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<input type="number" class="form-control input-sm" min="0" id="eT_largo">
					</div>
					<div class="form-group col-xs-4">
						<label style="font-weight:800; margin-top:20px;">Capacidad Trailer (Kg):&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<input type="number" class="form-control input-sm" min="0" id="eT_capacidad">
					</div>
					<div class="form-group col-xs-4">
						<label style="font-weight:800; margin-top:20px;">Tipo Carroceria Trailer:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<select id="eT_carroceria" class="form-control input-sm">

						</select>
					</div>
					<div class="form-group col-xs-12">
						<label style="font-weight:800; margin-top:20px;">Características Trailer:</label>
						<textarea type="text" id="eT_caracteristicas" placeholder="Características" class="form-control input-sm" onblur="mayuscula(this);"></textarea>
					</div>
					<div class="form-group col-xs-12">
						<label style="font-weight:800; margin-top:20px;">propietario:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<select id="eT_propietario" class="form-control input-sm">
						</select>
					</div>
					<div class="form-group col-xs-12">
						<label style="font-weight:800; margin-top:20px;">poseedor:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<select id="eT_poseedor" class="form-control input-sm">
						</select>
					</div>

					<div class="col-xs-6 col-md-6  col-sm-6">
						<label style="font-weight:800; margin-top:20px;">Estado</label>
						<select id="e_estado" class="form-control"></select>
					</div>
					<div class="col-xs-6 col-md-6  col-sm-6">
						<label style="font-weight:800; margin-top:20px;">id</label>
						<input type="text" id="e_id" class="form-control" readonly="">
					</div>
				</div>
				<div class="row">
					<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
						<label style="font-weight:800; margin-top:20px;">Documento actual:</label><br>
						<label id="docuactual">t</label>
					</div>
					<div class="col-xs-4 col-md-4  col-sm-4 col-lg-4">
						<label style="font-weight:800; margin-top:20px;">Editar Trailer</label><br>
						<input type="file" id="e_foto_trailer" onchange="etrailer(this.value)" class="form-control input-sm">
					</div>

					<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
						<label style="font-weight:800; margin-top:20px;">Nombre documento</label>
						<input type="text" id="namenew" class="form-control input-sm" disabled="disabled">
					</div>
				</div>
				<div class="row">
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<label style="font-weight:800; margin-top:20px;">N° licencia:</label><br>
						<input type="text" id="e_licencia" class="form-control input-sm">
					</div>
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<label style="font-weight:800; margin-top:20px;">Documento actual:</label><br>
						<label id="docuactuall">L</label>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<label style="font-weight:800; margin-top:20px;">Editar Licencia</label><br>
						<input type="file" id="e_foto_licencia" onchange="elicen(this.value)" class="form-control input-sm">
					</div>
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<label style="font-weight:800; margin-top:20px;">Nombre documento</label><br>
						<input type="text" id="namenlic" class="form-control input-sm" disabled="disabled">
					</div>
				</div>

				<div class="row">
					<h4 class="text-danger"><strong>
							<p>Seguro</p>
						</strong></h4>
					<div class="form-group col-xs-4">
						<label style="font-weight:800; margin-top:20px;">N° Responsabilidad Civil:</label>
						<input type="number" class="form-control input-sm" min="0" id="eT_civil">
					</div>
					<div class="form-group col-xs-6">
						<label style="font-weight:800; margin-top:20px;">Aseguradora Trailer:</label>
						<select id="eT_aseguradora" class="form-control input-sm">
						</select>
					</div>
					<div class="form-group col-xs-3">
						<label style="font-weight:800; margin-top:20px;">Fecha Vencimiento</label>
						<input type="date" id="eT_fechavence" class="form-control input-sm" data-date-format="yyyy/mm/dd">
					</div>
					<div>
						<input type="hidden" id="idtrailer" class="form-control input-sm" readonly="readonly">
					</div>
				</div>

				<!--cuerpo inicio -->
			</div>
			<div class="row  " style="border:1px solid silver;"></div>
			<div class="modal-footer">
				<button id="e_cierre" class="btn btn-secondary">Cerrar</button>
				<button id="editareltrailer" class="btn btn-success">Actualizar</button>
			</div>
		</div>
	</div>
</div>

<div id="historicovehiculos" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary" data-backdrop="static">
	<div class="modal-dialog custom-width">
		<div class="modal-content">
			<div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:left;height: 50px;padding: 19px;">
				<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close" style="color: #fff;"><span class="mdi mdi-close"></span></button>
				<h3 class="modal-title" id="">
					<label style="font-size:19pt; color:white; text-align:center;">
						Historial de Vehículos
					</label>
				</h3>
			</div>
			<div class="modal-body">
				<!-- inicio de la tabla-->
				<h4 class="text-center">Vehículos asociados al trailer</h4>
				<div class='row'>
					<div class='col-sm-12'>
						<div class='table-responsive noSwipe'>
							<table id='table1' class='table table-striped table-hover' data-page-length='100'>
								<thead>
									<tr class='nexos-encabezado'>
										<th>#</th>
										<th>Placa Vehículo</th>
										<th>Placa Trailer</th>
										<th>Estado</th>
									</tr>
								</thead>
								<tbody id="tbhistorico">
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<!-- fin tabla -->
				<div class="row"></div>
			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
			</div>
		</div>
	</div>
</div>

<div id="vertrailer" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary" data-backdrop="static">
	<div class="modal-dialog custom-width">
		<div class="modal-content">
			<div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:left;height: 50px;padding: 19px;">
				<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close" style="color: #fff;"><span class="mdi mdi-close"></span></button>
				<h3 class="modal-title" style="font-weight: bold;color: #fff;"><i class="fas fa-table"></i> Consultar Trailer</h3>
			</div>
			<div class="modal-body">
				<div class='row'>
					<div class='col-sm-12'>
						<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
							<tbody>
								<tr>
									<td class="celda_titulo2 text-center" style="margin:25px;">
										<b>Datos del trailer</b>
									</td>
								</tr>
								<tr>
								</tr>
							</tbody>
						</table>
						<table cellpadding="0" cellspacing="0" width="100%">
							<tbody>
								<tr>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Placa</th>
									<td id="vplacat" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Marca</th>
									<td id="vmarca" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Peso Vacío</th>
									<td id="vpeso_vacio" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
								</tr>
								<tr>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Alto</th>
									<td id="valto" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Volumen(m3)</th>
									<td id="vvolumen" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Tipo trámite</th>
									<td id="vtipo_tramite" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
								</tr>
								<tr>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Serie Chasis</th>
									<td id="vchasis" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Configuración</th>
									<td id="vconfiguracion" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Modelo</th>
									<td id="vmodelo" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
								</tr>
								<tr>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Ancho</th>
									<td id="vancho" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Largo</th>
									<td id="vlargo" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Capacidad</th>
									<td id="vcapacidad" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
								</tr>
								<tr>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Carroceria</th>
									<td id="vcarroceria" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Número civil</th>
									<td id="vcivil" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Característica</th>
									<td id="vcarateristica" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
								</tr>
								<tr>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Aseguradora</th>
									<td id="vaseguradora" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Fecha Vencimiento</th>
									<td id="vfecha_vencimiento" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Propietario</th>
									<td id="vpropietario" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
								</tr>
								<tr>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Poseedor</th>
									<td id="vaposeedor" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Estado</th>
									<td id="vestado" class="text-left" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
								</tr>
							</tbody>
						</table>
						<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
							<tbody>
								<tr>
									<td class="celda_titulo2 text-center" style="margin:25px;">
										<b>Documentos del trailer</b>
									</td>
								</tr>
								<tr>
								</tr>
							</tbody>
						</table>
						<table cellpadding="0" cellspacing="0" width="100%">
							<tbody>
								<tr>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Foto del tráiler</th>
									<td id="vfoto_trailer" class="text-center" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
									<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">Foto de licencia</th>
									<td id="vfoto_licencia" class="text-center" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;"></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12 col-sm-12 col-lg-12">
						<div class="panel panel-border-color panel-border-color-success">
							<div class="panel-heading"><strong>Consulta RNDC</strong></div>
							<div class="panel-body" id="panel_rndc">
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12 col-sm-12 col-lg-12">
						<div class="panel panel-border-color panel-border-color-success">
							<div class="panel-heading"><strong>Consulta OET</strong></div>
							<div class="panel-body" id="panel_oet">
							</div>
						</div>
					</div>
				</div>
				<!-- fin content -->
				<div class="row"></div>
			</div>
			<div class="modal-footer">
				<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	//$("#placa_trailer").mask("AAA");

	function mayuscula(elemento) {
		let texto = elemento.value;
		elemento.value = texto.toUpperCase();
	}

	function fototrai(fic) {
		fic = fic.split('\\');
		if (fic == '' || fic == null) {
			$("#name_foto").val('');
		} else {
			$("#name_foto").val(fic[fic.length - 1]);
		}
	}

	function fotolicen(fic) {
		fic = fic.split('\\');
		if (fic == '' || fic == null) {
			$("#name_licen").val('');
		} else {
			$("#name_licen").val(fic[fic.length - 1]);
		}
	}

	function etrailer(fic) {
		fic = fic.split('\\');
		if (fic == '' || fic == null) {
			$("#namenew").val('');
		} else {
			$("#namenew").val(fic[fic.length - 1]);
		}
	}

	function elicen(fic) {
		fic = fic.split('\\');
		if (fic == '' || fic == null) {
			$("#namenlic").val('');
		} else {
			$("#namenlic").val(fic[fic.length - 1]);
		}
	}
</script>