<?php
	$_jsScripts = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
	$result = $this->municipios->permisosPerfil( $ssn_id_perfil, 74);
	$permisos = $result["rowsData"][0];

	$vista = '';

	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->municipios) && count($this->municipios)){
		/*** SE CREA TABLA DE CONTENIDO ***/
		$table = '
			<div class="table-responsive noSwipe col-xs-12 col-sm-12 col-md-12">
				<table id="table1" class="table table-striped table-hover" data-page-length="100">
					<thead>
						<tr class="nexos-encabezado">
							<th>País</th>
							<th>Departamento | Estado | Región</th>
							<th>Ciudad | Municipio</th>
						</tr>
					</thead>
					<tbody>
		';

		$array = $this->municipios->getMunicipios();
		if (isset($array['rowsData'])) {
			foreach ($array['rowsData'] as $key => $value) {
				// Se maqueta contenido de la tabla 
				$table.= '
					<tr>
						<td class="cell-detail">
							<span>' . $value["pais"] . '</span>
						</td>
						<td class="cell-detail">
							<span>' . $value["depto"] . '</span>
						</td>
						<td class="cell-detail">
							<span>' . $value["municipio"] . '</span>
							<span class="cell-detail-description">' . $value["rndc_codigo_ciudad"] . '</span>
						</td>
					</tr>
				';
			}
		}
		$table.= '
					</tbody>
				</table>
			</div>
		';
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/

	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$_btn_crear = '';
	if ($permisos["adicionar"] == 1) {
		$_btn_crear = '
			<a href="javascript:" onclick="creaPais()" class="cell-detail hint--top-left" data-hint="Agregar País"><span class="icon mdi mdi-google-earth" data-toggle="modal" data-target="#popup_panel"></span></a>
			<a href="javascript:" onclick="creaDepto()" class="cell-detail hint--top-left" data-hint="Agregar Estado | Departamento | Región"><span class="icon mdi mdi-map" data-toggle="modal" data-target="#popup_panel"></span></a>
			<a href="javascript:" onclick="creaMunicipio()" class="cell-detail hint--top-left" data-hint="Agregar Municipio"><span class="icon mdi mdi-city" data-toggle="modal" data-target="#popup_panel"></span></a>
		';
	}
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Administración de Municipios
				<div class="tools">
					' . $_btn_crear . '
				</div>
				<span class="panel-subtitle">Establece las cuidades o municipios donde se ubicarán los clientes, proveedores, bodegas o remitentes destinatarios.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12"></div>
				</div>
			</div>
		</div>

		<div id="popup_panel" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="popup_title"></h3>
					</div>
					<div class="modal-body">
						<div id="popup_message"></div>
						<div id="popup_content"></div>
						<div class="row"></div>
					</div>
					<div class="modal-footer">
						<button id="btn_crea_pais" type="button" class="btn btn-success md-close">Guardar</button>
						<button id="btn_crea_depto" type="button" class="btn btn-success md-close">Guardar</button>
						<button id="btn_crea_municipio" type="button" class="btn btn-success md-close">Guardar</button>
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
					</div>
				</div>
			</div>
		</div>
	';

  	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>

		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>

	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;
?>
<script type="text/javascript">
	$(document).ready(function(){
		$("#btn_crea_pais").click(function(){
			let msg_error = '';
			var pais = $("#pais");
			if (!pais.val()) { msg_error+= `<p>Debe diligenciar el campo <strong>${pais.attr("placeholder")}</strong> para poder crear el país.</p>`; }
			if (!msg_error) {
				var params = {
					action: "agregar_pais",
					pais: pais.val()
				}
				$.ajaxSetup({async: false});
				$.ajax({
					url: $("#id_url_ajax").val() + "libs/municipios_ajax.php",
					type: 'POST',
					data: params,
					cache: false,
					dataType: 'json',
					beforeSend	: function(jqXHR, settings){
						funct_msg_loading(".nexos-messages");
					},
					error: function (jqXHR, textStatus, errorThrown){
						$(".nexos-messages").html('');
						msg_error+= "<p>" + jqXHR.responseText + "</p>";
						console.log(jqXHR);
						console.log(textStatus);
						console.log(errorThrown);
					},
					success: function (data, textStatus, jqXHR){
						$(".nexos-messages").html('');
						// console.log(data);
						if (data.id_municipio) {
							funct_msg_success("#popup_message");
							setTimeout(function() { location.reload(false);  }, 800);
						} 
					}
				});
				$.ajaxSetup({async: true});
			}
			if (msg_error) { funct_msg_error("#popup_message", msg_error); }
		});

		$("#btn_crea_depto").click(function(){
			$("#popup_message").empty();
			let msg_error = '';
			var pais = $("#slct_pais_");
			var depto = $("#depto");

			if (!pais.val()) { msg_error+= `<p>Debe seleccionar un <strong>${pais.attr("placeholder")}</strong> para poder crear el Estado | Departamento | Región.</p>`; }
			if (!depto.val()) { msg_error+= `<p>Debe diligenciar el campo <strong>${depto.attr("placeholder")}</strong> para poder crear el Estado | Departamento | Región.</p>`; }

			if (!msg_error) {
				var params = {
					action: "agregar_depto",
					pais: pais.val(),
					depto: depto.val()
				}
				$.ajaxSetup({async: false});
				$.ajax({
					url: $("#id_url_ajax").val() + "libs/municipios_ajax.php",
					type: 'POST',
					data: params,
					cache: false,
					dataType: 'json',
					beforeSend	: function(jqXHR, settings){
						funct_msg_loading(".nexos-messages");
					},
					error: function (jqXHR, textStatus, errorThrown){
						$(".nexos-messages").html('');
						msg_error+= "<p>" + jqXHR.responseText + "</p>";
						console.log(jqXHR);
						console.log(textStatus);
						console.log(errorThrown);
					},
					success: function (data, textStatus, jqXHR){
						$(".nexos-messages").html('');
						// console.log(data);
						if (data.flag) {
							funct_msg_success("#popup_message");
							setTimeout(function() { location.reload(false);  }, 800);
						} 
						if (data.error) { msg_error+= data.error }
					}
				});
				$.ajaxSetup({async: true});
			}
			if (msg_error) { funct_msg_error("#popup_message", msg_error); }
		});

		$("#btn_crea_municipio").click(function(){
			$("#popup_message").empty();
			let msg_error = '';
			var pais = $("#slct_pais_");
			var depto = $("#slct_depto_");
			var municipio = $("#municipio");
			//demas campos solo para colombia
				var valica,latitud,longitud;
			if(pais.val()=='COLOMBIA'){
				 valica= $("#valica").val();
				 latitud= $("#latitud").val();
				 longitud= $("#longitud").val();
			}else{
				valica='';
				latitud='';
				longitud='';
			}

			if (!pais.val()) { msg_error+= `<p>Debe seleccionar un <strong>${pais.attr("placeholder")}</strong> para poder crear el municipio.</p>`; }
			if (!depto.val()) { msg_error+= `<p>Debe diligenciar el campo <strong>${depto.attr("placeholder")}</strong> para poder crear el municipio.</p>`; }
			if (!municipio.val()) { msg_error+= `<p>Debe diligenciar el campo <strong>${municipio.attr("placeholder")}</strong> para poder crear el municipio.</p>`; }
			if(pais.val()=='COLOMBIA'){
				if(!$("#valica").val()){
				 msg_error+= `<p>Debe diligenciar el campo <strong> Valor ica</strong> para poder crear el municipio.</p>`;
				}
				if(!$("#latitud").val()){
					msg_error+= `<p>Debe diligenciar el campo <strong> Latitud</strong> para poder crear el municipio.</p>`;
				}
				if(!$("#longitud").val()){
					msg_error+= `<p>Debe diligenciar el campo <strong> Longitud</strong> para poder crear el municipio.</p>`;
				}
			}

			if (!msg_error) {
				var params = {
					action: "agregar_municipio",
					pais: pais.val(),
					depto: depto.val(),
					municipio: municipio.val(),
					valica:valica,
					latitud:latitud,
					longitud:longitud
				}
				$.ajaxSetup({async: false});
				$.ajax({
					url: $("#id_url_ajax").val() + "libs/municipios_ajax.php",
					type: 'POST',
					data: params,
					cache: false,
					dataType: 'json',
					beforeSend	: function(jqXHR, settings){
						funct_msg_loading(".nexos-messages");
					},
					error: function (jqXHR, textStatus, errorThrown){
						$(".nexos-messages").html('');
						msg_error+= "<p>" + jqXHR.responseText + "</p>";
						console.log(jqXHR);
						console.log(textStatus);
						console.log(errorThrown);
					},
					success: function (data, textStatus, jqXHR){
						$(".nexos-messages").html('');
						// console.log(data);
						if (data.flag) {
							funct_msg_success("#popup_message");
							setTimeout(function() { location.reload(false);  }, 800);
						} 
						if (data.error) { msg_error+= data.error }
					}
				});
				$.ajaxSetup({async: true});
			}
			if (msg_error) { funct_msg_error("#popup_message", msg_error); }
		});
	});

	function creaPais(){
		// console.log("Entro en función creaPais");
		$("#popup_content").empty();
		$("#btn_crea_pais").show();
		$("#btn_crea_depto").hide();
		$("#btn_crea_municipio").hide();
		$("#popup_message").empty();
		$("#popup_title").html("Crear País");
		var msg_error= '';

		$("#popup_content").html(`
			<div class="col-xs-12 col-sm-2 col-md-4"></div>
			<div class="col-xs-12 col-sm-8 col-md-4">
				<label class="control-label">(*) País:</label>
				<input type="text" class="form-control input-sm" name="pais" id="pais" placeholder="País">
			</div>
			<div class="col-xs-12 col-sm-2 col-md-4"></div>
		`);

		$("#pais").blur(function(){
			$("#popup_message").empty();
			$("#btn_crea_pais").show();
			if ($(this).val()) {
				let msg_error = '';
				var params = {
					action: "buscar_pais",
					pais: $(this).val().toUpperCase()
				}
				$.ajaxSetup({async: false});
				$.ajax({
					url: $("#id_url_ajax").val() + "libs/municipios_ajax.php",
					type: 'POST',
					data: params,
					cache: false,
					dataType: 'json',
					beforeSend	: function(jqXHR, settings){
						funct_msg_loading(".nexos-messages");
					},
					error: function (jqXHR, textStatus, errorThrown){
						$(".nexos-messages").html('');
						msg_error+= "<p>" + jqXHR.responseText + "</p>";
						console.log(jqXHR);
						console.log(textStatus);
						console.log(errorThrown);
					},
					success: function (data, textStatus, jqXHR){
						$(".nexos-messages").html('');
						// console.log(data);
						if (!data.error) {
							if (data.result) { 
								msg_error+= `<p>El pais <strong>${data.pais}</strong> ya se encuentra creado.</p>`; 
								$("#btn_crea_pais").hide();
							} 
						} 
						else { msg_error+= `<p>${data.error}</p>`; }
					}
				});
				if (msg_error) { funct_msg_error("#popup_message", msg_error); }
				$.ajaxSetup({async: true});
			}
		});
		if (msg_error) { funct_msg_error("#popup_message", msg_error); }
	}

	function creaDepto(){
		// console.log("Entro en función creaDepto");
		$("#popup_content").empty();
		$("#btn_crea_depto").show();
		$("#btn_crea_pais").hide();
		$("#btn_crea_municipio").hide();
		$("#popup_message").empty();
		$("#popup_title").html("Crear Estado | Departamento | Región");
		var msg_error= '';

		var params = {
			action: "form_crea_depto",
		}
		$.ajaxSetup({async: false});
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/municipios_ajax.php",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend	: function(jqXHR, settings){
				funct_msg_loading(".nexos-messages");
			},
			error: function (jqXHR, textStatus, errorThrown){
				$(".nexos-messages").html('');
				msg_error+= "<p>" + jqXHR.responseText + "</p>";
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function (data, textStatus, jqXHR){
				$(".nexos-messages").html('');
				// console.log(data);
				if (data.content) {
					$("#popup_content").html(data.content);
					$("#slct_pais_").change(function(){ buscar_depto(); });
					$("#depto").blur(function(){ buscar_depto(); });
				}
				if (data.error) { msg_error+= data.error }
			}
		});
		if (msg_error) { funct_msg_error("#popup_message", msg_error); }
		$.ajaxSetup({async: true});
	}

	function buscar_depto(){
		$("#btn_crea_depto").show();
		var pais = $("#slct_pais_");
		var depto = $("#depto");
		var msg_error = '';

		if ( pais.val() && depto.val() ) {
			$("#popup_message").empty();
			var params = {
				action: "buscar_depto",
				pais: pais.val().toUpperCase(),
				depto: depto.val().toUpperCase()
			}
			$.ajaxSetup({async: false});
			$.ajax({
				url: $("#id_url_ajax").val() + "libs/municipios_ajax.php",
				type: 'POST',
				data: params,
				cache: false,
				dataType: 'json',
				beforeSend	: function(jqXHR, settings){
					funct_msg_loading(".nexos-messages");
				},
				error: function (jqXHR, textStatus, errorThrown){
					$(".nexos-messages").html('');
					msg_error+= "<p>" + jqXHR.responseText + "</p>";
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
				},
				success: function (data, textStatus, jqXHR){
					$(".nexos-messages").html('');
					// console.log(data);
					if (data.depto) {
						msg_error+= `<p>El Estado | Departamento | Región <strong>${depto.val().toUpperCase()}</strong> del país <strong>${pais.val().toUpperCase()}</strong> ya existe.</p>`;
						$("#btn_crea_depto").hide();
					}
					if (data.error) { msg_error+= data.error }
				}
			});
			$.ajaxSetup({async: true});
		} 
		if (msg_error) { funct_msg_error("#popup_message", msg_error); }
	}

	function creaMunicipio(){
		$("#popup_content").empty();
		$("#btn_crea_municipio").show();
		$("#btn_crea_pais").hide();
		$("#btn_crea_depto").hide();
		$("#popup_message").empty();
		$("#popup_title").html("Crear Municipio");
		var msg_error= '';

		var params = {
			action: "form_crea_municipio",
		}
		$.ajaxSetup({async: false});
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/municipios_ajax.php",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend	: function(jqXHR, settings){
				funct_msg_loading(".nexos-messages");
			},
			error: function (jqXHR, textStatus, errorThrown){
				$(".nexos-messages").html('');
				msg_error+= "<p>" + jqXHR.responseText + "</p>";
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function (data, textStatus, jqXHR){
				$(".nexos-messages").html('');
				// console.log(data);
				if (data.content) {
					$("#popup_content").html(data.content);
					$("#div_depto").empty();
					$("#div_municipio").empty();

					$("#slct_pais_").change(function(){ 
						var pais=$(this).val();
						$("#div_depto").empty();
						$("#div_municipio").empty();
						crea_municipio_busca_depto( $(this).val() );
						buscar_municipio();

						$("#slct_depto_").change(function(){ buscar_municipio(); });
						$("#municipio").blur(function(){ buscar_municipio(); });
					});
				}
				if (data.error) { msg_error+= data.error }
			}
		});
		if (msg_error) { funct_msg_error("#popup_message", msg_error); }
		$.ajaxSetup({async: true});
		if (msg_error) { funct_msg_error("#popup_message", msg_error); }
	}

	function crea_municipio_busca_depto(pais){
		var msg_error= '';
		$("#div_depto").empty();
		$("#div_municipio").empty();

		var params = {
			action: "fld_busca_depto",
			pais: pais
		}
		$.ajaxSetup({async: false});
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/municipios_ajax.php",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend	: function(jqXHR, settings){
				funct_msg_loading(".nexos-messages");
			},
			error: function (jqXHR, textStatus, errorThrown){
				$(".nexos-messages").html('');
				msg_error+= "<p>" + jqXHR.responseText + "</p>";
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function (data, textStatus, jqXHR){
				$(".nexos-messages").html('');
				// console.log(data);
				if (data.content) { 
					$("#div_depto").html(data.content.depto) 
					$("#div_municipio").html(data.content.municipio) 
				}
				if (data.error) { msg_error+= data.error }
			}
		});
		if (msg_error) { funct_msg_error("#popup_message", msg_error); }
		$.ajaxSetup({async: true});
	}

	function buscar_municipio(){
		$("#btn_crea_municipio").show();
		var pais = $("#slct_pais_");
		var depto = $("#slct_depto_");
		var municipio = $("#municipio");
		var msg_error = '';

		if ( pais.val() && depto.val() && municipio.val() ) {
			$("#popup_message").empty();
			var params = {
				action: "buscar_municipio",
				pais: pais.val().toUpperCase(),
				depto: depto.val().toUpperCase(),
				municipio: municipio.val().toUpperCase()
			}
			$.ajaxSetup({async: false});
			$.ajax({
				url: $("#id_url_ajax").val() + "libs/municipios_ajax.php",
				type: 'POST',
				data: params,
				cache: false,
				dataType: 'json',
				beforeSend	: function(jqXHR, settings){
					funct_msg_loading(".nexos-messages");
				},
				error: function (jqXHR, textStatus, errorThrown){
					$(".nexos-messages").html('');
					msg_error+= "<p>" + jqXHR.responseText + "</p>";
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
				},
				success: function (data, textStatus, jqXHR){
					$(".nexos-messages").html('');
					// console.log(data);
					if (data.municipio) {
						msg_error+= `<p>El municipio <strong>${municipio.val().toUpperCase()}</strong> del Estado | Departamento | Región <strong>${depto.val().toUpperCase()}</strong> y del país <strong>${pais.val().toUpperCase()}</strong> ya existe.</p>`;
						$("#btn_crea_municipio").hide();
					}
					if (data.error) { msg_error+= data.error }
				}
			});
			$.ajaxSetup({async: true});
		} 
		if (msg_error) { funct_msg_error("#popup_message", msg_error); }
	}




</script>