<?php
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
$vista = '';
$table_content = '';

if (isset($this->group)) {
	$arrayPermisos = $this->group->permisosPerfil($ssn_id_perfil, 128);
	$_permisos = $arrayPermisos;

	$btn_crear = '';

	if ($_permisos["adicionar"] == 1) {
		$btn_crear = '
		<a id="btn_crea" href="#"  data-toggle="modal"  class="cell-detail  hint--top "  data-hint="" data-target="#crear_grupo"><span class="icon mdi mdi-plus" title="Agregar Grupo"></span></a>';
	}


	$vista .= '
	<div class="panel panel-border panel-contrast" id="tabla_principal">
		<div class="panel-heading panel-heading-contrast">
				Grupos
			<div class="tools">
					' . $btn_crear . '
			</div>
			<span class="panel-subtitle">Módulo para la creación de grupos asociados a un cliente.</span>
			</div>
			<div class="panel-body">
				<div class="nexos-messages"></div>
				<div class="nexos-content">
					%content%
				</div>
				<div class="row">
				<div class="col-sm-12"></div>
			</div>
		</div>
	</div>
';

	$table_content .= '
<div>
	<h3 class="text-center"><p style="font-size:20pt; font-weight:500; color:#2E2E2E;">Grupos</p></h3>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group col-xs-8 col-sm-8 col-md-8">
	<label>Seleccione el cliente</label>
	<select  class="form-control input-sm" id="nomgrupo" >
	</select>
</div>
<div class="form-group col-xs-4 col-sm-4 col-md-4">
	<label></label>
	<button class="form-control input-sm btn btn-info mdi mdi-search" id="consulte"  onclick="solicitudes_grupos();" >
		Consultar
	</button>
</div>
</div>';

	$table_content .= '
	<div id="esconder">
	<div class="row" >
	<div class="col-sm-12">
		<div  class="table-responsive noSwipe">

           	<table id="table1" class="table table-striped table-hover table-fw-widget">
                    <thead>
                      <tr>
                      	<th>#</th>
                        <th>Grupo</th>
                        <th>Cliente</th>
                         <th>Acción</th>
                      </tr>
                    </thead>
                    <tbody id="body_esconder">
                    </tbody>
                </table>

		</div>
	</div>
	</div>
</div>';
}

?>

<!--Crear grupo -->
<div id="crear_grupo" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
	<div class="modal-dialog custom-width">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
				<h3 class="modal-title" id="editar_title">
					<label id="titulo" style="font-size:20pt; color:white; text-align:center;">Crear Grupo</label>
				</h3>
			</div>
			<div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
				<div id="msg_creargrupo"></div>
				<div id="content_editar">
					<div class="row">
						<div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
							<label style="font-weight:800; margin-top:20px; ">Cliente</label>
							<select id="gr_cliente" class="form-control input-sm">
								<option value="">Seleccione</option>
							</select>
						</div>
						<div class="col-x-7 col-sm-7 col-md-7 col-lg-7">
							<label style="font-weight:800; margin-top:20px;">Nombre del grupo</label>
							<input type="text" id="gr_name" class="form-control input-sm">
						</div>
					</div><br><br>

					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<label style="font-weight:800; margin-top:20px;">Agregar Contacto</label>
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<button class="form-control btn btn-info mdi mdi-plus input-xs text-center" id="agregar_fila"></button>
						</div><br>
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<table class="table table-bordered">
								<thead style="border-color:blue;">
								</thead>
								<tbody id="tabla_contacte">
								</tbody>
							</table>
						</div>
						<input type="hidden" id="cont_contactos">
					</div>
				</div>
				<div class="modal-footer">
					<button id="btn_guadargrupo" type="button" class="btn btn-success md-close" onclick="">Guardar</button>
					<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
				</div>
			</div>
		</div>
	</div>
</div>

<!--Consultar Grupo -->
<div id="visite_grupo" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
	<div class="modal-dialog custom-width">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
				<h3 class="modal-title" id="editar_title">
					<label id="titulo" style="font-size:24pt; color:white; font-weight:800; ">Consultar Grupo</label>
				</h3>
			</div>
			<div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
				<div id="msg_ver"></div>
				<div id="content_ver">
					<div class="row">
						<div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
							<label>Cliente</label>
							<input type="text" id="vcliente" class="form-control input-sm" disabled="disabled">
						</div>
						<div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
							<label>Grupo</label>
							<input type="text" id="vgrupo" class="form-control input-sm" disabled="disabled">
						</div>
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<label>Contactos</label>
							<table class="table table-condensed table-hover table-bordered table-striped">
								<thead>
									<th>Nombre contacto</th>
									<th>Teléfono</th>
									<th>Cargo</th>
									<th>Áerea</th>
									<th>Email</th>
								</thead>
								<tbody id="ver_contacto">
								</tbody>
							</table>
						</div>
					</div>

				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
				</div>
			</div>
		</div>
	</div>
</div>

<!--Editar Grupo -->
<div id="edite_grupo" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
	<div class="modal-dialog custom-width">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
				<h3 class="modal-title" id="editar_title">
					<label id="titulo" style="font-size:24pt; color:white; font-weight:800; ">Actualizar Grupo</label>
				</h3>
			</div>
			<div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
				<div id="msg_edicion_grupo"></div>
				<div id="content_editar">
					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<label>Cliente</label>
							<select id="e_cliente" class="form-control input-sm"></select>
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<label>Nombre grupo</label>
							<input type="text" id="e_grupo" class="form-control input-sm">
						</div>
						<input type="hidden" id="idgrupo">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<label>Contactos</label>
							<table class="table table-condensed table-hover table-bordered table-striped">
								<thead>
									<th>Id</th>
									<th>Nombre contacto</th>
									<th>Teléfono</th>
									<th>Cargo</th>
									<th>Áerea</th>
									<th>Email</th>
									<th>Acción</th>
								</thead>
								<tbody id="e_contacto">
								</tbody>
							</table>
							<input type="hidden" id="ecant_bloque">
						</div>
					</div>
					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6 ol-lg-6">
							<label>¿Desea agregar más contactos?</label>
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<button class="form-control btn btn-info mdi mdi-plus input-xs text-center" id="otro_contacto"></button>
						</div><br>
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<table class="table table-bordered">
								<thead style="border-color:blue;">
								</thead>
								<tbody id="other_contacte">
								</tbody>
							</table>
						</div>
						<input type="hidden" id="mcontacto">
					</div>
				</div>
				<div class="modal-footer">
					<button id="btn_updategrupo" type="button" class="btn btn-success md-close" onclick="">Actualizar</button>
					<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
				</div>
			</div>
		</div>
	</div>
</div>


<?php
$vista .= '
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
			<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/rutas_ajax.js" type="text/javascript"></script>
			<script src="%root_file%js/main.js" type="text/javascript"></script>
			<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
			<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

			<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
			<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
			<link  rel="stylesheet" type="text/css" href="assets/lib/select2/css/select2.min.css"/>

			<link rel="stylesheet" type="text/css" src="%root_file%lib/assets/lib/select2/css/select2.min.css"/>

			<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
			<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

			<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
			<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
			<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

			<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
			<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
			<script type="text/javascript">
				$.fn.niftyModal(\'setDefaults\',{
					overlaySelector: \'.modal-overlay\',
					closeSelector: \'.modal-close\',
					classAddAfterOpen: \'modal-show\',
				});
				$(document).ready(function(){
					//initialize the javascript
					App.init();
				});
				$(document).ready(function(){
					//initialize the javascript
					App.init();
					App.dataTables();
				});
				$(document).ready(function(){
					//initialize the javascript
					App.init();
					App.wizard();
				});
			</script>
';
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%content%", $table_content, $vista);
echo $vista;

?>

<script type="text/javascript">
	$(document).ready(function() {
		consultar_grupos();
		clientes_select();
		//enviar a funciones
		$("#agregar_fila").click(function() {
			agregar_contacto();
		});

		$("#otro_contacto").click(function() {
			otro_contacto();
		});
		//validaciones
		$("#btn_guadargrupo").click(function() {
			var msg_error = '';
			if (!$("#gr_cliente").val()) {
				msg_error += "<p>Debe diligenciar el campo <strong>Cliente</strong> para poder registrar .</p>";
			}
			if (!$("#gr_name").val()) {
				msg_error += "<p>Debe diligenciar el campo <strong>Nombre del grupo</strong> para poder registrar.</p>";
			}
			var cant = $("#cont_contactos").val();
			if (cant > 0) {
				var i;
				for (i = 1; i <= cant; i++) {
					if (typeof $("#sy" + i).val() !== 'undefined') {
						if (!$("#nombres" + i + "").val()) {
							msg_error += "<p>Debe diligenciar el campo <strong>Nombre</strong>en el bloque Contactos para poder registrar.</p>";
						}

						if (!$("#correo" + i + "").val()) {
							msg_error += "<p>Debe diligenciar el campo <strong>Correo</strong>en el bloque Contactos para poder registrar.</p>";
						}
					}
				}
			}
			if ($(".identi").size() <= 0) {
				msg_error += "<p>Debe diligenciar <strong>Mínimo 1 bloque de contacto </strong> para poder registrar.</p>";
			}
			if (!msg_error) {
				Registrar_Grupo();
			} else {
				$("#msg_creargrupo").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
				$("#crear_grupo").animate({
					scrollTop: 0
				}, 600);
			}
		});

		$("#btn_updategrupo").click(function() {
			var msg_error = '';
			var e = $(".idene").size(); //bloque actual
			var me = $(".identie").size();
			if (e <= 0 && me <= 0) {
				msg_error += "<p>Debe haber Mínimo <strong>Bloque de contactos</strong> para poder actualizar .</p>";
			}
			//anteriores
			if (e > 0) {
				var t;
				var a = $("#ecant_bloque").val();
				for (t = 1; t <= a; t++) {
					if (typeof $("#sd" + t).val() !== 'undefined') {
						if (!$("#nomc" + t + "").val()) {
							msg_error += "<p>Debe ingresar el campo <strong>Nombre " + t + "</strong> en contactos actuales para poder actualizar .</p>";
						}
						if (!$("#emailc" + t + "").val()) {
							msg_error += "<p>Debe ingresar el campo <strong>email " + t + "</strong> en contactos actuales  para poder actualizar .</p>";
						}
					}
				}
			}
			//nuevos
			//bloque nuevo
			if (me > 0) {
				var k;
				var a = $("#mcontacto").val();
				for (k = 1; k <= a; k++) {
					if (typeof $("#se" + k).val() !== 'undefined') {
						if (!$("#nombrese" + k + "").val()) {
							msg_error += "<p>Debe ingresar el campo <strong>Nombre " + k + "</strong> en contactos nuevos para poder actualizar .</p>";
						}
						if (!$("#correoe" + k + "").val()) {
							msg_error += "<p>Debe ingresar el campo <strong> correo " + k + "</strong> en contactos nuevos para poder actualizar .</p>";
						}
					}
				}
			}

			if (!msg_error) {
				Actualizar_Grupo();
			} else {
				$("#msg_edicion_grupo").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
				$("#edite_grupo").animate({
					scrollTop: 0
				}, 600);
			}

		});

	});

	var url = $("#id_url_ajax").val() + "libs/grupo_ajax.php";

	function consultar_grupos() {
		var group = {
			action: 'consultar_grupo'
		};
		$("#nomgrupo").html('<option value="">Seleccione</option>');
		$.ajax({
			url: url,
			type: 'POST',
			data: group,
			dataType: 'json',
			success: function(data) {
				if (data) {
					data.result.forEach(function(element, index) {
						/*$("#nomgrupo").append('<option value="'+element.nombre_grupo+'">'+element.nombre_grupo+'</option>');*/
						$("#nomgrupo").append('<option value="' + element.id + '">' + element.nombre + ' - ' + element.documento + '</option>');
					});
				}
			},
			error: function(jqXHR, textStatus, errorThrown) {
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			}
		});
	}

	function clientes_select() {
		var dato = {
			action: 'consultar_cliente'
		};
		$("#gr_cliente").html('');
		$("#gr_cliente").html('<option value="">Seleccione</option>');
		$.ajax({
			url: url,
			type: 'POST',
			data: dato,
			dataType: 'json',
			success: function(data) {
				if (data) {
					data.result.forEach(function(element, index) {
						$("#gr_cliente").append('<option value="' + element.id + '">' + element.nombre + '</option>');
					});
				}
			},
			error: function(jqXHR, textStatus, errorThrown) {
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			}
		});
	}

	var a = 0;
	var b = 0;

	function agregar_contacto() {
		a++;
		b = b + 1;
		var ch = '<input type="button" id="p' + a + '" class="btn-primary borrar2" value="Eliminar" onclick="eliminar_co(' + a + ')" ><input type="hidden" id="sy' + a + '" value="1"><input type="hidden" class="identi tr' + a + '" value="1"> ';
		var contace = '<tr class="tr' + a + '">' +
			//'<th>#</th><th>Nombres</th><th>Cargo</th><th>Teléfono</th></tr><tr>'+
			'<td colspan="2" class="info tr' + a + '"><label>N°</label><p class="text-center text-primary tr' + a + '"><strong>' + a + '</strong></p><input type="hidden" id="sk' + a + '" value="1" class="form-control input-sm tr' + a + '">  </td>' +
			'</tr><tr class="tr' + a + '">' +
			'<td colspan="2" class="tr' + a + '"><label>Nombres</label> <input type="text" id="nombres' + a + '" class="form-control input-sm tr"></td>' +
			'</tr><tr class="tr' + a + '">' +
			'<td class="tr' + a + '"><label>Cargo</label> <input type="text" id="cargo' + a + '" class="form-control input-xs tr' + a + '"></td>' +
			'<td class="tr' + a + '"><label>Teléfono</label> <input type="number" id="fijo' + a + '" class="form-control input-xs tr' + a + '"></td>' +
			'<tr class="tr' + a + '">' +
			'<td class="tr' + a + '"><label>Área</label> <input type="text" id="area' + a + '" class="form-control input-xs tr' + a + '">  </td>' +
			'<td class="tr' + a + '"><label>Correo</label>   <input type="email" id="correo' + a + '" class="form-control input-xs tr' + a + '" > </td>' +
			'</tr>' +
			'<tr colspan="2" class="tr' + a + '">' +
			'<td colspan="2" class="tr' + a + '">' + ch + '</td>' +
			'</tr>' +
			'</tr>';

		$("#tabla_contacte").append(contace);
		$("#cont_contactos").val(b);
	}

	function eliminar_co(id) {
		event.preventDefault();
		$('.tr' + id).remove();
		$(this).closest('tr').remove();
	}

	//REGISTRAR

	function Registrar_Grupo() {
		var url2 = $("#id_url_ajax").val() + "libs/trafico2_ajax.php";
		var data = null;
		data = new FormData();
		var cliente = $("#gr_cliente").val();
		var grupo = $("#gr_name").val();
		data.append("accion", 'insertar_grupo');
		data.append("cliente", cliente);
		data.append("nomgrupo", grupo);

		$.ajax({
			url: url2,
			type: 'POST',
			data: data,
			cache: false,
			processData: false, // Don't process the files
			contentType: false, // Set content type to false as jQuery will tell the server its a query string request
			dataType: 'json',
			success: function(data, textStatus, jqXHR) {
				insertcontac();
				// alert('!!Registro Vehiculo exitosamente!!!');
			},
			error: function(jqXHR, textStatus, errorThrown) {
				console.log('no inserto contactos del proveedor');
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			}
		});
	}


	//ACTUALIZAR
	function Actualizar_Grupo() {

		var url2 = $("#id_url_ajax").val() + "libs/trafico2_ajax.php";
		var data = null;
		data = new FormData();
		data.append("accion", 'actualizar_grupo');
		//Actualizar los actuales
		var cliente = $("#e_cliente").val();
		var nomgrupo = $("#e_grupo").val();
		var idgrupo = $("#idgrupo").val();
		data.append("cliente", cliente);
		data.append("nomgrupo", nomgrupo);
		data.append("idgrupo", idgrupo);
		var e = $(".idene").size(); //bloque actual
		var me = $(".identie").size();
		if (e > 0) {
			var t;
			var a = $("#ecant_bloque").val();
			for (t = 1; t <= a; t++) {
				data.append("aid", $("#idc" + t + "").val());
				data.append("aname", $("#nomc" + t + "").val());
				data.append("atel", $("#telc" + t + "").val());
				data.append("acargo", $("#cargoc" + t + "").val());
				data.append("aarea", $("#areac" + t + "").val());
				data.append("aemail", $("#emailc" + t + "").val());
				data.append("actual", 9);
				data.append("nuevo", 1);
			}
		}
		//Insertar los nuevos
		if (me > 0) {
			var k;
			var a = $("#mcontacto").val();
			for (k = 1; k <= a; k++) {
				if (typeof $("#se" + k).val() !== 'undefined') {
					data.append("nnombre", $("#nombrese" + k + "").val());
					data.append("ncargo", $("#cargoe" + k + "").val());
					data.append("nfijo", $("#fijoe" + k + "").val());
					data.append("narea", $("#areae" + k + "").val());
					data.append("ncorreo", $("#correoe" + k + "").val());
					data.append("nuevo", 8);
					data.append("actual", 1);
				}
			}
		}

		$.ajax({
			url: url2,
			type: 'POST',
			data: data,
			cache: false,
			processData: false, // Don't process the files
			contentType: false, // Set content type to false as jQuery will tell the server its a query string request
			dataType: 'json',
			success: function(data, textStatus, jqXHR) {
				alert('!!Actualizo Datos exitosamente!!!');
				location.reload();
			},
			error: function(jqXHR, textStatus, errorThrown) {
				console.log('no inserto contactos del proveedor');
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			}
		});
	}


	function insertcontac() {
		var data = null;
		data = new FormData();
		var cant = $("#cont_contactos").val();
		if (cant > 0) {
			var i;
			for (i = 1; i <= cant; i++) {
				if (typeof $("#sy" + i).val() !== 'undefined') {

					var nom = $("#nombres" + i + "").val();
					var cargo = $("#cargo" + i + "").val();
					var tel = $("#fijo" + i + "").val();
					var area = $("#area" + i + "").val();
					var correo = $("#correo" + i + "").val();
					var cliente = $("#gr_cliente").val();
					data.append("accion", 'insertar_contactos');
					data.append("nombre", nom);
					data.append("cargo", cargo);
					data.append("tele", tel);
					data.append("area", area);
					data.append("correo", correo);
					data.append("cliente", cliente);

					$.ajax({
						url: url2,
						type: 'POST',
						data: data,
						cache: false,
						processData: false, // Don't process the files
						contentType: false, // Set content type to false as jQuery will tell the server its a query string request
						dataType: 'json',
						success: function(data, textStatus, jqXHR) {
							alert('!!Registro Datos exitosamente!!!');
							location.reload();
						},
						error: function(jqXHR, textStatus, errorThrown) {
							console.log('no inserto contactos del proveedor');
							console.log(jqXHR);
							console.log(textStatus);
							console.log(errorThrown);
						}
					});
				}
			}
		}
	}


	//TABLA

	function elimina_contacto(id) {
		var idcontacto = $("#idc" + id).val();
		var e = $(".idene").size();
		if (e == 1 && $("#mcontacto").val() == 0) {
			//if(e==1){ 
			var msg_error;
			msg_error += "<p>No puede remover este bloque , debe agregar otro documento: Contactos.</p>";
			$("#msg_edicion_grupo").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("#edite_grupo").animate({
				scrollTop: 0
			}, 600);
		} else {
			var dele = {
				id: idcontacto,
				action: 'eliminar_contacto'
			};
			$.ajax({
				url: url,
				type: 'POST',
				data: dele,
				dataType: 'json',
				success: function(data) {
					if (data) {
						event.preventDefault();
						$('.tr' + id).remove();
						$(this).closest('tr').remove();
						location.reload(0);
					}
				},
				error: function(jqXHR, textStatus, errorThrown) {
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
				}
			});
		}
	}

	function eliminar_otro(id) {
		var me = $(".identie").size(); //bloque nuevo
		var e = $(".idene").size(); //bloque actual
		if (e <= 1 && me == 1) {
			var msg_error;
			msg_error += "<p>No puede remover este bloque , ya que no existen contactos actuales.</p>";
			$("#msg_edicion_grupo").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("#edite_grupo").animate({
				scrollTop: 0
			}, 600);
		} else {
			event.preventDefault();
			$('.ti' + id).remove();
			$(this).closest('tr').remove();
		}
	}

	var am = 0;
	var t = 0;

	function otro_contacto() {
		am++;
		t = t + 1;
		var ch = '<input type="button" id="e' + am + '" class="btn-primary borrar2" value="Eliminar" onclick="eliminar_otro(' + am + ')" ><input type="hidden" id="se' + am + '" value="1"><input type="hidden" class="identie ti' + am + '" value="1"> ';
		var contace = '<tr class="ti' + am + '">' +
			//'<th>#</th><th>Nombres</th><th>Cargo</th><th>Teléfono</th></tr><tr>'+
			'<td colspan="2" class="info ti' + am + '"><label>N°</label><p class="text-center text-primary ti' + am + '"><strong>' + am + '</strong></p><input type="hidden" id="ske' + am + '" value="1" class="form-control input-sm ti' + am + '">  </td>' +
			'</tr><tr class="ti' + am + '">' +
			'<td colspan="2" class="ti' + am + '"><label>Nombres</label> <input type="text" id="nombrese' + am + '" class="form-control input-sm ti' + am + '"></td>' +
			'</tr><tr class="ti' + am + '">' +
			'<td class="ti' + am + '"><label>Cargo</label> <input type="text" id="cargoe' + am + '" class="form-control input-xs ti' + am + '"></td>' +
			'<td class="ti' + am + '"><label>Teléfono</label> <input type="number" id="fijoe' + am + '" class="form-control input-xs ti' + am + '"></td>' +
			'<tr class="ti' + am + '">' +
			'<td class="ti' + am + '"><label>Área</label> <input type="text" id="areae' + am + '" class="form-control input-xs ti' + am + '">  </td>' +
			'<td class="ti' + am + '"><label>Correo</label>   <input type="email" id="correoe' + am + '" class="form-control input-xs ti' + am + '" > </td>' +
			'</tr>' +
			'<tr colspan="2" class="ti' + am + '">' +
			'<td colspan="2" class="ti' + am + '">' + ch + '</td>' +
			'</tr>' +
			'</tr>';

		$("#other_contacte").append(contace);
		$("#mcontacto").val(t);
	}

	function solicitudes_grupos() {
		var grupo = $("#nomgrupo").val();
		if (grupo == '') {
			var msg_error = '';
			msg_error += "<p>Debe diligenciar el campo <strong>Cliente</strong> para poder registrar .</p>";
			$(".nexos-messages").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
		} else {
			var dato_table = {
				grupo: grupo,
				action: 'tabla_grupos'
			};
			$("#body_esconder").html('');
			$.ajax({
				url: url,
				type: 'POST',
				data: dato_table,
				dataType: 'json',
				success: function(data) {
					if (data.result != null) {
						cont = 0;
						data.result.forEach(function(element, index) {
							cont++;
							var ver = '';
							var btn_editar = '';
							var status = '';

							//datos
							var idgrupo = element.id;
							btn_ver = '<button type="button" class="btn btn-secondary btn btn-sm mdi mdi-eye" title="Consultar Grupo"   id="btn_ver' + cont + '"   data-toggle="modal" data-target="#visite_grupo"  data-id="' + idgrupo + '" "></button>';

							btn_editar = '<button type="button" class="btn btn-secondary btn btn-sm mdi mdi-edit" title="Editar Grupo"   id="btn_editar' + cont + '"   data-toggle="modal" data-target="#edite_grupo"  data-id="' + idgrupo + '" ></button>';

							if (element.estado == 1) {
								status = "<td class='nexos-txt-success'>" +
									"<center><span class='mdi mdi-dot-circle icon' title='Activo'></span></center>" +
									"</td>";
							}

							if (element.estado == 2) {
								status = "<td class='nexos-txt-danger'>" +
									"<span class='mdi mdi-dot-circle icon' title='Inactivo'></span>" +
									"</td>";
							}
							$("#body_esconder").append('<tr>' +
								status +
								'<td>' + element.nombre_grupo + '</td>' +
								'<td>' + element.nombre + '</td>' +
								'<td>' +
								btn_editar + '&nbsp;' +
								btn_ver +
								'</td>' +
								'</tr>');

							$("#btn_ver" + cont + "").click(function(element, index) {
								var id = $(this).attr('data-id');
								var acto = {
									idgrupo: id,
									action: 'indagar_grupo'
								};
								$("#ver_contacto").html('');
								$.ajax({
									url: url,
									type: 'POST',
									data: acto,
									dataType: 'json',
									success: function(data) {
										console.log(data);
										if (data.result != null) {
											$("#vcliente").val(data.result[0].nombre);
											$("#vgrupo").val(data.result[0].nombre_grupo);
										}

										if (data.result2 != null) {
											data.result2.forEach(function(element, index) {
												$("#ver_contacto").append('<tr>' +
													'<td>' + element.nombre_contactos + '</td>' +
													'<td>' + element.telefono + '</td>' +
													'<td>' + element.cargo + '</td>' +
													'<td>' + element.areaa + '</td>' +
													'<td>' + element.email + '</td>' +
													'</tr>');
											});
										}
									},
									error: function(jqXHR, textStatus, errorThrown) {
										console.log(jqXHR);
										console.log(textStatus);
										console.log(errorThrown);
									}
								});
							});

							$("#btn_editar" + cont + "").click(function(element, index) {
								var id = $(this).attr('data-id');
								$("#idgrupo").val(id);
								var acto = {
									idgrupo: id,
									action: 'indagar_grupoe'
								};
								$.ajax({
									url: url,
									type: 'POST',
									data: acto,
									dataType: 'json',
									success: function(data) {
										if (data.result != null) {
											$("#e_cliente").html('');
											data.result[0].clienten.forEach(function(element, index) {
												var tmpSelected = "";
												if (element.selected) {
													tmpSelected = "selected";
												}
												var cliente = $("#e_cliente").append('<option ' + tmpSelected + ' value="' + element.id + '">' + element.nombre + '</option>');
											});
											$("#e_grupo").val(data.result[0].nombre_grupo);
										}
										if (data.result2 != null) {
											var t = 0;
											$("#e_contacto").html('');
											data.result2.forEach(function(element, index) {
												t++;

												var ch = '<input type="button" id="p' + t + '" class="btn-primary tr' + t + '" value="Eliminar" onclick="elimina_contacto(' + t + ')">';

												$("#e_contacto").append('<tr class="tr' + t + '">' +
													'<td class="tr' + t + '"><input type="text" id="idc' + t + '" value="' + element.id + '" class="form-control input-xs tr' + t + '" disabled></td>' +
													'<td class="tr' + t + '"><input type="text" class="form-control input-sm tr' + t + '" id="nomc' + t + '" value="' + element.nombre_contactos + '"></td>' +
													'<td class="tr' + t + '"> <input type="number" class="form-control input-sm tr' + t + '" id="telc' + t + '" value="' + element.telefono + '"> </td>' +
													'<td class="tr' + t + '"> <input type="text" class="form-control input-sm tr' + t + '" id="cargoc' + t + '" value="' + element.cargo + '"> </td>' +
													'<td class="tr' + t + '"> <input type="text" class="form-control input-sm tr' + t + '" id="areac' + t + '" value="' + element.areaa + '">  </td>' +
													'<td class="tr' + t + '"> <input type="text" class="form-control input-sm tr' + t + '" id="emailc' + t + '" value="' + element.email + '"> </td>' +
													'<td class="tr' + t + '">' + ch + '<input type="hidden" class="idene tr' + t + '" value="1"><input type="hidden" id="sd' + t + '" value="1"> </td>' +
													'</tr>');

												$("#ecant_bloque").val(t);
											});
										}
									},
									error: function(jqXHR, textStatus, errorThrown) {
										console.log(jqXHR);
										console.log(textStatus);
										console.log(errorThrown);
									}
								});
							});
						});
					}
				},
				error: function(jqXHR, textStatus, errorThrown) {
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
				}
			});
		}
	}
</script>