<?php
$Conect = new Consultas;
$_dbTable = "actividades_carga_oc"; // SIN EL PREFIJO cmx_
$_jsScripts = "";
$_jsAjax = "";

// se definen las variables de session
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
// echo "<p>id_cliente - " . $ssn_id_cliente . "</p>";
// echo "<p>id_usuario - " . $ssn_id_usuario . "</p>";
// echo "<p>id_perfil - " . $ssn_id_perfil . "</p>";

$r = new Request();
// print_r($r->getArgs());

$vista = '';

// Validacion JS de seleccion de los checkbox de la tabla principal
$_jsAjax .= '
		$(\'input:checkbox[class="actividades"]\').change(function () {
			console.log("Entro en funcion actividades");
			$("#actividades").val(\'\');
			selected = "";
			$(\'input:checkbox[class="actividades"]:checked\').each(function(){
	 			selected += $(this).val() + \',\';
			}); 
			$("#actividades").val(selected);
		});
	';


/********* POPUPS *********/
/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
// POPUP DE MUESTRA DE INFORMACION
$info = new Popup();
// POPUP DE ALERTA DE CONFIRMACION
$alert = new Popup();
// POPUP DE FORMULARIO DE EDICION 
$form_edita = new Popup();
// POPUP DE FORMULARIO DE CREACION 
$form_crea = new Popup();

/********* FIN POPUPS *********/

/*** CREACION DE TABLA DE ENCABEZADO ***/
if (isset($this->orden_compra) /* && count($this->orden_compra) */) {

	$arrayOrden_compra = $this->orden_compra->getCargas($r->getArgs()[0], "");
	// echo print_r($arrayOrden_compra);
	if ($arrayOrden_compra) {
		$flag_encabezado = true;
		foreach ($arrayOrden_compra as $key => $value) {
			$_material = $value["cs_descripcion1"];
			if ($flag_encabezado) {
				$flag_encabezado = false;
				$encabezado = '
						<span><strong>Información del proyecto</strong></span>
						<table class="table">
							<tbody>
								<tr>
									<td class="cell-detail">
										<div class="row">
											<div class="col-sm-2">
												<span>Orden de compra:</span>
												<span class="cell-detail-description">' . $value["cs_num_de_orden"] . ' - ' . $value["cs_tipo_de_orden"] . '</span>
												<span class="cell-detail-description">Generado: ' . $value["cs_fecha_generacion_oc"] . '</span>
											</div>
											<div class="col-sm-2">
												<span>Requisición:</span>
												<span class="cell-detail-description">' . $value["cs_num_requisicion"] . ' - ' . $value["cs_tipo_requisicion"] . '</span>
												<span class="cell-detail-description">Recibido: ' . $value["fecha_recibido_en_cs"] . '</span>
											</div>
											<div class="col-sm-2">
												<span>Importado / Nacional:</span>
												<span class="cell-detail-description">' . $value["cs_importado_nacional"] . '</span>
												<span class="cell-detail-description">Incoterm - ' . $value["cs_incoterm"] . '</span>
											</div>
											<div class="col-sm-3">
												<span>Usuario: ' . $value["cs_usuario"] . '</span>
												<span class="cell-detail-description">' . $value["cs_comprador"] . '</span>
												<span class="cell-detail-description">Yk - ' . $value["cs_yk"] . '</span>
											</div>
											<div class="col-sm-3">
												<span>Términos de pago:</span>
												<span class="cell-detail-description">' . $value["cs_termino_pago"] . '</span>
											</div>
										</div>
									</td>
								</tr>
								<tr>
									<td class="cell-detail">
										<div class="row">
											<div class="col-sm-3">
												<span>Origen:</span>
												<span class="cell-detail-description">' . $value["cs_proveedor"] . '</span>
												<span class="cell-detail-description">Enviado: ' . $value["cs_fecha_envio_a_proveedor"] . '</span>
											</div>
											<div class="col-sm-3">
												<span>Destino:</span>
												<span class="cell-detail-description"></span>
												<span class="cell-detail-description">Llegada al almacén - ' . $value["cs_llegada_prometida_a_almacen"] . '</span>
											</div>
											<div class="col-sm-6">
												<span>Observacion General:</span>
												<span class="cell-detail-description">' . $value["cs_observacion_general"] . '</span>
											</div>
										</div>
									</td>
								</tr>
								<tr><td></td></tr>
							</tbody>
						</table>
					';
			}
		}
	} else {
		echo '<p>No hay registros en esta tabla...</p>';
	}


	/*** SE CREA TABLA DE CONTENIDO ***/
	$table_actividades = '
			<div class="panel-body table-responsive">
				<div class="row">
					<div class="col-sm-12">
						<input type="hidden" name="actividades" id="actividades" value="" class="actividades">
						<table id="table1" class="table table-striped table-hover table-fw-widget">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width:1%;"></th>
									<th style="width:25%;">Actividad</th>
									<th style="width:1%;"></th>
									<th style="width:17%;">Fechas</th>
									<!--<th>Creador</th>-->
									<!--<th>Última Actualización</th>-->
									<th style="width:4%;">Costo</th>
									<th style="width:4%;">Tiempo</th>
									<th>Responsable</th>
									<!--<th>Estado</th>-->
									<th style="width:1%;" class="icon">
										<span class="mdi mdi-attachment-alt"></span>
									</th>
									<th style="width:5%;"></th>
								</tr>
							</thead>
							<tbody>
		';

	/***** SE CREA LA TABLA DE ACTIVIDADES DEL MATERIAL *****/
	$arrayActividades = $this->orden_compra->getActividadesCarga($r->getArgs()[1]);
	// echo print_r("<pre>");
	// echo print_r($arrayActividades);
	// echo print_r("</pre>");
	if ($arrayActividades) {
		$flag_usuarios = false;
		foreach ($arrayActividades as $key => $value) {

			/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
			switch ($value["estado"]) {
				case '0':
					// se asigna contenido de la columna de estado
					$col_stasus = '<td class="nexos-txt-danger"><span class="mdi mdi-dot-circle icon"></span></td>';

					$_popupHabilita = $alert->_alert_modal_mod_success($value['id'], "Realmente desea habilitar este elemento?", $_dbTable);
					$vista .= $_popupHabilita[0];
					$_jsScripts .= $_popupHabilita[1];

					break;

				case '1':
					// se asigna contenido de la columna de estado
					$col_stasus = '<td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>';

					$_popupHabilita = $alert->_alert_modal_mod_success($value['id'], "Realmente desea habilitar este elemento?", $_dbTable);
					$vista .= $_popupHabilita[0];
					$_jsScripts .= $_popupHabilita[1];

					break;

				case '2':
					// se asigna contenido de la columna de estado
					$col_stasus = '<td class="nexos-txt-warning"><span class="mdi mdi-dot-circle icon"></span></td>';

					$_popupHabilita = $alert->_alert_modal_mod_success($value['id'], "Realmente desea habilitar este elemento?", $_dbTable);
					$vista .= $_popupHabilita[0];
					$_jsScripts .= $_popupHabilita[1];

					break;

				case '3':
					// se asigna contenido de la columna de estado
					$col_stasus = '<td class="nexos-txt-warning"><span class="mdi mdi-dot-circle icon"></span></td>';

					$_popupHabilita = $alert->_alert_modal_mod_success($value['id'], "Realmente desea habilitar este elemento?", $_dbTable);
					$vista .= $_popupHabilita[0];
					$_jsScripts .= $_popupHabilita[1];

					break;
			}
			/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

			/****** SE FILTRA LA COLUMNA DE ACCIONES POR RESPONSABLE ******/
			if ($value["responsable"]) {
				$col_check = '
						<td class="cell-detail">
							<div class="be-checkbox">
								<input type="checkbox" id="check_' . $value["id"] . '" name="id" class="actividades" value="' . $value["id"] . '">
								<label for="check_' . $value["id"] . '"></label>
							</div>
						</td>
					';
				$col_action = '
						<td class="actions">
							<a href="#" class="icon"><span id="#edita_' . $value['id'] . '"  class="mdi mdi-square-right"></span></a>
						</td>
					';
				$col_responsble = '
						<td class="user-avatar cell-detail user-info">
							<img src="' . BASE_URL . 'public/img/users/' . $value["avatar"] . '" alt="' . $value["nom_usuario"] . '">
							<span>' . $value["nom_usuario"] . '</span>
							<span class="cell-detail-description">Perfil</span>
						</td>
					';
			} else {
				$flag_usuarios = true;
				$col_check = '
						<td class="cell-detail">
						</td>
					';
				$col_action = '
						<td class="actions">
							<a href="#" class="icon"><span id="#edita_' . $value['id'] . '"  data-toggle="modal" data-target="#edita_' . $value['id'] . '"  class="mdi mdi-assignment-account"></span></a>
						</td>
					';
				$col_responsble = '
						<td class="user-avatar cell-detail user-info">
							<span>No se ha asignado responsable</span>
						</td>
					';


				/*** POPUP DE ASIGNACION DE RESPONSABLES ***/
				$form_edit_table = '
						<input type="hidden" name="id" value="' . $value['id'] . '" class="form-control">
						<div class="form-group col-xs-12">
							<label>Usuarios:</label>
							%slct_usuarios%
						</div>
						<div class="row"></div>
					';

				// genero el select de usuarios
				$form_edit_table = str_replace("%slct_usuarios%", $this->usuarios->getHtmlSelect("responsable", $value["id"], $ssn_id_cliente), $form_edit_table);

				$_popupEdita = $form_edita->_form_modal_update($value['id'], "Asignar Responsables", $form_edit_table, $_dbTable);
				$vista .= $_popupEdita[0];
				$_jsScripts .= $_popupEdita[1];
				/*** FIN POPUP DE ASIGNACION DE RESPONSABLES ***/
			}
			/****** FIN SE FILTRA LA COLUMNA DE ACCIONES POR RESPONSABLE ******/


			/**** Se maqueta contenido de la tabla ****/
			$table_actividades .= '<tr>';

			// Columna de checkbox
			$table_actividades .= $col_check;

			// Columna de actiidad
			$table_actividades .= '
					<td class="cell-detail"> 
						<span>' . $value["nombre"] . '</span>
						<span class="cell-detail-description">' . $value["descripcion"] . '</span>
					</td>
				';
			// Columna de estado
			$table_actividades .= $col_stasus;

			// Columna creado por 
			// $table_actividades.= '
			// 	<td class="user-avatar cell-detail user-info">
			// 		<img src="%root_file%img/avatar4.png" alt="Avatar">
			// 		<span>Benji Harper</span><span class="cell-detail-description">Designer</span>
			// 	</td>
			// ';

			// Columna fechas
			$table_actividades .= '
					<td class="cell-detail">
						<span class="cell-detail-description">Creado - ' . $value["fecha_creacion"] . '</span>
						<span class="cell-detail-description">Iniciado - ' . $value["fecha_hora_inicio"] . '</span>
						<span class="cell-detail-description">Finalizado - ' . $value["fecha_hora_finalizacion"] . '</span>
					</td>
				';

			// Columna de Costo
			if ($value["costo_aprobado"] > 0) {
				$costo = round(($value["costo_real"] * 100) / $value["costo_aprobado"]);
			} else {
				$costo = 0;
			}
			$col_costo = '
					<td class="milestone">
						<span class="version">' . $value["costo_real"] . ' / ' . $value["costo_aprobado"] . ' (' . $value["codigo"] . ')</span>
						<div class="progress">
							<div style="width: ' . $costo . '%" class="progress-bar progress-bar-primary"></div>
						</div>
					</td>
				';
			$table_actividades .= $col_costo;

			// Columna de tiempo
			if ($value["tiempo_aprobado"] > 0) {
				$tiempo = round(($value["tiempo_real"] * 100) / $value["tiempo_aprobado"]);
			} else {
				$tiempo = 0;
			}
			$col_tiempo = '
					<td class="milestone">
						<span class="version">' . $value["tiempo_real"] . ' / ' . $value["tiempo_aprobado"] . ' (minutos)</span>
						<div class="progress">
							<div style="width: ' . $tiempo . '%" class="progress-bar progress-bar-primary"></div>
						</div>
					</td>
				';
			$table_actividades .= $col_tiempo;

			// Columna responsable				
			$table_actividades .= $col_responsble;

			// Columna de Entregables adjuntos
			$table_actividades .= '
					<td class="actions">
						<div class="tools">
							<a href="#" class="icon" target="_blank"><span class="mdi mdi-collection-pdf"></span></a>
						</div>
					</td>
				';

			// se asigna la columna de acciones
			$table_actividades .= $col_action;

			$table_actividades .= '</tr>';
		}
		$table_actividades .= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
	}
}

/*** FIN CREACION DE TABLA DE CONTENIDO ***/


/*** POPUP DE ASIGNACION DE RESPONSABLES ***/
$form_edit_table = '
		<input type="text" name="id" value="' . $value['id'] . '" class="form-control">
		<div class="form-group col-xs-12">
			<label>Usuarios:</label>
			%slct_usuarios%
		</div>
		<div class="row"></div>
	';

// genero el select de usuarios
$form_edit_table = str_replace("%slct_usuarios%", $this->usuarios->getHtmlSelect("responsable", $value["id"], $ssn_id_cliente), $form_edit_table);

$_popupEdita = $form_edita->_message_title_modal("edita", "Asignar Responsables", $form_edit_table);
$vista .= $_popupEdita[0];
$_jsScripts .= $_popupEdita[1];
/*** FIN POPUP DE ASIGNACION DE RESPONSABLES ***/


/**** CONTENIDO DEL MODULO EN PANTALLA ****/
$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Actividades de Material - ' . $_material . '
				<div class="tools">
					<a href="' . BASE_URL . 'proyecto/cargas_/' . $r->getArgs()[0] . '"class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>
				</div>
				<span class="panel-subtitle">Muestra las actividades realizadas para el material <strong>' . $_material . '</strong>.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%encabezado%
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';

/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
$vista .= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>

	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
			%js-ajax%
	    </script>
	';

/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%js-ajax%", $_jsAjax, $vista);
$vista = str_replace("%encabezado%", $encabezado, $vista);
$vista = str_replace("%content%", $table_actividades, $vista);

// Se asiga codigo JS generado de la tabla de contenido
$vista .= $_jsScripts;

// SE PINTA CONTENIDO EN PANTALLA
echo $vista;
