<?php
  /******* INICIO INFORMACION DEL PROYECTO *********/
  $vista = '';


  /**** CONTENIDO DE LA CAJA DE PESTA;AS ****/
  $panel_tab ='
    <div class="panel panel-border panel-contrast">
      <div class="panel-heading panel-heading-contrast">
        Resumen de Servicio - %nom_proyecto% (%nom_material%)
        <div class="tools">
          <a href="' . BASE_URL . 'proyecto/ver"class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>
          <span class="icon mdi mdi-settings"></span>
        </div>
        <span class="panel-subtitle"></span>
      </div>
      <div class="panel-body xs-mt-12">
        <div class="tab-container">
          <ul class="nav nav-tabs nav-tabs-warning">
            <li class="active"><a href="#panel_1" data-toggle="tab">Resumen</a></li>
            <li><a href="#panel_2" data-toggle="tab">Entregables</a></li>
            <li><a href="#panel_3" data-toggle="tab">Gráficas</a></li>
          </ul>
          <div class="tab-content">
            %tab_content%
          </div>
        </div>
      </div>
    </div>
  ';

  $tab = '';
  /**** CONTENIDO DE LA PRIMER PESTA;A ****/
  $_panel1 ='
    <div id="panel_1" class="tab-pane active cont">
    %contenido1%
    </div>
  ';

  $_tabla1 = '
    <div class="panel panel-border panel-contrast">
      <div class="panel-heading panel-heading-contrast">
        Resumen Actividades</span>
      </div>
      <div class="panel-body table-responsive">
        <table id="table1" class="table table-striped table-hover table-fw-widget">
          <thead>
            <tr class="nexos-encabezado">
              <th style="width:15%;">Actividad</th>
              <th style="width:5%;">#</th>
              <th style="width:15%;">Creador</th>
              <th style="width:15%;">Última Actualización</th>
              <th style="width:15%;">Costo</th>
              <th style="width:15%;">Responsable</th>
              <th style="width:15%;">Estado</th>
              <th style="width:5%;"></th>
            </tr>
          </thead>
          <tbody>
            <tr class="odd gradeA">
              <td class="cell-detail"> <span>%hito%</span><span class="cell-detail-description">%actividad%</span></td>
              <td class="nexos-txt-warning"><span class="mdi mdi-dot-circle icon"></span></td>
              <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar4.png" alt="Avatar"><span>Benji Harper</span><span class="cell-detail-description">Designer</span></td>
              <td class="cell-detail"><span>April 22, 2016</span><span class="cell-detail-description">14:45</span></td>
              <td class="milestone"><span class="version">800.000 / 1.200.000</span>
                <div class="progress">
                  <div style="width: 75%" class="progress-bar progress-bar-primary"></div>
                </div>
              </td>
              <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar6.png" alt="Avatar"><span>Penelope Thornton</span><span class="cell-detail-description">Developer</span></td>
              <td class="cell-detail"><span>Pendiente</span><span class="cell-detail-description">Recibir Documentos</span></td>
              <td class="actions">
                <div class="tools">
                  <a href="#" class="icon" target="_blank"><span class="mdi mdi-collection-pdf"></span></a>
                </div>
              </td>
            </tr>
            <tr class="gradeA">
              <td class="cell-detail"> <span>%hito%</span><span class="cell-detail-description">%actividad%</span></td>
              <td class="nexos-txt-warning"><span class="mdi mdi-dot-circle icon"></span></td>
              <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar5.png" alt="Avatar"><span>Justine Myranda</span><span class="cell-detail-description">Designer</span></td>
              <td class="cell-detail"><span>April 15, 2016</span><span class="cell-detail-description">10:00</span></td>
              <td class="milestone"><span class="version">300.000 / 1.000.000</span>
                <div class="progress">
                  <div style="width: 33%" class="progress-bar progress-bar-primary"></div>
                </div>
              </td>
              <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar4.png" alt="Avatar"><span>Benji Harper</span><span class="cell-detail-description">Designer</span></td>
              <td class="cell-detail"><span>Pendiente</span><span class="cell-detail-description">Consertar cita</span></td>
              <td class="actions">
                <div class="tools">
                  <a href="#" class="icon" target="_blank"><span class="mdi mdi-collection-pdf"></span></a>
                </div>
              </td>
            </tr>
            <tr class="gradeA">
              <td class="cell-detail"> <span>%hito%</span><span class="cell-detail-description">%actividad%</span></td>
              <td class="nexos-txt-danger"><span class="mdi mdi-dot-circle icon"></span></td>
              <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar6.png" alt="Avatar"><span>Penelope Thornton</span><span class="cell-detail-description">Developer</span></td>
              <td class="cell-detail"><span>May 6, 2016</span><span class="cell-detail-description">8:30</span></td>
              <td class="milestone"><span class="version">2.000.000 / 2.700.000</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-primary"></div>
                </div>
              </td>
              <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar.png" alt="Avatar"><span>Kristopher Donny</span><span class="cell-detail-description">Designer</span></td>
              <td class="cell-detail"><span>Retrasado</span><span class="cell-detail-description">2017-01-20</span></td>
              <td class="cell-detail"></td>
            </tr>
            <tr class="gradeA">
              <td class="cell-detail"> <span>%hito%</span><span class="cell-detail-description">%actividad%</span></td>
              <td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>
              <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar3.png" alt="Avatar"><span>Sherwood Clifford</span><span class="cell-detail-description">Developer</span></td>
              <td class="cell-detail"><span>April 8, 2016</span><span class="cell-detail-description">17:24</span></td>
              <td class="milestone"><span class="version">1.100.000 / 2.000.000</span>
                <div class="progress">
                  <div style="width: 55%" class="progress-bar progress-bar-primary"></div>
                </div>
              </td>
              <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar5.png" alt="Avatar"><span>Justine Myranda</span><span class="cell-detail-description">Designer</span></td>
              <td class="cell-detail"><span>Completado</span><span class="cell-detail-description"></span></td>
              <td class="actions">
                <div class="tools">
                  <a href="#" class="icon" target="_blank"><span class="mdi mdi-collection-pdf"></span></a>
                </div>
              </td>
            </tr>
            <tr class="gradeA">
              <td class="cell-detail"> <span>%hito%</span><span class="cell-detail-description">%actividad%</span></td>
              <td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>
              <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar.png" alt="Avatar"><span>Kristopher Donny</span><span class="cell-detail-description">Designer</span></td>
              <td class="cell-detail"><span>Mars 18, 2016</span><span class="cell-detail-description">13:02</span></td>
              <td class="milestone"><span class="version">5.000.000 / 5.200.000</span>
                <div class="progress">
                  <div style="width: 98%" class="progress-bar progress-bar-primary"></div>
                </div>
              </td>
              <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar3.png" alt="Avatar"><span>Sherwood Clifford</span><span class="cell-detail-description">Developer</span></td>
              <td class="cell-detail"><span>Completado</span><span class="cell-detail-description"></span></td>
              <td class="actions">
                <div class="tools">
                  <a href="#" class="icon" target="_blank"><span class="mdi mdi-collection-pdf"></span></a>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  ';

  $_panel1 = str_replace("%contenido1%", $_tabla1, $_panel1);
  $tab.= $_panel1;
  /**** FIN CONTENIDO DE LA PRIMER PESTA;A ****/


  /**** CONTENIDO DE LA SEGUNDA PESTA;A ****/
  $_panel2 ='
    <div id="panel_2" class="tab-pane cont">
      %contenido2%
    </div>
  ';

  /**** SE CREA LA TABLA DE ENTREGABLES DE ACTIVIDADES POR MATERIAL DEL PROYECTO ****/
  $_tabla2 = '
    <div class="panel panel-border panel-contrast">
      <div class="panel-heading panel-heading-contrast">
        Entregables de Actividad</span>
      </div>
      <div class="panel-body table-responsive">
        <table id="table2" class="table table-striped table-hover table-fw-widget">
          <thead>
            <tr class="nexos-encabezado">
              <th style="width:5%;">Entregable</th>
              <th style="width:55%;">Actividad</th>
              <th style="width:20%;">Subido por</th>
              <th style="width:20%;">Fecha</th>
            </tr>
          </thead>
          <tbody>
            <tr class="odd gradeX">
                <td class="actions">
                  <div class="tools">
                    <a href="#" class="icon" target="_blank"><span class="mdi mdi-collection-pdf"></span></a>
                  </div>
                </td>
                <td class="cell-detail"> <span>%actividad%</span><span class="cell-detail-description">%hito%</span></td>
                <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar4.png" alt="Avatar"><span>Benji Harper</span><span class="cell-detail-description">Designer</span></td>
                <td class="cell-detail"><span>April 22, 2016</span><span class="cell-detail-description">14:45</span></td>
            </tr>
            <tr class="gradeX">
              <td class="actions">
                <div class="tools">
                  <a href="#" class="icon" target="_blank"><span class="mdi mdi-collection-pdf"></span></a>
                </div>
              </td>
              <td class="cell-detail"> <span>%actividad%</span><span class="cell-detail-description">%hito%</span></td>
              <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar5.png" alt="Avatar"><span>Justine Myranda</span><span class="cell-detail-description">Designer</span></td>
              <td class="cell-detail"><span>April 15, 2016</span><span class="cell-detail-description">10:00</span></td>
            </tr>
            <tr class="gradeX">
                <td class="actions">
                  <div class="tools">
                    <a href="#" class="icon" target="_blank"><span class="mdi mdi-collection-image"></span></a>
                  </div>
                </td>
                <td class="cell-detail"> <span>%actividad%</span><span class="cell-detail-description">%hito%</span></td>
                <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar6.png" alt="Avatar"><span>Penelope Thornton</span><span class="cell-detail-description">Developer</span></td>
                <td class="cell-detail"><span>May 6, 2016</span><span class="cell-detail-description">8:30</span></td>
            </tr>
            <tr class="gradeX">
              <td class="actions">
                <div class="tools">
                  <a href="#" class="icon" target="_blank"><span class="mdi mdi-collection-image"></span></a>
                </div>
              </td>
              <td class="cell-detail"> <span>%actividad%</span><span class="cell-detail-description">%hito%</span></td>
              <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar3.png" alt="Avatar"><span>Sherwood Clifford</span><span class="cell-detail-description">Developer</span></td>
              <td class="cell-detail"><span>April 8, 2016</span><span class="cell-detail-description">17:24</span></td>
            </tr>
            <tr class="gradeX">
                <td class="actions">
                  <div class="tools">
                    <a href="#" class="icon" target="_blank"><span class="mdi mdi-collection-pdf"></span></a>
                  </div>
                </td>
                <td class="cell-detail"> <span>%actividad%</span><span class="cell-detail-description">%hito%</span></td>
                <td class="user-avatar cell-detail user-info"><img src="%root_file%img/avatar.png" alt="Avatar"><span>Kristopher Donny</span><span class="cell-detail-description">Designer</span></td>
                <td class="cell-detail"><span>Mars 18, 2016</span><span class="cell-detail-description">13:02</span></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  ';

  $_panel2 = str_replace("%contenido2%", $_tabla2, $_panel2);
  $tab.= $_panel2;
  /**** FIN CONTENIDO DE LA SEGUNDA PESTA;A ****/

  /**** CONTENIDO DE LA TERCERA PESTA;A ****/
  $_panel3 ='
    <div id="panel_3" class="tab-pane cont">
      %contenido3%
    </div>
  ';
  $_grafica ='
    <div class="panel panel-border panel-contrast">
      <div class="panel-heading panel-heading-contrast">
        Seguimiento
      </div>
      <div class="panel-body table-responsive">
        <div id="chartdiv" style="width: 100%; height: 400px;"></div>
      </div>
    </div>
  ';
  $_panel3 = str_replace("%contenido3%", $_grafica, $_panel3);
  $tab.= $_panel3;
  /**** FIN CONTENIDO DE LA TERCERA PESTA;A ****/

  /**** SE AGREGA CONTENIDO AL PANEL TAB ****/
  $panel_tab = str_replace("%tab_content%", $tab, $panel_tab);
  $vista.=$panel_tab;
  /**** FIN CONTENIDO DE LA CAJA DE PESTA;AS ****/


  /**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
  $vista.= '
    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
    <script src="%root_file%js/main.js" type="text/javascript"></script>
    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
    <script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>
    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
    <script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
    <script type="text/javascript">
      $.fn.niftyModal(\'setDefaults\',{
        overlaySelector: \'.modal-overlay\',
        closeSelector: \'.modal-close\',
        classAddAfterOpen: \'modal-show\',
      });
      $(document).ready(function(){
          //initialize the javascript
        App.init();
      });
      $(document).ready(function(){
        //initialize the javascript
        App.init();
        App.dataTables();
      });
    </script>
  ';


  /**** CARGA DE ARCHIVOS JS DE LA GRAFICA GRANT ****/
  $vista.= '
    <script src="%root_file%amcharts/amcharts.js" type="text/javascript"></script>
    <script src="%root_file%amcharts/serial.js" type="text/javascript"></script>
    <script src="%root_file%amcharts/gantt.js" type="text/javascript"></script>

    <script>
      var chart = AmCharts.makeChart("chartdiv", {
        "type": "gantt",
        "period": "DD",
        "valueAxis": {
          "type": "date"
        },
        "brightnessStep": 10,
        "graph": {
          "fillAlphas": 1,
          "balloonText": "[[open]] - [[value]]"
        },
        "rotate": true,
        "categoryField": "category",
        "segmentsField": "segments",
        "dataDateFormat": "YYYY-MM-DD",
        "startDateField": "start",
        "endDateField": "end",
        "dataProvider": [{
        "category": "John",
        "segments": [{
          "start": "2015-01-02",
          "end": "2015-01-03"
        }, {
          "start": "2015-01-04",
          "end": "2015-01-05"
        }, {
          "start": "2015-01-07",
          "end": "2015-01-10"
        }]
        }, {
          "category": "Smith",
          "segments": [{
          "start": "2015-01-01",
          "end": "2015-01-02"
        }, {
          "start": "2015-01-10",
          "end": "2015-01-15"
        }]
        }, {
            "category": "Ben",
            "segments": [{
            "start": "2015-01-06",
            "end": "2015-01-09"
          }, {
            "start": "2015-01-11",
            "end": "2015-01-18"
          }, {
            "start": "2015-01-22",
            "end": "2015-01-21"
          }]
        }],
        "chartCursor": {
          "valueBalloonsEnabled": false,
          "cursorAlpha": 0,
          "valueLineBalloonEnabled": true,
          "valueLineEnabled": true,
          "valueZoomable":true,
          "zoomable":false
        },

        "valueScrollbar": {
          "position":"top",
          "autoGridCount":true,
          "color":"#000000"
        }
      });
    </script>
    ';

    /******* FIN INFORMACION DEL PROYECTO *********/


    /******* FIN INFORMACION DEL PROYECTO *********/

  /**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
  $vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);

  echo $vista;

?>

