<?php

  /**** CARGA DE ARCHIVOS DE ESTILOS DE LA VISTA ****/
  $vista = '';

  /**** SE CREA LA LISTA DETALLADA DE PROYECTOS ****/
  $vista.= '
    <div class="panel panel-border panel-contrast">
      <div class="panel-heading panel-heading-contrast">
        Lista de Proyectos
        <div class="tools">
          <a href="' . BASE_URL . 'proyecto/administrar" > <span class="icon mdi mdi-plus"></span> </a> 
        </div>
      </div>
      <div class="panel-body table-responsive">
        <table id="table1" class="table table-striped table-hover table-fw-widget">
          <thead>
            <tr class="nexos-encabezado">
              <th >Proyecto</th>
              <th >Material</th>
              <th >Origen</th>
              <th >Destino</th>
              <th >Estado</th>
              <th ></th>
            </tr>
          </thead>
          <tbody>
            <tr class="odd gradeX">
              <td class="cell-detail"><span>Transporte de Gas Licuado</span><span class="cell-detail-description">Praxair</span></td>
              <td class="cell-detail"><span>Gas Licuado</span><span class="cell-detail-description">riesgo 3</span></td>
              <td class="cell-detail"><span>Puerto Buenventura</span><span class="cell-detail-description">Buenaventura (Colombia)</span></td>
              <td class="cell-detail"><span>Bodega Fontibon</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">8 / 15</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-danger"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
             <tr class="even gradeC">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chapinero</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
            <tr class="odd gradeA">
              <td class="cell-detail"><span>Bicarbonato de sodio</span><span class="cell-detail-description">Quimicos de Colombia</span></td>
              <td class="cell-detail"><span>Bicarbonato de sodio en polvo</span><span class="cell-detail-description">riesgo 9</span></td>
              <td class="cell-detail"><span>Bodega Cartagena</span><span class="cell-detail-description">Cartagena (Colombia)</span></td>
              <td class="cell-detail"><span>Laboratorio Chico</span><span class="cell-detail-description">Bogota (Colombia)</span></td>
              <td class="milestone"><span class="completed">10 / 30</span><span class="version">v1.2.0</span>
                <div class="progress">
                  <div style="width: 45%" class="progress-bar progress-bar-success"></div>
                </div>
              </td>
              <td class="actions">
                <a href="' . BASE_URL . 'proyecto/ver" class="icon"><span class="mdi mdi-eye"></span></a>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  ';

	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.='
    <!-- INICIO JS DE LA TABLA DE HITOS -->
    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
    <script src="%root_file%js/main.js" type="text/javascript"></script>
    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
    <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
    <script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>
    <script type="text/javascript">
      $(document).ready(function(){
        //initialize the javascript
        App.init();
        App.dataTables();
      });
    </script>
    <!-- FIN JS DE LA TABLA DE HITOS -->
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);

	echo $vista;

?>



