<?php
$_dbTable = "servicios_operador"; // SIN EL PREFIJO cmx_
$_jsScripts = "";

// se definen las variables de session
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

$r = new Request();
// print_r($r->getArgs());

$vista = '';

/********* POPUPS *********/
/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
// POPUP DE MUESTRA DE INFORMACION
$info = new Popup();
// POPUP DE ALERTA DE CONFIRMACION
$alert = new Popup();
// POPUP DE FORMULARIO DE EDICION 
$form_edita = new Popup();
// POPUP DE FORMULARIO DE CREACION 
$form_crea = new Popup();

/********* FIN POPUPS *********/


$dataOperador = $this->operadores->getOperador($r->getArgs()[0]);
// print_r("<pre>");
// print_r($dataOperador['nombre_proveedor']);
// print_r("</pre>");
$nombre_proveedor = $dataOperador["nombre_proveedor"];


/*** CREACION DE TABLA DE CONTENIDO ***/
if (isset($this->servicios_operador) /* && count($this->servicios_operador) */) {

	/*** SE CREA TABLA DE CONTENIDO ***/
	$table_servicios_operador = '
			<div class="row">
				<div class="col-sm-12">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width:10%;"></th>
									<th>Servico</th>
									<th>Tarifa</th>
									<th>Origen</th>
									<th>Destino</th>
									<th style="width:10%;"></th>
								</tr>
							</thead>
							<tbody>
		';

	$arrayPlantillas = $this->servicios_operador->getTabla($r->getArgs()[0]);
	// print_r("<pre>");
	// print_r($arrayPlantillas);
	// print_r("</pre>");
	if ($arrayPlantillas) {
		foreach ($arrayPlantillas as $key => $value) {

			/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
			switch ($value["estado"]) {
				case '0':
					// se asigna contenido de la columna de estado
					$col_stasus = '
							<td class="nexos-txt-danger">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

					$_popupHabilita = $alert->_alert_modal_mod_success($value['id'], "Realmente desea habilitar este elemento?", $_dbTable);
					$vista .= $_popupHabilita[0];
					$_jsScripts .= $_popupHabilita[1];

					// se asigna contenudo de la columna de acciones
					$col_action = '
							<td class="actions">
								<a href="#" class="icon"><span id="#habilita_' . $value['id'] . '" data-toggle="modal" data-target="#habilita_' . $value['id'] . '" class="icon mdi mdi-check-circle"></span></a>
							</td>
						';
					break;

				case '1':
					// se asigna contenido de la columna de estado
					$col_stasus = '
							<td class="nexos-txt-success">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

					// se genera el formulario de edicion del registro

					// Se crea el select de servicio especial
					// $slct_servicio_especial = $this->servicios_especiales->getHtmlSelect("id_servicio_especial", $value["id_servicio_especial"]);
					$slct_servicio_especial = $this->servicios_operador->getHtmlSelect("id_servicio_especial", $value["id_servicio_especial"]);

					// Se crea el select de unidad de medida
					$slct_unidad_medida = $this->unidades_medida->getHtmlSelect("id_unidad_medida", $value["id_unidad_medida"]);

					// Se crea el select de monedas
					$slct_moneda = $this->monedas->getHtmlSelect("id_moneda", $value["id_moneda"]);

					// Se crea el select de origen
					$slct_origen = $this->municipios->getHtmlSelect("origen", $value["origen"]);

					// Se crea el select de origen
					$slct_destino = $this->municipios->getHtmlSelect("destino", $value["destino"]);

					$form_edit_table = '
							<input type="hidden" name="id" value="' . $value['id'] . '" class="form-control">
							<input type="hidden" name="id_operador" value="' . $r->getArgs()[0] . '" class="form-control">
							<div class="form-group col-xs-1"></div>
							<div class="form-group col-xs-6">
								<label>Servicio:</label>
								' . $slct_servicio_especial . ' 
							</div>
							<div class="form-group col-xs-4">
								<label>Unidades de Compra:</label>
								' . $slct_unidad_medida . ' 
							</div>
							<div class="row"></div>
							<div class="form-group col-xs-2"></div>
							<div class="form-group col-xs-4">
								<label>Valor:</label>
								<input type="number" min="0" name="valor" value="" placeholder="Valor" class="form-control text-right">
							</div>
							<div class="form-group col-xs-4">
								<label>Moneda:</label>
								' . $slct_moneda . ' 
							</div>
							<div class="row"></div>
							<div class="form-group col-xs-6">
								<label>Origen:</label>
								' . $slct_origen . ' 
							</div>
							<div class="form-group col-xs-6">
								<label>Destino:</label>
								' . $slct_destino . ' 
							</div>
							<div class="row"></div>
						';

					$_popupEdita = $form_edita->_form_modal_update($value['id'], "Editar Plantilla - " . $value['nombre_proveedor'], $form_edit_table, $_dbTable);
					$vista .= $_popupEdita[0];
					$_jsScripts .= $_popupEdita[1];


					$_popupElimina = $alert->_alert_modal_mod_danger($value['id'], "Realmente desea eliminar este elemento?", $_dbTable);
					$vista .= $_popupElimina[0];
					$_jsScripts .= $_popupElimina[1];

					// se asigna contenido de la columna de acciones
					$col_action = '
							<td class="actions">
								<span id="edita_' . $value['id'] . '" data-toggle="modal" data-target="#edita_' . $value['id'] . '" class="icon mdi mdi-edit"></span>
								<span id="elimina_' . $value['id'] . '"data-toggle="modal" data-target="#elimina_' . $value['id'] . '" class="icon mdi mdi-close-circle"></span>
							</td>
						';

					break;
			}
			/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

			// Se maqueta contenido de la tabla 
			$table_servicios_operador .= '<tr>';
			// Columna de estado
			$table_servicios_operador .= $col_stasus;
			// Columna de servicio especial
			$table_servicios_operador .= '
					<td class="cell-detail">
						<span>' . $value["nom_servicios_especial"] . '</span>
					</td>
				';
			// Columna de Tarifa
			$table_servicios_operador .= '
					<td class="cell-detail">
						<span>' . $value["valor"] . ' (' . $value["codigo"] . ')</span>
						<span class="cell-detail-description">' . $value["nom_unidad_medida"] . '</span>
					</td>
				';

			// Columna de Origen
			$table_servicios_operador .= '
					<td class="cell-detail">
						<span>' . $value["MUNICIPIO_ORIGEN"] . ' (' . $value["DEPTO_ORIGEN"] . ')</span>
						<span class="cell-detail-description">' . $value["PAIS_ORIGEN"] . '</span>
					</td>
				';

			// Columna de Destino
			$table_servicios_operador .= '
					<td class="cell-detail">
						<span>' . $value["MUNICIPIO_DESTINO"] . ' (' . $value["DEPTO_DESTINO"] . ')</span>
						<span class="cell-detail-description">' . $value["PAIS_DESTINO"] . '</span>
					</td>
				';

			// se asigna la columna de acciones
			$table_servicios_operador .= $col_action;

			$table_servicios_operador .= '</tr>';
		}

		$table_servicios_operador .= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
	} else {
		echo '<p>no hay registros en esta tabla...</p>';
	}
} else {
	echo '<p>no hay registros en esta tabla...</p>';
}
/*** FIN CREACION DE TABLA DE CONTENIDO ***/


/**** CONTENIDO DEL MODULO EN PANTALLA ****/
$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Servicios Operador - ' . $nombre_proveedor . '
				<div class="tools">
					<a href="' . BASE_URL . 'proyecto/operadores/"class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>
					<a href="#" data-toggle="modal" data-target="#crea_' . $_dbTable . '" class="cell-detail  hint--top"  data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a> 
				</div>
				<span class="panel-subtitle">Establece un molde de actividades que pueden ser usados con frecuencia para en el desarrollo de un nuevo proyecto.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
$vista .= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';


/****** CREACION CONTENIDO DE POPUPS ******/

// CONTENIDO DEL POPUP DE FORMULARIO DE CREACION

// Se crea el select de servicio especial
// $slct_servicio_especial = $this->servicios_especiales->getHtmlSelect("id_servicio_especial", "");
$slct_servicio_especial = $this->servicios_operador->getHtmlSelect("id_servicio_especial", "");

// Se crea el select de unidad de medida
$slct_unidad_medida = $this->unidades_medida->getHtmlSelect("id_unidad_medida", "");

// Se crea el select de monedas
$slct_moneda = $this->monedas->getHtmlSelect("id_moneda", "");

// Se crea el select de origen
$slct_origen = $this->municipios->getHtmlSelect("origen", "101");

// Se crea el select de origen
$slct_destino = $this->municipios->getHtmlSelect("destino", "101");

$forms = '
		<input type="hidden" name="id_operador" value="' . $r->getArgs()[0] . '" class="form-control">
		<div class="form-group col-xs-1"></div>
		<div class="form-group col-xs-6">
			<label>Servicio:</label>
			' . $slct_servicio_especial . ' 
		</div>
		<div class="form-group col-xs-4">
			<label>Unidades de Compra:</label>
			' . $slct_unidad_medida . ' 
		</div>
		<div class="row"></div>
		<div class="form-group col-xs-2"></div>
		<div class="form-group col-xs-4">
			<label>Valor:</label>
			<input type="number" min="0" name="valor" value="" placeholder="Valor" class="form-control text-right">
		</div>
		<div class="form-group col-xs-4">
			<label>Moneda:</label>
			' . $slct_moneda . ' 
		</div>
		<div class="row"></div>
		<div class="form-group col-xs-6">
			<label>Origen:</label>
			' . $slct_origen . ' 
		</div>
		<div class="form-group col-xs-6">
			<label>Destino:</label>
			' . $slct_destino . ' 
		</div>
		<div class="row"></div>
	';

$_popupCrea = $form_crea->_form_modal_simple_insert("crea_" . $_dbTable, "Crear Plantilla", $forms, $_dbTable);
$vista .= $_popupCrea[0];
$_jsScripts .= $_popupCrea[1];


/****** FIN CREACION CONTENIDO DE POPUPS ******/

/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%content%", $table_servicios_operador, $vista);

// Se asiga codigo JS generado de la tabla de contenido
$vista .= $_jsScripts;

// SE PINTA CONTENIDO EN PANTALLA
echo $vista;
