<?php
	/******* INICIO INFORMACION DEL PROYECTO *********/
	$vista = '';

	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();

	// INFORMACIÓN GENERAL DE LA EMPRESA
	$info_contenido_1 = '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Praxair
				<div class="tools">
					<a href="' . BASE_URL . 'clientes/editar/" class="icon"><span class="mdi mdi-edit"></span></a>
				</div>
			</div>
		</div>
		<table class="table">
			<tbody>
				<tr>
					<td class="cell-detail">
						<div class="row">
							<div class="col-sm-4">
								<span>Nit</span>
								<span class="cell-detail-description">800555666-4</span>
							</div>
							<div class="col-sm-4">
								<span>Nombre cliente</span>
								<span class="cell-detail-description">Praxair Gases Industriales Ltda.</span>
							</div>
							<div class="col-sm-4">
								<span>Sigla</span>
								<span class="cell-detail-description">PRAXAIR</span>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<div class="row">
							<div class="col-sm-12">
								<span>Actividad</span>
								<span class="cell-detail-description">Produccion Y Distribucion De Gases Industriales, Medicinales, Especiales Y Mesclas // Materias Primas </span>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<div class="row">
							<div class="col-sm-4">
								<span>Dirección</span>
								<span class="cell-detail-description">Calle 106 # 56-12</span>
							</div>
							<div class="col-sm-4">
								<span>Teléfono</span>
								<span class="cell-detail-description">(57) 1 3670400</span>
							</div>
							<div class="col-sm-4">
								<span>E-mail</span>
								<span class="cell-detail-description">info@praxair.com</span>
							</div>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	';
	$vista.= $info->_bootstrap_modal_dialog("info_1" , "Información General Cliente" , $info_contenido_1 );

	// INFORMACIÓN DEL MATERIAL - PENDIENTE AJUSTAR
	$info_contenido_2 = '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Socios
				<div class="tools">
					<a href="' . BASE_URL . 'clientes/socios/" class="icon"><span class="mdi mdi-accounts-list-alt"></span></a>
				</div>
			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
				<th></th>
				<th style="width:5%;"></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td class="cell-detail">
						<span>Maria Camila Torres</span>
						<span class="cell-detail-description">Representante Legal</span>
					</td>
					<td class="nexos-txt-success">
						<a href="' . BASE_URL . 'clientes/verificacion_socio/"><span class="icon mdi mdi-shield-check"></span></a> 
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<span>Daniel Galvis</span>
						<span class="cell-detail-description">Socio Mayoritario</span>
					</td>
					<td class="nexos-txt-success">
						<a href="' . BASE_URL . 'clientes/verificacion_socio/"><span class="icon mdi mdi-shield-check"></span></a> 
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<span>Fernando Alayon</span>
						<span class="cell-detail-description">Socio</span>
					</td>
					<td class="nexos-txt-warning">
						<a href="' . BASE_URL . 'clientes/verificacion_socio/"><span class="icon mdi mdi-shield-check"></span></a> 
					</td>
				</tr>
			</tbody>
		</table>
	';
	// $vista.= $info->_bootstrap_modal_dialog("info_2" , "Estado Antecedentes Socios" , $info_contenido_2 );

	// INFORMACIÓN DEL ORIGEN - PENDIENTE AJUSTAR
	$info_contenido_3 = '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Praxair
			</div>
		</div>
		<table class="table">
			<tbody>
				<tr>
					<td class="cell-detail">
						<div class="row">
							<div class="col-sm-12">
								<span>Nit</span>
								<span class="cell-detail-description">800555666-4</span>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<div class="row">
							<div class="col-sm-6">
								<span>Tipo Documento</span>
								<span class="cell-detail-description">Jurídico</span>
							</div>
							<div class="col-sm-6">
								<span>Régimen</span>
								<span class="cell-detail-description">Régimen Común</span>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<div class="row">
							<div class="col-sm-12">
								<span>Condición Tributaria</span>
								<span class="cell-detail-description"></span>
								<span>Condición Tributaria</span>
								<span class="cell-detail-description"></span>
							</div>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	';
	// $vista.= $info->_bootstrap_modal_dialog("info_3" , "Información Tributaria Empresa" , $info_contenido_3 );

	// INFORMACIÓN DEL DESTINO - PENDIENTE AJUSTAR
	$info_contenido_4 = '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Praxair
			</div>
		</div>
		<table class="table">
			<tbody>
				<tr>
					<td class="cell-detail">
						<div class="row">
							<div class="col-sm-4">
								<span>Ciudad</span>
								<span class="cell-detail-description">Bogotá</span>
							</div>
							<div class="col-sm-4">
								<span>Estado / Departamento</span>
								<span class="cell-detail-description">Cundinamarca</span>
							</div>
							<div class="col-sm-4">
								<span>País</span>
								<span class="cell-detail-description">Colombia</span>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<div class="row">
							<div class="col-sm-6">
								<span>Dirección</span>
								<span class="cell-detail-description">Calle 106 # 56-12</span>
							</div>
							<div class="col-sm-6">
								<span>Código Postal</span>
								<span class="cell-detail-description">11002</span>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<div class="row">
							<div class="col-sm-12">
								<span>Indicaciones de ubicación</span>
							<span class="cell-detail-description">Frente al Autódromo de Tocancipá</span>
							</div>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	';
	// $vista.= $info->_bootstrap_modal_dialog("info_4" , "Ubicación Empresa" , $info_contenido_4 );



	// POPUP DE ALERTA DE CONFIRMACION ELIMINACION
	$alert = new Popup();
	$vista.= $alert->_alert_modal_mod_danger("elimina", "Realmente desea eliminar este elemento?");

	// POPUP DE ALERTA DE CONFIRMACION HABILITAR
	$alert = new Popup();
	$vista.= $alert->_alert_modal_mod_success("habilita", "Realmente desea habilitar este elemento?");

  $vista.= '
      <!-- Nifty Modal-->
      <div id="colored-warning" role="dialog" class="modal-container colored-header colored-header-warning modal-effect-12">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
            <h3 class="modal-title">Custom Header Color</h3>
          </div>
          <div class="modal-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultrices euismod lobortis. Donec fermentum mattis velit id pretium. Suspendisse sed tortor sed diam lobortis tempus at sed lacus. Phasellus semper ex auctor libero scelerisque ultricies.</p>
            <p>Fusce sit amet lacus arcu. Pellentesque iaculis massa vitae ullamcorper venenatis. Cras metus dolor, maximus sit amet est nec, pharetra blandit elit sagittis vehicula.</p>
          </div>
          <div class="modal-footer">
            <button type="button" data-dismiss="modal" class="btn btn-default modal-close">Cancel</button>
            <button type="button" data-dismiss="modal" class="btn btn-warning modal-close">Proceed</button>
          </div>
        </div>
      </div>
  ';


 	$_tabla = '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Cargas - <span>%nom_proyecto%</span>
				<div class="tools">
					<a href="' . BASE_URL . 'proyecto/"class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>
					<a href="#"><span class="icon mdi mdi-plus"></span></a> 
					<a href="#"><span class="icon mdi mdi-edit"></span></a> 
				</div>
			</div>
			<div class="panel-body table-responsive">
				<table id="table1" class="table table-striped table-hover table-fw-widget">
					<thead>
						<tr class="nexos-encabezado">
							<th style="width:5%;">
								<div class="be-checkbox be-checkbox-sm">
									<input id="check1" type="checkbox">
									<label for="check1"></label>
								</div>
							</th>
							<th style="width:15%;">Cliente</th>
							<th style="width:5%;">#</th>
							<th style="width:15%;">Material</th>
							<th style="width:15%;">Origen</th>
							<th style="width:15%;">Destino</th>
							<th style="width:15%;">Actividad Actual</th>
							<th style="width:15%;">Última Modificación</th>
							<th style="width:10%;"></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<div class="be-checkbox be-checkbox-sm">
									<input id="check4" type="checkbox">
									<label for="check4"></label>
								</div>
							</td>
							<td data-toggle="modal" data-target="#info_1" class="cell-detail md-trigger">
								<span>Praxair</span>
								<span class="cell-detail-description">CIF - Terrestre</span>
							</td>
							<td class="nexos-txt-warning">
								<span class="mdi mdi-dot-circle icon"></span>
							</td>
							<td data-toggle="modal" data-target="#info_2" class="cell-detail md-trigger">
								<span>Gas Licuado</span>
								<span class="cell-detail-description">Riesgo 3</span>
							</td>
							<td data-toggle="modal" data-target="#info_3" class="cell-detail md-trigger">
								<span>Puerto Buenventura</span>
								<span class="cell-detail-description">Buenaventura (Colombia)</span>
							</td>
							<td data-toggle="modal" data-target="#info_4" class="cell-detail md-trigger">
								<span>Bodega Fontibon</span>
								<span class="cell-detail-description">Bogota (Colombia)</span>
							</td>
							<td class="cell-detail md-trigger">
								<span>Solicitud cita Puerto<span>
								<span class="cell-detail-description">Maria Moreno</span>
								<span class="cell-detail-description">Praxair - Agente Carga</span>
							</td>
							<td class="cell-detail md-trigger">
								<span>2017-03-05 08:25:32<span>
								<span class="cell-detail-description">Pedro Hernandez</span>
								<span class="cell-detail-description">Praxair - Agente Carga</span>
							</td>
							<td class="actions">
								<a href="' . BASE_URL . 'proyecto/detalle" class="icon"><span class="mdi mdi-eye"></span></a>
							</td>
						</tr>
						<tr>
							<td>
								<div class="be-checkbox be-checkbox-sm">
									<input id="check4" type="checkbox">
									<label for="check4"></label>
								</div>
							</td>
							<td data-toggle="modal" data-target="#info_1" class="cell-detail md-trigger">
								<span>Praxair</span>
								<span class="cell-detail-description">CIF - Terrestre</span>
							</td>
							<td class="nexos-txt-success">
								<span class="mdi mdi-dot-circle icon"></span>
							</td>
							<td data-toggle="modal" data-target="#info_2" class="cell-detail md-trigger">
								<span>Gas Licuado</span>
								<span class="cell-detail-description">Riesgo 3</span>
							</td>
							<td data-toggle="modal" data-target="#info_3" class="cell-detail md-trigger">
								<span>Puerto Buenventura</span>
								<span class="cell-detail-description">Buenaventura (Colombia)</span>
							</td>
							<td data-toggle="modal" data-target="#info_4" class="cell-detail md-trigger">
								<span>Bodega Fontibon</span>
								<span class="cell-detail-description">Bogota (Colombia)</span>
							</td>
							<td class="cell-detail md-trigger">
								<span>Solicitud cita Puerto<span>
								<span class="cell-detail-description">Maria Moreno</span>
								<span class="cell-detail-description">Praxair - Agente Carga</span>
							</td>
							<td class="cell-detail md-trigger">
								<span>2017-03-05 08:25:32<span>
								<span class="cell-detail-description">Pedro Hernandez</span>
								<span class="cell-detail-description">Praxair - Agente Carga</span>
							</td>
							<td class="actions">
								<a href="' . BASE_URL . 'proyecto/detalle" class="icon"><span class="mdi mdi-eye"></span></a>
							</td>
						</tr>
						<tr>
							<td>
								<div class="be-checkbox be-checkbox-sm">
									<input id="check4" type="checkbox">
									<label for="check4"></label>
								</div>
							</td>
							<td data-toggle="modal" data-target="#info_1" class="cell-detail md-trigger">
								<span>Praxair</span>
								<span class="cell-detail-description">CIF - Terrestre</span>
							</td>
							<td class="nexos-txt-danger">
								<span class="mdi mdi-dot-circle icon"></span>
							</td>
							<td data-toggle="modal" data-target="#info_2" class="cell-detail md-trigger">
								<span>Gas Licuado</span>
								<span class="cell-detail-description">Riesgo 3</span>
							</td>
							<td data-toggle="modal" data-target="#info_3" class="cell-detail md-trigger">
								<span>Puerto Buenventura</span>
								<span class="cell-detail-description">Buenaventura (Colombia)</span>
							</td>
							<td data-toggle="modal" data-target="#info_4" class="cell-detail md-trigger">
								<span>Bodega Fontibon</span>
								<span class="cell-detail-description">Bogota (Colombia)</span>
							</td>
							<td class="cell-detail md-trigger">
								<span>Solicitud cita Puerto<span>
								<span class="cell-detail-description">Maria Moreno</span>
								<span class="cell-detail-description">Praxair - Agente Carga</span>
							</td>
							<td class="cell-detail md-trigger">
								<span>2017-03-05 08:25:32<span>
								<span class="cell-detail-description">Pedro Hernandez</span>
								<span class="cell-detail-description">Praxair - Agente Carga</span>
							</td>
							<td class="actions">
								<a href="' . BASE_URL . 'proyecto/detalle" class="icon"><span class="mdi mdi-eye"></span></a>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	';
	$vista.= $_tabla;


	$vista.='
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>
		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
		<script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
				$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
		</script>
	';

	/******* FIN INFORMACION DEL PROYECTO *********/

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);

	echo $vista;

?>
