<div class="nexos-content">
  <div class="row" style="margin:-25px -39px -10px -39px;">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
        <tbody>
          <tr>
            <td class="celda_titulo2 text-center" style="margin:25px;">
              <b>Informe General responsable de Vehiculo</b>
            </td>
          </tr>
          <tr>
          </tr>
        </tbody>
      </table>
      <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;">
        <tbody>
          <tr>
            <td class="celda_titulo2" style="margin:25px;padding: 5px;">
              <b>Seleccionar fechas para crear el informe</b>
            </td>
          </tr>
          <tr>
          </tr>
        </tbody>
      </table>
      <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;font-zise: 8px;">
        <thead>
          <tr>
            <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Fecha Inicial:</th>
            <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
              <input type="date" id="fecha_inicial" name="fecha_inicial" style="width: 100%;" value="<?php echo date("Y-m-d") ?>">
            </td>
            <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Fecha Final:</th>
            <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
              <input type="date" id="fecha_final" name="fecha_final" style="width: 100%;" value="<?php echo date("Y-m-d") ?>">
            </td>
            <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Responsable:</th>
            <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
              <!-- <input type="date" id="fecha_final" name="fecha_final" style="width: 400px;" value="<?php echo date("Y-m-d") ?>"> -->
              <select name="responsable" id="responsable" style="width: 100%;height: 24px;">
                <!-- <option value="" selected>Seleccioonar..</option> -->
              </select>
            </td>
            <!-- <th style="background-color: #F5F5F5; width: 250px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">Fecha Final:</th> -->
            <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
              <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
              <button type="button" class="btn btn-primary btn-xs" id="aplicar_filtro"><i class="fas fa-filter"></i>Aplicar Filtro</button>
            </td>
          </tr>
        </thead>
      </table>

      <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;font-zise: 8px;">
        <thead>
          <tr>
            <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Total placas:</th>
            <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;" class="text-center">
              <span class="badge badge-success" id="num_placas_responsables">0</span>
            </td>
            <td class="text-right" style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;" colspan="5">
              <a href="JavaScript:void(0);" id="exportar_excel" style="text-decoration: none;cursor: pointer;color: #332D2D;"><img src="<?php echo BASE_URL; ?>public/img/excel_2013.png" alt="Excel" width="15px"> <span style="font-size: 11px;"> Exportar a excel</span></a>
            </td>
          </tr>
        </thead>
      </table>

      <div class="table-responsive">
        <table cellpadding="0" cellspacing="0" border="0" style="width: 100%;" style="border: #332D2D;" id="informe_responsable_placas">
          <thead style="border-collapse: collapse;background-color: #332D2D;color:#fff;">
            <tr>
              <!-- <th class="text-center"><b>Pedido</b></th> -->
              <th class="text-center"><b>Manifiesto</b></th>
              <th class="text-center"><b>Fecha manifiesto</b></th>
              <th class="text-center"><b>cliente</b></th>
              <th class="text-center"><b>Placa</b></th>
              <th class="text-center"><b>Tipo Vehículo</b></th>
              <th class="text-center"><b>Responsable</b></th>
              <th class="text-center"><b>Ruta</b></th>
              <th class="text-center"><b>Flete</b></th>
            </tr>
          </thead>
          <tbody id="tbl_informe_responsable_placa" style="border-collapse: collapse;font-size: 12px;">
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<!-- Mensajes para los usuarios de la plataforma -->
<div id="loading-overlay-nexosapp" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para NexosAPP...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
  </div>
</div>

<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src=<?php echo BASE_URL; ?>/views/informe/js/informe_responsable_placa.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
<script type="text/javascript">
  $(document).ready(function() {
    //initialize the javascript
    App.init();
  });
</script>