<?php
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

$vista = '';
$table_content='';

$table_content.='<div class="row">
	<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
	<input type="date" class="form-control input-sm" id="fecha"  value="'.date('Y-m-d').'" >


	</div>
</div>';

$table_content.="<div class='row' >
			<div class='col-sm-12'>
				<div  class='table-responsive noSwipe'>
					<table id='table1' class='table table-striped table-hover' data-page-length='100'>
						<thead>
							<tr class='nexos-encabezado'>
								<th>#</th>
								<th>Tipo Estudio</th>
								<th>Requerido</th>
								<th style='width:10%;min-width: 10%;'>acciones</th>
							</tr>
						</thead>
						<tbody>";

		//permisos de usuarios 
		$arrayPermisos = $this->hola->permisosPerfil( $ssn_id_perfil , 124);
		$_permisos = $arrayPermisos["rowsData"][0];	
		$btn_editar='';
		if($_permisos['editar']==1){
			
			$btn_editar='<button class="btn btn-success" >editar</button>';

		}	
		$btn_c='';
		if($_permisos['adicionar']==1){
			
			$btn_c='<button class="btn btn-info" >crear</button>';
		}	


		$fecha="<script>
			function fecha(){
				var a=1234;
				return a;
			}
			var x=fecha();
			
			
		</script>";
		$b="<script>alert("+$fecha+")</script>";
		echo $b;
		//print_r($fecha); 

		$array=$this->hola->informes();
		if($array){
			foreach($array["rowsData"] as $key => $value ){

				$table_content.="<tr> 
					<td>hola</td>
					<td>jefe</td>
					<td>jjj</td>
					<td>
						".$btn_editar."
						".$btn_c."
					</td>
				 </tr>";
			}

		}

						$table_content.="</tbody>
					</table>
				</div>
			</div>
		</div>";





		$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Tipo de Estudio 
				<div class="tools">
				<!--	<a id="btn_crea" href="#"  data-toggle="modal"  class="cell-detail  hint--top "  data-hint="Agregar" data-target="#crea_estudio" ><span class="icon mdi mdi-plus"></span></a>  -->
				</div>
				<span class="panel-subtitle">Módulo para customizar tipos de estudio que son requeridos para realizar el estudio vehícular en el área de Seguridad.</span>
				<div class=" col-xs-12 col-sm-4 col-md-12">
					<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'" >
				</div>
			</div>
			<div class="panel-body">
				<div class="nexos-messages"></div>
				<div class="nexos-content">
					%content%
				</div>
				<div class="row">
				<div class="col-sm-12"></div>
				</div>
			</div>
		</div>
	'; 


	$vista.= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
		<link  rel="stylesheet" type="text/css" href="assets/lib/select2/css/select2.min.css"/>

		<link rel="stylesheet" type="text/css" src="%root_file%lib/assets/lib/select2/css/select2.min.css"/>


		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
		<script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.wizard();
			});
		</script>
	';

	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);

	$vista = str_replace("%content%" , $table_content , $vista); //variable $table_content sirve para crear adentro de esta todo lo que se va a mostrar en el cuerpo del conetenedor 
	echo $vista;	



?>