<?php
	$_dbTable = "tarifas"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->tarifa) && count($this->tarifa)){

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_tarifa = '
			<div class="row">
				<div class="col-sm-12">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width:10%;">#</th>
									<th>Cliente</th>
									<th>Origen</th>
									<th>Destino</th>
									<th style="width:10%;">Tipo de vehículo</th>
									<th style="width:10%;">Tarifa</th>
									<th style="min-width:5%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayTarifa = $this->tarifa->getTabla();
		// echo print_r($arrayTarifa);
		foreach ($arrayTarifa['rowsData'] as $key => $value) {

			/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
			switch ($value["estado"]) {
				case '0':
					// se asigna contenido de la columna de estado
					$col_stasus = '<td class="nexos-txt-danger"><span class="mdi mdi-dot-circle icon"></span></td>';

					$_popupHabilita = $alert->_alert_modal_mod_success( $value[0] , "Realmente desea habilitar este elemento?" , $_dbTable );
					$vista.= $_popupHabilita[0];
					$_jsScripts.=$_popupHabilita[1];

					// se asigna contenudo de la columna de acciones
					$col_action = '
						<td class="actions">
							<span id="#habilita_' . $value[0] . '" data-toggle="modal" data-target="#habilita_' . $value[0] . '" class="icon mdi mdi-check-circle"></span>
						</td>
					';
					break;
				
				case '1':
					// se asigna contenido de la columna de estado
					$col_stasus = '<td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>';

					// se genera el formulario de edicion del registro
					$form_edit_table = '
						<input type="hidden" name="id" value="' . $value[0] . '" class="form-control">
						<div class="form-group">
							<label>Origen:</label>
							%slct_origen%
						</div>
						<div class="form-group">
							<label>Destino:</label>
							%slct_destino%
						</div>
						<div class="form-group col-xs-6">
							<label>Tipo Vehículo:</label>
							%slct_tipo_vehiculo%
						</div>
						<div class="form-group col-xs-6">
							<label>Tarifa:</label>
							<input type="text" name="valor" value="' . $value[12] . '" placeholder="Tarifa" class="form-control">
						</div>
						<div class="form-group col-xs-3"></div>
						<div class="form-group col-xs-6">
							<label>Vigencia:</label>
							<input type="text" name="vigencia" value="' . $value[13] . '" placeholder="Vigencia" class="form-control">
						</div>
						<div class="form-group col-xs-3"></div>
						<div class="row"></div>
					';

					$form_edit_table = str_replace( "%slct_origen%" , $this->municipios->getHtmlSelect( "id_ciudad_origen" , $value[2] ), $form_edit_table);
					$form_edit_table = str_replace( "%slct_destino%" , $this->municipios->getHtmlSelect( "id_ciudad_destino" , $value[6] ), $form_edit_table);
					$form_edit_table = str_replace( "%slct_tipo_vehiculo%", $this->tipo_vehiculo->getHtmlSelect( "id_tipo_vehiculo" , $value[10] , "1" ), $form_edit_table);


					$_popupEdita = $form_edita->_form_modal_update($value[0], "Editar Tarifa - " . $value[1] , $form_edit_table, $_dbTable);
					$vista.= $_popupEdita[0];
					$_jsScripts.=$_popupEdita[1];


					$_popupElimina = $alert->_alert_modal_mod_danger($value[0], "Realmente desea eliminar este elemento?",$_dbTable);
					$vista.= $_popupElimina[0];
					$_jsScripts.=$_popupElimina[1];
					// se asigna contenudo de la columna de acciones
					$col_action = '
						<td class="actions">
							<span id="edita_' . $value[0] . '" data-toggle="modal" data-target="#edita_' . $value[0] . '" class="icon mdi mdi-edit"></span>
							<span id="elimina_' . $value[0] . '"data-toggle="modal" data-target="#elimina_' . $value[0] . '" class="icon mdi mdi-close-circle"></span>
						</td>
					';

					break;
			}
			/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

			// Se maqueta contenido de la tabla 
			$table_tarifa.= '<tr>';
			$table_tarifa.= $col_stasus;
			$table_tarifa.= '
				<td class="cell-detail">
					<span>' . $value[1] . '</span>
				</td>
			';
			$table_tarifa.= '
				<td class="cell-detail">
					<span>' . $value[3] . '</span>
					<span class="cell-detail-description">' . $value[4] . ' - ' . $value[5] . '</span>
				</td>
			';
			$table_tarifa.= '
				<td class="cell-detail">
					<span>' . $value[7] . '</span>
					<span class="cell-detail-description">' . $value[8] . ' - ' . $value[9] . '</span>
				</td>
			';
			$table_tarifa.= '
				<td class="cell-detail">
					<span>' . $value[11] . '</span>
				</td>
			';
			$table_tarifa.= '
				<td class="cell-detail number">
					<span>$' . $value[12] . '</span>
					<span class="cell-detail-description">Vigencia - ' . $value[13] . '</span>
				</td>
			';

			// se asigna la columna de acciones
			$table_tarifa.=$col_action;
			
			$table_tarifa.= '</tr>';
		}

		$table_tarifa.= '
							</tbody>
						</table>
					</div>
				</div>
			</div>
		';
	}else{
		echo '<p>no hay registros en esta tabla...</p>';
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Tarifa Clientes
				<div class="tools">
					<a href="#" data-toggle="modal" data-target="#crea_' . $_dbTable . '" class="cell-detail  hint--top"  data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a> 
				</div>
				<span class="panel-subtitle">Se establece la base de cobro a los clientes para el transporte de material según el trayecto y tipo de vehículo.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


  	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();


			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';


	/****** CREACION CONTENIDO DE POPUPS ******/

	// CONTENIDO DEL POPUP DE FORMULARIO DE CREACION
	$forms = '
		<div class="form-group">
			<label class="control-label">Cliente:</label>
			%slct_cliente%
		</div>
		<div class="form-group">
			<label>Origen:</label>
			%slct_origen%
		</div>
		<div class="form-group">
			<label>Destino:</label>
			%slct_destino%
		</div>
		<div class="form-group col-xs-6">
			<label>Tipo Vehículo:</label>
			%slct_tipo_vehiculo%
		</div>
		<div class="form-group col-xs-6">
			<label>Tarifa:</label>
			<input type="text" name="valor" placeholder="Tarifa" class="form-control">
		</div>
		<div class="form-group col-xs-3"></div>
		<div class="form-group col-xs-6">
			<label>Vigencia:</label>
			<input type="text"  name="vigencia" placeholder="Vigencia" class="form-control">
		</div>
		<div class="form-group col-xs-3"></div>
		<div class="row"></div>
	';
	// se genera el select de clientes
	$forms = str_replace("%slct_cliente%", $this->cliente->getHtmlSelect("id_cliente","","1"), $forms);
	$forms = str_replace("%slct_origen%" , $this->municipios->getHtmlSelect( "id_ciudad_origen" , "" ), $forms);
	$forms = str_replace("%slct_destino%" , $this->municipios->getHtmlSelect( "id_ciudad_destino" , "" ), $forms);
	$forms = str_replace("%slct_tipo_vehiculo%", $this->tipo_vehiculo->getHtmlSelect( "id_tipo_vehiculo" , "" , "1" ), $forms);

	$_popupCrea = $form_crea->_form_modal_simple_insert("crea_" . $_dbTable ,"Crear Tarifa" , $forms , $_dbTable );
	$vista.= $_popupCrea[0];
	$_jsScripts.=$_popupCrea[1];


	/****** FIN CREACION CONTENIDO DE POPUPS ******/

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_tarifa , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
