<div class="text-center">
  <h4 style="font-weight: bold;">Detalle de gestión del pedido
    <!-- <span class="label label-danger" id="num_pedido"></span> -->
  </h4>
</div>

<div class="bs-example" data-example-id="simple-table">
  <table class="table table-condensed table-hover">
    <thead style="background-color:#332D2D;color:#fff;text-align:center;">
      <tr>
        <th>#</th>
        <th>Trazabilidad</th>
        <th>Actividad</th>
        <th>Fecha</th>
        <th>Observación</th>
        <th>Responsable</th>
        <th>publicado</th>
        <th>Evidencia</th>
      </tr>
    </thead>
    <tbody id="tbl_detalle_gestion">

    </tbody>
  </table>
</div>
