<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <div class="form-group">
    <div class="checkbox">
      <label style="font-weight: bold;font-size: 15px;">
        <input type="checkbox" id="publicar" name="publicar" style="transform: scale(1.5);margin-right: 5px;">
        Publicar Gestion al Cliente
      </label>
    </div>
  </div>
</div>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label for="" style="font-weight: bold;">Seleccione Parametro</label>
    <select name="parametros_pedido" id="parametros_pedido" class="form-control input-xs"></select>
  </div>
</div>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label for="" style="font-weight: bold;">Seleccione punto parametro</label>
    <select name="parametros_punto_pedido_opcion" id="parametros_punto_pedido_opcion"
      class="form-control input-xs"></select>
  </div>
</div>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label for="" style="font-weight: bold;">Observación</label>
    <textarea name="observacion_gestion" id="observacion_gestion" cols="30" rows="1"
      class="form-control input-xs"></textarea>
  </div>
</div>
<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
  <div class="form-group">
    <label for="" style="font-weight: bold;">Documento</label>
    <input type="file" name="documento" id="documento" class="form-control input-xs">
  </div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
  <button type="button" class="btn btn-success btn-xs" id="btn_guardar_gestion"><i class="far fa-save"></i> Guardar
    Gestión</button>
</div>
