<div class="bs-example" data-example-id="simple-table">
  <table class="table table-condensed table-hover">
    <thead style="background-color:#332D2D;color:#fff;text-align:center;">
      <tr>
        <!-- <th>#</th> -->
        <th>Cliente</th>
        <th>Referencia</th>
        <th>Observación</th>
        <th width>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td id="clientes" style="width: 280px;"></td>
        <td id="referencia"></td>
        <td id="observacion"></td>
        <td id="acciones"></td>
      </tr>
    </tbody>
  </table>
</div>
