<div class="container-fluid">
  <div class="row">
    <div class="col-12 col-xs-12 col-sm-12 col-md-12 col-lg-12 mt-0">
      <!--<div class="widget widget-tile" style="background: #ffffff; color: #1f1f1f; border-radius: 10px; padding: 15px;box-shadow: 0px 1px 10px rgba(0, 0, 0, 0.2);border-color: #ffffff;">-->
      <div class="panel panel-default" style="border-radius: 10px; padding: 15px;">
        <div class="data-info">
          <div class="row align-items-center">
            <div class="col-12 col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div class="markdown text-muted">
                <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                    <div class="form-group form-group-sm">
                      <div class="input-group">
                        <div class="input-group-addon" style="font-weight: bold;font-size: 14px;"><i class="fas fa-filter"></i></div>
                        <select class="form-control input-xs" name="filtro" id="filtro">
                          <option value="">Seleccionar filtro</option>
                          <option value="Fecha">Filtro Fecha</option>
                          <option value="Placa">Filtrar Fecha & Placa</option>
                          <option value="Pedido">Filtrar Fecha & Pedido</option>
                          <option value="Remesa">Filtrar Remesa</option>
                          <!--  <option value="fecha_cliente">Filtrar Cliente & Fecha</option> -->
                        </select>
                      </div>
                    </div>
                  </div>

                  <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                    <div class="form-group form-group-sm">
                      <div class="input-group">
                        <div class="input-group-addon" style="font-weight: bold;font-size: 12px;">Fecha inicio</div>
                        <input type="date" name="fecha_inicial" id="fecha_inicial" class="form-control input-xs fecha_inicial" value="<?php echo date("Y-m-d") ?>">
                      </div>
                    </div>
                  </div>

                  <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
                    <div class="form-group form-group-sm">
                      <div class="input-group">
                        <div class="input-group-addon" style="font-weight: bold;font-size: 12px;">Fecha fin</div>
                        <input type="date" name="fecha_final" id="fecha_final" class="form-control input-xs fecha_final" value="<?php echo date("Y-m-d") ?>">
                      </div>
                    </div>
                  </div>

                  <!-- Numero del cliente -->
                  <input type="hidden" name="cliente" id="cliente_id" value="' . $ssn_id_cliente . '" />
                  <!-- Fin numero del cliente -->

                  <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
                    <div class="form-group form-group-sm">
                      <div class="input-group">
                        <div class="input-group-addon" style="font-weight: bold;font-size: 12px;">Criterio</div>
                        <input type="text" name="criterio_busqueda" id="criterio_busqueda" class="form-control input-xs criterio_busqueda">
                      </div>
                    </div>
                  </div>

                  <div class="col-12 col-xs-12 col-sm-12 col-md-12 col-lg-12" style="padding-top: 3px;padding: 5px 5px 5px 10px;text-align: center;">
                    <button type="button" class="btn btn-primary btn-sm" style="width: auto;" id="filtrar">
                      <i class="fa-solid fa-magnifying-glass"></i> Aplicar Filtro
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Tbla de resultados -->
     <div id="tbl-resultados">
     <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="widget widget-title"
						style="background: #ffffff; color: #1f1f1f; border-radius: 10px; padding: 1px 1px 1px;">
            <div class="row">
              <div class="col-md-6 col-sm-12">
                  <h3 style="font-size: 18px; font-weight: 800; margin-bottom: 5px;">Despachos</h3>
              </div>
            </div>
						<div class="table-responsive noSwipe">
							<div class="col-md-12 col-sm-12" style="padding: 1px 1px 1px;">
								<table class="table table-striped table-borderless" width="100" cellpadding="0" cellspacing="0" border="0">
									<thead style="background-color:#332D2D;color:#fff;text-align:center;">
										<tr>
											<th scope="col" class="text-center">#</th>
											<th scope="col" class="text-center">Orden cargue</th> 
											<th scope="col" class="text-center">Remesa</th>
											<th scope="col" class="text-center">Manifiesto</th>
											<th scope="col" class="text-center">Placa</th>
											<th scope="col" class="text-center">Ruta</th>
											<th scope="col" class="text-center">Fecha</th>
											<th scope="col" class="text-center">Usuario</th>
										</tr>
									</thead>
									<tbody id="tbody-despachos">
										<tr>
											<td colspan="7" class="text-center">
												Esperando Información
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
     </div>

  </div>
</div>

<div id="loading-overlay-nexosapp" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para NexosAPP...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
  </div>
</div>


<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src=<?php echo BASE_URL; ?>/views/clientes_nuevo/js/tracking.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>

<script type="text/javascript">
  $(document).ready(function() {
    //initialize the javascript
    App.init();
  });
</script>