<?php
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

$vista = '';
$table_content='';
if (isset($this->trazo)){
$arrayPermisos = $this->trazo->permisosPerfil( $ssn_id_perfil , 133);
$_permisos = $arrayPermisos["rowsData"][0];
	

$vista.='
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="col-xs-12 col-sm-12 col-md-12">
	<input type="hidden" id="idcliente" value="'.$ssn_id_cliente.'">
</div>
<div class="form-group col-xs-4 col-sm-4 col-md-4">
	<label>Fecha Inicial</label>
	<input type="date" id="fecha_inicia" class="form-control input-sm"  value="'.date('Y-m-d').'" >	
</div>
<div class="form-group col-xs-4 col-sm-4 col-md-4">
	<label>Fecha Final</label>
	<input type="date" id="fecha_final" class="form-control input-sm"  value="'.date('Y-m-d').'"  >
</div>
<div class="form-group col-xs-3 col-sm-3 col-md-3">
	<label></label>
	<button class="form-control input-sm btn btn-info mdi mdi-search" id="consulte"  onclick="solicitudes_cliente();" >
		Consultar
	</button>
</div>
</div>';

$vista.="<div class='row' >
			<div class='col-sm-12'>
				<div  class='table-responsive noSwipe'>
					<table id='table4' class='table table-striped table-hover' data-page-length='100'>
						<thead>
							<tr class='nexos-encabezado'>
								<th>Cotización 1</th>
								<th>SSS 2</th>
								<th>Tiempo: 1-2</th>
								<th>S. estudio 3</th>
								<th>Estudio 4</th>
								<th>Tiempo: 3-4</th>
								<th>Planilla 5</th>
								<th>Inicio ruta 6</th>
								<th>Tiempo: 5-6</th>
								<th>Tiempo: 1-6</th>
							</tr>
						</thead>
						<tbody id='principal_cuerpo' >";
						$table_content.="</tbody>
					</table>
				</div>
			</div>
	</div>";

}
?>

<?php
$vista.= '
		<script  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMwRwybUARcBql3j71ykZpBTavAmkiqRo"></script>

		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
		<link  rel="stylesheet" type="text/css" href="assets/lib/select2/css/select2.min.css"/>

		<link rel="stylesheet" type="text/css" src="%root_file%lib/assets/lib/select2/css/select2.min.css"/>


		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
		<script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.wizard();
			});
		</script>
'; 
$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_content , $vista); 
echo $vista;
?>
<script type="text/javascript">
var url2 =$("#id_url_ajax").val() + "libs/trafico_ajax.php";
function solicitudes_cliente(){
	var fechai=$("#fecha_inicia").val();
	var fechaf=$("#fecha_final").val();
	var idcliente=$("#idcliente").val();
	var consulta={
		idcliente:idcliente,
		fechai:fechai,
		fechaf:fechaf,
		action:'consulta_trazabilidad'
	};
	 $.ajax({
		url:url2,
		type:'POST',
		data:consulta,
		dataType:'json',
		success: function(data){
			$("#principal_cuerpo").html('');
			if(data.result!=null){
				var valor;
				var cont=0;
				data.result.forEach(function(element,index){
					cont++
					$("#principal_cuerpo").append('<tr>'+
						'<td class="cell-detail">'+
						element.idcoti+
						'<span class="cell-detail-description">'+element.fechacoti+'</span>'
						+'</td>'+	
						'<td class="cell-detail">'+
						element.idservi+
						'<span class="cell-detail-description">'+element.fechaservi+'</span>'+
						'</td>'+
						'<td>'+element.weatherA+'</td>'+
						'<td class="cell-detail">'+
						element.idsoli+
						'<span class="cell-detail-description">'+element.fechasoli+'</span>'+
						'</td>'+
						'<td class="cell-detail">'+
						element.idestu+
						'<span class="cell-detail-description">'+element.fechaestu+'</span>'+
						'</td>'+
						'<td>'+element.weatherB+'</td>'+
						'<td class="cell-detail">'+
						element.idplani+
						'<span class="cell-detail-description">'+element.fechaplani+'</span>'+
						'</td>'+
						'<td class="cell-detail">'+
						element.idruta+
						'<span class="cell-detail-description">'+element.fecharuta+'</span>'
						+'</td>'+
						'<td>'+element.weatherC+'</td>'+
						'<td>'+element.weatherD+'</td>'+
					'</tr>');
				});
			}
		},
		error:function(jqXHR, textStatus, errorThrown){
			console.log('no hay fila');
			console.log(jqXHR);
			console.log(textStatus);
			console.log(errorThrown);
		}	
	});

}


</script>

