<?php
	$_dbTable = "contabilidad_conceptos"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	$vista = '';

	/********* POPUPS *********/
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	/********* FIN POPUPS *********/

	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->servicios_especiales) /* && count($this->servicios_especiales) */){
		$result = $this->servicios_especiales->permisosPerfil( $_SESSION["usuario"]["id_perfil"], 11);
		$access = $result;

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_servicios_especiales = '
			<div class="row">
				<div class="col-xs-1 col-sm-1 col-md-2"></div>
				<div class="col-xs-12 col-sm-12 col-md-8">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover" data-page-length="100">
							<thead>
								<tr class="nexos-encabezado">
									<th class="col-xs-1 col-sm-1 col-md-1">#</th>
									<th class="col-xs-2 col-sm-1 col-md-1"></th>
									<th>Servicio Especial</th>
									<th class="col-xs-2 col-sm-2 col-md-2"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayTarifa = $this->servicios_especiales->getTabla();

		if ($arrayTarifa) {
			foreach ($arrayTarifa as $key => $value) {

				/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
				switch ($value["estado"]) {
					case '0':
						// se asigna contenido de la columna de estado
						$col_stasus = '<td class="nexos-txt-danger"><span class="mdi mdi-dot-circle icon"></span></td>';

						$_popupHabilita = $alert->_alert_modal_mod_success( $value['id'] , "Realmente desea habilitar este elemento?" , $_dbTable );
						$vista.= $_popupHabilita[0];
						$_jsScripts.=$_popupHabilita[1];

						// se asigna contenudo de la columna de acciones
						$_btn_habilitar = '';
						if ($access["eliminar"]) {
							$_btn_habilitar = '
								<span id="#habilita_' . $value['id'] . '" data-toggle="modal" data-target="#habilita_' . $value['id'] . '" class="icon mdi mdi-check-circle"></span>
							';
						}
						$col_action = '
							<td class="actions">
								' . $_btn_habilitar . '
							</td>
						';
						break;
					
					case '1':
						// se asigna contenido de la columna de estado
						$col_stasus = '<td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>';

						$_popupElimina = $alert->_alert_modal_mod_danger($value['id'], "Realmente desea eliminar este elemento?",$_dbTable);
						$vista.= $_popupElimina[0];
						$_jsScripts.=$_popupElimina[1];
						// se asigna contenudo de la columna de acciones
						$_btn_editar = '';
						if ($access["editar"]) {
							$_btn_editar = '
								<a href="javascript:" onclick="form_edita(' . $value['id'] . ', \'' . $value["nom_servicios_especial"] . '\', \'' . $value["tipo_servicio"] . '\')" class="cell-detail  hint--top-left" data-hint="Editar Servicio Especial">
									<span class="icon mdi mdi-edit" data-toggle="modal" data-target="#editar"></span>
								</a>
								<a href="javascript:" onclick="form_edita_cuentas(' . $value['id'] . ', \'' . $value["nom_servicios_especial"] . '\', \'' . $value["tipo_servicio"] . '\')" class="cell-detail  hint--top-left" data-hint="Editar Cuentas Contables">
									<span class="icon mdi mdi-collection-bookmark" data-toggle="modal" data-target="#editar_cuentas"></span>
								</a>
							';
						}
						$_btn_eliminar = '';
						if ($access["eliminar"]) {
							$_btn_eliminar = '
								<span id="elimina_' . $value['id'] . '"data-toggle="modal" data-target="#elimina_' . $value['id'] . '" class="icon mdi mdi-close-circle"></span>
							';
						}

						$col_action = '
							<td class="actions">
								' . $_btn_editar . '
								' . $_btn_eliminar . '
							</td>
						';

						break;
				}
				/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

				// Se maqueta contenido de la tabla 
				$table_servicios_especiales.= '<tr>';
				$table_servicios_especiales.= $col_stasus;
				$table_servicios_especiales.= '
					<td class="cell-detail">
						<span class="label label-default">' . $value["CUANTOS"] . '</span>
					</td>
					<td class="cell-detail">
						<span>' . $value["nom_servicios_especial"] . '</span>
						<span class="cell-detail-description">' . $value["tipo_servicio"] . '</span>
					</td>
				';

				// se asigna la columna de acciones
				$table_servicios_especiales.=$col_action;
				
				$table_servicios_especiales.= '</tr>';
			}
		}
		$table_servicios_especiales.= '
							</tbody>
						</table>
					</div>
				</div>
			</div>
		';
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/

	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$_btn_adicionar = '';
	if ($access["adicionar"]) {
		$_btn_adicionar = '
			<div class="tools">
				<a href="#" data-toggle="modal" data-target="#crear" class="cell-detail  hint--top"  data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a> 
			</div>
		';
	}
	$_slct_tipo_servicio = $this->servicios_especiales->getEnumSlctTipoServicio_sm( "tipo_servicio" , "" , "" );
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Servicios Especiales
				' . $_btn_adicionar . '
				<span class="panel-subtitle">Se parametriza los tipos de servicio que pueden ser utilizados en el apoyo del desarrollo de una actividad. Estos puede tener un costo el cual se asigna al momento de crear una actividad en la que incluye un servicio especial.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>

		<div id="crear" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<form id="form_crea">
						<div class="modal-header">
							<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
							<h3 class="modal-title">Crear Servicio Especial</h3>
						</div>
						<div class="modal-body">
							<div class="msg_panel_content"></div>
							<div class="col-md-12 text-right">
								<span>(*) Campos Obligatorios</span>
							</div>
							<div class="form-group col-xs-12 col-sm-6 col-md-6">
								<label>Nombre:</label>
								<input type="text" name="nom_servicios_especial" id="nom_servicios_especial" placeholder="Servicio Especial" class="form-control input-sm">
							</div>
							<div class="form-group col-xs-12 col-sm-6 col-md-6">
								<label>Tipo Servicio:</label>
								' . $_slct_tipo_servicio . ' 
							</div>
							<div class="row"></div>
						</div>
						<div class="modal-footer">
							<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
							<button id="btn_crea" type="button" class="btn btn-success md-close">Guardar</button>
						</div>
					</form>
				</div>
			</div>
		</div>

		<div id="editar" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<form id="form_edita">
						<div class="modal-header">
							<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
							<h3 class="modal-title">Editar Servicio Especial</h3>
						</div>
						<div class="modal-body">
							<div class="msg_panel_content"></div>
							<input type="hidden" name="id" id="id">
							<div class="form-group col-xs-12 col-sm-6 col-md-6">
								<label>Nombre:</label>
								<input type="text" name="nom_servicios_especial" id="nom_servicios_especial" placeholder="Servicio Especial" class="form-control input-sm">
							</div>
							<div class="form-group col-xs-12 col-sm-6 col-md-6">
								<label>Tipo Servicio:</label>
								' . $_slct_tipo_servicio . ' 
							</div>
							<div class="row"></div>
						</div>
						<div class="modal-footer">
							<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
							<button id="btn_edita" type="button" class="btn btn-success md-close">Guardar</button>
						</div>
					</form>
				</div>
			</div>
		</div>

		<div id="editar_cuentas" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<form id="form_edita_cuentas">
						<div class="modal-header">
							<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
							<h3 class="modal-title" id="edita_cuentas_title"></h3>
						</div>
						<div class="modal-body">
							<div class="msg_panel_content"></div>
							<table class="table table-condensed table-borderless">
								<tbody>
									<tr>
										<td class="actions">
											<a class="icon hint--top-left" data-hint="Crear Cuenta Contable"><i class="mdi mdi-plus mostrar_form"></i></a>
										</td>
									</tr>
								</tbody>
							</table>
							<div class="row" id="form_content"></div>
							<div class="row" id="edita_cuentas_content" data-eliminar="' . $access["eliminar"] . '"></div>
							<div class="row"></div>
						</div>
						<div class="modal-footer">
							<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
							<button id="btn_edita_cuentas" type="button" class="btn btn-success md-close">Guardar</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	';

  	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();


			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_servicios_especiales , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
<script type="text/javascript">
	$(document).ready(function(){
		$("#btn_crea").click(function(){
			$(".msg_content").empty();
			let form_crea = $("#form_crea");
			var msg_error = "";

			// Se filtra el contenido del formulario
			var nombre = form_crea.find("#nom_servicios_especial").val();
			var tipo_servicio = form_crea.find("#slct_tipo_operacion_").val();

			if (!nombre) {
				msg_error+= '<p>Debe diligenciar el campo <strong>Nombre</strong> para crear el servicio.</p>';
			}
			if (!tipo_servicio) {
				msg_error+= '<p>Debe seleccionar un <strong>Tipo Servicio</strong> para crear el servicio.</p>';
			}

			if (!msg_error) {
				var params = form_crea.serialize();
				$.ajax({
					type		: "POST",
					cache		: false,
					url			: $("#id_url_ajax").val() + "libs/insertar.php?tabla=cmx_contabilidad_conceptos",
					data		: params,
					beforeSend	: function(jqXHR, settings){
						$("#crear").hide();
						$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
					},
					success		: function(data) {
						// console.log(data);
						$(".nexos-messages").empty();
						$("#crear").show();
						$(".msg_content").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado! </strong>Se ha creado el registro con éxito.</div></div>');
						$("#crear").animate({ scrollTop: 0 }, 600);
						setTimeout(function(){ location.reload(false); }, 800);
					}
				});
			}
			if (msg_error) {
				$(".msg_content").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
				$("#crear").animate({ scrollTop: 0 }, 600);
			}
		});

		$("#btn_edita").click(function(){
			$(".msg_content").empty();
			let form_edita = $("#form_edita");
			var msg_error = "";

			// Se filtra el contenido del formulario
			var nombre = form_edita.find("#nom_servicios_especial").val();
			var tipo_servicio = form_edita.find("#slct_tipo_operacion_").val();

			if (!nombre) {
				msg_error+= '<p>Debe diligenciar el campo <strong>Nombre</strong> para crear el servicio.</p>';
			}
			if (!tipo_servicio) {
				msg_error+= '<p>Debe seleccionar un <strong>Tipo Servicio</strong> para crear el servicio.</p>';
			}

			if (!msg_error) {
				var params = form_edita.serialize();
				// console.log(params);

				$.ajaxSetup({async: false});
				$.ajax({
					url: $("#id_url_ajax").val() + "libs/servicios_especiales_ajax.php?action=editarServicio",
					type: 'POST',
					data: params,
					cache: false,
					dataType: 'json',
					beforeSend	: function(jqXHR, settings){
						$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
					},
					error: function (jqXHR, textStatus, errorThrown){
						msg_error+= "<p>" + jqXHR.responseText + "</p>";
						console.log(jqXHR);
						console.log(textStatus);
						console.log(errorThrown);
					},
					success: function (data, textStatus, jqXHR){
						// console.log(data);
						$(".nexos-messages").empty();
						if (!data.error) {
							$("#editar").show();
							$(".msg_content").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado! </strong>Se ha editado el registro con éxito.</div></div>');
							$("#editar").animate({ scrollTop: 0 }, 600);
							setTimeout(function(){ location.reload(false); }, 800);
						} else {
							msg_error+= data.error;
						}
					}
				});
				$.ajaxSetup({async: true});
			}
			if (msg_error) {
				$(".msg_content").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
				$("#crear").animate({ scrollTop: 0 }, 600);
			}
		});

		$("#btn_edita_cuentas").click(function(){
			msg_error = "";
			$(".msg_panel_content").empty();

			var agencia = $("#slct_agencia_");
			var tipo_documento = $("#slct_tipo_documento_");
			var tipo_persona = $("#slct_tipo_persona_");
			var tipo_cuenta = $("#slct_tipo_cuenta_");
			var numero_cuenta = $("#numero_cuenta");
			var nombre_cuenta = $("#nombre_cuenta");

			/***** Se valida la información del formulario *****/
			if (!tipo_documento.val()) {
				msg_error+= `<p>Debe seleccionar un <strong>Tipo Documento</strong> para poder crear la cuenta.</p>`;
			}
			if (!tipo_persona.val()) {
				msg_error+= `<p>Debe seleccionar un <strong>Tipo Persona</strong> para poder crear la cuenta.</p>`;
			}
			if (!tipo_cuenta.val()) {
				msg_error+= `<p>Debe seleccionar un <strong>Naturaleza</strong> para poder crear la cuenta.</p>`;
			}
			if (!numero_cuenta.val()) {
				msg_error+= `<p>Debe diligenciar el campo <strong>${numero_cuenta.attr("placeholder")}</strong> para poder crear la cuenta.</p>`;
			} else if ( numero_cuenta.val().length != numero_cuenta.attr("maxlength") ) {
				msg_error+= `<p>El campo <strong>${numero_cuenta.attr("placeholder")}</strong> debe ser de <strong>${numero_cuenta.attr("maxlength")}</strong> dígitos para poder crear la cuenta.</p>`;
			} else if ( !Number.isInteger( parseInt( numero_cuenta.val() ) ) ) {
				msg_error+= `<p>El campo <strong>${numero_cuenta.attr("placeholder")}</strong> solo debe contener números para poder crear la cuenta.</p>`;
			} else {
				let numero = parseInt(numero_cuenta.val());
				if ( String(numero).length != numero_cuenta.attr("maxlength") ) {
					msg_error+= `<p>El campo <strong>${numero_cuenta.attr("placeholder")}</strong> solo debe contener números para poder crear la cuenta.</p>`;
				}
			} 

			if (!nombre_cuenta.val()) {
				msg_error+= `<p>Debe diligenciar el campo <strong>${nombre_cuenta.attr("placeholder")}</strong> para poder crear la cuenta.</p>`;
			}
			/***** Fin - Se valida la información del formulario *****/

			if (!msg_error) {
				let params = {
					id : _flag_content,
					agencia: agencia.val(),
					tipo_documento : tipo_documento.val(),
					tipo_persona : tipo_persona.val(),
					tipo_cuenta : tipo_cuenta.val(),
					numero_cuenta : numero_cuenta.val(),
					nombre_cuenta : nombre_cuenta.val(),
				};
				// console.log(params);

				$.ajaxSetup({async: false});
				$.ajax({
					url: $("#id_url_ajax").val() + "libs/servicios_especiales_ajax.php?action=crearCuentaContable",
					type: 'POST',
					data: params,
					cache: false,
					dataType: 'json',
					beforeSend	: function(jqXHR, settings){
						$(".msg_content").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
					},
					error: function (jqXHR, textStatus, errorThrown){
						$("#nexos_messages_costos").html('');
						msg_error+= "<p>" + jqXHR.responseText + "</p>";
						console.log(jqXHR);
						console.log(textStatus);
						console.log(errorThrown);
					},
					success: function (data, textStatus, jqXHR){
						// console.log(data);
						if (!data.error) {
							$(".msg_panel_content").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado! </strong>Se ha creado el registro con éxito.</div></div>');
							$("#editar_cuentas").animate({ scrollTop: 0 }, 600);
							$("#btn_edita_cuentas").fadeOut(1000);
							$("#form_content").fadeOut(1000, function(){
								$(".msg_panel_content").delay(500).fadeOut(1200, function(){
									$("#form_edita_cuentas")[0].reset();
									$(".msg_panel_content").empty();
									$(".msg_panel_content").show();
								});
							});
							verCuentas(_flag_content);
						} else {
							msg_error+= data.error;
						}
					}
				});
				$.ajaxSetup({async: true});
			}
			if (msg_error) {
				$(".msg_panel_content").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
				$("#editar_cuentas").animate({ scrollTop: 0 }, 600);
			}
		});
	});

	var id_content;
	function form_edita(id, nombre, tipo_servicio){
		var form_content = $("#form_edita");
		if (id_content != id) {
			id_content = id;
			form_content.find("#id").val(id);
			form_content.find("#nom_servicios_especial").val(nombre);
			form_content.find("#slct_tipo_operacion_").val(tipo_servicio);
		}
	}

	/***** Funciones de administración de cuentas contables de los servicios adicionales *****/
	$(".mostrar_form").click(function(){
		$("#form_content").fadeToggle("fast");
		$("#btn_edita_cuentas").fadeToggle("fast");
	});

	var _flag_content
	function form_edita_cuentas(id, nombre, tipo_servicio){
		if ( _flag_content != id) {
			_flag_content = id;
			$(".msg_panel_content").empty();
			$("#edita_cuentas_title").html(`Editar Cuentas Contables - ${nombre} <small>(${tipo_servicio})</small>`);
			$("#form_edita_cuentas")[0].reset();
			$("#form_content").fadeOut("fast");
			$("#btn_edita_cuentas").fadeOut("fast");
			$("#edita_cuentas_content").empty();
			cargarFormularioCuentas();
			verCuentas(id);
		}
	}

	function cargarFormularioCuentas(){
		var msg_error = "";
		$.ajaxSetup({async: false});
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/servicios_especiales_ajax.php?action=cargarFormularioCuentas",
			type: 'POST',
			cache: false,
			dataType: 'json',
			beforeSend	: function(jqXHR, settings){
				$(".msg_content").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
			},
			error: function (jqXHR, textStatus, errorThrown){
				$("#nexos_messages_costos").html('');
				msg_error+= "<p>" + jqXHR.responseText + "</p>";
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function (data, textStatus, jqXHR){
				// console.log(data);
				if (!data.error) {
					$("#form_content").html(data.content);
				} else {
					msg_error+= data.error;
				}
			}
		});
		$.ajaxSetup({async: true});
		if (msg_error) {
			$(".msg_panel_content").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("#editar_cuentas").animate({ scrollTop: 0 }, 600);
		}
	}

	function verCuentas(id){
		var msg_error = "";
		let permisos = $("#edita_cuentas_content");
		let params = {
			id : id,
			eliminar: permisos.data("eliminar")
		};

		$.ajaxSetup({async: false});
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/servicios_especiales_ajax.php?action=formCuentasContables",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend	: function(jqXHR, settings){
				$(".msg_content").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
			},
			error: function (jqXHR, textStatus, errorThrown){
				$("#nexos_messages_costos").html('');
				msg_error+= "<p>" + jqXHR.responseText + "</p>";
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function (data, textStatus, jqXHR){
				// console.log(data);
				if (!data.error) {
					$("#edita_cuentas_content").html(data.content);

					$(".btn_action").click(function(){
						cambiaEstado($(this));
						verCuentas(_flag_content);
					});
				} else {
					msg_error+= data.error;
				}
			}
		});
		$.ajaxSetup({async: true});
		if (msg_error) {
			$(".msg_panel_content").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("#editar_cuentas").animate({ scrollTop: 0 }, 600);
		}
	}

	function cambiaEstado(element){
		var msg_error = "";
		let params = {
			id : element.data("id"),
			estado: element.data("estado")
		};
		// console.log(params);

		$.ajaxSetup({async: false});
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/servicios_especiales_ajax.php?action=cambiaEstadoCuenta",
			type: 'POST',
			data: params,
			cache: false,
			dataType: 'json',
			beforeSend	: function(jqXHR, settings){
				$(".msg_content").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
			},
			error: function (jqXHR, textStatus, errorThrown){
				$("#nexos_messages_costos").html('');
				msg_error+= "<p>" + jqXHR.responseText + "</p>";
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success: function (data, textStatus, jqXHR){
				// console.log(data);
				if (!data.error) {
					$(".msg_panel_content").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado! </strong>Se ha creado el registro con éxito.</div></div>');
					$(".msg_panel_content").delay(1500).fadeOut(1000, function(){
						$(".msg_panel_content").empty();
						$(".msg_panel_content").show();
					});
				} else {
					msg_error+= data.error;
				}
			}
		});
		$.ajaxSetup({async: true});
		if (msg_error) {
			$(".msg_panel_content").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("#editar_cuentas").animate({ scrollTop: 0 }, 600);
		}
	}
	/***** Funciones de administración de cuentas contables de los servicios adicionales *****/
</script>
