<?php
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

$vista = '';
$colstatus = '';
$table_content = '';
if (isset($this->control_horas)) {
	$arrayPermisos = $this->control_horas->permisosPerfil($ssn_id_perfil, 112);
	$_permisos = $arrayPermisos;

	$table_content .= "
			<div class='row' >
						<div class='col-sm-12'>
							<div  class='table-responsive noSwipe'>
								<table id='table1' class='table table-striped table-hover' data-page-length='100'>
									<thead>
										<tr class='nexos-encabezado'>
											<th>Estado</th>
											<th>Hora</th>
											<th>Acciones</th>
										</tr>
									</thead>
									<tbody>";
	$array = $this->control_horas->gethoras();
	if ($array) {
		foreach ($array["rowsData"] as $key => $value) {

			if ($value['estado'] == 'Activo') {
				$colstatus = "
								<td class='nexos-txt-success'>
								<center><span class='mdi mdi-dot-circle icon'></span></center>
								</td>";
			}

			if ($value['estado'] == 'Inactivo') {
				$colstatus = "
								<td class='nexos-txt-danger'>
								<center><span class='mdi mdi-dot-circle icon'></span></center>
								</td>";
			}

			$btn_editar = '';
			if ($_permisos["editar"] == 1) {


				$btn_editar = '
								<button type="button" class="btn-secondary btn btn-xs mdi "
								<a href="javascript:" onclick="prueba_editar(this)" class="cell-detail hint--top-left" data-hint="" 
									data-id="' . $value['id'] . '"
									data-id2="' . $value['hora'] . '"
									data-id3="' . $value['estado'] . '">
										<span class="icon mdi mdi-edit" data-toggle="modal" data-target="#editar_hora" title="Editar Hora">
										</span>
									</a></button>

								';
			}



			$table_content .= '
					<tr>
						' . $colstatus . '
						<td class="cell-detail">
							<span><strong>' . $value["hora"] . '</strong></span>
						</td>
						<td class="cell-detail">
							' . $btn_editar . '
						</td>
					</tr>
					';
		}
	}

	$table_content .=  		"</tbody>
					</table>
				</div>
			</div>
	</div>";
	$_btn_crear = '';
	if ($_permisos["adicionar"] == 1) {
		$_btn_crear = '<a id="btn_crea" href="#"  data-toggle="modal"  class="cell-detail  hint--top "  data-hint="" data-target="#crea_horas"><span class="icon mdi mdi-plus" title="Agregar Hora"></span></a> 
				</div>';
	}
	$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Horas Control
				<div class="tools"> 
				' . $_btn_crear . '	
				<span class="panel-subtitle">Mòdulo para controlar el tiempo estimado para la cancelación del preestudio.</span>
			</div>
			<div class="panel-body">
				<div class="nexos-messages"></div>
				<div class="nexos-content">
					%content%
				</div>
				<div class="row">
				<div class="col-sm-12"></div>
				</div>
			</div>
		</div>
';
}
$vista .= '

			<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

			<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/" type="text/javascript"></script>
			<script src="%root_file%js/main.js" type="text/javascript"></script>
			<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
			<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

			<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
			<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
			<link  rel="stylesheet" type="text/css" href="assets/lib/select2/css/select2.min.css"/>

			<link rel="stylesheet" type="text/css" src="%root_file%lib/assets/lib/select2/css/select2.min.css"/>
			<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
			<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

			<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
			<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
			<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

			<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
			<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
			<script type="text/javascript">
				$.fn.niftyModal(\'setDefaults\',{
					overlaySelector: \'.modal-overlay\',
					closeSelector: \'.modal-close\',
					classAddAfterOpen: \'modal-show\',
				});
				$(document).ready(function(){
					//initialize the javascript
					App.init();
				});
				$(document).ready(function(){
					//initialize the javascript
					App.init();
					App.dataTables();
				});
				$(document).ready(function(){
					//initialize the javascript
					App.init();
					App.wizard();
				});
			</script>
';

$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%content%", $table_content, $vista);
echo $vista;
?>
<div id="crea_horas" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary" style="overflow-y: scroll;">
	<div class=".modal-dialog-modal-lg.modal-dialog ">
		<div class="modal-content ">
			<div class="modal-header">
				<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
				<h3 class="modal-title">
					<label style="font-size:19pt; color:white; text-align:center;">
						Crear Horas</label>
				</h3>
			</div>
			<div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
				<div id="nexos_messages_popup"></div>
				<div class="row">
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<label style="font-weight:800; margin-top:20px;">Tiempo de Expiración de la solicitud&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<input type="number" id="hora" class="form-control" placeholder="horas" required="requiered">
					</div>
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<label style="font-weight:800; margin-top:20px;">Estado&nbsp;<span style="color:red;"><i>(*)</i></span></label>
						<input type="text" id="estado" value="Activo" readonly="readonly" class="form-control">
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button id="crear" class="btn btn-success">Guardar</button>
				<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
			</div>
		</div>
	</div>
</div>


<div id="editar_hora" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
	<div class="modal-dialog custom-width">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
				<h3 class="modal-title" id="editar_title">
					<label id="titulo" style="font-size:19pt; color:white; text-align:center;">EDITAR CONTROL DE HORAS </label>
				</h3>
			</div>
			<div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
				<div id="msg_editar"></div><!-- id para manejar los mensajes de errordel popup -->
				<div id="content_editar">
					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<label style="font-weight:800; margin-top:20px;">Tiempo de Expiración de la solicitud&nbsp;<span style="color:red;"><i>(*)</label>
							<input type="number" id="e_hora" class="form-control" required="">
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<label style="font-weight:800; margin-top:20px;">Estado</label>
							<select id="e_estado" class="form-control">
							</select>
							<input type="hidden" id="valor">
						</div>

					</div>
				</div>
				<div class="modal-footer">
					<button id="btn_actualizar" type="button" class="btn btn-success md-close">Actualizar</button>
					<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
				</div>
			</div>
		</div>
	</div>


	<script type="text/javascript">
		var url2 = $("#id_url_ajax").val() + "libs/preestudio2_ajax.php";
		$("#crear").click(function() {
			var h, e;
			h = $("#hora").val();
			valu = 192;
			e = $("#estado").val();
			// alert(h);
			if (h > valu) {
				alert('mayor, el numero debe ser igual o menor a 192 por políticas del sistema');
			} else {
				// alert('menor');
				//validar si existe alguno 
				// $.ajax({
				// 	url:url2,
				// 	type:'POST',
				// 	data:dato,
				// 	dataType:'json',
				// 	success:function(data){
				// 		alert('Datos Registrados Exitosamente!');
				// 		$("html, body").animate({ scrollTop: 0 }, 600);
				// 		setTimeout(function() { location.reload(false);  }, 800);
				// 	},
				// 	error:function(jqXHR, textStatus, errorThrown){
				// 		console.log(jqXHR);
				// 		console.log(textStatus);
				// 		console.log(errorThrown);
				// 	}
				// });

				//VALIDAR SI YA EXISTE ESA HORA
				var existe = {
					action: 'existe_hora'
				};
				$.ajax({
					url: url2,
					type: 'POST',
					data: existe,
					dataType: 'json',
					success: function(data) {
						console.log('sucess');
						console.log(data)
						if (data.result == null) {
							console.log('NULL');
							//insertar normal
							var dato = {
								hora: h,
								estado: e,
								action: 'crear_hora_preestudio'
							};

							$.ajax({
								url: url2,
								type: 'POST',
								data: dato,
								dataType: 'json',
								success: function(data) {
									alert('Datos Registrados Exitosamente!');
									$("html, body").animate({
										scrollTop: 0
									}, 600);
									setTimeout(function() {
										location.reload(false);
									}, 800);
								},
								error: function(jqXHR, textStatus, errorThrown) {
									console.log(jqXHR);
									console.log(textStatus);
									console.log(errorThrown);
								}
							});

						} else if (data.result != null) {
							console.log('NO NULL');
							//insertar y update a los anteriores
							//update
							var dato2 = {
								action: 'update_horas'
							};

							$.ajax({
								url: url2,
								type: 'POST',
								data: dato2,
								dataType: 'json',
								success: function(data) {
									console.log('actualizo bien los anteriores');
									// alert('Datos Registrados Exitosamente!');
									// $("html, body").animate({ scrollTop: 0 }, 600);
									// setTimeout(function() { location.reload(false);  }, 800);
								},
								error: function(jqXHR, textStatus, errorThrown) {
									console.log(jqXHR);
									console.log(textStatus);
									console.log(errorThrown);
								}
							});


							var dato = {
								hora: h,
								estado: e,
								action: 'crear_hora_preestudio'
							};

							$.ajax({
								url: url2,
								type: 'POST',
								data: dato,
								dataType: 'json',
								success: function(data) {
									console.log('registro bien hora');
									// alert('Datos Registrados Exitosamente!');
									// $("html, body").animate({ scrollTop: 0 }, 600);
									// setTimeout(function() { location.reload(false);  }, 800);
								},
								error: function(jqXHR, textStatus, errorThrown) {
									console.log(jqXHR);
									console.log(textStatus);
									console.log(errorThrown);
								}
							});

						}
					},
					error: function(jqXHR, textStatus, errorThrown) {
						console.log('error');
						console.log(jqXHR);
						console.log(textStatus);
						console.log(errorThrown);
					}
				});
				//Actualizar la página
				alert('Datos Registrados Exitosamente!');
				$("html, body").animate({
					scrollTop: 0
				}, 600);
				setTimeout(function() {
					location.reload(false);
				}, 800);

			}
		});

		function prueba_editar(element) {
			var elemento = $(element);
			var id = elemento.data("id");
			var hour = elemento.data("id2");
			var estado = elemento.data("id3");
			$("#e_hora").val(hour);
			$("#valor").val(id);
			if (estado == 'Activo') {
				$("#e_estado").html('<option value="Activo">Activo</option>' +
					'<option value="Inactivo">Inactivo</option>');
			}
			if (estado == 'Inactivo') {
				$("#e_estado").html('<option value="Inactivo">Inactivo</option>' + '<option value="Activo">Activo</option>');
			}
		}

		//actualizar en la BD
		$("#btn_actualizar").click(function() {
			// alert('registrar');
			var a = $("#e_hora").val();
			var b = $("#e_estado").val();
			var c = $("#valor").val();

			var valu = 192;
			if (a > valu) {
				alert('mayor, el numero debe ser igual o menor a 192 por políticas del sistema');
			} else {
				dati = {
					hora: a,
					estado: b,
					id: c,
					action: 'actualizar_hora'
				};
				//actualizar hora seleccionada
				$.ajax({
					url: url2,
					type: 'POST',
					data: dati,
					dataType: 'json',
					success: function(data) {
						console.log('Actualizo hora');
						// alert('Actualizar Registrados Exitosamente!');
						// $("html, body").animate({ scrollTop: 0 }, 600);
						// setTimeout(function() { location.reload(false);  }, 800);	
					},
					error: function(jqXHR, textStatus, errorThrown) {
						console.log(jqXHR);
						console.log(textStatus);
						console.log(errorThrown);
					}
				});

				//actualizar las demas hora a inactivas

				var inact = {
					valor: c,
					action: 'inactivar_horas_update'
				};

				$.ajax({
					url: url2,
					type: 'POST',
					data: inact,
					dataType: 'json',
					success: function(data) {
						console.log('inactivo las demas horas');
						// alert('Actualizar Registrados Exitosamente!');
						// $("html, body").animate({ scrollTop: 0 }, 600);
						// setTimeout(function() { location.reload(false);  }, 800);	
					},
					error: function(jqXHR, textStatus, errorThrown) {
						consle.log('error');
						console.log(jqXHR);
						console.log(textStatus);
						console.log(errorThrown);
					}
				});


				alert('Actualizar Registrados Exitosamente!');
				$("html, body").animate({
					scrollTop: 0
				}, 600);
				setTimeout(function() {
					location.reload(false);
				}, 800);



			}
		});
	</script>