<?php
	$_dbTable = "monedas"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->monedas) /* && count($this->monedas) */){

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_view = '
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width:10%;">#</th>
									<th>Moneda</th>
									<th style="min-width:10%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayTarifa = $this->monedas->getTabla();
		// echo print_r($arrayTarifa);
		if ($arrayTarifa) {
			foreach ($arrayTarifa as $key => $value) {

				/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
				switch ($value["estado"]) {
					case '0':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-danger">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

						$_popupHabilita = $alert->_alert_modal_mod_success( $value['id'] , "Realmente desea habilitar este elemento?" , $_dbTable );
						$vista.= $_popupHabilita[0];
						$_jsScripts.=$_popupHabilita[1];

						// se asigna contenudo de la columna de acciones
						$col_action = '
							<td class="actions">
								<span id="#habilita_' . $value['id'] . '" data-toggle="modal" data-target="#habilita_' . $value['id'] . '" class="icon mdi mdi-check-circle"></span>
							</td>
						';
						break;
					
					case '1':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-success">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

						// se genera el formulario de edicion del registro
						$form_edit_table = '
							<input type="hidden" name="id" value="' . $value['id'] . '" class="form-control">
							<div class="form-group col-xs-6">
								<label>(*) Moneda:</label>
								<input type="text" name="nom_moneda" id="nom_moneda_' . $value['id'] . '" value="' . $value["nom_moneda"] . '" placeholder="Servicio Especial" class="form-control">
								<label id="error_nom_moneda_' . $value['id'] . '"></label>
							</div>
							<div class="form-group col-xs-6">
								<label>(*) Código:</label>
								<input type="text" name="codigo" id="codigo_' . $value['id'] . '" value="' . $value["codigo"] . '" placeholder="Servicio Especial" class="form-control">
								<label id="error_codigo_' . $value['id'] . '"></label>
							</div>
							<div class="row"></div>
						';

						// Validacion de contenido del formulario de creacion
						$_jsScripts.='
							<script type="text/javascript">
								var validar_nom_moneda = "";
								$("#nom_moneda_' . $value['id'] . '").focusin(function (){
									removerClaseserror("#error_nom_moneda_' . $value['id'] . '", "#nom_moneda_' . $value['id'] . '");
								});

								$("#nom_moneda_' . $value['id'] . '").focus(function (){
									$("#nom_moneda_' . $value['id'] . '").keypress(function() {
										validarkeypress("#error_nom_moneda_' . $value['id'] . '", "#nom_moneda_' . $value['id'] . '");
									});
								});

								$("#nom_moneda_' . $value['id'] . '").focusout(function (){
									validar_nom_moneda = validaciones("vacio" , $("#nom_moneda_' . $value['id'] . '").val() , "Moneda");
									if(validar_nom_moneda != true){
										agregarClaseserror("#error_nom_moneda_' . $value['id'] . '", "#nom_moneda_' . $value['id'] . '", validar_nom_moneda);
									}
									else{
										removerClaseserror("#error_nom_moneda_' . $value['id'] . '", "#nom_moneda_' . $value['id'] . '");
									}
								});

								var validar_codigo_' . $value['id'] . ' = "";
								$("#codigo_' . $value['id'] . '").focusin(function (){
									removerClaseserror("#error_codigo_' . $value['id'] . '", "#codigo_' . $value['id'] . '");
								});

								$("#codigo_' . $value['id'] . '").focus(function (){
									$("#codigo_' . $value['id'] . '").keypress(function() {
										validarkeypress("#error_codigo_' . $value['id'] . '", "#codigo_' . $value['id'] . '");
									});
								});

								$("#codigo_' . $value['id'] . '").focusout(function (){
									validar_codigo_' . $value['id'] . ' = validaciones("vacio" , $("#codigo_' . $value['id'] . '").val() , "Código");
									if(validar_codigo_' . $value['id'] . ' != true){
										agregarClaseserror("#error_codigo_' . $value['id'] . '", "#codigo_' . $value['id'] . '", validar_codigo_' . $value['id'] . ');
									}
									else{
										removerClaseserror("#error_codigo_' . $value['id'] . '", "#codigo_' . $value['id'] . '");
									}
								});
							</script>
						';

						$_popupEdita = $form_edita->_form_modal_update($value['id'], "Editar Moneda - " . $value['nom_moneda'] , $form_edit_table, $_dbTable);
						$vista.= $_popupEdita[0];
						$_jsScripts.=$_popupEdita[1];


						$_popupElimina = $alert->_alert_modal_mod_danger($value['id'], "Realmente desea eliminar este elemento?",$_dbTable);
						$vista.= $_popupElimina[0];
						$_jsScripts.=$_popupElimina[1];
						// se asigna contenudo de la columna de acciones
						$col_action = '
							<td class="actions">
								<span id="edita_' . $value['id'] . '" data-toggle="modal" data-target="#edita_' . $value['id'] . '" class="icon mdi mdi-edit"></span>
								<span id="elimina_' . $value['id'] . '"data-toggle="modal" data-target="#elimina_' . $value['id'] . '" class="icon mdi mdi-close-circle"></span>
							</td>
						';

						break;
				}
				/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

				// Se maqueta contenido de la tabla 
				$table_view.= '<tr>';
				$table_view.= $col_stasus;
				$table_view.= '
					<td class="cell-detail">
						<span>' . $value["nom_moneda"] . '</span>
						<span class="cell-detail-description">' . $value["codigo"] . '</span>
					</td>
				';

				// se asigna la columna de acciones
				$table_view.=$col_action;
				
				$table_view.= '</tr>';
			}

			$table_view.= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
		}else{
			echo '<p>no hay registros en esta tabla...</p>';
		}
	}else{
		echo '<p>no hay registros en esta tabla...</p>';
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Monedas
				<div class="tools">
					<a href="#" data-toggle="modal" data-target="#crea_' . $_dbTable . '" class="cell-detail  hint--top"  data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a> 
				</div>
				<span class="panel-subtitle">Determina las monedas que serán usadas para fijar la moneda del valor de un proyecto o del costo un servicio especial.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


  	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();


			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';


	/****** CREACION CONTENIDO DE POPUPS ******/

	// CONTENIDO DEL POPUP DE FORMULARIO DE CREACION
	$forms = '
		<div class="form-group col-xs-6">
			<label>(*) Moneda:</label>
			<input type="text" name="nom_moneda" id="nom_moneda" placeholder="Nombre Moneda" class="form-control">
			<label id="error_nom_moneda"></label>
		</div>
		<div class="form-group col-xs-6">
			<label>(*) Código:</label>
			<input type="text" name="codigo" id="codigo" placeholder="Código" maxlength="3"  class="form-control">
			<label id="error_codigo"></label>
		</div>
		<div class="row"></div>
	';

	// Valifdacion de contenido del formulario de creacion
	$_jsScripts.='
		<script type="text/javascript">
			var validar_codigo = "";
			var validar_nom_moneda = "";

			$("#nom_moneda").focusin(function (){
				removerClaseserror("#error_nom_moneda", "#nom_moneda");
			});

			$("#nom_moneda").focus(function (){
				$("#nom_moneda").keypress(function() {
					validarkeypress("#error_nom_moneda", "#nom_moneda");
				});
			});

			$("#nom_moneda").focusout(function (){
				validar_nom_moneda = validaciones("vacio" , $("#nom_moneda").val() , "Moneda");
				if(validar_nom_moneda != true){
					agregarClaseserror("#error_nom_moneda", "#nom_moneda", validar_nom_moneda);
				}
				else{
					removerClaseserror("#error_nom_moneda", "#nom_moneda");
				}
			});

			$("#codigo").focusin(function (){
				removerClaseserror("#error_codigo", "#codigo");
			});

			$("#codigo").focus(function (){
				$("#codigo").keypress(function() {
					validarkeypress("#error_codigo", "#codigo");
				});
			});

			$("#codigo").focusout(function (){
				validar_codigo = validaciones("vacio" , $("#codigo").val() , "Código");
				if(validar_codigo != true){
					agregarClaseserror("#error_codigo", "#codigo", validar_codigo);
				}
				else{
					removerClaseserror("#error_codigo", "#codigo");
				}
			});

			var flagError = "";
			if ( validar_codigo != true || validar_nom_moneda != true ) {
				flagError = false;
			} else {
				flagError = true;
			}
			
		</script>
	';

	$_popupCrea = $form_crea->_form_modal_simple_insert("crea_" . $_dbTable ,"Crear Moneda" , $forms , $_dbTable );
	$vista.= $_popupCrea[0];
	$_jsScripts.=$_popupCrea[1];


	/****** FIN CREACION CONTENIDO DE POPUPS ******/

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_view , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
