<?php
$_dbTable = "importacion_proyecto"; // SIN EL PREFIJO cmx_
$_jsScripts = "";
$_jsAjax = "";
$_time = date('Y-m-d', TIME());

$vista = '<link rel="stylesheet" type="text/css" href="%root_file%lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>';

// se definen las variables de session
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
$ssn_id_bodega = $_SESSION["usuario"]["id_bodega"];

// Se verifican los permisos del pefil de usuario
$arrayPermisos = $this->importacion->permisosPerfil($ssn_id_perfil, 21);

$_GET["sw"] = "";
$_GET["clientefiltro"] = "";
$_POST["clientefiltro"] = "";
$_POST["tipo"] = "";
$_POST["buscar_coti"] = "";


/********* POPUPS *********/
/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
// POPUP DE MUESTRA DE INFORMACION
$info = new Popup();
// POPUP DE ALERTA DE CONFIRMACION
$alert = new Popup();
// POPUP DE FORMULARIO DE EDICION 
$form_edita = new Popup();
// POPUP DE FORMULARIO DE CREACION 
$form_crea = new Popup();

/********* FIN POPUPS *********/

/*** CREACION DE TABLA DE CONTENIDO ***/
if (isset($this->importacion)) {
	$grupo = 1;
	//SE CREA FILTROS PARA LA TABLA

	$cliente = '';
	$cliente .= "<div class='col-xs-6 cli'><label>Cliente</label><select id='clientefiltro' class='form-control input-sm'>";
	$array = $this->importacion->consultar_clientes();
	if ($array) {
		foreach ($array as $key => $value) {
			$cliente .= '<option value="' . $value['id'] . '">' . $value['nombre'] . '-' . $value['documento'] . '</option>';
		}
	}
	$cliente .= '</select></div>';

	$filtro = "<div class='row'>
			<div class='col-sm-3'>
				<label>Tipo:</label>
				<select id='tipotb' class='form-control input-sm'>
					<option value='2'>Do proyecto</option>
					<option value='1'>Cliente</option>
				</select>	
			</div>
			<div>" . $cliente . "</div>

			<div class='col-sm-3 fi'>
				<label>DO del proyecto:</label>
				<input  type='text' id='fecha_incia' class='form-control input-sm'>
			</div>
			<div class='col-sm-3'>
				<br>

				<button class='btn btn-success btn-md' id='buscar_coti' name='buscar_coti'>Buscar</button>
			</div>
		</div>";



	if (isset($_GET["i"]) == 1) {
		if ($_GET["i"] == 1) {
			$tipo = $_GET["a"];
			$cliente = $_GET["b"];
			$fi = $_GET["c"];
		}

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_view = '
			<div class="table-responsive noSwipe col-xs-12 col-sm-12 col-md-12">
				<table id="table1" class="table table-striped table-hover table-fw-widget" data-page-length="100">
					<thead>
						<tr class="nexos-encabezado">
							<th style="width:4%;">#</th>
							<th style="width:7%;">Cant. Materiales</th>
							<th>Tipo Operación</th>
							<th>Operación</th>
							<th>Tipo Carga</th>
							<th>Contenedor</th>
							<th>Cliente</th>
							<th>Fecha - Hora</th>
							<th style="width:6%;"></th>
						</tr>
					</thead>
					<tbody>
		';

		$arrayImportaciones = $this->importacion->getProyectosImportacionActivos($_SESSION["usuario"], $tipo, $cliente, $fi);
		if (isset($arrayImportaciones["proyectos"])) {
			foreach ($arrayImportaciones["proyectos"] as $key => $value) {
				/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
				$col_action = '<td class="actions"></td>';
				switch ($value["estado"]) {
					case '0':
						// se asigna contenudo de la columna de acciones
						if ($arrayPermisos["eliminar"] == 1) {
							$col_action = '
								<td class="actions">
									<a href="javascript:" onclick="habilitar_proyecto(this)" class="cell-detail hint--top-left" data-hint="Habilitar" data-id="' . $value['ID_IMPORTACION'] . '"><span class="icon mdi mdi-check-circle" data-toggle="modal" data-target="#habilitar"></span></a>
								</td>
							';/* 							$col_action = '
								<td class="actions">
									<a href="javascript:" onclick="habilitar_proyecto(this)" class="cell-detail hint--top-left" data-hint="Habilitar" data-id="' . $value['ID_PROYECTO_INTERNACIONAL'] . '"><span class="icon mdi mdi-check-circle" data-toggle="modal" data-target="#habilitar"></span></a>
								</td>
							'; */
						}
						break;

					case '1':
						// se asigna contenido de la columna de acciones
						$_btn_crea = '';
						if ($arrayPermisos["eliminar"] == 1) {
							$_btn_ver = '';
							if ($value["FLAG_CONTRATO"]) {
								$_btn_ver = '
									<a href="' . BASE_URL . 'importacion/ver_actividades/' . $value["numero_importacion"] . '" class="icon hint--top-left" data-hint="Ver Actividades"><span  class="mdi mdi-eye"></span></a>
								';
							}
							$col_action = '
								<td class="actions">
									' . $_btn_ver . '
									<a href="javascript:" onclick="eliminar_proyecto(this)" class="cell-detail hint--top-left" data-hint="Eliminar" data-id="' . $value['ID_IMPORTACION'] . '"><span class="icon mdi mdi-close-circle" data-toggle="modal" data-target="#eliminar"></span></a>
								</td>
							';/* 							$col_action = '
								<td class="actions">
									' . $_btn_ver . '
									<a href="javascript:" onclick="eliminar_proyecto(this)" class="cell-detail hint--top-left" data-hint="Eliminar" data-id="' . $value['ID_PROYECTO_INTERNACIONAL'] . '"><span class="icon mdi mdi-close-circle" data-toggle="modal" data-target="#eliminar"></span></a>
								</td>
							'; */
						} else {
							$col_action = '
								<td class="actions">
									<a href="' . BASE_URL . 'importacion/ver_actividades/' . $value["numero_importacion"] . '" class="icon hint--top-left" data-hint="Ver Actividades"><span  class="mdi mdi-eye"></span></a>
								</td>
							';
						}
						break;

					case '2':
						// se asigna contenudo de la columna de acciones
						if ($arrayPermisos["eliminar"] == 1) {
							$col_action = '
								<td class="actions">
									<a href="javascript:" onclick="eliminar_proyecto(this)" class="cell-detail hint--top-left" data-hint="Eliminar" data-id="' . $value['ID_IMPORTACION'] . '"><span class="icon mdi mdi-close-circle" data-toggle="modal" data-target="#eliminar"></span></a>
								</td>
							';
						}/* 						if ($arrayPermisos["eliminar"] == 1) {
							$col_action = '
								<td class="actions">
									<a href="javascript:" onclick="eliminar_proyecto(this)" class="cell-detail hint--top-left" data-hint="Eliminar" data-id="' . $value['ID_PROYECTO_INTERNACIONAL'] . '"><span class="icon mdi mdi-close-circle" data-toggle="modal" data-target="#eliminar"></span></a>
								</td>
							';
						} */
						break;
				}
				/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

				/*** FILTRO DE SEMAFORO INDICADOR DE ESTADO DEL PROYECTO CON RELACIÓN A LAS ACTIVIDADES ***/
				$_estado_proyecto = $this->importacion->getEstadoActividades($value['ID_PROYECTO_INTERNACIONAL']);

				$col_stasus = '
					<td class="' . $_estado_proyecto["estado"] . '">
						<center>
							<span class="mdi mdi-dot-circle icon"></span>
						</center>
					</td>
				';
				/*** FIN FILTRO DE SEMAFORO INDICADOR DE ESTADO DEL PROYECTO CON RELACIÓN A LAS ACTIVIDADES ***/

				// Se maqueta contenido de la tabla 
				$table_view .= '<tr>';
				$table_view .= $col_stasus;
				// Columna información cantidad de materiales de la importación
				$table_view .= '
					<td class="cell-detail">
						<span class="label label-default">' . $value["MATERIALES_PROYECTO"] . '</span>
					</td>
				';

				/****** FILTRO DE MENSAJE DEL CONTRATO DEL CLIENTE ******/
				$_contrtato_text = "";
				if ($value["NUM_CONTRATO"]) {
					$_contrtato_text = '
						<span class="cell-detail-description">' . $value["NUM_CONTRATO"] . '</span>
					';

					if (!$value["FLAG_CONTRATO"]) {
						$_contrtato_text .= '
							<span class="cell-detail-description"><strong class="text-danger">Contrato pendiente de aprobación</strong></span>
						';
					}
				}
				/****** FIN - FILTRO DE MENSAJE DEL CONTRATO DEL CLIENTE ******/

				// Columna Tipo de operación
				$table_view .= '
					<td class="cell-detail">
						<span>' . $value["tipo_operacion"] . '</span>
						' . $_contrtato_text . '
						<span class="cell-detail-description">' . $value["TIPO_TRANSPORTE"] . '</span>
						<span class="cell-detail-description">' . $value["INCOTERM"] . '</span>
					</td>
				';

				/***** FILTROS DE MENSAJE SI EL PROYECTO ES NUEVO *****/
				// Se calcula los dias de creado el proyecto
				$_time_proyecto = date('Y-m-d', $value["numero_importacion"]);
				$date1 = new DateTime($_time);
				$date2 = new DateTime($_time_proyecto);
				$diff = $date1->diff($date2);

				// Se filtra el contenido del mensaje 	
				$_proyecto_nuevo = '';
				if ($diff->days <= 2) {
					$_proyecto_nuevo = '<strong class="text-danger">(Nuevo)</strong>';
				}
				/***** FIN - FILTROS DE MENSAJE SI EL PROYECTO ES NUEVO *****/

				/***** FILTROS DE MENSAJE SI EL PROYECTO INTERNACIONAL FUE APROBADO *****/
				$_do_proyecto = '';
				if ($value["DO_PROYECTO"]) {
					$_do_proyecto = '<strong>' . $value["DO_PROYECTO"] . '</strong>';
				}
				/***** FIN - FILTROS DE MENSAJE SI EL PROYECTO INTERNACIONAL FUE APROBADO *****/

				/***** FILTROS DE MENSAJES DE ESTADO DEL PROYECTO INTERNACIONAL *****/
				// Se filtra la información del estado del proyecto internacional 
				$_msg_estado_proyecto = "";
				$_intr_valor_oferta = '';
				if (isset($arrayImportaciones["info_internacional"][$value['ID_PROYECTO_INTERNACIONAL']])) {
					$info_internacional = $arrayImportaciones["info_internacional"][$value['ID_PROYECTO_INTERNACIONAL']];

					if ($info_internacional["VALOR_OFERTA"]) {
						$_intr_valor_oferta = "Valor Oferta <strong>" . number_format($info_internacional["VALOR_OFERTA"], 2, ',', '.') . " " . $info_internacional["MONEDA_OFERTA"] . "</strong>";
					}

					// Se filtra el color de los mensajes del estado del proyecto
					// Oferta Comercial 
					switch ($info_internacional["OFERTA_COMERCIAL"]) {
						case 'OCN':
							$_oferta_comercial = ' <strong class="text-danger hint--top" data-hint="Oferta Comercial no presentada">' . $info_internacional["OFERTA_COMERCIAL"] . '</strong> ';
							break;

						case 'OCP':
							$_oferta_comercial = ' <strong class="text-warning hint--top" data-hint="Oferta Comercial presentada">' . $info_internacional["OFERTA_COMERCIAL"] . '</strong> ';
							break;

						case 'OCA':
							$_oferta_comercial = ' <strong class="text-success hint--top" data-hint="Oferta Comercial aprobada">' . $info_internacional["OFERTA_COMERCIAL"] . '</strong> ';
							break;

						default:
							$_oferta_comercial = ' <strong class="text-danger hint--top" data-hint="Error en la Oferta Comercial">ERR</strong> ';
							break;
					}

					// Cotización de Proveedores
					switch ($info_internacional["COTIZACION_PROVEEDORES"]) {
						case 'SC':
							$_cotizacion_proveedores = ' <strong class="text-danger hint--top" data-hint="Sin Cotizaciones">' . $info_internacional["COTIZACION_PROVEEDORES"] . '</strong> ';
							break;

						case 'CP':
							$_cotizacion_proveedores = ' <strong class="text-warning hint--top" data-hint="Cotizaciones presentadas">' . $info_internacional["COTIZACION_PROVEEDORES"] . '</strong> ';
							break;

						case 'CPA':
							$_cotizacion_proveedores = ' <strong class="text-warning hint--top" data-hint="Cotizaciones pendientes de aprobar">' . $info_internacional["COTIZACION_PROVEEDORES"] . '</strong> ';
							break;

						case 'CA':
							$_cotizacion_proveedores = ' <strong class="text-success hint--top" data-hint="Cotizaciones aprobadas">' . $info_internacional["COTIZACION_PROVEEDORES"] . '</strong> ';
							break;

						default:
							$_cotizacion_proveedores = ' <strong class="text-danger hint--top" data-hint="Error en la Cotizacion de Proveedores">ERR</strong> ';
							break;
					}

					// Pruebas de entrega 
					switch ($info_internacional["PRUEBA_ENTREGA"]) {
						case 'PEP':
							$_prueba_entrega = ' <strong class="text-danger hint--top" data-hint="Prueba de Entrega pendiente">' . $info_internacional["PRUEBA_ENTREGA"] . '</strong> ';
							break;

						case 'PEE':
							$_prueba_entrega = ' <strong class="text-success hint--top" data-hint="Prueba de Entrega presentada">' . $info_internacional["PRUEBA_ENTREGA"] . '</strong> ';
							break;

						default:
							$_prueba_entrega = ' <strong class="text-danger hint--top" data-hint="Error en la Prueba de Entrega">ERR</strong> ';
							break;
					}

					// Instrucciones de Facturación 
					switch ($info_internacional["INSTRUCCION_FACTURA"]) {
						case 'IFP':
							$_instruccion_factura = ' <strong class="text-danger hint--top" data-hint="Instrucción de Factura pendiente">' . $info_internacional["INSTRUCCION_FACTURA"] . '</strong> ';
							break;

						case 'IFR':
							$_instruccion_factura = ' <strong class="text-success hint--top" data-hint="Instrucción de Factura realizada">' . $info_internacional["INSTRUCCION_FACTURA"] . '</strong> ';
							break;

						default:
							$_instruccion_factura = ' <strong class="text-danger hint--top" data-hint="Error en la Instrucción de Factura">ERR</strong> ';
							break;
					}

					// Facturación
					switch ($info_internacional["FACTURA"]) {
						case 'FP':
							$_factura = ' <strong class="text-danger hint--top" data-hint="Factura pendiente">' . $info_internacional["FACTURA"] . '</strong> ';
							break;

						case 'FR':
							$_factura = ' <strong class="text-success hint--top" data-hint="Factura realizada">' . $info_internacional["FACTURA"] . '</strong> ';
							break;

						default:
							$_factura = ' <strong class="text-danger hint--top" data-hint="Error en la Factura">ERR</strong> ';
							break;
					}

					$_msg_estado_proyecto = '<span class="cell-detail-description">' . $_oferta_comercial . $_cotizacion_proveedores . $_prueba_entrega . $_instruccion_factura . $_factura . '</span>';
				}

				// Se filtra si el proyecto ya ha terminado
				if ($_estado_proyecto["terminado"]) {
					$_msg_estado_proyecto = '<span><strong class="text-success">Proyecto terminado</strong></span>';
				}

				// Se filtra el estado del proyecto internacional
				if ($value["INTR_ESTADO_PROYECTO"]) {
					$_msg_estado_proyecto = '
						<span><strong class="text-danger">Proyecto no aprobado</strong></span>
						<span class="cell-detail-description">' . $value["INTR_ESTADO_PROYECTO"] . '</span>
					';
				}

				// Se filtra si el proyecto esta inactivo
				if ($value["estado"] == 0) {
					$_msg_estado_proyecto = '<span><strong class="text-danger">Proyecto inhabilitado</strong></span>';
				}
				/***** FILTROS DE MENSAJES DE ESTADO DEL PROYECTO *****/

				// Columna información de la operación
				$table_view .= '
					<td class="cell-detail">
						<span>' . $_do_proyecto . '</span>
						<span>' . $_proyecto_nuevo . ' ' . $value["importacion"] . '</span>
						<span class="cell-detail-description"><strong>' . $value["numero_importacion"] . '</strong> | ' . date('Y-m-d', $value["numero_importacion"]) . '</span>
						' . $_msg_estado_proyecto . '
					</td>
				';

				// Columna información tipo de carga
				$table_view .= '<td class="cell-detail"><span>' . $value["TIPO_CARGA"] . '</span></td>';

				// Columna Contenedor
				$_contenedor = '';
				if ($value["TIPO_CARGA"] == "FCL") {
					$_contenedor = '
						<span>' . $value["contenedor"] . '</span>
						<span class="cell-detail-description">' . $value["NOM_CONTENEDOR"] . '</span>
						<span class="cell-detail-description">' . $value["TARA_CONTENEDOR"] . ' Kg</span>
					';
				}
				$table_view .= '<td class="cell-detail">' . $_contenedor . '</td>';

				// Columna información del cliente
				$table_view .= '
					<td class="cell-detail">
						<span>' . $value["CLIENTE"] . '</span>
						<span class="cell-detail-description">' . $_intr_valor_oferta . '</span>
					</td>
				';

				//fecha y hora
				$table_view .= '<td class="cell-detail">
					<span>' . $value['fecha_hora'] . '</span>
				</td>';


				// se asigna la columna de acciones
				$table_view .= $col_action;

				$table_view .= '</tr>';
			}
		}

		$table_view .= '
					</tbody>
				</table>
			</div>
		';
	}
}

/*** FIN CREACION DE TABLA DE CONTENIDO ***/


/**** CONTENIDO DEL MODULO EN PANTALLA ****/

// Se verifica si el usuario puede crear proyecto de importación 
$_btn_crea = '
		<div class="tools">
			<a href="' . BASE_URL . 'importacion/proyectos/" class="cell-detail hint--top-left" data-hint="Ver todos los proyectos"><span class="icon mdi mdi-eye"></span></a> 
		</div>
	';
if ($arrayPermisos["adicionar"] == 1) {
	$_btn_crea .= '
			<div class="tools">
				<a href="#" data-toggle="modal" data-target="#crea_' . $_dbTable . '" class="cell-detail hint--top" data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a> 
			</div>
		';
}

$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Administrar Proyectos  
				' . $_btn_crea . '
				<span class="panel-subtitle">Módulo de administración de proyectos de transporte de materiales.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				' . $filtro . '
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>

		<div id="eliminar" tabindex="-1" role="dialog" class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close"><span class="mdi mdi-close"></span></button>
					</div>
					<div class="modal-body">
						<div class="msg_error_danger"></div>
						<div class="text-center">
							<form id="form_eliminar">
								<div class="text-danger"><span class="modal-main-icon mdi mdi-close-circle"></span></div>
								<h3>Alerta!</h3>
								<p>Realmente desea eliminar este elemento?</p>
								<div class="xs-mt-50">
									<input type="hidden" name="id" id="id">
									<input type="hidden" name="estado" id="estado" value="0">
									<button type="button" data-dismiss="modal" class="btn btn-space btn-default">Cancelar</button>
									<button id="btn_eliminar" type="button" class="btn btn-space btn-danger">EliminarES</button>
								</div>
							</form>
						</div>
					</div>
					<div class="modal-footer"></div>
				</div>
			</div>
		</div>

		<div id="habilitar" tabindex="-1" role="dialog" class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close"><span class="mdi mdi-close"></span></button>
					</div>
					<div class="modal-body">
						<div class="msg_error_success"></div>
						<div class="text-center">
							<form id="form_habilitar">
								<div class="text-success"><span class="modal-main-icon mdi mdi-check-circle"></span></div>
								<h3>Alerta!</h3>
								<p>Realmente desea habilitar este elemento?</p>
								<div class="xs-mt-50">
									<input type="hidden" name="id" id="id">
									<input type="hidden" name="estado" id="estado" value="1">
									<button type="button" data-dismiss="modal" class="btn btn-space btn-default">Cancelar</button>
									<button id="btn_habilitar" type="button" class="btn btn-space btn-success">Aceptar</button>
								</div>
							</form>
						</div>
					</div>
					<div class="modal-footer"></div>
				</div>
			</div>
		</div>
	';

/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
$vista .= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
			%js-ajax%
	    </script>
	';

/****** CREACION CONTENIDO DE POPUPS ******/
// CONTENIDO DEL POPUP DE FORMULARIO DE CREACION

$_slct_tipo_operacion = $this->importacion->getEnumSlctTipoOperacion_sm("tipo_operacion", "", "");
$_slct_tipo_carga = $this->importacion->getHtmlSelectTipoCarga_sm("id_tipo_carga", "");
$_slct_clientes = $this->clientes->getHtmlSelect_sm("id_cliente", "", 1);
$_slct_contenedores = $this->contenedores->getHtmlSelect_sm("tipo_contenedor_1", "");
$_slct_rndc_tipo_material = $this->importacion->getHtmlSelectRNDCTipoMaterial_sm("id_rndc_material", "");

// Elementos del formulario de contratos
// Select de tipo de contrato
$_slct_tipo_contrato = $this->clientes->getEnumSlctTipoContrato_sm("tipo_contrato", "", "");
// Select de origenes
$_slct_origenes = $this->clientes->getHtmlSelectMunicipios_multi("origenes", "", true);
// Select de destinos 
$_slct_destinos = $this->clientes->getHtmlSelectMunicipios_multi("destinos", "", true);
// Select de tipo de vehículos
$_slct_tipo_vehiculos = $this->clientes->getHtmlSlctTipoVehiculos_multi("tipos_vehiculo", "", "");
$_condiciones = $this->clientes->getCondicionesContrato();

$forms = '
		<input type="hidden" name="grupo" id="grupo" value="' . $grupo . '">
		<div class="row">
			<div class="form-group col-xs-3">
				<label>(*) Tipo de Operación:</label>
				' . $_slct_tipo_operacion . '
			</div>
			<div class="form-group col-xs-4">
				<label>(*) Número de Operación para el Cliente:</label>
				<input type="text" name="importacion" id="importacion" placeholder="# Operación para el Cliente" class="form-control input-sm">
			</div>
			<div class="form-group col-xs-3 internacional" style="display: none;">
				<label>Comodín Facturación:</label>
				<input type="text" name="intr_comodin_facturacion" id="intr_comodin_facturacion" placeholder="Comodín Facturación" class="form-control input-sm"></label>
			</div>
			<div class="form-group col-xs-3 nacional" style="display: none;">
				<label>(*) Tipo de Material:</label>
				' . $_slct_rndc_tipo_material . '
			</div>
			<!--
			<div class="form-group col-xs-2 be-checkbox nacional" style="display: none;">
			-->
			<div class="form-group col-xs-2 be-checkbox" style="display: none;">
				<label>Solicitud Urbano:</label><br>
				<input type="checkbox" name="solicita_urbano" id="solicita_urbano">
				<label for="solicita_urbano"></label>
			</div>
		</div>
		<div class="row" id="div_clientes"></div>
		<div class="row" id="div_contrato">
			<!-- FORMULARIO DE GENERALIDAES DEL CONTRATO -->
			<div class="form-group col-xs-12 col-sm-6 col-md-3">
				<label>(*) Tipo Contrato:</label>
				' . $_slct_tipo_contrato . '
			</div>
			<div class="form-group col-xs-12 col-sm-6 col-md-3">
				<label id="valor_contrato_text">(*) Valor Contrato:</label>
				<input type="text" name="valor_contrato" id="valor_contrato" class="form-control input-sm" onload="getFormatoNumeroDecimal(this)" onkeyup="getFormatoNumeroDecimal(this)" onchange="getFormatoNumeroDecimal(this)" placeholder="Valor Contrato">
			</div>
			<div class="form-group col-xs-12 col-sm-6 col-md-3">
				<label>(*) Inicio de Contrato:</label>
				<div data-min-view="2" data-start-view="4" data-date-format="yyyy-mm-dd" data-link-field="dtp_input1" class="input-group date datetimepicker" style="padding: 0">
					<input size="10" type="text" value="' . $_time . '" name="inicio_contrato" id="inicio_contrato" readonly="" class="form-control input-sm">
					<span class="input-group-addon btn btn-primary"><i class="icon-th mdi mdi-calendar"></i></span>
				</div>
			</div>
			<div class="form-group col-xs-12 col-sm-6 col-md-3">
				<label>(*) Finalización de Contrato:</label>
				<div data-min-view="2" data-start-view="4" data-date-format="yyyy-mm-dd" data-link-field="dtp_input1" class="input-group date datetimepicker" style="padding: 0">
					<input size="10" type="text" value="' . date('Y-m-d', strtotime('+1 year', strtotime($_time))) . '" name="fin_contrato" id="fin_contrato" readonly="" class="form-control input-sm">
					<span class="input-group-addon btn btn-primary"><i class="icon-th mdi mdi-calendar"></i></span>
				</div>
			</div>
			<div class="form-group col-xs-12 col-sm-6 col-md-4">
				<label class="control-label">(*) Adjunto Contrato:</label><br>
				<input type="file" name="url_contrato" id="url_contrato" class="inputfile">
				<label for="url_contrato" class="btn-success"> <i class="mdi mdi-upload"></i><span>Buscar Archivo...</span>:</label>
			</div>
			<!-- FORMULARIO DE CONDICIONES DEL CONTRATO -->
			<div class="col-xs-12 col-sm-12 col-md-12">
				<h4>Condiciones</h4>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-12">
				<div class="be-checkbox">
					<input class="condiciones" id="geografico" type="checkbox">
					<label for="geografico">Origenes y Destinos</label>
				</div>
			</div>
			<div class="form-group col-xs-12 col-sm-12 col-md-12" id="geografico_content">
				<div class="form-group col-xs-12 col-sm-12 col-md-12">
					<label class="control-label" for="origenes">(*) Orígenes:</label>
					' . $_slct_origenes . '
				</div>
				<div class="form-group col-xs-12 col-sm-12 col-md-12">
					<label class="control-label" for="destinos">(*) Destinos:</label>
					' . $_slct_destinos . '
				</div>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-12">
				<div class="be-checkbox">
					<input class="condiciones" id="tipo_vehiculo" type="checkbox">
					<label for="tipo_vehiculo">Tipos de vehículo</label>
				</div>
			</div>
			<div class="form-group col-xs-12 col-sm-12 col-md-12" id="tipo_vehiculo_content">
				<div class="form-group col-xs-12 col-sm-12 col-md-12">
					<label class="control-label" for="tipos_vehiculo">(*) Tipos de Vehículo:</label>
					' . $_slct_tipo_vehiculos . '
				</div>
			</div>
			' . $_condiciones . '
			<div class="form-group col-xs-12 col-sm-12 col-md-12"></div>
		</div>
		<div class="row tramo_clon" id="form_tramo_1"></div>
		<div class="row" id="div_form_intencional"></div>
		<div class="row">
			<div class="form-group col-xs-3">
				<label>(*) Tipo de Carga:</label>
				' . $_slct_tipo_carga . '
			</div>
			<div class="icon col-xs-9 div_contenedor" style="display: none; padding-top: 32px;">
				<button type="button" class="btn btn-space btn-success btn-big hint--top-left" data-hint="Agregar Contenedor" id="btn_agrega"><span class="mdi mdi-plus"></span></button>
				<button type="button" class="btn btn-space btn-danger btn-big hint--top-left" data-hint="Quitar Contenedor" id="btn_quita"><span class="mdi mdi-minus"></span></button>
			</div>
		</div>
		<div class="row form-group contenedor_clon" id="form_contenedor_1">
			<div class="col-xs-1 be-checkbox div_contenedor" id="div_devolucion_1" style="display: none; padding-left:15px;">
				<label>Devolución:</label><br>
				<input type="checkbox" name="devolucion_1" id="devolucion_1" onclick="muestraDevolucion(this.id);">
				<label for="devolucion_1" id="label_devolucion_1"></label>
			</div>
			<div class="col-xs-3 div_contenedor" id="div_tipo_contenedor_1" style="display: none;">
				<label>(*) Tipo de Contenedor:</label>
				' . $_slct_contenedores . '
			</div>
			<div class="col-xs-2 div_contenedor" id="div_contenedor_1" style="display: none;">
				<label>(*) # Contenedor:</label>
				<input type="text" name="contenedor_1" id="contenedor_1" placeholder="# Contenedor" class="form-control input-sm"><label id="error_contenedor"></label>
			</div>
			<div class="col-xs-3 div_contenedor div_devolucion" id="div_devolucion_contenedor_1" style="display: none;">
				<label>(*) Devolución Contenedor:</label>
				<div data-min-view="2" data-start-view="4" data-date-format="yyyy-mm-dd" data-link-field="dtp_input1" class="input-group date datetimepicker" style="padding: 0">
					<input size="10" type="text" value="" name="devolucion_contenedor_1" id="devolucion_contenedor_1" readonly="" class="form-control input-sm">
					<span class="input-group-addon btn btn-primary"><i class="icon-th mdi mdi-calendar"></i></span>
				</div>
			</div>
			<div class="col-xs-3 div_contenedor div_devolucion" id="div_fecha_comodato_1" style="display: none;">
				<label>(*) Fecha Comodato:</label>
				<div data-min-view="2" data-start-view="4" data-date-format="yyyy-mm-dd" data-link-field="dtp_input1" class="input-group date datetimepicker" style="padding: 0">
					<input size="10" type="text" value="" name="fecha_comodato_1" id="fecha_comodato_1" readonly="" class="form-control input-sm">
					<span class="input-group-addon btn btn-primary"><i class="icon-th mdi mdi-calendar"></i></span>
				</div>
			</div>
			<div class="row"></div>
			<div class="col-xs-3 div_contenedor div_devolucion" id="div_comodato_1" style="display: none;">
				<label class="control-label">(*) Adjunto Comodato:</label><br>
				<input type="file" name="url_comodato_1" id="url_comodato_1" class="inputfile">
				<label id="lbl_comodato_1" for="url_comodato_1" class="btn-success"> <i class="mdi mdi-upload"></i><span>Buscar Archivo</span>:</label>
			</div>
		</div>
		<div class="row">
			<div class="form-group col-xs-12">
				<label>Descripción:</label>
				<textarea name="descripcion_proyecto" placeholder="Descripción" class="form-control input-sm"></textarea>
			</div>
		</div>
		<div class="row">
			<div class="form-group col-xs-12" id="plantillas_actividades" style="display: none;"></div>
			<div class="col-xs-12">
				<div id="datos_platilla_"></div>
				<div id="msg_error_"></div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<div id="resultado"></div>
			</div>
		</div>
	';

// Validacion JS de seleccion de materiales 
$urlBuscaPlantilla = BASE_URL . 'libs/buscar.php?tabla=cmx_plantillas&id_cliente=' . $ssn_id_cliente;
$_jsAjax .= '';

$_popupCrea = $form_crea->_form_crea_importacion("crea_" . $_dbTable, "Crear Proyecto", $forms);
$vista .= $_popupCrea[0];
$_jsScripts .= $_popupCrea[1];
/****** FIN CREACION CONTENIDO DE POPUPS ******/

/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%js-ajax%", $_jsAjax, $vista);
$vista = str_replace("%content%", isset($table_view) ? $table_view : '', $vista);

// Se asiga codigo JS generado de la tabla de contenido
$vista .= $_jsScripts;

// SE PINTA CONTENIDO EN PANTALLA
echo $vista;

?>

<script type="text/javascript">
//FILTROS
var b = '';
var a = '';
var c = '';
$(".cli").hide();
$(".fi").show();

$("#tipotb").change(function() {
  //alert('cambio');
  var t = $("#tipotb").val();
  if (t == '') {
    $(".cli").hide();
    $(".fi").hide();
  }

  if (t == 1) {
    $(".cli").show();
    $(".fi").hide();
  }

  if (t == 2) {
    $(".fi").show();
    $(".cli").hide();
  }
});

$("#buscar_coti").click(function() {
  var a = $("#tipotb").val();
  if (a == '') {
    a == '';
    c = '';
    d = '';
    b = '';
    var url = $("#id_url_ajax").val() + 'importacion/index/?idmenu=2&i=1&a=' + a + '&b=' + b + '&c=' + c;
    window.location = (url);
  }

  if (a == 1) {
    b = $("#clientefiltro").val();
    c = '';
    d = '';
    var url = $("#id_url_ajax").val() + 'importacion/index/?idmenu=2&i=1&a=' + a + '&b=' + b + '&c=' + c;
    window.location = (url);
  }
  if (a == 2) {
    b = '';
    var p = $("#fecha_incia").val().trim();
    c = p; //DO
    var url = $("#id_url_ajax").val() + 'importacion/index/?idmenu=2&i=1&a=' + a + '&b=' + b + '&c=' + c;
    window.location = (url);
  }
});

$("#slct_tipo_operacion_").change(function() {
  $("#div_clientes").empty();
  $("#form_tramo_1").empty();

  // Se filtra vista de los campos de material y solicitud de urbano y se buscan los clientes correspondientes al tipo de operación
  var flag_vista;
  // Se filtra si el proyecto es nacional o internacional
  switch ($("#slct_tipo_operacion_").val()) {
    case 'IMPORTACION':
      flag_vista = "INTERNACIONAL";
      break;
    case 'EXPORTACION':
      flag_vista = "INTERNACIONAL";
      break;
    case 'NACIONAL_AEREO':
      flag_vista = "INTERNACIONAL";
      break;

    case 'NACIONAL':
      flag_vista = "NACIONAL";
      break;

    case 'URBANO':
      flag_vista = "NACIONAL";
      break;
  }

  switch (flag_vista) {
    case 'INTERNACIONAL':
      // Se filtra la vista de materiales y solicitud de urbano
      $(".nacional").hide();
      $(".internacional").show();
      $("#slct_rndc_material_").val('');
      $("#solicita_urbano").attr('checked', false);
      break;

    case 'NACIONAL':
      // Se filtra la vista de materiales y solicitud de urbano
      $(".nacional").show();
      $(".internacional").hide();
      break;
  }

  if ($("#slct_tipo_operacion_").val()) {
    buscaClientes(flag_vista);
    formDatosInternacional(flag_vista);
  }

  // Se hace filtro para ajustar las plantilla de actividades a seleccionar 
  let solicita_urbano = 0;
  if ($("#solicita_urbano").is(':checked')) {
    solicita_urbano = 1;
  }
  selectPlantillas($("#slct_tipo_operacion_").val(), solicita_urbano);
});

var num = 1;
$("#slct_tipo_cargas_").change(function() {
  var id_tipo_carga = $("#slct_tipo_cargas_").val();

  $(".div_contenedor").hide();
  if (id_tipo_carga == 1) {
    $(".div_contenedor").show();
    $(".div_devolucion").hide();
    $('#btn_quita').attr('disabled', 'disabled');
    App.formElements();
  } else {
    // Se reinicia el contenido de los contenedores
    $("#devolucion_1").attr("checked", false);
    num = $('.contenedor_clon').length;
    if (num > 1) {
      for (var i = 2; i <= num; i++) {
        $('#form_contenedor_' + i).remove();
      }
    }
    $('#btn_agrega').removeAttr("disabled");
    $('#btn_quita').attr('disabled', 'disabled');
  }
});

// Programación del botón de agregar contenedor
$('#btn_agrega').click(function() {
  num = $('.contenedor_clon').length;
  var newNum = new Number(num + 1);

  // create the new element via clone(), and manipulate it's ID using newNum value
  var newElem = $('#form_contenedor_' + num).clone().attr('id', 'form_contenedor_' + newNum);

  newElem.children('#div_tipo_contenedor_' + num).attr('id', 'div_tipo_contenedor_' + newNum);
  newElem.children('#div_contenedor_' + num).attr('id', 'div_contenedor_' + newNum);
  newElem.children('#div_devolucion_' + num).attr('id', 'div_devolucion_' + newNum);
  newElem.children('#div_devolucion_' + num).attr('id', 'label_devolucion_' + newNum);
  newElem.children('#div_comodato_' + num).attr('id', 'div_comodato_' + newNum);
  newElem.children('#div_fecha_comodato_' + num).attr('id', 'div_fecha_comodato_' + newNum);
  newElem.children('#div_devolucion_contenedor_' + num).attr('id', 'div_devolucion_contenedor_' + newNum);

  // manipulate the name/id values of the input inside the new element
  newElem.find('#div_contenedor_' + newNum + ' #contenedor_' + num).attr('id', 'contenedor_' + newNum).attr('name',
    'contenedor_' + newNum);
  newElem.find('#div_tipo_contenedor_' + newNum + ' #slct_tipo_contenedor_' + num).attr('id',
    'slct_tipo_contenedor_' + newNum).attr('name', 'tipo_contenedor_' + newNum);
  newElem.find('#div_devolucion_' + newNum + ' #devolucion_' + num).attr('id', 'devolucion_' + newNum).attr('name',
    'devolucion_' + newNum).attr("checked", false).parents(".contenedor_clon").find(".div_devolucion").hide();
  newElem.find('#div_devolucion_' + newNum + ' #label_devolucion_' + num).attr('id', 'label_devolucion_' + newNum)
    .attr('for', 'devolucion_' + newNum);
  newElem.find('#div_devolucion_contenedor_' + newNum + ' #devolucion_contenedor_' + num).attr('id',
    'devolucion_contenedor_' + newNum).attr('name', 'devolucion_contenedor_' + newNum);
  newElem.find('#div_fecha_comodato_' + newNum + ' #fecha_comodato_' + num).attr('id', 'fecha_comodato_' + newNum)
    .attr('name', 'fecha_comodato_' + newNum);
  newElem.find('#div_comodato_' + newNum + ' #url_comodato_' + num).attr('id', 'url_comodato_' + newNum).attr(
    'name', 'url_comodato_' + newNum);
  newElem.find('#div_comodato_' + newNum + ' #lbl_comodato_' + num).attr('id', 'lbl_comodato_' + newNum).attr('for',
    'url_comodato_' + newNum);

  // insert the new element after the last "duplicatable" input field
  $('#form_contenedor_' + num).after(newElem);

  // // enable the "remove" button
  $('#btn_quita').removeAttr("disabled");

  // business rule: you can only add 5 names
  if (newNum == 2)
    $('#btn_agrega').attr('disabled', 'disabled');
  App.formElements();
});

// Programación del botón de quitar contenedor
$('#btn_quita').click(function() {
  num = $('.contenedor_clon').length;

  $('#form_contenedor_' + num).remove();

  // enable the "add" button
  $('#btn_agrega').removeAttr("disabled");

  // if only one element remains, disable the "remove" button
  if (num - 1 == 1) {
    $('#btn_quita').attr('disabled', 'disabled');
  }
});

$("#solicita_urbano").change(function() {
  let solicita_urbano = 0;
  if ($("#solicita_urbano").is(':checked')) {
    solicita_urbano = 1;
  }
  selectPlantillas($("#slct_tipo_operacion_").val(), solicita_urbano);
});

function buscaClientes(tipo_proyecto) {
  let params = {
    tipo_proyecto: tipo_proyecto
  };
  // console.log(params);

  var url = $("#id_url_ajax").val() + "libs/buscar.php";
  $.ajax({
    type: "POST",
    url: url,
    data: params,
    dataType: "html",
    beforeSend: function() {
      $(".nexos-messages").html(
        '<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' +
        $("#id_url_ajax").val() +
        'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>'
      );
    },
    error: function() {
      console.log("Error");
    },
    success: function(data) {
      // console.log(data);
      // Se pinta el contenido en el formulario 
      $("#div_clientes").html(data);

      $("#slct_id_cliente").change(function() {
        let params = {
          id_cliente: $("#slct_id_cliente").val()
        };
        // console.log(params);

        switch (tipo_proyecto) {
          case 'NACIONAL':
            $("#div_slct_contrato").empty();

            var url = $("#id_url_ajax").val() + "libs/buscar_proyectos.php?action=crea_html_select_contrato";
            $.ajax({
              type: "POST",
              url: url,
              data: params,
              dataType: "json",
              beforeSend: function() {
                $(".nexos-messages").html(
                  '<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' +
                  $("#id_url_ajax").val() +
                  'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>'
                );
              },
              error: function(jqXHR, textStatus, errorThrown) {
                console.log(jqXHR);
                console.log(textStatus);
                console.log(errorThrown);
              },
              success: function(data) {
                var html_content = "<label>(*) Contrato:</label>";
                html_content += data.content;
                $(".nexos-messages").html("");
                $("#div_slct_contrato").empty();
                $("#div_slct_contrato").append(html_content);
                $("#div_contrato").fadeOut("fast");
              }
            });
            break;

          case 'INTERNACIONAL':
            // console.log("Entro en - " + tipo_proyecto);
            $("#div_btn_tramos").empty();
            $("#form_tramo_1").empty();

            var url = $("#id_url_ajax").val() + "libs/buscar_proyectos.php?action=crea_html_content_tramos";
            $.ajax({
              type: "POST",
              url: url,
              data: params,
              dataType: "json",
              beforeSend: function() {
                $(".nexos-messages").html(
                  '<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' +
                  $("#id_url_ajax").val() +
                  'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>'
                );
              },
              error: function(jqXHR, textStatus, errorThrown) {
                console.log(jqXHR);
                console.log(textStatus);
                console.log(errorThrown);
              },
              success: function(data) {
                // console.log(data);
                $(".nexos-messages").html("");
                $("#div_btn_tramos").empty();
                $("#div_tramos").empty();
                $("#div_btn_tramos").append(data.result["botones"]);
                $("#form_tramo_1").append(data.result["form_tramos"]);

                // Programación del botón de agregar tramo de la solicitud
                $('#btn_agrega_tramo').click(function() {
                  num = $('.tramo_clon').length;
                  var newNum = new Number(num + 1);

                  // create the new element via clone(), and manipulate it's ID using newNum value
                  var newElem = $('#form_tramo_' + num).clone().attr('id', 'form_tramo_' + newNum);

                  newElem.children('#div_tipo_tramo_' + num).attr('id', 'div_tipo_tramo_' + newNum);
                  newElem.children('#div_tramo_' + num).attr('id', 'div_tramo_' + newNum);

                  // manipulate the name/id values of the input inside the new element
                  newElem.find('#div_tipo_tramo_' + newNum + ' #slct_tipo_tramo_' + num).attr('id',
                    'slct_tipo_tramo_' + newNum).attr('name', 'tipo_tramo_' + newNum);
                  newElem.find('#div_tramo_' + newNum + ' #slct_remitente_destinatario_' + num)
                    .attr('id', 'slct_remitente_destinatario_' + newNum).attr('name', 'rem_dest_' +
                      newNum);

                  // insert the new element after the last "duplicatable" input field
                  $('#form_tramo_' + num).after(newElem);

                  // // enable the "remove" button
                  $('#btn_quita_tramo').removeAttr("disabled");

                  // business rule: you can only add 5 names
                  if (newNum == 20)
                    $('#btn_agrega_tramo').attr('disabled', 'disabled');
                });

                // Programación del botón de quitar tramo
                $('#btn_quita_tramo').click(function() {
                  num = $('.tramo_clon').length;

                  $('#form_tramo_' + num).remove();

                  // enable the "add" button
                  $('#btn_agrega_tramo').removeAttr("disabled");

                  // if only one element remains, disable the "remove" button
                  if (num - 1 == 1) {
                    $('#btn_quita_tramo').attr('disabled', 'disabled');
                  }
                });
              }
            });
            break;

          default:
            console.log("Error en la selección de tipo de proyecto");
            break;
        }
      });
    }
  });
}

function formDatosInternacional(tipo_proyecto) {
  $("#div_form_intencional").empty();
  if (tipo_proyecto == "INTERNACIONAL") {
    let params = {
      div_form_intencional: tipo_proyecto
    };
    // console.log(params);

    var url = $("#id_url_ajax").val() + "libs/buscar.php";
    $.ajax({
      type: "POST",
      url: url,
      data: params,
      dataType: "html",
      beforeSend: function() {
        $(".nexos-messages").html(
          '<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' +
          $("#id_url_ajax").val() +
          'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>'
        );
      },
      error: function() {
        console.log("Error");
      },
      success: function(data) {
        // console.log(data);
        // Se pinta el contenido en el formulario 
        $("#div_form_intencional").html(data);
      }
    });
  }
}

function selectPlantillas(tipo_operacion, solicita_urbano) {
  // console.log("Entro en funcion de plantillas");
  // console.log("tipo_operacion " + tipo_operacion);
  // console.log("solicita_urbano " + solicita_urbano);
  var id_cliente = "<?php echo $ssn_id_cliente; ?>";

  let params = {
    tipo_operacion: tipo_operacion,
    solicita_urbano: solicita_urbano,
    id_cliente: id_cliente
  };
  // console.log(params);

  $("#plantillas_actividades").empty();
  $("#datos_platilla_").empty();

  var url = $("#id_url_ajax").val() + "libs/buscar.php?genera_select=";
  $.ajax({
    type: "POST",
    url: url,
    data: params,
    dataType: "html",
    beforeSend: function() {
      $(".nexos-messages").html(
        '<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' +
        $("#id_url_ajax").val() +
        'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>'
      );
    },
    error: function() {
      console.log("Error");
    },
    success: function(data) {
      // console.log(data);
      $(".nexos-messages").html("");
      $("#plantillas_actividades").empty();
      $("#plantillas_actividades").css("display", "block");
      $("#plantillas_actividades").append(data);

      // Se adiciona la función que lista las actividades de la plantilla seleccionada 
      $("#slct_plantilla_").change(function() {
        // console.log("Entro en funcion slct_plantilla_");
        var id_plantilla = $("#slct_plantilla_").val();
        if (id_plantilla != "") {
          // console.log("selcciono plantilla " + id_plantilla);
          let params_1 = {
            valorBusqueda: id_plantilla,
            solicita_urbano: solicita_urbano
          }
          $.ajax({
            type: "POST",
            url: "<?php echo $urlBuscaPlantilla; ?>",
            data: params_1,
            dataType: "html",
            beforeSend: function() {
              $(".nexos-messages").html(
                '<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' +
                $("#id_url_ajax").val() +
                'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>'
              );
            },
            error: function() {
              console.log("Pailas no sirve");
            },
            success: function(data) {
              $(".nexos-messages").html("");
              $("#datos_platilla_").empty();
              $("#datos_platilla_").append(data);
            }
          });

          var url = $("#id_url_ajax").val() + "libs/buscar.php?orden_compra=";
          let params_2 = {
            valorBusqueda: id_plantilla,
            solicita_urbano: solicita_urbano
          }
          $.ajax({
            type: "POST",
            url: url,
            data: params_2,
            dataType: "html",
            beforeSend: function() {
              $(".nexos-messages").html(
                '<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' +
                $("#id_url_ajax").val() +
                'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>'
              );
            },
            error: function() {
              console.log("Error");
            },
            success: function(data) {
              // console.log(data);
              $(".nexos-messages").html("");
              $("#resultado").empty();
              $("#resultado").append(data);
            }
          });
        } else {
          console.log("No selecciono plantilla");
          // $("#resultado").html("");
        }
      });
    }
  });
}

function muestraDevolucion(element) {
  $("#" + element).parents(".contenedor_clon").find(".div_devolucion").fadeToggle("fast");
}

$("#div_contrato").hide();
$(".condiciones").click(function() {
  $("#" + $(this).attr("id") + "_content").slideToggle("fast");
});
$("#inicio_contrato").change(function() {
  var fecha = new Date($(this).val());
  var day = fecha.getDate() + 1;
  var month = fecha.getMonth() + 1;
  var year = fecha.getFullYear() + 1;

  if (day.toString().length == 1) {
    day = "0" + day;
  }

  if (month.toString().length == 1) {
    month = "0" + month;
  }

  var fecha_fin = year + "-" + month + "-" + day;
  $("#fin_contrato").val(fecha_fin)
});

function muestraFormContrato() {
  $("#div_contrato").fadeOut("fast");
  if ($("#slct_contrato_").val() == "otro") {
    $("#div_contrato").fadeIn("fast");
  }

  $(".condiciones").each(function() {
    $("#" + $(this).attr("id") + "_content").hide();
    $(this).prop("checked", false);
  });
  App.formElements();
}

// Funciones de eliminación de proyecto
function eliminar_proyecto(element) {
  $(".msg_error_danger").empty();
  var id = $(element).data("id");
  // console.log("🚀 ~ eliminar_proyecto ~ id:", id)
  var formulario = $("#eliminar");
  formulario.find("#id").val("");
  formulario.find("#id").val(id);

  formulario.find("#btn_eliminar").click(function() {
    var msg_error = '';
    let params = {
      tabla: "cmx_importacion_proyecto",
      id: formulario.find("#id").val(),
      estado: formulario.find("#estado").val()
    };
    // console.log("🚀 ~ formulario.find ~ params:", params)
    $.ajaxSetup({
      async: false
    });
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/editar_ajax.php",
      type: 'POST',
      data: params,
      cache: false,
      dataType: 'json',
      beforeSend: function(jqXHR, settings) {
        funct_msg_loading(".nexos-messages");
      },
      error: function(jqXHR, textStatus, errorThrown) {
        $(".nexos-messages").html('');
        msg_error += "<p>" + jqXHR.responseText + "</p>";
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      },
      success: function(data, textStatus, jqXHR) {
        // console.log(data);
        if (data.error) {
          msg_error += data.error;
        }
      }
    });
    $(".nexos-messages").empty();
    if (!msg_error) {
      funct_msg_success(".msg_error_danger");
      $("#eliminar").animate({
        scrollTop: 0
      }, 600);
      setTimeout(function() {
        location.reload(false);
      }, 800);
    }
    if (msg_error) {
      funct_msg_error(".msg_error_danger", msg_error);
      $("#eliminar").animate({
        scrollTop: 0
      }, 600);
    }
    $.ajaxSetup({
      async: true
    });
  });
}

// Funciones de habilitación de proyecto
function habilitar_proyecto(element) {
  $(".msg_error_success").empty();
  var id = $(element).data("id");
  var formulario = $("#habilitar");
  formulario.find("#id").val("");
  formulario.find("#id").val(id);

  formulario.find("#btn_habilitar").click(function() {
    var msg_error = '';
    let params = {
      tabla: "cmx_importacion_proyecto",
      id: formulario.find("#id").val(),
      estado: formulario.find("#estado").val()
    };

    $.ajaxSetup({
      async: false
    });
    $.ajax({
      url: $("#id_url_ajax").val() + "libs/editar_ajax.php",
      type: 'POST',
      data: params,
      cache: false,
      dataType: 'json',
      beforeSend: function(jqXHR, settings) {
        funct_msg_loading(".nexos-messages");
      },
      error: function(jqXHR, textStatus, errorThrown) {
        $(".nexos-messages").html('');
        msg_error += "<p>" + jqXHR.responseText + "</p>";
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
      },
      success: function(data, textStatus, jqXHR) {
        // console.log(data);
        if (data.error) {
          msg_error += data.error;
        }
      }
    });
    $(".nexos-messages").empty();
    if (!msg_error) {
      funct_msg_success(".msg_error_success");
      $("#eliminar").animate({
        scrollTop: 0
      }, 600);
      setTimeout(function() {
        location.reload(false);
      }, 800);
    }
    if (msg_error) {
      funct_msg_error(".msg_error_success", msg_error);
      $("#eliminar").animate({
        scrollTop: 0
      }, 600);
    }
    $.ajaxSetup({
      async: true
    });
  });
}
</script>