<?php
	$_jsScripts = "";
	$vista = '';

	$r = new Request();
	// print_r("<pre>");
	// print_r($r->getArgs());
	// print_r("</pre>");
	$id_actividad = $r->getArgs()[0];
	$numero_importacion = $r->getArgs()[1];

	// print_r("<pre>");
	// print_r($_SESSION);
	// print_r("</pre>");

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];

	// Busco los Seguimeintos de la actividad 
	$array_seguimientos = $this->informes->getSeguimientoCargueActividad( $id_actividad );
	// print_r("<pre>");
	// print_r($array_seguimientos);
	// print_r("</pre>");

	if ($array_seguimientos) {
		$info_contenido_1 = '';

		$_btn_return = '<a href="' . BASE_URL . '" class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>';
		if ( isset($r->getArgs()[2]) ) {
			$_btn_return = '<a href="' . BASE_URL . 'seguridad/seguimiento_cargue/" class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>';
		}

		$lista_seguimientos_ruta = '';
		if ($array_seguimientos) {
			$_table_content = "";
			foreach ($array_seguimientos["rowsData"] as $key_seguimientos => $value_seguimientos) {

				// Se filtra el contenido del campo observación interna
				$_observacion_interna = "";
				if ( $ssn_id_cliente == 1 ) {
					$_observacion_interna = '
						<span class="cell-detail-description" style="color: #ea4335;">' . $value_seguimientos["observacion_interna"] . '</span>
					';
				}

				$_table_content.= '
					<tr>
						<td class="user-avatar cell-detail user-info">
							<img src="' . BASE_URL . 'public/img/users/' . $value_seguimientos["url_avatar"] . '">
							<span>' . $value_seguimientos["nom_usuario"] . '</span>
							<span class="cell-detail-description">' . $value_seguimientos["fecha_hora"] . '</span>
						</td>
						<td class="cell-detail">
							' . $value_seguimientos["tipo_seguimiento"] . '
							<span class="cell-detail-description">' . $value_seguimientos["observacion"] . '</span>
							' . $_observacion_interna . '
						</td>
					</tr>
				';
			}

			$info_contenido_1 = '
				<div class="panel panel-border panel-contrast">
					<div class="panel-heading panel-heading-contrast">
						Información Seguimiento de Cargue - ' . $numero_importacion . '
						<div class="tools">
							' . $_btn_return . '
						</div>
					</div>
					<div class="panel-body"> 
						<div class="col-sm-2"></div>
						<div class="col-sm-8">
							<h3>Seguimientos</h3>
							<table id="table1" class="table table-striped table-hover">
								<thead>
									<tr class="nexos-encabezado">
										<th style="width: 25%">Realizado</th>
										<th>Observación</th>
									</tr>
								</thead>
								<tbody>
									' . $_table_content . '
								</tbody>
							</table>
						</div>
						<div class="col-sm-2"></div>
					</div>
				</div>
			';
		}

		$vista.= $info_contenido_1;
	}

 	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>

		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>


	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
		</script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;
?>
