<?php
	$_jsScripts = "";
	$vista = '
	    <link rel="stylesheet" type="text/css" href="%root_file%lib/jquery.magnific-popup/magnific-popup.css"/>
	';

	$r = new Request();
	// print_r("<pre>");
	// print_r($r->getArgs());
	// print_r("</pre>");
	$id_actividad = $r->getArgs()[0];

	// print_r("<pre>");
	// print_r($_SESSION);
	// print_r("</pre>");

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];

	// Busco los Seguimeintos de la actividad 
	$array_verificacion_material = $this->informes->getDetalleVerificacionMaterial( $id_actividad, $ssn_id_cliente );
	// print_r("<pre>");
	// print_r($array_verificacion_material);
	// print_r("</pre>");

	if ($array_verificacion_material["seguimiento"]) {
		// Se busca la información general de la Carga
		$header_content = '
			<span><strong>Información del Proyecto</strong></span>
			<table class="table">
				<tbody>
					<tr>
						<td class="cell-detail">
							<div class="row">
								<div class="col-sm-2">
									<span># Proyecto:</span>
									<span class="cell-detail-description">' . $array_verificacion_material["seguimiento"]["rowsData"][0]["numero_importacion"] . '</span>
									<span class="cell-detail-description">' . date('Y-m-d', $array_verificacion_material["seguimiento"]["rowsData"][0]["numero_importacion"]) . '</span>
								</div>
								<div class="col-sm-3">
									<span>Cliente:</span>
									<span class="cell-detail-description">' . $array_verificacion_material["seguimiento"]["rowsData"][0]["CLIENTE"] . '</span>
								</div>
								<div class="col-sm-2">
									<span># Materiales:</span>
									<span class="cell-detail-description">' . $array_verificacion_material["seguimiento"]["rowsData"][0]["CANTIDAD_MATERIALES"] . '</span>
									<span class="cell-detail-description">' . number_format($array_verificacion_material["seguimiento"]["rowsData"][0]["PESO"], 2, ",", ".") . 'Kg.</span>
								</div>
								<div class="col-sm-2">
									<span>Tipo de Operación:</span>
									<span class="cell-detail-description">' . $array_verificacion_material["seguimiento"]["rowsData"][0]["tipo_operacion"] . '</span>
									<span class="cell-detail-description">' . $array_verificacion_material["seguimiento"]["rowsData"][0]["importacion"] . '</span>
								</div>
								<div class="col-sm-3">
									<span>Origen:</span>
									<span class="cell-detail-description">' . $array_verificacion_material["seguimiento"]["rowsData"][0]["NOMBRE_ORIGEN"] . '</span>
									<span class="cell-detail-description">' . $array_verificacion_material["seguimiento"]["rowsData"][0]["CIUDAD_ORIGEN"] . '</span>
								</div>
							</div>
						</td>
					</tr>
					<tr><td></td></tr>
				</tbody>
			</table>
		';

		// Se buscan los materiales del proyecto 
		if ( $array_verificacion_material["seguimiento_material"] ) {
			$_table_material = '';
			foreach ($array_verificacion_material["seguimiento_material"][ $array_verificacion_material["seguimiento"]["rowsData"][0][0] ]["rowsData"] as $key => $value) {
				$_table_material.= '
					<tr>
						<td class="cell-detail">
							<span>' . $value["nombre"] . '</span>
							<span class="cell-detail-description">Código - ' . $value["codigo"] . '</span>
						</td>
						<td class="cell-detail">
							<span>UN - ' . $value["codigoUN"] . '</span>
							<span class="cell-detail-description">Rombos - ' . $value["rombos"] . '</span>
						</td>
						<td class="cell-detail">
							<span>' . $value["cantidad"] . '</span>
						</td>
						<td class="cell-detail">
							<span>' . number_format($value["peso_bruto"], 2, ",", ".") . 'Kg.</span>
						</td>
						<td class="cell-detail">
							<span>' . number_format($value["peso_neto"], 2, ",", ".") . 'Kg.</span>
						</td>
						<td class="cell-detail">
							<span>' . $value["OBSERVACIONES"] . '</span>
						</td>
					</tr>
				';
			}

			$_table_material_content = '';
			if ($_table_material) {
				$_table_material_content.= '
					<span><strong>Material de la Carga</strong></span>
					<table id="table" class="table table-striped" data-page-length="25">
						<thead>
							<tr>
								<th>Material</th>
								<th style="width: 10%;">Códigos</th>
								<th style="width: 5%;">Cantidad</th>
								<th style="width: 10%;">Peso Bruto</th>
								<th style="width: 10%;">Peso Neto</th>
								<th>Observación</th>
							</tr>
						</thead>
						<tbody>
							' . $_table_material .'
						<td></td><td></td><td></td><td></td><td></td><td></td>

						</tbody>
					</table>
				';
			}
		}


		// Se buscan la imágenes del seguimiento de carga 
		if ($array_verificacion_material["seguimiento_imagenes"]) {
			if ( $array_verificacion_material["seguimiento_imagenes"][ $array_verificacion_material["seguimiento"]["rowsData"][0][0] ]["rowsData"] ) {
				$_image_content = '
					<span><strong>Imágenes</strong></span>
					<div class="gallery-container">
				';
				foreach ($array_verificacion_material["seguimiento_imagenes"][ $array_verificacion_material["seguimiento"]["rowsData"][0][0] ]["rowsData"] as $key => $value) {
					$_image_content.= '
						<div class="item">
							<div class="photo">
								<div class="img">
									<img src="' . BASE_URL . 'public/files/importaciones/verificacion/' . $array_verificacion_material["seguimiento"]["rowsData"][0][0] . '/' . $value["url"] . '" alt="' . $array_verificacion_material["seguimiento"]["rowsData"][0]["numero_importacion"] . '">
									<div class="over">
										<div class="info-wrapper">
											<div class="info">
												<div class="title"></div>
												<div class="date"></div>
												<div class="description"></div>
												<div class="func">
													<center>
													<a href="' . BASE_URL . 'public/files/importaciones/verificacion/' . $array_verificacion_material["seguimiento"]["rowsData"][0][0] . '/' . $value["url"] . '" class="image-zoom"><i class="icon mdi mdi-search"></i></a>
													</center>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					';

				}
				$_image_content.= '
					</div>
				';
			}
		}

		$info_contenido_1 = '';
		if ($array_verificacion_material) {
			$info_contenido_1.= '
				<div class="panel panel-border panel-contrast">
					<div class="panel-heading panel-heading-contrast">
						Información Seguimiento de Cargue del Proyecto - ' . $array_verificacion_material["seguimiento"]["rowsData"][0]["numero_importacion"] . '
						<div class="tools">
							<a href="' . BASE_URL . '" class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>
						</div>
					</div>
					<div class="panel-body"> 
						<div class="col-xs-12">
							' . $header_content . '
						</div>
						<div class="col-xs-12">
							' . $_table_material_content . '
						</div>
						<div class="col-xs-12">
							' . $_image_content . '
						</div>
					</div>
				</div>
			';
		}
		$vista.= $info_contenido_1;
	}

 	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


		<script src="%root_file%lib/jquery.magnific-popup/jquery.magnific-popup.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/masonry/masonry.pkgd.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-page-gallery.js" type="text/javascript"></script>

	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});

			$(window).on("load",function(){
				App.pageGallery();
			});
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;
?>
