<input type="hidden" name="perfil_id" id="perfil_id" value="<?= $_SESSION["usuario"]["id_perfil"] ?>">
<input type="hidden" name="proveedor_id" id="proveedor_id" value="<?= $_SESSION['usuario']['proveedor_id'] ?>">
<input type="hidden" name="cliente_id" id="cliente_id" value="<?= $_SESSION['usuario']['id_cliente'] ?>">
<input type="hidden" name="ventana_id" class="ventana_id" value="<?= $_SESSION['usuario']['ventanas'] ?>">
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
            <div class="table-responsive scrollbar">
                <table id='table_global' class='table table-striped table-hover table-fw-widget table-sm w-100' data-page-length='100' style="font-size:12px;">
                    <thead>
                        <tr>
                            <th class='text-center' style='width: auto; white-space: nowrap;'>#</th>
                            <th class='text-center' style='width: auto; white-space: nowrap;'>C.C ó Nit</th>
                            <th class='text-center' style='width: auto; white-space: nowrap;'>Facturar a</th>
                            <th class='text-center' style='width: auto; white-space: nowrap;'>Instrucciones</th>
                            <th class='text-center' style='width: auto; white-space: nowrap;'>Total Instrucciones</th>
                        </tr>
                    </thead>
                    <tbody id="tbody_historico_instrcciones_facturacion">
                        <tr class="text-center img_load" id="img_load" style="display: none;">
                            <td colspan="8"><img src="<?= BASE_URL ?>public/img/nexos_loading.gif" height="25" width="25"> Esperando Información</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="verticallyCentered" tabindex="-1" data-bs-backdrop="static" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header justify-content-between bg-danger p-1">
                <h6 class="modal-title text-white dark__text-gray-1100" id="staticBackdropLabel">Solicitar Anulación de Instrucci&oacute;n y Factura</h6>
                <button class="btn p-1" type="button" data-bs-dismiss="modal" aria-label="Close"><span class="fas fa-times fs-9 text-white dark__text-gray-1100"></span></button>
            </div>
            <div class="modal-body">
                <!-- <p class="text-body-tertiary lh-lg mb-0">This is a static modal example (meaning its position and display have been overridden). Included are the modal header, modal body (required for padding), and modal footer (optional). </p> -->
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                        <div class="mb-1">
                            <label style="font-size: 12px;">Instrucci&oacute;n</label>
                            <input type="text" id="instruccion" class="form-control form-control-sm w-100" disabled>
                            <input type="hidden" id="instruccion_Id" class="form-control form-control-sm w-100" disabled>
                        </div>
                    </div>

                    <div class="col-6 col-sm-6 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
                        <div class="mb-1">
                            <label style="font-size: 12px;">
                                Motivo Anulación&nbsp;<span style="color:red;"><i>(*)</i></span>
                            </label>
                            <select id="motivo_anulacion" class="form-select form-select-sm w-100">
                                <option value="">Seleccione</option>
                                <option value="Solicitado SAC">Solicitado SAC</option>
                                <option value="Cliente Rechaza">Cliente Rechaza</option>
                                <option value="Error Digitacion">Error Digitación</option>
                                <option value="Error XML enviado a la DIAN">Error XML enviado a la DIAN</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-6 col-sm-6 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
                        <div class="mb-1">
                            <label style="font-size: 12px;">Evidencia</label>
                            <input type="file" id="evidencia" class="form-control form-control-sm w-100">
                        </div>
                    </div>

                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                        <div class="mb-1">
                            <label style="font-size: 12px;">Observaciones (Opcional)</label>
                            <textarea type="text" id="observacion" min="0" class="form-control input-sm" rows="2" oninput="this.value = this.value.toUpperCase();"></textarea>
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer p-1">
                <button class="btn btn-danger btn-sm" type="button" id="btn_anular_instruccion"><i class="fas fa-ban"></i> Solicitar Anulaci&oacute;n</button>
                <button class="btn btn-outline-danger btn-sm" type="button" data-bs-dismiss="modal" id="btn_cancelar_anulacion">Cancelar</button>
            </div>
        </div>
    </div>
</div>