<?php

	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

	$vista = '';
	$table_content = "";


	if (isset($this->aprobar) ) {
		$arrayPermisos = $this->aprobar->permisosPerfil( $ssn_id_perfil , 80);
		$_permisos = $arrayPermisos["rowsData"][0];
		// Se consulta la informacion para llenar la tabla - prueba=nombre del modelo;  
		$array = $this->aprobar->getpruebas();
		// print_r("<pre>");
		// print_r($array);
		// print_r("</pre>");

		$vista.= '
	<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Consulta Datos de la Cotización
				<span class="panel-subtitle"></span>
			</div>
			<div class="panel-body">
			<div class="nexos-messages"></div>
			<div class="form-group col-xs-12 col-sm-12 col-md-12">
			<div class="row">
				<div class="col-xs-6 col-sm-6 col-md-6 ">
					<label>Estado de la Cotización:</label>
						<select id="e_estado" class="form-control input-sm">
							<option value="F1">F1-realizada</option>
							<option value="F2">F2-Entregada</option>
							<option value="F4">F4-Perdida</option>
							<option value="F3">F3-ganada</option>
							<option value="F5">F5-Cancelada</option>
						</select>
				  </div>
					<div class="col-xs-12 col-sm-6 col-md-6">
						<button  class="btn btn-space btn-primary btn_conductor">Consultar</button>
					</div>
				</div>	
				</div>
			 	';

			 	$vista.='
			 	<div class="form-group col-xs-12 col-sm-12 col-md-12">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 ">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="datos_conductor">
					<div class="row" >
						<div class="col-lg-12 col-md-12">
							<div  class="table-responsive noSwipe">
								<table id="table1" class="table table-striped table-hover" data-page-length="100">
									<thead>
										<tr class="nexos-encabezado">
											<th>
												<h5>
												<strong>Total</strong><span class="badge badge-secondary" id="bdge" ></span>
												</h5>
											</th>
											<th>N° Cotización</th>
											<th>Cliente</th>
											<th>Tipo Servicio</th>
											<th>Origen</th>
											<th>Destino</th>
											<th>estado</th>
											<th>Autorizado por</th>
										</tr>
									</thead>
									<tbody id="cuerpo">';
								$vista.='</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
				</div>
				</div>
				</div>';
	}


//librerías
	$vista.= '
			<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
			<script src="%root_file%js/main.js" type="text/javascript"></script>
			<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
			<script>
				$(document).ready(function(){
					//initialize the javascript
					App.init();
				});
				</script>
	';
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	echo $vista;

?>
<script type="text/javascript">
$(document).ready(function(){
$(".btn_conductor").click(function(){
	var estado=$("#e_estado").val();
	// alert(estado);
 		var datos={
 			estado_cotice:estado,
 			action:'consulte_estado_cotizacion'
 	};

 	$("#cuerpo").html('');
 	
 	$.ajax({
 			url:"http://principal.nexosapp.com/libs/servicio_cliente_ajax.php",
 			type:'POST',
 			data:datos,
 			dataType:'json',
 			success: function(data){
 				var cuente=0;
 					data.result.forEach(function(element,index){
 					console.log(element);
 					// alert(estado);
 					if(estado == element.estado){
 						//traer bolita de color
 						cuente++;

 						var col_status='';
 						if(element.estado=='F1'){
 							// console.log('numero'+cuente);
 							document.getElementById('bdge').innerHTML =cuente;
 							var col_status ='<td class="text-default">'+
 							'<center>'+
							'<span class="mdi mdi-dot-circle icon"  data-toggle="tooltip" title="Realizada" ></span>'+
							'</center>'+
							'</td>';
 						}

 						if(element.estado=='F2'){
 							document.getElementById('bdge').innerHTML =cuente;
 							var col_status ='<td class="text-success">'+
									'<center>'+
									'<span class="mdi mdi-dot-circle icon"  data-toggle="tooltip" title="Entregada"></span>'+
									'</center>'+
								'</td>';
 						}

 						if(element.estado=='F4'){
 							document.getElementById('bdge').innerHTML =cuente;
 							var col_status ='<td class="text-danger">'+
									'<center>'+
									'<span class="mdi mdi-dot-circle icon" data-toggle="tooltip" title="Pérdida"  ></span>'+
									'</center>'+
								'</td>';
 						}


 						if(element.estado=='F3'){
 							document.getElementById('bdge').innerHTML =cuente;
 							var col_status ='<td class="text-warning">'+
								'<center>'+
								'<span class="mdi mdi-dot-circle icon"  data-toggle="tooltip" title="Ganada"></span>'+
									'</center>'+
								'</td>';
 						}


 						if(element.estado=='F3'){
 							document.getElementById('bdge').innerHTML =cuente;
 							var col_status ='<td class="text-warning">'+
								'<center>'+
								'<span class="mdi mdi-dot-circle icon"  data-toggle="tooltip" title="Ganada"></span>'+
									'</center>'+
								'</td>';
 						}


 						if(element.estado=='F5'){
 							document.getElementById('bdge').innerHTML =cuente;
 							var col_status ='<td class="text-primary">'+
									'<center>'+
									'<span class="mdi mdi-dot-circle icon" data-toggle="tooltip" title="Cancelada" ></span>'+
									'</center>'
								'</td>';
 						}

 						//traer el último dato
 						if(element.estado=='F3'){
 							$dato='<td>'+element.autorizado_por+'</td>';
 						}else{
 							$dato='<td>'+element.estado_autorizado+'</td>';
 						}



						$("#cuerpo").append('<tr>'+col_status+
						'<td>'+element.n_cotizacion+'</td>'+
 						'<td>'+element.nombre_cliente+'</td>'+
 						'<td>'+element.tipo_servicio_mer+'</td>'+
 						'<td>'+element.origen+'</td>'+
 						'<td>'+element.destino+'</td>'+
 						'<td>'+element.estado+'</td>'+
 						$dato
 						+'</tr>');
 					}
 					
 					});

 			},
 			error:function(data){

 			}
 	});
});		


});
</script>