<div class="container-fluid pt-3">
  <style>
    #agregar_fila {
      position: fixed;
      bottom: 25px;
      right: 25px;
      z-index: 9999;
      border-radius: 50px;
      padding: 12px 22px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.30);
    }

    .input-error {
      border: 1px solid red !important;
      background-color: #fff6f6 !important;
    }
  </style>
  <!-- <div class="d-flex justify-content-center"> -->
  <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-12 col-xxl-12">
    <!-- <div class="row"> </div> -->
    <!-- <div id="bloque_formulario" class="scrollbar vh-100"> -->
    <div id="bloque_formulario">
      <!-- Seleccionar el escenario para la solicitud de servicio -->
      <!-- <div class="d-flex flex-wrap justify-content-start mt-2">
        <div class="col-12 col-sm-12 col-md-8 col-lg-8 col-xl-8 col-xxl-8">
          <h6 class="mb-0 text-body-highlight me-2">Escenarios solicitud de servicio</h6>
        </div>
      </div>
      <hr class="my-1 text-dark">

      <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
        <div class="mb-1">
          <label style="font-size: 12px;">Escenarios&nbsp;<span style="color:red;"><i>(*)</i></label>
          <select id="escenarios" class="form-select form-select-sm mb-3">
            <option value="">Seleccione</option>
          </select>
        </div>
      </div> -->

      <hr class="my-1 text-dark">
      <div class="d-flex flex-wrap justify-content-start mt-2">
        <div class="col-12 col-sm-12 col-md-8 col-lg-8 col-xl-8 col-xxl-8">
          <h6 class="mb-0 text-body-highlight me-2">Datos del cliente</h6>
        </div>
        <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4 d-flex justify-content-end">
          <a class="fw-bold fs-9 text-decoration-none" href="#!" data-bs-toggle="modal" data-bs-target="#staticBackdrop"><i class="fas fas fa-users"></i> Seleccionr cliente</a>
        </div>
      </div>
      <hr class="my-1 text-dark">

      <div class="col-12 col-sm-12 col-md-12 col-lg-21 col-xl-12 col-xxl-12">
        <div class="row">
          <input type="hidden" name="id_cliente_seleccionado" id="id_cliente_seleccionado">
          <input type="hidden" name="empresa_seleccionada_id" id="empresa_seleccionada_id">
          <div class="col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 col-xxl-2">
            <div class="mb-1">
              <label style="font-size: 12px;">Documento</label>
              <input type="text" class="typeahead form-control form-control-sm" id="documento" disabled>
              <input type="hidden" class="typeahead form-control form-control-sm" id="nit_empresa" disabled>
              <input type="hidden" id="digito_verificacion" disabled class="form-control input-sm">
            </div>
          </div>
          <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
            <div class="mb-1">
              <label style="font-size: 12px;">Nombre</label>
              <input type="text" id="nombre_clientes" disabled class="form-control form-control-sm">
            </div>
          </div>
          <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4">
            <div class="mb-1">
              <label style="font-size: 12px;">Ubicación</label>
              <input type="text" id="direccion_cliente" class="form-control form-control-sm" disabled>
            </div>
          </div>
          <div class="col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 col-xxl-2">
            <div class="mb-1">
              <label style="font-size: 12px;">Telefono</label>
              <input type="number" id="telefono_cliente" maxlength="10" minlength="0" class="form-control form-control-sm" disabled>
            </div>
          </div>
          <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
            <div class="mb-1">
              <label style="font-size: 12px;">Correo</label>
              <input type="text" id="correo" disabled class="form-control form-control-sm">
            </div>
          </div>
          <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4">
            <div class="mb-1">
              <label style="font-size: 12px;">Tipo Documento</label>
              <input type="text" id="tipo_documento" class="form-control form-control-sm" disabled>
            </div>
          </div>
        </div>

        <!-- <hr class="my-1 text-dark"> -->
        <div class="d-flex flex-wrap justify-content-start mt-2">
          <div class="col-12 col-sm-12 col-md-8 col-lg-8 col-xl-8 col-xxl-8">
            <h6 class="mb-0 text-body-highlight me-2">Datos de la mercancía</h6>
          </div>
          <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4 d-flex justify-content-end">
            <!-- <a class="fw-bold fs-9 text-decoration-none me-2" style="font-size: 10px;" href="#!" data-toggle="tooltip" data-placement="top" title="Agregar fila" id="agregar_fila"><span class="text-body uil-plus-square"></span></a> -->
            <a class="fw-bold fs-9 text-decoration-none" style="font-size: 10px;" href="#!" title="Fletes nacional" onclick="ir_modulofletes();"><i class="fas fa-arrow-right"></i></a>
          </div>
        </div>
        <hr class="my-1 text-dark">

        <!-- Formulario de cotizaciones -->
        <div id="table_mercancia"></div>

        <!-- Servicios especiales -->
        <!-- <div class="d-flex flex-wrap justify-content-start mt-3">
          <div class="col-12 col-sm-12 col-md-8 col-lg-8 col-xl-8 col-xxl-8">
            <h6 class="mb-0 text-body-highlight me-2">Servicios especiales</h6>
          </div>
          <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4 d-flex justify-content-end">
            <a class="fw-bold fs-9 text-decoration-none me-2" style="font-size: 10px;" href="#!" data-toggle="tooltip" data-placement="top" title="Agregar fila" id="agregar_especial"><span class="text-body uil-plus-square"></span></a>
            <a class="fw-bold fs-9 text-decoration-none" style="font-size: 10px;" href="#!" title="Tipo servicio" onclick="ir_modulotiposervi();"><i class="fas fa-arrow-right"></i></a>
          </div>
        </div> -->

        <hr class="mt-5 text-dark">
        <!-- Formulario de servicios especiales -->
        <!-- <div id="table_especial"></div> -->

        <!-- Solicitud de servicio -->
        <div class="row">
          <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4">
            <div class="mb-1">
              <label style="font-size: 12px;">Agencia&nbsp;<span style="color:red;"><i>(*)</i></label>
              <select id="agencia" class="form-select form-select-sm mb-3">
                <option value="">Seleccione</option>
              </select>
            </div>
          </div>

          <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4">
            <div class="mb-1">
              <label style="font-size: 12px;">Grupo&nbsp;<span style="color:red;"><i>(*)</i></label>
              <select class="form-select form-select-sm mb-3 select2" aria-label="category" id="group" name="group[]" multiple style="width:100%;"></select>
            </div>
          </div>

          <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4">
            <div class="mb-1">
              <label style="font-size: 12px;">Hora Envio email</label>
              <select class="form-select form-select-sm mb-3 select2" aria-label="category" id="houremail" name="houremail[]" multiple style="width:100%;"></select>
            </div>
          </div>

          <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
            <div class="mb-1">
              <label style="font-size: 12px;">Observaciones Seguridad</label>
              <textarea type="text" id="observacion" min="0" class="form-control input-sm" rows="1"></textarea>
            </div>
          </div>

          <!-- <div id="devolver_contenedor" style="display:none;">
            <div class="row">
              <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <span style="font-weight:500; margin-top:20px;"><strong>Datos de Contenedor</strong></span>
                <span class="cell-detail-description" style="font-size:10px;"> (El registro de contenedor se activa cuando
                  el tipo de carga es Contenedor Cargado o Contenedor Vacío).</span>
                <hr class="my-1 text-dark">
              </div>

              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="mb-3">
                  <label style="font-size: 12px;">Devuelve Contenedor</label>
                  <select id="cnt_opcion" class="form-select form-select-sm" disabled>
                    <option value="">Seleccione</option>
                    <option value="1">Si</option>
                    <option value="0">No</option>
                  </select>
                </div>
              </div>

              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="mb-3">
                  <label style="font-size: 12px;">Tipo Contenedor</label>
                  <select id="cnt_tipocon" class="form-select form-select-sm" disabled></select>
                </div>
              </div>

              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="mb-3">
                  <label style="font-size: 12px;">Núm. contenedor</label>
                  <input type="text" id="cnt_num" class="form-control form-control-sm" min="0" placeholder="# Contenedor" disabled>
                </div>
              </div>

              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="mb-3">
                  <label style="font-size: 12px;">Fecha de vencimiento</label>
                  <input type="date" id="cnt_dias" class="form-control form-control-sm" disabled>
                </div>
              </div>

              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="mb-3">
                  <label style="font-size: 12px;">Mun devolución</label>
                  <select id="cnt_municipio" class="form-select form-select-sm" disabled>
                    <option value="">Seleccione</option>
                  </select>
                </div>
              </div>

              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="mb-3">
                  <label style="font-size: 12px;">Dirección devolución</label>
                  <input type="text" id="cnt_direccion" class="form-control form-control-sm" disabled>
                </div>
              </div>

              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="mb-3">
                  <label style="font-size: 12px;">Fecha comodato</label>
                  <input type="date" id="cnt_fcomodato" class="form-control form-control-sm" disabled>
                </div>
              </div>

              <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="mb-3">
                  <label style="font-size: 12px;">Peso Vacío (Kg)</label>
                  <input type="numer" id="cnt_peso" class="form-control form-control-sm" placeholder="sin puntos" disabled>
                </div>
              </div>

              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <input type="hidden" class="form-control input-xs" id="tip_transport">
              </div>
            </div>
          </div> -->

          <!-- CAMPOR PARA LA VISUALISACION DE COSTOS DE LA SOLICITUD DE SERVICIO -->

          <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
            <div class="d-flex flex-wrap justify-content-start mt-3">
              <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <h6 class="mb-0 text-body-highlight me-2"> Costo Servicios Mercancía</h6>
              </div>
            </div>
            <hr class="my-1 text-dark">
          </div>

          <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 col-xxl-3">
            <div class="mb-1">
              <label style="font-size: 12px;">Valor total costo servicio</label>
              <input type="text" id="Tcosto_flete" disabled class="form-control form-control-sm">
            </div>
          </div>
          <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 col-xxl-3">
            <div class="mb-1">
              <label style="font-size: 12px;">Valor total tarifa venta</label>
              <input type="text" id="Tservicio_transporte" disabled class="form-control form-control-sm">
            </div>
          </div>
          <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 col-xxl-3">
            <div class="mb-1">
              <label style="font-size: 12px;">Valor total Rentabilidad %</label>
              <input type="text" id="Tutilidad" disabled class="form-control form-control-sm">
            </div>
          </div>
          <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 col-xxl-3">
            <div class="mb-1">
              <label style="font-size: 12px;">Valor total utilidad</label>
              <input type="text" id="Trentabilidad" disabled class="form-control form-control-sm">
            </div>
          </div>

          <!-- <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
            <div class="d-flex flex-wrap justify-content-start mt-3">
              <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <h6 class="mb-0 text-body-highlight me-2"> Costo Servicios Especiales</h6>
              </div>
            </div>
            <hr class="my-1 text-dark">
          </div> -->

          <!-- Valores del servicio especial -->
          <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 col-xxl-3">
            <div class="mb-1">
              <!-- <label style="font-size: 12px;">Valor total Costo</label> -->
              <input type="hidden" id="Tcosto_especial" disabled class="form-control form-control-sm">
            </div>
          </div>
          <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 col-xxl-3">
            <div class="mb-1">
              <!-- <label style="font-size: 12px;">Valor Total tarifa</label> -->
              <input type="hidden" id="Ttarifa_especial" disabled class="form-control form-control-sm">
            </div>
          </div>
          <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 col-xxl-3">
            <div class="mb-1">
              <!-- <label style="font-size: 12px;">Valor total Rentabilidad%</label> -->
              <input type="hidden" id="Tutilidad_especial" disabled class="form-control form-control-sm">
            </div>
          </div>
          <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 col-xxl-3">
            <div class="mb-1">
              <!-- <label style="font-size: 12px;">Valor total Utilidad</label> -->
              <input type="hidden" id="Trenta_especial" disabled class="form-control form-control-sm">
            </div>
          </div>

          <!-- Valores total del servidio -->
          <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
            <div class="d-flex flex-wrap justify-content-start mt-3">
              <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <h6 class="mb-0 text-body-highlight me-2"> Costo Total Servicio</h6>
              </div>
            </div>
            <hr class="my-1 text-dark">
          </div>

          <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
            <div class="mb-1">
              <label style="font-size: 12px;">Valor total Servicio</label>
              <input type="text" id="Ttotal_cotizacion" disabled class="form-control form-control-sm text-center" min="0" value="0" nclick="totalt();" readonly>
            </div>
          </div>
        </div>

        <div class="col-12 gy-6 mt-3">
          <div class="row g-3 justify-content-center">
            <div class="col-auto">
              <button class="btn btn-phoenix-primary btn-sm text-danger" type="button" id="btn-cancelar">
                <span class="text-danger" data-feather="x"></span> Cancelar
              </button>
            </div>
            <div class="col-auto">
              <button class="btn btn-primary btn-sm px-5" id="btn_agregar_cotizacion" type="button">
                <span data-feather="save"></span> Crear Solicitud
              </button>
            </div>
          </div>
        </div>
        </form>
      </div>
    </div>
  </div>
</div>

<button id="agregar_fila" class="btn btn-primary rounded-circle p-3" style="margin-bottom: 55px;">
  <i class="fas fa-plus"></i>
</button>


<!-- Modal para seleccionar clientes -->
<div class="modal fade" id="staticBackdrop" tabindex="-1" data-bs-backdrop="static"
  aria-labelledby="scrollingLongModalLabel2" aria-hidden="true">
  <!-- <div class="modal-dialog modalgdialog-scrollable modal-xl"> -->
  <div class="modal-dialog modal-dialog-scrollable modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-primary">
        <h5 class="modal-title text-white dark__text-gray-1100" id="staticBackdropLabel"><i class="far fa-user"></i>
          Seleccione cliente</h5>
        <button class="btn p-1" type="button" data-bs-dismiss="modal" aria-label="Close">
          <span class="fas fa-times fs-9 text-white dark__text-gray-1100"></span></button>
      </div>
      <div class="modal-body">
        <!--cuerpo inicio -->
        <div class="row">
          <!--input con el nombre del cliente donde se va a guardar -->
          <div class="form-group col-xs-12 col-sm-12 pb-3">
            <input type="hidden" placeholder="Cliente Seleccionado" class="typeahead form-control form-control-sm"
              id="cargar_cliente" readonly="readonly">
          </div>
          <!--datatable para seleccionar el cliente -->
          <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-12 col-xxl-12">
            <!-- inicio de la tabla-->
            <?php
            $array = $this->prueba->traercliente_modal();
            $uno = 0;
            ?>
            <div class='row'>
              <div class='col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12'>
                <div class='table-responsive noSwipe'>
                  <table id="myTable" class='table table-striped table-hover table-bordered table-sm' style="font-size: 11px;" data-page-length='100'>
                    <thead>
                      <tr>
                        <th class="text-center" data-sort="id">#</th>
                        <th data-sort="cliente">Cliente</th>
                        <th class="text-center" data-sort="nit">Nit</th>
                        <th class="text-center" data-sort="nit">Empresa</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($array["rowsData"] as $key => $value): ?>
                        <?php $uno++; ?>
                        <tr>
                          <td class='cell-detail text-center'><span><?= $value['id']; ?></span></td>
                          <td class='cell-detail'><span><?= $value['nombre']; ?></span></td>
                          <td class='cell-detail text-center'><span><?= $value['documento'] . '-' . $value['digito_verificacion'] ?></span></td>
                          <td class='cell-detail'><span><?= $value['nombre_empresa']; ?></span></td>
                          <td class='cell-detail text-center'>
                            <button id='btn_uno<?= $uno; ?>' class='btn btn-sm' type='button' title='Seleccionar Cliente' onclick='verVehiculo(this);'
                              data-id='<?= $value['documento']; ?>' data-id2='<?= $value['digito_verificacion']; ?>' data-id3='<?= $value['telefono']; ?>' data-id4='<?= $value['nombre']; ?>'
                              data-id5='<?= $value['direccion']; ?>' data-id6='<?= $value['id']; ?>' data-id7='<?= $value['email']; ?>' data-id8='<?= $value['tipo_documento']; ?>'
                              data-id9='<?= $value['regimen']; ?>' data-id10="<?= $value['empresa_id']; ?>" data-id11="<?= $value['capacidad_endeudamiento'] ?>" data-id12="<?= $value['saldo_cartera'] ?>">
                              <i class="far fa-check-circle"></i>
                            </button>
                          </td>
                        </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <!-- fin tabla -->
          </div>
        </div>
        <!-- cuerpo fin  -->
      </div>
      <div class=" modal-footer">
        <!-- <button class="btn btn-primary" type="button">Okay</button>
        <button class="btn btn-outline-primary btn-sm" type="button" data-bs-dismiss="modal">Cancelar</button> -->
      </div>
    </div>
  </div>
</div>

<div id="loading-overlay-nexosapp" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para NexosAPP...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
  </div>
</div>