<!-- <div class="nexos-content">
	<div class="row" style="margin:-11px -39px -11px -39px;">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
				<tbody>
					<tr>
						<td class="celda_titulo2 text-center" style="margin:25px;">
							<b>Retransmisión de documentos y recursos al RDNC</b>
						</td>
					</tr>
					<tr>
					</tr>
				</tbody>
			</table>
			<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
				<thead>
					<tr>
						<th style="background-color: #F5F5F5; font-weight: bold; font-size: 12px; border: 1px solid #ddd; width: auto; white-space: nowrap;" class="text-left"> Numero de Manifiesto:</th>
						<td style="border: 1px solid #ddd; width: auto; white-space: nowrap;">
							<input type="number" id="numero_manifiesto" name="numero_manifiesto" style="width: 100%;" oninput="this.value = this.value.toUpperCase();">
						</td>
						<th style="background-color: #F5F5F5; font-weight: bold; font-size: 12px; border: 1px solid #ddd; width: auto; white-space: nowrap;" class="text-left"> Acción:</th>
						<td style="border: 1px solid #ddd; width: auto; white-space: nowrap;">
							<button class="btn btn-success btn-xs" id="buscar_datos" name="buscar_datos" style="width: 100%;height: 23px;"><i class="fas fa-search"></i> Buscar</button>
						</td>
					</tr>
				</thead>
			</table>
			<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
				<tbody>
					<tr>
						<td class="celda_titulo2 text-center" style="margin:25px;">
							<b>Información del cliente</b>
						</td>
					</tr>
					<tr>
					</tr>
				</tbody>
			</table>
			<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
				<thead>
					<tr>
						<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Tipo de documento:</th>
						<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;margin: 0;" id="tipo_documento"></td>
						<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Número de documento:</th>
						<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;margin: 0; " id="numero_documento"></td>
						<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Codigo Cliente:</th>
						<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="codigo_cliente"></td>
					</tr>
					<tr>
						<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Nombre o Razón social:</th>
						<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;" id="nombre_cliente"></td>
						<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Telefono:</th>
						<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="telefono_cliente"></td>
						<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Dirección:</th>
						<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="direccion_cliente"></td>
					</tr>
					<tr>
						<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Estado RNDC:</th>
						<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;" id="estado_cliente_rndc"></td>
					</tr>
				</thead>
			</table>
			<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
				<tbody>
					<tr>
						<td class="celda_titulo2 text-center" style="margin:25px;">
							<b>Información del remitente & destinatario</b>
						</td>
					</tr>
					<tr>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
					<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top:  1px solid #fff;">
						<tbody>
							<tr>
								<td class="celda_titulo2 text-center" style="margin:25px;">
									<b>Información del remitente</b>
								</td>
							</tr>
							<tr>
							</tr>
						</tbody>
					</table>
					<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
						<thead>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Documento:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;margin: 0;" id="documento_remitente"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Digito Verificacion:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;margin: 0; " id="digito_remitente"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Nombre:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="nombre_remitente"></td>
							</tr>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Dirección:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;" id="direccion_remitente"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Telefono:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="telefono_remitente"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Estado RNDC:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="esatdo_rndc_remitente"></td>
							</tr>
						</thead>
					</table>
				</div>
				<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
					<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top:  1px solid #fff;">
						<tbody>
							<tr>
								<td class="celda_titulo2 text-center" style="margin:25px;">
									<b>Información del destinatario</b>
								</td>
							</tr>
							<tr>
							</tr>
						</tbody>
					</table>
					<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
						<thead>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Documento:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;margin: 0;" id="documento_destinatario"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Digito Verificacion:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;margin: 0; " id="digito_destinatario"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Nombre:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="nombre_destinatario"></td>
							</tr>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Dirección:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;" id="direccion_destinatario"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Telefono:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="telefono_destinatario"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Estado RNDC:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="esatdo_rndc_destinatario"></td>
							</tr>
						</thead>
					</table>
				</div>
			</div>

			<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
				<tbody>
					<tr>
						<td class="celda_titulo2 text-center" style="margin:25px;">
							<b>Información de proveedores</b>
						</td>
					</tr>
					<tr>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
					<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top:  1px solid #fff;">
						<tbody>
							<tr>
								<td class="celda_titulo2 text-center" style="margin:25px;">
									<b>Información del propietario</b>
								</td>
							</tr>
							<tr>
							</tr>
						</tbody>
					</table>
					<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
						<thead>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Tipo documento:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;margin: 0;" id="tipo_documento_propietario"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Documento:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;margin: 0; " id="documento_propietario"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Nombre:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="nombre_propietario"></td>
							</tr>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Dirección:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;" id="direccion_propietario"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Telefono:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="telefono_propietario"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Estado RNDC:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="esatdo_rndc_propietario"></td>
							</tr>
						</thead>
					</table>
				</div>
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
					<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top:  1px solid #fff;">
						<tbody>
							<tr>
								<td class="celda_titulo2 text-center" style="margin:25px;">
									<b>Información del poseedor</b>
								</td>
							</tr>
							<tr>
							</tr>
						</tbody>
					</table>
					<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
						<thead>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Tipo documento:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;margin: 0;" id="tipo_documento_tenedor"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Documento:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;margin: 0; " id="documento_tenedor"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Nombre:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="nombre_tenedor"></td>
							</tr>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Dirección:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;" id="direccion_tenedor"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Telefono:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="telefono_tenedor"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Estado RNDC:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="esatdo_rndc_tenedor"></td>
							</tr>
						</thead>
					</table>
				</div>
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
					<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top:  1px solid #fff;">
						<tbody>
							<tr>
								<td class="celda_titulo2 text-center" style="margin:25px;">
									<b>Información del conductor</b>
								</td>
							</tr>
							<tr>
							</tr>
						</tbody>
					</table>
					<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
						<thead>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Tipo documento:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;margin: 0;" id="tipo_documento_conductor"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Documento:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;margin: 0; " id="documento_conductor"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Nombre:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="nombre_conductor"></td>
							</tr>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Dirección:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;" id="direccion_conductor"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Telefono:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="telefono_conductor"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Estado RNDC:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="esatdo_rndc_conductor"></td>
							</tr>
						</thead>
					</table>
				</div>
			</div>
			<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
				<tbody>
					<tr>
						<td class="celda_titulo2 text-center" style="margin:25px;">
							<b>Información de vehículos & tráiler</b>
						</td>
					</tr>
					<tr>
					</tr>
				</tbody>
			</table>
			<div class="row">
				<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
					<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top:  1px solid #fff;">
						<tbody>
							<tr>
								<td class="celda_titulo2 text-center" style="margin:25px;">
									<b>Información del vehículo</b>
								</td>
							</tr>
							<tr>
							</tr>
						</tbody>
					</table>
					<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
						<thead>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Placa:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;margin: 0;" id="palca_vehiculos"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Configuración:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;margin: 0; " id="confgiracion_vehiculo"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Marca:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="marca_vehiculo"></td>
							</tr>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Liena:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;" id="linea_vehiculo"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Modelo:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="modelo_vehiculo"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Estado RNDC:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="esatdo_rndc_vehiculo"></td>
							</tr>
						</thead>
					</table>
				</div>
				<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
					<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top:  1px solid #fff;">
						<tbody>
							<tr>
								<td class="celda_titulo2 text-center" style="margin:25px;">
									<b>Información del tráiler</b>
								</td>
							</tr>
							<tr>
							</tr>
						</tbody>
					</table>
					<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
						<thead>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Placa:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;margin: 0;" id="palca_vehiculos"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Configuración:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;margin: 0; " id="confgiracion_vehiculo"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Marca:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="marca_vehiculo"></td>
							</tr>
							<tr>
								<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Carroceria:</th>
								<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;" id="linea_vehiculo"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Modelo:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="modelo_vehiculo"></td>
								<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
									Estado RNDC:</th>
								<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="esatdo_rndc_vehiculo"></td>
							</tr>
						</thead>
					</table>
				</div>
			</div>


			<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
				<tbody>
					<tr>
						<td class="celda_titulo2 text-center" style="margin:25px;">
							<b>Información de orden de cargue</b>
						</td>
					</tr>
					<tr>
					</tr>
				</tbody>
			</table>

			<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
				<thead>
					<tr>
						<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Orden:</th>
						<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;margin: 0;" id="numero_orden"></td>
						<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Cliente:</th>
						<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;margin: 0; " id="confgiracion_vehiculo"></td>
						<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Carga (kg):</th>
						<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="marca_vehiculo"></td>
					</tr>
					<tr>
						<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Producto:</th>
						<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;" id="linea_vehiculo"></td>
						<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Empaque:</th>
						<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="modelo_vehiculo"></td>
						<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Estado RNDC:</th>
						<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="esatdo_rndc_vehiculo"></td>
					</tr>
				</thead>
			</table>


			<table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
				<tbody>
					<tr>
						<td class="celda_titulo2 text-center" style="margin:25px;">
							<b>Información de remesa</b>
						</td>
					</tr>
					<tr>
					</tr>
				</tbody>
			</table>

			<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
				<thead>
					<tr>
						<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Rmesa:</th>
						<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;margin: 0;" id="numero_orden"></td>
						<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Orden:</th>
						<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;margin: 0; " id="confgiracion_vehiculo"></td>
						<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Pedido:</th>
						<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="marca_vehiculo"></td>
					</tr>
					<tr>
						<th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Precintos:</th>
						<td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;" id="linea_vehiculo"></td>
						<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Observación:</th>
						<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="modelo_vehiculo"></td>
						<th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
							Estado RNDC:</th>
						<td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; " id="esatdo_rndc_vehiculo"></td>
					</tr>
				</thead>
			</table>

		</div>
	</div>
</div> -->
<!-- </div> -->

<div class="panel panel-border panel-contrast">
	<div class="panel-heading panel-heading-contrast">
		Informe Carga
		<div class="tools"> </div>
		<span class="panel-subtitle">Módulo dedicado transmisión de documentos de carga.</span>
		<div class=" col-xs-12 col-sm-4 col-md-12">
			<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'">
			<input type="hidden" id="elperfil" class="form-control input-sm" readonly="readonly" value="0">
		</div>
	</div>
	<div class="panel-body">
		<div class="nexos-messages"></div>
		<div class="nexos-content">
			<div class="row">
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfiltro">
					<label>Documento Carga</label>
					<select id="filtro" class="form-control input-sm">
						<option value="">Seleccionar</option>
						<option value="" disabled>Parametros</option>
						<option value="4">Cliente</option>
						<option value="5">Remitentes</option>
						<option value="6">Propietario-Poseedor-Conductor-veh</option>
						<option value="7">Trailer</option>
						<option value="8">Vehículo</option>
						<option value="" disabled>Documentos</option>
						<option value="1">Remesa</option>
						<option value="2">Manifiesto</option>
						<option value="3">Cumplido</option>
					</select>
				</div>

				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 opcion_filtro">
					<label>Opción de Filtro</label>
					<select id="opcion" class="form-control input-sm">
						<option value="">Seleccione</option>
						<option value="3">Filtrar por número</option>
						<option value="4">Filtrar por Fecha</option>
					</select>
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divcliente">
					<label>Número Documento</label>
					<input type="text" id="numero_documento" class="form-control input-sm">
				</div>

				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfecha">
					<label>Fecha</label>
					<input type="date" id="fecha_doc" class="form-control input-sm">
				</div>

				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divbtnbusqueda">
					<br><button id="buscar_datos" class="btn btn-primary btn-sm"> <i class="fas fa-search"></i> Buscar</button>
				</div>
			</div><br>


			<div class="row" id="contenedor_datos">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="panel panel-border-color panel-border-color-dark">
						<div class="panel-body" id="bodycontenido">
							<div class="row">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<label><strong>Respuesta Ministerio</strong></label>
									<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="respuesta_rndc"></div>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label><strong>Etiquetas</strong></label>
									<div class="panel-body" id="etiqueta">
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<div class="panel-body" id="etiqueta2">
									</div>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>

			<div class="row" id="tabla_datos">
				<hr>
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class='table-responsive noSwipe'>
						<table id='table1' class='table table-condensed table-hover table-bordered table-striped' data-page-length='100'>
							<thead id="cabecera_general">
							</thead>
							<tbody id="tabla_general">
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12"></div>
	</div>
</div>

<!-- Mensajes para los usuarios de la plataforma -->
<!-- <div id="loading-overlay-nexosapp" class="loading-nexosapp">
	<div style="text-align: center;">
		<img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
		<h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para NexosAPP...</h2>
		<h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
	</div>
</div>

<div id="loading-overlay-oet" class="loading-nexosapp">
	<div style="text-align: center;">
		<img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
		<h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para Oet...</h2>
		<h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
	</div>
</div>

<div id="loading-overlay-rndc" class="loading-nexosapp">
	<div style="text-align: center;">
		<img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
		<h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para Rndc...</h2>
		<h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
	</div>
</div> -->
</div>
</div>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src=<?php echo BASE_URL; ?>/views/web_service/js/informe_carga.js type="text/javascript"></script>
<!-- <script src=<?php echo BASE_URL; ?>/views/web_service/js/transmision_rndc.js type="text/javascript"></script> -->
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>


<script type="text/javascript">
	$(document).ready(function() {
		//initialize the javascript
		App.init();
		App.wizard();
	});
</script>