<div class="panel panel-border panel-contrast">
	<div class="panel-heading panel-heading-contrast">
		Anulación
		<div class="tools">	</div>
		<span class="panel-subtitle">
      En este apartado podrá ejecutar anular el proceso que seleccione para que no se vea reflejado en los demás módulos.
    </span>
		<div class=" col-xs-12 col-sm-4 col-md-12">
			<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'" >
			<input type="hidden" id="elperfil" class="form-control input-sm" readonly="readonly" value="0">
		</div>
	</div>
	<div class="panel-body">
		<div class="nexos-messages"></div>
		<div class="nexos-content">
			<section class="row">
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
					<label><strong>(*) Módulo de cambio</strong></label>
					<select id="modulo_cambio" class="form-control input-sm">
						<option value="">Seleccione</option>
						<option value="CO">Cotización</option>
						<option value="SS">Solicitud de Servicio</option>
						<option value="ES">Estudio de Seguridad</option>
						<option value="OC">Orden de Cargue</option>
						<option value="RM">Remesa</option>
						<option value="MNF">Manifiesto</option>
						<option value="CU">Cumplido</option>
						<option value="LQ" disabled="disabled">Liquidación</option>
						<option value="SB">Subasta</option>
					</select>
				</div>
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
					<label><strong>(*) Número de Documento</strong></label>
					<input type="text" id="numero_documento" class="form-control input-sm" tooltip="Número documento asignado por el sistema">
				</div>
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
						<br><button id="Buscar_Dato" class="btn btn-primary btn-sm mdi mdi-search">Buscar</button>
				</div>
			</section><br>
			<section class="row" id="contenedor_datos">
				<div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
					<div class="panel panel-border-color panel-border-color-dark">
						<div class="panel-heading">
		     <p id="titulo"><strong></strong></p>
		    </div>
		    <div class="panel-body" id="bodycontenido">
		    </div>	
					</div>
				</div>
			</section><br>
			<section class="row" id="contenedor_tabla">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div  class='table-responsive noSwipe'>
					<table id='table1' class='table table-striped table-hover' data-page-length='100'>
						<thead>
							<tr class='nexos-encabezado'>
								<th>Número</th>
								<th>Documento</th>
								<th>Cliente</th>	
								<th>Fecha</th>
								<th style='width:10%;min-width: 10%;'>Acciones</th>
							</tr>
						</thead>
						<tbody id="body_documento">
						</tbody>
					</table>
					</div>
				</div>
			</section>
		</div>	
	</div>

	   <script src=<?php echo BASE_URL;?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/js/main.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
	  	 <script src=<?php echo BASE_URL;?>views/gestion_cambio_proceso/js/proceso.js type="text/javascript"></script>
	  	 
		<!-- js para creacion de formularios dinamicos -->
	    <script src=<?php echo BASE_URL;?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>
	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			
	    </script> 