<div class="pb-6">
    <div class="row align-items-center justify-content-between g-3 mb-6">
        <div class="col-12 col-md-auto">
            <!-- <h2 class="mb-0">Analytics</h2> -->
        </div>
        <div class="col-12 col-md-auto">
            <!-- <div class="flatpickr-input-container">
                <input class="form-control ps-6 datetimepicker" id="datepicker" type="text"
                    data-options='{"dateFormat":"M j, Y","disableMobile":true,"defaultDate":"Mar 1, 2022"}' /><span
                    class="uil uil-calendar-alt flatpickr-icon text-body-tertiary"></span>
            </div> -->
        </div>
    </div>
    <!-- <div class="px-3 mb-6">
        <div class="row justify-content-between" id="indicadores_porcentuales"></div>
    </div> -->

    <div class="px-3 mb-6">
        <div class="row" >
            <div class="col-12 col-md-12">
                <div class="card h-100">
                    <div class="row card-body" id="indicadores_graficos">

                    <iframe title="Modelo de datos Indicadores Carboquimica" width="600" height="373.5" src="https://app.powerbi.com/view?r=eyJrIjoiNjg3ZWU0NmEtZTA3Yy00ZjZkLTllODctMGQ0NTgyMWE3YzBjIiwidCI6ImRlYjRlNjExLWI5YmYtNDZlNS05YTU4LTQ0YjFkZTRmM2ViMiJ9" frameborder="0" allowFullScreen="true"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>  

</div>