<div class="container-fluid">
  <!-- <div class="d-flex justify-content-center"> -->
  <div class="row">

    <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 col-xxl-3" id="seleccionar_tipo_pedido">
      <!-- Selecionar que tipo de cargue de informacion se hara  -->
      <!-- Select con dos opciones -->
      <label class="form-label" for="customFileSm">Tipo de pedido</label>
      <select id="miSelect" class="form-control form-control-sm" style="margin-bottom:20px;">
        <option value="">-- Selecciona una opción --</option>
        <option value="cargue">Cargue Masivo</option>
        <option value="crear_pedido">Crear Pedido</option>
      </select>
    </div>

    <div class="col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 col-xxl-3" id="seleccionar_tipo_modalidad">
      <!-- Selecionar que tipo de cargue de informacion se hara  'CARGA SECA','CARGA LIQUIDA','IMPORTACION','EXPORTACION' -->
      <!-- Select con dos opciones -->
      <label class="form-label" for="customFileSm">Modalidad</label>
      <select id="miSelectModalidad" class="form-control form-control-sm" style="margin-bottom:20px;">
        <option value="">-- Selecciona una opción --</option>
        <option value="CARGA SECA">CARGA SECA</option>
        <option value="CARGA LIQUIDA">CARGA LIQUIDA</option>
        <option value="IMPORTACION">IMPORTACION</option>
        <option value="EXPORTACION">EXPORTACION</option>
      </select>
    </div>

    <div class="col-12 col-sm-12 col-md-10 col-lg-10 col-xl-10 col-xxl-10" id="cargue_masivo" style="display:none;">
      <!-- 1) Input para seleccionar el archivo de Excel -->
      <div class="mb-3">
        <label class="form-label" for="customFileSm">Subir Archivo</label>
        <input type="file" class="form-control form-control-sm" id="excelFile" accept=".xls, .xlsx"
          onchange="leerExcel()" placeholder="Seleccionar Archivo">
      </div>
    </div>

    <!-- Botón para descargar la plantilla de Excel -->
    <div class="col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 col-xxl-2 mt-4" id="boton_descargar_plantilla" style="display: none;">
      <div class="d-flex justify-content-end align-content-center">
        <a href="<?= BASE_URL ?>public/files/Pedidos.xlsx" download
          class="btn btn-subtle-primary me-1 mb-1 btn-sm"><span data-feather="download-cloud"></span> Descargar
          Plantilla</a>
      </div>
    </div>

    <div class="col-12 gy-6 my-3" id="btn-acciones" style="display:none;">
      <div class="row g-3 justify-content-end">
        <div class="col-auto">
          <button class="btn btn-phoenix-primary btn-sm text-danger" type="button" id="btn-cancelar-importacion">
            <span class="text-danger" data-feather="x"></span> Cancelar
          </button>
        </div>
        <div class="col-auto">
          <button class="btn btn-success btn-sm" id="btn_importar_pedidos" type="button">
            <span class="uil uil-file-import"></span> Importar Pedidos
          </button>
        </div>
      </div>
    </div>

    <!-- 3) Área de previsualización -->
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12" id="visualizar_pedidos"
      style="display:none;">
      <h6>Vista Previa</h6>
      <div class="form-group col-xs-12">
        <div class="table-responsive">
          <table class="table table-striped table-sm" id="previewTable" cellpadding="0" border="1"
            style="width: 100%; border: #332D2D;">
            <!-- Aquí se generarán dinámicamente las filas -->
          </table>
        </div>
      </div>
    </div>

    <!-- <div class="col-12 gy-6 my-3" id="btn-acciones" style="display:none;">
      <div class="row g-3 justify-content-end">
        <div class="col-auto">
          <button class="btn btn-phoenix-primary btn-sm text-danger" type="button" id="btn-cancelar-importacion">
            <span class="text-danger" data-feather="x"></span> Cancelar
          </button>
        </div>
        <div class="col-auto">
          <button class="btn btn-success btn-sm" id="btn_importar_pedidos" type="button">
            <span class="uil uil-file-import"></span> Importar Pedidos
          </button>
        </div>
      </div>
    </div> -->

    <div id="crear_pedido" style="display: none;">
      <div class="row">
        <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
          <div class="mb-1">
            <label class="control-label">(*) Clientes:</label>
            <select class="form-select form-select-sm" name="clientes" id="slct_clientes_" style="width: 100%;">
              <!-- <option value="" disabled="" selected="">Seleccione</option> -->
            </select>
          </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
          <hr class="my-1 text-dark">
          <div class="d-flex flex-wrap justify-content-start">
            <div class="col-12 col-sm-12 col-md-11 col-lg-11 col-xl-11 col-xxl-11">
              <h6 class="mb-0 text-body-highlight me-2">Datos de la mercancía</h6>
            </div>
            <div class="col-12 col-sm-12 col-md-1 col-lg-1 col-xl-1 col-xxl-1 d-flex justify-content-end">
              <a class="fw-bold fs-9 text-decoration-none" href="#!" data-toggle="tooltip" data-placement="top"
                title="Agregar fila" id="agregar_fila"><span class="text-body uil-plus-square"></span> Agregar</a>
            </div>
          </div>
          <hr class="my-1 text-dark">
        </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
          <ul class="nav nav-underline fs-9 flex-nowrap p-1" id="bloque_header" role="tablist" style="overflow-x: auto;">
          </ul>
          <div class="tab-content mt-3" id="bloques_mercamcia"></div>

        </div>
      </div>

      <div class="col-12 gy-6 my-3" id="btn-acciones-pedidos" style="display:none;">
        <div class="row g-3 justify-content-end">
          <div class="col-auto">
            <button class="btn btn-phoenix-primary btn-sm text-danger" type="button" id="btn-cancelar-pedido">
              <span class="text-danger" data-feather="x"></span> Cancelar
            </button>
          </div>
          <div class="col-auto">
            <button class="btn btn-success btn-sm" id="btn_guardar_pedido" type="button">
              <span class="uil uil-file-import"></span> GUardar Pedido
            </button>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>