<?php
	$Conect = new Consultas;
	$_jsScripts = "";
	$_jsAjax = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
	$ssn_id_bodega = $_SESSION["usuario"]["id_bodega"];

	$r = new Request();
	// print_r($r->getArgs());

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/

	$table_view = '';
	$qr_estiba = '';

	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->bodegas) && count($this->bodegas)){

		$arrayMaterialNovedad = $this->bodegas->getMaterialNovedades($r->getArgs()[0]);
		// print_r("<pre>");
		// print_r($arrayMaterialNovedad);
		// print_r("</pre>");

		$table_view.= '
			<div class="panel-body">
				<div class="row">
					<div class="col-sm-12">
						<table class="table">
							<tbody>
								<tr>
									<td class="cell-detail">
										<div class="row">
											<div class="col-sm-1"></div>
											<div class="col-sm-3">
												<span>' . $arrayMaterialNovedad["rowsData"][0]["descripcion"] . '</span>
												<span class="cell-detail-description">' . $arrayMaterialNovedad["rowsData"][0]["codigo"] . '</span>
											</div>
											<div class="col-sm-3">
												<span>' . $arrayMaterialNovedad["rowsData"][0]["lote"] . '</span>
												<span class="cell-detail-description">' . $arrayMaterialNovedad["rowsData"][0]["fecha_vencimiento"] . '</span>
											</div>
											<div class="col-sm-4">
												<span>' . $arrayMaterialNovedad["rowsData"][0]["nombre"] . '</span>
												<span class="cell-detail-description">' . $arrayMaterialNovedad["rowsData"][0]["detalle"] . '</span>
											</div>
											<div class="col-sm-1"></div>
										</div>
									</td>
								</tr>
								<tr><td></td></tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		';

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_view.= '
			<div class="row">
				<div class="col-sm-3"></div>
				<div class="col-sm-6">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th>Unidad</th>
									<th style="width: 5%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		if($arrayMaterialNovedad['rowsData']){

			$_btn_qr = '';
			$_btn_print_qr = '';
			if($arrayMaterialNovedad['rowsData'][0]["causa_novedad"] == 1 AND $arrayMaterialNovedad['rowsData'][0]["grupo"] == 0){
				$_btn_print_qr = '
					<a href="#" id="imprimir" class="hint--top" data-hint="Imprimir QR´s"><span class="icon mdi mdi-print"></span></a>
				';
			}

			foreach ($arrayMaterialNovedad['rowsData'] as $key => $value) {
				$_btn_qr = '';
				if($value["causa_novedad"] == 1 AND $value["grupo"] == 0){
					$qr_estiba.= '<div class="panel col-sm-3 text-center" style="border: 0px; height: 47mm; margin: 0; padding: 20px 0 0 0; border-radius: 0; box-shadow: none;" id="area_"><img src="' . BASE_URL . $value["URL_QR"] . '" height="80" width="80"><br /><span class="panel-subtitle" style="font-size: 6px;">Código - ' . $value["codigo"] . '<br />Lote - ' . $value["lote"] . '-' . $value["grupo"] . ' (' . $value["fecha_vencimiento"] . ')<br />' . $value["descripcion"] . '<br />Unid. por estiba - ' . $value["cantidad_grupo"] . ' Unid<br />Present. - ' . $value["nom_unidad_presentacion"] . ' x ' . $value["cant_contenido_interno"] . ' ' . $value["nom_unidad_medida"] . '<br />Embal. - ' . $value["nom_unidad_empaque"] . ' x ' . $value["unidades_x_embalaje"] . ' Unid</span></div>';

					// INFORMACIÓN DE LA ESTIBA
					$info_contenido = '
						<div class="panel panel-border panel-contrast">
							<div class="panel-heading panel-heading-contrast">
								Información de Estiba - ' . $value["lote"] . '-' . $value["GRUPO_EMBALAJE"] . ' 
								<div class="tools">
								</div>
							</div>
						</div>
						<div class="form-group col-xs-4"></div>
						<div class="form-group col-xs-4 text-center" id="area_' . $value["lote"] . '-' . $value["GRUPO_EMBALAJE"] . '">
							<img src="' . BASE_URL . $value["URL_QR"] . '"  height="180" width="180">
							<span class="panel-subtitle">
								Código - ' . $value["codigo"] . '<br />
								Lote - ' . $value["lote"] . '-' . $value["GRUPO_EMBALAJE"] . ' (' . $value["fecha_vencimiento"] . ')<br />
								' . $value["descripcion"] . '<br />
								Unidades por estiba - ' . $value["cantidad_grupo"] . ' Unid<br />
								Presentación - ' . $value["nom_unidad_presentacion"] . ' x ' . $value["cant_contenido_interno"] . ' ' . $value["nom_unidad_medida"] . '<br />
								Embalaje - ' . $value["nom_unidad_empaque"] . ' x ' . $value["unidades_x_embalaje"] . ' Unid
							</span>
						</div>
						<div class="form-group col-xs-4"></div>
						<div class="row"></div>
					';
					$vista.= $info->_bootstrap_modal_dialog("info_" . $value["lote"] . "_" . $value["GRUPO_EMBALAJE"] , "Impresión de Estiba" , $info_contenido );

					// Botón de vista del 
					$_btn_qr = '
						<a href="#" data-toggle="modal" data-target="#info_' . $value["lote"] . '_' . $value["GRUPO_EMBALAJE"] . '" class="icon hint--top-left" data-hint="Ver QR"><span class="mdi mdi-eye"></span></a>
					';
				}

				// Se maqueta contenido de la tabla 
				$table_view.= '<tr>';
				// Columna Materiales
				$table_view.= '
					<td class="cell-detail">
						<span>' . $value["lote"] . '-' . $value["GRUPO_EMBALAJE"] . '</span>
						<span class="cell-detail-description">' . $value["TIPO_EMBALAJE"] . '</span>
					</td>
				';
				// Columna datos de lote y vencimiento del material
				$table_view.= '
					<td class="actions">
						' . $_btn_qr . '
					</td>
				';

				$table_view.= '</tr>';
			}

			// $_jsScripts.='
			// 	<script type="text/javascript">
			// 		$("#imprimir").click(function (){
			// 			console.log("Entro en funcion de impresión");
			// 			console.log("div#area_");
			// 			$("div#area_").printArea({
			// 				popWd:	30,
			// 				popHt: 	60
			// 			});
			// 		})
			// 	</script>
			// ';

		}

		$table_view.= '
							</tbody>
						</table>
					</div>
				</div>
			</div>
		';
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/

	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Materiales Novedad -  ' . $r->getArgs()[0] . ' (' . date('Y-m-d', $r->getArgs()[0]) . ')
				<br >Bodega - ' . $arrayMaterialNovedad["rowsData"][0]["BODEGA"] . '
				<div class="tools">
					<a href="' . BASE_URL . 'bodegas/ver_novedades/" class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>
					' . $_btn_print_qr . '
				</div>
				<span class="panel-subtitle">Visualización de los materiales que presentaron alguna novedad en la llegada a ala bodega.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';

	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE IMPRESION PrintThis -->
		<script src="%root_file%js/printThis.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE IMPRESION PrintArea -->
		<script src="%root_file%js/jquery.PrintArea.js" type="text/javascript"></script>

	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
			$("#imprimir").click(function(){
				$("#area_").printThis({
					importStyle: "block",
					header: \'' . $qr_estiba . '\',
				});
			});

			%js-ajax%
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%js-ajax%" , $_jsAjax , $vista);
	$vista = str_replace("%content%" , $table_view , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
