<?php
	$Conect = new Consultas;
	$_dbTable = "salidas"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";
	$_jsAjax = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
	$ssn_id_bodega = $_SESSION["usuario"]["id_bodega"];


	// if(BODEGAS_LITE){
	// 	echo "Es versión LITE";
	// }else{
	// 	echo "Es versión FULL";
	// }


	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->bodegas) && count($this->bodegas)){

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_despachos = '
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width:5%;"></th>
									<th style="width:5%;"></th>
									<th style="width: 5%;">Unidades</th>
									<th>Delivery</th>
									<th style="width:15%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayDespachos = $this->bodegas->getPreSalidas($ssn_id_cliente, $ssn_id_bodega);
		// print_r("<pre>");
		// print_r($arrayDespachos);
		// print_r("</pre>");
		if ($arrayDespachos['rowsData']) {
			foreach ($arrayDespachos['rowsData'] as $key => $value) {
				$col_check = '
					<td class="be-checkbox">
					</td>
				';
				/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
				switch ($value["estado"]) {
					case '0':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-danger">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

						$_popupHabilita = $alert->_alert_modal_mod_warning( $value["delivery"] , "Realmente desea habilitar este elemento?" , $_dbTable );
						$vista.= $_popupHabilita[0];
						$_jsScripts.=$_popupHabilita[1];

						// se asigna contenudo de la columna de acciones
						$col_action = '
							<td class="actions">
								<a href="#" class="icon"><span id="#habilita_' . $value["delivery"] . '" data-toggle="modal" data-target="#habilita_' . $value["delivery"] . '" class="icon mdi mdi-check-circle"></span></a>
							</td>
						';
						break;
					
					case '1':
						// INFORMACIÓN LOS QR NECESARIOS PARA SACAR EL MATERIAL
						$info_contenido = '
							<table id="table" class="table table-striped table-hover">
								<thead>
									<tr class="nexos-encabezado">
										<th style="width: 5%;">QR</th>
										<th>Información</th>
										<th></th>
										<th>Ubicación</th>
									</tr>
								</thead>
								<tbody>
									%table_info%
								</tbody>
							</table>
						';

						// Tomo los materiales del envio
						$arrayQrSalidas = $this->bodegas->getQrPreSalidas($value["delivery"]);
						// print_r("<pre>");
						// print_r($arrayQrSalidas);
						// print_r("</pre>");

						$table_info = '';
						if ($arrayQrSalidas["rowsNum"] > 0) {
							foreach ($arrayQrSalidas["rowsData"] as $key1 => $value1) {
								$empaque = 'Estiba';
								if($arrayQrSalidas["rowsData"][$key1]["grupo"] == 0){
									$empaque = $arrayQrSalidas["rowsData"][$key1]["nom_unidad_empaque"];
								}
								$table_info.= '
									<tr>
										<td class="cell-detail">
											<div class="panel col-sm-12 text-center" style="border: 0px; height: 47mm; margin: 0; padding: 20px 0 0 0; border-radius: 0; box-shadow: none;">
												<span style="font-size: 6px;">
													<img src="' . BASE_URL . $arrayQrSalidas["rowsData"][$key1]["URL_QR"] . '" height="80" width="80"><br />
													Código - ' . $arrayQrSalidas["rowsData"][$key1]["codigo"] . '<br />
													Lote - ' . $arrayQrSalidas["rowsData"][$key1]["lote"] . ' (' . $arrayQrSalidas["rowsData"][$key1]["fecha_vencimiento"] . ')<br />
													' . $arrayQrSalidas["rowsData"][$key1]["descripcion"] . '<br />
													Present. - ' . $arrayQrSalidas["rowsData"][$key1]["nom_unidad_presentacion"] . ' x ' . $arrayQrSalidas["rowsData"][$key1]["cant_contenido_interno"] . ' ' . $arrayQrSalidas["rowsData"][$key1]["nom_unidad_medida"] . '
												</span>
											</div>
										</td>
										<td class="cell-detail">
											<span>
												Código - ' . $arrayQrSalidas["rowsData"][$key1]["codigo"] . '<br />
												Lote - ' . $arrayQrSalidas["rowsData"][$key1]["lote"] . ' (' . $arrayQrSalidas["rowsData"][$key1]["fecha_vencimiento"] . ')<br />
												' . $arrayQrSalidas["rowsData"][$key1]["descripcion"] . '<br />
												Present. - ' . $arrayQrSalidas["rowsData"][$key1]["nom_unidad_presentacion"] . ' x ' . $arrayQrSalidas["rowsData"][$key1]["cant_contenido_interno"] . ' ' . $arrayQrSalidas["rowsData"][$key1]["nom_unidad_medida"] . '
											</span>
										</td>
										<td class="cell-detail">
											<div class="col-sm-12">
												<span>' . $empaque . '</span>
											</div>
										</td>
										<td class="cell-detail">
											<div class="col-sm-12">
												<span>' . $arrayQrSalidas["rowsData"][$key1]["UBICACION_ESTIBA"] . '</span>
											</div>
										</td>
									</tr>
								';
							}
						} else {
							$table_info = '
								<tr>
									<td class="cell-detail" colspan="5">
										<div class="col-sm-12 text-center">
											<span>El envío no tiene materiales asignados</span>
										</div>
									</td>
								</tr>
							';
							$arraySalidas["rowsNum"] = 0;
						}

						// Ingreso los materiales a la tabla
						$info_contenido = str_replace("%table_info%", $table_info , $info_contenido);

						$vista.= $info->_bootstrap_modal_dialog("info_" . $value["delivery"] , "Materiales de Orden de Salida - " . $value["delivery"] , $info_contenido );

						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-success">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

						$_popupElimina = $alert->_alert_modal_mod_danger($value["delivery"], "Realmente desea eliminar este elemento?",$_dbTable);
						$vista.= $_popupElimina[0];
						$_jsScripts.=$_popupElimina[1];

						$col_action = '
							<td class="actions">
								<a href="' . BASE_URL . 'bodegas/material_despacho/' . $value["delivery"] . '" class="icon hint--top-left" data-hint="Administrar Materiales a Enviar"><span class="mdi mdi-eye"></span></a>
							</td>
						';

						break;

					case '2':
						// INFORMACIÓN GENERAL DEL ENVIO
						$info_contenido = '
							<div class="panel panel-border panel-contrast">
								<div class="panel-heading panel-heading-contrast">
									Delivery - ' . $value["delivery"] . '
								</div>
							</div>
							<strong>Materiales del Envío</strong>
							<table id="table" class="table table-striped table-hover">
								<thead>
									<tr class="nexos-encabezado">
										<th>Material</th>
										<th>Shipment</th>
										<th>Lote</th>
										<th>Cantidad</th>
									</tr>
								</thead>
								<tbody>
									%table_info%
									<tr>
										<td></td><td></td><td></td><td></td>
									</tr>
								</tbody>
							</table>
						';

						// Tomo los materiales del envio
						$arraySalidas = $this->bodegas->getEnvioSalidas($value["delivery"]);
						// print_r("<pre>");
						// print_r($arraySalidas);
						// print_r("</pre>");

						$table_info = '';
						if ($arraySalidas["rowsNum"] > 0) {
							foreach ($arraySalidas["rowsData"] as $key1 => $value1) {
								$table_info.= '
									<tr>
										<td class="cell-detail">
											<div class="col-sm-12">
												<span>' . $arraySalidas["rowsData"][$key1]["descripcion"] . '</span>
												<span class="cell-detail-description">' . $arraySalidas["rowsData"][$key1]["codigo"] . '</span>
											</div>
										</td>
										<td class="cell-detail">
											<div class="col-sm-12">
												<span>' . $arraySalidas["rowsData"][$key1]["shipment"] . '</span>
											</div>
										</td>
										<td class="cell-detail">
											<div class="col-sm-12">
												<span>' . $arraySalidas["rowsData"][$key1]["lote"] . '</span>
												<span class="cell-detail-description">Vence - ' . $arraySalidas["rowsData"][$key1]["fecha_vencimiento"] . '</span>
											</div>
										</td>
										<td class="cell-detail">
											<div class="col-sm-12">
												<span>' . $arraySalidas["rowsData"][$key1]["cantidad"] . '</span>
												<span class="cell-detail-description">' . $arraySalidas["rowsData"][$key1]["nom_unidad_empaque"] . ' x ' . $arraySalidas["rowsData"][$key1]["unidades_x_embalaje"] . ' unid</span>
												<span class="cell-detail-description">' . $arraySalidas["rowsData"][$key1]["nom_unidad_presentacion"] . ' x ' . $arraySalidas["rowsData"][$key1]["cant_contenido_interno"] . ' ' . $arraySalidas["rowsData"][$key1]["nom_unidad_medida"] . '</span>
											</div>
										</td>
									</tr>
								';
							}
						} else {
							$table_info = '
								<tr>
									<td class="cell-detail" colspan="5">
										<div class="col-sm-12 text-center">
											<span>El envío no tiene materiales asignados</span>
										</div>
									</td>
								</tr>
							';
							$arraySalidas["rowsNum"] = 0;
						}

						// Ingreso los materiales a la tabla
						$info_contenido = str_replace("%table_info%", $table_info , $info_contenido);

						$vista.= $info->_bootstrap_modal_dialog("info_" . $value["delivery"] , "Materiales del Delivery - " . $value["delivery"] , $info_contenido );

						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-warning">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

						$col_check = '
							<td class="be-checkbox">
								<input type="checkbox" class="checkbox" name="checkbox" value="' . $value["delivery"] . '-' . $value[0] . '-' . $value["id_bodega"] . '" id="check_' . $value["delivery"] . '_' . $value[0] . '" >
								<label for="check_' . $value["delivery"] . '_' . $value[0] . '"></label>
							</td>
						';

						$_popupElimina = $alert->_alert_modal_mod_danger($value[0], "Realmente desea eliminar este elemento?","material_bodega_salida");
						$vista.= $_popupElimina[0];
						$_jsScripts.=$_popupElimina[1];

						$col_action = '
							<td class="actions">
								<a href="' . BASE_URL . 'bodegas/material_despacho/' . $value["delivery"] . '" class="icon hint--top-left" data-hint="Administrar Materiales a Enviar"><span class="mdi mdi-eye"></span></a>
								<a href="#" class="icon hint--top-left" data-hint="Eliminar Solicitud de Envío"><span id="elimina_' . $value[0] . '"data-toggle="modal" data-target="#elimina_' . $value[0] . '" class="icon mdi mdi-close-circle"></span></a>
							</td>
						';

						break;
				}
				/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

				// Se maqueta contenido de la tabla 
				$table_despachos.= '<tr>';
				// Columna de estado
				$table_despachos.= $col_stasus;
				// Columna de check box
				$table_despachos.= $col_check;

				// Columna de unidades
				$table_despachos.= '
					<td data-toggle="modal" data-target="#info_' . $value["delivery"] . '" class="cell-detail">
						<span class="label label-default">' . $value["UNIDADES"] . '</span>
					</td>
				';

				// Columna Delivery
				$table_despachos.= '
					<td data-toggle="modal" data-target="#info_' . $value["delivery"] . '" class="cell-detail">
						<span>' . $value["delivery"] . '</span>
						<span class="cell-detail-description">' . $value["nombre"] . '</span>
					</td>
				';
				// se asigna la columna de acciones
				$table_despachos.=$col_action;
				
				$table_despachos.= '</tr>';
			}

			$table_despachos.= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';

			// Validacion de asignacion de elemnentos del delivery
			$_jsScripts.='
				<script type="text/javascript">
					$(".checkbox").click(function (){
						$("#id_bodega_habilita").val("");
						var delivery_content = "";
						var id_check = "";
						$("input:checkbox[name=checkbox]:checked").each(function (){
							var valueCheck = $(this).val();
							var res = valueCheck.split("-");
							if(delivery_content == ""){
								delivery_content+= res[0] + ",";
								id_check = res[2];
								$("#id_bodega_habilita").val(id_check);
							}else{
								if(res[2] == id_check){
									delivery_content+= res[0] + ",";
								}else{
									delivery_content = "multiple bodega";
									return false;
								}
							}
						});
						$("#delivery_group").val(delivery_content);
					});
				</script>
			';
		}
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/

	// FORMULARIO DE SUBIDA DE ARCHIVO 
	if ($ssn_id_bodega) {
		$_form_bodega = '<div class="col-sm-8"></div><div class="col-sm-3"><input type="hidden" name="id_bodega" value="' . $ssn_id_bodega . '"></div>';
	} else {
		// Se crea el select de bodegas
		$slct_bodegas_archivo = $this->bodegas->getHtmlSelect( "id_bodega" , "_archivo" , $ssn_id_cliente);

		$_form_bodega = '<div class="col-sm-6"></div><div class="col-sm-6"><label class="control-label">Seleccione Bodega</label>' . $slct_bodegas_archivo . '</div><div class="row"></div>';
	}
	$_form_file = '
		<form action="' . BASE_URL . 'bodegas/generar_despacho/" method="POST" name="envia_archivo" enctype="multipart/form-data" style="border-radius: 0px;" class="form-horizontal group-border-dashed" >
			<div class="form-group">
				' . $_form_bodega . '
				<div class="col-sm-6"></div>
				<label class="col-sm-3 control-label">Subir Archivo de Generación de Ingreso</label>
				<div class="col-sm-3">
					<input type="file" name="file_ingresos" id="file_ingresos" class="inputfile">
					<label for="file_ingresos" class="btn-default"> <i class="mdi mdi-upload"></i><span>Busque Archivo...</span></label>
					<input type="submit" name="sube-archivo" id="sube-archivo" value="Subir" class="btn btn-success">
					<a href="' . BASE_URL . 'public\files\formatoGeneracionSalida.csv" target="_blank"  alt="Formato Archivos"><img src="' . BASE_URL . 'public\img\excel_2013.png" height="35" width="35"></a>
				</div>
			</div>
		</form>
	';


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Generar Salida de Materiales de Bodega
				<div class="tools">
					<a href="#" data-toggle="modal" data-target="#edita_files_" class="cell-detail  hint--top-left"  data-hint="Asignar Conductor"><span class="icon mdi mdi-check-circle"></span></a> 
				</div>
				<span class="panel-subtitle">Módulo de generación de salida de materiales de clientes de las bodegas Nexos Group.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%form-file%
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
			%js-ajax%
	    </script>
	';


	/****** CREACION CONTENIDO DE POPUPS ******/
	// CONTENIDO DEL POPUP DE FORMULARIO DE ASIGNCION DE CONDUCTOR AL GRUPO DE DELIVERIES

	$forms = '
		<form id="form_asigna">
			<input type="hidden" name="id_bodega" id="id_bodega_habilita" value="" class="form-control">
			<input type="hidden" name="delivery_group" id="delivery_group" value="" class="form-control">
			<input type="hidden" name="id_cliente" id_cliente value="' . $ssn_id_cliente . '" class="form-control">

			<div class="panel panel-border panel-contrast">
				<div class="panel-heading panel-heading-contrast">
					Aprobar Envío de Deliveries 
					<div class="tools">
						<a href="#" class="icon hint--top-left" data-hint="Aprobar Envío"><span class="icon mdi mdi-check-circle" id="asigna" data-dismiss="modal"></span></a>
					</div>
				</div>
			</div>
			<div class="form-group col-xs-12">
				<label>*Destino:</label>
				<input type="text" name="destino" id="destino" value="" placeholder="Destino" class="form-control">
				<label id="error_destino"></label>
			</div>
			<div class="row"></div>
		</form>
	';

	// Validacion JS de seleccion de materiales 
	$urlAsignaSalida = BASE_URL . 'libs/habilitar_salida.php';
	// Validacion de contenido del formulario de creacion
	$_jsScripts.='
		<script type="text/javascript">
			var validar_destino = "";

			$("#destino").focus(function (){
				$("#destino").keypress(function() {
					validarkeypress("#error_destino", "#destino");
				});
			});
			$("#destino").focusin(function (){
				removerClaseserror("#error_destino", "#destino");
			});
			$("#destino").focusout(function (){
				validar_destino = validaciones("vacio" , $("#destino").val() , "Destino");
				if(validar_destino != true){
					agregarClaseserror("#error_destino", "#destino", validar_destino);
				}
				else{
					removerClaseserror("#error_destino", "#destino");
				}
			});


			var flagError = "";
			if ( validar_destino != true ) {
				flagError = false;
			} else {
				flagError = true;
			}

			$(\'#asigna\').click(function () {
				var msgError = "";
				var deliveries =  $(\'#delivery_group\').val();

				if(deliveries){
					if(deliveries != "multiple bodega"){

						var destino =  $(\'#destino\').val();

						if (!destino) {
							msgError+= "<p>Para cerrar el envío debe diligenciar el <strong>Destino</strong>.</p>";
						}
					}else{
						msgError+= "<p>No puede generar una salida usando varias bodegas de origen.</p>";
					}
				}else{
					msgError+= "<p>Debe seleccionar primero los deliveries del listado para asignarles un conductor</strong>.</p>";
				}
				if (!msgError) {
					$.ajax({
						type		: 	"POST",
						cache		: 	false,
						url			: 	"' . $urlAsignaSalida . '",
						data		: 	$("#form_asigna").serialize(),
						beforeSend	: 	function(jqXHR, settings){
											$(".nexos-messages").html(\'<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' . BASE_URL . 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos</h4></div></div>\');
										},
						error: 			function(){
											console.log("error1...");
										},
						success		: 	function(data) {
											console.log(data);
											$(".nexos-messages").hide();
											$(".nexos-messages").html(\'<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong> Se han generado la orden con éxito.</div></div>\');
											$("#table1").hide();
											setTimeout(function() { location.reload(false);  }, 2000);

										}
					});
				} else {
					$(".nexos-messages").html(\'<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close-circle-o"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong> \' + msgError + \'</div></div>\');
				}
			});
		</script>
	';
	$_popupCrea = $form_crea->_message_title_modal("files_" , "Aprobar Envío de Deliveries" , $forms );
	$vista.= $_popupCrea;
	/****** FIN CREACION CONTENIDO DE POPUPS ******/


	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%js-ajax%" , $_jsAjax , $vista);
	$vista = str_replace("%content%" , $table_despachos , $vista);
	$vista = str_replace("%form-file%" , $_form_file , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

	/**** FUNCIONES DE SUBIDA DE ARCHIVO ****/
	if (isset($_POST["sube-archivo"])) {
		$_msg_error = "";
		$contenidoValido = false;

		if ( isset($_POST["id_bodega"]) ) {
			ini_set('max_execution_time', 120);

			$table = "cmx_" . $_dbTable;
			$ruta = BASE_URL . "public/files/";
			$columnasArchivo = 5;
			$_registro_exitoso = 0;
			$_count_row = 0;
			$archivoValido = true;

			if ($_FILES) {
				// print_r("<pre>");
				// print_r($_FILES);
				// print_r("</pre>");
				foreach ($_FILES as $key) {
					$nombre = $key["name"];
					$ruta_temporal = $key["tmp_name"];

					if ($nombre) {
						$file_origin = explode(".", $nombre);
						if ($file_origin[1] == "csv") {

							$x = 0;
							$info = array();
							$data = array();

							$archivo = file_get_contents($ruta_temporal);
							$archivo = ucfirst($archivo);

							// se verifica la separacion del archivo si es por , o por ;
							$_verifica_comas = substr_count($archivo,";");
							if ($_verifica_comas == 0) {
								$arrayArchivo = explode(",", $archivo);
							} else {
								$arrayArchivo = explode(";", $archivo);
							}

							$i = 0;

							foreach ($arrayArchivo as $datos) {
								$i++;
								$data[$i-1] = $datos;
								if ($i == $columnasArchivo) {
									$_count_row++;

									$arrayUltimaColumna = explode("\n", $datos);

									$data[$i-1] = $arrayUltimaColumna[0];
									$i = 1;

									$x++;
									if($x > 1){
										// Se verifica si la fila tiene datos, si no tiene la ignora
										$flagFila = false; 
										for ($j=0; $j < $columnasArchivo ; $j++) { 
											if (limpiaTexto($data[$j]) != "") {
												$flagFila = true;
												break;
											}
										}


										if ($flagFila) {
											// arreglo para la tabla material bodega
											// valido contentido de los campos 
											// campo id material
											if(limpiaTexto($data[0]) != ""){
												// campo Delivery
												if(limpiaTexto($data[1]) != ""){
													// campo shipment
													if(limpiaTexto($data[2]) != ""){
														$_filter_query = '';
														if($ssn_id_cliente != 1){
															$_filter_query = ' AND cmc.id_cliente = "' . $ssn_id_cliente;
														}
														// se busca el id del material
														$sql = '
															SELECT 
																cmc.id
															FROM 
																cmx_material_cliente cmc
															WHERE 
																cmc.codigo = "' . limpiaTexto($data[0]) . '"
																' . $_filter_query . ';
														';
														$buscaIdMaterial = $Conect->getConsulta($sql);
														// print_r("<p>Consulta id material</p>");
														// print_r("<pre>");
														// print_r($buscaIdMaterial);
														// print_r("</pre>");

														if ($buscaIdMaterial["rowsNum"] > 0) {
															$id_material = $buscaIdMaterial["rowsData"][0]["id"];
															// campo lote
															if(limpiaTexto($data[3]) != ""){
																// campo cantidad
																if(limpiaTexto($data[4]) != ""){
																	$sql = '
																		SELECT COUNT(ce.id) CUANTOS
																		FROM 
																			cmx_embalaje ce
																			INNER JOIN cmx_material_bodega cmb ON ce.id_material_bodega = cmb.id
																			INNER JOIN cmx_inventario cin ON cmb.id_material = cin.id_material_cliente
																		WHERE 
																			ce.grupo = 0
																			AND ce.sub_estado = 5
																			AND ce.estado = 1
																			AND cin.id_bodega = ' . $_POST["id_bodega"] . '
																			AND cmb.lote = "'.limpiaTexto($data[3]).'"
																			AND cmb.id_material = "' .$id_material. '"
																	';
																	// echo "<p>" . $sql . "</p>";
																	$existencias = $Conect->getConsulta($sql);
																	// print_r("<p>Consulta existencias</p>");
																	// print_r("<pre>");
																	// print_r($existencias);
																	// print_r("</pre>");

																	// Campo cantidad
																	if (limpiaTexto($data[4]) <= $existencias["rowsData"][0]["CUANTOS"] ) {
																		// campo fecha de vencimiento
																		$fecha_vencimiento = $this->bodegas->validarFechaDow($this->bodegas->limpiaTexto($data[3]));

																		$info[$_count_row] = array(
																			"id_bodega" 		=> $_POST["id_bodega"], 
																			"id_material" 		=> $id_material, 
																			"delivery" 			=> limpiaTexto($data[1]), 
																			"shipment"			=> limpiaTexto($data[2]), 
																			"lote" 				=> limpiaTexto($data[3]), 
																			"fecha_vencimiento"	=> $fecha_vencimiento, 
																			"cantidad" 			=> limpiaTexto($data[4])
																		);
																	}
																	else{
																		$archivoValido = false;
																		$_msg_error.= "<p><strong>Error en fila $_count_row:</strong> La columna \"Cantidad\" es demasiada para las existencias en bodega.</p>";
																	}
																}
																else{
																	$archivoValido = false;
																	$_msg_error.= "<p><strong>Error en fila $_count_row:</strong> La columna \"Cantidad\" esta vacía.</p>";
																}	
															}
															else{
																$archivoValido = false;
																$_msg_error.= "<p><strong>Error en fila $_count_row:</strong> La columna \"lote\" esta vacía.</p>";
															}
														} else {
															$archivoValido = false;
															$_msg_error.= "<p><strong>Error en fila $_count_row:</strong> No se encontró registrado el material \"" . limpiaTexto($data[0]) . "\" en la lista de materiales.</p>";
														}
													}
													else{
														$archivoValido = false;
														$_msg_error.= "<p><strong>Error en fila $_count_row:</strong> La columna \"Shipment\" esta vacía.</p>";
													}
												}
												else{
													$archivoValido = false;
													$_msg_error.= "<p><strong>Error en fila $_count_row:</strong> La columna \"Delivery\" esta vacía.</p>";
												}
											}
											else{
												$archivoValido = false;
												$_msg_error.= "<p><strong>Error en fila $_count_row:</strong> La columna \"Código de Material\" esta vacía.</p>";
											}
										}
									}

									// se asigna el valor del primer registro de la siguinete fila
									$data[$i-1] = $arrayUltimaColumna[1];
								}
							}
						} else {
							$archivoValido = false;
							$_msg_error.= '<p>Archivo no válido para subir al servidor, debe ser un archivo plano con extensión <strong>\".csv\"</strong>.</p><p>Se recomienda descargar el formato para su diligenciamiento <a href="' . BASE_URL . 'public/files/formatoGeneracionSalida.csv" target="_blank"  alt="Formato Archivos"><img src="' . BASE_URL . 'public/img/excel_2013.png" height="20" width="20"></a></p>';
						}
					} else {
						$archivoValido = false;
						$_msg_error.= "Debe seleccionar un archivo válido para subir al servidor.";
					}
				}
				// print_r("<pre>");
				// print_r($info);
				// print_r("</pre>");

				// Si el archivo es correcto puede verificar si la informacion no se encuentra en la base de datos 
				if($archivoValido){
					$contenidoValido = true;
					$_msg_error.= "<p><strong>Archivo diligenciado correctamente</strong>.</p>";
					foreach ($info as $key1 => $value1) {
						$Conect->setRegistro("cmx_material_bodega_salida", $value1);
						$_registro_exitoso++;
					}
					$_msg_error.= "<h4><strong>Se subieron $_registro_exitoso registros exitosamente.</strong></h4>";
					echo '
						<script language="javascript">
							setTimeout(function() { window.location="' . BASE_URL . 'bodegas/generar_despacho";  }, 3000);
						</script>
					';
				}
			} else {
				$_msg_error.= "Debe subir un archivo";
			}
		}else {
			$_msg_error.= "Debe seleccionar la bodega de salida del material a despachar.";
		}

		$_msg_color = "danger";
		if($contenidoValido){
			$_msg_color = "success";
		}
		echo '
			<script language="javascript">
				$(".nexos-messages").html(\'<div role="alert" class="alert alert-' . $_msg_color . ' alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button>' . $_msg_error . '</div></div>\');
			</script>
		';
	}

	/**** FUNCIONES DE SUBIDA DE ARCHIVO ****/
	function limpiaTexto($text){
		$text = filter_var(trim($text), FILTER_SANITIZE_STRING);
		//Filtro anti-XSS
		$caracteres_malos = array("<", ">", "\"", "'", "/", "<", ">", "'", "/");
		$caracteres_buenos = array("& lt;", "& gt;", "& quot;", "& #x27;", "& #x2F;", "& #060;", "& #062;", "& #039;", "& #047;");
		$consultaBusqueda = str_replace($caracteres_malos, $caracteres_buenos, $text);
		return $text;
	}


?>
