<?php
	$Conect = new Consultas;
	$_dbTable = "material_bodega"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";
	$_jsAjax = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

	$r = new Request();
	// print_r($r->getArgs());

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->bodegas) && count($this->bodegas)){

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_inventario = '
			<div class="row">
				<div class="col-sm-1"></div>
				<div class="col-sm-10">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th>Material</th>
									<th style="width:15%;">Almacenado</th>
									<th>Embalaje</th>
									<th style="width:10%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayBodega = $this->bodegas->getBodegas($r->getArgs()[0]);
		// print_r("<pre>");
		// print_r($arrayBodega);
		// print_r("</pre>");

		$arrayMateriales_clientes = $this->bodegas->getMaterialInvenatrio($r->getArgs()[0]);
		// print_r("<pre>");
		// print_r($arrayMateriales_clientes);
		// print_r("</pre>");

		if($arrayMateriales_clientes['rowsData']){
			foreach ($arrayMateriales_clientes['rowsData'] as $key => $value) {

				/******** SE CREAN POPUPS DE INFORMACION DEL MATERIAL DE ENVIO ********/
				// INFORMACIÓN GENERAL DEL MATERIAL - Columna Materiales
				$info_contenido = '
					<div class="panel panel-border panel-contrast">
						<div class="panel-heading panel-heading-contrast">
							' . $value["descripcion"] . ' 
							<span class="panel-subtitle">Código - ' . $value["codigo"] . '</span>
							<span class="panel-subtitle">' . $value["detalle"] . '</span>
						</div>
					</div>
					<table class="table">
						<tbody>
							<tr>
								<td class="cell-detail">
									<div class="col-sm-2">
										<span>EAN13</span>
										<span class="cell-detail-description">' . $value["ean13"] . '</span>
									</div>
									<div class="col-sm-2">
										<span>Subpatida</span>
										<span class="cell-detail-description">' . $value["subpartida"] . '</span>
									</div>
									<div class="col-sm-3">
										<span>Código Antiguo</span>
										<span class="cell-detail-description">' . $value["codigo_antiguo"] . '</span>
									</div>
									<div class="col-sm-3">
										<span>Código Corto</span>
										<span class="cell-detail-description">' . $value["codigo_corto"] . '</span>
									</div>
									<div class="col-sm-2">
										<span>Consolidable</span>
										<span class="cell-detail-description">' . $value["consolidable"] . '</span>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-2">
											<span>Codigo UN</span>
											<span class="cell-detail-description">' . $value["codigoUN"] . '</span>
										</div>
										<div class="col-sm-1">
											<img src="' . BASE_URL . 'public/img/riesgos/' . $value["url"] . '" height="50" width="50">
										</div>
										<div class="col-sm-2">
											<span>Riesgo</span>
											<span class="cell-detail-description">' . $value["numero_riesgo"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Nombre del Riesgo</span>
											<span class="cell-detail-description">' . $value["nom_riesgo_material"] . '</span>
										</div>
										<div class="col-sm-4">
											<span>Descripción del Riesgo</span>
											<span class="cell-detail-description">' . $value["DESCRIPCION_RIESGO"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-1"></div>
										<div class="col-sm-2">
											<span>Peso Unitario Bruto</span>
											<span class="cell-detail-description">' . $value["peso_unitario_bruto"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Peso Unitario Neto</span>
											<span class="cell-detail-description">' . $value["peso_unitario_neto"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Largo</span>
											<span class="cell-detail-description">' . $value["largo"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Alto</span>
											<span class="cell-detail-description">' . $value["alto"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Ancho</span>
											<span class="cell-detail-description">' . $value["ancho"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-2">
											<span>Volumen Terrestre</span>
											<span class="cell-detail-description">' . $value["volumen_terrestre"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Volumen Aéreo</span>
											<span class="cell-detail-description">' . $value["volumen_aereo"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Cupo Autorizado</span>
											<span class="cell-detail-description">' . $value["cupo_autorizado"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Cantidad Contenido Interno</span>
											<span class="cell-detail-description">' . $value["cant_contenido_interno"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Vida Útil</span>
											<span class="cell-detail-description">' . $value["vida_util"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-3">
											<span>Familia</span>
											<span class="cell-detail-description">' . $value["nom_familia"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Categoría</span>
											<span class="cell-detail-description">' . $value["nom_categoria"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Grupo</span>
											<span class="cell-detail-description">' . $value["grupo"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Sub-grupo</span>
											<span class="cell-detail-description">' . $value["sub_grupo"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-3">
											<span>Especificación</span>
											<span class="cell-detail-description">' . $value["especificacion"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Característica</span>
											<span class="cell-detail-description">' . $value["caracteristica"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Talla</span>
											<span class="cell-detail-description">' . $value["talla"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Color</span>
											<span class="cell-detail-description">' . $value["color"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail"></td>
							</tr>
						</tbody>
					</table>
				';
				$vista.= $info->_bootstrap_modal_dialog("info_" . $value[0] , "Información del Material" , $info_contenido );
				/******** FIN SE CREAN POPUPS DE INFORMACION DEL MATERIAL ********/

				/******** SE CREAN POPUPS DE INFORMACION DE UBICACION DEL MATERIAL ********/
				// INFORMACIÓN GENERAL DEL MATERIAL - Columna Materiales
				$arrayUbicacion_material = $this->bodegas->getUbicacionMaterial($value[0]);
				// print_r("<pre>");
				// print_r($arrayUbicacion_material);
				// print_r("</pre>");

				$table_ubicacion_material = '
					<table id="table" class="table table-striped table-hover">
						<thead>
							<tr class="nexos-encabezado">
								<th>Ubicación</th>
								<th>Lote</th>
								<th>Vencimiento</th>
							</tr>
						</thead>
						<tbody>
				';

				if($arrayUbicacion_material['rowsNum'] > 0 ){
					foreach ($arrayUbicacion_material['rowsData'] as $key1 => $value1) {
						$table_ubicacion_material.= '<tr>';
						$table_ubicacion_material.= '<td class="cell-detail">' . $value1["UBICACION"] . '</td>';
						$table_ubicacion_material.= '<td class="cell-detail">' . $value1["lote"] . '</td>';
						$table_ubicacion_material.= '<td class="cell-detail">' . $value1["fecha_vencimiento"] . '</td>';
						$table_ubicacion_material.= '</tr>';
					}
				}
				else{
						$table_ubicacion_material.= '<tr>';
						$table_ubicacion_material.= '<td class="cell-detail text-center" colspan="3">Material no se encuentra ubicado</td>';
						$table_ubicacion_material.= '</tr>';
				}

				$table_ubicacion_material.= '
						</tbody>
					</table>
				';

				$info_contenido = '
					<div class="panel panel-border panel-contrast">
						<div class="panel-heading panel-heading-contrast">
							' . $value["descripcion"] . ' 
							<span class="panel-subtitle">Código - ' . $value["codigo"] . '</span>
							<span class="panel-subtitle">' . $value["detalle"] . '</span>
						</div>
					</div>
					%table_info%
				';
				$info_contenido = str_replace("%table_info%", $table_ubicacion_material, $info_contenido);

				$vista.= $info->_bootstrap_modal_dialog("info_1_" . $value[0] , "Ubicación del Material" , $info_contenido );
				/******** FIN SE CREAN POPUPS DE INFORMACION DE UBICACION DEL MATERIAL ********/

				// Se maqueta contenido de la tabla 
				$table_inventario.= '<tr>';
				// Columna Materiales
				$table_inventario.= '
					<td data-toggle="modal" data-target="#info_' . $value[0] . '" class="cell-detail md-trigger">
						<span>' . $value["descripcion"] . '</span>
						<span class="cell-detail-description">' . $value["codigo"] . '</span>
					</td>
				';

				// Columna de Cantidad de embalajes del despacho 
				$_porcentaje = 0;
				if ($value["DISPONIBLE"] > 0) {
					$_porcentaje = ceil(($value["DISPONIBLE"] * 100) / $value["cantidad"]);
				}
				$table_inventario.= "
					<td class='milestone'>
						<span class='version'>" . $value["DISPONIBLE"] . " / " . $value["cantidad"] . "</span>
						<div class='progress'><div style='width: " . $_porcentaje . "%' class='progress-bar progress-bar-primary'></div>
						</div>
					</td>
				";

				// Columna datos de cantiidad y embalaje del material
				$table_inventario.= '
					<td class="cell-detail">
						<span>' . $value["nom_unidad_empaque"] . ' x ' . $value["unidades_x_embalaje"] . ' unid</span>
						<span class="cell-detail-description">' . $value["nom_unidad_presentacion"] . ' x ' . $value["cant_contenido_interno"] . ' ' . $value["nom_unidad_medida"] . '</span>
					</td>
				';

				// se asigna la columna de acciones
				$table_inventario.='
					<td class="actions">
						<a href="' . BASE_URL . 'bodegas/log_material/' . $value[0] . '/' . $r->getArgs()[0] . '" class="hint--top-left" data-hint="Ver Movimientos"><span class="icon mdi mdi-assignment-check"></span></a>
						<a href="' . BASE_URL . 'bodegas/detalle_inventario/' . $value[0] . '/' . $r->getArgs()[0] . '" class="hint--top-left" data-hint="Ver Detalles"><span class="icon mdi mdi-eye"></span></a>
					</td>
				';
				
				$table_inventario.= '</tr>';
			}
		}

		$table_inventario.= '
							</tbody>
						</table>
					</div>
				</div>
			</div>
		';
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/

	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Inventario Bodega - ' . $arrayBodega["rowsData"][0]["nombre"] . '
				<div class="tools">
					<a href="' . BASE_URL . 'bodegas/lista_bodegas/" class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>
				</div>
				<span class="panel-subtitle">Se muestra los materiales existentes en la bodega.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';

	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.formElements();
			});
			%js-ajax%
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%js-ajax%" , $_jsAjax , $vista);
	$vista = str_replace("%content%" , $table_inventario , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
