<?php
	$Conect = new Consultas;
	$_dbTable = "material_bodega"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";
	$_jsAjax = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

	$r = new Request();
	// print_r($r->getArgs());

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->bodegas) && count($this->bodegas)){

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_materiales_clientes = '
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th>Fecha</th>
									<th>Usuario</th>
									<th>Acción</th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayMaterial = $this->materiales_clientes->getMaterial($r->getArgs()[0]);
		// print_r("<pre>");
		// print_r($arrayMaterial);
		// print_r("</pre>");

		$arrayMateriales_clientes = $this->bodegas->getLogMatrial($r->getArgs()[0]);
		// print_r("<pre>");
		// print_r($arrayMateriales_clientes);
		// print_r("</pre>");

		if($arrayMateriales_clientes['rowsData']){
			foreach ($arrayMateriales_clientes['rowsData'] as $key => $value) {
				// Se maqueta contenido de la tabla 
				$table_materiales_clientes.= '<tr>';
				// Columna Fecha
				$table_materiales_clientes.= '
					<td class="cell-detail md-trigger">
						<span>' . $value["fecha_hora"] . '</span>
					</td>
				';
				// Columna Usuario
				$table_materiales_clientes.= '
					<td class="user-avatar">
						<img src="' . BASE_URL . 'public/img/users/' . $value["url_avatar"] . '" alt="' . $value["nom_usuario"] . '">' . $value["nom_usuario"] . '
					</td>
				';
				// Columna accion
				$table_materiales_clientes.= '
					<td class="cell-detail">
						<span>' . $value["tipo_movimiento"] . '</span>
					</td>
				';
				
				$table_materiales_clientes.= '</tr>';
			}
		}

		$table_materiales_clientes.= '
							</tbody>
						</table>
					</div>
				</div>
			</div>
		';
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/

	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Log Movimientos Material - ' . $arrayMaterial["rowsData"][0]["descripcion"] . '
				<div class="tools">
					<a href="' . BASE_URL . 'bodegas/inventario/' . $r->getArgs()[1] . '" class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>
				</div>
				<span class="panel-subtitle">Se muestra los movimientos generados de un material.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';

	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.formElements();
			});
			%js-ajax%
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%js-ajax%" , $_jsAjax , $vista);
	$vista = str_replace("%content%" , $table_materiales_clientes , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
