<?php
	$Conect = new Consultas;
	$_dbTable = "ingresos"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";
	$_jsAjax = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
	$ssn_id_bodega = $_SESSION["usuario"]["id_bodega"];

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->bodegas) && count($this->bodegas)){

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_view = '
			<div class="row">
				<div class="col-sm-12">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width: 4%;"># Novedad</th>
									<th style="width: 3%;">Cantidad</th>
									<th>Bodega</th>
									<th>Material</th>
									<th>Novedad</th>
									<th style="width: 20%;">Registrado por</th>
									<th style="width: 5%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayNovedades = $this->bodegas->getNovedades($ssn_id_cliente , $ssn_id_bodega);
		// print_r("<pre>");
		// print_r($arrayNovedades);
		// print_r("</pre>");
		if ($arrayNovedades['rowsData']) {
			foreach ($arrayNovedades['rowsData'] as $key => $value) {
				// Se maqueta contenido de la tabla 
				$table_view.= '<tr>';

				// Columna # Novedad
				$table_view.= '
					<td class="cell-detail">
						<span>' . $value["numero_novedad"] . '</span>
						<span class="cell-detail-description">' . date('Y-m-d', $value["numero_novedad"]) . '</span>
					</td>
				';

				// Columna Cantidad
				$table_view.= '
					<td class="cell-detail">
						<span class="label label-default">' . $value["EMBALAJES_AFECTADOS"] . '</span>
					</td>
				';

				// Columna de bodega 
				$table_view.= '
					<td class="cell-detail">
						<span>' . $value["BODEGA"] . '</span>
						<span class="cell-detail-description">' . $value["DOC_BODEGA"] . '-' . $value["DIGIT_BODEGA"] . '</span>
					</td>
				';

				// Columna de material
				$table_view.= '
					<td class="cell-detail">
						<span>' . $value["codigo"] . ' - ' . $value["descripcion"] . '</span>
						<span class="cell-detail-description">Lote - ' . $value["lote"] . '</span>
					</td>
				';

				// Columna Novedad
				$table_view.= '
					<td class="cell-detail">
						<span>' . $value["nombre"] . '</span>
						<span class="cell-detail-description">' . $value["detalle"] . '</span>
					</td>
				';

				// Columna Quien registra
				$table_view.= '
					<td class="user-avatar cell-detail user-info">
						<img src="' . BASE_URL . $value["URL_AVATAR"] . '" alt="Avatar">
						<span>' . $value["nom_usuario"] . '</span>
						<span class="cell-detail-description">' . $value["nombre_perfil"] . '</span>
					</td>
				';

				// Columna de acciones
				$table_view.= '
					<td class="actions">
						<a href="' . BASE_URL . 'bodegas/detalle_novedad/' . $value["numero_novedad"] . '" class="icon hint--top-left" data-hint="Ver Estibas Descargadas"><span class="mdi mdi-eye"></span></a>
					</td>
				';

				$table_view.= '</tr>';
			}

			$table_view.= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
		}
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/

	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Listado de Novedades de Mercancía 
				<div class="tools">
				</div>
				<span class="panel-subtitle">Listado de los materiales que han tenido algún tipo de novedad al momento de ser recibidos en la bodega.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
			%js-ajax%
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%js-ajax%" , $_jsAjax , $vista);
	$vista = str_replace("%content%" , $table_view , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
