<?php
	$Conect = new Consultas;
	$_dbTable = "traslados"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";
	$_jsAjax = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->bodegas) && count($this->bodegas)){

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_traslados = '
			<div class="row">
				<div class="col-sm-1"></div>
				<div class="col-sm-10">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width: 3%;"></th>
									<th>Bodega</th>
									<th>Cliente</th>
									<th>Material</th>
									<th style="width: 12%;">Lote</th>
									<th style="width: 7%;">Origen</th>
									<th style="width: 7%;">Destino</th>
									<th style="width: 3%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayDescargas = $this->bodegas->getTraslados();
		// print_r("<pre>");
		// print_r($arrayDescargas);
		// print_r("</pre>");
		if ($arrayDescargas['rowsData']) {
			foreach ($arrayDescargas['rowsData'] as $key => $value) {
				/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
				$col_action = '<td class="actions"></td>';	
				switch ($value["ESTADO_TRASLADO"]) {
					case '0':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-danger">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["ESTADO_TRASLADO"] . '</span>
							</td>
						';

						$_popupHabilita = $alert->_alert_modal_mod_habilita( $value[0] , "Realmente desea desbloquear la reubicación?" , $_dbTable , 2 );
						$vista.= $_popupHabilita[0];
						$_jsScripts.=$_popupHabilita[1];

						// se asigna contenido de la columna de acciones
						$col_action = '
							<td class="actions">
								<a href="#" class="icon hint--top-left" data-hint="Desbloquear"><span id="#habilita_' . $value[0] . '" data-toggle="modal" data-target="#habilita_' . $value[0] . '" class="icon mdi mdi-check-circle"></span></a>
							</td>
						';

						break;

					case '2':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-warning">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["ESTADO_TRASLADO"] . '</span>
							</td>
						';

						break;

				}
				/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

				// INFORMACIÓN GENERAL DE LA BODEGA
				$arrayBodega = $this->bodegas->getBodegas($value["id_bodega"]);
				// print_r("<pre>");
				// print_r($arrayBodega);
				// print_r("</pre>");

				/******** SE CREAN POPUPS DE INFORMACION DEL MATERIAL ********/
				// INFORMACIÓN DE LA BODEGA
				$info_contenido = '
					<div class="panel panel-border panel-contrast">
						<div class="panel-heading panel-heading-contrast">
							' . $arrayBodega["rowsData"][0]["nombre"] . '
							<span class="panel-subtitle">
								' . $arrayBodega["rowsData"][0]["sigla"] . '
							</span>
							<span class="panel-subtitle">
								' . $arrayBodega["rowsData"][0]["direccion"] . ' - ' . $arrayBodega["rowsData"][0]["municipio"] . ' (' . $arrayBodega["rowsData"][0]["depto"] . ' - ' . $arrayBodega["rowsData"][0]["pais"] . ') 
							</span>
						</div>
					</div>
					<strong>Información General</strong>
					<table class="table">
						<tbody>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-3">
											<span>Código Postal</span>
											<span class="cell-detail-description">' . $arrayBodega["rowsData"][0]["codigo_postal"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Atención</span>
											<span class="cell-detail-description">' . $arrayBodega["rowsData"][0]["dias_atencion"] . ' (' . $arrayBodega["rowsData"][0]["horario_atencion"] . ')</span>
										</div>
										<div class="col-sm-6">
											<span>Como llegar</span>
											<span class="cell-detail-description">' . $arrayBodega["rowsData"][0]["como_llegar"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-12">
											<span>Actividad</span>
											<span class="cell-detail-description">' . $arrayBodega["rowsData"][0]["descripcion_actividad"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
								</td>
							</tr>
						</tbody>
					</table>
				';
				$vista.= $info->_bootstrap_modal_dialog("info_1_" . $value[0] , "Información General Bodega" , $info_contenido );

				// INFORMACIÓN GENERAL DEL MATERIAL - Columna Materiales
				$info_contenido = '
					<div class="panel panel-border panel-contrast">
						<div class="panel-heading panel-heading-contrast">
							' . $value["descripcion"] . ' (' . $value["CLIENTE"] . ')
							<span class="panel-subtitle">Código - ' . $value["codigo"] . '</span>
							<span class="panel-subtitle">' . $value["detalle"] . '</span>
						</div>
					</div>
					<table class="table">
						<tbody>
							<tr>
								<td class="cell-detail">
									<div class="col-sm-2">
										<span>EAN13</span>
										<span class="cell-detail-description">' . $value["ean13"] . '</span>
									</div>
									<div class="col-sm-2">
										<span>Subpatida</span>
										<span class="cell-detail-description">' . $value["subpartida"] . '</span>
									</div>
									<div class="col-sm-3">
										<span>Código Antiguo</span>
										<span class="cell-detail-description">' . $value["codigo_antiguo"] . '</span>
									</div>
									<div class="col-sm-3">
										<span>Código Corto</span>
										<span class="cell-detail-description">' . $value["codigo_corto"] . '</span>
									</div>
									<div class="col-sm-2">
										<span>Consolidable</span>
										<span class="cell-detail-description">' . $value["consolidable"] . '</span>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-2">
											<span>Codigo UN</span>
											<span class="cell-detail-description">' . $value["codigoUN"] . '</span>
										</div>
										<div class="col-sm-1">
											<img src="' . BASE_URL . 'public/img/riesgos/' . $value["url"] . '" height="50" width="50">
										</div>
										<div class="col-sm-2">
											<span>Riesgo</span>
											<span class="cell-detail-description">' . $value["numero_riesgo"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Nombre del Riesgo</span>
											<span class="cell-detail-description">' . $value["nom_riesgo_material"] . '</span>
										</div>
										<div class="col-sm-4">
											<span>Descripción del Riesgo</span>
											<span class="cell-detail-description">' . $value["DESCRIPCION_RIESGO"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-1"></div>
										<div class="col-sm-2">
											<span>Peso Unitario Bruto</span>
											<span class="cell-detail-description">' . $value["peso_unitario_bruto"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Peso Unitario Neto</span>
											<span class="cell-detail-description">' . $value["peso_unitario_neto"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Largo</span>
											<span class="cell-detail-description">' . $value["largo"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Alto</span>
											<span class="cell-detail-description">' . $value["alto"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Ancho</span>
											<span class="cell-detail-description">' . $value["ancho"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-2">
											<span>Presentación</span>
											<span class="cell-detail-description">' . $value["nom_unidad_presentacion"] . ' x ' . $value["cant_contenido_interno"] . ' ' . $value["nom_unidad_medida"] . ' .</span>
										</div>
										<div class="col-sm-2">
											<span>Embalaje</span>
											<span class="cell-detail-description">' . $value["nom_unidad_empaque"] . ' x ' . $value["unidades_x_embalaje"] . ' Unid.</span>
										</div>
										<div class="col-sm-2">
											<span>Unidades por Tendido</span>
											<span class="cell-detail-description">' . $value["unidades_x_tendido"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Planchas por Estiba</span>
											<span class="cell-detail-description">' . $value["planchas_x_estiba"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Altura de la estiba</span>
											<span class="cell-detail-description">' . $value["altura_estiba"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Embalajes por estiba</span>
											<span class="cell-detail-description">' . ($value["unidades_x_tendido"] * $value["planchas_x_estiba"]) . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-2">
											<span>Volumen Terrestre</span>
											<span class="cell-detail-description">' . $value["volumen_terrestre"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Volumen Aéreo</span>
											<span class="cell-detail-description">' . $value["volumen_aereo"] . '</span>
										</div>
										<div class="col-sm-2">
											<span>Cupo Autorizado</span>
											<span class="cell-detail-description">' . $value["cupo_autorizado"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Cantidad Contenido Interno</span>
											<span class="cell-detail-description">' . $value["cant_contenido_interno"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Vida Útil</span>
											<span class="cell-detail-description">' . $value["vida_util"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-3">
											<span>Familia</span>
											<span class="cell-detail-description">' . $value["nom_familia"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Categoría</span>
											<span class="cell-detail-description">' . $value["nom_categoria"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Grupo</span>
											<span class="cell-detail-description">' . $value["grupo"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Sub-grupo</span>
											<span class="cell-detail-description">' . $value["sub_grupo"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-3">
											<span>Especificación</span>
											<span class="cell-detail-description">' . $value["especificacion"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Característica</span>
											<span class="cell-detail-description">' . $value["caracteristica"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Talla</span>
											<span class="cell-detail-description">' . $value["talla"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Color</span>
											<span class="cell-detail-description">' . $value["color"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail"></td>
							</tr>
						</tbody>
					</table>
				';
				$vista.= $info->_bootstrap_modal_dialog("info_2_" . $value[0] , "Información del Material" , $info_contenido );
				/******** FIN SE CREAN POPUPS DE INFORMACION DEL MATERIAL ********/

				// INFORMACIÓN LOS QR DEL EMBALAJE DE LA ESTIBA
				$info_contenido = '
					<div class="col-sm-1"></div>
					<div class="col-sm-10">
						<table id="table" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width: 5%;">QR</th>
									<th>Información</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								%table_info%
							</tbody>
						</table>
					</div>
					<div class="row"></div>
				';

				// Tomo los materiales del envio
				$arrayQrSalidas = $this->bodegas->getQrEmbalajes($value["ID_EMBALAJE"]);
				// print_r("<pre>");
				// print_r($arrayQrSalidas);
				// print_r("</pre>");

				$table_info = '';
				if ($arrayQrSalidas["rowsNum"] > 0) {
					foreach ($arrayQrSalidas["rowsData"] as $key1 => $value1) {
						$empaque = 'Estiba';
						if($arrayQrSalidas["rowsData"][$key1]["grupo"] == 0){
							$empaque = $arrayQrSalidas["rowsData"][$key1]["nom_unidad_empaque"];
						}
						$table_info.= '
							<tr>
								<td class="cell-detail">
									<div class="panel col-sm-12 text-center" style="border: 0px; height: 47mm; margin: 0; padding: 20px 0 0 0; border-radius: 0; box-shadow: none;">
										<span style="font-size: 6px;">
											<img src="' . BASE_URL . $arrayQrSalidas["rowsData"][$key1]["URL_QR"] . '" height="80" width="80"><br />
											Código - ' . $arrayQrSalidas["rowsData"][$key1]["codigo"] . '<br />
											Lote - ' . $arrayQrSalidas["rowsData"][$key1]["lote"] . ' (' . $arrayQrSalidas["rowsData"][$key1]["fecha_vencimiento"] . ')<br />
											' . $arrayQrSalidas["rowsData"][$key1]["descripcion"] . '<br />
											Present. - ' . $arrayQrSalidas["rowsData"][$key1]["nom_unidad_presentacion"] . ' x ' . $arrayQrSalidas["rowsData"][$key1]["cant_contenido_interno"] . ' ' . $arrayQrSalidas["rowsData"][$key1]["nom_unidad_medida"] . '
										</span>
									</div>
								</td>
								<td class="cell-detail">
									<span>
										Código - ' . $arrayQrSalidas["rowsData"][$key1]["codigo"] . '<br />
										Lote - ' . $arrayQrSalidas["rowsData"][$key1]["lote"] . ' (' . $arrayQrSalidas["rowsData"][$key1]["fecha_vencimiento"] . ')<br />
										' . $arrayQrSalidas["rowsData"][$key1]["descripcion"] . '<br />
										Present. - ' . $arrayQrSalidas["rowsData"][$key1]["nom_unidad_presentacion"] . ' x ' . $arrayQrSalidas["rowsData"][$key1]["cant_contenido_interno"] . ' ' . $arrayQrSalidas["rowsData"][$key1]["nom_unidad_medida"] . '
									</span>
								</td>
								<td class="cell-detail">
									<div class="col-sm-12">
										<span>' . $empaque . '</span>
									</div>
								</td>
							</tr>
						';
					}
				} else {
					$table_info = '
						<tr>
							<td class="cell-detail" colspan="4">
								<div class="col-sm-12 text-center">
									<span>El envío no tiene materiales asignados</span>
								</div>
							</td>
						</tr>
					';
					$arraySalidas["rowsNum"] = 0;
				}

				// Ingreso los materiales a la tabla
				$info_contenido = str_replace("%table_info%", $table_info , $info_contenido);

				$vista.= $info->_bootstrap_modal_dialog("info_3_" . $value[0] , "QR de Embalaje Material  - " . $value["descripcion"] , $info_contenido );


				// Tomo el QR de la ubicacion de origen
				$arrayQrUbicacionOrigen = $this->bodegas->getQrUbicacion($value["ORIGEN"]);
				// print_r("<pre>");
				// print_r($arrayQrUbicacionOrigen);
				// print_r("</pre>");

				// INFORMACIÓN UBICACIÓN DE ORIGEN - Columna origen
				$info_contenido = '
					<div class="panel panel-border panel-contrast">
						<div class="panel-body">
							<div class="col-sm-12 text-center">
								<span class="panel-subtitle">' . $arrayQrUbicacionOrigen["rowsData"][0]["UBICACION"] . '</span>
								<img src="' . BASE_URL . $arrayQrUbicacionOrigen["rowsData"][0]["QR_UBICACION"] . '" height="220" width="220">
								<span class="panel-subtitle">' . $arrayQrUbicacionOrigen["rowsData"][0]["tipo_ubicacion"] . '</span>
								<span class="panel-subtitle">' . $arrayQrUbicacionOrigen["rowsData"][0]["nombre"] . '</span>
							</div>
						</div>
					</div>
				';
				$vista.= $info->_bootstrap_modal_dialog("info_4_" . $value[0] , "Ubicación de Origen " . $arrayQrUbicacionOrigen["rowsData"][0]["UBICACION"] , $info_contenido );
				/******** FIN SE CREAN POPUPS DE INFORMACION DE LA UBICACION ORIGEN ********/

				// Tomo el QR de la ubicacion de destino
				$arrayQrUbicacionDestino = $this->bodegas->getQrUbicacion($value["DESTINO"]);
				// print_r("<pre>");
				// print_r($arrayQrUbicacionDestino);
				// print_r("</pre>");

				// INFORMACIÓN UBICACIÓN DE DESTINO - Columna destino
				$info_contenido = '
					<div class="panel panel-border panel-contrast">
						<div class="panel-body">
							<div class="col-sm-12 text-center">
								<span class="panel-subtitle">' . $arrayQrUbicacionDestino["rowsData"][0]["UBICACION"] . '</span>
								<img src="' . BASE_URL . $arrayQrUbicacionDestino["rowsData"][0]["QR_UBICACION"] . '" height="220" width="220">
								<span class="panel-subtitle">' . $arrayQrUbicacionDestino["rowsData"][0]["tipo_ubicacion"] . '</span>
								<span class="panel-subtitle">' . $arrayQrUbicacionDestino["rowsData"][0]["nombre"] . '</span>
							</div>
						</div>
					</div>
				';
				$vista.= $info->_bootstrap_modal_dialog("info_5_" . $value[0] , "Ubicación de Destino " . $arrayQrUbicacionDestino["rowsData"][0]["UBICACION"] , $info_contenido );
				/******** FIN SE CREAN POPUPS DE INFORMACION DE LA UBICACION DESTINO ********/


				// Se maqueta contenido de la tabla 
				$table_traslados.= '<tr>';

				// Columna de estado 
				$table_traslados.= $col_stasus;

				// Columna de bodega origen
				$table_traslados.= '
					<td data-toggle="modal" data-target="#info_1_' . $value[0] . '" class="cell-detail">
						<span class="hint--top-right" data-hint="Ver Bodega">' . $value["BODEGA"] . '</span>
						<span class="cell-detail-description">' . $value["DOC_BODEGA"] . '-' . $value["DIGIT_BODEGA"] . '</span>
					</td>
				';

				// Columna de cliente
				$table_traslados.= '
					<td data-toggle="modal" data-target="#info_' . $value[0] . '" class="cell-detail">
						<span>' . $value["CLIENTE"] . '</span>
						<span class="cell-detail-description">' . $value["DOC_CLIENTE"] . '-' . $value["DIGIT_CLIENTE"] . '</span>
					</td>
				';

				// Columna Material
				$table_traslados.= '
					<td data-toggle="modal" data-target="#info_2_' . $value[0] . '" class="cell-detail">
						<span>' . $value["descripcion"] . '</span>
						<span class="cell-detail-description">' . $value["codigo"] . '</span>
					</td>
				';

				// Columna Lote
				$table_traslados.= '
					<td data-toggle="modal" data-target="#info_3_' . $value[0] . '" class="cell-detail">
						<span>' . $value["lote"] . '</span>
						<span class="cell-detail-description">(' . $value["fecha_vencimiento"] . ')-' . $value["GRUPO_ESTIBA"] . '</span>
					</td>
				';

				// Columna Ubicación Origen
				$table_traslados.= '
					<td data-toggle="modal" data-target="#info_4_' . $value[0] . '" class="cell-detail">
						<span>' . $value["UBICACION_ORIGEN"] . '</span>
					</td>
				';

				// Columna Ubicación Destino
				$table_traslados.= '
					<td data-toggle="modal" data-target="#info_5_' . $value[0] . '" class="cell-detail">
						<span>' . $value["UBICACION_DESTINO"] . '</span>
					</td>
				';

				// se asigna la columna de acciones
				$table_traslados.= $col_action;

				$table_traslados.= '</tr>';
			}

			$table_traslados.= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
		}
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/

	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Listado de Traslado de Estibas
				<div class="tools">
				</div>
				<span class="panel-subtitle">Listado de las estibas que deben ser trasladadas a una posición de Saldo por concepto de que fue descompletada en un despacho o por ser reuqerido por el coordinador de la bodega.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
			%js-ajax%
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%js-ajax%" , $_jsAjax , $vista);
	$vista = str_replace("%content%" , $table_traslados , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
