<?php
	ini_set('max_execution_time', 240);
	$_dbTable = "bodegas"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";
	$_jsAjax = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

	$r = new Request();

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/

	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->bodegas) /* && count($this->bodegas) */){

		$table_configuracion_bodega_print = '';

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_configuracion_bodega = '
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover" data-page-length="100">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width:5%;"></th>
									<th style="width:10%;">Ubicación</th>
									<th style="width:7%;"></th>
									<th>Estiba Material</th>
									<th style="width:5%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayBodega = $this->bodegas->getBodegas($r->getArgs()[0]);

		$arrayConfiguracionBodega = $this->bodegas->getConfiguracionBodega($r->getArgs()[0]);

		if ($arrayConfiguracionBodega) {

			/****** SE CREA LISTADO DE QR DE LA BODEGA *****/
			foreach ($arrayConfiguracionBodega as $key => $value) {

				// Se setermia el estado de la ubicación 
				switch ($value["MATERIAL"]) {
					case 'Disponible':
						$_estado_ubicacion = "Disponible";
						$_color_estado = "success";
						break;
					
					default:
						$_estado_ubicacion = "Ocupado";
						$_color_estado = "danger";
						break;
				}

				$table_configuracion_bodega.= '
					<tr>
						<td class="nexos-txt-' . $_color_estado . '">
							<span class="mdi mdi-dot-circle icon"></span>
						</td>
						<td data-toggle="modal" data-target="#info_1_' . $value['id'] . '" class="cell-detail">
							<span>' . $value["UBICACION"] . '</span>
							<span class="cell-detail-description">' . $value["tipo_ubicacion"] . '</span>
						</td>
						<td class="cell-detail">
							<span class="label label-default">' . $value["CANTIDAD_ESTIBAS"] . '</span>
						</td>
						<td data-toggle="modal" data-target="#info_1" class="cell-detail">
							' . $value["MATERIAL"] . '
						</td>
						<td class="actions">
							<a href="' . BASE_URL . 'bodegas/detalle_ubicacion/' . $value['id'] . '" class="cell-detail  hint--top-left" data-hint="Ver información detallada"><span class="icon mdi mdi-eye"></span></a> 
						</td>
					</tr>
				';

				// Se llena el contenido de impresion 
				// Configuración stikers 40 x 40
				$table_configuracion_bodega_print.= "<div class='panel col-sm-3 text-center' style='border: none; margin-bottom: 15px; '><img src='" . BASE_URL . $value["URL_QR"] . "'  height='220' width='220'><span class='panel-subtitle'>" . $value["UBICACION"] . " (" . $value["tipo_ubicacion"] . ")</span><span class='panel-subtitle'>" . $value["nombre"] . "</div>";

			}
			$table_configuracion_bodega.= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
			/****** FIN DE SE CREA LISTADO DE QR DE LA BODEGA *****/
		}

	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/
	/*** FILTRO DE CREACIÓN DE UBICACIONES VIRTUALES ***/

	$arrayUbicacionVirtual = $this->bodegas->getUbicacionVirtual($r->getArgs()[0]);

	$_btn_ubicaciones_virtuales = '';
	if ($arrayUbicacionVirtual == 0) {
		$forms = '
			<form id="form_asigna">
				<input type="hidden" name="id_bodega" id_cliente value="' . $r->getArgs()[0] . '" class="form-control">

				<div class="panel panel-border panel-contrast">
					<div class="panel-heading panel-heading-contrast">
						Generar Ubicaciones Virtuales 
						<div class="tools">
							<a href="#" class="icon hint--top-left" data-hint="Aprobar Envío"><span class="icon mdi mdi-check-circle" id="asigna" data-dismiss="modal"></span></a>
						</div>
					</div>
				</div>
				<div class="form-group col-xs-4"></div>
				<div class="form-group col-xs-4">
					<label>*Cantidad de ubicaciones Virtuales:</label>
					<input type="number" name="ubicaciones_virtuales" id="ubicaciones_virtuales" value="" max="100" class="form-control">
					<label id="error_ubicaciones_virtuales"></label>
				</div>
				<div class="form-group col-xs-4"></div>
				<div class="row"></div>
			</form>
		';

		// Validacion JS de seleccion de materiales 
		$urlAsignaSalida = BASE_URL . 'libs/generar_ubicaciones_virtuales.php';
		// Validacion de contenido del formulario de creacion
		$_jsScripts.='
			<script type="text/javascript">
				var validar_ubicaciones_virtuales = "";

				$("#ubicaciones_virtuales").focus(function (){
					$("#ubicaciones_virtuales").keypress(function() {
						validarkeypress("#error_ubicaciones_virtuales", "#ubicaciones_virtuales");
					});
				});
				$("#ubicaciones_virtuales").focusin(function (){
					removerClaseserror("#error_ubicaciones_virtuales", "#ubicaciones_virtuales");
				});
				$("#ubicaciones_virtuales").focusout(function (){
					validar_ubicaciones_virtuales = validaciones("vacio" , $("#ubicaciones_virtuales").val() , "Ubicaciones Virtuales");
					if(validar_ubicaciones_virtuales != true){
						agregarClaseserror("#error_ubicaciones_virtuales", "#ubicaciones_virtuales", validar_ubicaciones_virtuales);
					}
					else{
						removerClaseserror("#error_ubicaciones_virtuales", "#ubicaciones_virtuales");
					}
				});


				var flagError = "";
				if ( validar_ubicaciones_virtuales != true ) {
					flagError = false;
				} else {
					flagError = true;
				}

				$(\'#asigna\').click(function () {
					var msgError = "";
					var deliveries =  $(\'#delivery_group\').val();

						var ubicaciones_virtuales =  $(\'#ubicaciones_virtuales\').val();
						if (!ubicaciones_virtuales || ubicaciones_virtuales == "" || ubicaciones_virtuales == 0) {
							msgError+= "<p>Para cerrar el envío debe diligenciar la cantidad de <strong>Ubicaciones Virtuales</strong>.</p>";
						}

					if (!msgError) {
						$.ajax({
							type		: 	"POST",
							cache		: 	false,
							url			: 	"' . $urlAsignaSalida . '",
							data		: 	$("#form_asigna").serialize(),
							beforeSend	: 	function(jqXHR, settings){
												$(".nexos-messages").html(\'<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' . BASE_URL . 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos</h4></div></div>\');
											},
							error: 			function(){
												console.log("error1...");
											},
							success		: 	function(data) {
												console.log(data);
												$(".nexos-messages").hide();
												$(".nexos-messages").html(\'<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong> Se han generado la orden con éxito.</div></div>\');
												$("#table1").hide();
												setTimeout(function() { location.reload(false);  }, 2000);

											}
						});
					} else {
						$(".nexos-messages").html(\'<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close-circle-o"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong> \' + msgError + \'</div></div>\');
					}
				});
			</script>
		';
		$_popupCrea = $form_crea->_message_title_modal("form_" , "Genrar Ubicaciones Virtuales" , $forms );
		$vista.= $_popupCrea;

		$_btn_ubicaciones_virtuales = '
			<a href="#" data-toggle="modal" data-target="#edita_form_" class="cell-detail hint--top-left" data-hint="Generar Ubicaciones Virtuales"><span class="icon mdi mdi-storage"></span></a>
		';
	}

	/*** FIN FILTRO DE CREACIÓN DE UBICACIONES VIRTUALES ***/
	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Ubicaciones Bodega - ' . $arrayBodega["nombre"] . '
				<div class="tools">
					<a href="' . BASE_URL . 'bodegas/index" class="cell-detail  hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a> 
					<a href="#" id="imprimir" class="cell-detail hint--top" data-hint="Imprimir QR´s"><span class="icon mdi mdi-print"></span></a>
					' . $_btn_ubicaciones_virtuales . '
				</div>
				<span class="panel-subtitle"></span>
			</div>
			<div class="panel-body xs-mt-15" style="padding-top: 0; margin-top: 0 !important;">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';

	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE IMPRESION PrintArea -->
		<script src="%root_file%js/jquery.PrintArea.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE IMPRESION PrintThis -->
		<script src="%root_file%js/printThis.js" type="text/javascript"></script>

	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$("#imprimir").click(function(){
				$("#prueba").printThis({
					importStyle: "block",
					header: "' . $table_configuracion_bodega_print . '",
				});
			});

			%js-ajax%
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%js-ajax%" , $_jsAjax , $vista);
	$vista = str_replace("%content%" , $table_configuracion_bodega , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
