<?php
	$Conect = new Consultas;
	$_dbTable = "salidas"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";
	$_jsAjax = "";

	// se definen las variables de session
	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
	$ssn_id_bodega = $_SESSION["usuario"]["id_bodega"];

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->bodegas) && count($this->bodegas)){

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_alistamientos = '
			<div class="row">
				<div class="col-sm-1"></div>
				<div class="col-sm-10">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width: 5%;"></th>
									<th>Envío</th>
									<th>Destino</th>
									<th>Origen</th>
									<th style="width: 7%;">Estibas Alistadas</th>
									<th style="width: 7%;">Embalajes Alistados</th>
									<th style="width: 7%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayAlistamientos = $this->bodegas->getAlistamientos($ssn_id_cliente , $ssn_id_bodega);
		// print_r("<pre>");
		// print_r($arrayAlistamientos);
		// print_r("</pre>");
		if ($arrayAlistamientos['rowsData']) {
			foreach ($arrayAlistamientos['rowsData'] as $key => $value) {
				// INFORMACIÓN DE QR POR EMBALAJES					
				$arrayQrEmbalajes = $this->bodegas->getQrEmbalajesAlistamiento($value["numero_salida"]);
				// print_r("<pre>");
				// print_r($arrayQrEmbalajes);
				// print_r("</pre>");

				$_btn_qr_embalajes = '';
				if ($arrayQrEmbalajes) {
					$_btn_qr_embalajes = '
						<a href="#" data-toggle="modal" data-target="#info_embalaje_' . $value[0] . '" class="cell-detail  hint--top-left"  data-hint="QR Embalajes"><span class="icon mdi mdi-border-clear"></span></a> 
					';
					$info_contenido = '
						<div class="panel panel-border panel-contrast">
							<div class="panel-heading panel-heading-contrast">
								Imprimir
								<div class="tools">
									<a href="#" id="imprimir_1_' . $value[0] . '" class="cell-detail hint--top" data-hint="Imprimir"><span class="icon mdi mdi-print"></span></a>
								</div>
							</div>
							<div class="panel-body" id="contenido_1" style="padding-top: 0;">
					';
					foreach ($arrayQrEmbalajes["rowsData"] as $key1 => $value1) {
						$info_contenido.= '
							<div class="panel col-sm-3 text-center" style="border: 0px; height: 47mm; margin: 0; padding: 20px 0 0 0; border-radius: 0; box-shadow: none;">
								<span style="font-size: 6px;">
									<img src="' . BASE_URL . $value1["URL_QR"] . '" height="80" width="80"><br />
									Código - ' . $value1["codigo"] . '<br />
									Lote - ' . $value1["LOTE"] . ' (' . $value1["fecha_vencimiento"] . ')<br />
									' . $value1["descripcion"] . '<br />
									Present. - ' . $value1["nom_unidad_presentacion"] . ' x ' . $value1["cant_contenido_interno"] . ' ' . $value1["nom_unidad_medida"] . '
								</span>
							</div>
						';
					}
					$info_contenido.= '
							</div>
						</div>
						<div class="row"></div>
					';
					$_jsScripts.='
						<script type="text/javascript">
							$("#imprimir_1_' . $value[0] . '").click(function (){
								$("div#contenido_1").printArea({
									popWd:	30,
									popHt: 	60
								});
							})
						</script>
					';
					$vista.= $info->_bootstrap_modal_dialog("info_embalaje_" . $value[0] , "QR Embalajes - Salida - " . $value["numero_salida"] , $info_contenido );
				}
				/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
				switch ($value["estado"]) {
					case '0':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-danger">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

						$_popupHabilita = $alert->_alert_modal_mod_habilita( $value[0] , "Realmente desea desbloquear el alistamiento <strong>" . $value["numero_salida"] . "</strong>?" , $_dbTable , 1 );
						$vista.= $_popupHabilita[0];
						$_jsScripts.=$_popupHabilita[1];

						$col_action = '
							<td class="actions">
								<a href="#" class="icon hint--top-left" data-hint="Desbloquear"><span id="#habilita_' . $value[0] . '" data-toggle="modal" data-target="#habilita_' . $value[0] . '" class="icon mdi mdi-check-circle"></span></a>
								' . $_btn_qr_embalajes . '
								<a href="' . BASE_URL . 'bodegas/ver_material_alistamiento/' . $value["numero_salida"] . '" class="icon hint--top-left" data-hint="Ver Materiales del Despacho"><span class="mdi mdi-eye"></span></a>
							</td>
						';

						break;

					case '1':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-warning">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

						$col_action = '
							<td class="actions">
								' . $_btn_qr_embalajes . '
								<a href="' . BASE_URL . 'bodegas/ver_material_alistamiento/' . $value["numero_salida"] . '" class="icon hint--top-left" data-hint="Ver Materiales del Despacho"><span class="mdi mdi-eye"></span></a>
							</td>
						';

						break;
				}
				/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

				// INFORMACIÓN GENERAL DE LA BODEGA
				$arrayBodega = $this->bodegas->getBodegas($value["ID_BODEGA"]);
				// print_r("<pre>");
				// print_r($arrayBodega);
				// print_r("</pre>");

				$info_contenido = '
					<div class="panel panel-border panel-contrast">
						<div class="panel-heading panel-heading-contrast">
							' . $arrayBodega["rowsData"][0]["nombre"] . '
							<span class="panel-subtitle">
								' . $arrayBodega["rowsData"][0]["sigla"] . '
							</span>
							<span class="panel-subtitle">
								' . $arrayBodega["rowsData"][0]["direccion"] . ' - ' . $arrayBodega["rowsData"][0]["municipio"] . ' (' . $arrayBodega["rowsData"][0]["depto"] . ' - ' . $arrayBodega["rowsData"][0]["pais"] . ') 
							</span>
						</div>
					</div>
					<strong>Información General</strong>
					<table class="table">
						<tbody>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-3">
											<span>Código Postal</span>
											<span class="cell-detail-description">' . $arrayBodega["rowsData"][0]["codigo_postal"] . '</span>
										</div>
										<div class="col-sm-3">
											<span>Atención</span>
											<span class="cell-detail-description">' . $arrayBodega["rowsData"][0]["dias_atencion"] . ' (' . $arrayBodega["rowsData"][0]["horario_atencion"] . ')</span>
										</div>
										<div class="col-sm-6">
											<span>Como llegar</span>
											<span class="cell-detail-description">' . $arrayBodega["rowsData"][0]["como_llegar"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
									<div class="row">
										<div class="col-sm-12">
											<span>Actividad</span>
											<span class="cell-detail-description">' . $arrayBodega["rowsData"][0]["descripcion_actividad"] . '</span>
										</div>
									</div>
								</td>
							</tr>
							<tr>
								<td class="cell-detail">
								</td>
							</tr>
						</tbody>
					</table>
				';
				$vista.= $info->_bootstrap_modal_dialog("info_1_" . $value["numero_salida"] , "Información General Bodega" , $info_contenido );

				// INFORMACIÓN LOS QR NECESARIOS PARA SACAR EL MATERIAL
				$info_contenido = '
					<div class="col-sm-1"></div>
					<div class="col-sm-10">
						<table id="table" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width: 5%;">QR</th>
									<th>Información</th>
									<th></th>
									<th style="width: 15%;">Ubicación</th>
								</tr>
							</thead>
							<tbody>
								%table_info%
							</tbody>
						</table>
					</div>
					<div class="row"></div>
				';

				// Tomo los materiales del envio
				$arrayQrAlistamientos = $this->bodegas->getQrAlistamiento($value["numero_salida"]);
				// print_r("<pre>");
				// print_r($arrayQrAlistamientos);
				// print_r("</pre>");

				$table_info = '';
				if ($arrayQrAlistamientos["rowsNum"] > 0) {
					foreach ($arrayQrAlistamientos["rowsData"] as $key1 => $value1) {
						$empaque = 'Estiba';
						if($arrayQrAlistamientos["rowsData"][$key1]["grupo"] == 0){
							$empaque = $arrayQrAlistamientos["rowsData"][$key1]["nom_unidad_empaque"];
						}
						$table_info.= '
							<tr>
								<td class="cell-detail">
									<div class="panel col-sm-12 text-center" style="border: 0px; height: 47mm; margin: 0; padding: 20px 0 0 0; border-radius: 0; box-shadow: none;">
										<span style="font-size: 6px;">
											<img src="' . BASE_URL . $arrayQrAlistamientos["rowsData"][$key1]["URL_QR"] . '" height="80" width="80"><br />
											Código - ' . $arrayQrAlistamientos["rowsData"][$key1]["codigo"] . '<br />
											Lote - ' . $arrayQrAlistamientos["rowsData"][$key1]["LOTE"] . ' (' . $arrayQrAlistamientos["rowsData"][$key1]["fecha_vencimiento"] . ')<br />
											' . $arrayQrAlistamientos["rowsData"][$key1]["descripcion"] . '<br />
											Present. - ' . $arrayQrAlistamientos["rowsData"][$key1]["nom_unidad_presentacion"] . ' x ' . $arrayQrAlistamientos["rowsData"][$key1]["cant_contenido_interno"] . ' ' . $arrayQrAlistamientos["rowsData"][$key1]["nom_unidad_medida"] . '
										</span>
									</div>
								</td>
								<td class="cell-detail">
									<span>
										Código - ' . $arrayQrAlistamientos["rowsData"][$key1]["codigo"] . '<br />
										Lote - ' . $arrayQrAlistamientos["rowsData"][$key1]["LOTE"] . ' (' . $arrayQrAlistamientos["rowsData"][$key1]["fecha_vencimiento"] . ')<br />
										' . $arrayQrAlistamientos["rowsData"][$key1]["descripcion"] . '<br />
										Present. - ' . $arrayQrAlistamientos["rowsData"][$key1]["nom_unidad_presentacion"] . ' x ' . $arrayQrAlistamientos["rowsData"][$key1]["cant_contenido_interno"] . ' ' . $arrayQrAlistamientos["rowsData"][$key1]["nom_unidad_medida"] . '
									</span>
								</td>
								<td class="cell-detail">
									<div class="col-sm-12">
										<span>' . $empaque . '</span>
									</div>
								</td>
								<td class="cell-detail">
									<div class="col-sm-12">
										<span>' . $arrayQrAlistamientos["rowsData"][$key1]["UBICACION"] . '</span>
									</div>
								</td>
							</tr>
						';
					}
				} else {
					$table_info = '
						<tr>
							<td class="cell-detail" colspan="4">
								<div class="col-sm-12 text-center">
									<span>El envío no tiene materiales asignados</span>
								</div>
							</td>
						</tr>
					';
					$arraySalidas["rowsNum"] = 0;
				}

				// Ingreso los materiales a la tabla
				$info_contenido = str_replace("%table_info%", $table_info , $info_contenido);

				$vista.= $info->_bootstrap_modal_dialog("info_3_" . $value["numero_salida"] , "Materiales de Orden de Salida - " . $value["numero_salida"] , $info_contenido );


				// Se maqueta contenido de la tabla 
				$table_alistamientos.= '<tr>';

				// Columna de estado
				$table_alistamientos.= $col_stasus;

				// Columna Numero de envio
				$table_alistamientos.= '
					<td data-toggle="modal" data-target="#info_3_' . $value["numero_salida"] . '" class="cell-detail">
						<span class="hint--top-right" data-hint="Ver Materiales">' . $value["numero_salida"] . '</span>
					</td>
				';

				// Columna de destino
				$table_alistamientos.= '
					<td class="cell-detail">
						<span class="hint--top-right" data-hint="Ver Bodega">' . $value["destino"] . '</span>
					</td>
				';

				// Columna de bodega origen
				$table_alistamientos.= '
					<td data-toggle="modal" data-target="#info_1_' . $value["numero_salida"] . '" class="cell-detail">
						<span class="hint--top-right" data-hint="Ver Bodega">' . $value["BODEGA"] . '</span>
						<span class="cell-detail-description">' . $value["DOC_BODEGA"] . '-' . $value["DIGIT_BODEGA"] . '</span>
					</td>
				';

				// Columna de Cantidad de estibas del despacho 
				$_porcentaje = 0;
				if ($value["ESTIBAS_ALISTADAS"] > 0) {
					$_porcentaje = ceil(($value["ESTIBAS_ALISTADAS"] * 100) / $value["ESTIBAS_SOLICITADAS"]);
				}
				$table_alistamientos.= '
					<td class="milestone">
						<span class="version">' . $value["ESTIBAS_ALISTADAS"] . ' / ' . $value["ESTIBAS_SOLICITADAS"] . '</span>
						<div class="progress">
							<div style="width: ' . $_porcentaje . '%" class="progress-bar progress-bar-primary"></div>
						</div>
					</td>
				';

				// Columna de Cantidad de embalajes del despacho 
				$_porcentaje = 0;
				if ($value["EMBALAJES_ALISTADOS"] > 0) {
					$_porcentaje = ceil(($value["EMBALAJES_ALISTADOS"] * 100) / $value["EMBALAJES_SOLICITADOS"]);
				}
				$table_alistamientos.= '
					<td class="milestone">
						<span class="version">' . $value["EMBALAJES_ALISTADOS"] . ' / ' . $value["EMBALAJES_SOLICITADOS"] . '</span>
						<div class="progress">
							<div style="width: ' . $_porcentaje . '%" class="progress-bar progress-bar-primary"></div>
						</div>
					</td>
				';

				// se asigna la columna de acciones
				$table_alistamientos.=$col_action;
				
				$table_alistamientos.= '</tr>';
			}

			$table_alistamientos.= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
		}
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/

	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Listado de Materiales en Alistamiento
				<div class="tools">
				</div>
				<span class="panel-subtitle">Listado del material que se encuentran para ser alistados y están almacenados en una ubicación.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE IMPRESION PrintArea -->
		<script src="%root_file%js/jquery.PrintArea.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE IMPRESION PrintThis -->
		<script src="%root_file%js/printThis.js" type="text/javascript"></script>

	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
			%js-ajax%
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%js-ajax%" , $_jsAjax , $vista);
	$vista = str_replace("%content%" , $table_alistamientos , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
