<?php
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
    //2. se definen variables para diseñar el contenido 
	$vista = '';
	$table_content='';


	$table_content ="
		<div class='row'>
		<div class='col-xs-12 col-sm-12 col-md-12 col-lg-12'>
			<div class='col-md-4 colsm-4'>
				<label>Fecha Inicial</label>
				<input type='date' id='fechaini' class='form-control input-sm'>
			</div>
			<div class='col-md-4 colsm-4'>
				<label>Fecha Final</label>
				<input type='date' id='fechafinal' class='form-control input-sm'>
			</div>
			<div class='col-md-4 col-sm-4'>
				<label></label>
				<button id='buscar'  class='btn btn-sm btn btn-primary'>Buscar</button>
			</div>
		</div>
	</div>
	";

	$table_content.='
	 <div id="la_tabla">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12">
					<div class="table-responsive noSwipe">
						<input type="hidden" id="flag_popup">
						<table id="table1" class="table table-striped table-hover table-fw-widget" data-page-length="100">
							<thead>
								<tr class="nexos-encabezado">
									<th class="col-xs-1 col-sm-1 col-md-1">#</th>
									<th class="col-xs-1 col-sm-1 col-md-1">Usuario <br> Responsable</th>
									<th>Cant. Estudios</th>
									<th>Cant. Aprobados</th>
									<th>estado</th>
									<th>Acciones</th>
								</tr>
							</thead>
								<tbody id="body_tabla">
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>	
';
					

	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Informe de Productividad
				<div class="tools">
					
				</div>
				<span class="panel-subtitle">Módulo para consultar la actividad .</span>
				<div class=" col-xs-12 col-sm-4 col-md-12">
					<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'" >
				</div>
			</div>
			<div class="panel-body">
				<div class="nexos-messages"></div>
				<div class="nexos-content">
					%content%
				</div>
				<div class="row">
				<div class="col-sm-12"></div>
				</div>
			</div>
		</div>
	'; 


	$vista.= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
		<link  rel="stylesheet" type="text/css" href="assets/lib/select2/css/select2.min.css"/>

		<link rel="stylesheet" type="text/css" src="%root_file%lib/assets/lib/select2/css/select2.min.css"/>


		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
		<script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.wizard();
			});
		</script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****///7.1   NO TOCARRRRRRRRR NUNCA
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_content , $vista); //variable $table_content sirve para crear adentro de esta todo lo que se va a mostrar en el cuerpo del conetenedor 
	echo $vista;

?>
<script type="text/javascript">
$(document).ready(function(){
	$("#buscar").click(function(){
		// alert('buscar Informe');
		var a=$("#fechaini").val();
		var b=$("#fechafinal").val();
		if(a=='' || b==''){
			alert('Por favor Ingrese una fecha en cada campo para generar su consulta');
		}else{

			var dato1={
				finicia:a,
				ffinal:b,
				action:'informe_productivo'
			};
			$("#body_tabla").html('');
			$.ajax({
				url:"http://localhost/mvcLuisMiguel/libs/seguridad_estudio2_ajax.php",
	 			type:'POST',
	 			data:dato1,
	 			dataType:'json',
	 			success: function(data){
	 				cont=0;
	 				capro=0;
	 				cnoapro=0;
	 				if(data.result){
	 					// alert('shdjshd');
	 					
	 					data.result.forEach(function(element,index){
	 						cont++;
	 							var numes=element.id_estudio;
	 					var boton_ver='';
	 						boton_ver='<button type="button"  class="btn btn-warning btn btn-sm mdi mdi-eye" id="btn_ver'+cont+'" data-toggle="modal"data-target="#verestudio"  data-id="'+numes+'"  >Consultar <br> Estudio</button>';
	 						var tesatdo=element.cestado;
	 						if(element.estado=='Aprobado' || element.estado=='Rechazado' || element.estado=='Pendiente'){
	 							capro=tesatdo+0;
	 						}

	 						var colstatus='';
	 						colstatus='';
	 						$_col_status='<td class="text" style="color:green;">'+
									'<center>'+
									'<span class="mdi mdi-dot-circle icon"></span>'+
									'</center>'+
								'</td>';

	 						

	 							$("#body_tabla").append('<tr>'+$_col_status+
	 						'<td>'+element.id_usuario+'</td>'+
	 						'<td>'+capro+'</td>'+
	 						'<td>'+element.cestado+'</td>'+
	 						'<td>'+element.estado+'</td>'+
	 						'<td></td>'+
	 						'</tr>');
	 						});

	 					
	 				}
	 			},
	 			error:function(jqXHR, textStatus, errorThrown){
	 				console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
	 			}	
	 		});	

		}
	});
});	


</script>