<?php

	$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
	$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
	$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
	$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
    //2. se definen variables para diseñar el contenido 
	$vista = '';
	$table_content='';
	$formulario='';
	 
	// if (isset($this->pedir_vehiculo) ) { 
	//  	$arrayPermisos = $this->pedir_vehiculo->permisosPerfil( $ssn_id_perfil , 80);
	//  	$_permisos = $arrayPermisos["rowsData"][0];
	// 	 $array = $this->pedir_vehiculo->getsolicitud();		
	// 	  $table_content .='
	// 	  <div class="row">
	// 	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	// 		<div class="col-md-3 col-sm-3">
	// 			<label>Fecha Inicial</label>
	// 			<input type="date" id="finicial" class="form-control input-sm">
	// 		</div>
	// 		<div class="col-md-3 col-sm-3">
	// 			<label>Fecha Final</label>
	// 			<input type="date" id="ffinal" class="form-control input-sm">
	// 		</div>
	// 		<div class="col-md-3 colsm-3">
	// 			<label>Filtrar</label>
	// 			<select id="filtro" class="form-control input-sm">
	// 				<option value="">Seleccione una opción</option>
	// 				<option value="t">Todos</option>
	// 				<option value="Aprobado">Aprobados</option>
	// 				<option value="Rechazado">Rechazado</option>
	// 				<option value="Pendiente">Pendiente</option>
	// 			</select>
	// 		</div>

	// 		<div class="col-md-3 col-sm-3">
	// 			<label></label>
	// 			<button id="buscar_historico" class="btn btn-sm btn btn-primary" >Buscar</button>
	// 		</div>
	// 	</div>
	// 	</div>


	// 	 <div id="la_tabla">
	// 		<div class="row">
	// 			<div class="col-xs-12 col-sm-12 col-md-12">
	// 				<div class="table-responsive noSwipe">
	// 					<input type="hidden" id="flag_popup">
	// 					<table id="table1" class="table table-striped table-hover table-fw-widget" data-page-length="100">
	// 						<thead>
	// 							<tr class="nexos-encabezado">
	// 								<th class="col-xs-1 col-sm-1 col-md-1">#</th>
	// 								<th class="col-xs-1 col-sm-1 col-md-1">Id estudio</th>
	// 								<th>Placa</th>
	// 								<th>Estado</th>
	// 								<th>Acciones</th>
	// 							</tr>
	// 						</thead>
	// 							<tbody id="body_tabla">
	// 						</tbody>
	// 					</table>
	// 				</div>
	// 			</div>
	// 		</div>
	// 	</div>	
	// 	';

	// 	 $vista.= '
	// 	CONTENEDORES Y REGISTRO DE DATOS
	// 	<div class="panel panel-border panel-contrast">
	// 		<div class="panel-heading panel-heading-contrast">
	// 			Solicitudes de Vehículos
	// 			<div class="tools">
	// 			</div>
	// 			<span class="panel-subtitle">Módulo para ver las solicitudes de vehiculos por operaciones</span>
	// 			<input type="hidden" id="usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'" >
	// 		</div>
	// 		<div class="panel-body xs-mt-15">
	// 			<div class="nexos-messages"></div>
	// 			%content%
	// 			<div class="row">
	// 				<div class="col-sm-12">
	// 				</div>
	// 			</div>
	// 		</div>
	// 	</div>
	// 		 	';

	// }

	$vista.= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
		<link  rel="stylesheet" type="text/css" href="assets/lib/select2/css/select2.min.css"/>

		<link rel="stylesheet" type="text/css" src="%root_file%lib/assets/lib/select2/css/select2.min.css"/>


		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
		<script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.wizard();
			});
		</script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****///7.1   NO TOCARRRRRRRRR NUNCA
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_content , $vista); 
	echo $vista;
?>

<div class="modal fade" id="verestudio" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"><strong>Consultar Resumen del Estudio de Seguridad</strong></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       	<div id="content_ver">
               <div id="titlu"></div>
          <div class="form-group col-xs-12 col-sm-12 col-md-12" id="linea_negocio">
              <label>N° Estudio<span style="color:red;"><i>(*)</i></span></label><br>
              <input type="text" id="num_estu" readonly="readonly" class="form-control input-sm">
              </div>
            <div class="titulogeneral col-md-12">
             <strong>Datos de Comprobación</strong><hr/ style="border: 0; height: 12px; box-shadow: inset 0 12px 12px -12px blue;">
           </div>
            <table class="table table-condensed table-hover table-bordered table-striped">
                <thead style="background-color:;   ">
                          <tr>
                            <th class="number">Estudios</th>
                            <th class="number">Aprobación</th>
                            <th class="">Observación</th>
                            <th class="number">usuario</th>
                            <th class="number">Fecha</th>
                            <th class="number">Hora</th>
                          </tr>
                </thead>
                <tbody id="cuerpo_estudio">
                </tbody>
            </table>



       	</div><!--conten fin -->    
		<div class="row"></div>
		</div>		
 		<div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">
	$(document).ready(function(){
	$("#buscar_historico").click(function(){
		// alert('historico');
		var f1=$("#finicial").val();
		var f2=$("#ffinal").val();
		var opt=$("#filtro").val();


		if(f1==='' || f2==='' || opt===''){
			alert('Por favor registre los campos para poder generar su consulta');
		}else{
			//maqueta la tabla
			

			var datos={
			finicia:f1,
			ffinal:f2,
			option:opt,
			action:'historico_estudio'
			};
			$("#body_tabla").html('');
			$.ajax({
				url:"http://localhost/mvcLuisMiguel/libs/seguridad_estudio2_ajax.php",
	 			type:'POST',
	 			data:datos,
	 			dataType:'json',
	 			success: function(data){
	 				// alert('ha traido datos');
	 				// console.log(data);
	 				cont=0;
	 				if(data){
	 					data.result.forEach(function(element,index){
	 						cont++;
							var estado=element.estadoes;
							var numes=element.id_preliminar;
							var es='';
							status='';
							if(estado=='Aprobado'){
								es='Aprobado';
								status='<center><span class="text-success mdi mdi-dot-circle icon"></span></center>';
							}

							if(estado=='Pendiente'){
								es='Pendiente';
								status='<center><span class="text-primary mdi mdi-dot-circle icon"></span></center>';
							}

							if(estado=='Rechazado'){
								es='Rechazado';
								status='<center><span class="text-danger mdi mdi-dot-circle icon"></span></center>';
							}

							var boton_ver='';
	 						boton_ver='<button type="button"  class="btn btn-secondary btn btn-sm mdi mdi-eye" id="btn_ver'+cont+'" data-toggle="modal" data-target="#verestudio" title="consultar historial" data-id="'+numes+'"  ></button>';

		 					$("#body_tabla").append('<tr><td>'+status+'</td>'+
		 					'<td>'+element.id_preliminar+'</td>'+
		 					'<td>'+element.placa+'</td>'+
		 					'<td>'+es+'</td>'+
		 					'<td>'+boton_ver+'</td>'+
		 					'</tr>');


						//boton ver

	 					$("#btn_ver"+cont+"").click(function(){
						 	  // alert('btn ver');
							var id=$(this).attr('data-id');
							$("#num_estu").val(id);
							//alert(id);

							var ver_estu={
								id_estudio:id,
								action:'ver_estudio_historial'
							};
							$("#cuerpo_estudio").html('');
							$.ajax({
								url:"http://localhost/mvcLuisMiguel/libs/seguridad_estudio2_ajax.php",
					 			type:'POST',
					 			data:ver_estu,
					 			dataType:'json',
					 			success: function(data){
					 				console.log(data);
					 				if(data.result){
					 					data.result.forEach(function(element,index){
											var apro=element.estado;
					 						var palabra='';
					 						if(apro=='1'){
					 							palabra='Aceptado';
					 						}
					 						if(apro=='0'){
					 							palabra='Rechazado';
					 						}

					 						var observe=element.observacion;
					 						if(observe !=''){
					 							obser=element.observacion;
					 						}else{
					 							obser='';
					 						}

					 					$("#cuerpo_estudio").append('<tr><td>'+element.estudio+'</td>'+
					 						'<td>'+palabra+'</td>'+
					 						'<td>'+obser+'</td>'+
					 						'<td>'+element.usuario+'</td>'+
					 						'<td>'+element.fecha+'</td>'+
					 						'<td>'+element.hora+'</td>'+
					 						'</tr>');
					 					});
					 				}
					 			},
					 			error:function(jqXHR, textStatus, errorThrown){
					 				console.log(jqXHR);
									console.log(textStatus);
									console.log(errorThrown);
					 			}
					 	});

						});

	 					});

	 				}
	 			
	 			},
	 			error: function(jqXHR, textStatus, errorThrown){
	 				console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
	 			}
	 		});
		}
	});
});
</script>
