<?php
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

//variables del sistema
$vista = '';
$table_content='';
$cliente='';
$usuario='';

if ( isset($this->index) ) {
	$arrayPermisos = $this->index->permisosPerfil( $ssn_id_perfil , 122);
	$_permisos = $arrayPermisos["rowsData"][0];
$btn_crear='';
if($_permisos["adicionar"]== 1){

	$btn_crear='
		<a id="btn_crea" href="#"  data-toggle="modal"  class="cell-detail  hint--top "  data-hint="Asignar Agencia" data-target="#crear"><span class="icon mdi mdi-plus"></span></a>';	
}


$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Asignar agencias a un usuario
				<div class="tools">
					'.$btn_crear.'
				</div>
				<span class="panel-subtitle">Módulo para asignar agencias a un usuario Nexos.</span>
				<div class=" col-xs-12 col-sm-4 col-md-12">
					<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'" >
				</div>
			</div>
			<div class="panel-body">
				<div class="nexos-messages"></div>
				<div class="nexos-content">
					%content%
				</div>
				<div class="row">
				<div class="col-sm-12"></div>
				</div>
			</div>
		</div>
	'; 
/*
$cliente.="<select id='agencia' class='form-control input-sm mi-selector' name='agencia[]' multiple='multiple'  ><option value=''>Seleccione</option>
";
$array = $this->index-> getagencia();
if($array){
	foreach ($array["rowsData"] as $key => $value) {
		$cliente.="<option value='".$value['id']."'>".$value['nombre']."</option>";
	}
}

$cliente.="</select>";
*/

/*
$array2 = $this->index->getusuario();

$usuario.="
<select id='usuario_asigne' class='form-control input-sm '><option value=''>Seleccione</option>";

if($array2){
	foreach ($array2["rowsData"] as $key => $value2) {
		$usuario.="<option value='".$value2['id']."'>".$value2['nom_usuario']."</option>";
	}
}
$usuario.="</select>";
*/

/*
$cliente.='<ul class="list-group list-group-flush">';
	$array = $this->index-> getagencia2($ssn_id_usuario);
	if($array){
	foreach ($array["rowsData"] as $key => $value) {

    $cliente.='<li class="list-group-item">
      <!-- Default checked -->
      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="agencia" checked="true">
        <label class="custom-control-label" for="agencia">'.$value['nombre'].'</label>
      </div>
    </li>';
    
    	}

    }
  $cliente.='</ul>';
*/







$table_content.="<div class='row' >
			<div class='col-sm-12'>
				<div  class='table-responsive noSwipe'>
					<table id='table1' class='table table-striped table-hover' data-page-length='100'>
						<thead>
							<tr class='nexos-encabezado'>
								<th>#</th>
								<th>Usuario</th>
								<th style='width:10%;min-width: 10%;'>acciones</th>
							</tr>
						</thead>
						<tbody>";

	$array3 = $this->index->gettablass();	
	if($array3){
		foreach($array3["rowsData"] as $index => $value){

			if($value['estado']=='Activo'){
				$_col_status='
					<td class="text-warning">
						<center>
						<span class="mdi mdi-dot-circle icon" title="Activo"></span>
						</center>
					</td>';
			}

			if($value['estado']=='Inactivo'){
				$_col_status='
					<td class="text-danger">
						<center>
						<span class="mdi mdi-dot-circle icon" title="Inactivo"></span>
						</center>
					</td>';
			}

			if($_permisos["adicionar"]== 1){

				$btn_edita='<button  button  class="btn-secondary btn btn-xs ">
					<a href="javascript:" onclick="editar_agencia(this)"  
						class="cell-detail hint--top-left" 
						data-id="'.$value['id_usuario'].'">
						<span class="icon mdi mdi-edit" 
						data-toggle="modal" 
						data-target="#editar_agencia" 
						title="Editar Agencia"></span>
					</a>
				</button>';

			}

			$table_content.="<tr>
				".$_col_status."
				<td>".$value['nom_usuario']."</td>
				<td>".$btn_edita."</td>
			</tr>";

		}

	}



		$table_content.="</tbody>
					</table>
				</div>
			</div>
		</div>";

}	?>

<div id="crear" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="editar_title">
						<label id="titulo" style="font-size:19pt; color:white; text-align:center;">Designar Agencias a Usuarios</label>
						</h3>
					</div>
					<div class="modal-body"  style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
						<div id="msg_editar"></div><!-- id para manejar los mensajes de errordel popup -->
						<div id="content_editar">
							<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<label style="font-weight:800; margin-top:20px;">Usuario</label>
									<select id='usuario_asigne' class='form-control input-sm'>
										<option value=''>Seleccione</option>
									</select>	

							</div>
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
								<label style="font-weight:800; margin-top:20px;">Agencias actuales</label>
								<ul class="list-group list-group-flush lista_agencia">
								</ul>	
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
								<label style="font-weight:800; margin-top:20px;">Agencia</label>
								<select id='agencia' class='form-control input-sm mi-selector'><option value=''>Seleccione</option>
								</select>	

							</div>
							</div>


							<div class="row">
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<label style="font-weight:800; margin-top:20px;">Fecha</label>
								<input type="text" id="fecha" class="form-control input-sm" readonly="" value="<?php echo date('Y-m-d');  ?>">
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<label style="font-weight:800; margin-top:20px;">Hora</label>
								<input type="text" id="hora" class="form-control input-sm" readonly="readonly" value="<?php echo date('H:i:s'); ?>">
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<label style="font-weight:800; margin-top:20px;">Usuario</label>
								<input type="text" id="usuario" class="form-control input-sm" readonly="readonly" value="<?php  echo $ssn_nombre; ?>">
							</div>
							</div>

							<div class="row"></div>
						</div>
					<div class="modal-footer">
						<button id="btn_actualizar" type="button" class="btn btn-success md-close" onclick="registrar();" >Guardar</button>
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
						</div>
					</div>
				</div>
			</div>
</div>


<div id="editar_agencia" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title" id="editar_title">
						<label id="titulo">
							<label style="font-size:19pt; color:white; text-align:center;">EDITAR DESIGNACION DE AGENCIAS
							</label>
						</label>
						</h3>
					</div>
					<div class="modal-body"  style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
						<div id="msg_editar"></div><!-- id para manejar los mensajes de errordel popup -->
						<div id="content_editar">
							<div  class='table-responsive noSwipe'>
								<table id='table2' class='table table-striped table-hover' data-page-length='100'>
									<thead>
										<tr class='nexos-encabezado'>
											<th>estado</th>
											<th>Usuario</th>		
											<th>Agencia</th>
											<th style='width:10%;min-width: 10%;'>acciones</th>
										</tr>
									</thead>
									<tbody id="cuerpo_editar">
									</tbody>
								</table>
							</div>
						</div>
					<div class="modal-footer">
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
						</div>
					</div>
				</div>
			</div>
</div>


<?php $vista.= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
		<link  rel="stylesheet" type="text/css" href="assets/lib/select2/css/select2.min.css"/>

		<link rel="stylesheet" type="text/css" src="%root_file%lib/assets/lib/select2/css/select2.min.css"/>


		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
		<script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.wizard();
			});
		</script>
';
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_content , $vista); //variable $table_content sirve para crear adentro de esta todo lo que se va a mostrar en el cuerpo del conetenedor 
	echo $vista;			
?>

<script type="text/javascript">
$(document).ready(function() {
        /*$('.mi-selector').select2({
        	width:'100%';
        });*/
       traer_usuarios();
       traer_agencias();

});
var urlu =$("#id_url_ajax").val() + 
	"libs/trafico_ajax.php";

	//consultar las agencias que tiene cada usuario	
	function editar_agencia(element){
		var elemento = $(element);
		var id_usuario = elemento.data("id");
		var ta={
			id_usuario:id_usuario,
			action:'agencias_usuario'
		};
		$("#cuerpo_editar").html('');
		$.ajax({
			url:urlu,
			type:'POST',
			data:ta,
			dataType:'json',
			success: function(data){
				if(data){
					data.result.forEach(function(element,index){
						var status, btn, text, color;
						if(element.estado=='Activo'){
							status='<td class="text-warning">'+
								'<center>'+
								'<span class="mdi mdi-dot-circle icon" title="Activo"></span>'+
								'</center>'+
									'</td>';
									btn='close-circle-o';	
									text='Inactivar  ';
									color='danger';
						}

						if(element.estado=='Inactivo'){
							status='<td class="text-danger">'+
								'<center>'+
								'<span class="mdi mdi-dot-circle icon" title="Inactivo"></span>'+
								'</center>'+
									'</td>';
								btn='check';
								text='Activar  ';
								color='success';
						}


						$("#cuerpo_editar").append('<tr>'+
								status+
							'<td>'+element.nom_usuario+'</td>'+
							'<td>'+element.nombre+'</td>'+
							'<td>'+
								'<button id="" class="btn btn-xs btn-'+color+'"  onclick="accion_agencia(this)" data-id="'+element.id+'" data-id2="'+element.estado+'"   ><span class="icon mdi mdi-'+btn+'" title="'+text+'agencia"></span></button>'+
							'</td>'
							+'</tr>');
					});
				}
			},
			error:function(jqXHR, textStatus, errorThrown){
				console.log('no iserto');
				console.log(jqXHR);
			console.log(textStatus);
				console.log(errorThrown);
			}
		});
	}


	function accion_agencia(element){
		var elemento = $(element);
		var id_agencia_usuario = elemento.data("id");
		var estado = elemento.data("id2");
		var accion={
			id_agencia_usuario:id_agencia_usuario,
			estado:estado,
			action:'accion_agencia'
		};

		$.ajax({
			url:urlu,
			type:'POST',
			data:accion,
			dataType:'json',
			success: function(data){
				//console.log('accion bien hecha');
				alert('Ok!!Acción  Realizada Exitosamente!!');
				location.reload(); 
			},
			error:function(jqXHR, textStatus, errorThrown){
				//console.log('accion error');
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			}
		});
	}


	function registrar(){
		// alert('guardar');
		var age=$("#agencia").val();
		var usu=$("#usuario_asigne").val();
		var fcha=$("#fecha").val();
		var hr=$("#hora").val();
		var user_creador=$("#usuario").val();
		//validar que la opcion elegida no este creada 
		var valida={
			age:age,
			usu:usu,
			fcha:fcha,
			hr:hr,
			user_creador:user_creador,
			action:'validar_creacion'
		};

		$.ajax({
			url:urlu,
			type:'POST',
			data:valida,
			dataType:'json',
			success: function(data){
				console.log(data);


				if(data.result==null){
					//no hay nada puede crear
					//alert('puede registrar');

					var insert={
						age:age,
						usu:usu,
						fcha:fcha,
						hr:hr,
						user_creador:user_creador,
						action:'usuario_agencia'
					};
					$.ajax({
						url:urlu,
						type:'POST',
						data:insert,
						dataType:'json',
						success: function(data){
							console.log('inserto bien');
							alert('Ok!! Registro Exitosamente!!');
							location.reload(); 
						},
						error:function(jqXHR, textStatus, errorThrown){
							console.log('no iserto');
							console.log(jqXHR);
						console.log(textStatus);
							console.log(errorThrown);
						}
					});

				}

				if(data.result!=null){
					//si hay ya existe una , no puede crear
					alert('Señor usuario usted ya tiene asociada esta agencia por favor eliga otra');
				}

			},
			error:function(jqXHR, textStatus, errorThrown){
				console.log('no valido creacion');
				console.log(jqXHR);
			console.log(textStatus);
				console.log(errorThrown);
			}
		});


		/*
		var insert={
			age:age,
			usu:usu,
			fcha:fcha,
			hr:hr,
			user_creador:user_creador,
			action:'usuario_agencia'
		};
		$.ajax({
			url:urlu,
			type:'POST',
			data:insert,
			dataType:'json',
			success: function(data){
				console.log('inserto bien');
				alert('Ok!! Registro Exitosamente!!');
				location.reload(); 
			},
			error:function(jqXHR, textStatus, errorThrown){
				console.log('no iserto');
				console.log(jqXHR);
			console.log(textStatus);
				console.log(errorThrown);
			}
		});*/


	}

	//traer usuarios - creacion
	function traer_usuarios(){
		  var traer_usuario={
        	action:'traer_usuarios'
       	 };

	       	$("#usuario_asigne").html('<option value="">Seleccione</option>');
	        $.ajax({
				url:urlu,
				type:'POST',
				data:traer_usuario,
				dataType:'json',
				success: function(data){
					//console.log('accion bien hecha');
					if(data){
						data.result.forEach(function(element,index){
							$("#usuario_asigne").append('<option value="'+element.id+'">'+element.nom_usuario+'</option>');
						});
					}
				},
				error:function(jqXHR, textStatus, errorThrown){
					console.log('error usuarios');
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
				}
			});	
	}

	$("#usuario_asigne").change(function(){
		
		var usu=$("#usuario_asigne").val();
		var buscar_agencias={
			usu:usu,
			action:'buscar_agencias'
		};
		$(".lista_agencia").html('');
		  $.ajax({
				url:urlu,
				type:'POST',
				data:buscar_agencias,
				dataType:'json',
				success: function(data){
					//console.log('accion bien hecha');
					if(data.result!=null || data.result!=''){
						data.result.forEach(function(element,index){							
							$(".lista_agencia").append('<li class="list-group-item">'+
								     ' <div class="custom-control custom-checkbox">'+
								        '<input type="checkbox" class="custom-control-input" id="agenci" checked="true">'+
								        '<label class="custom-control-label" for="agencia">'+element.nombre+'/'+element.estado+'</label>'+
								      '</div>'+
								    '</li>');
						});
					}
					if(data.result==null || data.result==''){

						$(".lista_agencia").html('<li><label class="custom-control-label">No tiene agencias asociadas</label></li>');

					}
				},
				error:function(jqXHR, textStatus, errorThrown){
					console.log('error lista agencias');
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
				}
			});	
	});


	function traer_agencias(){
		$("#agencia").html('');
		var agencia={
			action:'traer_agencia'
		};

		 $.ajax({
				url:urlu,
				type:'POST',
				data:agencia,
				dataType:'json',
				success: function(data){
					//console.log('accion bien hecha');
					if(data){
						data.result.forEach(function(element,index){
							$("#agencia").append('<option value="'+element.id+'">'+element.nombre+'</option>');
						});
					}
				},
				error:function(jqXHR, textStatus, errorThrown){
					console.log('error agencia');
					console.log(jqXHR);
					console.log(textStatus);
					console.log(errorThrown);
				}
			});	
	}







</script>