<form class="row g-3 mb-6">
  <div class="col-12 col-sm-4 col-md-4 col-lg-4 col-xl-4 col-xxl-4">
    <div class="mb-4">
      <div class="d-flex flex-wrap mb-2">
        <h5 class="mb-0 text-body-highlight me-2">Proveedores <span style="color:red;"><i>*</i></h5>
      </div>
      <select class="form-select form-select-sm select2" id="slt_Proveedores" style="width:100%;"></select>
    </div>
  </div>
  <div class="col-12 col-sm-4 col-md-4 col-lg-4 col-xl-4 col-xxl-4">
    <div class="mb-4">
      <div class="d-flex flex-wrap mb-2">
        <h5 class="mb-0 text-body-highlight me-2">Modalidad <span style="color:red;"><i>*</i></h5>
      </div>
      <select class="form-select form-select-sm select2" id="slt_Modalidad" style="width:100%;">
        <option value="" disabled="" selected="">Seleccione</option>
        <option value="CARGA SECA">CARGA SECA</option>
        <option value="CARGA LIQUIDA">CARGA LIQUIDA</option>
        <option value="IMPORTACION">IMPORTACION</option>
        <option value="EXPORTACION">EXPORTACION</option>
      </select>
    </div>
  </div>

  <div class="col-12 col-sm-4 col-md-4 col-lg-4 col-xl-4 col-xxl-4">
    <div class="mb-4">
      <div class="d-flex flex-wrap mb-2">
        <h5 class="mb-0 text-body-highlight me-2">Nombre Plantilla <span style="color:red;"><i>*</i></h5>
      </div>
      <input type="text" class="form-control form-control-sm" name="nombre_plantilla" id="nombre_plantilla">
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 col-md-9 col-lg-9 col-xl-9 col-xxl-9">
      <h4 class="text-center" style="font-weight: bold;background-color: #332D2D;color:#FFFFFF;padding: 12px;">
        Parametros de trazabilidad</h4>
      <div id="accordionExample"><!-- Contenido JS --></div>
      <h4 class="text-center" style="font-weight: bold;background-color: #332D2D;color:#FFFFFF;padding: 12px;"> Visualización de actividades</h4>
      <table class="table table-sm">
        <thead>
          <tr>
            <th style="width: auto; white-space: nowrap;" scope="col">#</th>
            <th style="width: auto; white-space: nowrap;" scope="col">Usuarios</th>
            <th style="width: auto; white-space: nowrap;" scope="col">Actividades</th>
            <th style="width: auto; white-space: nowrap;" scope="col"><button class="btn btn-subtle-success btn-sm me-1 px-1 py-0" type="button" id="btn-agregar-fila"><span class="uil uil-plus-circle"></span> Agregar</button></th>
          </tr>
        </thead>
        <tbody id="tbody_visualizadores"></tbody>
      </table>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3" id="lista_previsualizacion">
      <div class="panel panel-primary" style="background-color: #332D2D;color:#FFFFFF;margin-bottom:5px;">
        <h4 class="text-center" style="font-weight:bold; background-color: #332D2D;color:#FFFFFF;padding: 12px;"> Previsualizar orden actividades</h4>
      </div>
      <div class="panel-body border"
        style="max-height: 500px;overflow-x: hidden;overflow-y: auto ;padding: 1px 1px 1px;">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div id="secondaryList"></div>
          </div>
        </div>
      </div>
      <div class="panel-footer" style="padding: 1px 1px 1px;font-weight: bold;">
        <h4 id="posicion"></h4>
      </div>
    </div>
  </div>

</form>

<div class="col-12 gy-6">
  <div class="row g-3 justify-content-end">
    <div class="col-auto">
      <button class="btn btn-primary btn-sm px-5" id="btn-create-plantilla" type="button">
        <span data-feather="save"></span> Crear Plantilla</button>
    </div>
  </div>
</div>