<div id="tablaPlantillas">
  <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
    <div class="row">
      <div class="table-responsive scrollbar">
        <table id='table1' class='table table-bordered table-sm' data-page-length='100' style="font-size:11px;">
          <thead>
            <tr>
              <th class='text-center' style='color:black;width: auto; white-space: nowrap;'>N.Plantilla</th>
              <th class='text-center' style='color:black;width: auto; white-space: nowrap;'>Nompre Plantilla</th>
              <th class='text-center' style='color:black;width: auto; white-space: nowrap;'>Proveedor</th>
              <th class='text-center' style='color:black;width: auto; white-space: nowrap;'>Modalidad</th>
              <th class='text-center' style='color:black;width: auto; white-space: nowrap;'>Fecha Creación</th>
              <th class='text-center' style='color:black;width: auto; white-space: nowrap;'>Estado plantilla</th>
            </tr>
          </thead>
          <tbody id='tbl_plantillas_administrador' class='text-center'>
            <tr>
              <td colspan="11" class="text-center" style="font-size:15px;font-weight:bold;">
                <img src="<?= BASE_URL ?>public/img/nexos_loading.gif" height="25" width="25" id="load_info" style="display: none;"> Esperando Información
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>