<?php
	$_dbTable = "riesgo_comercializacion"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->riesgo_comercializacion) && count($this->riesgo_comercializacion)){

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_view = '
			<div class="row">
				<div class="col-sm-3"></div>
				<div class="col-sm-6">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover" data-page-length="25">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width:10%;">#</th>
									<th>Riesgo de Comercialización</th>
									<th style="width:10%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayTarifa = $this->riesgo_comercializacion->getTabla();
		// echo print_r($arrayTarifa);
		if ($arrayTarifa['rowsData']) {
			foreach ($arrayTarifa['rowsData'] as $key => $value) {

				/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
				switch ($value["estado"]) {
					case '0':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-danger">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

						$_popupHabilita = $alert->_alert_modal_mod_success( $value[0] , "Realmente desea habilitar este elemento?" , $_dbTable );
						$vista.= $_popupHabilita[0];
						$_jsScripts.=$_popupHabilita[1];

						// se asigna contenudo de la columna de acciones
						$col_action = '
							<td class="actions">
								<span id="#habilita_' . $value[0] . '" data-toggle="modal" data-target="#habilita_' . $value[0] . '" class="icon mdi mdi-check-circle"></span>
							</td>
						';
						break;
					
					case '1':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-success">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

						$form_edit_table = '
							<input type="hidden" name="id" value="' . $value[0] . '" class="form-control">
							<div class="form-group col-xs-2"></div>
							<div class="form-group col-xs-8">
								<label>(*) Riesgo de Comercialización:</label>
								<input type="text" name="nom_riesgo_comercializacion" id="nom_riesgo_comercializacion_' . $value[0] . '" value="' . $value["nom_riesgo_comercializacion"] . '" placeholder="Riesgo de Comercialización" class="form-control">
								<label id="error_nom_riesgo_comercializacion_' . $value[0] . '"></label>
							</div>
							<div class="form-group col-xs-2"></div>
							<div class="row"></div>
							<div class="form-group col-xs-2"></div>
							<div class="form-group col-xs-8">
								<label>(*) Descripcion:</label>
								<textarea name="descripcion" id="descripcion_' . $value[0] . '" placeholder="Descripción" class="form-control">' . $value["descripcion"] . '</textarea>
							</div>
							<div class="row"></div>
						';

						// Validacion de contenido del formulario de creacion
						$_jsScripts.='
							<script type="text/javascript">
								var validar_nom_riesgo_comercializacion = "";
								$("#nom_riesgo_comercializacion_' . $value[0] . '").focusin(function (){
									removerClaseserror("#error_nom_riesgo_comercializacion_' . $value[0] . '", "#nom_riesgo_comercializacion_' . $value[0] . '");
								});

								$("#nom_riesgo_comercializacion_' . $value[0] . '").focus(function (){
									$("#nom_riesgo_comercializacion_' . $value[0] . '").keypress(function() {
										validarkeypress("#error_nom_riesgo_comercializacion_' . $value[0] . '", "#nom_riesgo_comercializacion_' . $value[0] . '");
									});
								});

								$("#nom_riesgo_comercializacion_' . $value[0] . '").focusout(function (){
									validar_nom_riesgo_comercializacion = validaciones("vacio" , $("#nom_riesgo_comercializacion_' . $value[0] . '").val() , "Riesgo de Comercialización");
									if(validar_nom_riesgo_comercializacion != true){
										agregarClaseserror("#error_nom_riesgo_comercializacion_' . $value[0] . '", "#nom_riesgo_comercializacion_' . $value[0] . '", validar_nom_riesgo_comercializacion);
									}
									else{
										removerClaseserror("#error_nom_riesgo_comercializacion_' . $value[0] . '", "#nom_riesgo_comercializacion_' . $value[0] . '");
									}
								});
							</script>
						';

						$_popupEdita = $form_edita->_form_modal_update($value[0], "Editar Riesgo de Comercialización - " . $value[1] , $form_edit_table, $_dbTable);
						$vista.= $_popupEdita[0];
						$_jsScripts.=$_popupEdita[1];


						$_popupElimina = $alert->_alert_modal_mod_danger($value[0], "Realmente desea eliminar este elemento?",$_dbTable);
						$vista.= $_popupElimina[0];
						$_jsScripts.=$_popupElimina[1];
						// se asigna contenudo de la columna de acciones
						$col_action = '
							<td class="actions">
								<span id="edita_' . $value[0] . '" data-toggle="modal" data-target="#edita_' . $value[0] . '" class="icon mdi mdi-edit"></span>
								<span id="elimina_' . $value[0] . '"data-toggle="modal" data-target="#elimina_' . $value[0] . '" class="icon mdi mdi-close-circle"></span>
							</td>
						';

						break;
				}
				/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

				// Se maqueta contenido de la tabla 
				$table_view.= '<tr>';
				$table_view.= $col_stasus;
				$table_view.= '
					<td class="cell-detail">
						<span>' . $value["nom_riesgo_comercializacion"] . '</span>
						<span class="cell-detail-description">' . $value["descripcion"] . '</span>
					</td>
				';

				// se asigna la columna de acciones
				$table_view.=$col_action;
				
				$table_view.= '</tr>';
			}

			$table_view.= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
		}
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Riesgo de Comercialización
				<div class="tools">
					<a href="#" data-toggle="modal" data-target="#crea_' . $_dbTable . '" class="cell-detail  hint--top"  data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a> 
				</div>
				<span class="panel-subtitle">Establece el nivel de riesgo de robo que corre el material como consecuencia de su alta demanda en el mercado.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


  	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();


			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';


	/****** CREACION CONTENIDO DE POPUPS ******/

	// CONTENIDO DEL POPUP DE FORMULARIO DE CREACION
	$forms = '
		<div class="form-group col-xs-2"></div>
		<div class="form-group col-xs-8">
			<label>(*) Riesgo de Comercialización:</label>
			<input type="text" name="nom_riesgo_comercializacion" id="nom_riesgo_comercializacion" placeholder="Nombre Riesgo de Comercialización" class="form-control">
			<label id="error_nom_riesgo_comercializacion"></label>
		</div>
		<div class="form-group col-xs-2"></div>
		<div class="row"></div>
		<div class="form-group col-xs-2"></div>
		<div class="form-group col-xs-8">
			<label>(*) Descripcion:</label>
			<textarea name="descripcion" placeholder="Descripción" class="form-control"></textarea>
		</div>
		<div class="form-group col-xs-2"></div>
		<div class="row"></div>
	';

	// Valifdacion de contenido del formulario de creacion
	$_jsScripts.='
		<script type="text/javascript">
			var validar_tipo_unidad = "";
			var validar_nom_riesgo_comercializacion = "";

			$("#nom_riesgo_comercializacion").focusin(function (){
				removerClaseserror("#error_nom_riesgo_comercializacion", "#nom_riesgo_comercializacion");
			});

			$("#nom_riesgo_comercializacion").focus(function (){
				$("#nom_riesgo_comercializacion").keypress(function() {
					validarkeypress("#error_nom_riesgo_comercializacion", "#nom_riesgo_comercializacion");
				});
			});

			$("#nom_riesgo_comercializacion").focusout(function (){
				validar_nom_riesgo_comercializacion = validaciones("vacio" , $("#nom_riesgo_comercializacion").val() , "Riesgo de Comercialización");
				if(validar_nom_riesgo_comercializacion != true){
					agregarClaseserror("#error_nom_riesgo_comercializacion", "#nom_riesgo_comercializacion", validar_nom_riesgo_comercializacion);
				}
				else{
					removerClaseserror("#error_nom_riesgo_comercializacion", "#nom_riesgo_comercializacion");
				}
			});

			var flagError = "";
			if ( validar_tipo_unidad != true || validar_nom_riesgo_comercializacion != true ) {
				flagError = false;
			} else {
				flagError = true;
			}
			
		</script>
	';

	$_popupCrea = $form_crea->_form_modal_simple_insert("crea_" . $_dbTable ,"Crear Riesgo de Comercialización" , $forms , $_dbTable );
	$vista.= $_popupCrea[0];
	$_jsScripts.=$_popupCrea[1];


	/****** FIN CREACION CONTENIDO DE POPUPS ******/

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_view , $vista);

	// Se asiga código JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
