<div class="container-fluid">
  <div class="row">
    <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-3">
      <div class="mb-3">
        <label class="control-label">(*) Proveedor:</label>
        <select class="form-select form-select-sm" name="proveedor_asignar" id="slct_proveedor_asignar_">
          <!-- <option value="" disabled="" selected="">Seleccione</option> -->
        </select>
      </div>
    </div>
    <div class="form-group col-xs-6 col-sm-6 col-md-6 col-lg-6">
      <div class="mb-3">
        <label class="control-label">(*) Servicios:</label>
        <select class="form-select form-select-sm" multiple="multiple" name="servicios_asignar[]" id="slct_servicios_asignar_">
          <!-- <option value="" disabled="" selected="">Seleccione</option> -->
        </select>
      </div>
    </div>
    
    <div class="form-group col-xs-3 col-sm-3 col-md-3 col-lg-3">
      <div class="mb-3">
        <label class="control-label">(*) Estado  Asignación Servicio:</label>
        <select class="form-select form-select-sm" name="estado_servicio" id="slct_estado_servicio_">
          <option value="" selected>Seleccione</option>
          <option value="Activo">Activo</option>
          <option value="Inactivo">Inactivo</option>
        </select>
      </div>
    </div>

    <div class="col-12 mb-2">
      <div class="row g-3 justify-content-end">
        <!-- <div class="col-auto">
          <button class="btn btn-phoenix-primary btn-sm text-danger" type="button" id="btn-cancelar">
            <span class="text-danger" data-feather="x"></span> Cancelar
          </button>
        </div> -->
        <div class="col-auto">
          <button class="btn btn-primary btn-sm" id="btn_guardar_asignacion" type="button">
            <!-- <button class="btn btn-primary btn-sm me-1 px-1 py-0" id="btn_guardar_proveedor" type="button"> -->
            <span class="uil uil-save"></span> Guardar Asignación
          </button>
        </div>
      </div>
    </div>
  </div>
</div>