<?php
	$_dbTable = "agrupacion_anticipo"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/

	/*** SE CREA TABLA DE CONTENIDO ***/
	$table_view = '';

	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->facturacion) /* && count($this->facturacion) */){
		$table_view = '
			<div class="row">
				<div class="col-sm-12">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width: 5%;"></th>
									<th>Manifiesto</th>
									<th>Cliente</th>
									<th>Servicio Adicional</th>
									<th>Origen</th>
									<th>Destino</th>
									<th>Proveedor</th>
								</tr>
							</thead>
							<tbody>
		';
		$costos = $this->facturacion->getCostosProyectos();

		$link_descarga = '';
		if ($costos) {
			$link_descarga = '
				<a href="" id="generarExcelHelisa" target="_blank" class="hint--top-left" data-hint="Crear archivo de facturación">
					<span class="icon mdi mdi-grid"></span>
				</a>
			';
			foreach ($costos as $key => $value) {
				// Se filtra la información del Proveedor
				$documento = $value["numero_documento"];
				if ( $value["tipo_documento"] == "NIT" ) {
					$documento = $value["numero_documento"] . "-" . $value["digito_verificacion"];
				}
				// Se maqueta contenido de la tabla 
				$table_view.= '<tr>';
				$table_view.= '
					<td class="cell-detail text-center">
						<span> 
							<div class="be-checkbox">
								<input name="' . $value['ID_MANIFIESTO'] . '" class="check_costos costos_' . $value['ID_MANIFIESTO'] . '" value="' . $value['ID_MANIFIESTO'] . '" id="num_costos_' . $value['ID_MANIFIESTO'] . '" type="checkbox">
								<label for="num_costos_' . $value['ID_MANIFIESTO'] . '"></label>
							</div>
						</span>
					</td>
					<td class="cell-detail">
						<span>' . $value["numero_manifiesto"] . '</span>
						<span class="cell-detail-description">' . $value["numero_solicitud"] . '</span>
					</td>
					<td class="cell-detail">
						<span>' . $value["NOMBRE_CLIENTE"] . '</span>
					</td>
					<td class="cell-detail">
						<span>' . $value["tipo_servicio"] . '</span>
						<span class="cell-detail-description">' . number_format($value["VALOR_COMPRA"], 2, ",", ".") . '</span>
					</td>
					<td class="cell-detail">
						<span>' . $value["ORIGEN"] . '</span>
						<span class="cell-detail-description">' . $value["CIUDAD_ORIGEN"] . '</span>
					</td>
					<td class="cell-detail">
						<span>' . $value["DESTINO"] . '</span>
						<span class="cell-detail-description">' . $value["CIUDAD_DESTINO"] . '</span>
					</td>
					<td class="cell-detail">
						<span>' . $value["nombre"] . '</span>
						<span class="cell-detail-description">' . $documento . '</span>
					</td>
				';
				$table_view.= '</tr>';
			}
		}

		$table_view.= '
							</tbody>
						</table>
					</div>
				</div>
			</div>
		';
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Costos de Proyectos
				<div class="tools">%link_descarga%</div>
				<span class="panel-subtitle">Módulo de creación de archivos en Excel para ser subidos al sistema Helisa.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
			</div>
		</div>
	';


  	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();


			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_view , $vista);
	$vista = str_replace("%link_descarga%" , $link_descarga , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>

<script type="text/javascript">
	$(document).ready(function(){
		buscarCostosChecked();

		$(".check_costos").click(function(){
			// console.log("El valor es - " + $(this).val() );
			// console.log( $(".remesa_" + $(this).val() ).val() );
			var id_costo = $(this).val();
			if ( $(this).prop("checked") ) {
				$(".remesa_" + id_costo ).attr("checked", true);
				$(".manifiesto_" + id_costo ).attr("checked", true);
			} else {
				$(".remesa_" + id_costo ).attr("checked", false);
				$(".manifiesto_" + id_costo ).attr("checked", false);
			}
		});

		$(".check_costos").click(function(){
			buscarCostosChecked();
		});

		$("#generarExcelHelisa").click(function(){
			setTimeout(function() { location.reload(false);  }, 3000);
		});
	});

	function buscarCostosChecked(){
		// console.log("Entro en funcion buscarCostosChecked");
		var flag_costos = false;
		var id_costos = "";
		var id_costos_checked = "";

		$(".check_costos").each(function(){
			id_costos+= $(this).val() + ",";

			if ( $(this).prop("checked") ) {
				flag_costos = true;
				id_costos_checked+= $(this).val() + ",";
			}
		});

		if ( flag_costos ) {
			// console.log("Se han seleccionado costos");
			var lista_costos = id_costos_checked;
		} 
		else {
			// console.log("No se han seleccionado costos");
			var lista_costos = id_costos;
		}
		// console.log(lista_costos);

		var url = $("#id_url_ajax").val() + 'libs/helisa_ajax.php?action=generaExcelCostos&id_costos=' + lista_costos;
		// console.log(url);

		$("#generarExcelHelisa").attr("href",url);
	}
</script>
