<?php
$_dbTable = "monedas"; // SIN EL PREFIJO cmx_
$_jsScripts = "";

$vista = '';

/*** CREACION DE TABLA DE CONTENIDO ***/
if (isset($this->facturacion) /* && count($this->facturacion) */) {
	$arrayFacturacion = $this->facturacion->getListaRemesasCliente();

	/*** SE CREA TABLA DE CONTENIDO ***/
	$table_view = '
			<div class="row">
				<div class="col-sm-12">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover" data-page-length="100">
							<thead>
								<tr class="nexos-encabezado">
									<th></th>
									<th>Cliente</th>
									<th>Remesas</th>
									<th>#</th>
									<th>Manifiestos</th>
									<th>#</th>
									<th>Proyecto</th>
									<th>Peso Total</th>
									<th>Peso Remesa</th>
									<th>Valor Proyecto</th>
									<th>Valor Remesa</th>
								</tr>
							</thead>
							<tbody>
		';

	$_falg_link_descarga = false;
	if ($arrayFacturacion) {
		foreach ($arrayFacturacion as $key => $value) {
			$col_status = '
					<td class="actions">
						<center>
							<input type="hidden" name="helisa_estado_' . $value['ID_REMESA'] . '" value="' . $value["helisa_estado"] . '">
							<span class="mdi mdi-dot-circle icon"></span>
						</center>
					</td>
				';
			$col_check_remesa = '
					<td class="cell-detail">
						<span> 
							<div class="be-checkbox ">
								<input name="' . $value['ID_REMESA'] . '" class="check_remesas remesa_' . $value["ID_MANIFIESTO"] . '" value="' . $value['ID_REMESA'] . '" id="num_remesa_' . $value['ID_REMESA'] . '_' . $value["ID_MANIFIESTO"] . '" type="checkbox">
								<label for="num_remesa_' . $value['ID_REMESA'] . '_' . $value["ID_MANIFIESTO"] . '"></label>
							</div>
						</span>
					</td>
				';
			$col_check_manifiestos = '
					<td class="cell-detail">
						<span> 
							<div class="be-checkbox ">
								<input name="' . $value['ID_REMESA'] . '" class="check_manifiestos manifiesto_' . $value["ID_MANIFIESTO"] . '" value="' . $value["ID_MANIFIESTO"] . '" id="num_manifiesto_' . $value['ID_REMESA'] . '_' . $value["ID_MANIFIESTO"] . '" type="checkbox">
								<label for="num_manifiesto_' . $value['ID_REMESA'] . '_' . $value["ID_MANIFIESTO"] . '"></label>
							</div>
						</span>
					</td>
				';
			if ($value["helisa_estado"] != "Pendiente") {
				$col_status = '
						<td class="nexos-txt-success">
							<center>
								<input type="hidden" name="helisa_estado_' . $value['ID_REMESA'] . '" value="' . $value["helisa_estado"] . '">
								<span class="mdi mdi-dot-circle icon"></span>
							</center>
						</td>
					';
				$col_check_remesa = '<td class="cell-detail"></td>';
				$col_check_manifiestos = '<td class="cell-detail"></td>';
			} else {
				$_falg_link_descarga = true;
			}
			// Se maqueta contenido de la tabla 
			$table_view .= '<tr>';
			$table_view .= $col_status;

			$table_view .= '
					<td class="cell-detail">
						<span>' . $value["nombre"] . '</span>
						<span class="cell-detail-description">' . $value["documento"] . '-' . $value["digito_verificacion"] . '</span>
						<input type="hidden" id="documento_' . $value['ID_REMESA'] . '" value="' . $value["documento"] . '">
						<input type="hidden" id="digito_verificacion_' . $value['ID_REMESA'] . '" value="' . $value["digito_verificacion"] . '">
					</td>
					<td class="cell-detail">
						<span>' . $value["numero_remesa"] . '</span>
						<input type="hidden" id="ID_REMESA_' . $value['ID_REMESA'] . '" value="' . $value["ID_REMESA"] . '">
					</td>
					' . $col_check_remesa . '
					<td class="cell-detail">
						<span>' . $value["numero_manifiesto"] . '</span>
						<input type="hidden" value="' . $value["ID_MANIFIESTO"] . '">
					</td>
					' . $col_check_manifiestos . '
					<td class="cell-detail">
						<span>' . $value["importacion"] . '</span>
						<span class="cell-detail-description">' . $value["numero_importacion"] . '</span>
						<input type="hidden" value="' . $value["ID_PROYECTO"] . '">
					</td>
					<td class="cell-detail text-center">
						<span>' .  number_format($value["PESO_TOTAL"], 0, ",", ".") . 'Kg</span>
					</td>
					<td class="cell-detail text-center">
						<span>' . number_format($value["PESO_MATERIAL"], 0, ",", ".") . 'Kg</span>
					</td>
					<td class="cell-detail text-right">
						<span>$' . number_format($value["valor_venta"], 0, ",", ".") . '</span>
					</td>
					<td class="cell-detail text-right">
						<span>$' . number_format($value["VALOR_PRORRATEO"], 0, ",", ".") . '</span>
					</td>
				';
			$table_view .= '</tr>';
		}
	}
	$table_view .= '
							</tbody>
						</table>
					</div>
				</div>
			</div>
		';
}
/*** FIN CREACION DE TABLA DE CONTENIDO ***/

/**** CONTENIDO DEL MODULO EN PANTALLA ****/
$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Facturación de Remesas
				<div class="tools">%link_descarga%</div>
				<span class="panel-subtitle">Se genera la facturación de remesas de la gestión realizada del transporte de materiales.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
$vista .= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';

// Se valida si se debe pintar el link de descarga en la vista
$link_descarga = '';
if ($_falg_link_descarga) {
	$link_descarga = '
			<a href="" id="generarExcelHelisa" target="_blank" class="hint--top-left" data-hint="Crear archivo de facturación">
				<span class="icon mdi mdi-grid"></span>
			</a>
		';
}

/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%content%", $table_view, $vista);
$vista = str_replace("%link_descarga%", $link_descarga, $vista);

// Se asiga codigo JS generado de la tabla de contenido
$vista .= $_jsScripts;

// SE PINTA CONTENIDO EN PANTALLA
echo $vista;

?>

<script type="text/javascript">
	$(document).ready(function() {
		buscarRemesasChecked();

		$(".check_manifiestos").click(function() {
			// console.log("El valor es - " + $(this).val() );
			// console.log( $(".remesa_" + $(this).val() ).val() );
			var id_manifiesto = $(this).val();
			if ($(this).prop("checked")) {
				$(".remesa_" + id_manifiesto).attr("checked", true).prop('checked', true);
				$(".manifiesto_" + id_manifiesto).attr("checked", true).prop('checked', true);
			} else {
				$(".remesa_" + id_manifiesto).attr("checked", false).prop('checked', false);
				$(".manifiesto_" + id_manifiesto).attr("checked", false).prop('checked', false);
			}
			buscarRemesasChecked();
		});

		$(".check_remesas").click(function() {
			buscarRemesasChecked();
		});

		$("#generarExcelHelisa").click(function() {
			setTimeout(function() {
				location.reload(false);
			}, 1500);
		});
	});

	function buscarRemesasChecked() {
		// console.log("Entro en funcion buscarRemesasChecked");
		var flag_remesas = false;
		var id_remesas = "";
		var id_remesas_checked = "";

		$(".check_remesas").each(function() {
			id_remesas += $(this).val() + ",";

			if ($(this).prop("checked")) {
				flag_remesas = true;
				id_remesas_checked += $(this).val() + ",";
			}
		});

		if (flag_remesas) {
			// console.log("Se han seleccionado remesas");
			var lista_remesas = id_remesas_checked;
		} else {
			// console.log("No se han seleccionado remesas");
			var lista_remesas = id_remesas;
		}
		// console.log(lista_remesas);

		var url = $("#id_url_ajax").val() + 'libs/helisa_ajax.php?action=generaExcelPedidos&id_remesas=' + lista_remesas;
		// console.log(url);

		$("#generarExcelHelisa").attr("href", url);
	}
</script>