<?php
	$_dbTable = "monedas"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/

	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->facturacion) /* && count($this->facturacion) */){

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_view = '
			<div class="row">
				<div class="col-sm-3"></div>
				<div class="col-sm-6">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover" data-page-length="100">
							<thead>
								<tr class="nexos-encabezado">
									<th>Fecha Creación</th>
									<th style="width: 15%;">Cant Remesas</th>
									<th style="width: 15%;">Cant Manifiestos</th>
									<th style="width: 15%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayFacturacion = $this->facturacion->getListaRemesasDescargadas();
		if ($arrayFacturacion['descargas']) {
			foreach ($arrayFacturacion['descargas'] as $key => $value) {
				// Se maqueta contenido de la tabla 
				$table_view.= '<tr>';
				$table_view.= '
					<td class="cell-detail">
						<span>' . $value["fecha_creacion"] . '</span>
					</td>
					<td class="cell-detail">
						<span class="label label-default">' . $arrayFacturacion['cant_remesas'][$value['id']] . '</span>
					</td>
					<td class="cell-detail">
						<span class="label label-default">' . $arrayFacturacion['cant_manifiestos'][$value['id']] . '</span>
					</td>
					<td class="actions">
						<a href="javascript:" class="cell-detail hint--top-left" data-hint="Ver contenido" onclick="verdatosArchivo(\'' . $value["lista_remesas"] . '\',\'' . $value["fecha_creacion"] . '\')" ><span class="icon mdi mdi-eye" data-toggle="modal" data-target="#ver_archivo"></span></a>
						<a href="' . BASE_URL . 'libs/helisa_ajax.php?action=descargaExcelPedidos&id_remesas=' . $value["lista_remesas"] . '&fecha_creacion=' . $value["fecha_creacion"] . '" class="icon hint--top-left" data-hint="Descargar archivo"><span class="mdi mdi-grid"></span></a>
					</td>
				';
				
				$table_view.= '</tr>';
			}
		}
		$table_view.= '
							</tbody>
						</table>
					</div>
				</div>
			</div>
		';
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Lista de Archivos Generados - Facturación
				<div class="tools"></div>
				<span class="panel-subtitle">Lista de archivos que se han generado para ser usados en el sistema contable Helisa.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>

		<div id="ver_archivo" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
			<div class="modal-dialog custom-width">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
						<h3 class="modal-title">Datos del archivo</h3>
					</div>
					<div class="modal-body">
						<div class="nexos-messages_popups"></div>
						<div id="contenido_pedidos"></div>
						<div class="row"></div>
					</div>
					<div class="modal-footer">
						<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cerrar</button>
					</div>
				</div>
			</div>
		</div>
	';


  	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>

	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_view , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>

<script type="text/javascript">
	// FUNCIONES JS DEL MÓDULO 
	function verdatosArchivo(lista_remesas, fecha_creacion){
		// console.log("Entro en funcion de verdatosArchivo");
		$(".nexos-messages_popups").empty();

		var params = {
			lista_remesas	: lista_remesas,
			fecha_creacion	: fecha_creacion
		};

		$.ajax({
			type		: "POST",
			cache		: false,
			url			: $("#id_url_ajax").val() + "libs/helisa_ajax.php?action=verDatosPedido",
			data		: params,
			dataType	: "json",
			error 		: function (jqXHR, textStatus, errorThrown){
				$(".nexos-messages_popups").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong><p>' + jqXHR.responseText + '</p></div></div>');
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			},
			success		: function(data) {
				// console.log(data);
				$("#contenido_pedidos").html(data.table_content);
			}
		});
	}
</script>


