<div class="nexos-content">
  <div class="row" style="margin:-25px -25px -25px -25px;">
    <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
      <tbody>
        <tr>
          <td class="celda_titulo2 text-left" style="margin:25px;"><b>Tabla Citas Itr</b></td>
          <td class="celda_titulo2 text-right" style="margin:25px;">
            <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#form-bp1"><i class="far fa-calendar-plus"></i> Agregar Cita</button>
          </td>
        </tr>
      </tbody>
    </table>
    <!-- <form method="POST" action=""></form> -->
    <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
      <thead>
        <tr>
          <th style="background-color: #F5F5F5;font-weight: bold;font-size: 12px; border: 1px solid #ddd; width: auto; white-space: nowrap;" class="text-left">Tipo:</th>
          <td style="border: 1px solid #ddd; width: auto; white-space: nowrap;">
            <select id="tipo" name="tipo" style="width: 100%;height: 23px;">
              <option value="">Seleccione</option>
              <option value="cita">Numero Cita</option>
              <option value="manifiesto">Manfiesto</option>
            </select>
          </td>
          <th style="background-color: #F5F5F5; font-weight: bold; font-size: 12px; border: 1px solid #ddd; width: auto; white-space: nowrap;" class="text-left"> Carácter Búsqueda:</th>
          <td style="border: 1px solid #ddd; width: auto; white-space: nowrap;">
            <input type="text" id="buscador" name="buscador" onblur="mayuscula(this);" style="width: 100%;">
          </td>
          <th style="background-color: #F5F5F5; font-weight: bold; font-size: 12px; border: 1px solid #ddd; width: auto; white-space: nowrap;" class="text-left"> Acción:</th>
          <td style="border: 1px solid #ddd; width: auto; white-space: nowrap;">
            <button class="btn btn-success btn-xs" id="busqueda" name="busqueda" style="width: 100%;height: 23px;"><i class="fas fa-search"></i> Buscar</button>
          </td>
        </tr>
      </thead>
    </table>

    <!-- <form method="POST" action=""></form> -->
    <div class="row">
      <!-- <div class="row"></div> -->
      <div class="col-sm-12">
        <!-- <div class="table-responsive noSwipe"></div> -->
        <!--<table id='table1' class='table table-striped table-hover tablavehicular' data-page-length='100'>-->
        <table cellpadding="0" cellspacing="0" width="100%" border="1">
          <thead style="background-color:#332D2D;color:#fff;text-align:center;">
            <tr>
              <th class="text-center" style="width: auto; white-space: nowrap;">#</th>
              <th class="text-center" style="width: auto; white-space: nowrap;">Manifiesto</th>
              <th class="text-center" style="width: auto; white-space: nowrap;">Puerto</th>
              <th class="text-center" style="width: auto; white-space: nowrap;">Numero Cita</th>
              <th class="text-center" style="width: auto; white-space: nowrap;">Fecha Cita</th>
              <th class="text-center" style="width: auto; white-space: nowrap;">Hora Cita</th>
              <th class="text-center" style="width: auto; white-space: nowrap;">Estado</th>
              <th class="text-center" style="width: auto; white-space: nowrap;">Fecha/Hora</th>
              <th class="text-center" style="width: auto; white-space: nowrap;">Documento</th>
              <th class="text-center" style="width: auto; white-space: nowrap;">Usuario</th>
              <th class="text-center" style="width: auto; white-space: nowrap;">Acciones</th>
            </tr>
          </thead>
          <tbody id="tbody_citas_puerto"></tbody>
        </table>

      </div>
    </div>
  </div>
  <!-- Modal para agregar las citas -->
  <div class="modal fade" id="form-bp1" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header modal-header-colored" style="background-color:#332D2D;color:#fff;text-align:left;height: 50px;padding:19px;">
          <button class="close md-close" type="button" data-dismiss="modal" aria-hidden="true" style="color: #ffffff;"><span class="mdi mdi-close"> </span></button>
          <h4 class="modal-title" style="color: #ffffff;font-weight: 700;"><i class="fa-regular fa-calendar-days"></i> Agregar Cita</h4>
        </div>
        <div class="modal-body" style="padding: 1px 1px 1px;">
          <!-- <div class="row"></div> -->
          <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
            <tbody>
              <tr>
                <td class="celda_titulo2 text-center" style="margin:25px;">
                  <b>Datos de la cita</b>
                </td>
              </tr>
              <tr>
              </tr>
            </tbody>
          </table>
          <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
            <thead>
              <tr>
                <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Puerto:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                  <select name="puerto" id="puerto" style="width: 100%;height: 24px;">
                    <option value="" selected>Seleccione</option>
                    <option value="Sociedad Portuaria Buenaventura">Sociedad Portuaria Buenaventura</option>
                    <option value="Aguadulce Buenaventura">Aguadulce Buenaventura</option>
                    <option value="Tcbuen">TCBUEN</option>
                  </select>
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Numero Cita:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="text" id="numero_cita" style="width: 100%;">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Fecha Cita:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap; ">
                  <input type="date" id="fecha_cita" style="width: 100%;">
                </td>
              </tr>
              <tr>
                <th style="background-color: #F5F5F5; width: 150px; font-weight: bold;font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Hora Cita:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; padding: 1px 1px 1px; width: auto; white-space: nowrap;">
                  <input type="time" id="hora_cita" style="width: 100%;height: 24px;">
                </td>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Manifiesto:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  <input type="number" id="manifiesto" style="width: 100%;">
                </td>
                <td id="valdiar_manifiesto" style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="2"></td>
              </tr>
              <tr>
                <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Documento cita:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;" colspan="5">
                  <input type="file" name="documento_cita" id="documento_cita" style="width: 100%;" accept="pdf">
                </td>
                <!-- <th style="background-color: #F5F5F5; width: 250px; font-weight: bold; font-size: 12px; border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  Fecha:&nbsp;<span style="color:red;"><i>(*)</i></span></th>
                <td style="border: 1px solid #ddd; padding: 1px; width: auto; white-space: nowrap;">
                  <input type="text" id="timeInput" placeholder="Ingrese la hora aquí" style="width: 100%;">
                </td> -->
              </tr>
            </thead>
          </table>
          <div class="text-center">
            <embed id="pdfPreview" type="application/pdf" / style="width: 100%;height: 500px;">
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary md-close" type="button" data-dismiss="modal">Cancelar</button>
          <button class="btn btn-primary md-close" type="button" id="btn_guardar_asignacion">Proceder</button>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/typeahead.bundle.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/transporte/js/asignacion_citas.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/js/main.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

<!-- js para creacion de data-tables -->
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/js/app-tables-datatables.js" type="text/javascript"></script>

<!-- js para creacion de formularios dinamicos -->
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/select2/js/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/daterangepicker/js/daterangepicker.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/moment.js/min/moment.min.js" type="text/javascript"></script>

<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>

<script src="<?php echo BASE_URL; ?>views/layout/assets/js/app-form-elements.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
<script type="text/javascript">
  $(document).ready(function() {
    //initialize the javascript
    App.init();
    App.dataTables();
  });
  $(document).ready(function() {
    //initialize the javascript
    App.wizard();
    App.formElements();
  });

  $(document).ready(function() {});
</script>
<script type="text/javascript">
  function mayuscula(elemento) {
    let texto = elemento.value;
    elemento.value = texto.toUpperCase();
  }

  //edicion
  function docutransit(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#newtransi").val('');
    } else {
      $("#newtransi").val(fic[fic.length - 1]);
    }
  }

  function docusoat(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#newso").val('');
    } else {
      $("#newso").val(fic[fic.length - 1]);
    }
  }

  function docuteno(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#newte").val('');
    } else {
      $("#newte").val(fic[fic.length - 1]);
    }
  }

  function docufronta(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#newavf").val('');
    } else {
      $("#newavf").val(fic[fic.length - 1]);
    }
  }

  function docuderec(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#newavd").val('');
    } else {
      $("#newavd").val(fic[fic.length - 1]);
    }
  }

  function docuizqui(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#newavi").val('');
    } else {
      $("#newavi").val(fic[fic.length - 1]);
    }
  }

  function docuatras(fic) {
    fic = fic.split('\\');
    if (fic == '' || fic == null) {
      $("#newava").val('');
    } else {
      $("#newava").val(fic[fic.length - 1]);
    }
  }


  //creacion
  function vtransito(fic) {
    var input = document.getElementById('foto_transi'); // Reemplaza 'tuInputFile' con el ID de tu input file
    var archivo = input.files[0];
    if (archivo) {
      var nombreArchivo = archivo.name;
      var extension = nombreArchivo.split(".").pop().toLowerCase();
      var extensionesPermitidas = ["pdf", "jpg", "png", "webp"]; // Lista de extensiones permitidas
      if (extensionesPermitidas.indexOf(extension) === -1) {
        let mensaje = `
            <div class="alert alert-primary alert-icon alert-icon-border alert-dismissible" role="alert">
                <div class="icon"><i class="fas fa-info"></i></div>
                <div class="message">
                  <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                  <strong>Mensaje!</strong> Extensión de archivo no permitida. Por favor, selecciona un archivo con una de las siguientes extensiones: ${extensionesPermitidas.join(", ")}
                </div>
            </div>`;
        $("#crea_vehiculos").animate({
          scrollTop: 0
        }, 600);
        document.getElementById("historicos").innerHTML = mensaje;
        input.value = ""; // Limpia el campo de entrada
      } else {
        fic = fic.split('\\');
        if (fic == '' || fic == null) {
          $("#name_transi").val('');
        } else {
          $("#name_transi").val(fic[fic.length - 1]);
        }
      }
    }
  }

  function vtecno(fic) {
    var input = document.getElementById('foto_tecno'); // Reemplaza 'tuInputFile' con el ID de tu input file
    var archivo = input.files[0];
    if (archivo) {
      var nombreArchivo = archivo.name;
      var extension = nombreArchivo.split(".").pop().toLowerCase();
      var extensionesPermitidas = ["pdf", "jpg", "png", "webp"]; // Lista de extensiones permitidas
      if (extensionesPermitidas.indexOf(extension) === -1) {
        let mensaje = `
            <div class="alert alert-primary alert-icon alert-icon-border alert-dismissible" role="alert">
                <div class="icon"><i class="fas fa-info"></i></div>
                <div class="message">
                  <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                  <strong>Mensaje!</strong> Extensión de archivo no permitida. Por favor, selecciona un archivo con una de las siguientes extensiones: ${extensionesPermitidas.join(", ")}
                </div>
            </div>`;
        $("#crea_vehiculos").animate({
          scrollTop: 0
        }, 600);
        document.getElementById("historicos").innerHTML = mensaje;
        input.value = ""; // Limpia el campo de entrada
      } else {
        fic = fic.split('\\');
        if (fic == '' || fic == null) {
          $("#name_tecno").val('');
        } else {
          $("#name_tecno").val(fic[fic.length - 1]);
        }
      }
    }
  }


  function vsoat(fic) {
    var input = document.getElementById('foto_soat'); // Reemplaza 'tuInputFile' con el ID de tu input file
    var archivo = input.files[0];
    if (archivo) {
      var nombreArchivo = archivo.name;
      var extension = nombreArchivo.split(".").pop().toLowerCase();
      var extensionesPermitidas = ["pdf", "jpg", "png", "webp"]; // Lista de extensiones permitidas
      if (extensionesPermitidas.indexOf(extension) === -1) {
        let mensaje = `
            <div class="alert alert-primary alert-icon alert-icon-border alert-dismissible" role="alert">
                <div class="icon"><i class="fas fa-info"></i></div>
                <div class="message">
                  <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                  <strong>Mensaje!</strong> Extensión de archivo no permitida. Por favor, selecciona un archivo con una de las siguientes extensiones: ${extensionesPermitidas.join(", ")}
                </div>
            </div>`;
        $("#crea_vehiculos").animate({
          scrollTop: 0
        }, 600);
        document.getElementById("historicos").innerHTML = mensaje;
        input.value = ""; // Limpia el campo de entrada
      } else {
        fic = fic.split('\\');
        if (fic == '' || fic == null) {
          $("#name_soat").val('');
        } else {
          $("#name_soat").val(fic[fic.length - 1]);
        }
      }
    }
  }

  function vfrente(fic) {
    var input = document.getElementById('foto_vehiculo'); // Reemplaza 'tuInputFile' con el ID de tu input file
    var archivo = input.files[0];
    if (archivo) {
      var nombreArchivo = archivo.name;
      var extension = nombreArchivo.split(".").pop().toLowerCase();
      var extensionesPermitidas = ["pdf", "jpg", "png", "webp"]; // Lista de extensiones permitidas
      if (extensionesPermitidas.indexOf(extension) === -1) {
        let mensaje = `
            <div class="alert alert-primary alert-icon alert-icon-border alert-dismissible" role="alert">
                <div class="icon"><i class="fas fa-info"></i></div>
                <div class="message">
                  <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                  <strong>Mensaje!</strong> Extensión de archivo no permitida. Por favor, selecciona un archivo con una de las siguientes extensiones: ${extensionesPermitidas.join(", ")}
                </div>
            </div>`;
        $("#crea_vehiculos").animate({
          scrollTop: 0
        }, 600);
        document.getElementById("historicos").innerHTML = mensaje;
        input.value = ""; // Limpia el campo de entrada
      } else {
        fic = fic.split('\\');
        if (fic == '' || fic == null) {
          $("#name_frontal").val('');
        } else {
          $("#name_frontal").val(fic[fic.length - 1]);
        }
      }
    }
  }

  function vderecha(fic) {
    var input = document.getElementById('foto_vehiculod'); // Reemplaza 'tuInputFile' con el ID de tu input file
    var archivo = input.files[0];
    if (archivo) {
      var nombreArchivo = archivo.name;
      var extension = nombreArchivo.split(".").pop().toLowerCase();
      var extensionesPermitidas = ["pdf", "jpg", "png", "webp"]; // Lista de extensiones permitidas
      if (extensionesPermitidas.indexOf(extension) === -1) {
        let mensaje = `
            <div class="alert alert-primary alert-icon alert-icon-border alert-dismissible" role="alert">
                <div class="icon"><i class="fas fa-info"></i></div>
                <div class="message">
                  <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                  <strong>Mensaje!</strong> Extensión de archivo no permitida. Por favor, selecciona un archivo con una de las siguientes extensiones: ${extensionesPermitidas.join(", ")}
                </div>
            </div>`;
        $("#crea_vehiculos").animate({
          scrollTop: 0
        }, 600);
        document.getElementById("historicos").innerHTML = mensaje;
        input.value = ""; // Limpia el campo de entrada
      } else {
        fic = fic.split('\\');
        if (fic == '' || fic == null) {
          $("#name_derecha").val('');
        } else {
          $("#name_derecha").val(fic[fic.length - 1]);
        }
      }
    }

  }

  function vizquierda(fic) {
    var input = document.getElementById('foto_vehiculoi'); // Reemplaza 'tuInputFile' con el ID de tu input file
    var archivo = input.files[0];
    if (archivo) {
      var nombreArchivo = archivo.name;
      var extension = nombreArchivo.split(".").pop().toLowerCase();
      var extensionesPermitidas = ["pdf", "jpg", "png", "webp"]; // Lista de extensiones permitidas
      if (extensionesPermitidas.indexOf(extension) === -1) {
        let mensaje = `
            <div class="alert alert-primary alert-icon alert-icon-border alert-dismissible" role="alert">
                <div class="icon"><i class="fas fa-info"></i></div>
                <div class="message">
                  <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                  <strong>Mensaje!</strong> Extensión de archivo no permitida. Por favor, selecciona un archivo con una de las siguientes extensiones: ${extensionesPermitidas.join(", ")}
                </div>
            </div>`;
        $("#crea_vehiculos").animate({
          scrollTop: 0
        }, 600);
        document.getElementById("historicos").innerHTML = mensaje;
        input.value = ""; // Limpia el campo de entrada
      } else {
        fic = fic.split('\\');
        if (fic == '' || fic == null) {
          $("#name_izquierda").val('');
        } else {
          $("#name_izquierda").val(fic[fic.length - 1]);
        }
      }
    }
  }

  function vatras(fic) {
    var input = document.getElementById('foto_vehiculoa'); // Reemplaza 'tuInputFile' con el ID de tu input file
    var archivo = input.files[0];
    if (archivo) {
      var nombreArchivo = archivo.name;
      var extension = nombreArchivo.split(".").pop().toLowerCase();
      var extensionesPermitidas = ["pdf", "jpg", "png", "webp"]; // Lista de extensiones permitidas
      if (extensionesPermitidas.indexOf(extension) === -1) {
        let mensaje = `
            <div class="alert alert-primary alert-icon alert-icon-border alert-dismissible" role="alert">
                <div class="icon"><i class="fas fa-info"></i></div>
                <div class="message">
                  <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                  <strong>Mensaje!</strong> Extensión de archivo no permitida. Por favor, selecciona un archivo con una de las siguientes extensiones: ${extensionesPermitidas.join(", ")}
                </div>
            </div>`;
        $("#crea_vehiculos").animate({
          scrollTop: 0
        }, 600);
        document.getElementById("historicos").innerHTML = mensaje;
        input.value = ""; // Limpia el campo de entrada
      } else {
        fic = fic.split('\\');
        if (fic == '' || fic == null) {
          $("#name_atras").val('');
        } else {
          $("#name_atras").val(fic[fic.length - 1]);
        }
      }
    }

  }
</script>
<!-- fin del contenido  -->

<div class="footer navbar-fixed-bottom">
  <div class="row" style="height:25px;background-color:#37474F;margin:0px;color:white;padding:5px;text-align:center;font-size:10pt">
    <div class="col-lg-12">
      <span> Nexos Group S.a.S / Bogota - Colombia / Logistica - Almacenamiento - Transporte de Carga Multimodal /
        Nacional e Internacional
      </span>
    </div>
  </div>


  <div id="divProcessing" align="center" style="display: none;background :#FFFFFF;">
    <span id="divProcessMessage" style="max-width: 100px;"></span>
    <img src="http://localhost/mvcLuisMiguel/views/layout/assets/img/spinner.gif"><br><br>
  </div>

  <script src="http://localhost/mvcLuisMiguel/views/layout/assets/js/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>
  <script src="http://localhost/mvcLuisMiguel/views/layout/assets/lib/nexos.min.js" type="text/javascript"></script>

</div>
</div>