<div class="panel panel-border panel-contrast">
	<div class="panel-heading panel-heading-contrast">
		Cumplidos
		<div class="tools"> </div>
		<span class="panel-subtitle">El módulo de Cumplido nos permite cerrar el despacho de operaciones y trasladar el proceso a la legalicacion en contabilidad.</span>
		<div class=" col-xs-12 col-sm-4 col-md-12">
			<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'">
			<input type="hidden" id="elperfil" class="form-control input-sm" readonly="readonly" value="0">
		</div>
	</div>
	<div class="panel-body">
		<div class="nexos-messages"></div>
		<div class="nexos-content">
			<div class="row">
				<div class="col-xs-4 col-sm-5 col-md-4 col-lg-4">
					<label>Filtrar por</label>
					<select id="filtro" class="form-control input-sm">
						<option value="">Seleccione</option>
						<option value="1">Número Manifiesto</option>
						<option value="2">Fecha</option>
					</select>
				</div>
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 fec">
					<label>Fecha inicial</label>
					<input type="date" id="finicial" class="form-control input-xs" value="<?php echo date('Y-m-d'); ?>">
				</div>
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 fec">
					<label>Fecha final</label>
					<input type="date" id="ffinal" class="form-control input-xs" value="<?php echo date('Y-m-d'); ?>">
				</div>
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 num">
					<label>Número Manifiesto</label>
					<input type="number" id="numnani" class="form-control input-sm">
				</div>
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 btn">
					<br><button id="buscar_cumplido" class="btn btn-primary btn-sm">Buscar</button>
				</div>
			</div><br>

			<div class="row" id="contenedor_datos">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="panel panel-border-color panel-border-color-dark">
						<div class="panel-heading">
							<p id="titulo"></p>
						</div>
						<div class="panel-body" id="bodycontenido">
							<div class="row">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<label>N° cumplido</label>
									<input type="text" id="c_cumpli" class="form-control text-center input-xs text-white bg-dark campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label>Placa</label>
									<input type="text" id="c_placa" class="form-control input-xs text-white bg-dark campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label>Manifiesto</label>
									<input type="text" id="c_manifi" class="form-control input-xs campov" readonly="readonly">
								</div>

								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label>Conductor</label>
									<input type="text" id="c_nombre" class="form-control input-xs text-white bg-dark  campov" readonly="readonly" title="Nombre conductor">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label>Número de identificación</label>
									<input type="text" id="c_numero" class="form-control input-xs text-white bg-dark campov" readonly="readonly" title="Número de identificación">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label>Propietario</label>
									<input type="text" id="c_propieta" class="form-control input-xs text-white bg-dark  campov" readonly="readonly" title="Nombre conductor">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label>Número de identificación</label>
									<input type="text" id="c_propinumero" class="form-control input-xs text-white bg-dark campov" readonly="readonly" title="Número de identificación">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label>Poseedor</label>
									<input type="text" id="c_posee" class="form-control input-xs text-white bg-dark  campov" readonly="readonly" title="Nombre conductor">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label>Número de identificación</label>
									<input type="text" id="c_poseenumero" class="form-control input-xs text-white bg-dark campov" readonly="readonly" title="Número de identificación">
								</div>
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<label>Novedad</label>
									<input type="text" id="c_novedad" class="form-control input-xs text-white bg-dark campov" readonly="readonly" title="Novedad">
								</div>


							</div>
							<div class="row">
								<hr>
								<table class="table table-bordered" border="1" cellpading="2">
									<thead>
										<tr class="text-center">
											<td>Remesa</td>
											<td>Fecha</td>
											<td>Hora</td>
											<td>Observación</td>
											<td>Tipo</td>
										</tr>
									</thead>
									<tbody id="tabla_remesas"></tbody>
								</table>
							</div>
							<div class="row"></div>
							<br><button id="btn_imprimir" class="btn-success btn-xs" title="Imprimir cumplido">Imprimir</button>
						</div>
					</div>
				</div>
			</div>

			<div class="row" id="tabla_datos">
				<hr>
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class='table-responsive noSwipe'>
						<table id='table1' class='table table-striped table-hover' data-page-length='100'>
							<thead>
								<tr class='nexos-encabezado'>
									<th>Estado</th>
									<th>Cumplido</th>
									<th>Manifiesto</th>
									<th>Placa</th>
									<th style='width:10%;min-width: 10%;'>Acciones</th>
								</tr>
							</thead>
							<tbody id="cumplidobody">
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12"></div>
	</div>
</div>
</div>

<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src=<?php echo BASE_URL; ?>/views/transporte/js/tbcumplidoajax.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>


<script type="text/javascript">
	$(document).ready(function() {
		//initialize the javascript
		App.init();
		//App.wizard();
	});
</script>