<div class="nexos-content">
    <div class="row" style="margin:-25px -39px -10px -39px;">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
                <tbody>
                    <tr>
                        <td class="celda_titulo2 text-center" style="margin:25px;">
                            <b>Gesti&oacute;n Precintos por documentos</b>
                        </td>
                    </tr>
                </tbody>
            </table>
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;font-size: 12px;">
                <thead>
                    <tr>
                        <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Fecha Inicial:</th>
                        <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
                            <input type="date" id="fecha_inicial" name="fecha_inicial" style="width: 100%;" value="<?php echo date("Y-m-d") ?>" disabled>
                        </td>

                        <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Fecha Final:</th>
                        <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
                            <input type="date" id="fecha_final" name="fecha_final" style="width: 100%;" value="<?php echo date("Y-m-d") ?>" disabled>
                        </td>

                        <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Orden Cargue:</th>
                        <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
                            <input type="number" id="num_criterio" name="num_criterio" style="width: 100%;height: 23px;">
                        </td>

                        <th style="background-color: #F5F5F5; width: auto;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Filtro:</th>
                        <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;" class="text-center">
                            <button type="button" class="btn btn-primary btn-xs" id="filtrar"><i class="fas fa-filter"></i> Buscar Documento</button>
                        </td>
                    </tr>
                </thead>
            </table>

            <!-- <div class="table-responsive" id="tbl_datos" style="display: none;"> -->
            <div id="tbl_datos" style="display: none;margin-bottom: 5px;">
                <table class="table-striped" cellpadding="0" cellspacing="0" border="0" style="width: 100%;" style="border: #332D2D;" id="informe_precintos">
                    <thead style="border-collapse: collapse;background-color: #332D2D;color:#fff;">
                        <tr>
                            <th style="width: auto; white-space: nowrap; padding-left: 5px;" class="text-center"><b>Manifiesto</b></th>
                            <th style="width: auto; white-space: nowrap; padding-left: 5px;" class="text-center"><b>Remesa</b></th>
                            <th style="width: auto; white-space: nowrap; padding-left: 5px;" class="text-center"><b>Orden Cargue</b></th>
                            <th style="width: auto; white-space: nowrap; padding-left: 5px;" class="text-center"><b>Agencia</b></th>
                        </tr>
                    </thead>
                    <tbody id="tbody-documentos-precintos" style="border-collapse: collapse;font-size: 12px;">
                        <div id="tablaVaciaMensaje" style="display: none;">No hay datos disponibles</div>
                    </tbody>
                </table>
            </div>

            <div id="tbl_datos_precintos" style="display: none;margin-bottom: 5px;">
                <table class="table-striped" cellpadding="0" cellspacing="0" border="0" style="width: 100%;" style="border: #332D2D;" id="informe_precintos">
                    <thead style="border-collapse: collapse;background-color: #332D2D;color:#fff;">
                        <tr>
                            <th style="width: auto; white-space: nowrap; padding-left: 5px;" class="text-center"><b>Numero Precinto</b></th>
                            <th style="width: auto; white-space: nowrap; padding-left: 5px;" class="text-center"><b>Tipo Precinto</b></th>
                            <th style="width: auto; white-space: nowrap; padding-left: 5px;" class="text-center"><b>Fecha Asignaci&oacute;n</b></th>
                            <!-- <th style="width: auto; white-space: nowrap; padding-left: 5px;" class="text-center"><b>Agencia</b></th> -->
                        </tr>
                    </thead>
                    <tbody id="tbody-precintos-asociados" style="border-collapse: collapse;font-size: 12px;">
                        <div id="tablaVaciaMensaje" style="display: none;">No hay datos disponibles</div>
                    </tbody>
                </table>
            </div>

            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;margin-bottom: 2px;margin-top: 5px;">
                <tbody>
                    <tr>
                        <td class="celda_titulo2 text-center" style="margin:25px;">
                            <b>Listar Precintos disponibles</b>
                        </td>
                    </tr>
                </tbody>
            </table>

            <div class="row">
                <div style="display: flex; justify-content: center;">
                    <table class="table-striped" id="tabla_precintos" style="width: 50%; border: #332D2D;">
                        <thead style="border-collapse: collapse; font-size: 12px; background-color: #332D2D; color: #fff;">
                            <tr>
                                <th class="text-center" style="white-space: nowrap;">#</th>
                                <th class="text-center" style="white-space: nowrap;">Tipo precinto</th>
                                <th class="text-center" style="white-space: nowrap;">Código precinto</th>
                                <th class="text-center" style="white-space: nowrap;">Acción</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
                <div class="text-center" style="margin-top: 5px;">
                    <button class="btn btn-primary btn-xs" onclick="agregarFilaPrecinto()">
                        <i class="fa-solid fa-square-plus"></i> Agregar precinto
                    </button>
                </div>
            </div>

            <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;margin-bottom: 2px;margin-top: 5px;">
                <tbody>
                    <tr>
                        <td class="celda_titulo2 text-center" style="margin:25px;">
                            <b></b>
                        </td>
                    </tr>
                </tbody>
            </table>

            <table cellpadding="0" cellspacing="0" width="100%" border="0">
                <tbody>
                    <tr>
                        <td style="padding: 1px;width: auto; white-space: nowrap;" class="text-right">
                            <!-- <div class="row text-right"> -->
                            <button id="Registrar_precintos" class="btn btn-success btn-xs offset-10"><i class="fa-regular fa-floppy-disk"></i> Guardar precintos</button>

                        </td>
                    </tr>
                </tbody>
            </table>



        </div>
    </div>
</div>

<div id="loading-overlay-nexosapp" class="loading-nexosapp">
    <div style="text-align: center;">
        <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
        <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso...</h2>
        <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
    </div>
</div>

<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js
    type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src=<?php echo BASE_URL; ?>/views/transporte/js/gestion_precinto.js type="text/javascript"></script>

<!-- js para creacion de formularios dinamicos -->
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


<script type="text/javascript">
    $(document).ready(function() {
        //initialize the javascript
        App.init();
    });
</script>