<div class="nexos-content">
  <div class="row" style="margin:-25px -39px -20px -39px;">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#FFFFFF;font-weight: bold;">
        <tbody>
          <tr>
            <td class="celda_titulo2 text-center" style="margin:25px;">
              <b>Subasta</b>
            </td>
          </tr>
          <tr></tr>
        </tbody>
      </table>
      <!-- <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;font-size: 10px;">
        <thead>
          <tr>
            <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">Filtro:</th>
            <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
              <select id="filtro_subastaa" style="width: 100%;">
                <option value="fecha">Fecha</option>
                <option value="placa">Placa</option>
                <option value="ss">solicitud servicio</option>
              </select>
            </td>
            <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">Busqueda:</th>
            <section id="seccion_fecha">
              <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
                <input type="date" id="fec_incio" style="width: 100%;" value="<?php echo date('Y-m-d'); ?>">
              </td>
              <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
                <section id="seccion_fecha"></section>
                <input type="date" id="fec_final" style="width: 100%;" value="<?php echo date('Y-m-d'); ?>">
              </td>
            </section>
            <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
              <section id="seccion_placa" class="col-xs-6 col-sm-6 col-md-6">
                <input type="text" id="placa" class="form-control input-sm col-xs-6 col-sm-6 col-md-6">
              </section>
              <section id="seccion_ss" class="col-xs-6 col-sm-6 col-md-6">
                <input type="number" id="sservicio" class="form-control input-sm col-xs-6 col-sm-6 col-md-6">
              </section>
            </td>
            <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
              <button type="button" class="btn btn-primary btn-xs" id="buscar_datos"><i class="fa-solid fa-magnifying-glass"></i> Buscar</button>
            </td>
          </tr>
        </thead>
      </table> -->
      <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;font-zise: 8px;">
        <thead>
          <tr>
            <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">Filtro:</th>
            <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
              <select id="filtro_subastaa" class="form-control input-xs">
                <option value="fecha">Fecha</option>
                <option value="placa">Placa</option>
                <option value="ss">solicitud servicio</option>
              </select>
            </td>
            <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">Busqueda:</th>
            <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
              <section id="seccion_fecha">
                <div class="row">
                  <div class="col-xs-4 col-sm-4 col-md-6">
                    <input type="date" id="fec_incio" class="form-control input-xs " value="<?php echo date('Y-m-d'); ?>">
                  </div>
                  <div class="col-xs-4 col-sm-4 col-md-6">
                    <input type="date" id="fec_final" class="form-control input-xs " value="<?php echo date('Y-m-d'); ?>">
                  </div>
                </div>
              </section>
              <section id="seccion_placa" class="col-xs-6 col-sm-6 col-md-6">
                <input type="text" id="placa" class="form-control input-sm col-xs-6 col-sm-6 col-md-6">
              </section>
              <section id="seccion_ss" class="col-xs-6 col-sm-6 col-md-6">
                <input type="number" id="sservicio" class="form-control input-sm col-xs-6 col-sm-6 col-md-6">
              </section>
            </td>
            <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
              <button type="button" class="btn btn-primary btn-xs" id="buscar_datos"><i class="fa-solid fa-magnifying-glass"></i> Buscar</button>
            </td>
          </tr>
        </thead>
      </table>
      <div class="table-responsive" id="tabla_filtro">
        <table cellpadding="0" cellspacing="0" border="0" style="width: 100%;" style="border: #332D2D;" id="informe_placas_asignadas" class="table table-striped table-hover table-condensed">
          <thead style="border-collapse: collapse;background-color: #332D2D;color:#fff;">
            <tr>
              <th class="text-center"><b>#</b></th>
              <th class="text-center"><b>Subasta</b></th>
              <th class="text-center"><b>Fecha inicio - final</b></th>
              <th class="text-center"><b>Fecha registro</b></th>
              <th class="text-center"><b>Solicitud(es) Servicio</b></th>
              <th class="text-center"><b>Placa(s)</b></th>
              <th class="text-center"><b>Estado Solicitud</b></th>
              <th class="text-center"><b>Estado Subasta</b></th>
              <th class="text-center"><b>Acción</b></th>
            </tr>
          </thead>
          <tbody id="tbl_subasta" style="border-collapse: collapse;font-size: 10px;"></tbody>
        </table>
      </div>

    </div>
  </div>
</div>
<br><br><br>

<!-- Contenedor -->
<div class="nexos-content" id="contenedor_dato">
  <div class="row" style="margin:-25px -39px -20px -39px;">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <div id="msg_present" class="col-xs-12 col-sm-12 col-md-12 col-lg-12"></div>
          <div class="row">
            <!--contenedor de  solicitudes de servicio-->
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <b class="mg_title"></b>
              </div>
              <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 FP2">
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 FP">
                <br>
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>Estudio de seguridad</th>
                      <th>Flete Propuesto</th>
                      <th>Flete sugerido</th>
                      <th>Estado flete</th>
                      <th>Traza estado</th>
                      <th>Realizado por</th>
                      <th>Accioón</th>
                    </tr>
                  </thead>
                  <tbody id="tabla_placas">
                  </tbody>
                </table>
              </div>
              <!--contenedor de  estudio de seguridad-->
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 FT">
                <section>
                  <h5 class="text-center"><strong>Estudio de seguridad</strong></h5>
                </section>
                <table class="table table-bordered">
                  <thead>
                    <td>Id subasta</td>
                    <td>Num servicio</td>
                    <td>Placa</td>
                    <td>Conductor</td>
                    <td>Núm estudio</td>
                    <td>Estado</td>
                  </thead>
                  <tbody id="cuerpo_estado">
                  </tbody>
                </table>
              </div>
              <!--contenedor de  calculo de vehículos-->
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 FM">
                <div class="col-xs-12 col-sm-12 col.md-12 col-lg-12 MSG"></div>
                <section>
                  <h5 class="text-center"><strong>Cálculo de vehículos</strong></h5>
                </section>
                <table class="table table-striped table-hover">
                  <thead>
                    <th>Subasta</th>
                    <th>Fecha inicio</th>
                    <th>Fecha final</th>
                    <th>estado</th>
                  </thead>
                  <tbody id="cuerpo_calculo">
                  </tbody>
                </table>
                <label><strong>Vehículos Aprobados</strong></label>
                <table class="table table-bordered table-hover">
                  <thead>
                    <td>Id subasta</td>
                    <td>Placa</td>
                    <td>Conductor</td>
                    <td>Núm estudio</td>
                    <td>Flete ganador</td>
                    <td>Estado</td>
                  </thead>
                  <tbody id="cuerpo_estado2">
                  </tbody>
                </table>

                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                  <label>Valor flete propuesto</label>
                  <input type="text" id="flete_ganador" class="form-control input-xs" readonly="readonly">
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                  <label>Id Flete</label>
                  <input type="text" id="id_fleteg" class="form-control input-xs" readonly="readonly">
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                  <label>Subasta</label>
                  <input type="text" id="n_subasta" class="form-control input-xs" readonly="readonly">
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                  <label>Placa</label>
                  <input type="text" id="splaca" class="form-control input-xs" readonly="readonly">
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                  <br><input type="" id="estadofle" class="form-control input-xs text-center" readonly="readonly">
                </div>
              </div>
            </div>
            <div class="row text-center">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
  <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
  <script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
  <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
  <script src=<?php echo BASE_URL; ?>/views/transporte/js/subasta_solaajax.js type="text/javascript"></script>
  <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
  <script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
  <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

  <script type="text/javascript">
    $(document).ready(function() {
      //initialize the javascript
      App.init();
    });
  </script>
  <!--Final del control de los submenús-->