<div class="container">
  <div class="row">
    <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11">
      <div class="panel panel-default">
        <div class="panel-body">
          <div id="msg_present" class="col-xs-12 col-sm-12 col-md-12 col-lg-12"></div>
          <div class="row">
            <section>
              <H3 class="text-center"><strong>Subasta de fletes</strong></H2>
            </section>
            <!--filtro -->
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <label>Tipo</label>
              <select id="tipo" class="form-control input-sm">
                <option value="">Seleccione</option>
                <option value="1">Placa</option>
              </select>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 Impdato">
              <label>Dato</label>
              <input type="text" id="dato" class="form-control input-sm">
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 Impdato">
              <br><button id="buscar_datos" class="btn-success btn-sm">Buscar</button>
            </div>
          </div>

          <div class="row" id="contenedor_dato">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <h3>Subasta</h3>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <label>Fletes propuestos</label>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 FP">
            </div>
          </div>



          <div class="row" id="tabla_filtro">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Subasta</th>
                  <th>Fecha inicio/final</th>
                  <th>Vence en</th>
                  <th>Usuario</th>
                  <th>N° servicio</th>
                  <th class="actions">Acción</th>
                </tr>
              </thead>
              <tbody id="filtro_subasta">
              </tbody>
            </table>
          </div>

          <div class="row text-center">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript">
</script>
<!--Control de los submenus-->
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>/views/transporte/js/subastaajax.js type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

<script type="text/javascript">
  $(document).ready(function() {
    //initialize the javascript
    App.init();
    App.wizard();
  });
</script>
<!--Final del control de los submenús-->