<div class="panel panel-border panel-contrast">
	<!-- <div class="panel-heading panel-heading-contrast">
		Remesa
		<div class="tools"> </div>
		<span class="panel-subtitle">Es el contrato que se tiene entre la empresa de transporte y el cliente, el cual asegura la mercancía y permite generar el cobro de este servicio al cliente.</span>
	</div> -->
	<div class=" col-xs-12 col-sm-4 col-md-12">
		<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'">
		<input type="hidden" id="elperfil" class="form-control input-sm" readonly="readonly" value="0">
	</div>
	<div class="panel-body">
		<div class="nexos-messages"></div>
		<div class="nexos-content">
			<div class="row">
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfiltro">
					<label>Filtrar</label>
					<select id="filtro" class="form-control input-xs">
						<option value="">Seleccionar</option>
						<option value="1">Fecha</option>
						<option value="2">Cliente</option>
						<option value="3">Cliente & Fecha</option>
					</select>
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divcliente">
					<label>Cliente</label>
					<select id="clientefiltro" class="form-control input-xs">
						<option value="">Seleccionar</option>
					</select>
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfechas">
					<label>Fecha inicial</label>
					<input type="date" id="finicial" class="form-control input-xs" value="<?php echo date('Y-m-d'); ?>">
					<!-- <label>Fecha final</label>
					<input type="date" id="ffinal" class="form-control input-xs" value="<?php echo date('Y-m-d'); ?>"> -->
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfechas">
					<!-- <label>Fecha inicial</label>
					<input type="date" id="finicial" class="form-control input-xs" value="<?php echo date('Y-m-d'); ?>"> -->
					<label>Fecha final</label>
					<input type="date" id="ffinal" class="form-control input-xs" value="<?php echo date('Y-m-d'); ?>">
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divbtnbusqueda">
					<br><button id="buscar_remesa" class="btn btn-primary btn-sm">Buscar</button>
				</div>
			</div><br>

			<div class="row" id="contenedor_datos">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="panel panel-border-color panel-border-color-dark">
						<div class="panel-heading">
							<p id="titulo"></p>
						</div>
						<div class="panel-body" id="bodycontenido">

							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<input type="hidden" id="id_servicio" class="form-control">
							</div>
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label>N° remesa</label>
									<input type="text" id="c_remesa" class="form-control text-center input-xs text-white bg-dark campov" readonly="readonly">
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label>N° orden</label>
									<input type="text" id="c_orden" class="form-control text-center input-xs text-white bg-dark campov" readonly="readonly">
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label>Fecha</label>
									<input type="text" id="c_fecha" class="form-control text-center input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label>Oficina</label>
									<input type="text" id="c_oficina" class="form-control text-center input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label>Placa</label>
									<input type="text" id="c_placa" class="form-control input-xs text-white bg-dark campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label>Conductor</label>
									<input type="text" id="c_nombre" class="form-control input-xs text-white bg-dark  campov" readonly="readonly" title="Nombre conductor">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label>Número de identificación</label>
									<input type="text" id="c_numero" class="form-control input-xs text-white bg-dark campov" readonly="readonly" title="Número de identificación">
								</div>
							</div><br>
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" style="border-right:1px solid gray;">
									<label>Remitente</label>
									<input type="text" id="c_remitente" class="form-control input-xs campov" readonly="readonly">
									<label>Ciudad</label>
									<input type="text" id="c_remciudad" class="form-control input-xs campov" readonly="readonly">
									<label>Dirección</label>
									<input type="text" id="c_remdireccion" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" style="border:1px solid white;">
									<label>Destinatario</label>
									<input type="text" id="c_destinatario" class="form-control input-xs campov" readonly="readonly">
									<label>Ciudad</label>
									<input type="text" id="c_desciudad" class="form-control input-xs campov" readonly="readonly">
									<label>Dirección</label>
									<input type="text" id="c_desdireccion" class="form-control input-xs campov" readonly="readonly">
								</div>
							</div><br>
							<div class="row">
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label>Valor declarado</label><br>
									<label>XXXXXX</label>
									<input type="hidden" id="c_flete" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
									<label>Producto transportado</label>
									<input type="text" id="c_producto" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label>Naturaleza</label>
									<input type="text" id="c_natu" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label>Aplica seguro</label>
									<select id="c_seguro" class="form-control input-xs campov" readonly="readonly"></select>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label>Remesa contado</label>
									<select id="c_remesac" class="form-control input-xs campov" readonly="readonly"></select>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label>Remesa contra entrega</label>
									<select id="c_remcontra" class="form-control input-xs campov" readonly="readonly"></select>
								</div>
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<label>Descripción novedad</label>
									<textarea id="c_descripcion" class="form-control input-xs campov" readonly="readonly"></textarea>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label>Archivo</label>
									<label id="documento"></label>
								</div>

							</div>
							<br>
							<div class="row text-center btn1">
								<button id="btn_actualizar" class="btn-success btn-xs" title="Actualizar">Actualizar</button>
							</div>
							<div class="row">
								<div class="col-md-12">
									<div class="panel panel-border-color panel-border-color-success">
										<div class="panel-heading"><strong>Consulta Oet</strong></div>
										<div class="panel-body" id="panel_oet">
										</div>
									</div>
								</div>
							</div>
							<div class="row text-center btn2">
								<button id="btn_imprimir" class="btn-danger btn-xs" title="Imprimir remesa">PDF</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12"></div>
	</div>
</div>
<div class="row" id="tabla_datos">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<div class='table-responsive noSwipe'>
			<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;font-size: 8px;">
				<thead>
					<tr>
						<td class="text-center" style="padding: 1px 1px 1px;width: auto; white-space: nowrap;">
							<span class="label label-primary" style="font-size: 13px;"><b>Numero de Remesas:</b> <span class="badge">0</span></span>
							<!-- <div class="text-center"></div> -->
						</td>
						<td class="text-right" style="padding: 1px 1px 1px;width: auto; white-space: nowrap;">
							<a href="JavaScript:void(0);" id="exportar_excel" style="text-decoration: none;cursor: pointer;color: #332D2D;"><img src="http://principal.nexosapp.com/public/img/excel_2013.png" alt="Excel" width="15px"> <span style="font-size: 11px;"> Exportar a excel</span></a>
						</td>
					</tr>
				</thead>
			</table>
			<table id='ordenes_remesa_export' class='table table-striped table-hover' data-page-length='100'>
				<thead style="background-color:#332D2D;color:#fff;text-align:center;">
					<tr>
						<th>Estado</th>
						<th>Remesa - Orden</th>
						<th>Placa</th>
						<th>Conductor</th>
						<th>Observación</th>
						<th>Fecha-Hora</th>
						<th>acciones</th>
					</tr>
				</thead>
				<tbody id="remesabody">
				</tbody>
			</table>
		</div>
	</div>
</div>
</div>


<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src=<?php echo BASE_URL; ?>/views/transporte/js/tbremesaajax.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>
<script src="https://cdn.sheetjs.com/xlsx-0.19.3/package/dist/xlsx.mini.min.js"></script>

<script type="text/javascript">
	$(document).ready(function() {
		//initialize the javascript
		App.init();
		//App.wizard();
	});
</script>