<div class="panel panel-border panel-contrast">
	<!-- <div class="panel-heading panel-heading-contrast">
		Orden de cargue
		<div class="tools"> </div>
		<span class="panel-subtitle">Es un documento que acompaña a la carga en donde estan de acuerdo el despachador y el transportista de acuerdo a los bienes que estan transportando.</span>

		</div> -->
	<div class=" col-xs-12 col-sm-4 col-md-12">
		<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'">
		<input type="hidden" id="elperfil" class="form-control input-sm" readonly="readonly" value="0">
	</div>

	<div class="panel-body">
		<div class="nexos-messages"></div>
		<div class="nexos-content">
			<div class="row">
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfiltro">
					<label>Filtrar</label>
					<select id="filtro" class="form-control input-xs">
						<option value="">Seleccionar</option>
						<option value="1">Fecha</option>
						<option value="2">Cliente</option>
						<option value="3">Cliente & Fecha</option>
					</select>
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divcliente">
					<label>Cliente</label>
					<select id="clientefiltro" class="form-control input-xs">
						<option value="">Seleccionar</option>
					</select>
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfechas">
					<label>Fecha inicial</label>
					<input type="date" id="finicial" class="form-control input-xs" value="<?php echo date('Y-m-d'); ?>">
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divfechas">
					<label>Fecha final</label>
					<input type="date" id="ffinal" class="form-control input-xs" value="<?php echo date('Y-m-d'); ?>">
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 divbtnbusqueda">
					<br><button id="buscar_orden" class="btn btn-primary btn-sm">Buscar</button>
				</div>
			</div><br>

			<div class="row" id="contenedor_datos">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="panel panel-border-color panel-border-color-dark">
						<div class="panel-heading">
							<p id="titulo"><strong></strong></p>
						</div>
						<div class="panel-body" id="bodycontenido">
							<div class="row">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<label><strong>N° orden</strong></label>
									<input type="text" id="c_orden" class="form-control text-center input-xs text-white bg-dark campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Placa</strong></label>
									<input type="text" id="c_placa" class="form-control input-xs text-white bg-dark campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Color</strong></label>
									<input type="text" id="c_color" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Marca</strong></label>
									<input type="text" id="c_marca" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label><strong>Carroceria</strong></label>
									<input type="text" id="c_carroceria" class="form-control input-xs campov" readonly="readonly">
								</div>

								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label><strong>Módelo</strong></label>
									<input type="text" id="c_modelo" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Conductor</strong></label>
									<input type="text" id="c_nombre" class="form-control input-xs text-white bg-dark  campov" readonly="readonly" title="Nombre conductor">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Número de identificación</strong></label>
									<input type="text" id="c_numero" class="form-control input-xs text-white bg-dark campov" readonly="readonly" title="Número de identificación">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Número de celular</strong></label>
									<input type="text" id="c_celular" class="form-control input-xs text-white bg-dark  campov" readonly="readonly" title="Números telefónicos">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Tipo vinculación</strong></label>
									<input type="text" id="c_tipovin" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Clase del vehículo</strong></label>
									<input type="text" id="c_clase" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Remolque</strong></label>
									<input type="text" id="c_remolque" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Valor Flete</strong></label>
									<input type="text" id="c_flete" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-6 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Valor Flete Pactado</strong></label>
									<input type="text" id="c_fletep" class="form-control input-xs campov" readonly="readonly">
								</div>
							</div>
							<div class="row">
								<hr>
								<table class="table table-bordered" border="1" cellpading="2">
									<thead>
										<tr class="text-center">
											<td>Cliente</td>
											<td>Origen</td>
											<td>Dirección</td>
											<td>Fecha</td>
											<td>Hora</td>
											<td>Observación</td>
											<td>Tipo</td>
										</tr>
									</thead>
									<tbody id="tabla_cremitente"></tbody>
								</table>
							</div>
							<div class="row"></div>
							<div class="row"></div>
							<div class="row">
								<hr>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Producto</strong></label>
									<input type="text" id="c_producto" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Tipo empaque</strong></label>
									<input type="text" id="c_empaque" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Cantidad</strong></label>
									<input type="text" id="c_cant" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Volumen(m3)</strong></label>
									<input type="text" id="c_volumen" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
									<label><strong>Peso mercancía</strong></label>
									<input type="text" id="c_pesom" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label><strong>Contenedor 1</strong></label>
									<input type="text" id="c_con1" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<label><strong>Contenedor 2</strong></label>
									<input type="text" id="c_con2" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<label><strong>Observaciones</strong></label>
									<input type="text" id="c_obs" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<label><strong>Condiciones</strong></label>
									<input type="text" id="c_condi" class="form-control input-xs campov" readonly="readonly">
								</div>
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<label><strong>Embalaje</strong></label>
									<input type="text" id="c_laje" class="form-control input-xs campov" readonly="readonly">
								</div>
							</div>
							<div class="row">
								<br>
								<div class="col-md-12">
									<div class="panel panel-border-color panel-border-color-success">
										<div class="panel-heading"><strong>Consulta OET</strong></div>
										<div class="panel-body" id="panel_oet">
										</div>
									</div>
								</div>
							</div>
							<br><button id="btn_imprimir" class="btn-success btn-xs" title="Imprimir orden">Imprimir</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12"></div>
	</div>
</div>

<!-- Tabla de lista  -->
<div class="row" id="tabla_datos">
	<!-- <hr> -->
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<div class='table-responsive noSwipe'>
			<table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;font-size: 8px;">
				<thead>
					<tr>
						<td class="text-center" style="padding: 1px 1px 1px;width: auto; white-space: nowrap;">
							<span class="label label-primary" style="font-size: 13px;"><b>Numero de ordenes de cargue:</b> <span class="badge">0</span></span>
							<!-- <div class="text-center"></div> -->
						</td>
						<td class="text-right" style="padding: 1px 1px 1px;width: auto; white-space: nowrap;">
							<a href="JavaScript:void(0);" id="exportar_excel" style="text-decoration: none;cursor: pointer;color: #332D2D;"><img src="http://principal.nexosapp.com/public/img/excel_2013.png" alt="Excel" width="15px"> <span style="font-size: 11px;"> Exportar a excel</span></a>
						</td>
					</tr>
				</thead>
			</table>
			<table id="ordenes_decargue_export" class='table table-striped table-hover table-condensed' data-page-length='100'>
				<thead style="background-color:#332D2D;color:#fff;text-align:center;">
					<tr>
						<th class="text-center" style="color: white;width: auto; white-space: nowrap;">Estado</th>
						<th class="text-center" style="color: white;width: auto; white-space: nowrap;">Orden</th>
						<th class="text-center" style="color: white;width: auto; white-space: nowrap;">Cliente</th>
						<th class="text-center" style="color: white;width: auto; white-space: nowrap;">Placa</th>
						<th class="text-center" style="color: white;width: auto; white-space: nowrap;">Conductor</th>
						<th class="text-center" style="color: white;width: auto; white-space: nowrap;">carga (Kg)</th>
						<th class="text-center" style="color: white;width: auto; white-space: nowrap;">Condiciones</th>
						<th class="text-right" style="color: white;width: auto; white-space: nowrap;">acciones</th>
					</tr>
				</thead>
				<tbody id="ordenbody">
				</tbody>
			</table>
		</div>
	</div>
</div>
</div>

<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src=<?php echo BASE_URL; ?>/views/transporte/js/tbordenajax.js type="text/javascript"></script>

<!-- js para creacion de formularios dinamicos -->
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>
<script src="https://cdn.sheetjs.com/xlsx-0.19.3/package/dist/xlsx.mini.min.js"></script>

<script type="text/javascript">
	$(document).ready(function() {
		//initialize the javascript
		App.init();
		App.wizard();
	});
</script>