<div class="nexos-content">
  <div class="row" style="margin:-25px -39px -10px -39px;">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
        <tbody>
          <tr>
            <td class="celda_titulo2 text-center" style="margin:25px;">
              <b>Configuración de correo de envios a clientes</b>
            </td>
          </tr>
          <tr>
          </tr>
        </tbody>
      </table>
      <div id="config_inicial"> <!-- style="display: none;" -->
        <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;">
          <tbody>
            <tr>
              <td class="celda_titulo2" style="margin:25px;padding: 5px;">
                <b>Seleccionar cliente para crear la configuración</b>
              </td>
            </tr>
            <tr>
            </tr>
          </tbody>
        </table>
        <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;font-zise: 8px;">
          <thead>
            <tr>
              <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Cliente:</th>
              <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
                <select name="cliente" id="cliente" style="width: 100%;height: 24px;" class="select2">
                  <option value="" selected>Seleccioonar..</option>
                </select>
              </td>
              <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Correo Automatico:</th>
              <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
                <input type="checkbox" id="correo_automatico" name="correo_automatico" style="width: 100%;transform: scale(1.5);">
              </td>
              <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Correo Manual:</th>
              <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
                <input type="checkbox" id="correo_manual" name="correo_manual" style="width: 100%;transform: scale(1.5);">
              </td>
              <th style="background-color: #F5F5F5; width: 250px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">Acción:</th>
              <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
                <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
                <button type="button" class="btn btn-primary btn-xs" id="aplicar_filtro" style="width: 100%;height: 24px;"><i class="fas fa-save"></i> Guardar Configuración</button>
              </td>
            </tr>
          </thead>
        </table>

        <!-- <div class="table-responsive"> </div> -->
        <table cellpadding="0" cellspacing="0" border="0" style="width: 100%;" style="border: #332D2D;" id="informe_responsable_placas">
          <thead style="border-collapse: collapse;background-color: #332D2D;color:#fff;">
            <tr>
              <!-- <th class="text-center"><b>Pedido</b></th> -->
              <th class="text-center"><b>#</b></th>
              <th class="text-center"><b>Novedad</b></th>
              <th class="text-center"><b>Reporta Cliente</b></th>
              <th class="text-center"><b>Reporte Sac</b></th>
            </tr>
          </thead>
          <tbody id="tbl_asignar_configuracion" style="border-collapse: collapse;font-size: 12px;">
          </tbody>
        </table>
      </div>

      <div id="confgiuracion_contactos" style="display: none;">
        <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;border-top: 1px #fff solid;">
          <tbody>
            <tr>
              <td class="celda_titulo2" style="margin:25px;padding: 5px;">
                <b>Configurar las notas por contacto del cliente</b>
              </td>
            </tr>
            <tr>
            </tr>
          </tbody>
        </table>
        <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;">
          <thead>
            <tr>
              <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Cliente:</th>
              <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;" class="text-center" id="nombre_cliente"></td>
              <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Nombre del grupo:</th>
              <td style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;" class="text-center" id="nombre_grupo"></td>
              <th style="background-color: #F5F5F5; width: 200px;font-weight: bold;border: 1px solid #ddd;padding: 5px;">Contactos del grupo:</th>
              <td class="text-right" style="border: 1px solid #ddd;padding: 1px;width: auto; white-space: nowrap;">
                <span class="badge badge-success" id="cantidad_contacto">0</span>
              </td>
            </tr>
          </thead>
        </table>

        <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
          <tbody>
            <tr>
              <td class="celda_titulo2 text-center" style="margin:25px;">
                <b>Contactos del cliente</b>
              </td>
            </tr>
            <tr>
            </tr>
          </tbody>
        </table>

        <div id="contactos">
          <div class="row" id="contactos_grupo"></div>
        </div>

        <div class="col-sm-12 col-xs-12 col-sm-12 col-md-12 col-lg-12" style="margin-top: 25px;">
          <p class="text-center">
            <button class="btn btn-space btn-primary btn-sm" type="button" id="btn_registrar_configuracion"><i class="far fa-save"></i> Registrar</button>
            <button class="btn btn-space btn-secondary btn-sm"><i class="far fa-window-close"></i> Cancelar</button>
          </p>
        </div>
      </div>

      <!-- <ul class="mt-2" style="display: flex; flex-wrap: wrap;" id="novedades_trafico"></ul> -->
      <!-- <div id="novedades_trafico"></div> -->
    </div>
  </div>
</div>



<!-- Mensajes para los usuarios de la plataforma -->
<div id="loading-overlay-nexosapp" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para NexosAPP...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
  </div>
</div>

<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src=<?php echo BASE_URL; ?>/views/parametros/js/configuracion_correo.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
<script type="text/javascript">
  $(document).ready(function() {
    //initialize the javascript
    App.init();
  });
</script>