<div class="panel panel-border panel-contrast">
	<div class="panel-heading panel-heading-contrast">
		Detalle de Ruta
		<div class="tools">
			<a id="btn_crea" href="#" data-toggle="modal" class="cell-detail  hint--top " data-hint="" data-target="#crear_plan"><span class="icon mdi mdi-plus" title="Agregar Punto"></span></a>
		</div>
		<span class="panel-subtitle">Módulo para la creación de puntos de ruta.</span>
	</div>
	<div class="panel-body">
		<div class="nexos-messages"></div>
		<div class="nexos-content">
			<div class="col-xs-12 col-sm-12 col-md-12">
				<div class="form-group col-xs-4 col-sm-4 col-md-4">
					<label>Ubicación del Punto</label>
					<select class="form-control input-sm" id="Punto">
						<option value="" readonly="readonly">Seleccione</option>
					</select>
				</div>
				<div class="form-group col-xs-3 col-sm-3 col-md-3">
					<br>
					<button class="form-control input-sm btn btn-info mdi mdi-search" id="consulte">
						Consultar
					</button>
				</div>
			</div>
			<!--TABLA PRINCIPAL -->
			<div id="esconder">
				<div class="row">
					<div class="col-sm-12">
						<div class="table-responsive noSwipe">
							<table id="table1" class="table table-striped table-hover table-fw-widget">
								<thead>
									<tr>
										<th title="Estado">#</th>
										<th>Ubicación</th>
										<th>Nombre Punto</th>
										<th>Latitud / Longitud</th>
										<th>Acción</th>
									</tr>
								</thead>
								<tbody id="cuerpo_tabla">
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12"></div>
		</div>
	</div>
</div>

<div id="crear_plan" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary" style="overflow-y: scroll;">
	<div class=".modal-dialog-modal-lg.modal-dialog ">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
				<h3 class="modal-title" id="editar_title">
					<label id="titulo" style="font-size:20pt; color:white; text-align:center;">Crear Punto</label>
				</h3>
			</div>
			<div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
				<div id="msg_crear"></div>
				<div id="content_editar">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<h3 class="text-center">
							<p style="font-size:20pt; font-weight:500; color:#2E2E2E;">Crear Punto</p>
						</h3>
					</div>
					<div class="row">
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<label style="font-weight:800; margin-top:20px;">Nombre Punto(*)</label>
							<input type="text" id="p_punto" class="form-control input-sm">
						</div>
						<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
							<label style="font-weight:800; margin-top:20px;">Ubicación(*)</label>
							<select id="municipio" class="form-control input-sm">
								<option value="">Seleccione</option>
							</select>
						</div>
						<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
							<label style="font-weight:800; margin-top:20px;">Latitud(*)</label>
							<input type="number" id="latitud" class="form-control input-sm">
						</div>
						<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
							<label style="font-weight:800; margin-top:20px;">Longitud(*)</label>
							<input type="number" id="longitud" class="form-control input-sm">
						</div>
						<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
							<label style="font-weight:800; margin-top:20px;">Tipo punto</label>
							<select id="tipo_punto" class="form-control input-sm">
								<option value="">Seleccione</option>
								<!-- <option value="punto control">Punto físico</option> -->
								<option value="punto geografico">Punto Control</option>
							</select>
						</div>
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<label style="font-weight:800; margin-top:20px;">Descripción(*)</label>
							<textarea id="p_descri" class="form-control input-sm"></textarea>
						</div>

						<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
							<label style="font-weight:800; margin-top:20px;">Usuario</label>
							<input type="text" id="user" class="form-control input-sm" readonly="readonly"
								value="<?php echo $_SESSION["usuario"]["nom_usuario"]; ?>">
						</div>
						<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
							<label style="font-weight:800; margin-top:20px;">Fecha</label>
							<input type="text" id="fecha" class="form-control input-sm" readonly="readonly" value="<?php echo date('Y-m-d'); ?>">
						</div>
						<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
							<label style="font-weight:800; margin-top:20px;">Hora</label>
							<input type="text" id="hora" class="form-control input-sm" readonly="readonly" value="<?php echo date('H:i:s'); ?>">
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button id="btn_guadarpoint" type="button" class="btn btn-success md-close" onclick="">Guardar</button>
				<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
			</div>
		</div>
	</div>
</div>
</div>


<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src=<?php echo BASE_URL; ?>views/parametros/js/punto_ruta.js type="text/javascript"></script>

<!-- js para creacion de formularios dinamicos -->
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>



<script type="text/javascript">
	$(document).ready(function() {
		//initialize the javascript
		App.init();
		//App.wizard();
	});
</script>