<div class="panel panel-border panel-contrast">
	<div class="panel-heading panel-heading-contrast">
		Reglas de Módulo
		<div class="tools">	 
		<a href="#" data-toggle="modal" id="crear_regla" class="cell-detail  hint--top"  data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a>  
		</div>
		<span class="panel-subtitle">
      En este apartado se puede parametrizar las diferentes reglas que requieren cada módulo para su funcionamiento, de acuerdo a la estructura de cada uno.
    	</span>
		<div class=" col-xs-12 col-sm-4 col-md-12">
			<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="'. $ssn_nombre .'" >
			<input type="hidden" id="elperfil" class="form-control input-sm" readonly="readonly" value="0">
		</div>
	</div>
	<div class="panel-body">
		<div class="nexos-messages"></div>
		<div class="nexos-content">
			<section class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<h5>Consultar Reglas de Negocio</h5>
				</div>
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
					<label><strong>(*) Módulo</strong></label>
					<select id="modulo_cambio" class="form-control input-sm">
						<option value="">Seleccione</option>
						<option value="CO">Cotización</option>
						<option value="SS">Solicitud de Servicio</option>
						<option value="SE">Solicitud de Estudio</option>
						<option value="SU">Subasta</option>
						<option value="ES">Estudio de Seguridad</option>
						<option value="OC">Orden de cargue</option>
						<option value="RM">Remesa</option>
						<option value="MNF">Manifiesto</option>
						<option value="PLR">Plan de ruta</option>
						<option value="SEG">Seguimiento</option>
						<option value="SA">Sálida</option>
						<option value="TC">Tiempos logísticos de cargue</option>
						<option value="TD">Tiempos logísticos de descargue</option>
						<option value="LG">LLegada</option>
						<option value="CU">Cumplido</option>
					</select>
				</div>
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
						<br>
						<button id="busca_reglas" class="btn-primary">Buscar</button>
				</div>
			</section><br>
			<section class="row" id="contenedor_datos">
				<div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
					<div class="panel panel-border-color panel-border-color-dark">
						<div class="panel-heading">
					    <p id="titulo"><strong></strong></p>
					    </div>
					    <div class="panel-body" id="bodycontenido">
					    </div>	
					</div>
				</div>
			</section><br>
			<section class="row" id="contenedor_tabla">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div  class='table-responsive noSwipe'>
					<table id='table1' class='table table-striped table-hover' data-page-length='100'>
						<thead>
							<tr class='nexos-encabezado'>
								<th>Estado</th>
								<th>Regla</th>
								<th>Valor</th>	
								<th>Objetivo</th>
								<th style='width:10%;min-width: 10%;'>Acciones</th>
							</tr>
						</thead>
						<tbody id="contenido_tabla">
						</tbody>
					</table>
					</div>
				</div>
			</section>
		</div>	
	</div>

	   <script src=<?php echo BASE_URL;?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/js/main.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
	  	 <script src=<?php echo BASE_URL;?>views/parametros/js/regla_negocio.js type="text/javascript"></script>
	  	 
		<!-- js para creacion de formularios dinamicos -->
	    <script src=<?php echo BASE_URL;?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
	    <script src=<?php echo BASE_URL;?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>
	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			
	    </script> 