<?php
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
$vista = '';
$table_content = '';
$sw1 = "n";
$_GET["sw"] = "";
$_GET["nameprove"] = "";
$_POST["nameprove"] = "";
$_POST["numero"] = "";
$_POST["buscar_tipo"] = "";

$table_content .= "<div class='row'>
	<div class='col-sm-3'>
		<label>Tipo:</label>
		<select id='tipotb' class='form-control input-sm'>
			<option value=''>Seleccione</option>	
			<option value='2'>Documento</option>
			<option value='1'>Nombre</option>
			</select>	
		</div>

		<div class='col-sm-3 fnum'>
				<label>Número documento:</label>
				<input  type='number' id='docuprove' class='form-control input-sm'>
		</div>
		<div class='col-sm-3 fnom'>
				<label>Nombre:</label>
				<input  type='text' id='nameprove' class='form-control input-sm'>
		</div>
		<div class='col-sm-3'>
		<br>
		<button class='btn btn-success btn-md' id='buscar_coti' name='buscar_coti'>Buscar</button>
	</div>
	</div><br>";



if (isset($_GET["i"]) == 1) {
	$table_content .= "<div class='row'>
		<div class='col-sm-12'>
			<div  class='table-responsive noSwipe'>
				<table id='table2' class='table table-striped table-hover' data-page-length='100'>
					<thead>
						<tr class='nexos-encabezado'>
							<th>#</th>
							<th>Documento</th>
							<th>Nombre Completo</th>
							<th>Tipo actividad</th>
							<th style='width:10%;min-width: 10%;'>acciones</th>
						</tr>
					</thead>
					<tbody>";
	$arrayPermisos = $this->tipo_pro->permisosPerfil($ssn_id_perfil, 126);
	$_permisos = $arrayPermisos;
	if ($_GET["i"] == 1) {
		$tipo = $_GET["a"]; //tipo de busqueda
		$numero = $_GET["c"];
		$nombre = $_GET["b"];
	}
	$array = $this->tipo_pro->getProveedores($tipo, $numero, $nombre);
	if ($array) {
		print_r("<pre>");
		print_r($array);
	}
	if ($array) {

		foreach ($array as $key => $valor) {
			$btn_editar = '';
			if ($_permisos['editar']) {
				$btn_editar = '
						<button	 
						type="button" class="btn-secondary btn btn-xs" data-placement="top" 
						<a href="javascript:" onclick="edita_t_proveedor(this)" class="cell-detail hint--top-left" data-hint="" 
						data-id="' . $valor['numdoc_nexos'] . '">
						<span class="icon mdi mdi-edit" data-toggle="modal" data-target="#tipo_proveedor" title="Editar actividad proveedor">
						</span>
						</a> </button> ';
			}

			if ($valor['estado'] == 'Activo') {
				$_col_status = '
									<td class="text" style="color:green;">
										<center>
										<span class="mdi mdi-dot-circle icon"  data-toggle="tooltip" title="Activo" ></span>
										</center>
									</td>';
			}

			if ($valor['estado'] == 'Inactivo') {
				$_col_status = '
									<td class="text" style="color:red;">
										<center>
										<span class="mdi mdi-dot-circle icon"  data-toggle="tooltip" title="Inactivo" ></span>
										</center>
									</td>';
			}


			$table_content .= '
				<tr>
					' . $_col_status . '
					<td>' . $valor['numero_documento'] . '</td>
					<td>' . $valor['nombre'] . ' ' . $valor['apellido1'] . ' ' . $valor['apellido2'] . '</td>
					<td></td>
					<td>	
						' . $btn_editar . '
					</td>	
				</tr>';
		}
	}
	$table_content .= "</tbody>
					</table>
				</div>
			</div>
		</div>";
}

$vista .= '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Tipo de proveedor
				<div class="tools">
				<!--	<a id="btn_crea" href="#"  data-toggle="modal"  class="cell-detail  hint--top "  data-hint="Agregar" data-target="#crea_estudio" ><span class="icon mdi mdi-plus"></span></a>  -->
				</div>
				<span class="panel-subtitle">
				Módulo para adicionar o retirar el tipo de proveedor que tenga un tercero en el sistema (Conductor, Poseedor, Propietario, Proveedor)
				</span>
				<div class=" col-xs-12 col-sm-4 col-md-12">
					<input type="hidden" id="ee_usuario" class="form-control input-sm" readonly="readonly" value="' . $ssn_nombre . '" >
				</div>
			</div>
			<div class="panel-body">
				<div class="nexos-messages"></div>
				<div class="nexos-content">
					%content%
				</div>
				<div class="row">
				<div class="col-sm-12"></div>
				</div>
			</div>
		</div>
';
?>


<div id="tipo_proveedor" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
	<div class="modal-dialog custom-width">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
				<h3 class="modal-title" id="editar_title">
					<label id="titulo" style="font-size:16pt; color:white; font-weight:800; ">Editar tipo proveedor</label>
				</h3>
			</div>
			<div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
				<div id="msg_editar"></div><!-- id para manejar los mensajes de errordel popup -->
				<div id="msg_informativo"></div>
				<div id="content_editar">
					<div class=" col-xs-12 col-sm-12 col-md-12">
						<input type="hidden" id="condu_ligado">
						<input type="hidden" id="id_proveedor" class="form-control">
					</div>
					<div class="form-group col-xs-12 col-sm-12 col-md-12">
						<label style="font-weight:800; margin-top:20px; ">Tipo de actividad actual</label><br>
						<div class="be-checkbox inline">
							<input class="v_tipo_actividad" id="v_Conductor" type="checkbox">
							<label for="v_Conductor">Conductor</label>
						</div>
						<div class="be-checkbox inline">
							<input class="v_tipo_actividad" id="v_poseedor_vehiculo" type="checkbox">
							<label for="v_poseedor_vehiculo">Poseedor Vehículo</label>
						</div>
						<div class="be-checkbox inline">
							<input class="v_tipo_actividad" id="v_propietario_vehiculo" type="checkbox">
							<label for="v_propietario_vehiculo">Propietario Vehículo</label>
						</div>
						<div class="be-checkbox inline">
							<input class="v_tipo_actividad" id="v_Proveedor" type="checkbox">
							<label for="v_Proveedor">Proveedor</label>
						</div>
					</div>
					<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<label style="font-weight:800; margin-top:20px;">Datos registrados actualmente:</label><br>
						<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
							<label>Datos Básicos</label>
							<input type="text" id="basic_data" class="form-control input-sm" disabled="disabled" value="si">
						</div>
						<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
							<label>Datos Conductor</label>
							<input type="text" id="driver_data" class="form-control input-sm" disabled="disabled">
						</div>
						<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
							<label>Datos proveedor</label>
							<input type="text" id="supplier_data" class="form-control input-sm" disabled="disabled">
						</div>
						<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
							<label>Datos propietario</label>
							<input type="text" id="dueno_data" class="form-control input-sm" disabled="disabled">
						</div>
						<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
							<label>Datos poseedor</label>
							<input type="text" id="holder_data" class="form-control input-sm" disabled="disabled">
						</div>
					</div>
					<!--Datos basicos -->
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div id="accordion1" class="panel-group accordion">
							<div class="panel panel-default" id="basic">
								<div class="panel-heading">
									<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#collapseOne"><i class="icon mdi mdi-chevron-down"></i>Datos básicos</a></h4>
								</div>
								<div id="collapseOne" class="panel-collapse collapse in">
									<div class="panel-body">
										<div class="row">
											<label>Nombre o Razón social:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
											<input type="text" id="e_rndc_nombre" placeholder="Nombre o Razón social" class="form-control input-sm des" disabled="disabled">
											<input type="hidden" id="e_nombre" placeholder="" readonly="readonly">
											<label id="error_e_rndc_nombre"></label>
										</div>

										<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
											<label>Primer apellido:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
											<input type="text" id="e_rndc_apellido1" class="form-control input-sm" disabled="disabled">
										</div>
										<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
											<label>Segundo apellido:</label>
											<input type="text" id="e_rndc_apellido2" class="form-control input-sm" disabled="disabled">
										</div>

										<div class="col-xs-12 col-sm-8 col-md-8">
											<label>Abreviatura:</i></span></label>
											<input type="text" id="e_abreviatura" placeholder="Abreviatura" class="form-control input-sm des" disabled="disabled">
											<label id="error_e_abreviatura"></label>
										</div>
										<div class="col-xs-12 col-sm-4 col-md-4">
											<label>Tipo de documento:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
											<input type="text" id="e_tipo_documento" class="form-control input-sm des" readonly="" disabled="disabled">
											<label id="e_error_tipo_documento"></label>
										</div>
										<div class="col-xs-12 col-sm-4 col-md-5">
											<label>Número de documento:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
											<input type="text" id="e_numero_documento" placeholder="Número de documento" class="form-control input-sm des" disabled="disabled">
											<label id="e_error_numero_documento"></label>
										</div>
										<div class="col-xs-12 col-sm-4 col-md-3">
											<label>Tipo de identificación:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
											<input type="text" id="e_tipo_identificacion" class="form-control input-sm des" disabled>
										</div>
										<div class="col-xs-6 col-sm-3 col-md-4">
											<label>Teléfono Fijo Contacto:</label>
											<input type="text" id="e_contacto" placeholder="Teléfono Contacto" maxlength="7" class="form-control input-sm des" disabled="disabled">
											<label id="error_e_contacto"></label>
										</div>
										<div class="col-xs-6 col-sm-3 col-md-3">
											<label>Celular Contacto:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
											<input type="text" id="e_celular" placeholder="Celular Contacto" maxlength="10" class="form-control input-sm des" disabled="disabled">
											<label id="error_e_celular"></label>
										</div>
										<div class="col-xs-6 col-sm-3 col-md-4 CelularContacto">
											<label>Celular Contacto 2:&nbsp;<span style="color:blue;"><i>(*)</i></span></label>
											<input type="text" id="e_celular2" placeholder="Celular Contacto" maxlength="10" class="form-control input-sm des" disabled="disabled">
											<label id="error_celular"></label>
										</div>
										<div class="col-xs-12 col-sm-6 col-md-5">
											<label>Correo electrónico:</label>
											<input type="text" id="e_email" placeholder="Correo electrónico" class="form-control input-sm des" disabled="disabled">
											<label id="e_error_email"></label>
										</div>
										<div class="col-xs-12 col-sm-12 col-md-4">
											<label>Estado:</label>
											<select id="e_estado" class="form-control input-sm des" disabled="disabled">
												<option value="Activo">Activo</option>
												<option value="Inactivo">Inactivo</option>
											</select>
											<label id="e_error_estado"></label>
										</div>
										<div class="col-xs-12 col-sm-6 col-md-4">
											<label>Municipio:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
											<input type="text" id="e_municipio" class="form-control input-sm" disabled="disabled">
											<label id="e_error_municipio"></label>
										</div>
										<div class="col-xs-12 col-sm-6 col-md-4">
											<label>Dirección:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
											<input type="text" id="e_direccion" placeholder="Dirección" class="form-control input-sm des" disabled="disabled">
											<label id="e_error_direccion"></label>
										</div>
										<div class="col-xs-12 col-sm-4 col-md-3">
											<label>Dígito de verificación:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
											<input type="number" id="e_digito_verificacion" disabled placeholder="Digito de verificación" class="form-control input-sm des" disabled="disabled">
											<label id="e_error_digito_verificacion"></label>
										</div>
									</div>
								</div>
							</div>
							<div class="panel panel-default" id="driver">
								<div class="panel-heading">
									<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#collapseTwo" class="collapsed"><i class="icon mdi mdi-chevron-down"></i>Datos del conductor</a></h4>
								</div>
								<div id="collapseTwo" class="panel-collapse collapse">
									<div class="panel-body">

										<div class="row">
											<div class="col-xs-12 col-sm-3 col-md-3">
												<label>Categoría Licencia&nbsp;<span style="color:red;"><i>(*)</i></label>
												<select id="categoria_licencia" class="form-control input-sm">
													<option value="" disabled selected>Seleccione</option>
													<option value="4">4</option>
													<option value="5">5</option>
													<option value="6">6</option>
													<option value="C1">C1</option>
													<option value="C2">C2</option>
													<option value="C3">C3</option>
												</select>
											</div>
											<div class="col-xs-12 col-md-6 col-sm-6">
												<label>Número Licencia&nbsp;<span style="color:red;"><i>(*)</i></label>
												<input type="text" id="e_num_licencia" class="form-control input-sm des">
											</div>
											<div class="col-xs-12 col-md-3 col-md-3">
												<label>Vencimiento Licencia&nbsp;<span style="color:red;"><i>(*)</i></label>
												<input type="date" id="e_vence_licencia" class="form-control input-sm">
											</div>
										</div>
										<div class="row">
											<div>
												<h4 class="text-primary text-center">Referencias Laborales</h4>
											</div>
											<div class="col-xs-12 col-sm-8 col-md-8 REmpresarial1">
												<label>Empresa 1:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
												<input class="form-control input-sm des" id="e_referencias_empresariales1" onblur="mayuscula(this);">
												<label id="error_referencias_empresariales"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-4 col-md-4">
												<label>Fecha Ingreso 1:</label>

												<input type="date" id="e_fecha_referencia1" class="form-control input-sm">
												<label id="error_fecha_empresarial1"></label>
											</div>

											<div class="form-group col-xs-12 col-sm-4 col-md-4">
												<label>Fecha Retiro 1:</label>
												<input type="date" id="e_fecha_retiro1" class="form-control input-sm">
												<label id="error_fecha_empresarial1"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-4 col-md-4">
												<label>Persona Contacto :</label>
												<input type="text" id="e_contacto_ref1" placeholder="Nombre Contacto" class="form-control input-sm des" onblur="mayuscula(this);">
												<label id="error_contacto"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-4 col-md-4">
												<label>Celular Empresa:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
												<input type="int" id="e_celular_ref1" placeholder="Celular Empresa" maxlength="10" class="form-control input-sm des">
												<label id="error_celularref1"></label>
											</div>
											<!-- row-->
										</div>
										<div class="row">
											<div class="form-group col-xs-12 col-sm-6 col-md-6">
												<label>Cargo :</label>
												<input type="text" id="e_cargo_ref1" placeholder="Cargo" class="form-control input-sm des" onblur="mayuscula(this);">
												<label id="error_cargo"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-6 col-md-6">
												<label>Antiguedad:</label>
												<input type="number" id="e_anti_ref1" min="0" placeholder="Antiguedad" class="form-control input-sm des">
												<label id="error_antig"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-3 col-md-3">
												<input type="hidden" id="e_idrefe1" class="form-control input-sm">
											</div>
										</div>
										<div class="row">
											<div class="col-xs-12 col-sm-8 col-md-8 REmpresarial2">
												<label>Empresa 2:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
												<input type="text" class="form-control input-sm des" id="e_referencias_empresariales2" onblur="mayuscula(this);">
												<label id="error_referencia_empresarial2"></label>
											</div>
											<div class="col-xs-12 col-sm-4 col-md-4 REmpresarial1">
												<label>Fecha Ingreso 2:</label>
												<input type="date" id="e_fecha_referencia2" class="form-control input-sm">
												<label id="error_fecha_empresarial2"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-4 col-md-4">
												<label>Fecha Retiro 2:</label>
												<input type="date" id="e_fecha_retiro2" class="form-control input-sm">
												<label id="error_fecha_empresarial1"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-4 col-md-4">
												<label>Persona Contacto :</label>
												<input type="text" id="e_contacto_ref2" placeholder="Nombre Contacto" class="form-control input-sm des">
												<label id="error_contacto"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-4 col-md-4">
												<label>Celular Empresa:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
												<input type="int" id="e_celular_ref2" placeholder="Celular Empresa" maxlength="10" class="form-control input-sm des">
												<label id="error_celularref1"></label>
											</div>
										</div>

										<div class="row">
											<div class="form-group col-xs-12 col-sm-6 col-md-6">
												<label>Cargo:</label>
												<input type="text" id="e_cargo_ref2" placeholder="Cargo" class="form-control input-sm des" onblur="mayuscula(this);">
												<label id="error_cargo"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-6 col-md-6">
												<label>Antiguedad:</span></label>
												<input type="number" id="e_anti_ref2" min="0" placeholder="Antiguedad" class="form-control input-sm des">
												<label id="error_antig"></label>
											</div>

											<div class="form-group col-xs-12 col-sm-3 col-md-3">
												<input type="hidden" id="e_idrefe2" class="form-control input-sm">
											</div>
										</div>
										<div class="row">
											<div class="col-xs-12 col-sm-8 col-md-8 REmpresarial2">
												<label>Empresa 3:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
												<input type="text" class="form-control input-sm des" id="e_referencias_empresariales3" onblur="mayuscula(this);">
												<label id="error_referencia_empresarial2"></label>
											</div>
											<div class="col-xs-12 col-sm-4 col-md-4 REmpresarial1">
												<label>Fecha Ingreso 3:</label>
												<input type="date" id="e_fecha_referencia3" class="form-control input-sm">
												<label id="error_fecha_empresarial2"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-4 col-md-4">
												<label>Fecha Retiro 3:</label>
												<input type="date" id="e_fecha_retiro3" class="form-control input-sm">
												<label id="error_fecha_empresarial1"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-4 col-md-4">
												<label>Persona Contacto :</label>
												<input type="text" id="e_contacto_ref3" placeholder="Nombre Contacto" class="form-control input-sm des">
												<label id="error_contacto"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-4 col-md-4">
												<label>Celular Empresa:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
												<input type="int" id="e_celular_ref3" placeholder="Celular Empresa" maxlength="10" class="form-control input-sm des">
												<label id="error_celularref1"></label>
											</div>
										</div>

										<div class="row">
											<div class="form-group col-xs-12 col-sm-6 col-md-6">
												<label>Cargo:</label>
												<input type="text" id="e_cargo_ref3" placeholder="Cargo" class="form-control input-sm des" onblur="mayuscula(this);">
												<label id="error_cargo"></label>
											</div>
											<div class="form-group col-xs-12 col-sm-6 col-md-6">
												<label>Antiguedad:</label>
												<input type="number" id="e_anti_ref3" min="0" placeholder="Antiguedad" class="form-control input-sm des">
												<label id="error_antig"></label>
											</div>

											<div class="form-group col-xs-12 col-sm-3 col-md-3">
												<input type="hidden" id="e_idrefe3" class="form-control input-sm">
											</div>
										</div>
										<div class="row">
											<div class="col-xs-12 col-sm-8 col-md-8 REmpresarial2">
												<label>Nombre persona 1:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
												<input class="form-control input-sm des" id="e_referencias_personales1" onblur="mayuscula(this);">
												<label id="error_referencias_personales"></label>
											</div>
											<div class="col-xs-12 col-sm-4 col-md-4 FPersonal1">
												<label>Fecha 1:</label>
												<input type="date" id="e_fecha_personal1" class="form-control input-sm">
												<label id="error_referencias_personales1"></label>
											</div>
											<div class="col-xs-12 col-sm-6 col-md-3 REmpresarial2">
												<label>Parentezco:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
												<select class="form-control input-sm" id="parenp1">
													<option value="" readonly="readonly">Seleccione una opción</option>
													<option value="1">Amigo/a</option>
													<option value="2">Hermano/a</option>
													<option value="3">Padre</option>
													<option value="4">Madre</option>
													<option value="5">Tio/a</option>
													<option value="6">Sobrino/a</option>
													<option value="7">Hijo/a</option>
													<option value="8">Espaso/a</option>
												</select>
												<label id="error_referencias_personales"></label>
											</div>
											<div class="col-xs-12 col-sm-6 col-md-6 REmpresarial2">
												<label>Teléfono:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
												<input type="number" id="e_telefonop1" min="0" maxlength="10" class="form-control input-sm des">
												<label id="error_referencias_personales"></label>
											</div>
											<div class="col-xs-12 col-sm-3 col-md-3 REmpresarial2">
												<input type="hidden" id="e_idp1" class="form-control">
											</div>
										</div>
										<div class="row">
											<div class="col-xs-12 col-sm-8 col-md-8 RPersonal2">
												<label>Nombre Personal 2:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
												<input type="text" class="form-control input-sm des" id="e_referencias_personales2" onblur="mayuscula(this);">
												<label id="error_referencias_personales"></label>
											</div>
											<div class="col-xs-12 col-sm-4 col-md-4 FRpersonal2">
												<label>Fecha 2:</label>
												<input type="date" id="e_fecha_personal2" class="form-control input-sm">
												<label id="error_referencias_personales"></label>
											</div>
											<div class="col-xs-12 col-sm-6 col-md-3 REmpresarial2">
												<label>Parentezco:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
												<select class="form-control input-sm" id="parenp2">
													<option value="" readonly="readonly">Seleccione una opción</option>
													<option value="1">Amigo/a</option>
													<option value="2">Hermano/a</option>
													<option value="3">Padre</option>
													<option value="4">Madre</option>
													<option value="5">Tio/a</option>
													<option value="6">Sobrino/a</option>
													<option value="7">Hijo/a</option>
													<option value="8">Espaso/a</option>
												</select>
												<label id="error_referencias_personales"></label>
											</div>
											<div class="col-xs-12 col-sm-6 col-md-6 REmpresarial2">
												<label>Teléfono:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
												<input type="number" id="e_telefonop2" min="0" maxlength="10" class="form-control input-sm des">
												<label id="error_referencias_personales"></label>
											</div>
											<div class="col-xs-12 col-sm-3 col-md-3 REmpresarial2">
												<input type="hidden" id="e_idp2" class="form-control">
											</div>
										</div>
										<div class="row">
											<div class="col-xs-12 col-sm-8 col-md-8 NombreEps">
												<label>Planilla de seguridad social:</label>
												<input type="text" id="e_name_eps" placeholder="Planilla seguridad" class="form-control input-sm des" onblur="mayuscula(this);">
												<label id="error_eps"></label>
											</div>
											<div class="col-xs-12 col-sm-4 col-md-4 FVenceEps">
												<label>Fecha vencimiento plan. seguridad social:</label>
												<input type="date" id="e_vence_eps" class="form-control input-sm">
												<label id="error_feps"></label>
											</div>
										</div>
										<div class="row">
											<div class="col-xs-12 col-sm-8 col-md-8 NombreEntidad">
												<label>Entidad curso peligroso:</label>
												<input type="text" id="e_nom_enti" class="form-control input-sm des" onblur="mayuscula(this);">
												<label id="error_nom_enti"></label>
											</div>
											<div class="col-xs-12 col-sm-4 col-md-4 FVCurso">
												<label>Fecha Vencimiento del Curso:</label>
												<input type="date" id="e_vence_curso" class="form-control input-sm">
												<label id="error_nom_enti"></label>
											</div>
										</div>
										<div class="row">
											<div class="form-group col-xs-4">
												<label>Sexo:</label>
												<select class="form-control input-sm" id="sexo">
													<option value="">Seleccione</option>
													<option value="Femenino">Femenino</option>
													<option value="Masculino">Masculino</option>
													<option value="Otro">Otro</option>
												</select>
												<label id="e_error_sexo"></label>
											</div>
											<div class="form-group col-xs-4">
												<label>Fecha Nacimiento:</label>
												<input type="date" id="e_fecha_nacimiento" class="form-control input-sm">
												<label id="v_error_nacimiento"></label>
											</div>
											<div class="form-group col-xs-4">
												<label>RH:</label>
												<select class="form-control input-sm text-center" id="sangre">
													<option value="">Seleccione</option>
													<option value="O+">O+</option>
													<option value="O-">O-</option>
													<option value="A+">A+</option>
													<option value="A-">A-</option>
													<option value="B+">B+</option>
													<option value="B-">B-</option>
													<option value="AB+">AB+</option>
													<option value="AB-">AB-</option>
												</select>
												<label id="v_error_rh"></label>
											</div>
											<div class="form-group col-xs-6">
												<label>Fecha Ingreso:</label>
												<input type="date" id="e_ingreso" class="form-control input-sm">
												<label id="v_error_ingreso"></label>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="panel panel-default" id="prove">
								<div class="panel-heading">
									<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#collapseThree" class="collapsed"><i class="icon mdi mdi-chevron-down"></i>Datos de proveedor</a></h4>
								</div>
								<div id="collapseThree" class="panel-collapse collapse">
									<div class="panel-body">

										<div class="panel panel-border-color panel-border-color-primary">
											<div class="panel-heading">Detalle Proveedor</div>
											<div class="panel-body">
												<!-- -->
												<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
													<label>Tipo de proveedor</label><br>
													<input class="tipo_proveedor" id="nacional" type="radio" name="tipo_proveedor" value="1">
													<label for="nacional">Nacional</label>
													<input class="tipo_proveedor" id="internacional" type="radio" name="tipo_proveedor" value="2">
													<label for="internacional">Internacional</label>
												</div>
												<div class="form-group col-xs-12 col-sm-12 col-md-12">
													<label>Localización operacional</label>
													<select id="pv_localizacion" class="form-control input-sm text-center" style="text-align:center;">
													</select>
												</div>
												<div class="form-group col-xs-12 col-sm-12 col-md-12 zona">
													<label>Zona</label>
													<input type="text" id="pv_zona" class="form-control input-sm">
												</div>
												<div class="form-group col-xs-12 col-sm-12 col-md-12">
													<label>Tipo de servicio</label>
													<select id="pv_tiposervice" class="form-control input-sm">
														<option value="">Seleccione</option>
														<option value="Transporte">Transporte</option>
														<option value="Porteadores">Porteadores</option>
														<option value="Adecuaciones">Adecuaciones</option>
														<option value="Aduana">Aduana</option>
														<option value="Impuestos">Impuestos</option>
														<option value="Agenciamiento de carga">Agenciamiento de carga</option>
														<option value="Tramites operativos">Trámites operativos</option>
														<option value="Tramites administrativos">Trámites administrativos</option>
													</select>
												</div>

												<div class="form-group col-xs-12 col-sm-12 col-md-12" id="tipos_servicios">
													<div class="col-xs-12 col-sm-12 col-md-12 text-center"><strong><label id="titulo_tservice"></label></strong></div>

													<div class="row" id="Transporte">
														<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
															<label>Vía</label>
															<select id="pv_via" class="form-control input-sm">
																<option value="">Seleccione</option>
																<option value="Aerea">Aerea</option>
																<option value="Maritima">Maritima</option>
																<option value="Terrestre">Terrestre</option>
															</select>
														</div>
														<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
															<label>Tipificación</label>
															<select id="pv_select" class="form-control input-sm">
															</select>
														</div>
													</div>

													<div class="row" id="porteadores">
														<div class="col-xs-12 col-sm-12 col-md-12 text-center">
															<label>Detalle</label>
															<select id="detalle_porteador" class="form-control input-sm">
																<option value="">Seleccione</option>
																<option value="Puertos">Puertos</option>
																<option value="Aeropuertos">Aeropuertos</option>
																<option value="Entes regulatorios">Entes regulatorios</option>
																<option value="Trámites en frontera">Trámites en frontera</option>
															</select>
														</div>
													</div>

													<div class="row" id="agencia_carga">
														<div class="col-xs-12 col-sm-12 col-md-12 text-center">
															<label>Detalle</label>
															<select id="detalle_acarga" class="form-control input-sm">
																<option value="">Seleccione</option>
																<option value="Agente de carga">Agente de carga</option>
																<option value="Consolidador neutral">Consolidador neutral</option>
															</select>
														</div>
													</div>

													<div class="row" id="tramite_admin">
														<div class="col-xs-12 col-sm-12 col-md-12">
															<label>Trámites Administrativos</label>
															<select id="tramite_ad" class="form-control input-sm">
																<option value="">Seleccione</option>
																<option value="Navidad">Navidad</option>
																<option value="Calendarios">Calendarios</option>
																<option value="Dotaciones">Dotaciones</option>
																<option value="Servicios públicos">Servicios públicos</option>
															</select>
														</div>
													</div>
												</div>
												<!-- -->
											</div>
										</div>

										<div class="panel panel-border-color panel-border-color-primary">
											<div class="panel-heading">Contactos</div>
											<div class="panel-body">
												<div class="form-group col-xs-12 col-sm-12 col-md-12">
													<label>Agregar contacto</label>
													<button class="form-control btn btn-info mdi mdi-plus input-xs text-center" id="agregar_fila"></button>
												</div>
												<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
													<table class="table table-bordered">
														<thead style="border-color:blue;">
														</thead>
														<tbody id="tabla_contacte">
														</tbody>
													</table>
												</div>
												<input type="hidden" id="cont_contactos">
											</div>
										</div>

										<!--cierre del proveedor -->
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row"></div><!-- separar contenido entre el body y el footer-->
			</div>
			<div class="modal-footer">
				<button id="btnactualizar" type="button" class="btn btn-success md-close">Actualizar</button>
				<button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
			</div>
		</div>
	</div>
</div>

<?php
$vista .= '
		<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
		<script src="%root_file%js/main.js" type="text/javascript"></script>
		<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
		<link  rel="stylesheet" type="text/css" href="assets/lib/select2/css/select2.min.css"/>

		<link rel="stylesheet" type="text/css" src="%root_file%lib/assets/lib/select2/css/select2.min.css"/>


		<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
		<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
		<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

		<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
		<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
		<script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.wizard();
			});
		</script>
	';
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%content%", $table_content, $vista); //variable $table_content sirve para crear adentro de esta todo lo que se va a mostrar en el cuerpo del conetenedor 
echo $vista;
?>

<script type="text/javascript">
	paisesinternacional();

	function mayuscula(elemento) {
		let texto = elemento.value;
		elemento.value = texto.toUpperCase();
	}

	$(".fnum").hide();
	$(".fnom").hide();
	$("#civil").hide();
	$(".zona").hide();
	$("#tipos_servicios").hide();
	$("#Transporte").hide();
	$("#agencia_carga").hide();


	$("#tipotb").change(function() {
		var t = $("#tipotb").val();
		if (t == '') {
			$(".fnum").hide();
			$(".fnom").hide();
		}
		if (t == 2) {
			$(".fnum").show();
			$(".fnom").hide();
		}
		if (t == 1) {
			$(".fnum").hide();
			$(".fnom").show();
		}
	});
	$("#buscar_coti").click(function() {
		var a = $("#tipotb").val();
		if (a == '') {
			a == '';
			c = '';
			b = '';
			var url = $("#id_url_ajax").val() + 'operaciones/tipo_proveedor/?idmenu=3&i=1&a=' + a + '&b=' + b + '&c=' + c + '';
			window.location = (url);
		}

		if (a == 1) {
			b = $("#nameprove").val();
			c = '';
			var url = $("#id_url_ajax").val() + 'operaciones/tipo_proveedor/?idmenu=3&i=1&a=' + a + '&b=' + b + '&c=' + c + '';
			window.location = (url);
		}
		if (a == 2) {
			b = '';
			c = $("#docuprove").val();
			var url = $("#id_url_ajax").val() + 'operaciones/tipo_proveedor/?idmenu=3&i=1&a=' + a + '&b=' + b + '&c=' + c + '';
			window.location = (url);
		}
	});
	$("#driver").hide();
	$("#prove").hide();
	//traer datos básicos y algunas validaciones
	$("#id_proveedor").val('');

	function edita_t_proveedor(element) {
		var elemento = $(element);
		var id_proveedor = elemento.data("id");
		$("#id_proveedor").val(id_proveedor);
		// VALIDAR SI TIENE VEHÍCULO ASOCIADO(conductor)
		var asocicar = {
			id_proveedor: id_proveedor,
			action: 'validar_conductor'
		};

		$("#msg_informativo").html('');
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/lista_tipoproveedor.php",
			type: 'POST',
			data: asocicar,
			dataType: 'json',
			success: function(data) {
				if (data.result != null) {
					var vdriver = data.result[0].vdriver;
					if (vdriver > 0) {
						//si tiene asoaciado un vehículo
						$("#v_Conductor").prop('disabled', true);
						$("#msg_informativo").html('<div role="alert" class="alert alert-contrast alert-primary alert-dismissible  mensajito">' +
							'<div class="icon"><span class="mdi mdi-check"></span></div>' +
							'<div class="message">' +
							'<p class="text-center">' +
							'<strong>' +
							'Este conductor tiene un vehículo asociado actualmente, por lo tanto no puede eliminar este tipo de actividad ni sus datos' +
							'</strong></p></div></div>');
						$("#condu_ligado").val(1);
					} else {
						$("#condu_ligado").val(0);
						$("#v_Conductor").prop('disabled', false);
					}
				}
			},
			error: function(jqXHR, textStatus, errorThrown) {
				alert('error');
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			}
		});

		//VALIDAR SI TIENE DATOS EN TABLAS
		$("#driver_data").val('');
		$("#supplier_data").val('');
		$("#dueno_data").val('');
		$("#holder_data").val('');
		var tbcondu = {
			id_proveedor: id_proveedor,
			action: 'datos_enconductor'
		};
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/lista_tipoproveedor.php",
			type: 'POST',
			data: tbcondu,
			dataType: 'json',
			success: function(data) {
				if (data.result != null) {
					var tb_condu = data.result[0].tb_condu;
					if (tb_condu > 0) { //tiene datos en detalle conductor
						$("#driver_data").val('si');
					} else { //no existen esos datos
						$("#driver_data").val('no');
					}
				}

				if (data.result2 != null) {
					var tba_prove = data.result2[0].tb_provee;
					if (tba_prove > 0) { //tiene datos en proveedor_detalle
						$("#supplier_data").val('si');
					} else { //no existen datos en proveedor detalle
						$("#supplier_data").val('no');
					}
				}


				if (data.result3 != null) {
					var tba_propi = data.result3[0].tb_dueno;
					if (tba_propi > 0) {
						$("#dueno_data").val('si');
					} else {
						$("#dueno_data").val('no');
					}
				}

				if (data.result4 != null) {
					var tbtene = data.result4[0].tb_tene;
					if (tbtene > 0) {
						$("#holder_data").val('si');
					} else {
						$("#holder_data").val('no');
					}
				}
			},
			error: function(jqXHR, textStatus, errorThrown) {
				alert('error');
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			}
		});


		//TIPO ACTIVIDAD + DATOS BÁSICOS
		var dato = {
			id_proveedor: id_proveedor,
			action: 'cargar_actividades'
		};

		$("#v_Conductor").prop("checked", false);
		$("#v_poseedor_vehiculo").prop("checked", false);
		$("#v_propietario_vehiculo").prop("checked", false);
		$("#v_Proveedor").prop("checked", false);
		$.ajax({
			url: $("#id_url_ajax").val() + "libs/lista_tipoproveedor.php",
			type: 'POST',
			data: dato,
			dataType: 'json',
			success: function(data) {
				if (data.result != null) {
					data.result.forEach(function(element, index) {
						actividad = element.actividad;
						if (actividad == 'Conductor') {
							$("#v_Conductor").prop("checked", true);
						}
						if (actividad == 'Poseedor Vehiculo') {
							$("#v_poseedor_vehiculo").prop("checked", true);
							/*$("#agrega_tene").prop('disabled', true);
							$("#eli_tene").prop('disabled', false);*/
						}
						if (actividad == 'Propietario Vehiculo') {
							$("#v_propietario_vehiculo").prop("checked", true);
							/*$("#agrega_propi").prop('disabled', true);
							$("#eli_propi").prop('disabled', false);*/
						}
						if (actividad == 'Proveedor') {
							$("#v_Proveedor").prop("checked", true);
						}
					});
				}

				if (data.result2 != null) {
					$("#e_rndc_nombre").val(data.result2[0].nombre);
					$("#e_rndc_apellido1").val(data.result2[0].apellido1);
					$("#e_rndc_apellido2").val(data.result2[0].apellido2);
					$("#e_abreviatura").val(data.result2[0].abreviatura);
					$("#e_tipo_documento").val(data.result2[0].tipo_documento);
					$("#e_numero_documento").val(data.result2[0].numero_documento);
					$("#e_tipo_identificacion").val(data.result2[0].tipo_identificacion);
					$("#e_contacto").val(data.result2[0].contacto);
					$("#e_celular").val(data.result2[0].celular);
					$("#e_email").val(data.result2[0].email);
					$("#e_direccion").val(data.result2[0].direccion);
					$("#e_digito_verificacion").val(data.result2[0].digito_verificacion);
					$("#e_municipio").val(data.result2[0].municipio);
					$("#e_celular2").val(data.result2[0].celular2);
					$("#e_email").val(data.result2[0].email);
				}
			},
			error: function(jqXHR, textStatus, errorThrown) {
				alert('error');
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			}
		});

	}
	//validar cambio de checkbox
	$("#v_Conductor").change(function() {
		if ($(this).is(":checked")) {
			var a = $("#driver_data").val();
			if (a == 'si') {
				$("#driver").hide();
			}
			if (a == 'no') {
				$("#driver").show();
			}
		}
		if (!$(this).is(":checked")) {
			$("#driver").hide();
		}
	});

	$("#v_Proveedor").change(function() {
		if ($(this).is(":checked")) {
			var b = $("#supplier_data").val();
			if (b == 'si') {
				$("#prove").hide();
			}
			if (b == 'no') {
				$("#prove").show();
			}
		}
		if (!$(this).is(":checked")) {
			$("#prove").hide();
		}
	});


	//PROVEEDORES INTERNACIONAL
	$("#agregar_fila").click(function() {
		agregar_contacto();
	});

	var a = 0;
	var b = 0;

	function agregar_contacto() {
		a++;
		b = b + 1;
		var ch = '<input type="button" id="p' + a + '" class="btn-primary borrar2" value="Eliminar">';
		var contace = '<tr>' +
			//'<th>#</th><th>Nombres</th><th>Cargo</th><th>Teléfono</th></tr><tr>'+
			'<td colspan="2" class="info"><label>N°</label><p class="text-center text-primary"><strong>' + a + '</strong></p><input type="hidden" id="sk' + a + '" value="1" class="form-control input-sm">  </td>' +
			'</tr><tr>' +
			'<td colspan="2"><label>Nombres</label> <input type="text" id="nombres' + a + '" class="form-control input-sm"></td>' +
			'</tr><tr>' +
			'<td><label>Cargo</label> <input type="text" id="cargo' + a + '" class="form-control input-xs"></td>' +
			'<td><label>Teléfono</label> <input type="number" id="fijo' + a + '" class="form-control input-xs"></td>' +
			'<tr>' +
			'<td><label>Celular</label> <input type="number" id="celular' + a + '" class="form-control input-xs">  </td>' +
			'<td><label>Correo</label>   <input type="email" id="correo' + a + '" class="form-control input-xs" > </td>' +
			'</tr>' +
			'<tr>' +
			'<td><label>Info. crítica</label> <textarea id="critica' + a + '" class="form-control input-xs"></textarea>   </td>' +
			'<td><label>Referencia</label> <textarea id="refe' + a + '" class="form-control input-xs"></textarea>  </td>' +
			'</tr>' +
			'</tr>';

		$("#tabla_contacte").append(contace);
		$("#cont_contactos").val(b);
	}
	$("#pv_localizacion").change(function() {
		var local = $("#pv_localizacion").val();
		if (local == '') {
			$("#pv_zona").val('');
			$(".zona").hide();
		} else {
			$(".zona").show();
		}
	});
	$("#pv_tiposervice").change(function() {
		//limpiar los campos de cada tipo de servicio

		var tipo_service = $("#pv_tiposervice").val();
		if (tipo_service == '') {
			$("#pv_via").val('');
			$("#pv_select").val('');
			$("#detalle_porteador").val('');
			$("#detalle_acarga").val('');
			$("#tramite_ad").val('');
			$("#titulo_tservice").val('');
			$("#Transporte").hide();
			$("#porteadores").hide();
			$("#agencia_carga").hide();
			$("#tramite_admin").hide();
		} else {
			$("#tipos_servicios").show();
			if (tipo_service == 'Transporte') {
				//limpiar campos que no pertenecen a este tipo
				$("#detalle_porteador").val('');
				$("#detalle_acarga").val('');
				$("#tramite_ad").val('');
				//segun
				$("#titulo_tservice").html('TIPO SERVICIO: Transporte');
				$("#Transporte").show();
				$("#porteadores").hide();
				$("#agencia_carga").hide();
				$("#tramite_admin").hide();
			}

			if (tipo_service == 'Porteadores') {
				//limpiar campos
				$("#pv_via").val('');
				$("#pv_select").html('');
				$("#detalle_acarga").val('');
				$("#tramite_ad").val('');
				//
				$("#titulo_tservice").html('TIPO SERVICIO: Porteadores');
				$("#Transporte").hide();
				$("#porteadores").show();
				$("#agencia_carga").hide();
				$("#tramite_admin").hide();
			}

			if (tipo_service == 'Agenciamiento de carga') {
				//limpiar campos
				$("#pv_via").val('');
				$("#pv_select").html('');
				$("#detalle_porteador").val('');
				$("#tramite_ad").val('');
				//
				$("#titulo_tservice").html('TIPO SERVICIO: Agenciamiento de carga');
				$("#Transporte").hide();
				$("#porteadores").hide();
				$("#tramite_admin").hide();
				$("#agencia_carga").show();
			}

			if (tipo_service == 'Tramites administrativos') {
				//limpiar campos
				$("#pv_via").val('');
				$("#pv_select").html('');
				$("#detalle_porteador").val('');
				$("#detalle_acarga").val('');
				//
				$("#titulo_tservice").html('TIPO SERVICIO: Trámites Administrativos');
				$("#tramite_admin").show();
				$("#Transporte").hide();
				$("#porteadores").hide();
				$("#agencia_carga").hide();
			}

			if (tipo_service == 'Adecuaciones' || tipo_service == 'Aduana' || tipo_service == 'Impuestos' ||
				tipo_service == 'Tramites operativos') {
				//limpiar campos
				$("#pv_via").val('');
				$("#pv_select").html('');
				$("#detalle_porteador").val('');
				$("#detalle_acarga").val('');
				$("#tramite_ad").val('');
				//
				$("#titulo_tservice").html('');
				$("#tramite_admin").hide();
				$("#Transporte").hide();
				$("#porteadores").hide();
				$("#agencia_carga").hide();
			}

		}
	});
	$("#pv_via").change(function() {
		$("#pv_select").html('');
		var via = $("#pv_via").val();
		if (via == '') {
			$("#pv_select").html('');
		}

		if (via == 'Aerea') {
			$("#pv_select").html('<option value="Aerolinea de carga/pasajeros">Aerolinea de carga/pasajeros</option>' +
				'<option value="Courier Internacional">Courier Internacional</option>' +
				'<option value="Agentes aereos">Agentes aereos</option>' +
				'<option value="Aereos nacional">Aereos nacional</option>');
		}

		if (via == 'Maritima') {
			$("#pv_select").html('<option value="Navieras">Navieras</option>' +
				'<option value="Agentes maritimos">Agentes maritimos</option>');
		}

		if (via == 'Terrestre') {
			$("#pv_select").html('<option value="Transportadores terrestres">Transportadores terrestres</option>' +
				'<option value="Nacionales">Nacionales</option>' +
				'<option value="Transportadores urbanos">Transportadores urbanos</option>');
		}

	});

	function paisesinternacional() {
		var paises = {
			action: 'localizacion_operacional'
		};
		$("#pv_localizacion").html('<option value="">Seleccione(Municipio-Depto-País)</option>');
		$.ajax({
			//url:$("#id_url_ajax").val() +"libs/hojas_de_vida_ajax.php",
			url: $("#id_url_ajax").val() + 'libs/hojas_de_vida_ajax.php',
			type: 'POST',
			data: paises,
			dataType: 'json',
			success: function(data) {
				data.result.forEach(function(element, index) {
					$("#pv_localizacion").append('<option value="' + element.id + '">' + element.municipio + '  -  ' + element.depto + '  -  ' + element.pais + '</option>');
				});
			},
			error: function(jqXHR, textStatus, errorThrown) {
				console.log('no trajo paises localizacion operacional');
				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			}
		});
	}

	//validar boton editar
	$("#btnactualizar").click(function() {
		var msg_error = "";
		var datoconductor = $("#driver_data").val();
		var datoproveedor = $("#supplier_data").val();
		var datopropietario = $("#dueno_data").val();
		var datotenedor = $("#holder_data").val();

		if (!$("#v_Conductor").is(':checked') &&
			!$("#v_poseedor_vehiculo").is(':checked') &&
			!$("#v_propietario_vehiculo").is(':checked') &&
			!$("#v_Proveedor").is(':checked')) {
			msg_error += "<p>Debe seleccionar un <strong> tipo de actividad </strong> para poder actualizar el tipo de proveedor.</p>";
		}

		if ($("#v_Conductor").is(':checked') && datoconductor == 'no') {
			if (!$("#categoria_licencia").val()) {
				msg_error += "<p>Debe seleccionar el campo <strong> Categoría</strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#e_num_licencia").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Número Licencia</strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#e_vence_licencia").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Vencimiento Licencia</strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#e_referencias_empresariales1").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Empresa 1: </strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#e_celular_ref1").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Celular Empresa </strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#e_referencias_empresariales2").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Empresa 2 </strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#e_celular_ref2").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Celular Empresa:  </strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#e_referencias_empresariales3").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Empresa 3</strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#e_celular_ref3").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Celular Empresa</strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#e_referencias_personales1").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Nombre persona 1</strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#parenp1").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Parentezco</strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#e_telefonop1").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Teléfono</strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#e_referencias_personales2").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Nombre Personal 2</strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#parenp2").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Parentezco 2</strong> para poder actualizar el tipo de proveedor.</p>";
			}
			if (!$("#e_telefonop2").val()) {
				msg_error += "<p>Debe ingresar el campo <strong> Teléfono 2</strong> para poder actualizar el tipo de proveedor.</p>";
			}
		}

		if ($("#v_Proveedor").is(':checked') && datoproveedor == 'no') {
			if (!$("#nacional").is(':checked') && !$("#internacional").is(':checked')) {
				msg_error += "<p>Debe seleccionar el campo  <strong> Localización operacional</strong> para poder actualizar el tipo de proveedor.</p>";

			}
			if (!$("#pv_localizacion").val()) {
				msg_error += "<p>Debe seleccionar el campo  <strong> Localización operacional</strong> para poder actualizar el tipo de proveedor.</p>";
			}
		}


		if (!msg_error) {
			Actualizar();
		} else {
			$("#msg_editar").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
			$("#tipo_proveedor").animate({
				scrollTop: 0
			}, 600);
		}

	});

	var url = $("#id_url_ajax").val() + "libs/proveedores_ajax.php";

	function Actualizar() {
		var data = null;
		data = new FormData();
		var datoconductor = $("#driver_data").val();
		var datoproveedor = $("#supplier_data").val();
		var datopropietario = $("#dueno_data").val();
		var datotenedor = $("#holder_data").val();

		var driver = '';
		var proveinte = '';
		var tene = '';
		var propieta = '';
		data.append("v_Conductor", driver);
		data.append("v_Proveedor", proveinte);
		data.append("v_poseedor_vehiculo", tene);
		data.append("v_propietario_vehiculo", propieta);
		data.append("accion", 'CrearTipoProveedor');
		data.append("id_proveedor", $("#id_proveedor").val());
		//INSERTAR
		if ($("#v_Conductor").is(':checked') && datoconductor == 'no') {
			data.append("categoria_licencia", $("#categoria_licencia").val());
			data.append("e_num_licencia", $("#e_num_licencia").val());
			data.append("e_vence_licencia", $("#e_vence_licencia").val());
			data.append("e_referencias_empresariales1", $("#e_referencias_empresariales1").val());
			data.append("e_fecha_referencia1", $("#e_fecha_referencia1").val());
			data.append("e_fecha_retiro1", $("#e_fecha_retiro1").val());
			data.append("e_contacto_ref1", $("#e_contacto_ref1").val());
			data.append("e_celular_ref1", $("#e_celular_ref1").val());
			data.append("e_cargo_ref1", $("#e_cargo_ref1").val());
			data.append("e_anti_ref1", $("#e_anti_ref1").val());
			data.append("e_referencias_empresariales2", $("#e_referencias_empresariales2").val());
			data.append("e_fecha_referencia2", $("#e_fecha_referencia2").val());
			data.append("e_fecha_retiro2", $("#e_fecha_retiro2").val());
			data.append("e_contacto_ref2", $("#e_contacto_ref2").val());
			data.append("e_celular_ref2", $("#e_celular_ref2").val());
			data.append("e_cargo_ref2", $("#e_cargo_ref2").val());
			data.append("e_anti_ref2", $("#e_anti_ref2").val());
			data.append("e_referencias_empresariales3", $("#e_referencias_empresariales3").val());
			data.append("e_fecha_referencia3", $("#e_fecha_referencia3").val());
			data.append("e_fecha_retiro3", $("#e_fecha_retiro3").val());
			data.append("e_contacto_ref3", $("#e_contacto_ref3").val());
			data.append("e_celular_ref3", $("#e_celular_ref3").val());
			data.append("e_cargo_ref3", $("#e_cargo_ref3").val());
			data.append("e_anti_ref3", $("#e_anti_ref3").val());
			data.append("e_referencias_personales1", $("#e_referencias_personales1").val());
			data.append("e_fecha_personal1", $("#e_fecha_personal1").val());
			data.append("parenp1", $("#parenp1").val());
			data.append("e_telefonop1", $("#e_telefonop1").val());
			data.append("e_referencias_personales2", $("#e_referencias_personales2").val());
			data.append("e_fecha_personal2", $("#e_fecha_personal2").val());
			data.append("parenp2", $("#parenp2").val());
			data.append("e_telefonop2", $("#e_telefonop2").val());
			data.append("e_name_eps", $("#e_name_eps").val());
			data.append("e_vence_eps", $("#e_vence_eps").val());
			data.append("e_nom_enti", $("#e_nom_enti").val());
			data.append("e_vence_curso", $("#e_vence_curso").val());
			data.append("sexo", $("#sexo").val());
			data.append("e_fecha_nacimiento", $("#e_fecha_nacimiento").val());
			data.append("sangre", $("#sangre").val());
			data.append("e_ingreso", $("#e_ingreso").val());
			driver = $("#v_Conductor").is(':checked');
			data.append("v_Conductor", driver);
		}
		if ($("#v_Proveedor").is(':checked') && datoproveedor == 'no') {
			data.append("tipo_proveedor", $(".tipo_proveedor").val());
			data.append("nacional", $("#nacional").is(':checked'));
			data.append("internacional", $("#internacional").is(':checked'));
			data.append("pv_localizacion", $("#pv_localizacion").val());
			data.append("pv_zona", $("#pv_zona").val());
			data.append("pv_tiposervice", $("#pv_tiposervice").val());
			data.append("pv_via", $("#pv_via").val());
			data.append("pv_select", $("#pv_select").val());
			data.append("detalle_porteador", $("#detalle_porteador").val());
			data.append("detalle_acarga", $("#detalle_acarga").val());
			data.append("tramite_ad", $("#tramite_ad").val());
			proveinte = $("#v_Proveedor").is(':checked');
			data.append("v_Proveedor", proveinte);
		}

		if ($("#v_poseedor_vehiculo").is(':checked') && datotenedor == 'no') {
			tene = $("#v_poseedor_vehiculo").is(':checked');
			data.append("v_poseedor_vehiculo", tene);
		}
		if ($("#v_propietario_vehiculo").is(':checked') && datopropietario == 'no') {
			propieta = $("#v_propietario_vehiculo").is(':checked');
			data.append("v_propietario_vehiculo", propieta);
		}
		//ELIMINAR
		if (!$("#v_Conductor").is(':checked') && datoconductor == 'si') {
			driver = $("#v_Conductor").is(':checked');
			data.append("v_Conductor", driver);
		}

		if (!$("#v_propietario_vehiculo").is(':checked') && datopropietario == 'si') {
			propieta = $("#v_propietario_vehiculo").is(':checked');
			data.append("v_propietario_vehiculo", propieta);
		}

		if (!$("#v_poseedor_vehiculo").is(':checked') && datotenedor == 'si') {
			tene = $("#v_poseedor_vehiculo").is(':checked');
			data.append("v_poseedor_vehiculo", tene);
		}

		if (!$("#v_Proveedor").is(':checked') && datoproveedor == 'si') {
			proveinte = $("#v_Proveedor").is(':checked');
			data.append("v_Proveedor", proveinte);
		}

		$.ajax({
			url: url,
			type: 'POST',
			data: data,
			cache: false,
			processData: false, // Don't process the files
			contentType: false, // Set content type to false as jQuery will tell the server its a query string request
			dataType: 'json',
			beforeSend: function(jqXHR, settings) {
				// console.log("Entro en el proceso de creación del proveedor");
				// console.log(data);
				$(".nexos-messages").html('<div id="clock" role="modal" class="modal" style="display: block; background-color: rgba(0,0,0,0.5););"><div style="text-align: center; margin-top: 10%; background-color: #fff; padding: 30px; min-width: 20%; max-width: 60%; border-radius: 5px; border: 1px solid rgba(0,0,0,0.8); margin: 10% auto;"><img src="' + $("#id_url_ajax").val() + 'public/img/nexos_loading.gif" height="60" width="60"><h3>Solicitud en proceso...</h3><h4>Por favor, espere unos segundos.</h4></div></div>');
			},
			success: function(data, textStatus, jqXHR) {
				// console.log(data);
				if (!data.error) {
					if ($("#v_Proveedor").is(':checked')) {
						insertcontac();
					}
					$(".nexos-messages").html('<div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-check"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Proceso terminado!</strong> Se ha actualizado el registro con éxito.</div></div>');
					$("html, body").animate({
						scrollTop: 0
					}, 600);
					setTimeout(function() {
						location.reload(false);
					}, 800);
				} else {
					var msg_error = data.error.replace(/\n/g, "</p><p>");
					$(".nexos-messages").html('<div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible"><div class="icon"><span class="mdi mdi-close"></span></div><div class="message"><button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong>' + msg_error + '</div></div>');
					$("html, body").animate({
						scrollTop: 0
					}, 600);
				}
			},
			error: function(jqXHR, textStatus, errorThrown) {

				console.log(jqXHR);
				console.log(textStatus);
				console.log(errorThrown);
			}
		});

		//CREACION DE CONTACTOS DE PROVEEDORES
		function insertcontac() {
			var canti = $("#cont_contactos").val();
			if (canti > 0) {
				var i;
				for (i = 1; i <= canti; i++) {
					if (typeof $("#sk" + i).val() !== 'undefined') {
						var nombre = $("#nombres" + i).val();
						var cargo = $("#cargo" + i).val();
						var fijo = $("#fijo" + i).val();
						var celular = $("#celular" + i).val();
						var correo = $("#correo" + i).val();
						var critica = $("#critica" + i).val();
						var refe = $("#refe" + i).val();
						data.append("accion", 'crearContactostp');
						data.append("id_proveedor", $("#id_proveedor").val());
						data.append("nombre", nombre);
						data.append("cargo", cargo);
						data.append("fijo", fijo);
						data.append("celular", celular);
						data.append("correo", correo);
						data.append("critica", critica);
						data.append("refe", refe);
						data.append("verifica", 2);

						$.ajax({
							url: url,
							type: 'POST',
							data: data,
							cache: false,
							processData: false, // Don't process the files
							contentType: false, // Set content type to false as jQuery will tell the server its a query string request
							dataType: 'json',
							success: function(data, textStatus, jqXHR) {
								console.log('si inserto contactos del proveedor');
								// alert('!!Registro Vehiculo exitosamente!!!');
							},
							error: function(jqXHR, textStatus, errorThrown) {
								console.log('no inserto contactos del proveedor');
								console.log(jqXHR);
								console.log(textStatus);
								console.log(errorThrown);
							}
						});

					}
				}
			}
		}

	}
</script>