<?php
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];
$vista = '';
$table_content = '';
$table_content1 = '';
$table_rutas = '';
$num_plan = '';

if (isset($this->planes)) {
  $arrayPermisos = $this->planes->permisosPerfil($ssn_id_perfil, 117);
  $_permisos = $arrayPermisos;
  $btn_crear = '';
  if ($_permisos["adicionar"] == 1) {
    $btn_crear = '<a id="btn_crea" href="#"  data-toggle="modal"  class="cell-detail  hint--top btn btn-success btn-xs"  data-hint="" data-target="#crear_plan"><span class="icon mdi mdi-plus" title="Detalle Ruta Nuevo"></span> Crear Detalle Ruta</a>';
    $btn_copiar = '<a id="btn_copiar" href="#"  data-toggle="modal"  class="cell-detail  hint--top "  data-hint="" data-target="#copiar_ruta"><span class="icon mdi mdi-copy" title="Copiar Detalle Ruta"></span></a>';
  }
  $table_rutas .= "
	<div class='row' >
	<div class='col-sm-12'>
		<div  class='table-responsive noSwipe'>
			<table id='table1' class='table table-striped table-hover' data-page-length='100'>
			<thead style='background-color:#332D2D;color:#fff;text-align:center;'>
				<tr>
					<th style='width:10px'>Código</th>
					<th style='width:280px'>Origen</th>
					<th style='width:280px'>Destino</th>
					<th style='width:10px' class='text-center'>Seleccionar</th>
				</tr>
			</thead>
			<tbody>";
  $array = $this->planes->traerruta_modal();
  $uno = 0;
  if ($array) {
    foreach ($array["rowsData"] as $key => $value) {
      $uno++;
      //traer codigos de las ciudades
      $cod_origen = $value['cod_ciudad_origen'];
      $cod_destino = $value['cod_ciudad_destino'];
      //enviar esos codigos a otra función
      $array2 = $this->planes->traer_lugar_origen($cod_origen);
      $array3 = $this->planes->traer_lugar_destino($cod_destino);

      if ($array2 && $array3) {
        //foreach de origen
        foreach ($array2["rowsData"] as $key => $value2) {
          foreach ($array3["rowsData"] as $key => $value3) {

            $o_letra = $value2['municipio'] . '-' . $value2['depto'];
            $d_letra = $value3['municipio'] . '-' . $value3['depto'];

            $municipios = $value2['municipio'] . ' ' . $value3['municipio'];

            $table_rutas .= "
					<tr>
					<td class='cell-detail text-center'>
						<span><strong>$value[id]</strong></span>
					</td>
					<td class='cell-detail'>
						<span >
						$value2[municipio] - $value2[depto]
						</span>
					</td>
					<td class='cell-detail'>
						<span >
						$value3[municipio] - $value3[depto]
						</span>
					</td>
					<td class='cell-detail'>
						<button id='btn_uno" . $uno . "'  class='btn btn-space btn-success btn-xs mdi mdi-check' style='border-radius:25px;' onclick='verVehiculo(this);'
						 data-id='" . $value['id'] . "' data-id2='" . $value['cod_ciudad_origen'] . "' data-id3='" . $value['cod_ciudad_destino'] . "'
						 data-id4='" . $value['observaciones'] . "'
						 	data-id5='" . $o_letra . "'
						 	data-id6='" . $d_letra . "'
						 	data-id7='" . $value['latitud_origen'] . "'
						 	data-id8='" . $value['latitud_destino'] . "'
						 	data-id9='" . $value["longitud_origen"] . "'
						 	data-id10='" . $value["longitud_destino"] . "'
						 	data-id11='" . $municipios . "'
						 	data-id12='" . $value["tiempo_tot_ruta"] . "'
						 	data-id13='" . $value["km_tot_ruta"] . "'>
						</button>
					</td>
					</tr>";
          }
        }
      }
      //cierre del foreach principal
    }
  }
  $table_rutas .=
    "</tbody>
		</table>
	</div>
	</div>
</div>";

  //N° PLAN
  $cuente = 0;
  $num_plan .= "
<input type='number' id='num_plan' class='form-control input-sm text-center' readonly='readonly' style='font-size:14pt; font-weight:700;'";
  $array2 = $this->planes->n_plan();
  if ($array2) {
    foreach ($array2["rowsData"] as $key => $value) {
      $cuente++;
      if ($value['nco'] == '' || $value['nco'] == (null)) {
        $num_plan .= 'value="' . $cuente . '"';
      }
      if ($value['nco'] != ' ' || $value['nco'] != (null)) {
        $num_plan .= 'value="' . $value['nco'] . '"';
      }
    }
  }
  $num_plan .= ">";

  $vista .= '
		<div class="col-xs-12 col-sm-12 col-md-12">
		<div class="panel panel-border panel-contrast">
			<div class="panel-body" style="padding: 1px 1px 1px 1px;">
				<div class="nexos-messages"></div>
				<div class="nexos-content">
					%content%
				</div>
				<div class="row">
					<div class="col-sm-12"></div>
				</div>
			</div>
		</div>
	</div>
';

  $table_content .= '
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div>
      <div class="text-right" style="margin-top:5px;">
        ' . $btn_crear . '
      </div>
    </div>
  </div>

		<div class="form-group col-xs-4 col-sm-4 col-md-4">
			<label>Origen Ruta</label>
			<select class="form-control input-xs" id="Punto">
				<option value="" readonly="readonly">Seleccione</option>
			</select>
		</div>
		<div class="form-group col-xs-4 col-sm-4 col-md-4">
			<label>Destino Ruta</label>
			<select class="form-control input-xs" id="Destino">
				<option value="" readonly="readonly">Seleccione</option>
			</select>
		</div>
		<div class="form-group col-xs-3 col-sm-3 col-md-4">
			<!--<button class="form-control input-xs btn btn-info mdi mdi-search" id="consulte" onclick="solicitudes_rutas();" style="margin-top:25px;">
				Consultar
			</button>-->

			<button class=" form-control input-xs btn btn-info btn-xs mdi mdi-search" id="btn_consulta_rutas" onclick="solicitudes_rutas();"
      style="margin-top:25px;">
      Consultar
    </button>
		</div>
	';

  $vista .= '
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			%content1%
		</div>
		';

  $table_content1 .= '
		<div id="esconder">
		<div class="row">
			<div class="col-sm-12">
				<div class="table-responsive noSwipe">
					<table id="table1" class="table table-striped table-hover table-fw-widget">
						<thead style="background-color:#332D2D;color:#fff;text-align:center;">
							<tr>
								<th>#</th>
								<th>N° Ruta / N° Plan</th>
								<th>Origen</th>
								<th>Destino</th>
								<th>Estado de Ruta</th>
								<th>Acción</th>
							</tr>
						</thead>
						<tbody id="body_esconder">
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>';
} ?>

<script type="text/javascript">
  $(document).on('click', '#pruebabtn', function() {
    $('#exampleModalLong').modal('show');
  });
  //cierre de botones del segundo modal
  $(document).on('click', '#cierre', function() {
    $('#exampleModalLong').modal('hide');

  });
</script>

<div id="crear_plan" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary" style="overflow-y:auto;">
  <div class=".modal-dialog-modal-lg .modal-dialog ">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:left;height: 50px;padding: 19px;">
        <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close" style="color: #fff;"><span class="mdi mdi-close"></span></button>
        <h4 class="modal-title" id="titulo"><i class="fas fa-road"></i> Crear Detalle de ruta</h4>
      </div>
      <div class="modal-body" style="padding: 1px 1px 1px;">
        <div id="msg_crear"></div>
        <div id="historico"></div>
        <div id="content_editar">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="row">
              <!-- <label>Seleccione La ruta</label> -->
              <button type="button" id="pruebabtn" data-toggle="modal" class="btn btn-warning btn-xs"><i class="fas fa-road"></i> Seleccionar Ruta</button>
            </div>
          </div>
          <!--MODAL DE LA RUTA -->
          <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class=".modal-dialog-centered.modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:left;height: 50px;padding: 19px;">
                  <h5 class="modal-title" id="exampleModalLongTitle">Seleccione la ruta</h5>
                  <button type="button" class="close" id="cierre" aria-label="Close" style="color: #fff;"><span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <!--cuerpo inicio -->
                  <div class="row  " style="border:1px solid silver;">
                    <!--input con el nombre del cliente donde se va a guardar -->
                    <div class="form-group col-xs-12 col-sm-12" style="padding:20px; ">
                      <label style="font-weight:700; font-size:14pt;">Código de Ruta:&nbsp;<span style="color:red;"><i>(*)</i></span></label>
                      <input type="text" placeholder="codigo" class="typeahead form-control input-sm" id="cargar_cliente" readonly="readonly">
                    </div>
                    <div>
                      <p class="text-center"><strong>Señor Usuario su ruta no se encuentra por favor creela en el
                          submenú rutas.</strong></p>
                    </div>
                    <!--datatable para seleccionar el cliente -->
                    <div class="form-group col-xs-12 col-sm-12">
                      <!-- inicio de la tabla-->
                      <?php echo $table_rutas; ?>
                      <!-- fin tabla -->
                    </div>
                  </div>
                  <!-- cuerpo fin  -->
                </div>
                <div class="modal-footer">
                  <button id="cierre" class="btn btn-secondary">Cerrar</button>
                </div>
              </div>
            </div>
          </div>
          <!--Acordeones de ruta llena y el plan-->
          <br>
          <div class="row" id="div_rp">
            <div class="col-sm-12 col-xs-12 col-md-12 col-lg-12">
              <div id="accordion1" class="panel-group accordion">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion1" href="#collapseOne">
                        <i class="icon mdi mdi-chevron-down"></i><strong> Creación detalle de ruta</strong></a>
                    </h4>
                  </div>
                  <div id="collapseOne" class="panel-collapse collapse in">
                    <div class="panel-body" style="padding: 1px 1px 1px;">
                      <h3>
                        <p class="text-center" style="font-size:12pt; font-weight:500; color:#2E2E2E;">Ruta Seleccionada
                        </p>
                      </h3>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                          <label>Código de Ruta</label>
                          <input type="text" id="r_id" class="form-control input-sm text-center" readonly="readonly" style="font-size:12pt;">
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                          <label>Ruta(origen-destino)</label><br>
                          <label id="rutacompl" class="text-primary text-center" style="font-size:12pt; text-align:center;"></label><br>
                          <input type="hidden" id="r_origen" readonly="readonly">
                          <input type="hidden" id="r_destino" readonly="readonly">
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                          <label>Tiempo total de la ruta</label>
                          <input type="text" id="timeruta" class="form-control input-xs" readonly="readonly">
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                          <label>Kilométro total de la ruta</label>
                          <input type="text" id="kilometerruta" class="form-control input-xs" readonly="readonly">
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                          <label>Observaciones</label>
                          <textarea id="r_obser" class="form-control input-sm" rows="1" readonly="readonly"></textarea>
                        </div>
                      </div>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div id="mapruta" style="height:300px; width:95%; margin-top:30px;"></div>
                      </div>
                    </div>
                    <div class="panel-body">
                      <h3>
                        <p class="text-center" style="font-size:12pt; font-weight:500; color:#2E2E2E;">Detalle de ruta
                        </p>
                      </h3>
                      <hr>
                      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                          <label>N° Detalle</label>
                          <?php echo $num_plan; ?>
                        </div>
                        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
                          <label>Nombre de Detalle de ruta</label>
                          <input type="text" id="p_planname" class="form-control input-xs">
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                          <label>Detalle</label>
                          <textarea id="p_planob" class="form-control input-xs"></textarea>
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                          <input type="hidden" id="p_fechac" class="form-control input-xs" readonly="readonly" value="<?php echo date('Y-m-d'); ?>">
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">

                          <input type="hidden" id="p_horac" class="form-control input-xs" readonly="readonly" value="<?php echo date('H:i:s'); ?>">
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">

                          <input type="hidden" id="p_userc" class="form-control input-xs" readonly="readonly" value="<?php echo $ssn_nombre; ?>">
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                          <input type="hidden" id="cab" value="1">
                          <input type="hidden" id="puntos" value="2">
                        </div>
                      </div>
                    </div>

                    <!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"></div> -->
                    <div class="panel panel-border-color panel-border-color-primary">
                      <div class="panel-heading" style="padding: 1px 1px 1px;">Puntos</div>
                      <div class="panel-body">
                        <div class="row">
                          <!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"></div> -->
                          <div class="panel-body">
                            <div class="table-responsive noSwipe">
                              <table class="table table-condensed" id="tabla_plan">
                                <thead>
                                  <tr>
                                  </tr>
                                </thead>
                                <tbody id="punto_plan_crear">
                                </tbody>
                              </table>
                            </div>
                          </div>

                          <div class="col-xs-6 col-sm-2 col-md-2 col-lg-12 text-right" style="margin-bottom: 5px;">
                            <button class="btn btn-info btn-xs" data-toggle="tooltip" data-placement="top" title="Agregar fila" id="agregar_fila"><i class="far fa-plus-square"></i> Agregar
                              Punto</button>
                          </div>
                        </div>
                        <!-- <div class="text-right">
														<button id="anadirpunto" type="button" class="btn btn-success btn-xs md-close" onclick=""><i class="far fa-save"></i> Registrar puntos</button>
													</div> -->

                        <table class="table" id="tabla_final">
                          <thead>
                            <tr>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                            <tr colspan="5" style="text-align:left; color:white; background-color:#33b5e5; height:20px;">
                              <th>Punto paramétrico final</th>
                            </tr>
                            <td> </td>
                            <tr>
                              <th>Nombre Punto</th>
                              <th>Ubicación</th>
                              <th>Tiempo Estimado (minutos)</th>
                            </tr>
                            <td><input type="text" id="p_puntofinal" class="form-control" style=" height:14px; font-size:90%;" value="Lugar Llegada" readonly="readonly"></td>
                            <td><select class="form-control input-xs" id="p_ciudadfinal" readonly="readonly"></select>
                            </td>
                            <td><input type="number" id="p_tiempofinal" class="form-control" placeholder="Respecto al punto anterior (min)" title="En minutos" style=" height:14px; font-size:90%;"></td>
                            </tr>
                            <tr>
                              <th>Descripción</th>
                              <th>Km estimados
                                <span class="cell-detail-description"> desde el punto anterior</span>
                              </th>
                              <th>Orden</th>
                            </tr>
                            <tr>
                              <td><textarea id="p_descrifinal" class="form-control" style="width:310px; height:14px; font-size:90%;" readonly="readonly">Lugar de destino de la ruta, este punto indica el lugar de llegada</textarea>
                              </td>
                              <td><input type="number" id="p_kmfinal" class="form-control" placeholder="Km estimados desde el punto anterior" style="width:169px; height:14px; font-size:90%;"></td>
                              <td><input type="text" id="ordenfinal" class="form-control input-xs" readonly="readonly">
                              </td>
                            <tr>
                              <th>Tipo punto</th>
                              <th>Latitud</th>
                              <th>Longitud</th>
                            </tr>
                            <tr>
                              <td><select id="tpfinal" class="form-control input-sm" style="width:169px; height:25px; font-size:90%;">
                                  <option value="">Seleccione</option>
                                  <option value="punto geografico">Punto virtual</option>
                                </select></td>
                              <td> <input type="number" id="latitudfinal" class="form-control" style="width:169px; height:25px; font-size:90%;" readonly="readonly"></td>
                              <td> <input type="number" id="longitudfinal" class="form-control" style="width:169px; height:25px; font-size:90%;" readonly="readonly"></td>
                            </tr>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn btn-danger btn-xs md-close"><i class="fas fa-times"></i>
          Cancelar</button>
        <button id="btn_guadarplan" type="button" class="btn btn-success btn-xs md-close" onclick=""><i class="far fa-save"></i> Guardar Detalle Ruta</button>
      </div>
    </div>
  </div>
</div>
</div>

<!--consultar puntos  -->
<div id="ver_puntos" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
  <div class="modal-dialog custom-width">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:left;height: 50px;padding: 19px;">
        <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close" style="color: #fff;"><span class="mdi mdi-close"></span></button>
        <h4 class="modal-title" id="editar_title">
          <b>Consultar Puntos de la Ruta</b>
        </h4>
      </div>
      <div class="modal-body" style="padding: 1px 1px 1px;max-height: 550px; overflow-y: auto;overflow-x: hidden;">
        <div id="msg_edicion"></div>
        <div id="content_editar">
          <!-- <div class="row"></div> -->
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-2">
            <label style="font-weight:bold;">Código de Ruta</label>
            <input type="text" id="codigo_r" readonly="readonly" class="form-control input-xs text-center">
          </div>
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-2">
            <label style="font-weight:bold;">Código detalle ruta</label>
            <input type="text" id="codigo_p" readonly="readonly" class="form-control input-xs text-center">
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-8">
            <label style="font-weight:bold;">Nombre Detalle ruta</label>
            <input type="text" id="nombre_p" class="form-control input-xs text-center" readonly="readonly">
          </div>
          <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <label style="font-weight:bold;">Kilómetros</label>
            <input type="text" id="kilop" class="form-control input-xs text-center" readonly="readonly">
          </div>
          <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <label style="font-weight:bold;">Tiempo</label>
            <input type="text" id="tiempo_p" class="form-control input-xs text-center" readonly="readonly">
          </div>
          <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <label style="font-weight:bold;">Estado</label>
            <input type="text" id="estado_p" class="form-control input-xs text-center" readonly="readonly">
          </div>

          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="margin-top: 15px;">
              <div class="panel panel-default panel-table">
                <div class="panel-heading" style="padding: 1px 1px 1px;">
                  <h5 style="font-weight: bold;">Puntos Virtuales</h5>
                  <!-- <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div> -->
                </div>
                <div class="panel-body">
                  <div class="table-responsive noSwipw">
                    <table class="table table-condensed">
                      <thead style="text-align:left; color:white; background-color:#332D2D;">
                        <tr>
                          <th style="width:22%;">Orden</th>
                          <th style="width:22%;">Ciudad</th>
                          <th style="width:11%;">Tiempo</th>
                          <th style="width:30%;">Descripción</th>
                          <th style="width:20%;">Kilómetros</th>
                          <th>Latitud</th>
                          <th>Longitud</th>
                          <th>Usuario</th>
                        </tr>
                      </thead>
                      <tbody id="body_puntosg"></tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <!-- <div id="" style="margin:auto;"></div> -->
            <div id="mapcontrol" style="height:400px; width:100%; margin-top:10px"></div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
        </div>
      </div>
    </div>
  </div>
</div>

<!--actualizar el plan-->
<div id="upda_puntos" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
  <div class="modal-dialog modal-lg custom-width">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#332D2D;color:#fff;text-align:left;height: 50px;padding: 19px;">
        <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close" style="color: #fff;"><span class="mdi mdi-close"></span></button>
        <h4 class="modal-title" id="titulo"><i class="fas fa-map-marked-alt"></i> Actualizar Detalle de ruta</h4>
      </div>
      <!-- <div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;"> -->
      <div class="modal-body" style="padding: 1px 1px 1px;max-height: 600px; overflow-y: auto;overflow-x:hidden;">
        <div id="msg_edicion_ac"></div>
        <div id="content_editar">
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div class="panel panel-default panel-contrast">
                <div class="panel-heading">
                  <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4">
                      <div class="col">
                        <label style="font-weight:800;">Código de Ruta</label>
                        <input type="text" id="codigo_e" readonly="readonly" class="form-control input-xs text-center" style="font-size:8pt;">
                      </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4">
                      <label style="font-weight:800;">Código de Detalle de ruta</label>
                      <input type="text" id="plan_e" readonly="readonly" class="form-control input-xs text-center" style="font-size:8pt;">
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4">
                      <label style="font-weight:800;">Nombre detallado</label>
                      <input type="text" id="namep_e" class="form-control input-xs text-center" readonly>
                    </div>

                  </div>
                </div>
                <div class="panel-body panel-body-contrast">
                  <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                      <label style="font-weight:800;">Detalle de ruta</label>
                      <textarea id="deta_pe" class="form-control input-xs" rows="1"></textarea>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4">
                      <label style="font-weight:800;">Habilitar</label>
                      <select id="es_e" class="form-control input-xs"></select>
                    </div>
                    <div class="col-xs-6 col-sm-2 col-md-2 col-lg-2">
                      <button id="btn_editarplan" type="button" class="btn btn-success btn-xs md-close" onclick="" style="margin-top: 30px;"><i class="far fa-save"></i> Guardar Estado</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div>
              <div>
                <input type="hidden" id="codigo_rm" readonly="readonly" class="form-control input-sm text-center" style="font-size:12pt;">
                <input type="hidden" id="codigo_pm" readonly="readonly" class="form-control input-sm text-center" style="font-size:12pt;">
              </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div class="panel panel-border-color panel-border-color-primary panel-table">
                <div class="row">
                  <div class="ccol-xs-12 col-sm-12 col-md-10 col-lg-10">
                    <div class="panel-heading" style="padding: 1px 1px 1px;">Punto de ruta actuales</div>
                  </div>
                  <div class="ccol-xs-12 col-sm-12 col-md-2 col-lg-2" style="margin-top: 2px;">
                    <button class="btn btn-info btn-xs" onclick="abrir_ventana();"><i class="fas fa-map-marker-alt"></i> Crear punto de Ruta</button>
                    <input type="hidden" name="plan_id" id="plan_id">
                  </div>
                </div>

                <div class="panel-body">
                  <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                      <div class="table-responsive noSwipe">
                        <table class="table table-striped table-hover table-fw-widge dataTable no-footer" id="tbl_puntos">
                          <thead style="background-color:#332D2D;color:#fff;text-align:center;">
                            <tr>
                              <th></th><!-- style="display: none;" -->
                              <th>#</th>
                              <th>Tipo</th>
                              <th>Ciudad</th>
                              <th>Punto</th>
                              <th>Tiempo</th>
                              <th>Descripción</th>
                              <th>Kilómetros</th>
                              <th>Latitud</th>
                              <th>Longitud</th>
                              <!-- <th style="width: 5px;">Acción</th> -->
                            </tr>
                          </thead>
                          <tbody id="body_puntose">
                          </tbody>
                        </table>
                      </div>

                      <!-- <div style="margin: 2px;">
												<button id="agregarBoton">Previsualizar Plan</button>
												<div id="resultado"></div>
											</div> -->
                    </div>

                  </div>

                </div>
              </div>
              <div>
                <!-- <input type="button" name="guardarPunT" value="Guardar" id="guardarPunT" /> -->
                <div class="text-right" style="margin-bottom: 10px;margin-top: -8px;">
                  <button class="btn btn-success btn-xs" id="guardarPunT"><i class="fas fa-sync-alt"></i> Actualizar Plan de Ruta</button>
                </div>
              </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div class="panel panel-border-color panel-border-color-primary">
                <div class="panel-heading" style="padding: 1px 1px 1px;font-weight: bold;">Nuevos puntos</div>
                <div class="panel-body" style="padding: 1px 1px 1px;">
                  <div class="row">
                    <!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"></div> -->
                    <div class="panel-body">
                      <div class="table-responsive noSwipe">
                        <table class="table table-condensed" id="punto_plan">
                          <thead>
                            <tr>
                            </tr>
                          </thead>
                          <tbody id="accion_puntos">
                          </tbody>
                        </table>
                      </div>
                    </div>
                    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-12" style="margin-bottom: 5px;">
                      <div id="historicos"></div>
                      <button class="btn btn-info btn-xs" data-toggle="tooltip" data-placement="top" title="Agregar fila" id="agregar_punto"><i class="fas fa-plus-square"></i> Añadir Nuevo Punto</button>
                    </div>
                  </div>
                  <div class="text-right">
                    <button id="anadirpunto" type="button" class="btn btn-success btn-xs md-close" onclick=""><i class="far fa-save"></i> Registrar puntos</button>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
        <div class="modal-footer">
          <button type="button" data-dismiss="modal" class="btn btn-danger btn-xs md-close"><i class="fas fa-times"></i> Cancelar</button>
        </div>
      </div>
    </div>
  </div>
</div>

<!--agregar mas puntos-->
<div id="mas_puntos" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
  <div class="modal-dialog custom-width">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
        <h3 class="modal-title" id="editar_title">
          <label id="titulo" style="font-size:20pt; color:white; text-align:center;">Acción a Puntos de la Ruta</label>
        </h3>
      </div>
      <div class="modal-body" style=" margin-top:20px; margin-bottom:20px;  margin-right:20px;  margin-left:20px;">
        <div id="msg_edicion_mpunto"></div>
        <div id="content_editar">
          <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <label style="font-weight:800; margin-top:20px; ">Código de Ruta</label>
              <input type="text" id="codigo_rm" readonly="readonly" class="form-control input-sm text-center" style="font-size:12pt;">
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
              <label style="font-weight:800; margin-top:20px; ">Código de Plan</label>
              <input type="text" id="codigo_pm" readonly="readonly" class="form-control input-sm text-center" style="font-size:12pt;">
            </div>
          </div><br>
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div class="panel panel-default panel-table">
                <div class="panel-heading">Puntos Asociados a este plan
                  <!--boton agregar puntos-->
                  <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                    <button class=" form-control btn btn-info mdi mdi-plus input-xs text-center" data-toggle="tooltip" data-placement="top" title="Agregar fila" id="agregar_punto">
                    </button>
                  </div>
                  <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div>
                </div>
                <div class="panel-body">
                  <table class="table" id="punto_plan">
                    <thead>
                      <tr>

                      </tr>
                    </thead>
                    <tbody id="accion_puntos">
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button id="anadirpunto" type="button" class="btn btn-success md-close" onclick="">Añadir</button>
          <button type="button" data-dismiss="modal" class="btn btn-default md-close">Cancelar</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script src=<?php echo BASE_URL; ?>/views/control_ruta/js/control_ruta.js type="text/javascript"></script>
<!-- <script src="%root_file%lib/planes_ajax.js" type="text/javascript"></script> -->
<?php
$vista .= '
	<script  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMwRwybUARcBql3j71ykZpBTavAmkiqRo"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
			<script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/planes_ajax.js" type="text/javascript"></script>
			<script src="%root_file%js/main.js" type="text/javascript"></script>
			<script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
			<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
			<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

			<script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
			<script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
			<link  rel="stylesheet" type="text/css" href="assets/lib/select2/css/select2.min.css"/>

			<link rel="stylesheet" type="text/css" src="%root_file%lib/assets/lib/select2/css/select2.min.css"/>


			<script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
			<script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

			<!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
			<script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
			<script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
			<script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>

			<!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
			<script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
			<script type="text/javascript">
				$.fn.niftyModal(\'setDefaults\',{
					overlaySelector: \'.modal-overlay\',
					closeSelector: \'.modal-close\',
					classAddAfterOpen: \'modal-show\',
				});
				$(document).ready(function(){
					//initialize the javascript
					App.init();
				});
				$(document).ready(function(){
					//initialize the javascript
					App.init();
					App.dataTables();
				});
				$(document).ready(function(){
					//initialize the javascript
					App.init();
					App.wizard();
				});
			</script>
';
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%content%", $table_content, $vista);
$vista = str_replace("%content1%", $table_content1, $vista);
echo $vista;
?>