<?php
$ssn_id_cliente = $_SESSION["usuario"]["id_cliente"];
$ssn_id_usuario = $_SESSION["usuario"]["id_usuario"];
$ssn_nombre = $_SESSION["usuario"]["nom_usuario"];
$ssn_id_perfil = $_SESSION["usuario"]["id_perfil"];

$vista = '';
$table_content = '';
$cod_inicia = '';
$cuerpo = '';

if (isset($this->continuaruta)) {
  $arrayPermisos = $this->continuaruta->permisosPerfil($ssn_id_perfil, 127);
}

$vista .= '';
$fecha_actual = date("Y-m-d H:i:s");

$vista .= '
<div class="row" style="margin:-25px -39px -10px -39px;">
  <div class="col-xs-4 col-sm-4 col-md-12 col-lg-12">
    <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
      <tbody>
        <tr>
          <td class="celda_titulo2" style="margin:25px;">
            <b>Información Principal</b>
          </td>
        </tr>
        <tr>
        </tr>
      </tbody>
    </table>
    <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;margin-bottom: 10px;font-zise: 8px;">
      <thead>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Manifiesto:</th>
          <td class="manifiesto gif-cell" style="border: 1px solid #ddd;padding: 1px;"></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Origen: </th>
          <td class="origen gif-cell" style="border: 1px solid #ddd;padding: 1px;"></td>
        </tr>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Agencia </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="agencia gif-cell"></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Destino </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="destino gif-cell"></td>
        </tr>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Conductor </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="conductor gif-cell"></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Ruta </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="ruta gif-cell"></td>
        </tr>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            C.C. </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="documento gif-cell"></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Fecha Salida </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="fecha-salida gif-cell"></td>
        </tr>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Celular </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="celular gif-cell"></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Fecha planeada Llegada </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="fecha-llegada gif-cell"></td>
        </tr>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Telefono </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="telefono gif-cell"></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Fecha Creación </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="fecha-creacion gif-cell">' . $fecha_actual . '</td>
        </tr>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Marca </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="marca gif-cell"></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Placa </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="placa gif-cell"></td>
        </tr>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Linea </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="linea gif-cell"></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Configuración </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="configuración"></td>
        </tr>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Color </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="color gif-cell"></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Carroceria </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="carroceria gif-cell"></td>
        </tr>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Operador GPS </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="operador-gps gif-cell"></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Modelo </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="modelo gif-cell"></td>
        </tr>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Usuario GPS </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="usuario-gps gif-cell"></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">ID
            GPS </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="id-gps gif-cell"></td>
        </tr>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">URL
            GPS </th>
          <td style="border: 1px solid #ddd;padding: 1px;"><a class="url-gps gif-cell" target="framename"></a></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Clave GPS </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="clave-gps gif-cell"></td>
        </tr>
        <tr>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Remolque </th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="remolque gif-cell"></td>
          <th style="background-color: #F5F5F5; width: 150px;font-weight: bold;border: 1px solid #ddd;padding: 1px;">
            Usuario</th>
          <td style="border: 1px solid #ddd;padding: 1px;" class="usuario-salida gif-cell"></td>
        </tr>
      </thead>
    </table>
  </div>

  <div class="col-xs-4 col-sm-4 col-md-12 col-lg-12" style="margin-top:-15px;">
    <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
      <tbody>
        <tr>
          <td class="celda_titulo2" style="margin:25px;">
            <b>Información de Remesas en Seguimiento</b>
          </td>
        </tr>
        <tr>
        </tr>
      </tbody>
    </table>
    <table cellpadding="0" cellspacing="1" width="100%" border="0">
      <thead style="font-size: 8pt;background-color: #EEEEEE;border-bottom: 1px #ddd solid;">
        <tr>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Orden Carga</th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Remesa</th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Fecha Est. Entrega</th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Peso</th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Volumen</th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Empaque </th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Mercancia</th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Cliente</th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Remitente</th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Destinatario</th>
        </tr>
      </thead>
      <tbody id="tbl_informacion" style="font-size: 10px;border-bottom: 1px #ddd solid;border-right:1px #ddd solid;">
      </tbody>
    </table>
  </div>

  <div class="col-xs-4 col-sm-4 col-md-12 col-lg-12" id="plan_ruta_lista">
    <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
      <tbody>
        <tr>
          <td class="celda_titulo2" style="margin:25px;">
            <b>Información el plan de ruta</b>
          </td>
        </tr>
        <tr>
        </tr>
      </tbody>
    </table>
    <table cellpadding="0" cellspacing="1" width="100%" border="0" style="font-size: 8pt;">
      <thead style="font-size: 8pt;background-color: #EEEEEE;border-bottom: 1px #ddd solid;">
        <tr>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Punto</th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Fecha/Hora Control</th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Novedad</th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Municipio</th>
          <th style="width: auto; white-space: nowrap;border-right:1px #ddd solid;">Usuario</th>
        </tr>
      </thead>
      <tbody id="panel_control_plan_ruta" style="font-size: 10px;">
      </tbody>
    </table>
  </div>
  <!--<div id="" style="margin:auto;">
    <div id="mapcontrol" style="height:500px; width:95%; margin-top:30px"></div>
  </div>-->
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" >
    <div id="contenido-controlador"></div>
  </div>
  <!--<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="mapa_recorrido">
    <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
      <tbody>
        <tr>
          <td class="celda_titulo2" style="margin:25px;">
            <b>Ver recorrido del vehículo</b>
          </td>
        </tr>
        <tr>
        </tr>
      </tbody>
    </table>
    <div id="" style="margin:auto;">
      <div id="mapgeografico" style="height:400px; width:100%;"></div>
    </div>
  </div>-->
  <div class="col-xs-4 col-sm-4 col-md-12 col-lg-12" id="notas_controlador">
    <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;">
      <tbody>
        <tr>
          <td class="celda_titulo2" style="margin:25px;">
            <b>Información de Notas del Controlador</b>
          </td>
        </tr>
        <tr>
        </tr>
      </tbody>
    </table>
    <div class="hcontenedor"></div>
  </div>
</div>

<!-- Modal de loagoin -->
<dialog id="modal1" style="border:none;">
  <div style="text-align: center;">
    <img src="http://principal.nexosapp.com/public/img/nexos_loading.gif" height="100" width="100">
    <h3>Solicitud en proceso...</h3>
    <h4>Por favor, espere unos segundos.</h4>
  </div>
</dialog>

<!-- Mensajes para los usuarios de la plataforma -->
<div id="loading-overlay-nexosapp" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="http://principal.nexosapp.com/public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para NexosAPP...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
  </div>
</div>

<div id="loading-overlay-oet" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="http://principal.nexosapp.com/public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para Oet...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
  </div>
</div>

<div id="loading-overlay-rndc" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="http://principal.nexosapp.com/public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para el Ministerio...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
  </div>
</div>
';
?>

<?php
$vista .= '
     <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

     <script  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMwRwybUARcBql3j71ykZpBTavAmkiqRo"></script>


     <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
     <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
     <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
     <script src="%root_file%lib/seguimiento_rutab_ajax.js" type="text/javascript"></script>

     <script src="%root_file%js/main.js" type="text/javascript"></script>
     <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
     <script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
     <script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
     <script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
     <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
     <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
     <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
     <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
     <script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
     <script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

     <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>

     <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
     <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>

     <!-- CARGA DE ARCHIVOS JS DE CALENDARIOS -->
     <script src="%root_file%lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
     <script src="%root_file%lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
     <script src="%root_file%js/app-form-elements.js" type="text/javascript"></script>
		 <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
     <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
     <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
     <script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
     <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6vpUhRVoEe5U6m7Wh5_LFMCr_g8OzU1E&libraries=places&callback=initMap">
</script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
     <script type="text/javascript">
     $.fn.niftyModal(\'setDefaults\',{
     	overlaySelector: \'.modal-overlay\',
     	closeSelector: \'.modal-close\',
     	classAddAfterOpen: \'modal-show\',
     	});
     	$(document).ready(function(){
					//initialize the javascript
     		App.init();
     		});
     		$(document).ready(function(){
					//initialize the javascript
     			App.init();
     			App.dataTables();
     			});
     			$(document).ready(function(){
					//initialize the javascript
     				App.init();
     				App.wizard();
     				});
     				</script>
     				';
$vista = str_replace("%root_file%", $_layoutParams["ruta_layout"], $vista);
$vista = str_replace("%content%", $table_content, $vista);
$vista = str_replace("%cuerpo%", $cuerpo, $vista);
echo $vista;
?>