<div class="nexos-content">
  <div class="row" style="margin:-25px -39px -10px -39px;">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;font-weight: 300;">
        <tbody>
          <tr>
            <td class="celda_titulo2 text-center" style="margin:25px;">
              <b>Se encontraron <span id="num_manifiestos"></span> Manifiestos pendientes de darle salida a trafico</b>
            </td>
          </tr>
          <tr>
          </tr>
        </tbody>
      </table>
      <div id="mensaje"></div>
      <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;font-size: 8px;">
        <thead>
          <tr>
            <td class="text-left" style="border: 1px solid #ddd;padding: 1px 1px 1px;width: auto; white-space: nowrap;" colspan="1">
              <b style="font-size: 14px;font-weight: bold;">Buscar:</b> <input type="text" id="buscar_manifiesto" style="width: 250px;height: 22px;font-size: 12px;">
            </td>
          </tr>
        </thead>
      </table>
      <table cellpadding="0" cellspacing="0" border="1" style="width: 100%;font-size: 11px;border-bottom: 1px solid #332D2D;height: 5px;border: 1px solid #E0E0E0;">
        <thead style="border-collapse: collapse;background-color: #332D2D;color:#FBFBFB;" class="text-right">
          <tr>
            <th style="width: auto; white-space: nowrap;">Manifiesto</th>
            <!-- <th style="width: auto; white-space: nowrap;">Tipo Manifiesto</th> -->
            <th style="width: auto; white-space: nowrap;">Agencia</th>
            <!-- <th style="width: auto; white-space: nowrap;">Tipo Transporte</th> -->
            <th style="width: auto; white-space: nowrap;">Origen</th>
            <th style="width: auto; white-space: nowrap;">Destino</th>
            <th style="width: auto; white-space: nowrap;">Placa</th>
            <!-- <th style="width: auto; white-space: nowrap;">Gps</th> -->
            <th style="width: auto; white-space: nowrap;">Conductor</th>
            <th style="width: auto; white-space: nowrap;">Celular</th>
          </tr>
        </thead>
        <tbody id="tablero_salida" style="font-size: 9pt;"></tbody>
      </table>
    </div>
  </div>
</div>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type=" text/javascript">
</script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src=<?php echo BASE_URL; ?>views/control_ruta/js/salidas.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>public/helpers/helpers.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
<script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>
<script type="text/javascript">
  $(document).ready(function() {
    //initialize the javascript
    App.init();
  });
</script>