<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/v/bs-3.3.7/jq-3.7.0/jszip-3.10.1/dt-2.1.8/af-2.7.0/b-3.2.0/b-colvis-3.2.0/b-html5-3.2.0/b-print-3.2.0/cr-2.0.4/fc-5.0.4/sb-1.8.1/sl-2.1.0/datatables.min.css" rel="stylesheet">

<div class="nexos-content" style="padding: 1px 1px 1px;">
  <div class="row" style="margin:-25px -39px -10px -39px;">
    <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;font-weight: 300;">
      <tbody>
        <tr>
          <td class="celda_titulo2 text-left" style="padding-left: 25px;">
            Se encontraron total de <span class="badge" id="num_vehiculos_totales"></span> vehiculos en despacho
          </td>
        </tr>
        <tr>
        </tr>
      </tbody>
    </table>
    <div class="progress">
      <div class="progress-bar progress-bar" style="width:25%; background:#FFFF6C;">
        <span style="color:black;">Amarillo : 30 Min</span>
      </div>
      <div class="progress-bar progress-bar" style="width:25%; background:#FF9E5E;">
        <span style="color:black;">Naranja: 60 Min</span>
      </div>
      <div class="progress-bar progress-bar" style="width:25%; background:#FF8891;">
        <span style="color:black;">Rojo: 90 Min</span>
      </div>
      <div class="progress-bar progress-bar" style="width: 25%; background:#DDBBFF;">
        <span style="color:black;">Violeta: 120 Min</span>
      </div>
    </div>

    <div style="margin-top:-20px;">
      <table cellpadding="0" cellspacing="0" border="0" style="width:100%;background-color: #332D2D;color:#fff;font-weight: 300;padding: 1px 1px 1px;">
        <tbody>
          <tr>
            <td class="celda_titulo2 text-left" style="padding-left: 25px;">
              Se encontraron total de <span class="badge" id="num_vehiculos_seguimiento"></span> vehiculos en seguimiento
            </td>
          </tr>
        </tbody>
      </table>
      <div class="table-responsive noSwipe">
        <table id="tbl_Manifiestos_seguimiento" class="table table-condensed table-hover" style="font-size: 8pt;border-top: #FFFFFF 1px solid;">
          <thead style="background-color:#332D2D;color:#fff;">
            <tr>
              <th style="text-align: center; color: white;width: auto; white-space: nowrap;padding-left: 25px;">Manifiesto</th>
              <th style="color: white;width: auto; white-space: nowrap;">Tiempo</th>
              <th style="color: white;width: auto; white-space: nowrap;">Ruta</th>
              <th style="color: white;width: auto; white-space: nowrap;">Vehículo</th>
              <th style="color: white;width: auto; white-space: nowrap;">Conductor</th>
              <th style="color: white;width: auto; white-space: nowrap;">Celular</th>
              <th style="color: white;width: auto; white-space: nowrap;">Cliente</th>
              <th style="color: white; white-space: nowrap;">Sitio</th>
              <th style="color: white; white-space: nowrap;">Fecha Hora</th>
              <th style="color: white; white-space: nowrap;">Observación</th>
              <th style="color: white; white-space: nowrap;">Usuario</th>
            </tr>
          </thead>
          <tbody id="tablero"></tbody>
        </table>
        <!-- Tabla de llegada -->
        <table cellpadding="0" cellspacing="0" width="100%" border="0" style="background-color: #332D2D;color:#fff;font-weight: 300;">
          <tbody>
            <tr>
              <td class="celda_titulo2 text-left" style="padding-left: 25px;">
                Se encontraron <span class="badge" id="num_manifiestos_llegada"></span> Manifiestos sin darle llegada
              </td>
            </tr>
            <tr>
            </tr>
          </tbody>
        </table>
        <table cellpadding="0" cellspacing="0" border="0" style="width:100%; border-collapse: collapse;font-size: 8px;">
          <thead>
            <tr>
              <td class="text-right" style="border: 1px solid #ddd;padding: 1px 1px 1px;width: auto; white-space: nowrap;" colspan="4">
                <a href="JavaScript:void(0);" id="exportar_excel" style="text-decoration: none;cursor: pointer;color: #332D2D;"><img src="http://principal.nexosapp.com/public/img/excel_2013.png" alt="Excel" width="15px"> <span style="font-size: 11px;"> Exportar a excel</span></a>
              </td>
            </tr>
          </thead>
        </table>
        <!-- <div class="table-responsive noSwipe" style="padding-left: 25px;">  </div> -->
        <!-- <table id="table1" class="table table-condensed table-hover" style="font-size: 8pt;"> -->
        <table class="table" cellpadding="0" cellspacing="0" border="0" style="width: 100%;font-size: 11px;border-bottom: 1px solid #332D2D;height: 5px;padding-left: 25px;" id="informe_placas_asignadas">
          <thead style="border-collapse: collapse;background-color: #FBFBFB;color:#332D2D;">
            <tr>
              <th style="text-align: center; width: auto; white-space: nowrap;padding-left: 25px;">Manifiesto</th>
              <!-- <th style="width: auto; white-space: nowrap;">Tiempo</th> -->
              <th style="width: auto; white-space: nowrap;">Tipo Manifiesto</th>
              <!-- <th style="">Semaforo</th> -->
              <th style="width: auto; white-space: nowrap;">Agencia</th>
              <th style="width: auto; white-space: nowrap;">Origen</th>
              <th style="width: auto; white-space: nowrap;">Destino</th>
              <th style="width: auto; white-space: nowrap;">Mercancias</th>
              <th style="width: auto; white-space: nowrap;">Dta</th>
              <th style="width: auto; white-space: nowrap;">Vehículo</th>
              <th style="width: auto; white-space: nowrap;">Conductor</th>
              <th style="width: auto; white-space: nowrap;">Celular</th>
              <th style="width: auto; white-space: nowrap;">Cliente</th>
              <th style=" white-space: nowrap;">Novedad</th>
              <th style=" white-space: nowrap;">Fecha Hora</th>
              <th style=" white-space: nowrap;">Sitio</th>
              <th style=" white-space: nowrap;">Observación</th>
              <th style=" white-space: nowrap;">Usuario</th>
            </tr>
          </thead>
          <tbody id="tablero_llegada" style="font-size: 7pt;"></tbody>
        </table>
      </div>
    </div>


  </div>
</div>

<div id="loading-overlay-nexosapp" class="loading-nexosapp">
  <div style="text-align: center;">
    <img src="<?php echo BASE_URL; ?>public/img/nexos_loading.gif" height="120" width="120">
    <h2 style="color: #FFFFFF;font-weight: 400;">Solicitud en proceso para NexosAPP...</h2>
    <h4 style="color: #FFFFFF;">Por favor, espere unos segundos.</h4>
  </div>
</div>

<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js" type="text/javascript"></script>

<!-- Definir la función personalizada $.isXs -->
<script type="text/javascript">
  $.isXs = function() {
    return window.innerWidth < 768; // Detecta si el ancho de la pantalla es menor a 768px
  };
</script>

<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/js/main.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<!-- <script src="<?php echo BASE_URL; ?>views/control_ruta/js/tablero_ajax.js" type="text/javascript"></script> -->
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>

<!-- Datatable -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/v/bs-3.3.7/jq-3.7.0/jszip-3.10.1/dt-2.1.8/af-2.7.0/b-3.2.0/b-colvis-3.2.0/b-html5-3.2.0/b-print-3.2.0/cr-2.0.4/fc-5.0.4/sb-1.8.1/sl-2.1.0/datatables.min.js"></script>

<script type="text/javascript">
  $(document).ready(function() {
    //initialize the javascript
    App.init();

    // Prueba de $.isXs
    if ($.isXs()) {
      console.log("Dispositivo pequeño detectado");
    }
  });
</script>