<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recuperar Contraseña</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            font-family: "Segoe UI", sans-serif;
            background: url("img/fondo5.jpg") no-repeat center center fixed;
            background-size: cover;
            display: flex;
            flex-direction: column;
        }

        .overlay {
            background-color: rgba(0, 0, 0, 0.35);
            position: fixed;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            z-index: 1;
        }

        .login-container {
            z-index: 2;
            flex: 1;
            display: flex;
            align-items: center;
            justify-content: center;
            position: relative;
        }

        .login-box {
            background: rgba(28, 28, 28, 0.215);
            border-radius: 16px;
            padding: 40px;
            max-width: 400px;
            width: 90%;
            color: #fff;
            box-shadow: 0 8px 32px rgba(98, 98, 98, 0.2);
            border: 1px solid rgba(255, 255, 255, 0.2);
            backdrop-filter: blur(2px);
            -webkit-backdrop-filter: blur(2px);
        }

        .logo {
            display: flex;
            justify-content: center;
            margin-bottom: 15px;
        }

        .logo img {
            max-width: 300px;
            margin: 0;
        }

        .separator {
            height: 1px;
            background-color: #ccc;
            margin: 10px 0 20px;
        }

        .subtitle {
            font-size: 1rem;
            color: #ffffff;
            margin-bottom: 30px;
            text-align: center;
        }

        .form-label {
            color: #eee;
        }

        .form-control {
            border-radius: 10px;
            background-color: rgba(255, 255, 255, 0.1);
            border: 0.1px solid rgb(221, 221, 221);
            color: white !important;
        }

        .form-control:focus {
            background-color: rgba(255, 255, 255, 0.2);
            color: white !important;
            border: #fff;
        }

        .btn-login {
            background-color: #012A4A;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 10px;
            font-weight: 600;
        }

        input.form-control::placeholder {
            color: rgb(221, 221, 221) !important;
        }

        input.form-control:focus {
            border: 2px solid #077f97;
            box-shadow: 0 0 5px rgba(2, 134, 161, 0.6);
        }

        .btn-login:hover {
            background-color: #003a66;
        }

        footer {
            background-color: #012A4A;
            color: white;
            text-align: center;
            padding: 20px 0;
            font-size: 1.1rem;
            position: relative;
            z-index: 2;
        }
    </style>
</head>

<body>

    <div class="overlay"></div>

    <div class="login-container">
        <div class="login-box">
            <div class="logo">
                <img src="img/Icono-01.png" alt="HarmonyGroup">
            </div>
            <div class="separator"></div>
            <h4 class="text-center mb-2">¿Olvidaste tu contraseña?</h4>
            <p class="subtitle">Ingresa tu correo electrónico</p>
            <form>
                <div class="mb-4 text-start">
                    <label for="correo" class="form-label">Correo Electrónico</label>
                    <input type="email" class="form-control" id="correo" placeholder="usuario@ejemplo.com">
                </div>

                <button type="submit" class="btn btn-login w-100">Crear cuenta</button>
            </form>
        </div>
    </div>

    <footer>
        © 2025 HarmonyGroup - Todos los derechos reservados
    </footer>


    <!-- <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/jquery/jquery.min.js type="text/javascript"></script>
    <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js type="text/javascript"></script>
    <script src=<?php echo BASE_URL; ?>views/layout/assets/js/main.js type="text/javascript"></script>
    <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap/dist/js/bootstrap.min.js type="text/javascript">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
    <script src=<?php echo BASE_URL; ?>/views/informe/js/informe_calidad.js type="text/javascript"></script>
    <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/fuelux/js/wizard.js type="text/javascript"></script>
    <script src=<?php echo BASE_URL; ?>views/layout/assets/js/app-form-wizard.js type="text/javascript"></script>
    <script src=<?php echo BASE_URL; ?>views/layout/assets/lib/bootstrap-slider/js/bootstrap-slider.js type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            //initialize the javascript
            App.init();
        });
    </script> -->
</body>

</html>