<?php
	$vista = '';


  	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	$vista.= $alert->_alert_modal_mod_danger("elimina", "Realmente desea eliminar este elemento?");

	// POPUP DE FORMULARIO DE EDICION DE RIESGO DE COMERCIALIZACION
	$forms = '
		<form action="#">
			<div class="form-group col-xs-6">
				<label>Tipo de Contacto:</label>
				<select class="select2">
					<option value="" selected disabled>Seleccione</option>
					<option value="1">Contacto Principal</option>
					<option value="2">Contacto Logistico</option>
					<option value="3">Contacto Seguridad</option>
					<option value="4">Contacto Comercial</option>
					<option value="5">Contacto Administrativo</option>
					<option value="6">Contacto Tesoreria</option>
				</select>
			</div>
			<div class="form-group col-xs-12">
				<label>Nombre:</label>
				<input type="text" placeholder="Nombre" class="form-control">
			</div>
			<div class="form-group col-xs-6">
				<label>Teléfono:</label>
				<input type="text" placeholder="Número de Teléfono" class="form-control">
			</div>
			<div class="form-group col-xs-6">
				<label>Extensión:</label>
				<input type="text" placeholder="Extensión" class="form-control">
			</div>
			<div class="form-group col-xs-6">
				<label>Móvil:</label>
				<input type="text" placeholder="Número de Móvil" class="form-control">
			</div>
			<div class="form-group col-xs-6">
				<label>E-mail:</label>
				<input type="text" placeholder="Correo electrónico" class="form-control">
			</div>
		</form>
		<div class="row"></div>
	';

	$form_edita = new Popup();
	$vista.= $form_edita->_form_modal("edita", "Editar Información de Contacto" , $forms);

	$form_crea = new Popup();
	$vista.= $form_crea->_form_modal("crea", "Crear Contacto" , $forms);


	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Lista de Contactos - Praxair
				<div class="tools">
					<a href="' . BASE_URL . 'clientes/"class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>
					<a href="#" data-toggle="modal" data-target="#crea" class="cell-detail  hint--top"  data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a> 
				</div>
				<span class="panel-subtitle">Muestra los contactos que pertenecen a un cliente.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="row">
					<div class="col-sm-12">
				        <div class="table-responsive noSwipe">
							<table id="table1" class="table table-striped table-hover table-fw-widget">
								<thead>
									<tr class="nexos-encabezado">
										<th>Nombre</th>
										<th style="width:5%;">#</th>
										<th>Teléfono</th>
										<th>Móvil</th>
										<th>E-mail</th>
										<th style="width:10%;"></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>Maria Camila Torres</span>
											<span class="cell-detail-description">Contacto Principal</span>
										</td>
										<td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>(57) 1 3698744</span>
											<span class="cell-detail-description">Ext - 6</span>
										</td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>315 66699987</span>
										</td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>etorres@praxair.com</span>
										</td>
										<td class="actions">
											<span data-toggle="modal" data-target="#edita" class="icon mdi mdi-edit"></span>
											<span data-toggle="modal" data-target="#elimina" class="icon mdi mdi-close-circle"></span>
										</td>
									</tr>
									<tr>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>Pedro Avila</span>
											<span class="cell-detail-description">Contacto de Seguridad</span>
										</td>
										<td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>(57) 1 3698744</span>
											<span class="cell-detail-description">Ext - 8</span>
										</td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>315 6547892</span>
										</td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>pavila@praxair.com</span>
										</td>
										<td class="actions">
											<span data-toggle="modal" data-target="#edita" class="icon mdi mdi-edit"></span>
											<span data-toggle="modal" data-target="#elimina" class="icon mdi mdi-close-circle"></span>
										</td>
									</tr>
									<tr>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>Jhon laguna</span>
											<span class="cell-detail-description">Contacto Logístico</span>
										</td>
										<td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>(57) 1 3698744</span>
											<span class="cell-detail-description">Ext - 9</span>
										</td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>315 3214568</span>
										</td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>jlaguna@praxair.com</span>
										</td>
										<td class="actions">
											<span data-toggle="modal" data-target="#edita" class="icon mdi mdi-edit"></span>
											<span data-toggle="modal" data-target="#elimina" class="icon mdi mdi-close-circle"></span>
										</td>
									</tr>
									<tr>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>Felipe Gomez</span>
											<span class="cell-detail-description">Contacto Administrativo</span>
										</td>
										<td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>(57) 1 3698744</span>
											<span class="cell-detail-description">Ext - 2</span>
										</td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>315 9876582</span>
										</td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>fgomez@praxair.com</span>
										</td>
										<td class="actions">
											<span data-toggle="modal" data-target="#edita" class="icon mdi mdi-edit"></span>
											<span data-toggle="modal" data-target="#elimina" class="icon mdi mdi-close-circle"></span>
										</td>
									</tr>
								</tbody>
							</table>
				        </div>
					</div>
				</div>
			</div>
		</div>
	';

  	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>


	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
	    <script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.wizard();
			});
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);

	echo $vista;
?>

<!-- 
<div class="be-wrapper be-error be-error-404">
	<div class="error-container">
		<div class="error-number">404</div>
		<div class="error-description">Página en construcción.</div>
		<div class="error-goback-text">Este módulo estará próximamente disponible.</div>
	</div>
</div>
 -->

