<?php
	$vista = '';

	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();

	// INFORMACIÓN GENERAL DE LA EMPRESA
	$info_contenido = '
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Daniel Galvis
				<div class="tools">
					<a href="' . BASE_URL . 'clientes/verificacion_socio/"><span class="icon mdi mdi-shield-check"></span></a> 
					<span data-toggle="modal" data-target="#edita" class="icon mdi mdi-edit"></span>
				</div>
					<span class="panel-subtitle">Socio Mayoritario.</span>
			</div>
		</div>
		<table class="table">
			<thead>
				<tr >
					<th>Entidad</th>
					<th style="width:30%;">Próxima Verificación</th>
					<th style="width:5%;"></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td class="cell-detail">
						<span>Lista Clinton</span>
						<span class="cell-detail-description">Revisado - 2017-02-26</span>
					</td>
					<td class="cell-detail">
						<span>2017-06-23</span>
					</td>
					<td class="nexos-txt-success">
						<span class="icon mdi mdi-shield-security"></span>
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<span>Cifin</span>
						<span class="cell-detail-description">Revisado - 2017-02-25</span>
					</td>
					<td class="cell-detail">
						<span>2017-04-14</span>
					</td>
					<td class="nexos-txt-success">
						<span class="icon mdi mdi-shield-security"></span>
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<span>Datacrédito</span>
						<span class="cell-detail-description">Revisado - 2017-01-30</span>
					</td>
					<td class="cell-detail">
						<span>2017-03-05</span>
					</td>
					<td class="nexos-txt-warning">
						<span class="icon mdi mdi-shield-security"></span>
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<span>Basc</span>
						<span class="cell-detail-description">Revisado - 2016-01-30</span>
					</td>
					<td class="cell-detail">
						<span>2017-06-23</span>
					</td>
					<td class="nexos-txt-success">
						<span class="icon mdi mdi-shield-security"></span>
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<span>Policía</span>
						<span class="cell-detail-description">Revisado - 2017-01-30</span>
					</td>
					<td class="cell-detail">
						<span>2017-03-05</span>
					</td>
					<td class="nexos-txt-warning">
						<span class="icon mdi mdi-shield-security"></span>
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<span>Procuraduría</span>
						<span class="cell-detail-description">Revisado - 2016-01-30</span>
					</td>
					<td class="cell-detail">
						<span>2017-06-23</span>
					</td>
					<td class="nexos-txt-success">
						<span class="icon mdi mdi-shield-security"></span>
					</td>
				</tr>
				<tr>
					<td class="cell-detail">
						<span>Bases de Datos</span>
						<span class="cell-detail-description">Revisado - 2016-01-30</span>
					</td>
					<td class="cell-detail">
						<span>2017-06-23</span>
					</td>
					<td class="nexos-txt-success">
						<span class="icon mdi mdi-shield-security"></span>
					</td>
				</tr>
			</tbody>
		</table>
	';
	$vista.= $info->_bootstrap_modal_dialog("info" , "Información de Antecedentes del Socio" , $info_contenido );


  	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	$vista.= $alert->_alert_modal_mod_danger("elimina", "Realmente desea eliminar este elemento?");

	// POPUP DE FORMULARIO DE EDICION DE RIESGO DE COMERCIALIZACION
	$forms = '
		<div class="form-group">
			<label>Documento de identidad:</label>
			<input type="text" placeholder="Número de Documento" class="form-control">
		</div>
		<div class="form-group">
			<label>Nombre:</label>
			<input type="text" placeholder="Nombre" class="form-control">
		</div>
		<div class="form-group">
			<label>Tipo de Vínculo:</label>
			<select class="select2">
				<option value="" selected disabled>Seleccione</option>
				<option value="1">Representante legal</option>
				<option value="2">Socio Mayoritario</option>
				<option value="3">Socio Minoritario</option>
				<option value="4">Socio</option>
				<option value="5">Propietario</option>
			</select>
		</div>
	';

	$form_edita = new Popup();
	$vista.= $form_edita->_form_modal("edita", "Editar Información del Socio" , $forms);

	$form_crea = new Popup();
	$vista.= $form_crea->_form_modal("crea", "Crear Socio de Cliente" , $forms);


	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Socios - Praxair
				<div class="tools">
					<a href="' . BASE_URL . 'clientes/"class="hint--top" data-hint="Volver"><span class="icon mdi mdi-long-arrow-return"></span></a>
					<a href="#" data-toggle="modal" data-target="#crea" class="cell-detail  hint--top"  data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a> 
				</div>
				<span class="panel-subtitle">Muestra los socios que pertenecen a un cliente.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="row">
					<div class="col-sm-3"></div>
					<div class="col-sm-6">
				        <div class="table-responsive noSwipe">
							<table id="table1" class="table table-striped table-hover table-fw-widget">
								<thead>
									<tr class="nexos-encabezado">
										<th>Nombre</th>
										<th style="width:5%;">#</th>
										<th style="width:5%;"></th>
										<th>Empresa</th>
										<th style="width:15%;"></th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>Maria Camila Torres</span>
											<span class="cell-detail-description">Documento - 52666888</span>
										</td>
										<td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>
										<td class="nexos-txt-success">
											<span class="icon mdi mdi-shield-security"></span>
										</td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>Representante Legal</span>
											<span class="cell-detail-description">Praxair</span>
										</td>
										<td class="actions">
											<a href="' . BASE_URL . 'clientes/verificacion_socio/"><span class="icon mdi mdi-shield-check"></span></a> 
											<span data-toggle="modal" data-target="#edita" class="icon mdi mdi-edit"></span>
											<span data-toggle="modal" data-target="#elimina" class="icon mdi mdi-close-circle"></span>
										</td>
									</tr>
									<tr>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>Daniel Galvis</span>
											<span class="cell-detail-description">Documento - 80555999</span>
										</td>
										<td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>
										<td class="nexos-txt-success">
											<span class="icon mdi mdi-shield-security"></span>
										</td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>Socio Mayoritario</span>
											<span class="cell-detail-description">Praxair</span>
										</td>
										<td class="actions">
											<a href="' . BASE_URL . 'clientes/verificacion_socio/"><span class="icon mdi mdi-shield-check"></span></a> 
											<span data-toggle="modal" data-target="#edita" class="icon mdi mdi-edit"></span>
											<span data-toggle="modal" data-target="#elimina" class="icon mdi mdi-close-circle"></span>
										</td>
									</tr>
									<tr>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>Fernando Alayon</span>
											<span class="cell-detail-description">Documento - 19555222</span>
										</td>
										<td class="nexos-txt-success"><span class="mdi mdi-dot-circle icon"></span></td>
										<td class="nexos-txt-warning">
											<span class="icon mdi mdi-shield-security"></span>
										</td>
										<td data-toggle="modal" data-target="#info" class="cell-detail md-trigger">
											<span>Socio</span>
											<span class="cell-detail-description">Praxair</span>
										</td>
										<td class="actions">
											<a href="' . BASE_URL . 'clientes/verificacion_socio/"><span class="icon mdi mdi-shield-check"></span></a> 
											<span data-toggle="modal" data-target="#edita" class="icon mdi mdi-edit"></span>
											<span data-toggle="modal" data-target="#elimina" class="icon mdi mdi-close-circle"></span>
										</td>
									</tr>
								</tbody>
							</table>
				        </div>
					</div>
					<div class="col-sm-3"></div>
				</div>
			</div>
		</div>
	';

  	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>


	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script src="%root_file%lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
	    <script type="text/javascript">
			$.fn.niftyModal(\'setDefaults\',{
				overlaySelector: \'.modal-overlay\',
				closeSelector: \'.modal-close\',
				classAddAfterOpen: \'modal-show\',
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.wizard();
			});
	    </script>
	';

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);

	echo $vista;
?>

<!-- 
<div class="be-wrapper be-error be-error-404">
	<div class="error-container">
		<div class="error-number">404</div>
		<div class="error-description">Página en construcción.</div>
		<div class="error-goback-text">Este módulo estará próximamente disponible.</div>
	</div>
</div>
 -->
