<?php
	$_dbTable = "actividades"; // SIN EL PREFIJO cmx_
	$_jsScripts = "";

	$vista = '';

	/********* POPUPS *********/
	/***** SE INTANCIAN LOS POPUPS DEL MODULO *****/
  	// POPUP DE MUESTRA DE INFORMACION
	$info = new Popup();
	// POPUP DE ALERTA DE CONFIRMACION
	$alert = new Popup();
	// POPUP DE FORMULARIO DE EDICION 
	$form_edita = new Popup();
	// POPUP DE FORMULARIO DE CREACION 
	$form_crea = new Popup();

	/********* FIN POPUPS *********/


	/*** CREACION DE TABLA DE CONTENIDO ***/
	if(isset($this->actividades) && count($this->actividades)){

		/*** SE CREA TABLA DE CONTENIDO ***/
		$table_actividades = '
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<div class="table-responsive noSwipe">
						<table id="table1" class="table table-striped table-hover">
							<thead>
								<tr class="nexos-encabezado">
									<th style="width:10%;">#</th>
									<th>Plantilla</th>
									<th style="width:18%;"></th>
								</tr>
							</thead>
							<tbody>
		';

		$arrayActividades = $this->actividades->getTabla();
		// echo print_r($arrayActividades);
		if ($arrayActividades['rowsData']) {
			foreach ($arrayActividades['rowsData'] as $key => $value) {

				/*** SE FILTRA CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/
				switch ($value["estado"]) {
					case '0':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-danger">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

						$_popupHabilita = $alert->_alert_modal_mod_success( $value[0] , "Realmente desea habilitar este elemento?" , $_dbTable );
						$vista.= $_popupHabilita[0];
						$_jsScripts.=$_popupHabilita[1];

						// se asigna contenudo de la columna de acciones
						$col_action = '
							<td class="actions">
								<a href="#" class="icon"><span id="#habilita_' . $value[0] . '" data-toggle="modal" data-target="#habilita_' . $value[0] . '" class="icon mdi mdi-check-circle"></span></a>
							</td>
						';
						break;
					
					case '1':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-success">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>
						';

						// se genera el formulario de edicion del registro
						// Valor quemado 
						$id_cliente = 1;
						$form_edit_table = '
							<input type="hidden" name="id" value="' . $value[0] . '" class="form-control">
							<input type="hidden" name="id_cliente" value="' . $id_cliente . '" class="form-control">
							<div class="form-group col-xs-12">
								<label>Nombre:</label>
								<input type="text" name="nombre" value="' . $value["nombre"] . '" placeholder="Nombre de la Actividad" class="form-control">
							</div>
							<div class="form-group col-xs-12">
								<label>Descripción:</label>
								<textarea name="descripcion" placeholder="descripcion" class="form-control">' . $value["descripcion"] . '</textarea>
							</div>
							<div class="row"></div>
						';

						$_popupEdita = $form_edita->_form_modal_update($value[0], "Editar Servicio Especial - " . $value[1] , $form_edit_table, $_dbTable);
						$vista.= $_popupEdita[0];
						$_jsScripts.=$_popupEdita[1];


						$_popupElimina = $alert->_alert_modal_mod_danger($value[0], "Realmente desea eliminar este elemento?",$_dbTable);
						$vista.= $_popupElimina[0];
						$_jsScripts.=$_popupElimina[1];

						// se asigna contenido de la columna de acciones
						$col_action = '
							<td class="actions">
								<span id="edita_' . $value[0] . '" data-toggle="modal" data-target="#edita_' . $value[0] . '" class="icon mdi mdi-edit"></span>
								<span id="elimina_' . $value[0] . '"data-toggle="modal" data-target="#elimina_' . $value[0] . '" class="icon mdi mdi-close-circle"></span>
							</td>
						';

						break;

					case '2':
						// se asigna contenido de la columna de estado
						$col_stasus = '
							<td class="nexos-txt-warning">
								<span class="mdi mdi-dot-circle icon"></span>
								<span style="display: none;">' . $value["estado"] . '</span>
							</td>

						';

						// se genera el formulario de edicion del registro
						$form_edit_table = '
							<input type="hidden" name="id" value="' . $value[0] . '" class="form-control">
							<div class="form-group col-xs-12">
								<label>Moneda:</label>
								<input type="text" name="nom_plantilla" value="' . $value["nom_plantilla"] . '" placeholder="Nombre de la Planilla" class="form-control">
							</div>
							<div class="form-group col-xs-12">
								<label>Código:</label>
								<textarea name="descripcion" placeholder="descripcion" class="form-control">' . $value["descripcion"] . '</textarea>
							</div>
							<div class="row"></div>
						';

						$_popupEdita = $form_edita->_form_modal_update($value[0], "Editar Actividad - " . $value[1] , $form_edit_table, $_dbTable);
						$vista.= $_popupEdita[0];
						$_jsScripts.=$_popupEdita[1];


						$_popupElimina = $alert->_alert_modal_mod_danger($value[0], "Realmente desea eliminar este elemento?",$_dbTable);
						$vista.= $_popupElimina[0];
						$_jsScripts.=$_popupElimina[1];


						$_popupHabilita = $alert->_alert_modal_mod_success( $value[0] , "Realmente desea habilitar este elemento?" , $_dbTable );
						$vista.= $_popupHabilita[0];
						$_jsScripts.=$_popupHabilita[1];

						// se asigna contenido de la columna de acciones
						$col_action = '
							<td class="actions">
								<a href="#" class="icon"><span id="#edita_' . $value[0] . '"  data-toggle="modal" data-target="#edita_' . $value[0] . '"  class="mdi mdi-edit"></span></a>
								<a href="#" class="icon"><span id="#habilita_' . $value[0] . '" data-toggle="modal" data-target="#habilita_' . $value[0] . '" class="icon mdi mdi-check-circle"></span></a>
								<span id="elimina_' . $value[0] . '"data-toggle="modal" data-target="#elimina_' . $value[0] . '" class="icon mdi mdi-close-circle"></span>
							</td>
						';

						break;
				}
				/*** FIN DE FILTRO DE CONTENDO DE LA COLUMNA DE BOTONES DE ACCION***/

				// Se maqueta contenido de la tabla 
				$table_actividades.= '<tr>';
				$table_actividades.= $col_stasus;
				$table_actividades.= '
					<td class="cell-detail">
						<span>' . $value["nombre"] . '</span>
						<span class="cell-detail-description">' . $value["descripcion"] . '</span>
					</td>
				';

				// se asigna la columna de acciones
				$table_actividades.=$col_action;
				
				$table_actividades.= '</tr>';
			}

			$table_actividades.= '
								</tbody>
							</table>
						</div>
					</div>
				</div>
			';
		}else{
			echo '<p>no hay registros en esta tabla...</p>';
		}
	}else{
		echo '<p>no hay registros en esta tabla...</p>';
	}
	/*** FIN CREACION DE TABLA DE CONTENIDO ***/


	/**** CONTENIDO DEL MODULO EN PANTALLA ****/
	$vista.='
		<div class="panel panel-border panel-contrast">
			<div class="panel-heading panel-heading-contrast">
				Actividades
				<div class="tools">
					<a href="#" data-toggle="modal" data-target="#crea_' . $_dbTable . '" class="cell-detail  hint--top"  data-hint="Agregar"><span class="icon mdi mdi-plus"></span></a> 
				</div>
				<span class="panel-subtitle">Parametriza las actividades que podrían ser usadas en el desarrollo de un proyecto, estas pueden ser usadas directamente en las actividadesde un proyecto o para establecer una platilla de actividades.</span>
			</div>
			<div class="panel-body xs-mt-15">
				<div class="nexos-messages"></div>
				%content%
				<div class="row">
					<div class="col-sm-12">
					</div>
				</div>
			</div>
		</div>
	';


	/**** CARGA DE ARCHIVOS JS DE LA VISTA ****/
	$vista.= '
	    <script src="%root_file%lib/jquery/jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
	    <script src="%root_file%js/main.js" type="text/javascript"></script>
	    <script src="%root_file%lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>


		<script src="%root_file%lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>

		<!-- js para creacion de data-tables -->
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
		<script src="%root_file%lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
		<script src="%root_file%js/app-tables-datatables.js" type="text/javascript"></script>

		<!-- js para creacion de formularios dinamicos -->
	    <script src="%root_file%lib/fuelux/js/wizard.js" type="text/javascript"></script>
	    <script src="%root_file%js/app-form-wizard.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.min.js" type="text/javascript"></script>
	    <script src="%root_file%lib/select2/js/select2.full.min.js" type="text/javascript"></script>

	    <script src="%root_file%lib/bootstrap-slider/js/bootstrap-slider.js" type="text/javascript"></script>


	    <!-- CARGA DE ARCHIVOS JS DE VENTANAS EMERGENTES -->
	    <script type="text/javascript">
			$(document).ready(function(){
				//initialize the javascript
				App.init();
				App.dataTables();
			});
			$(document).ready(function(){
				//initialize the javascript
				App.wizard();
			});
	    </script>
	';


	/****** CREACION CONTENIDO DE POPUPS ******/

	// CONTENIDO DEL POPUP DE FORMULARIO DE CREACION
	$forms = '
		<div class="form-group col-xs-12">
			<label>Nombre:</label>
			<input type="text" name="nombre" value="" placeholder="Nombre de la Actividad" class="form-control">
		</div>
		<div class="form-group col-xs-12">
			<label>Descripción:</label>
			<textarea name="descripcion" placeholder="descripcion" class="form-control"></textarea>
		</div>
		<div class="row"></div>
	';

	$_popupCrea = $form_crea->_form_modal_simple_insert("crea_" . $_dbTable ,"Crear Actividad" , $forms , $_dbTable );
	$vista.= $_popupCrea[0];
	$_jsScripts.=$_popupCrea[1];


	/****** FIN CREACION CONTENIDO DE POPUPS ******/

	/**** SE ASIGNAN LOS ELEMENTOS DE LA PAGINA  ****/
	$vista = str_replace("%root_file%" , $_layoutParams["ruta_layout"] , $vista);
	$vista = str_replace("%content%" , $table_actividades , $vista);

	// Se asiga codigo JS generado de la tabla de contenido
	$vista.= $_jsScripts;

	// SE PINTA CONTENIDO EN PANTALLA
	echo $vista;

?>
